### ISSUE TITLE
TODO MVC example HTML missing from gh-pages

### ISSUE THREAD

**Issue by liamcurry** [rustwasm/wasm-bindgen#1000]
The link to view the compiled TODO MVC example on [this page](https://rustwasm.github.io/wasm-bindgen/examples/todomvc.html) is broken.

It looks like the `index.html` file is missing in the `gh-pages` branch: https://github.com/rustwasm/wasm-bindgen/tree/gh-pages/exbuild/todomvc

**Comment by alexcrichton** [comment]
cc @jonathanKingston

**Comment by David-OConnor** [comment]
This appears to be fixed now, although the stylesheet associated with the todomvc project is missing.

**Comment by alexcrichton** [comment]
👍
