### ISSUE TITLE
Questions about creating bindings for React

### ISSUE THREAD

**Issue by liamcurry** [rustwasm/wasm-bindgen#1001]
Hi there!

I'm interested in creating bindings for React, but I have some questions. Please feel free to close this issue if there are solutions.

Starting with the basics, React has a function `React.createElement()` that takes 3 parameters: a tag name, property values, and child elements, e.g.:

```js
React.createElement(
    "p",
    { className: "summary" },
    [
        React.createElement("strong", { }, ["Hello"]),
        "World"
    ]
)
```

I've been using [ReasonReact](https://reasonml.github.io/reason-react/) as inspiration, so I'll frame my questions from that point of view:

1. How would properties be implemented in a type-safe way? I think a crude implementation could be something like a hash map of JsValues, but I would prefer something like this: https://github.com/reasonml/reason-react/blob/a46fcda65f0847246a493bb2743f216010679b86/src/ReactDOMRe.re#L90

    So there are props that are optional but strictly typed, and included with user-defined props as well. 

2. How to handle children that can be React elements, strings, or numbers? In BuckleScript (what ReasonML is built on) there is [a keyword called `identity`](https://bucklescript.github.io/docs/en/intro-to-external#special-identity-external) which basically just tells the type checker to treat an object as a different type. I'm not sure if something similar exists in `wasm-bindgen` or if I'm thinking about this the wrong way, but I've done something similar to convert strings/numbers to ReactElements. Example:

```js
// rust_react_util.js
export function identity(thing) { return thing; }
```

```rust
// src/lib.rs
use wasm_bindgen::prelude::*;

extern "C" {
    pub type ReactElement;
}

#[wasm_bindgen(module = "./rust_react_util")]
extern "C" {
    #[wasm_bindgen(js_name = identity)]
    pub fn string(text: &str) -> ReactElement;
}
```

I think it would be useful if something like `#[wasm_bindgen(identity)]` was provided, but maybe I'm missing something and that isn't necessary.

3. ~Is it possible to convert external types to `JsValue`?~ Yes

**Comment by alexcrichton** [comment]
Thanks for the questions!

For (1) I think you may want something that looks like a WebIDL dictionary perhaps? That [looks like this](https://docs.rs/web-sys/0.3.4/web_sys/struct.RequestInit.html) and basically takes the shape of:

* It's just a newtype wrapper around a `js_sys::Object`
* Methods provide types to use for various properties
* You can add setters/getters as necessary
* For custom properties, you could perhaps have a fallback custom setter/getter which just takes a string as the property name.

Implementation-wise this is all done with `Reflect.get` and `Reflect.set`. Would that work for you use case?

For (2) I think you could do something similar in that `ReactElement` is just a newtype wrapper around `JsValue`, so you could provide a custom constructor like:

```rust
impl ReactElement {
    pub fn from_raw(raw: JsValue) -> ReactElement { /* ... */ }
}
```

and then you could do something like `ReactElement::from_raw("foo".into())` maybe?

**Comment by liamcurry** [comment]
Thanks for the response! I think that could work for the properties, and now I'm not actually sure it's even necessary to pass `String`s around as `ReactElement`s.

Now my other issues are:

- I can't get event callbacks to work without using `forget`, otherwise they are destroyed too soon. I assume this would cause memory leaks if used in a lot of components? Here's a code snippet, maybe I'm doing something wrong:

```rust
let props = ::react::Props::new();
let onclick = Closure::wrap(Box::new(|| {
    log("CLICK".into());
}) as Box<Fn()>);
props.set("onClick", onclick.as_ref().into());
onclick.forget();
let button = ::react::create_element("button", Some(&add_props), Box::new(["+".into()]));
```

- React just introduced [Hooks](https://reactjs.org/docs/hooks-intro.html) which are basically just functions for managing state/context. I thought this would be perfect for `wasm-bindgen` since it avoids using classes, but in practice I'm getting errors like this:

![image](https://user-images.githubusercontent.com/77758/47885226-4e548000-de0a-11e8-8acd-72e197d804b5.png)

Apparently React is expecting the hook function call and the element creation to be within the same function like this:

```jsx
function Example() {
  // Declare a new state variable, which we'll call "count"
  const [count, setCount] = useState(0);

  return (
    <div>
      <p>You clicked {count} times</p>
      <button onClick={() => setCount(count + 1)}>
        Click me
      </button>
    </div>
  );
}
```

So for this to work Rust would have to export a function like that, which I'm not sure is possible? The alternative then is to use classes, which seems like it could be equally difficult.

I'm starting to think that maybe my time would be better spent on building with vanilla JS rather than trying to jury-rig React components with Rust. I don't mind using vanilla JS, but my thinking with React is that it would be a good gateway for web developers who would otherwise turn to things like ReasonML/Elm/Purescript. ReasonReact is nice in particular because they make it really easy to write bindings for existing JS React components and use all the build/dev tools available to the React ecosystem.

Thanks again! Feel free to close this issue.

**Comment by alexcrichton** [comment]
Ah sorry you're having difficulties with things, it's true though that this is still somewhat early days so not all the idioms have been codified yet! Working with closures is indeed a sticking point where it's not nearly as nice as JS closures. Eventually when we have `WeakRef` to automatically free memory in Rust I think this'll be much nicer (as you won't have to manually free nor will we need to connect to `Drop`).

I'm not sure what you mean by the react hooks, but it sounds like your use case may want to hold off for now with wasm-bindgen in that it wasm-bindgen may not be quite ready yet. It's great to have these issues though! I at least like to have a good "finger to the pulse" about the common difficulties of using wasm-bindgen and such.

Thanks so much for taking the time to write all this up and kick the tires on wasm-bindgen!
