### ISSUE TITLE
WorkerGlobalScope::self requires a WorkerGlobalScope ref

### ISSUE THREAD

**Issue by aep** [rustwasm/wasm-bindgen#1003]
WorkerGlobalScope::self should probably not be an instance method, otherwise there's no way to get  the global scope WorkerGlobalScope

**Comment by alexcrichton** [comment]
Thanks for the report! For getting the global object we currently provide [`js_sys::global`](https://docs.rs/js-sys/0.3.4/js_sys/fn.global.html), would that work for your use case?

**Comment by aep** [comment]
thanks,

yes it probably would (i'm not using WorkerGlobalScope at all now because there's no way to construct a Function for onmessage)

but WorkerGlobalScope::self  is still a confusing interface i think. what's it supposed to be for?

**Comment by alexcrichton** [comment]
Oh so for `onmessage` you can use `Closure<T>` and its `AsRef<JsValue>` implementation ([a longer explanation here](https://rustwasm.github.io/wasm-bindgen/examples/closures.html)), but for the API itself it's purely generated from WebIDL, namely [this line](https://github.com/rustwasm/wasm-bindgen/blob/0d5f5147093746ec209277fc0c879329c2c13188/crates/web-sys/webidls/enabled/WorkerGlobalScope.webidl#L18)

**Comment by aep** [comment]
oh i didnt realize that, thanks!

this IDL is really strange, but maybe its just me not understanding javascript.  The IDL clearly says its a member function as you pointed out, but the docs refer to the global object https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/self
this is why i got confused and thought bindgen isnt generating the right thing.

closing this one, since probably not a bindgen bug.
