### ISSUE TITLE
webidl: Add a method of whitelisting an API as not mutating its byte slice argument

### ISSUE THREAD

**Issue by alexcrichton** [rustwasm/wasm-bindgen#1005]
Spawned off from https://github.com/rustwasm/wasm-bindgen/issues/978, we currently [pessmize all slices to be mutable](https://github.com/rustwasm/wasm-bindgen/blob/0d5f5147093746ec209277fc0c879329c2c13188/crates/webidl/src/util.rs#L75) when passed to JS. This conservative decision is required for correctness, but we typically know on a one-off basis that the mutable borrow isn't actually necessary.

We should add a specific method to whitelist particular APIs and switch the to using an immutable slice instead of a mutable one!

**Comment by RReverser** [comment]
I've just found that `TextDecoder::decode_with_u8_array{_and_options}` requires a mutable slice. Sounds relevant to this issue? I'll be happy to send a PR, but what do I need to do to whitelist these methods?

**Comment by alexcrichton** [comment]
@RReverser just to confirm, but do you mean it *doesn't* need a mutable slice? (it looks like it already takes a mutable slice)

**Comment by RReverser** [comment]
Yeah, I'm saying that I found that it currently requires mutable slice in the Rust API, but it shouldn't.

**Comment by alexcrichton** [comment]
Ah yes, then indeed this is the right issue! Currently a whitelist isn't implemented, though, that would need to be done first. (that's what this issue is about)

**Comment by RReverser** [comment]
Ah sorry, I misread, I thought the issue was merely about finding and marking methods that need to accept immutable slices.

**Comment by chinedufn** [comment]
@alexcrichton where might one start looking in order to implement the whitelist? Any tips / guidance for diving in here?

---

Background:

You end up running into minor inconveniences very frequently when working on WebGL applications since you're using a bunch of these APIs that require mutable slices very frequently.

Nothing too, too painful - just inconvenient.

---

So if this is do-able for a beginner contributor I'd love to take a look!

Thanks!

**Comment by alexcrichton** [comment]
Sure yeah! Here's at least one way I think this could be implemented today:

* First up, probably some cleanup needs to be done to `enum IdlType` because everything becomes mutable slices. For example `Uint8ArrayMut` probably isn't needed any more as opposed to `Uint8Array`
* Next, We'll want to add a variant that represents immutable slices. Perhaps booleans on the existing arrays, or perhaps new variants. After an enum variant is added appropriate places are fixed in compilation to ensure shared slices instead of mutable slices are used in Rust.
* Finally, we'll want to actually generate these new types when generating bindings. More on that now...

Digging around again, the main point of creation of the mutable type vs immutable happens [here](https://github.com/rustwasm/wasm-bindgen/blob/6b13a865cba1a3b7794a2cfd879d7b9854a8a962/crates/webidl/src/util.rs#L436). I think we'll want to change that to something like:

```rust
let idl_type = arg.ty.to_idl_type(self);
let idl_type = maybe_adjust(idl_type, id);
idl_args.push(idl_type);
```

The `maybe_adjust` method would implement a whitelist that would take a look at the `id`, and if it's `OperationId::Operation(Some(s))` then it'll check `s` against a whitelist and convert any mutable slice into an immutable slice. (or something like that)

And I think that may be good enough to start here?

**Comment by fitzgen** [comment]
One thing that is not clear to me is how we intend to deal with semver here -- changing an `&mut [u8]` to a `&[u8]` is a breaking change, yeah? I'd prefer not to require a breaking release for web-sys...

**Comment by alexcrichton** [comment]
I'm personally hoping that because `&mut [u8]` coerces to `&[u8]` we'll be able to get by without breaking changes, but if that doesn't end up being the case then we'll definitely want to batch these up and do a more thorough review

**Comment by chinedufn** [comment]
Super helpful guidance thanks! Should be taking a look later this week.

**Comment by alexcrichton** [comment]
@fitzgen FWIW in terms of literal code, I think this is a non-breaking change, this compiles on the playground:

```rust
fn a(_: &[u8]) {}


fn b() {
    a(&mut Vec::new());
    a(&mut []);
    a(&mut [1]);
    a(&mut [1;2]);
    a(&mut [3][..]);
}
```

If, however, someone did something like `let x: fn(&mut [u8]) = ...` then that could be a problem, but I think we can probably land whitelisting without worrying too much about that.

**Comment by fitzgen** [comment]
SGTM :+1:

**Comment by dakom** [comment]
It seems that floats such as `uniform2fv_with_f32_array()` are whitelisted, while ints such as `uniform2iv_with_i32_array()` are not.

Is this intentional? If not - is the fix only to add to this list: https://github.com/rustwasm/wasm-bindgen/blob/master/crates/webidl/src/lib.rs#L177 ?

**Comment by alexcrichton** [comment]
Just hasn't been done yet, PRs are always welcome to update the whitelist!
