### ISSUE TITLE
Using #[wasm_bindgen(constructor)] for a module that is a type

### ISSUE THREAD

**Issue by liamcurry** [rustwasm/wasm-bindgen#1006]
I am trying to use an NPM module that only has 1 default export that is a type. Here is the JS code I'm trying to produce:

```js
import ScatterEos from "scatterjs-plugin-eos";
const eos = new ScatterEos();
```

Here are bindings I thought might work:

```rust
#[wasm_bindgen(module = "scatterjs-plugin-eosjs")]
extern "C" {
    pub type EosPlugin;

    #[wasm_bindgen(constructor)]
    pub fn new() -> EosPlugin;
}
```

But this is generating an import statement like this:

```js
import { EosPlugin } from 'scatterjs-plugin-eosjs';
```

Is there anyway to get this working without custom JS glue code?

**Comment by Pauan** [comment]
Not sure how well it will work with CommonJS, but with ES6 modules these two are equivalent:

```js
import ScatterEos from "scatterjs-plugin-eos";
import { default as ScatterEos } from "scatterjs-plugin-eos";
```

So maybe something like this would work?

```rust
#[wasm_bindgen(module = "scatterjs-plugin-eosjs")]
extern "C" {
    #[wasm_bindgen(js_name = default)]
    pub type EosPlugin;

    #[wasm_bindgen(constructor)]
    pub fn new() -> EosPlugin;
}
```

**Comment by alexcrichton** [comment]
Thanks for the report! What @Pauan mentioned *should* work but it looks like it's a bug in wasm-bindgen that `js_name` isn't respected on types just yet (I'll work to fix soon!).

I think we could also, in the future, add a way of indicating that something imported from a module is the default object, so it wouldn't have to be as "janky" as `js_name = default`

**Comment by alexcrichton** [comment]
Ah I forgot that if you use `js_name` to rename a type then you'll also need `js_class` on all the method declarations (I've sent a doc clarification in https://github.com/rustwasm/wasm-bindgen/pull/1011). If it's changed to `#[wasm_bindgen(constructor, js_class = default)]` I think this should make some more progress, @liamcurry could you try that out?

**Comment by mvlabat** [comment]
Hi everyone! Do I understand it right, `#[wasm_bindgen(js_name = default)]` applied to types doesn't work yet?

```
#[wasm_bindgen(module = "MyClass")]
extern "C" {
    #[wasm_bindgen(js_name = default)]
    type MyClass;
}
```

As I can see, it generates the following glue code:
```
import { default } from '...';
```
which doesn't look right.

**Comment by alexcrichton** [comment]
@mvlabat ah yeah that looks problematic! I think in that case we could special case the import `default` and always use `default as Foo` perhaps?

**Comment by Pauan** [comment]
@alexcrichton ES6 imports/exports allow any identifier to be imported/exported, including keywords:

```js
const foo = 5;
export { foo as if };
export { foo as null };
```

```js
import { if as foo, null as bar } from "...";
```

So rather than special-casing `default`, instead it should [check if the identifier is invalid (e.g. a keyword)](http://www.ecma-international.org/ecma-262/6.0/#sec-reserved-words), and if so it then it will rename it using `as`.

Since `default` is a keyword, it will also be fixed as a consequence of that.
