### ISSUE TITLE
RuntimeError when using functions that return futures

### ISSUE THREAD

**Issue by liamcurry** [rustwasm/wasm-bindgen#1007]
I'm trying to create reusable functions for `fetch` API calls but I'm running into errors like this:

![image](https://user-images.githubusercontent.com/77758/47948226-24cb4f80-df03-11e8-98a1-a8bce10d91b6.png)

Here is an example function:

```rust
pub fn get_info(node: &str) -> impl Future<Item = JsValue, Error = JsValue> {
    let mut opts = RequestInit::new();
    opts.method("GET");
    opts.mode(RequestMode::Cors);

    let mut url: String = node.to_owned();
    url.push_str("/v1/chain/get_info");

    let request = Request::new_with_str_and_init(url.as_str(), &opts).unwrap();
    let window = web_sys::window().unwrap();
    let request_promise = window.fetch_with_request(&request);

    JsFuture::from(request_promise)
}

// Then if I call it later I see the error
get_info("https://localhost:8889");
```

If I change the return type to `Promise` then it works, but I would prefer to use futures for type safety and `await`.

Side note: please let me know if these kinds of issues are useful or if I should wait for a more stable release. I've opened up a couple issues recently and I definitely don't want to spam you all if it isn't wanted. Thanks!

**Comment by alexcrichton** [comment]
Thanks for the report! This definitely seems like a bug in wasm-bindgen, and the issue reports are greatly appreciated! I'll try to dig into this today and see if I can hunt this down

**Comment by alexcrichton** [comment]
Hm ok in some testing I can't get it to fault early on, so I may need a service to run as well? Do you perhaps have a standalone example I could pull down and test out?

**Comment by liamcurry** [comment]
After a reformat I'm no longer seeing this issue so I think it was probably an issue with my setup. Thanks for the response!
