### ISSUE TITLE
`js_name = ...` attribute not working on exported types

### ISSUE THREAD

**Issue by Diggsey** [rustwasm/wasm-bindgen#1010]
The documentation indicates that this should work, but my type still gets exported as `JsProject` rather than `Project`.

I've tried putting the attribute everywhere that might make sense, and nowhere seems to have any effect:

```rust
#[wasm_bindgen(js_name = Project)]
pub struct JsProject(Project);

#[wasm_bindgen(js_name = Project)]
impl JsProject {
    #[wasm_bindgen(js_name = Project, constructor)]
    pub fn new() -> JsProject {
        JsProject(Project::new())
    }
}
```

**Comment by alexcrichton** [comment]
While never explicitly supported it's something we should definitely support! I've implemented this in https://github.com/rustwasm/wasm-bindgen/pull/1012

**Comment by Diggsey** [comment]
Awesome, thanks!
