### ISSUE TITLE
How to index js array

### ISSUE THREAD

**Issue by JoeHowarth** [rustwasm/wasm-bindgen#1016]
This seems like a simple thing I'm missing, but how do you index into a js array?
``` rust 
fn foo(arr: js_sys::Array) {
     let a = arr[0]   <--- or something
}
```

**Comment by fitzgen** [comment]
Right now, you can use `Reflect::get`: https://docs.rs/js-sys/0.3.4/js_sys/struct.Reflect.html#method.get

We may want to add a specific method for this, however.

**Comment by JoeHowarth** [comment]
Ahh, this was what I missed!
Thanks!

**Comment by ArhanChaudhary** [comment]
Note to future readers that specific methods for this [have been implemented](https://github.com/rustwasm/wasm-bindgen/pull/1749).
