### ISSUE TITLE
Implement RFC 5: structural by default and Deref inheritance

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-bindgen#1018]
* https://github.com/rustwasm/rfcs/pull/5
* https://rustwasm.github.io/rfcs/005-structural-and-deref.html

**Comment by alexcrichton** [comment]
I'm currently working on this!

**Comment by alexcrichton** [comment]
Implementation: https://github.com/rustwasm/wasm-bindgen/pull/1019
