### ISSUE TITLE
Support `Closure<FnOnce()>`

### ISSUE THREAD

**Issue by alexcrichton** [rustwasm/wasm-bindgen#1022]
Currently the `Closure` type only supports `Fn` and `FnOnce`. It'd be really slick though if we could also support `FnOnce` in an ergonomic fashion, ideally one that automatically does all the memory management for you!

**Comment by Pauan** [comment]
For reference, the way that stdweb handles this is that it provides a `Once` wrapper, which allows for sending `FnOnce` closures to JS:

```rust
// FnOnce closure
let x = || {
    ...
};

// Wrap in Once
let x = Once(x);

// Send to JS
js!( ... @{x} ... )
```

The semantics are that when the `FnOnce` is called from JavaScript, it will automatically clean up the Rust memory for the closure (and if it's called a second time it errors).

It can also be manually cleaned up from JS (without calling it), by using `x.drop()` (in JS). I'm not sure if that will be useful for wasm-bindgen or not (being able to cleanup from Rust is probably good enough).

**Comment by alexcrichton** [comment]
I think this was effectively done in https://github.com/rustwasm/wasm-bindgen/pull/1281, so closing.
