### ISSUE TITLE
feature request: optimize destruction arrays on js side

### ISSUE THREAD

**Issue by MaxGraey** [rustwasm/wasm-bindgen#1031]
When generate glue code for slices/vectors using array destructors like:
```js
const [ptr0, len0] = passArray8ToWasm(arg0);
const retptr = globalArgumentPtr();
```
Part `const [ptr0, len0]` used iterators under the hood. To avoid that we can use this approach:
```js
const { 0: ptr0, 1: len0 } = passArray8ToWasm(arg0);
...
```
Or better just use object destruction instead array destruction by design and without this hack

More details: https://twitter.com/_developit/status/1057636803354648582

**Comment by alexcrichton** [comment]
Oh an excellent point! We can probably go one step further and remove the array completely :)

https://github.com/rustwasm/wasm-bindgen/pull/1033
