### ISSUE TITLE
Methods that take a WebIDL `sequence` argument are missing

### ISSUE THREAD

**Issue by RSSchermer** [rustwasm/wasm-bindgen#1038]
Some methods seem to be missing from the `WebGl2RenderingContext`:

- `invalidateFramebuffer`
- `invalidateSubFramebuffer`
- `drawBuffers`
- `transformFeedbackVaryings`
- `getUniformIndices`
- `getActiveUniforms`

What they all seem to have in common is that they all take a WebIDL `sequence` as an argument. I've not checked other APIs, so I'm not sure whether or not this affects other APIs besides the WebGl2 API.

**Comment by LordPython** [comment]
I just noticed this when looking at the SubtleCrypto api, which has the same problem:

- `generateKey`
- `deriveKey`
- `importKey`
- `unwrapKey`

are all missing, and all have `sequence` parameters.

**Comment by alexcrichton** [comment]
Er sorry for taking awhile to get back to this! I believe this is [handled here](https://github.com/rustwasm/wasm-bindgen/blob/7768328fc49962c9996d80a72bc20b16856104ce/crates/webidl/src/idl_type.rs#L545) where we don't handle it right now. I suspect that we probably want to return either an `Array` or some sort of Rust-defined iterator here perhaps. It'd definitely be nice to bind these!

This'll need some work to figure out what the best interface is, an implementation, and then a PR!

**Comment by derekdreery** [comment]
Relevant webidl spec: https://heycam.github.io/webidl/#es-sequence

**Comment by derekdreery** [comment]
I've added a patch to use `Array`, because I think all sequences are converted to arrays in ECMAScript. PR: https://github.com/rustwasm/wasm-bindgen/pull/1152. I'm going to see if I get any errors with it like this.

**Comment by derekdreery** [comment]
Update: I've re-read [the spec](https://heycam.github.io/webidl/#es-sequence) and it seems ambiguous. I think `Array` is a safe option.

**Comment by Pauan** [comment]
Rather than guessing, we should test and see what the browsers actually do.

**Comment by derekdreery** [comment]
I've experimented with DocumentOrShadowRoot elementsFromPoint in the console window (Firefox):

```text
$ temp0 = document.elementsFromPoint(1.0, 1.0);
Array [ html ]
$ temp0 instanceof Array
true
```

**Comment by alexcrichton** [comment]
@derekdreery it may be worthwhile testing a few sequences in argument position too, I think it makes sense that coming out they're an array, but going in it may be anything iterable

**Comment by derekdreery** [comment]
@alexcrichton that's what I thought too, they might accept stuff that's iterable. I'll do some tests.

**Comment by derekdreery** [comment]
Here's a test case showing that for at least indexedDB, iterables are supported in argument position:

```js
const keys = ['first', 'second'];
var iterable = {
    [Symbol.iterator]() {
        let idx = 0;

        return {
            next: function() {
                if (idx >= keys.length) {
                    return { done: true };
                }
                idx += 1;
                return {value: keys[idx-1], done: false};
            }
        };
    }
}

var request = indexedDB.open("test2", 1);
request.onupgradeneeded = function(evt) {
    var db = request.result;
    var store = db.createObjectStore("test", {keyPath: iterable});
    console.log(store.keyPath);
}

request.onerror = function(evt) {
    console.warn("Error");
    console.warn(evt);
}

request.onsuccess = function(event) {
    console.log("js Success");
}
```

How should we handle this in web-sys? Should we emit different types depending on whether the sequence is in argument position, or return position?

**Comment by alexcrichton** [comment]
Fixed in https://github.com/rustwasm/wasm-bindgen/pull/1152!
