### ISSUE TITLE
.d.ts for _bg module

### ISSUE THREAD

**Issue by likr** [rustwasm/wasm-bindgen#1040]
I'm trying to access wasm memory from TypeScript like this example.
https://rustwasm.github.io/wasm-bindgen/reference/types/pointers.html

But, the TypeScript compiler shows an error because the type definition for _bg module does not exist.

Currently, I manually added following .d.ts file to avoid the error.
(@types/webassembly-js-api is needed.)

```
import 'webassembly-js-api';

export var memory : WebAssembly.Memory;
```

I think it is better to automatically generate .d.ts file for _bg module.
Or, is there any other way to solve this?

**Comment by alexcrichton** [comment]
Oops yeah I forgot about importing memory! Definitely something we should emit `.d.ts` files for!

We could also go ahead and emit a `.d.ts` file for the entire wasm module, and it would be pretty easy to do so as we've got the types of all the exports already!
