### ISSUE TITLE
Clarification: export {...} vs export "C" {...}

### ISSUE THREAD

**Issue by slnovak** [rustwasm/wasm-bindgen#1042]
Hello!

I've been going through the documentation and came across a small discrepancy. When using `#[wasm_bindgen]` to annotate functions to be imported from JS, I've seen two formats:

In [examples/hello_world/src/lib.rs](https://github.com/rustwasm/wasm-bindgen/blob/d4297ad2d391aa93c685127616c46adfd1987f8a/examples/hello_world/src/lib.rs#L5-L8):
```
#[wasm_bindgen]
extern "C" {
    fn alert(s: &str);
}
```

In [guide/src/whirlwind-tour/basic-usage.md](https://github.com/rustwasm/wasm-bindgen/blame/d4297ad2d391aa93c685127616c46adfd1987f8a/guide/src/whirlwind-tour/basic-usage.md#L45-L48):

```
#[wasm_bindgen]
extern {
    fn alert(s: &str);
}
```

For a developer that is relatively new to Rust + WebAssembly, this can be slightly confusing. Is there a preferred annotation and can the documentation be updated to reflect this?

Thanks for piecing together an awesome guide!

**Comment by alexcrichton** [comment]
Oh dear, thanks for pointing out the discrepancy! Those are two equivalent snippets, and rustfmt prefers the `"C"` but my fingers are taking a long time to change to type it! We should definitely update all documentation to favor the rustfmt idiom of adding `"C"` everywhere.

**Comment by slnovak** [comment]
Thank you!!
