### ISSUE TITLE
wasm_bindgen::memory(), Float32Array wrapping and endianness

### ISSUE THREAD

**Issue by djozis** [rustwasm/wasm-bindgen#1049]
About a month ago I submitted a change to the webgl example to remove the copy by wrapping the memory buffer with a Float32Array, currently here: https://github.com/rustwasm/wasm-bindgen/blob/5b76a6291e5083b24f96b96a4939f18ec9d9d4df/examples/webgl/src/lib.rs#L47

Upon further learning, my understanding is now that Float32Array is platform endian, but wasm is little endian, so I suspect that means that code would behave incorrectly on big endian platforms. Is that right? If so, what would be the best way to fix that?

Is there something better than to detect the platform endianness, and use something like the byteorder crate to create a buffer which is platform endian? Detection by means of something like this: https://stackoverflow.com/a/19606031/10676406

**Comment by alexcrichton** [comment]
Oh dear, thanks for the report! I'll be honest in that I have no idea what the impact here would mean or what it means to interoperate wasm and big-endian platforms. They're so rare though this is unlikely to really come up that often in practice.

**Comment by djozis** [comment]
I read this [this thread](https://github.com/WebAssembly/design/issues/786) and my take-away was that wasm can run on big-endian platforms with endianness-swapping. So since the memory is little-endian but the typed arrays are platform-endian, then I theorize that a typed array wrapping a wasm memory buffer would be interpreted with the incorrect byte order on a big-endian platform. I don't have a big-endian platform to verify it, so maybe I'm missing something. Maybe it's a more theoretical issue due to the rarity of big-endian platforms. I thought I should at least say something for consideration if wasm memory buffer wrapping with typed arrays is intended to be an idiomatic practice (it's now in the example above), and if wasm theoretically should work on big-endian platforms.

**Comment by alexcrichton** [comment]
Is there a way we could fix this by creating typed arrays that internally do byte swapping? Otherwise seem totally reasonable to me to add some documentation!

**Comment by Pauan** [comment]
@alexcrichton Sure, it's possible to create typed array wrappers that will detect whether the platform is big or little endian, and then if it's big endian they will auto-swap the bytes.

This does have some performance hit (and it increases the file size), but the performance hit is only for big endian platforms, and perhaps the file size is small enough that it's acceptable.

Personally, I think it's fine to ignore big endian, for the same reasons that the WebAssembly team decided that mandatory little endian is fine. So the only changes would be to the documentation.

**Comment by alexcrichton** [comment]
I agree that this is a rare and pretty esoteric concern, so if we do fix it then it may be best to place behind a flag like `--big-endian-compatible`

**Comment by alexcrichton** [comment]
I'm gonna close this for now as I don't think this is a problem for wasm as-is today, but if it comes up we can definitely add a fix!
