### ISSUE TITLE
Convert from struct to JsValue

### ISSUE THREAD

**Issue by schulzch** [rustwasm/wasm-bindgen#1052]
Due to current limitations with exposing a `Vec<Vec<T>>` I thought I could work around this by wrapping the following signature
```rust
pub fn cluster<P: MetricSpace>(&self, points: &[P]) -> Vec<Cluster>
```
using
```rust
pub fn cluster(&self, js_points: js_sys::Array) -> js_sys::Array {
    use wasm_bindgen::JsCast;
    // Convert from JS.
    let mut points = Vec::<JsPoint>::new();
    js_points.for_each(&mut |obj, _idx, _arr| points.push(obj.dyn_into::<JsPoint>().unwrap()));
    // Run the algorithm.
    let clusters = self.inner.cluster(&points);
    // Convert to JS.
    let js_clusters = Array::new();
    for cluster in clusters.iter() {
        let js_cluster = Array::new();
        for assignment in cluster {
            //js_cluster.push(assignment); //TODO: this does not work/convert to JsValue
        }
        js_clusters.push(&js_cluster);
    }
    js_clusters
}
```
However, I can not find a way for converting the `Assignment` struct into a `JsValue`. Is it impossible or did I overlook documentation?

**Comment by alexcrichton** [comment]
Thanks for the report! There's two main options of how to do this, one is to tag `Assignment` with `#[wasm_bindgen]` and then call `.into()`, and the other is to implement `#[derive(Serialize)]` for `Assignment` and then use `JsValue::from_serde`. Would one of those work in this case?

**Comment by alexcrichton** [comment]
Oh if you want a raw JS record with the fields, then you'll want to use the Serde-based approach. The records using `.into()` are wrapping Rust values so they'll have accessors for methods, but they don't have the bare fields themselves. In this case though `#[derive(Serialize)]` should do the trick!

**Comment by schulzch** [comment]
Thanks - somehow it is always the last variant ;)
This looks a lot better:
```json
[ [ { index: 1, label: 1, category: 'Core' },
    { index: 2, label: 1, category: 'Core' },
    { index: 1, label: 1, category: 'Core' },
    { index: 3, label: 0.58578646, category: 'Core' } ],
  [ { index: 0, label: 1, category: 'Noise' } ] ]
```

For the sake of completeness, here is the wrapper:
```rust
    pub fn cluster(&self, js_points: JsValue) -> JsValue {
        let points: Vec<JsPoint> = js_points.into_serde().unwrap();
        let clusters = self.fuzzy_dbscan(&points);
        JsValue::from_serde(&clusters).unwrap()
    }
```

For that method:
```rust
fn fuzzy_dbscan<P: MetricSpace>(&self, points: &[P]) -> Vec<Cluster> { ... }
```

And the specialized struct (since I can not export the trait):
```rust
#[cfg(all(target_arch = "wasm32", target_os = "unknown"))]
#[derive(Deserialize)]
pub struct JsPoint {
    x: f64,
    y: f64,
}

#[cfg(all(target_arch = "wasm32", target_os = "unknown"))]
impl MetricSpace for JsPoint {
    fn distance(&self, other: &Self) -> f32 {
        ((other.x - self.x).powi(2) + (other.y - self.y).powi(2)).sqrt() as f32
    }
}
```
