### ISSUE TITLE
Assert all #[wasm_bindgen] attributes are used by default

### ISSUE THREAD

**Issue by alexcrichton** [rustwasm/wasm-bindgen#1056]
An off-by-default option for this was introduced in https://github.com/rustwasm/wasm-bindgen/pull/1055, and it's a breaking change to turn it on, so this tracks enabling it eventually!

**Comment by RReverser** [comment]
This one can probably be closed now too.

**Comment by hamza1311** [comment]
Closing it as per previous comment
