### ISSUE TITLE
Errors with "manual" compilation

### ISSUE THREAD

**Issue by P-E-Meunier** [rustwasm/wasm-bindgen#1074]
I can now compile Rust to WASM using wasm-bindgen, with rustc called by cargo. This even works when I call rustc manually from a terminal. However, I've been failing to compile wasm-bindgen to WASM using carnix (https://nixos.org/nixpkgs/manual/#compiling-rust-crates-using-nix-instead-of-cargo) instead of cargo.

The following command doesn't produce the same results when called in a nix builder and in a terminal, and I don't understand why:

```
rm -Rf target
mkdir -p target/deps
rustc --crate-name wasm_bindgen src/lib.rs --target wasm32-unknown-unknown --crate-type lib \
  -C debuginfo=2 -C codegen-units=1 -C metadata=146444cfc827e146 \
  -C extra-filename=-146444cfc827e146 --cfg 'feature="std"' --cfg 'feature="spans"'  \
  --cfg 'feature="default"' --out-dir target/deps --emit=dep-info,link -L dependency=target/deps \
  --extern wasm_bindgen_macro=/nix/store/jhq7z1f7v7982p3b1wkx3360js4z8kkv-rust_wasm-bindgen-macro-0.2.28/lib/libwasm_bindgen_macro-422c4f93025079cd.so \
  --cap-lints allow
```

The output of running this command with `RUST_LOG=debug` shows only marginal differences (involving only times in microseconds, after removing timestamps).

- If I run this in a terminal, I get a perfectly usable `libwasm_bindgen-146444cfc827e146.rlib`, which I can then link with a "Hello, world" crate".
- However, when run in nix-build, I get a different `libwasm_bindgen-146444cfc827e146.rlib` (the WAT is different). I can still compile and link my "Hello world" crate, but then running `wasm-bindgen` on the result yields "thread 'main' panicked at 'assertion failed: idx >= self.imports', /path/to/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-wasm-interpreter-0.2.28/src/lib.rs:290:9".

I know I'm the only one to blame here, for not using standard tools, but the pipeline the NixOS community has been developing around Carnix is starting to be quite usable, and makes it easy and fast to deploy Rust code to a server (using tools like NixOps).

I guess this is more a question than a bug report, but what steps can I take to debug this? I've tried using `env -i`, comparing the debugging outputs, but I'm quite stuck.

**Comment by P-E-Meunier** [comment]
The bug is that two invocations of rustc with the same files yield different results, one of which is not usable.
Could there be for instance files (shared libraries? data?) that wasm_bindgen_macro is trying to access and fails silently in one of the contexts for some mysterious reason? Maybe an environment variable?

**Comment by P-E-Meunier** [comment]
Also, I'm sort of stuck because since RUST_LOG=debug produces the same output in both instances, I don't know what to use to debug.

**Comment by alexcrichton** [comment]
There's various environment variables that are read, but afaik no shared library state is used. Can you minimize the difference between the two environments to see what change causes the issue?

**Comment by TitanThinktank** [comment]
process didn't exit successfully: `rustc -vV` (exit code: 127)
--- stderr
/home/user1/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc: symbol lookup error: /home/user1/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/librustc_save_analysis-96d845528e8efb0e.so: undefined symbol: _ZN4core3fmt3num53_$LT$impl$u20$core..fmt..LowerHex$u20$for$u20$u32$GT$3fmt17h51d6c265e3c71e67E

The command used was :
> cargo build --target wasm32-unknown-unknown

any idea whats that, this is new error today, getting it for the same newbie examples that compiled few days back.

**Comment by TitanThinktank** [comment]
process didn't exit successfully: `rustc -vV` (exit code: 127)
--- stderr
/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc: symbol lookup error: /home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/../lib/../lib/librustc_save_analysis-96d845528e8efb0e.so: undefined symbol: _ZN4core3fmt3num53_$LT$impl$u20$core..fmt..LowerHex$u20$for$u20$u32$GT$3fmt17h51d6c265e3c71e67E

The command used was :
> cargo build --target wasm32-unknown-unknown

any idea whats that, this is new error today, getting it for the same newbie examples that compiled few days back.

**Comment by TitanThinktank** [comment]
The above error i mentioned , its gone now, probably since Rustlang got a new update which means new features must be getting in the nightly for the next release. But the weird errors are gone for now after i updated cargo nightly.

but there may be new problem now, the command "wasm-bindgen sample.wasm –no-modules –out-dir ." is not working, give errror "Invalid arguments."

Good i didnt start new issue here, since i dont have much idea what i am doing, will take time to learn all these cryptic steps, but am deeply committed to ruin JavaScript, and will reach there by any means possible.
:-)

**Comment by alexcrichton** [comment]
I'm gonna close this since I think it's a bit stale, but feel free to resubmit if it resurfaces!
