### ISSUE TITLE
CLI: way to change the file names?

### ISSUE THREAD

**Issue by David-OConnor** [rustwasm/wasm-bindgen#1076]
Is there a way to specify custom file names for the output created by the CLI? Currently, it seems to be hard-locked to the package name (eg packagename.d.ts, packagename.js, packagename_bg.wasm) What I'm tracking:
```
    -h --help
    --out-dir DIR
    --nodejs
    --browser
    --no-modules
    --no-modules-globa
    --typescript
    --no-typescript
    --debug
    --no-demangle
    --keep-debug
    --remove-name-sect
    -V --version
```
It would be nice to have a --name option that would replace 'packagename' in my example above. Also of note, the descriptions for --browser and --no-modules are a bit unclear.

**Comment by alexcrichton** [comment]
Thanks for the report! This is definitely just an option we haven't had a chance to implement yet, it should be fine to add a `--name` option at any time! Would you be interesting in sending a PR for this?

**Comment by David-OConnor** [comment]
I'll poke around and see what I can come up with

**Comment by alexcrichton** [comment]
Ok great, thanks!

As some pointers:

* [The option would probably go in this file](https://github.com/rustwasm/wasm-bindgen/blob/master/crates/cli/src/bin/wasm-bindgen.rs)
* [The usage would replace all uses of `file_stem` in this file](https://github.com/rustwasm/wasm-bindgen/blob/master/crates/cli-support/src/lib.rs)

And I think that'd roughly be it?

**Comment by David-OConnor** [comment]
Looks to be the case. Forked and made the changes, but not sure how to build or test. If I run `cargo build` from the main crate, I get the error: `error[E0635]: unknown feature `wasm_import_module``

**Comment by David-OConnor** [comment]
Submitted the PR, but unable to test due to a version mismatch I'm not sure how to fix when using a local v of bindgen. Also of note: can't get the top-level crate to build on my nightly setup due to this error: ```error[E0635]: unknown feature `wasm_import_module```.

**Comment by David-OConnor** [comment]
I suck at git; deleted my fork and started again; new PR submitted.

**Comment by alexcrichton** [comment]
Added in https://github.com/rustwasm/wasm-bindgen/pull/1084, thanks @David-OConnor!
