### ISSUE TITLE
Lifting exact version between binary and project restriction

### ISSUE THREAD

**Issue by chinedufn** [rustwasm/wasm-bindgen#1086]
Hey!

It looks like `wasm-bindgen` is getting closer and closer to being "API complete", where the underlying pieces (ex: generated JS vs. `anyref`) might change.. but the way that a developer would use `wasm-bindgen` will largely stay the same (or am I off here?)

If that's the case - how does that impact the requirement that your `wasm-bindgen-cli` binary matches your `wasm-bindgen` version?

More specifically. What things stand in the way of lifting or loosening that requirement?

Cheers!!

---

**Edit** - Main motivation for asking is that when you're working on multiple projects but you have one `wasm-bindgen-cli` anytime you upgrade one you have to go back and upgrade the rest (or change your CLI version).

Sure I could have different binaries for each project but I don't really want to do that unless I need to. 

But yeah.. not an _enormous_ or _show stopping_ amount of friction.. just a nice-to-have that I've run into and am curious about.

Thanks!!!

**Comment by alexcrichton** [comment]
An interesting question! The short answer is that I don't think we're equipped to do this in the near term, most versions of wasm-bindgen tweak the custom section in one way or another. The longer answer though is that `wasm-pack` is intended to be the answer here where you don't have to manage wasm-bindgen-cli versions by hand. 

Would wasm-pack work for your use case though?

**Comment by chinedufn** [comment]
It 115% would and I'll move all of my projects to it. Thanks as always!
