### ISSUE TITLE
Expose BigInt bindings

### ISSUE THREAD

**Issue by RReverser** [rustwasm/wasm-bindgen#1087]
PR https://github.com/rustwasm/wasm-bindgen/pull/188 a while back added mapping of `{u,i}64` to `BigInt`s for custom bindings, but there is still no implementations of `From<{u,i}64> for JsValue` or raw `BigInt` bindings which makes their construction a bit cumbersome in generic contexts.

**Comment by RReverser** [comment]
Looking into this further, I see that some other types that are castable when creating manual bindings, are not supported with explicit conversion to `JsValue`.

I wonder if it would make sense to enforce such conversion traits for any type supported by bindgen itself (via `: JsCast` constraint or anything like it)?

**Comment by alexcrichton** [comment]
We've [previously decided](https://github.com/rustwasm/wasm-bindgen/issues/859) that any phase 4 proposals can be added to js-sys, so once it's there we're good to go!

**Comment by RReverser** [comment]
Ah I see. And how about a blanket `From` implementation for any types supported by wasm-bindgen itself as suggested above?

**Comment by RReverser** [comment]
That's what I'm trying to say - `BigInt` seems to be one of these, if I understand correctly. I mean, it's possible to create custom function with `#[wasm_bindgen]` attribute that accepts/returns `u64` and that would translate to `BigInt` on JS side, but it's not possible to similarly convert `u64` to `JsValue` directly.

**Comment by alexcrichton** [comment]
Oh sure yeah makes sense, and seems fine by me to add!

**Comment by alexcrichton** [comment]
We decided awhile back that we'd bind stage 4+ proposals, and it looks like this is currently stage 3 so I'm going to go ahead and close this.

**Comment by RReverser** [comment]
Nooo, I'm working on it in a branch, there is just a bunch of different changes needed. ;(

**Comment by alexcrichton** [comment]
Oh that's still fine! I just figured we didn't need a tracking issue for something that's not quite ready yet, but there can always be a crate on crates.io that we pull in later

**Comment by RReverser** [comment]
Wouldn't it be a bit inconsistent that wasm-bindgen already internally relies on BigInt for u64/i64 support, but doesn't expose explicit bindings to it?

This was the main motivation for this issue.

**Comment by alexcrichton** [comment]
It only relies on it in an experimental fashion because it's the only way to work with some of those types.

**Comment by Recmo** [comment]
BigInt has since moved to stage 4: https://github.com/tc39/proposals/blob/master/finished-proposals.md

**Comment by trevyn** [comment]
These bindings are present and working in #2629.
