### ISSUE TITLE
draw_elements_with_f64 offset parameter shouldn't be a float

### ISSUE THREAD

**Issue by chinedufn** [rustwasm/wasm-bindgen#1088]
Hey, unless I'm missing something it seems like [draw_elements_with_f64](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.WebGlRenderingContext.html#method.draw_elements_with_f64)'s offset shouldn't be a float but rather a `usize` or `u32` or something like that..?

![image](https://user-images.githubusercontent.com/2099811/49651512-65842000-f9fd-11e8-8cfb-1dd5ef265f67.png)

Since the `offset` is an `offset` into the buffer of data.

Or am I missing something?

Cheers!

**Comment by chinedufn** [comment]
Well I guess I need to learn how to read 🤷‍♂️  . Looks like there are other methods (although I'm still not sure why you'd need an `f64` offset

https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.WebGlRenderingContext.html#method.draw_elements_with_i32

**Comment by jsheard** [comment]
Javascript doesn't support 64-bit integers natively, so when the WebIDL defines a `u64`/`i64` parameter (like `offset` there) the bindings generator compromises by emitting a version taking a `u32`/`i32` and a version taking an `f64`. The `u32`/`i32` version is usually all you need but an `f64` can hold exact integers up to 53 bits so it can support a much wider range of values.
