### ISSUE TITLE
Add `buffer_data_with_u16_array` to WebGlRenderingContext

### ISSUE THREAD

**Issue by chinedufn** [rustwasm/wasm-bindgen#1089]
Right now there's a [buffer_data_with_u8_array](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.WebGlRenderingContext.html#method.buffer_data_with_u8_array) which is super convenient if you want o use `WebGLRenderingContext::UNSIGNED_BYTE`.

However, `UNSIGNED_SHORT` is probably more common, so `buffer_data_with_u16_array` would be super useful IMO.

Any reason that this shouldn't exist?

If not - I'd be happy to add it if you can point me in the right direction!

**Comment by alexcrichton** [comment]
I believe that method is [defined here](https://github.com/rustwasm/wasm-bindgen/blob/7768328fc49962c9996d80a72bc20b16856104ce/crates/web-sys/webidls/enabled/WebGLRenderingContext.webidl#L719) which we [expand here](https://github.com/rustwasm/wasm-bindgen/blob/master/crates/webidl/src/idl_type.rs#L640) to an `ArrayBuffer` and a `&mut [u8]`. In theory any typed array can be accepted here but we just don't expand to all typed arrays, just a few. We could perhaps though add an `&[u16]` though!

Another option is https://github.com/rustwasm/wasm-bindgen/issues/811 to create a `Uint16Array` from a `&[u16]` instance and then hand off the `ArrayBuffer`

**Comment by chinedufn** [comment]
I ended up going with this approach -> https://github.com/rustwasm/wasm-bindgen/pull/918#issuecomment-445495395
