### ISSUE TITLE
DOM example fails: Chrome and Firefox Nightly have `body` on `Document` only

### ISSUE THREAD

**Issue by badboy** [rustwasm/wasm-bindgen#109]
The [current DOM example](https://github.com/rustwasm/wasm-bindgen/tree/9723fdd69bbcd26bed7c61d1904ca21ffbf5fdf7/examples/dom) fails to run on Firefox Nightly (61.0a1) and Chrome with the following error:

```
TypeError: Object.getOwnPropertyDescriptor(...) is undefined
```

This happens when this code is run:

```javascript
Object.getOwnPropertyDescriptor(HTMLDocument.prototype, 'body').get
```

In Chrome and newer Firefox properties of `HTMLDocument` were moved into `Document` (see [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=897815) I think).
The following patch makes the example work on Nightly (but then fails on Firefox stable)

```patch
--- a/examples/dom/src/lib.rs
+++ b/examples/dom/src/lib.rs
@@ -16,12 +16,12 @@ use wasm_bindgen::prelude::*;
 // signatures documented on MDN, for example
 #[wasm_bindgen]
 extern {
-    type HTMLDocument;
-    static document: HTMLDocument;
+    type Document;
+    static document: Document;
     #[wasm_bindgen(method)]
-    fn createElement(this: &HTMLDocument, tagName: &str) -> Element;
+    fn createElement(this: &Document, tagName: &str) -> Element;
     #[wasm_bindgen(method, getter)]
-    fn body(this: &HTMLDocument) -> Element;
+    fn body(this: &Document) -> Element;
 
     type Element;
     #[wasm_bindgen(method, setter = innerHTML)]

```

**Comment by corbinu** [comment]
@alexcrichton Looks like this was expected for a while. In TypeScripts dom definition HTMLDocument simply extends Document with no additions.

https://github.com/Microsoft/TypeScript/blob/02547fe664a1b5d1f07ea459f054c34e356d3746/src/lib/dom.generated.d.ts#L4532

So it looks like as far as the browsers are concerned the JavaScript duck types were the same so this was a non breaking change.

However I would expect few changes can fall into that category so this should happen very often.

**Comment by lukewagner** [comment]
Very interesting, thanks for pointing this out.  It seems like, while breakage like this should be rare (esp. with everything being pretty well-specified by Web IDL), it will probably happen from time to time and then there's the issue of different browsers doing different things.

One idea: if we assume that properties mostly only ever move "up" the protochain, wasm-bindgen could use the following helper instead of `Object.getOwnPropertyDescriptor`:
```js
function GetOwnOrInheritedPropertyDescriptor(obj, id) {
  while (obj) {
    let desc = Object.getOwnPropertyDescriptor(obj, id);
    if (desc) return desc;
    obj = Object.getPrototypeOf(obj);
  }
  throw "not found";
}
```

**Comment by alexcrichton** [comment]
Ok thanks @lukewagner, makes sense to me!

@corbinu ah good to know! I wonder though if that means that the TypeScript may not be as strict as the actual definition (aka WebIDL) and not sufficient for wasm-bindgen...

**Comment by badboy** [comment]
that was a quick turnaround. Thanks for the fix!

**Comment by alexcrichton** [comment]
@corbinu on today's browsers at least some properties must be accessed through `HTMLDocument.prototype` rather than `Document.prototype`, but if Typescript has everything on `Document` then wasm-bindgen may know now where to find everything infallibly
