### ISSUE TITLE
Remote context requirement for Function?

### ISSUE THREAD

**Issue by dakom** [rustwasm/wasm-bindgen#1094]
This is just a question for discussion... I feel icky needing JsValue::NULL, even if it's only for passing to js_sys::Function calls...

Would it make sense to add function callers which do not need the `this` context and instead use JsValue::NULL internally?

Or, alternatively, have them accept `Option<&JsValue>` instead so that it can be called like `cb.call_1(None, JsValue::from_str("hello world"))` ?

**Comment by alexcrichton** [comment]
An interesting idea! For now though the `js-sys` crate is intended on exposing the raw functionality exposed by JS itself. While we could add higher level abstractions to wasm-bindgen and/or js-sys we're hoping the ecosystem can help us pick up the slack in that regard!

For now I think we'll leave this as-is and not add APIs to js-sys as they're intended to be low level, but we're always happy to see progress happening in this space on crates.io!
