### ISSUE TITLE
UiEvent.pageX does not exixt

### ISSUE THREAD

**Issue by chinedufn** [rustwasm/wasm-bindgen#1095]
This code panics when I mouse over my canvas

```rust
 let on_mouse_move = Closure::wrap(Box::new(move |event: web_sys::MouseEvent| {
      web_sys::console::log_1(&"mouse moved".into());
      let x = event.page_x();
      let y = event.page_y();
  }) as Box<FnMut(_)>);

  canvas.add_event_listener_with_callback(
      "mousemove",
      on_mouse_move.as_ref().unchecked_ref(),
  )?;

  on_mouse_move.forget();
```

![image](https://user-images.githubusercontent.com/2099811/49702236-06bcd300-fbc4-11e8-90bc-ca80e94497a8.png)

I have the `MouseEvent` and `UiEvent` features enabled. 

I'm using wasm-bindgen `0.2.29`

**Comment by alexcrichton** [comment]
Hm interesting! Looks like on Firefox `Object.getOwnPropertyDescriptor(UIEvent.prototype, 'pageX')` returns a descriptor, whereas on Chrome it does not. Are you using chrome perchance?

**Comment by chinedufn** [comment]
_FWIW I switched to `offset_x` which works fine for my use case (I just need some relative positions)_

Yup I was indeed using Chrome and I didn't check Firefox so that could be the problem!

**Comment by limira** [comment]
I look in the [docs](https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/pageX). It says that (emphasis added by me)
> This property was never part of any standard, and was only implemented across a subset of browsers, and only for a limited number of versions. **A standardized version of pageX was added to the MouseEvent interface, however, and is well-supported**. You should not expect to find pageX on any non-mouse events. Do not look for pageX on any non-mouse events in new code and update existing code as soon as possible.

And in the Specifications Section:

> This property is not part of any specification. See MouseEvent.pageX instead.

So may be just access MouseEvent.pageX directly, not via UiEvent.

**Comment by limira** [comment]
@chinedufn, I guess you import these things yourself (not using `web-sys`)??. I do a search on `web-sys` docs and it seems that `page_x` only available for `UiEvent`!

I think this is still an issue in `web-sys`!

**Comment by chinedufn** [comment]
I'm using `web-sys` but I thought you were suggesting that people should write their own import for this - haha sorry! Re-opened!

**Comment by alexcrichton** [comment]
Hm ok now that I look into this I think it's a bug that we're still using the old "structural" intepretation of field accesses throughout web-sys. After https://github.com/rustwasm/wasm-bindgen/pull/1019 it's intended that web-sys switched over to just accessing properties directly, and not doing so is a bug we forgot to fix! I'll submit a fix for this shortly.
