### ISSUE TITLE
Weird diagnostics with wasm_bindgen and language server

### ISSUE THREAD

**Issue by dakom** [rustwasm/wasm-bindgen#1097]
I know this is like the worst bug report ever... but...

I've had issues in both VSCode and NeoVim where error reporting stops showing up in the IDE, or is only at the top of the file instead of on the appropriate line(s). (both IDEs use RLS).

~~It seems to be when I import web_sys only.... but~~ honestly it's been an intermittent issue and I can't even faithfully push a repo to demonstrate this, so I'm not sure if it really has anything to do with web_sys.

Sorry for such a vague and useless bug report - feel free to close this right away, but I felt it was worthwhile raising here on the off chance that someone else is experiencing the same thing, and maybe has better detective work to share. Thanks!

**Comment by dakom** [comment]
> I can't even faithfully push a repo to demonstrate this

I take that back... it's just that I can only make it appear in this real-world (very beginning!) project and the bug _sometimes_ goes away when I tried to make it reproduce in a standalone repo.

Here's a commit than can be cloned (linking directly to the test bug): https://github.com/dakom/pure3d/blob/668e9cbbce4e1e6fc0945574e1b9a174339b358c/examples/webgl-demo/src/lib.rs#L75

And here's a screenshot showing the weirdness. It has the same file just split, and you can see the error should be reported on `line #81` - but instead it's showing at the top of the file!

What's even crazier is removing the `#[wasm_bindgen]` annotation fixes it!

![screenshot_2018-12-10_11-10-38](https://user-images.githubusercontent.com/6406986/49722009-53f47f80-fc6c-11e8-9ae1-f83423f65570.png)

Here, without the annotation:
![screenshot_2018-12-10_11-13-13](https://user-images.githubusercontent.com/6406986/49722126-a03fbf80-fc6c-11e8-9306-338efcec929d.png)

**Comment by alexcrichton** [comment]
Thanks for the report! This is actually an upstream bug in rust-lang/rust (found [here](https://github.com/rust-lang/rust/issues/43081)) which, for an obscure number of reasons, means that the error message diagnostics aren't the best.

The "fix" here is to use `extern "C" fn` instead of just `extern fn`, although it's definitely an obscure fix! We're working on fixing these on nightly for sure!

I'm gonna close this for now in favor of the upstream rust-lang/rust issue

**Comment by dakom** [comment]
That did fix it, awesome!

By any chance do you happen to know if there's another known bug which is preventing autocomplete for working with the imports like `js_sys:Function` ?

**Comment by alexcrichton** [comment]
Hm I wonder if that just has to do with macros and expansion? I'm not quite sure myself though!

**Comment by dakom** [comment]
OK cool, I'll keep my eyes peeled to try it out again when there's updates to the ecosystem, maybe something will fix itself. Thanks for the quick feedback!
