### ISSUE TITLE
Use `.wasm` Extension

### ISSUE THREAD

**Issue by 0xcaff** [rustwasm/wasm-bindgen#1114]
I'm attempting to use rust from the web using parcel as the bundler with https://github.com/catsigma/parcel-plugin-wasm.rs

Running `wasm-bindgen` generates a file with the following line:

    import * as wasm from './chromaprint_wasm_bg';

And parcel doesn't know how to determine the loader for this file.

![image](https://user-images.githubusercontent.com/3277097/50046787-36158900-0077-11e9-903f-b085decfee94.png)

Changing the line above to:

    import * as wasm from './chromaprint_wasm_bg.wasm';

fixes everything.

Similar to #154, except parcel seems to work now.

Can wasm-bindgen add the `.wasm` extension to fix this issue?

**Comment by 0xcaff** [comment]
Actually changing the extension to the _bg script to `.wasm` doesn't fix anything. I've resorted to changing my import to:

    import { ChromaprintContext } from "chromaprint-wasm/chromaprint_wasm_bg.wasm";

and using the generated typescript definitions from my module

    declare module "chromaprint-wasm/chromaprint_wasm_bg.wasm" {
      export * from "chromaprint-wasm";
    }

This causes the `parcel-plugin-wasm` to handle loading the `.wasm` file. It seems to work, but I'm not sure why.

**Comment by 0xcaff** [comment]
Actually that doesn't work either. I don't know how to use this with parcel and typescript.

**Comment by andrewdavidmackenzie** [comment]
I'm stuck on similar issue, following the "Programming WebAssembly with rust" book.

The js generated by wasm-bindgen is:
```
import * as wasm from './bindgenhello_bg';
```

Which causes chrome (in console) to report:
```
GET http://0.0.0.0:8000/bindgenhello_bg net::ERR_ABORTED 404 (File not found)
```

When I modify it manually to be:
```
import * as wasm from './bindgenhello_bg.wasm';
```

then chrome reports:
```
Failed to load module script: The server responded with a non-JavaScript MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.
```

So, I can't load it either way...

**Comment by 0xcaff** [comment]
I ended up giving up on Parcel and switching to webpack. Here's a project where wasm + webpack works: https://github.com/0xcaff/chromaprint-web

The second error can be fixed by changing the Content-Type header, but it will fail with another error.

Support for this is still blocked by https://github.com/parcel-bundler/parcel/issues/647

**Comment by andrewdavidmackenzie** [comment]
Actually I'm using webpack, but got those problems mentioned.
I have other wasm projects working (with more handwritten boilerplate JS), and so this seems to be related to switch to use wasm-bindgen generated JS to help bootstrap things.

**Comment by andrewdavidmackenzie** [comment]
I don't understand all the details - but the book author suggested some changes and that got my problem fixed - here is the issue (with a reference to fixing commit in my repo), in case it's useful to anyone else:

https://github.com/andrewdavidmackenzie/wasm-book/issues/1

Thanks for the offer of help though @alexcrichton
