### ISSUE TITLE
Reasoning for Option<WebGlProgram>, Option<WebGlShader>, etc.?

### ISSUE THREAD

**Issue by dakom** [rustwasm/wasm-bindgen#1115]
There's several functions which accept a WebGlProgram, WebGlShader, etc.

However, in the API they require that they're wrapped in an Option. Some examples:

* [gl.use_program](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.WebGlRenderingContext.html#method.use_program)

* [gl.delete_shader](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.WebGlRenderingContext.html#method.delete_shader)

(actually lots of the delete stuff)

Fwiw - the delete_* shouldn't be very high impact, but use_program is probably called fairly often, and I think it's fair to say that the caller has already dealt with error handling before trying to use_program()

Very possible I'm just totally missing something, looking forward to understanding better!

**Comment by jsheard** [comment]
Those bindings are auto-generated from the WebIDL definitions, which for those functions is:

```
void useProgram(WebGLProgram? program);
void deleteShader(WebGLShader? shader);
```

The `?` means the parameter is nullable, so wasm-bindgen maps it as `Option<T>`.

In practice you probably wouldn't actually pass a null, but you *could*, so wasm-bindgen allows it.

**Comment by dakom** [comment]
Fair enough - I'll close the issue. Thanks!
