### ISSUE TITLE
Alternative to build.sh?

### ISSUE THREAD

**Issue by grovesNL** [rustwasm/wasm-bindgen#1120]
I noticed many of the examples rely on `build.sh`. I assume most users have some shell installed (even on Windows), but I think it would be better to avoid this dependency if possible.

Is there a portable alternative that could be used instead? For example, using some cargo runner (I think a few exist?) or simply providing an equivalent `build.bat` for Windows might be helpful to new users following the guide.

This is fairly minor, but thought I would mention it here as people will probably be looking to this guide for best practices.

**Comment by alexcrichton** [comment]
This is a very good point! The "alternative" is actually more like the official solution, which is `wasm-pack`. We haven't had a chance to integrate `wasm-pack` into the examples here, but I'd love to do that to really show off how everything works!

**Comment by grovesNL** [comment]
That sounds good to me. Using `wasm-pack build` with the examples instead seems mostly straightforward, but I wasn't sure about a few points I raised in rustwasm/wasm-pack#466

**Comment by TitanThinktank** [comment]
for some reason wasmpack builds /compiles the programs super fast, no idea why, but i use the build part only since publish seems like its for NodeJS

**Comment by alexcrichton** [comment]
Integrating wasm-pack into wasm-bindgen will at least require the workspace fixes to wasm-pack which aren't on master yet, but can revisit this once that's published!

**Comment by ashleygwilliams** [comment]
@alexcrichton the workspaces fix is on master now!
