### ISSUE TITLE
fetch example should show extraction of data into usable form

### ISSUE THREAD

**Issue by David-OConnor** [rustwasm/wasm-bindgen#1127]
The [fetch api example](https://rustwasm.github.io/wasm-bindgen/examples/fetch.html) (Also lives in the examples/fetch folder) demonstrates how to perform a get request on data, returning a js_sys::Promise, but not how to extract the original data (In this case, the Branch struct) from it in Rust. Eg it could use the addition of something like this, but working:
```rust
let branch_promise = run();

let closure = Closure::wrap(
    Box::new(move |val: JsValue| {
        val.into_serde().unwrap()
    })
        as Box<FnMut(JsValue) + 'static>
);

let branch = branch_promise.then(closure);
web_sys::console::log_1(&format("{:?}", branch).into());
```
It appears you can access the rust data in the final and_then leg, so perhaps we can return the data directly (Set up a mutable variable of the struct you're returning before the let future = line, then resassign it during this leg?)), or a Rust future (We have to somehow turn the AndThen into one?), instead of transforming it back to a JsValue.

Or perhaps return before the final and_then, letting the user construct it; this may be required in order to de serialize into the object type (Not sure how to pass the object to deserialize into otherwise). Not sure what to put for AndThen's 3 type args though. Ultimately, it would be nice to do something like this:

```rust
wasm_bindgen::fetch("get", "https://mysite.com", |data| update_state(data.json())
```
}

Once I sort out how to do this, I'd be happy to submit a PR with a writeup in the Guide, or if you think appropriate, a higher-level API. (The latter may be more appropriate in a standalone crate.)

**Comment by alexcrichton** [comment]
Thanks for the report! I think that the best way to implement this would be to use `Future` in Rust rather than `Promise` in JS, which should likely only be used at the edges of the wasm module.

Futures in Rust are much more geared towards arbitrary Rust data types than JS promises are :)

In any case sounds like a great addition to the `fetch` example to me!

**Comment by David-OConnor** [comment]
That seems like best approach. I think this abbreviated code is close:
```rust
pub fn fetch(// ...) -> impl Future<Item = JsValue> {
     // ...
    wasm_bindgen_futures::JsFuture::from(request_promise)
        .and_then(|resp_value| {
            // `resp_value` is a `Response` object.
            assert!(resp_value.is_instance_of::<web_sys::Response>());
            let resp: web_sys::Response = resp_value.dyn_into()
                .expect("Problem casting response as Reponse.");
            resp.json()
        })
        .and_then(|json_value: js_sys::Promise| {
            // Convert this other `Promise` into a rust `Future`.
            wasm_bindgen_futures::JsFuture::from(json_value)
        })
}

// ... 

fetch(//...)
    .and_then(|json| {
            // Use serde to parse the JSON into a struct.
            let branch_info: Branch = json.into_serde().unwrap();

            // Send the `Branch` struct back to JS as an `Object`.
            future::ok(JsValue::from_serde(&branch_info).unwrap())
    });
```
But getting this error: `^^^^^^^^ the trait `futures::future::Future` is not implemented for `()`
`

**Comment by David-OConnor** [comment]
Update: call to fetch now looks like this:
```rust
    let r = fetch(...);
    let r_fin = r.and_then(|json| {
        // Use serde to parse the JSON into a struct.
        let branch_info: Branch = json.into_serde().unwrap();

        // Send the `Branch` struct back to JS as an `Object`.
        future::ok(JsValue::null())
    });
```
This compiles without warnings in Rust, but results in the following panic in-browser: ```panicked at 'assertion failed: a != 0', C:\Users\david\.cargo\registry\src\github.com-1ecc6299db9ec823\wasm-bindgen-0.2.29\src\closure.rs:408:1'```. [relevant file](https://github.com/rustwasm/wasm-bindgen/blob/master/src/closure.rs).
My guess at the relevant code chunk:
```rust
 unsafe extern fn destroy<$($var: FromWasmAbi,)* R: ReturnWasmAbi>(
                    a: usize,
                    b: usize,
                ) {
                    debug_assert!(a != 0);
                    drop(Box::from_raw(FatPtr::<FnMut($($var,)*) -> R> {
                        fields: (a, b)
                    }.ptr));
                }
                inform(destroy::<$($var,)* R> as u32);

<&mut Self>::describe();
```
Whether split or not, not applying wasm_bindgen_futures::JsFuture::from() to the future triggers this; likely due to not being able to properly "destroy" the closure/promise/future. But when split, attempting to apply this results in this compile error: ```expected associated type, found struct `wasm_bindgen::JsValue````

**Comment by alexcrichton** [comment]
@David-OConnor oh actually, would you be interested in sending a PR for an updated example, and I could try to help debug issues in the example?

**Comment by David-OConnor** [comment]
My lack of understanding of how to work with futures makes me hesitant to submit a PR, or write docs on the subject. Here's a working high-level [API](https://github.com/David-OConnor/seed/blob/master/src/fetch.rs). It works by inserting a callback into the official example, either to intercept the response, or the parsed JSON. It then allows the future to resolve as per the example, to avoid the panic I posted above. It involves some repetitive code, and the API is not idea, but it's the best working soln I've come up with.

Would ideally like to do what you described (Return a Rust future of the web_sys::Response), but run into trouble when splitting futures across funcs. (Perhaps could be sorted with the right type signatures?)

**Comment by Pauan** [comment]
@David-OConnor If you don't mind, I sent you a pull request with some changes.

In particular, `Request` is now a builder that you use to specify the various fetching options, and then you call `fetch` to start the fetching. It returns a `Future`, so you can chain it with the regular Future methods:

```rust
Request::new("http://example.com")
    .method(Method::GET)
    .header("Content-Type", "text/html")
    .fetch()
    .map(|response| {
        // ...
    })
```

It supports all of the `Request` options, and it automatically supports cancellation as well. Performance should be good, especially after `anyref` is supported.

It also has a few helper methods, such as `fetch_string`, `fetch_json`, and `body_json`:

```rust
Request::new("http://foo.com")
    .method(Method::POST)
    // value is any Rust type which can be serialized
    .body_json(value)
    .fetch_json()
    .map(|response| {
        // response is any Rust type which can be deserialized
    })
```

To actually run the Future, you just use `future_to_promise`, as usual:

```rust
#[wasm_bindgen]
pub fn start() {
    future_to_promise(
        Request::new("http://foo.com")
            .method(Method::POST)
            // value is any Rust type which can be serialized
            .body_json(value)
            .fetch_json()
            .map(|response| {
                // response is any Rust type which can be deserialized
            })
    );
}
```

**Comment by Pauan** [comment]
To answer some of your questions:

> It works by inserting a callback into the official example, either to intercept the response, or the parsed JSON. It then allows the future to resolve as per the example, to avoid the panic I posted above.

My implementation doesn't use callbacks at all, just `Future`s, so it should be a lot cleaner (and probably avoids this bug?).

> Can we avoid the need to return a dummy future::ok, and call to wasm_bindgen_futures::future_to_promise(f); at the end?

Yup! My implementation avoids both of those.

> Is there a way we can parse json (or text) from a web_sys::Response directly, eg using the fetch fn I posted plus some additional async code, vice the fetch_json fn.

Yes, that's what my implementation does (see the `fetch_string` and `fetch_json` methods).

**Comment by David-OConnor** [comment]
@Pauan Love it. Will dig in/merge tonight. Seems like much of my trouble was in a poor understanding of futures.

**Comment by alexcrichton** [comment]
I think at the very least this'd make a great example, so we can always start there!

**Comment by alexcrichton** [comment]
I think this is done now on master, so closing.
