### ISSUE TITLE
mut required for uploading to uniforms

### ISSUE THREAD

**Issue by dakom** [rustwasm/wasm-bindgen#1131]
Functions like [uniform4fv_with_f32_array()](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.WebGlRenderingContext.html#method.uniform4fv_with_f32_array) expect a mutable reference to a slice as input

This is really odd imho because you would never expect that function to change the data you pass in.

Also makes it a bit tougher to work with due to borrowing rules...

From looking at the [WebIDL](https://www.khronos.org/registry/webgl/specs/latest/1.0/webgl.idl) it seems this is a `Float32List` - but I see no indication of why that would be mutable.

Help understanding is greatly appreciated!

**Comment by jsheard** [comment]
See https://github.com/rustwasm/wasm-bindgen/issues/1005

**Comment by dakom** [comment]
Ohhh... thanks, I'll go ahead and close this since it's already addressed there and the linked issues.
