### ISSUE TITLE
Don't omit module extension (wasm-bindgen --browser)

### ISSUE THREAD

**Issue by KSXGitHub** [rustwasm/wasm-bindgen#1133]
When I read JavaScript output of `wasm-bindgen --browser`, I see it imports modules without extension, this violates ESM specification.

## Suggestion

```diff
-import * as wasm from './module_name_bg';
+import * as wasm from './module_name_bg.wasm';
```

**Comment by limira** [comment]
Related: #1114 

I think `.wasm` is left out intentionally. If you use a bundler, like webpack, it will take care all for you. But if you don't use any bundler, you must do [a hack](https://github.com/rustwasm/wasm-bindgen/blob/master/crates/cli/src/bin/wasm2es6js.rs) on the `module_name_bg.wasm`  to generate a `module_name_bg.js`. Then the files will be loaded like: `module_name.js` -> `module_name_bg.js` -> `module_name_bg.wasm`. In this case, `import * as wasm from './module_name_bg';` is actually refer to a `js` file. It is currently how [wasm-bindgen-test-runner](https://github.com/rustwasm/wasm-bindgen/tree/master/crates/cli/src/bin/wasm-bindgen-test-runner) works.

If you want to comply to the ESM specification, then `wasm-bindgen-test-runner` must be modified, or you must wait for the browsers to fully support wasm.

**Comment by Pauan** [comment]
It is intended for wasm-bindgen to have a `.wasm` extension, it just hasn't been done yet: https://github.com/rustwasm/wasm-bindgen/pull/1059

**Comment by alexcrichton** [comment]
Indeed this is being handled in https://github.com/rustwasm/wasm-bindgen/pull/1059, so I'm going to close this in favor of that.

Unfortunately native ESM support is hard to come by with wasm right now, and so we're doing the best we can to follow existing conventions :(
