### ISSUE TITLE
convert Vec<[u8]> to JsValue

### ISSUE THREAD

**Issue by lcnr** [rustwasm/wasm-bindgen#1134]
I am using `fetch` in combination with `bincode`. As `bincode::deserialize` expects a byte array and `bincode::serialize` creates a byte array. To do this I currently use the following code: 

```
let data = bincode::serialize(content).unwrap()
opts.body(Some(&JsValue::from_str(unsafe { std::str::from_utf8_unchecked(data) })));
```

Is there a better way to do this?

**Comment by alexcrichton** [comment]
Currently there's not a great way to do this inline in Rust, but it's covered by https://github.com/rustwasm/wasm-bindgen/issues/811 so I'm going to close this in favor of that. Thanks for the report though!

**Comment by rylev** [comment]
@alexcrichton I have a `Vec<f64>` and I need a `&JsValue`. I believe it's not possible to do this conversion without doing the serialization trick. Am I missing something?

**Comment by alexcrichton** [comment]
@rylev I think [`Float64Array::view`](https://docs.rs/js-sys/0.3.10/js_sys/struct.Float64Array.html#method.view) might do the trick for you?

**Comment by alexcrichton** [comment]
I believe if you `slice()` just afterwards you can make a safe wrapper as that'll do a copy
