### ISSUE TITLE
Setting Content-Type Header

### ISSUE THREAD

**Issue by David-OConnor** [rustwasm/wasm-bindgen#1135]
Running into issues with the fetch api setting Content-Type. Am I doing something wrong, or is this a bug? Other headers appear to set correctly:

```rust
    let request = web_sys::Request::new_with_str_and_init(url, &opts)
        .expect("Problem with request");

    request.headers().set("Content-Type", "application/json").unwrap();
    request.headers().set("Accept", "application/vnd.github.v3+json").unwrap();
    request.headers().set("Accept-Language", "en-us").unwrap();

    crate::log(format!("HERE: {:?}", request.headers().get("Content-Type").unwrap()));
    crate::log(format!("HERE: {:?}", request.headers().get("Accept").unwrap()));
    crate::log(format!("HERE: {:?}", request.headers().get("Accept-Language").unwrap()));
```

Where crate::log is a console logger. Accept and Accept-Language are set correctly, but Content-Type shows as "Some("text/plain;charset=UTF-8")" regardless of what is set.

**Comment by David-OConnor** [comment]
`"application/json; charset=utf-8"` has no effect. How do I use raw JS in this case?

**Comment by Pauan** [comment]
> How do I use raw JS in this case?

I meant rewrite it in JS, and use that to test (to see whether it's an issue in JS or in wasm-bindgen):

```js
const request = new Request(url, opts);

request.headers.set("Content-Type", "application/json");
request.headers.set("Accept", "application/vnd.github.v3+json");
request.headers.set("Accept-Language", "en-us");

console.log(request.headers.get("Content-Type"));
console.log(request.headers.get("Accept"));
console.log(request.headers.get("Accept-Language"));
```

You didn't provide your URL or opts, so you'll have to translate those yourself into JS.

**Comment by David-OConnor** [comment]
When I do that, it works correctly. Having trouble trying to dig into the source code on this to see if there's a simple bug going on due to how web_sys is set up as a wrapper of some sort.

**Comment by Pauan** [comment]
> Have you (or anyone) successfully been able to set content type in web_sys?

Well, I never tried, so, technically no.

> Leaning bug.

If you can make a small reduced test case, that'll make it a lot easier for us to fix it.

**Comment by David-OConnor** [comment]
[Test case](https://gist.github.com/David-OConnor/55c385dac86538fb19fcc6a43f1f3ae7). Although I suspect we can narrow down what's going on with any case where we attempt to set Content-Type.

**Comment by limira** [comment]
It works for me. But my code is exactly as yours!??

**Comment by alexcrichton** [comment]
Ok sounds like this is somewhat solved at least, but @David-OConnor if more comes up I can certainly reopen!

**Comment by dmilford** [comment]
I'm having the same problem.  Any idea on how I can resolve this?

**Comment by loveJesus** [comment]
✝ Having the same problem, can set other headers but not content type. For my purposes it worked by removing the content type ```request_aleluya.headers().delete("content-type").unwrap();``` appending or setting afterwards seems to not work to set it afterwards though but it isn't a wrong header at least, hallelujah

**Comment by eigmax** [comment]
Same issue.  is it solved?, guys

**Comment by balanceglove2** [comment]
@alexcrichton please re-open. I'm having the exact same issue. `Accept-Language` works, `Content-Type` doesn't. Running `log(&format!("HERE: {:?}", request.headers().get("Content-Type")));` even makes my Safari force-reload the page saying "This webpage was reloaded because a problem occurred."

**Comment by balanceglove2** [comment]
Apparently `request.headers()` is readonly. Correct usage is constructing a `Headers` with `Headers::new()`, setting the headers with `.set()` and then assigning it to the `Request` object using `request.headers(headers)`.

**Comment by balanceglove2** [comment]
In my case I'm trying to set it to `application/octet-stream`. My data is `Uint8Array`. I changed my data to a simple string and my `Content-Type` to `text/plain` and now the header is showing up. I.e. JS actually does some sort of validation of whether your content fits your specified `Content-Type`. If it doesn't, at least here, it silently sets it to `None`, apparently.

**Comment by richtera** [comment]
> Apparently `request.headers()` is readonly. Correct usage is constructing a `Headers` with `Headers::new()`, setting the headers with `.set()` and then assigning it to the `RequestInit` object using `request_init.headers(headers)`.

@balanceglove2 I am also unable to send the headers to request_init. I was able to serialize it as json and then I can see it on the javascript side, but the "new Request" function in the browser also seems to ignore them on that side. What browser are you using? Very strange, I have now spent way to long to just get a simple request to work :)

Here is my code but all headers seem to be ignored. When I stop in the js code the headers property looks like an empty object but using .get('Accept') for example does return values, but the Request constructor seems to ignore the whole thing.

```rust
... snip ...
    let bearer = format!("Bearer {}", token.id_token.clone());
    let headers = Headers::new().unwrap();
    headers.set("Accept", "application/json").unwrap();
    headers.set("Authorization", &bearer).unwrap();
    headers.set("Content-Type", "application/json").unwrap();

    bindings::log(format!("headers {:#?}", &headers));

    let mut opts = RequestInit::new();
    opts.method("POST");
    opts.mode(RequestMode::NoCors);
    opts.headers(&headers);
    let request_str = serde_json::to_string(&query).unwrap();
    opts.body(Some(&JsValue::from_str(&request_str)));

    let request = Request::new_with_str_and_init(&url, &opts).unwrap();

    let window = web_sys::window().unwrap();
    let resp_value = JsFuture::from(window.fetch_with_request(&request))
        .await
        .unwrap();
```

**Comment by richtera** [comment]
It looks like RequestInit with no-cors ignores all headers.
