### ISSUE TITLE
Unintentional `mut` in WebGL API

### ISSUE THREAD

**Issue by emilk** [rustwasm/wasm-bindgen#1146]
The final argument of [`WebGlRenderingContext::tex_image_2d_with_i32_and_i32_and_i32_and_format_and_type_and_opt_u8_array`](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.WebGlRenderingContext.html#method.tex_image_2d_with_u32_and_u32_and_image_bitmap) is `pixels: Option<&mut [u8]>`, but it makes no sense for it to be `mut`, so I think this is a mistake.

**Comment by chinedufn** [comment]
Related to https://github.com/rustwasm/wasm-bindgen/issues/1005

**Comment by alexcrichton** [comment]
Ah yeah I think this is a consequence of #1005, so I'm going to close in favor of that. Thanks for the report though!
