### ISSUE TITLE
[web-sys] Incorrect codegen for `unsigned long long` in `IDBVersionChangeEvent`

### ISSUE THREAD

**Issue by richard-uk1** [rustwasm/wasm-bindgen#1149]
The webidl signature is

```webidl
[Constructor(DOMString type, optional IDBVersionChangeEventInit eventInitDict),
 Exposed=(Window,Worker,System)]
interface IDBVersionChangeEvent : Event {
    readonly    attribute unsigned long long  oldVersion;
    readonly    attribute unsigned long long? newVersion;
};
```

but the code in web-sys is

```rust
impl IdbVersionChangeEvent {
    pub fn old_version(&self) -> f64;
    pub fn new_version(&self) -> Option<f64>;
}
```

The `f64` should be `u64`.

**Comment by derekdreery** [comment]
I don't know how this works in practice, since u64 isn't supported in ECMAScript. Maybe f64 is the correct type. But then why define something in webidl that can't be represented in js?

**Comment by chinedufn** [comment]
Yup -> https://github.com/rustwasm/wasm-bindgen/issues/1088#issuecomment-445244540

And because WebIDL was never meant to be coupled to JS AFAICT.

**Comment by Pauan** [comment]
> And because WebIDL was never meant to be coupled to JS AFAICT.

To expand on this: WebIDL was intended to be language-agnostic (so it could be used in other languages, like Java).

But in practice it is used almost exclusively with JS, so more recent WebIDL contains more JSisms.

The `f64` is correct, since JS doesn't have `u64` support.

**Comment by Pauan** [comment]
@derekdreery As you found, the biggest integer in JS is [`Number.MAX_SAFE_INTEGER`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER), which is `9007199254740991`

It seems to me that a function like that would be a nice addition to wasm-bindgen, since converting from `f64` to `u64` is rather tricky.
