### ISSUE TITLE
Supporting `new Foo(...)` instead of `Foo.new(...)`

### ISSUE THREAD

**Issue by konstin** [rustwasm/wasm-bindgen#115]
Given the otherwise pleasantly natural mapping between rust and javascript types, the behavior of the javascript new is counterintuitive and an easy pitfall. Therefore I'd like to change the constructor to map to what `new` is in rust.

So instead of the currently generated code

```javascript
module.exports.MyClass = class MyClass {

    constructor(ptr) {
        this.ptr = ptr;
    }

    static new(arg0, arg1) {
        const ret = wasm.myclass_new(arg0, arg1);
        return new MyClass(ret);
    }
    // ...
}
```

I'd suggest something like the following: 

```javascript
class _ConstructorToken {
    constructor(ptr) {
        this.ptr = ptr
    }
}

module.exports.MyClass = class MyClass {
    constructor(...args) {
        if (args.length === 1 && args[0] instanceof _ConstructorToken) {
            this.ptr = args[0].ptr;
        }

        this.ptr = wasm.myclass_new(...args);
    }

    // ...
}
```

An alternative approach would be passing a token the way it's currently done with --debug. I don't have enough background knowledge though to decide which is better.

It also needs to be figured out whether a static new returning an instance should be used for the  constructor by convention or if it should be specially annotated (e.g. with `#[wasm_bindgen(constructor)]` with the extern functions).

**Comment by alexcrichton** [comment]
Thanks for the report! I've indeed though it's a bummer that `new Foo()` can't work. I do think that we'll need to use `#[wasm_bindgen(constructor)]` to flag a static on the Rust side as routing to `new`, although we could also perhaps infer that with the name `new` by default as a constructor.

Is there a possible performance pitfall though with the construction? Does the dynamic check cause the runtime here to be slower?
