### ISSUE TITLE
Custom `Debug` implementations for js_sys::*

### ISSUE THREAD

**Issue by derekdreery** [rustwasm/wasm-bindgen#1157]
It would be nice when debugging if you could get more information about the contents of a javascript object, etc. Debug could be implemented to iterate over its own properties and use `f.debug_map` to print them.

Same applies to other built-in javascript objects.

**Comment by alexcrichton** [comment]
This sounds like a great idea to me, and I think we could take a PR for these at any time!

**Comment by derekdreery** [comment]
I've implemented something in #1161, I'm seeing how it works out in practice and it seems to be good.

It basically tries to json-encode the object, and if that's not possible use toString to get something.

**Comment by alexcrichton** [comment]
We've already added a few of these so I'm going to close this, and more are of course welcome at any time!
