### ISSUE TITLE
How to consume artifacts of "wasm-pack build" without using webpack

### ISSUE THREAD

**Issue by habemus-papadum** [rustwasm/wasm-bindgen#1163]
Is it possible to provide a tutorial/instructions on how to use the build output (i.e. the `.js`/`_bg.wasm` pair) without having to rely on webpack magic loading?   I would like to load the js from a modern browser with es6 support, so I imagine the instructions would be of the form:
edit the generated js, replacing:

```
import * as wasm from './wasm101_bg';
```

with 
```
<a bunch of js boilerplate that loads the wasm, compiles,  and attaches memory and so forth>
```

Is there an older version of wasm-pack that generated the boilerplate without relying on webpack?  
 
Otherwise, is there a link that explains what webpack 4.0 does when loading a wasm file?

Am I correct in understanding that the current version of wasm-pack pretty much requires post-processing by a bundler?  If so, is there an advantage requiring this extra step/dependency -- is webpack doing something amazing?

thanks! nehal

**Comment by alexcrichton** [comment]
Thanks for the report! We've actually [got an example of doing this](https://rustwasm.github.io/wasm-bindgen/examples/no-modules.html), although I'd have to double check whether or not wasm-pack supports `--no-modules` just yet. In any case do those docs help your use case?

**Comment by habemus-papadum** [comment]
Thanks!  I knew there must be something like this already.  This gets me pretty close to what I had in mind. Give me a few days, and if nothing else pops up I will come back and close the issue.  Thanks again, nehal

**Comment by fitzgen** [comment]
```
wasm-pack build --target no-modules
```

should be what you're looking for
