### ISSUE TITLE
It seems the wrapper around Blob is not effective

### ISSUE THREAD

**Issue by rgiot** [rustwasm/wasm-bindgen#1168]
I'm trying to create a `Blob` object.
To do so, I added 	`Blob` and `BlobPropertyBag` to the list of features to activate for `web_sys` (version 0.3.8).

And I test with the following example:

```rust
extern crate web_sys;

#[test]
fn test_blob() {
		use crate::web_sys::Blob;
		use crate::web_sys::BlobPropertyBag;

		let mut blob = Blob::new_with_blob_sequence_and_options(
			None.into(),
			BlobPropertyBag::new().type_("application/json")
		);
}
```

I'm expecting compilation issues related to the types of the arguments, but instead, I obtain this error : 
```
error[E0599]: no function or associated item named `new_with_blob_sequence_and_options` found for type `web_sys::Blob` in the current scope
 --> tests/blob.rs:8:18
  |
8 |         let mut blob = Blob::new_with_blob_sequence_and_options(
  |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `web_sys::Blob`

error: aborting due to previous error
```

Regarding the documentation: https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.Blob.html#method.new_with_blob_sequence_and_options
I do not see why it fails

**Comment by alexcrichton** [comment]
Thanks for the report! I think this is because support is not published on crates.io yet but this is only supported on master. If you use a `git` dependency or a `[patch]` override it should work. Otherwise this will get fixed with the next publish!
