### ISSUE TITLE
add target to .gitignore for examples

### ISSUE THREAD

**Issue by dakom** [rustwasm/wasm-bindgen#1170]
Was playing around with examples and noticed that it added `target` folder to git staging

Should those folders not be `.gitignore`d?

**Comment by alexcrichton** [comment]
Hm all of the examples should be in the same workspace with a top-level `target` directory which should be ignored. This also doesn't show up for me, mind detailing how this showed up?

**Comment by dakom** [comment]
Oh... my mistake, it was when going into an individual example and byilding from there

**Comment by dakom** [comment]
I'll see if I can re-create it with a fresh clone just to be sure I didn't do something wonky

**Comment by dakom** [comment]
Heh, can't duplicate it... confirmed wonkiness on my part, sorry 'bout that!
