### ISSUE TITLE
Support for Maps

### ISSUE THREAD

**Issue by markandrus** [rustwasm/wasm-bindgen#118]
Is it planned to support Maps or other JavaScript data types in wasm-bindgen? For example,
 I would like to be able to bind a function that returns a `BTreeMap<String, String>` (unless there is a more appropriate type for maps—I'm relatively new to Rust).

**Comment by alexcrichton** [comment]
A good question! I think this is probably best done for now through something like #96 and the API would use JsValue, but would that still be too cumbersome?

**Comment by alexcrichton** [comment]
Ok I'm gonna close this in favor of https://github.com/rustwasm/wasm-bindgen/issues/96 as I think that's probably the route we'd take for this, but thanks for the report!

**Comment by couchand** [comment]
I think it would be worth supporting the limited case of string to string maps.  A handful of web APIs use them, for instance [Headers](https://developer.mozilla.org/en-US/docs/Web/API/Headers/Headers) and [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/URLSearchParams).

**Comment by alexcrichton** [comment]
@couchand in both those cases though those are dedicated classes, right? I'd imagine we'd want native bindings to them and then perhaps a helper method to convert them to a map on the Rust side?

**Comment by couchand** [comment]
Unfortunately, I don't think dedicated classes would work there, since they have arbitrary keys.

**Comment by alexcrichton** [comment]
Ah if that's the case then yeah we may need to add some more support for more maps in the future as well!
