### ISSUE TITLE
JSON.stringify with optional arguments

### ISSUE THREAD

**Issue by liamcurry** [rustwasm/wasm-bindgen#1186]
`JSON.stringify` has two optional arguments that are unsupported in `js-sys`.

- MDN docs: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify
- `js_sys::JSON::stringify` implementation: https://github.com/rustwasm/wasm-bindgen/blob/master/crates/js-sys/src/lib.rs#L3793

The two arguments are:

1. `replacer`, is nullable and can be a function or an array of `JsValue`s.
2. `space`, is nullable and can be a `str` or a number.

I imagine two new functions could be exported to support this (untested):

```rust
#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(catch, static_method_of = JSON, js_name = stringify)]
    pub fn stringify_with_replacer(obj: &JsValue, replacer: Option<&JsValue>) -> Result<JsString, JsValue>;

    #[wasm_bindgen(catch, static_method_of = JSON, js_name = stringify)]
    pub fn stringify_with_replacer_and_space(obj: &JsValue, replacer: Option<&JsValue>, space: Option<&JsValue>) -> Result<JsString, JsValue>;
}
```

**Comment by alexcrichton** [comment]
Sounds like great APIs to add to me!

**Comment by fitzgen** [comment]
Overall: yes we should totally add support for these optional parameters!

--------------------------------

Nitpicking: Does the `stringify_with_replacer` variant need to take an `Option<&JsValue>`? presumably if you weren't using a replacer you would use normal `stringify`, so it seems we don't need an `Option` here.

**Comment by liamcurry** [comment]
Makes sense to me. I assume then `stringify_with_replacer_and_space` wouldn't take an `Option<&JsValue>` in the last argument either.

**Comment by liamcurry** [comment]
I created PR #1190 to resolve this issue. Apparently `Option<&JsValue>` and `Option<JsValue>` are both unsupported:

```
error[E0277]: the trait bound `&wasm_bindgen::JsValue: wasm_bindgen::convert::OptionIntoWasmAbi` is not satisfied
    --> crates\js-sys\src\lib.rs:3769:1
     |
3769 | #[wasm_bindgen]
     | ^^^^^^^^^^^^^^^ the trait `wasm_bindgen::convert::OptionIntoWasmAbi` is not implemented for `&wasm_bindgen::JsValue`
     |
     = note: required because of the requirements on the impl of `wasm_bindgen::convert::IntoWasmAbi` for `std::option::Option<&wasm_bindgen::JsValue>`
```

So all the arguments are `&JsValue`, which is fine, people can just use `JsValue::NULL` instead of `None`.
