### ISSUE TITLE
Highlighted items are hidden in gh-pages API docs

### ISSUE THREAD

**Issue by liamcurry** [rustwasm/wasm-bindgen#1192]
Highlighted items are hidden in the Github pages API docs. Tested in Brave and Firefox.

- Example `gh-pages` URL: https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.Element.html#method.set_inner_html
- Example `docs.rs` URL: https://docs.rs/web-sys/0.3.9/web_sys/struct.Element.html#method.set_inner_html

Highlighted items are invisible due this selector in `rustdoc.css`:

```css
.in-band, code {
    z-index: -5;
}
```

![image](https://user-images.githubusercontent.com/77758/51337699-d1729300-1a55-11e9-8cd4-fc7629569653.png)

versus

![image](https://user-images.githubusercontent.com/77758/51337731-e64f2680-1a55-11e9-9d74-ea18da62a237.png)

**Comment by fitzgen** [comment]
This is a bug in rustdoc. Filed as https://github.com/rust-lang/rust/issues/57712
