### ISSUE TITLE
no method named `class_list` found for type `web_sys::Element` in the current scope

### ISSUE THREAD

**Issue by nrayamajhee** [rustwasm/wasm-bindgen#1196]
I keep getting this error event though the docs says the method is there.
> no method named `class_list` found for type `web_sys::Element` in the current scope

> https://docs.rs/web-sys/0.3.10/web_sys/struct.Element.html#method.class_list

I am trying to use it like this:
```rust
fn addEvents(&self, body: HtmlElement) {
    let click_event = Closure::wrap(Box::new(||{
        body.dyn_into::<Element>().unwrap()
        .class_list().toggle("light");
    }) as Box<dyn FnMut(_)>);
      self.theme_toggle_btn.add_event_listener_with_callback("click",click_event.as_ref().unchecked_ref());
    }
````

I am new to web_sys, so I might be missing something. My Cargo.toml looks like this:
```toml
[dependencies.web-sys]
version = "0.3.10"
features = [
  'Document',
  'Element',
  'HtmlElement',
  'HtmlBodyElement',
  'HtmlButtonElement',
  'EventTarget',
  'Node',
  'Window',
```

**Comment by limira** [comment]
You may miss this:

> This API requires the following crate features to be activated: **DomTokenList**, Element

**Comment by nrayamajhee** [comment]
That worked. thanks!
