### ISSUE TITLE
Option<enum> returns undefined

### ISSUE THREAD

**Issue by attente** [rustwasm/wasm-bindgen#1198]
Hello! I have a reproducer for this bug here: https://github.com/attente/wasm-bindgen-option

Basically:

```
use wasm_bindgen::prelude::*;

// doesn't work :(
#[wasm_bindgen]
pub fn foo() -> Option<Foo> {
    Some(Foo::Foo)
}

// works!
#[wasm_bindgen]
pub fn bar() -> Foo {
    Foo::Bar
}

// works!
#[wasm_bindgen]
pub fn baz() -> Option<i32> {
    Some(3)
}

pub enum Foo {
    Foo = 1,
    Bar = 2,
}

impl wasm_bindgen::describe::WasmDescribe for Foo {
    fn describe() {
        wasm_bindgen::describe::inform(wasm_bindgen::describe::I32)
    }
}

impl wasm_bindgen::convert::IntoWasmAbi for Foo {
    type Abi = i32;

    fn into_abi(self, _extra: &mut dyn wasm_bindgen::convert::Stack) -> Self::Abi {
        self as Self::Abi
    }
}

impl wasm_bindgen::convert::OptionIntoWasmAbi for Foo {
    fn none() -> Self::Abi {
        0
    }
}
```

Returning an `enum` that implements`wasm_bindgen::convert::OptionIntoWasmAbi` works. (`bar()`)
Returning an `Option<i32>` works. (`baz()`)
But returning `Option<enum: wasm_bindgen::convert::OptionIntoWasmAbi>` doesn't work. (`foo()`)

The output I got from the reproducer is:

```
Some(Foo::Foo) = undefined
Foo::Bar = 2
3 = 3
```

**Comment by attente** [comment]
Adding `#[wasm_bindgen]` on the `enum` causes the compiler to complain that there are multiple implementations of `wasm_bindgen::convert::traits::IntoWasmAbi` and `wasm_bindgen::describe::WasmDescribe` for type `Foo`. Fair enough, but after removing my own definitions, wasm-bindgen then complains:

```
error: failed to generate bindings for Rust export `foo`
	caused by: unsupported optional return type for calling Rust function from JS: Enum
```

**Comment by alexcrichton** [comment]
Oh dear that sounds like a bug! That may just be an unimplemented code path in wasm-bindgen's JS generating for now

**Comment by alexcrichton** [comment]
Ok option support should be added in https://github.com/rustwasm/wasm-bindgen/pull/1214
