### ISSUE TITLE
Cannot run the bindgen tool in js-hello-world example

### ISSUE THREAD

**Issue by lauransauco** [rustwasm/wasm-bindgen#120]
It compiles well, but once I try to run the bindgen tool with:
**$ wasm-bindgen target/wasm32-unknown-unknown/debug/js_hello_world.wasm \
  --out-dir .**
It appears this error:
**thread 'main' panicked at 'failed to generate bindings: Error("HeapOther(\"I/O Error: The system cannot find the path specified. (os error 3)\")")', libcore\result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.**
And if I try with RUST_BACKTRACE=1 it says:
**$ wasm-bindgen target/wasm32-unknown-unknown/debug/js
_hello_world.wasm --out-dir . RUSTBACKTRACE=1
Invalid arguments.
Usage:
    wasm-bindgen [options] <input>
    wasm-bindgen -h | --help
    wasm-bindgen -V | --version**

**Comment by alexcrichton** [comment]
Thanks for the report! Does `target/wasm32-unknown-unknown/debug/js_hello_world.wasm` exist as a file? It may have a slightly different name depending on your project

**Comment by lauransauco** [comment]
yes! it exists, that's why I'm a little bit confused. What can the problem be?

**Comment by lauransauco** [comment]
$ RUST_BACKTRACE=1 wasm-bindgen target/wasm32-unknown-unknown/debug/js_he
llo_world.wasm   --out-dir .
thread 'main' panicked at 'failed to generate bindings: Error("HeapOther(\"I/O Error: The system cannot find the path specified. (os error 3)\")")', libcore\result.rs:945:5
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: BaseThreadInitThunk
  17: RtlUserThreadStart

**Comment by lauransauco** [comment]
It looks like is working now, so I'm going to continue with the readme steps. I don't really know why is working because I just have done the same steps 3 times in the same directory with no result and now it works. Thanks anyway, you can close the issue!

**Comment by alexcrichton** [comment]
Ok great! I'll work on improving error messages soon as well
