### ISSUE TITLE
Add #[allow(clippy::*)] to all our macro-generated Rust code

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-bindgen#1200]
### What

Using `wasm-bindgen` with `clippy` results in warnings like those reported in https://github.com/rustwasm/wasm-bindgen/issues/1112 and like:

```
error: calls to `std::mem::drop` with a reference instead of an owned value. Dropping a reference does nothing.
 --> src/change_list.rs:9:5
  |
9 |     #[wasm_bindgen]
  |     ^^^^^^^^^^^^^^^
  |
  = note: #[deny(clippy::drop_ref)] on by default
  = note: argument has type &wasm_bindgen::JsValue
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#drop_ref
```

You can test it out by installing clippy:

```
rustup self update
rustup component add clippy
```

and then running clippy on `wasm-bindgen/examples/request-animation-frame`:

```
cd wasm-bindgen/examples/request-animation-frame/
cargo clippy
```

This should print out warnings like

```
warning: this function has too many arguments (8/7)
    --> crates/js-sys/src/lib.rs:3798:15
     |
3798 | #[wasm_bindgen]
     |               ^
     |
     = note: #[warn(clippy::too_many_arguments)] on by default
     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#too_many_arguments
```

We would ideally like there to be zero clippy warnings in code generated by the `#[wasm-bindgen]` macro. (Note that tehre are unrelated clippy warnings in wasm-bindgen's general code base, which we are less interested in. The goal is to support folks using clippy on projects that use wasm-bindgen.)

### How to fix

In all the top-level items we create with the `quote! { ... }` macro in `wasm-bindgen/crates/backend/src/codegen.rs`, we need to add `#[allow(clippy::*)]` to the top-level item (function or static, etc...).

**Comment by T5uku5hi** [comment]
I’d like to pick this issue up!

**Comment by fitzgen** [comment]
Let me know if you have any questions!

**Comment by T5uku5hi** [comment]
Thank you so much!

I tried to fix but I have a problem.
Please read my PR.

**Comment by Mitchell0069** [comment]
-—BEGIN PGP PUBLIC KEY BLOCK--—-—QINBFt7PakBEADNZVrXPrO2CMUfbydLxJi+QGe6znpDkSe0KCsYPvcY3dMb1Q9s x8c3etgrIAEXREBOIQ036xUTmOC87wK6KHdi0yomGmEE2U3+C4Qx1JihcsP8w2GT IPVJfmLicdVdQD/BJBSuQ+Fhs/4EIEaShqY8wUVN5am8+gzAfQw5aqWxbd2qycuw XKIxKqLr2ose3kmHE4HxvoZpdjBckOrH4HWnmk5DpQ2rJw5wC79bUkozvBb5O8Vo GHb21qfIOfqq60+L7FO7rSC7bhyeGJzEL5ws3qS3DuqYT7WhcnVpyGTGtHDfE6sj cLL0p1EUAeB2FBLt/9VfF2FpVoFvbbwpJvZMikwoLv7VXKUX/YFXml2vjKBPf2tV UoKgkGi4nBYEwuAiGppaavGsq02tB/b2nOp/vouoTqjfSYiHKyltEbULfzk1s6zP HPqnLOj/rnmOsKAWy+DLHzVf8JTxzMkgLVStk1FbHPV0EYCs2NGkLWaXcT1SebmK eYx1AoIKeGlVkl/ke7Cr5sxZEZnahAQy27wh/222NbbjHCk+XlfxbclESYd5xx1m 8oVHe+w/nxyMuMPT2pvyvLqqqQmhuaUuKA1lJaWGeZUKf2LW4UKsyCnLGWRsIrLa kCrjbElMmf2HMT2PwX2plTfC5hp0uvE/Wxuh+RX282I7T4kUqAhChIkabwARAQAB tE9BcHBsZSBQcm9kdWN0IFNlY3VyaXR5IE5vdGlmaWNhdGlvbnMgPHByb2R1Y3Qt c2VjdXJpdHktbm9yZXBseUBsaXN0cy5hcHBsZS5jb20+iQJUBBMBCAA+FiEEDNXJ VNCJJEAVmJdZeC9tht7TK3EFAlt7PcgCGwMFCQHhM4AFCwkIBwIGFQoJCAsCBBYC AwECHgECF4AACgkQeC9tht7TK3FuGw//QVN0NVcNXSIp8k08XzsF17XN4JZKXKV

**Comment by fitzgen** [comment]
Fixed in https://github.com/rustwasm/wasm-bindgen/pull/1207 -- thanks @T5uku5hi
