### ISSUE TITLE
The "right way" to wrap wasm modules created by Emscripten

### ISSUE THREAD

**Issue by ilya-edrenkin** [rustwasm/wasm-bindgen#1202]
First and foremost -- huge thanks for developing and maintaining this awesome toolset!

I'm currently facing a rather minor problem with interoperation of wasm modules. My setup is:
1) The entry point and main logic is in Rust, processed by wasm-bindgen.
2) I have to use a dependency written in C and C++ and converted to WASM via emscripten. I use ES6 module output from Emscripten and import it with webpack (using `file-loader` webpack plugin to import the wasm dependency). The bindings are created with Embind.

I want to import the functionality provided by Emscripten and use it in my Rust code.

The problem is that the Emscripten-exported module seemingly exports the symbols to the Module object only dynamically, when the wasm file is loaded. Therefore the generated code cannot do
`import { SomeClass } from MyEmscriptenModule`, as SomeClass is not defined at MyEmscriptenModule at the moment when MyEmscriptenModule is exported. And it means I cannot use `#[wasm_bindgen(module = "MyEmscriptenModule")]`

As a workaround, I am doing roughly the following in my entry point for main module:
```$ cat index.js
import MyEmscriptenModule from "my_emscripten_module";
window.MyEmscriptenModule = MyEmscriptenModule;
import "./rust_wasm_module.js";
```

And then I just use `#[wasm_bindgen(js_namespace = MyEmscriptenModule)]` to bind to the code I need. It relies on MyEmscriptenModule being available in global namespace, which feels to me like an unhealthy kludge. Unfortunately so far I was not able to devise an elegant method to bind to these symbols that are not available statically.

I believe my usecase should be pretty common, so most likely I am missing something obvious.

**Comment by chinedufn** [comment]
> I have to use a dependency written in C and C++ and converted to WASM via emscripten.

Have you taken a look at the [wasm in wasm example](https://github.com/rustwasm/wasm-bindgen/tree/master/examples/wasm-in-wasm)

If so, could you skip webpack entirely and just use your emscripten generated wasm binary directly? Or is that not an option for you?

**Comment by ilya-edrenkin** [comment]
@chinedufn thanks for the hint! Yes, I have looked at this example and I am not entirely convinced that it matches my usecase. I want to make use of all the handy auto-generated JS interfaces provided by emscripten.

The only problem is that these interfaces appear dynamically :)

As far as I understand I could use something like dynamic imports and implement a promise-based interface for all imports. However it seems to me to be even a bigger kludge than using `window` namespace (and would require much more code).

**Comment by ilya-edrenkin** [comment]
This solution pretends to work:

```
my-emscripten-dependency $ cat index.js
import MyEmscriptenModule from "./dist/my_emscripten_module.js"
import MyEmscriptenModuleWasm from "./dist/my_emscripten_module.wasm";

export var SomeClass = undefined;

const module = MyEmscriptenModule({
    locateFile: () => MyEmscriptenModuleWasm
}).then(() => {
    SomeClass = module.SomeClass;
}
);
```

The crux for me was to learn that it's possible in JS to mutate exports dynamically from the exporting module.

**Comment by BatiGencho** [comment]
@ilya-edrenkin  Hi Ilya, I know the post is closed, but I have the same issue and am trying to understand what import MyEmscriptenModuleWasm from "./dist/my_emscripten_module.wasm"; is doing. I do not see any callable functions in that import, it has lots of generics produced by Emscripten.  I am actually trying to import a game into a yew-rs project by doing this. Can you maybe give me some directions ?
