### ISSUE TITLE
How to coerce Rust memory into Javascript generically

### ISSUE THREAD

**Issue by Thomspoon** [rustwasm/wasm-bindgen#1206]
Hello,

I created a trait that would allow me to coerce slices into JS datatypes:

```rust
pub trait FromJsSys {
    fn from_js_sys(memory: &JsValue, data: Self) -> Uint8ClampedArray;
}

macro_rules! from_js_sys {
    ($type:ty, $id:ident) => {
        impl FromJsSys for $type {
            fn from_js_sys(memory: &JsValue, data: $type) -> Uint8ClampedArray {
                let data_size = data.len();
                let data_pointer = data.as_ptr() as u32;
                let data_normalization = size_of_val(&data[0]) as u32;
                let data_location = data_pointer / data_normalization;
                $id::new(&memory)
                    .slice(data_location, data_location + data_size as u32)
            }
        }
    };
}

from_js_sys!(&[f32], Float32Array);

//...

let vertices: [f32; 9] = [-0.7, -0.7, 0.0, 0.7, -0.7, 0.0, 0.0, 0.7, 0.0];
FromJsSys::from_js_sys(&vertices[..]);
```
However, when I look at the console I have the error: `wasm-bindgen: imported JS function that was not marked as `catch` threw an error: TypeError: "attempting to access detached ArrayBuffer"`

Is this due to the memory being resized?

**Comment by fitzgen** [comment]
> Is this due to the memory being resized?

Most likely yes. Whenever wasm memory grows (eg someone called `malloc`), any existing array buffer views of the memory get detached.

If wasm can be called again between uses the `Uint8ClampedArray`, it is more robust to recreate the `Uint8ClampedArray` on each use.

**Comment by Thomspoon** [comment]
So you're saying construct the Float32Array, then immediately construct a new Uint8ClampedArray using the data from the former? Is there a way to detect when a memory expansion happened? Lastly, is this going to force WebAssembly to have global variable structs where you have to reset all of them everytime you detect a memory change?

**Comment by alexcrichton** [comment]
You should be able to detect when changes happen by using `===` on two `ArrayBuffer` instances. For example in `wasm-bindgen` you'll see code that [looks like this](https://github.com/rustwasm/wasm-bindgen/blob/c56dff8edecad4219ee59d4825d0072943e97944/crates/cli-support/src/js/mod.rs#L1438-L1444) where it only recreates typed array views if the underlying buffer changed, intending to reuse instances where possible

**Comment by fitzgen** [comment]
> Lastly, is this going to force WebAssembly to have global variable structs where you have to reset all of them everytime you detect a memory change?

I would do it in the JS code that accesses the memory, like the snippet that Alex linked.

**Comment by Thomspoon** [comment]
It seems as though that Context impl is using an intrinsic wasm-bindgen function to call the JS, am I right? Would I have to create a javascript function that takes two arrays and returns if they are equal using `===`?

Also, if one is not equal, do we assume all of them are not equal and we'd have to recreate every single global buffer in our application?

**Comment by alexcrichton** [comment]
You should be able to `===` inside of Rust using `PartialEq for JsValue`, and yeah if equality doesn't hold up then anything using the previous `ArrayBuffer` needs to be recreated

**Comment by Thomspoon** [comment]
Thank you Alex, that makes a lot of sense!

**Comment by alexcrichton** [comment]
Hm I'm not sure I quite understand? But in any case all typed arrays in JS are backed by an `ArrayBuffer` and so is `WebAssembly.Memory`, but the array buffer behind `WebAssembly.Memory` can change over time and when it does you need to recreate any typed arrays that were views into the previous one. 

The `ArrayBuffer` itself is gc'd in JS and typically the same instance is shared amongst things, and AFAIK you have to explicitly clone them and no implicit clones happen.

**Comment by Thomspoon** [comment]
Ah, I was misunderstanding. So I'll need to create a new handle to my Memory JSValue when this happens, and then recreate all of the views that I had before. The only other thing that I don't understand is how would I check if the memory sized? Would I create a new memory and test it against the old one:

```rust
let test = wasm_bindgen::memory()
        .dyn_into::<WebAssembly::Memory>()
        .unwrap();

if test == old_memory {
    //.. redo memory views
}
```

**Comment by alexcrichton** [comment]
To test if it's resized you'll want to access the `buffer` property to get the underlying `ArrayBuffer` and then equate that with the previous `ArrayBuffer` which you'll want to store from before
