### ISSUE TITLE
Accessors for pub fields

### ISSUE THREAD

**Issue by dbrgn** [rustwasm/wasm-bindgen#121]
It would be nice if I could directly access public struct fields from JS:

```rust
#[wasm_bindgen]
pub struct BoundingBox {
    pub x_min: f32,
    pub x_max: f32,
    pub y_min: f32,
    pub y_max: f32,
}                                                                    
```

In JS, I'd like to be able to call `bbox.x_min` directly without having to explicitly write a getter method in Rust.

**Comment by alexcrichton** [comment]
There's currently an open question around returning references to JS to one design question here is what types to allow in public fields. One option is to `Clone` them but that could be surprising for some, and another would be to `Copy` but that's also somewhat surprising but also somewhat aligned with Rust's normal semantics when accessing a field.

@dbrgn I presume that `Copy` would probably be sufficient for your use case?

**Comment by dbrgn** [comment]
Yes, `Copy` would be perfectly fine for now.

**Comment by fitzgen** [comment]
Perhaps emit multiple accessors:

```js
borrow_field(fnOnce) {
  const reference = this.ptr + STATIC_OFFSET_OF_FIELD;
  const field = new Field(reference);
  return fnOnce(field);
}

clone_field() {
  return wasm.clone_field(this.ptr);
}

copy_field() {
  // etc...
}
```

**Comment by alexcrichton** [comment]
@fitzgen hm yeah perhaps! I was thinking though that we'd do somethign like:

```rust
class Foo {
    get field() {
        // ...
    }
}
```

to make it feel like a field access in JS. Otherwise exposing methods like that can always be done manually w/ methods and such.

I'm also not sure how to conditionally generate a method based on whether a trait is implemented :(

**Comment by fitzgen** [comment]
> I'm also not sure how to conditionally generate a method based on whether a trait is implemented :(

I think the answer is specialization, unfortunately :(

**Comment by alexcrichton** [comment]
I've implemented this in https://github.com/rustwasm/wasm-bindgen/pull/149

**Comment by dbrgn** [comment]
@alexcrichton nice, this works :)

In the future, it would probably be nice to be able to specify whether a field is readonly or not via some kind of annotation. If it's readonly, you could skip generating the setter.

**Comment by alexcrichton** [comment]
Aha an excellent idea!

**Comment by alexcrichton** [comment]
I've opened https://github.com/rustwasm/wasm-bindgen/issues/151 for that
