### ISSUE TITLE
Error loading Rust wasm module

### ISSUE THREAD

**Issue by DuckerMan** [rustwasm/wasm-bindgen#1210]
When I use wasm_bindgen I get error: ``` Error loading Rust wasm module 'hello_wasm': TypeError: WebAssembly Instantiation: Import #0 module="__wbindgen_placeholder__" error: module is not an object or function ```

My code:

``` extern crate wasm_bindgen;
use wasm_bindgen::prelude::*;

// Import the `window.alert` function from the Web.
#[wasm_bindgen]
extern "C" {
    fn alert(s: &str);
}

// Export a `greet` function from Rust to JavaScript, that alerts a
// hello message.
#[wasm_bindgen]
pub fn greet(name: &str) {
    alert(&format!("Hello, {}!", name));
}
```

**Comment by sepiropht** [comment]
Try [this](https://github.com/rustwasm/rust-webpack-template). It will help you with all boilerplate needed
to run wasm in browser

**Comment by alexcrichton** [comment]
Thanks for the report! It looks like `wasm-bindgen` may not have been exeuted or the wrong wasm file is being used perhaps? The template @sepiropht pointed out should use `wasm-pack` which should orchestrate these parts of the build, and does that help @DuckerMan?

**Comment by DuckerMan** [comment]
Yes, this have helped me, thanks

**Comment by DoumanAsh** [comment]
Sorry to bump into old issue, but to just clarify does using `wasm-bindgen` results in generating invalid WASM module unless you run some extra tooling?

**Comment by daxpedda** [comment]
Depending on `wasm-bindgen` in your Rust crate will generate a Wasm module that won't work correctly. It's technically still valid.
You have to run it through a post-processor, in this case `wasm-bindgen-cli`, to prepare it for proper consumption by a browser.
