### ISSUE TITLE
HTML in console log is interpreted in tests

### ISSUE THREAD

**Issue by dbrgn** [rustwasm/wasm-bindgen#1232]
With this test:

```
#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(js_namespace = console)]
    fn log(s: &str);
}

#[wasm_bindgen_test]
fn direct_log() {
    log("hello<br><b>world</b>");
    assert!(false);
}
```

When run like this:

    CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUNNER=wasm-bindgen-test-runner cargo test --target wasm32-unknown-unknown

...there are two places where the console output is printed.

First, after the assertion: This looks fine.

![img](https://tmp.dbrgn.ch/screenshots/20190207115819-zjeusq78.png)

But later in the console.log excerpt, the HTML seems to get interpreted:

![img](https://tmp.dbrgn.ch/screenshots/20190207115851-g_dhjteb.png)

This makes logging in tests quite useless if the logs contain < and >, since things in between are interpreted as elements.

Example project: [testproj.tar.gz](https://github.com/rustwasm/wasm-bindgen/files/2840446/testproj.tar.gz)

**Comment by chinedufn** [comment]
Likely related to #898

**Comment by fitzgen** [comment]
Fix in https://github.com/rustwasm/wasm-bindgen/pull/1233
