### ISSUE TITLE
Testing: Cleanup

### ISSUE THREAD

**Issue by dbrgn** [rustwasm/wasm-bindgen#1236]
Is there a way to get automatic cleanup of the document body between `#[wasm_bindgen_test]` based tests? Or in other words, is there a way to start all tests with a cleared initial DOM?

I'm trying to write integration tests, but the state between tests seems to persist.

**Comment by chinedufn** [comment]
I've had to solve some test collision problems here and there, so if you don't mind describing exactly how your tests look right now I'd be happy to let you know if I've run into anything similar in terms of test collisions.

I would assume that wasm bindgen test's run concurrently just like regular Rust tests. So if so the worst case scenario you can do something like `cargo test -- --test-threads=1` if there is no other reasonable solution for easily isolating your test case's.

**Comment by alexcrichton** [comment]
One way to do this would be to possibly develop a macro that resets everything just before the test starts, for example:

```rust
#[wasm_bindgen_test_clear_body]
fn foo() {
    // ...
}
```

would expand to:

```rust
#[wasm_bindgen_test]
fn foo() {
    ::my_crate::clear_body();
    // ...
}
```

**Comment by dbrgn** [comment]
I could imagine that this is an issue that affects a lot of people. Wouldn't a `wasm_bindgen_clean_test` macro in wasm-bindgen be the better approach?

**Comment by fitzgen** [comment]
If you write a file to the file system in a `#[test]` it doesn't get automatically deleted, why would writes to the DOM in `#[wasm_bindgen_test]` automatically get cleared?

With `#[test]` and temporary files, one would use something like the `tempfile` crate. I would expect that if one needs temporary/cleanup stuff for the DOM, one would use an analogous crate.

**Comment by dbrgn** [comment]
Ok, that's a valid point. My expectation is probably coming from the fact that I previously used Selenium for frontend testing, which provides a clear DOM for every test case. 

But even if no DOM cleaning is the default case (which is nice for performance), what about providing an official "reset DOM to a known state before test" attribute? That approach would be similar to the Django tests, where the default test case does not clean the database between tests, but you can optionally use the `TransactionTestCase` instead which does a rollback between test cases.

**Comment by alexcrichton** [comment]
I think a crate for cleaning the DOM could do all sorts of cool things that could range from simply clearing the HTML node to also handling things like cookies, local storage, indexed DB, etc. In that sense our general philosophy is to provide a foundation with wasm-bindgen (like libstd/libtest), but enable an ecosystem of crates to also exist to encourage lots of parallel development instead of having a bottleneck on this repository.

That being said there's of course a discoverability problem if it's not all in one repository, but that's something we can work on too! I'd be a fan, for example, of having more documentation about "recommended crates" or something like that

**Comment by dbrgn** [comment]
@alexcrichton Yep, I think you're right :slightly_smiling_face: Thanks for the explanation.

**Comment by alexcrichton** [comment]
Ok! In that case I'm gonna close this issue as we're unlikely to add this to wasm-bindgen itself, but if this exists (or if @dbrgn you make it!) we can certainly find a place to add it to the docs.

**Comment by dbrgn** [comment]
Yes, sorry, I wanted to close the issue myself but forgot :slightly_smiling_face:
