### ISSUE TITLE
"Opaque Pointer" pattern

### ISSUE THREAD

**Issue by dbrgn** [rustwasm/wasm-bindgen#1242]
This is similar to #530, although in #530 the solution was making the returned type serializable.

Is there a way to return an opaque "context object" to JS without serializing it?

What I'm trying to do, is writing an application where the state lives fully on the Rust/Wasm side. I only manipulate the state using functions/methods.

This is the approach I'm currently using, similar to FFI to C:

```rust
pub struct Context {
  pub state: State,
  pub wrapper_id: String,
}

#[wasm_bindgen]
pub fn bind_to(id: &str) -> *mut Context {
  ...
  let ctx = Box::new(Context { state, wrapper_id });
  Box::into_raw(ctx)
}

...

#[wasm_bindgen]
pub fn process_key(ctx: *mut Context, key_val: &str) {
  let mut ctx = unsafe { Box::from_raw(ctx) };
  ctx.state.modify_something();
  ...
  mem::forget(ctx);
}
```

Is this the recommended pattern to prevent unnecessary serialization between wasm and JS? (An alternative would be thread local state and RefCells, but that feels like global variables and has the downside that RefCells can get poisoned by panics.)

What happens if I dereference a raw pointer to a type that isn't a Context? From tests it seems that I got an "zero-initialized" Context object (Strings and Vecs are empty, integers are 0...), but that could be undefined behavior.

**Comment by fitzgen** [comment]
Normal `#[wasm_bindgen]`-exposed structs do not serialize and deserialize, and if you don't have any `#[wasm_bindgen]`ed methods or `pub` fields, than it should be opaque to JS.

So I think you can put that all together and do:

```rust
#[wasm_bindgen]
pub struct Context {
  state: State,
  wrapper_id: String,
}

// `Context` helpers that are not exposed to JS...
impl Context {
     // alternatively, mark the state field as `pub(crate)`
     pub fn get_state(&self) -> &State { &self.state }
     // ...
}

#[wasm_bindgen]
pub fn bind_to(id: &str) -> Context {
  ...
  Context { state, wrapper_id }
}

...

#[wasm_bindgen]
pub fn process_key(ctx: &mut Context, key_val: &str) {
  ctx.state.modify_something();
  ...
}
```

Does this work for you?

**Comment by dbrgn** [comment]
@fitzgen very nice, thanks! Yes, that helps.

I'm getting the following error though when the struct is called `Context` when calling `wasm-pack test --headless --firefox`:

```
  [3/6] Compiling tests to WASM...
     Compiling compose-area v0.1.0 (/home/danilo/Projects/compose-area)
  error: linking with `rust-lld` failed: exit code: 1
    |
    = note: "rust-lld" "-flavor" "wasm" "--no-threads" "-z" "stack-size=1048576" "--stack-first" "--allow-undefined" "--no-entry" "--fatal-warnings" "--export-dynamic" "--no-
    = note: rust-lld: error: duplicate symbol: __wbg_context_free
            >>> defined in /home/danilo/Projects/compose-area/target/wasm32-unknown-unknown/debug/deps/libcompose_area.rlib(compose_area.1zjlr9g8cstvtdrr.rcgu.o)
            >>> defined in /home/danilo/Projects/compose-area/target/wasm32-unknown-unknown/debug/deps/libwasm_bindgen_test-258015b5016fb118.rlib(wasm_bindgen_test-258015b501
```

That's probably an unrelated name collision bug, right? Is the linking done by wasm-bindgen?

**Comment by alexcrichton** [comment]
Oh heh that's a bug in wasm-bindgen, we should probably mangle those symbols more than we do now! If you rename to a different name other than `Context` you should be good to go

**Comment by dbrgn** [comment]
Yep, that worked for me.

If you want you can close this issue. I'll open a separate issue for the mangling part.

**Comment by alexcrichton** [comment]
sure thing, thanks!
