### ISSUE TITLE
suggestion: move utility functions (getStringFromWasm, etc.) into their own file

### ISSUE THREAD

**Issue by rbalicki2** [rustwasm/wasm-bindgen#125]
Hey - thank you so much for this library. I've struggled a few times to get rust and wasm working and always gave up, without getting much farther than hello world. But not with this + the amazing game of life tutorial.

Anyway, my use case is as follows. I want to use `#[wasm_bindgen(module = "./custom_imports")]` to bring in a `fetch` function into WASM-land. Obviously, fetch needs to read and pass strings and such.

For now (I'm just messing around), I am copy-pasting large chunks of the generated JS file to get functions like `passStringToWasm`, which is fine. However, it might be easier if all these utility files were exported from another file, so that they can be accessed and re-used.

Thanks!

**Comment by rbalicki2** [comment]
Hm... come to think of it, it's definitely easier to re-use `import { fetch_cb } from './generated-js-file'`, which creates a circular dependency. However, handles this case perfectly, so it's NBD.

**Comment by alexcrichton** [comment]
Thanks for the report! I'd recommend importing from the generated JS as well, yeah. Hopefully the circular dependency doesn't cause too much of a problem, but if it does please let me know!
