### ISSUE TITLE
Cannot access ANGLE_instanced_arrays or other extensions

### ISSUE THREAD

**Issue by ZacLiveEarth** [rustwasm/wasm-bindgen#1257]
I'm trying to use WebGL extensions within web_sys, but cannot seem to access the ANGLE_instanced_arrays interface that exists in this webidl - https://github.com/rustwasm/wasm-bindgen/blob/master/crates/web-sys/webidls/enabled/WebGLRenderingContext.webidl

Here is what I've tried...
let ext = context.get_extension("ANGLE_instanced_arrays").unwrap().unwrap();
let inst_arrays = ext.dyn_into::<web_sys::ANGLE_instanced_arrays>();

I've opened a related [StackOverflow question here](https://stackoverflow.com/questions/54699650/how-can-i-use-webgl-extensions-from-web-sys-in-rust): but wasn't sure that would get your attention.

Apologies if this is something obvious, today is my first day writing Rust.

**Comment by chinedufn** [comment]
I have some example code that uses `OES_vertex_array_object`. Your use case should be similar

I get the extension here: https://github.com/chinedufn/webgl-water-tutorial/blob/master/src/render/mod.rs#L52-L55

extension is stored as a `js_sys::Object` https://github.com/chinedufn/webgl-water-tutorial/blob/master/src/render/mod.rs#L29

Then you can use `Reflect::get` to call methods on it https://github.com/chinedufn/webgl-water-tutorial/blob/master/src/render/mod.rs#L219

**Comment by ZacLiveEarth** [comment]
Yes, that looks like it will work thanks for the help.

Are there any performance concerns with using Reflect and allocating an array each time there?

Is exposing a more idiomatic interface something that I could help out with? I would be willing to create a PR, but some pointing in the right direction would probably be necessary.

**Comment by chinedufn** [comment]
In practice I doubt that it would matter much for most use cases but if it did could just store the `Array` in a struct or somewhere and then re-use the same `Array` each time.

---

So I'm not sure if the WebGL extensions are specified in WebIDL (I doubt it but not sure).

If they are then `web-sys` could probably be made to auto generate the bindings but that's outside of my knowledge about the crate so I can't offer any help here - sorry!

\cc @fitzgen

**Comment by ZacLiveEarth** [comment]
> So I'm not sure if the WebGL extensions are specified in WebIDL (I doubt it but not sure).

`interface ANGLE_instanced_arrays {` is at [line 1063](https://github.com/rustwasm/wasm-bindgen/blob/master/crates/web-sys/webidls/enabled/WebGLRenderingContext.webidl#L1063)

**Comment by chinedufn** [comment]
Ohhh sweet looks like there are a bunch of extensions in there! Cool let's wait on word from someone who knows why they weren't originally included!

**Comment by alexcrichton** [comment]
I think that's currently skipped due to [this check](https://github.com/rustwasm/wasm-bindgen/blob/e9f423d57ec62fffc6d1e7788486084a753e92ae/crates/webidl/src/first_pass.rs#L306-L312) where `NoInterfaceObject` means that we skip generating bindings. I think nowadays though it may be possible to test out removing that check and see how far we get! @ZacLiveEarth would you be up for poking around in the webidl generator to see if that can be removed to solve this issue?

**Comment by ZacLiveEarth** [comment]
@alexcrichton Yes, I will take a look this afternoon. Do you have a contributor guidelines page, or a getting started contributing for the build process, etc?

**Comment by alexcrichton** [comment]
We do indeed! It all [starts here](https://rustwasm.github.io/wasm-bindgen/contributing/index.html)

**Comment by ZacLiveEarth** [comment]
Was starting by doing some research into what this attribute means, and found out that there's a PR to remove [NoInterfaceObject] from webidl entirely - [https://github.com/heycam/webidl/pull/609](https://github.com/heycam/webidl/pull/609)

**Comment by ZacLiveEarth** [comment]
Got a bit stuck. Here are some of the things I've done...

Removed the is_no_interface_object check. Building with `cargo build -vv` before this check clearly showed the log for skipping the interfaces that I'm interested in, including ANGLE_instanced_arrays. Building after does not show those log lines, and does not introduce any new lines that are concerning.

Here is the relevant output:
```
[web-sys 0.3.14] cargo:rerun-if-env-changed=__WASM_BINDGEN_DUMP_FEATURES
[web-sys 0.3.14] [2019-02-18T16:44:54Z WARN  wasm_bindgen_webidl::first_pass] Unsupported WebIDL Maplike interface member: AudioParamMap Maplike(MaplikeInterfaceMember { attributes: None, readonly: Some(ReadOnly), maplike: Maplike, generics: Generics { open_angle: LessThan, body: (AttributedType { attributes: None, type_: Single(NonAny(DOMString(MayBeNull { type_: DOMString, q_mark: None }))) }, Comma, AttributedType { attributes: None, type_: Single(NonAny(Identifier(MayBeNull { type_: Identifier("AudioParam"), q_mark: None }))) }), close_angle: GreaterThan }, semi_colon: SemiColon })
[web-sys 0.3.14] [2019-02-18T16:44:54Z WARN  wasm_bindgen_webidl::first_pass] Unsupported WebIDL Stringifier interface member: Exception Stringifier(StringifierMember { attributes: None, stringifier: Stringifier, semi_colon: SemiColon })
[web-sys 0.3.14] [2019-02-18T16:44:54Z WARN  wasm_bindgen_webidl::first_pass] Unsupported WebIDL Stringifier interface member: DOMMatrixReadOnly Stringifier(StringifierMember { attributes: None, stringifier: Stringifier, semi_colon: SemiColon })
[web-sys 0.3.14] [2019-02-18T16:44:54Z WARN  wasm_bindgen_webidl::first_pass] Unsupported webidl stringifier: DOMTokenList OperationInterfaceMember { attributes: None, modifier: Some(Stringifier(Stringifier)), special: None, return_type: Type(Single(NonAny(DOMString(MayBeNull { type_: DOMString, q_mark: None })))), identifier: None, args: Braced { open_brace: OpenBrace, body: Punctuated { list: [], separator: Comma }, close_brace: CloseBrace }, semi_colon: SemiColon }
[web-sys 0.3.14] [2019-02-18T16:44:54Z WARN  wasm_bindgen_webidl::first_pass] Unsupported WebIDL iterable interface member: DOMTokenList Iterable(Single(SingleTypedIterable { attributes: None, iterable: Iterable, generics: Generics { open_angle: LessThan, body: AttributedType { attributes: None, type_: Single(NonAny(DOMString(MayBeNull { type_: DOMString, q_mark: Some(QMark) }))) }, close_angle: GreaterThan }, semi_colon: SemiColon }))
[web-sys 0.3.14] [2019-02-18T16:44:54Z WARN  wasm_bindgen_webidl::first_pass] Unsupported WebIDL iterable interface member: FormData Iterable(Double(DoubleTypedIterable { attributes: None, iterable: Iterable, generics: Generics { open_angle: LessThan, body: (AttributedType { attributes: None, type_: Single(NonAny(USVString(MayBeNull { type_: USVString, q_mark: None }))) }, Comma, AttributedType { attributes: None, type_: Single(NonAny(Identifier(MayBeNull { type_: Identifier("FormDataEntryValue"), q_mark: None }))) }), close_angle: GreaterThan }, semi_colon: SemiColon }))
[web-sys 0.3.14] [2019-02-18T16:44:54Z WARN  wasm_bindgen_webidl::first_pass] Unsupported WebIDL iterable interface member: Headers Iterable(Double(DoubleTypedIterable { attributes: None, iterable: Iterable, generics: Generics { open_angle: LessThan, body: (AttributedType { attributes: None, type_: Single(NonAny(ByteString(MayBeNull { type_: ByteString, q_mark: None }))) }, Comma, AttributedType { attributes: None, type_: Single(NonAny(ByteString(MayBeNull { type_: ByteString, q_mark: None }))) }), close_angle: GreaterThan }, semi_colon: SemiColon }))
[web-sys 0.3.14] [2019-02-18T16:44:54Z WARN  wasm_bindgen_webidl::first_pass] Unsupported WebIDL Stringifier interface member: HTMLHyperlinkElementUtils Stringifier(StringifierMember { attributes: None, stringifier: Stringifier, semi_colon: SemiColon })
[web-sys 0.3.14] [2019-02-18T16:44:54Z WARN  wasm_bindgen_webidl::first_pass] Unsupported WebIDL Stringifier interface member: Location Stringifier(StringifierMember { attributes: Some(Bracketed { open_bracket: OpenBracket, body: Punctuated { list: [NoArgs(ExtendedAttributeNoArgs(Identifier("Throws"))), NoArgs(ExtendedAttributeNoArgs(Identifier("NeedsSubjectPrincipal")))], separator: Comma }, close_bracket: CloseBracket }), stringifier: Stringifier, semi_colon: SemiColon })
[web-sys 0.3.14] [2019-02-18T16:44:54Z WARN  wasm_bindgen_webidl::first_pass] Unsupported WebIDL iterable interface member: MediaKeyStatusMap Iterable(Double(DoubleTypedIterable { attributes: None, iterable: Iterable, generics: Generics { open_angle: LessThan, body: (AttributedType { attributes: None, type_: Single(NonAny(ArrayBuffer(MayBeNull { type_: ArrayBuffer, q_mark: None }))) }, Comma, AttributedType { attributes: None, type_: Single(NonAny(Identifier(MayBeNull { type_: Identifier("MediaKeyStatus"), q_mark: None }))) }), close_angle: GreaterThan }, semi_colon: SemiColon }))
[web-sys 0.3.14] [2019-02-18T16:44:54Z WARN  wasm_bindgen_webidl::first_pass] Unsupported WebIDL Stringifier interface member: MediaList Stringifier(StringifierMember { attributes: None, stringifier: Stringifier, semi_colon: SemiColon })
[web-sys 0.3.14] [2019-02-18T16:44:54Z WARN  wasm_bindgen_webidl::first_pass] Unsupported WebIDL Maplike interface member: MIDIInputMap Maplike(MaplikeInterfaceMember { attributes: None, readonly: Some(ReadOnly), maplike: Maplike, generics: Generics { open_angle: LessThan, body: (AttributedType { attributes: None, type_: Single(NonAny(DOMString(MayBeNull { type_: DOMString, q_mark: None }))) }, Comma, AttributedType { attributes: None, type_: Single(NonAny(Identifier(MayBeNull { type_: Identifier("MIDIInput"), q_mark: None }))) }), close_angle: GreaterThan }, semi_colon: SemiColon })
[web-sys 0.3.14] [2019-02-18T16:44:54Z WARN  wasm_bindgen_webidl::first_pass] Unsupported WebIDL Maplike interface member: MIDIOutputMap Maplike(MaplikeInterfaceMember { attributes: None, readonly: Some(ReadOnly), maplike: Maplike, generics: Generics { open_angle: LessThan, body: (AttributedType { attributes: None, type_: Single(NonAny(DOMString(MayBeNull { type_: DOMString, q_mark: None }))) }, Comma, AttributedType { attributes: None, type_: Single(NonAny(Identifier(MayBeNull { type_: Identifier("MIDIOutput"), q_mark: None }))) }), close_angle: GreaterThan }, semi_colon: SemiColon })
[web-sys 0.3.14] [2019-02-18T16:44:54Z WARN  wasm_bindgen_webidl::first_pass] Unsupported WebIDL iterable interface member: NodeList Iterable(Single(SingleTypedIterable { attributes: None, iterable: Iterable, generics: Generics { open_angle: LessThan, body: AttributedType { attributes: None, type_: Single(NonAny(Identifier(MayBeNull { type_: Identifier("Node"), q_mark: Some(QMark) }))) }, close_angle: GreaterThan }, semi_colon: SemiColon }))
[web-sys 0.3.14] [2019-02-18T16:44:54Z WARN  wasm_bindgen_webidl::first_pass] Unsupported WebIDL Stringifier interface member: Range Stringifier(StringifierMember { attributes: Some(Bracketed { open_bracket: OpenBracket, body: Punctuated { list: [NoArgs(ExtendedAttributeNoArgs(Identifier("Throws")))], separator: Comma }, close_bracket: CloseBracket }), stringifier: Stringifier, semi_colon: SemiColon })
[web-sys 0.3.14] [2019-02-18T16:44:54Z WARN  wasm_bindgen_webidl::first_pass] Unsupported WebIDL Maplike interface member: RTCStatsReport Maplike(MaplikeInterfaceMember { attributes: None, readonly: Some(ReadOnly), maplike: Maplike, generics: Generics { open_angle: LessThan, body: (AttributedType { attributes: None, type_: Single(NonAny(DOMString(MayBeNull { type_: DOMString, q_mark: None }))) }, Comma, AttributedType { attributes: None, type_: Single(NonAny(Object(MayBeNull { type_: Object, q_mark: None }))) }), close_angle: GreaterThan }, semi_colon: SemiColon })
[web-sys 0.3.14] [2019-02-18T16:44:54Z WARN  wasm_bindgen_webidl::first_pass] Unsupported webidl stringifier: Selection OperationInterfaceMember { attributes: None, modifier: Some(Stringifier(Stringifier)), special: None, return_type: Type(Single(NonAny(DOMString(MayBeNull { type_: DOMString, q_mark: None })))), identifier: None, args: Braced { open_brace: OpenBrace, body: Punctuated { list: [], separator: Comma }, close_brace: CloseBrace }, semi_colon: SemiColon }
[web-sys 0.3.14] [2019-02-18T16:44:54Z WARN  wasm_bindgen_webidl::first_pass] Unsupported WebIDL Stringifier interface member: URL Stringifier(StringifierMember { attributes: None, stringifier: Stringifier, semi_colon: SemiColon })
[web-sys 0.3.14] [2019-02-18T16:44:54Z WARN  wasm_bindgen_webidl::first_pass] Unsupported WebIDL iterable interface member: URLSearchParams Iterable(Double(DoubleTypedIterable { attributes: None, iterable: Iterable, generics: Generics { open_angle: LessThan, body: (AttributedType { attributes: None, type_: Single(NonAny(USVString(MayBeNull { type_: USVString, q_mark: None }))) }, Comma, AttributedType { attributes: None, type_: Single(NonAny(USVString(MayBeNull { type_: USVString, q_mark: None }))) }), close_angle: GreaterThan }, semi_colon: SemiColon }))
[web-sys 0.3.14] [2019-02-18T16:44:54Z WARN  wasm_bindgen_webidl::first_pass] Unsupported WebIDL Stringifier interface member: URLSearchParams Stringifier(StringifierMember { attributes: None, stringifier: Stringifier, semi_colon: SemiColon })
[web-sys 0.3.14] [2019-02-18T16:44:54Z WARN  wasm_bindgen_webidl::first_pass] Unsupported WebIDL Stringifier interface member: WorkerLocation Stringifier(StringifierMember { attributes: None, stringifier: Stringifier, semi_colon: SemiColon })
[web-sys 0.3.14] cargo:rustc-env=BINDINGS=C:\git\wasm-bindgen\target\release\build\web-sys-6530c5b6f7b8a8d8\out\bindings.rs
[web-sys 0.3.14] cargo:rerun-if-env-changed=WEBIDL_RUSTFMT_BINDINGS
```

Note that I added the logging of self_name for these logs to more easily see what was being skipped due to an usupported WebIDL.

After running cargo build, I tried both accessing the features through my project (using a [patch.crate-io] in the .toml file) and using `cargo doc --open` to search for the APIs. Cusiously, doc/web_sys/all.html does not have anything listed and running a search for ANGLE_instanced_arrays yields no results, but neither does WebGlRenderingContext.

I'm not sure what the next step forward is from here.

**Comment by ZacLiveEarth** [comment]
Some additional info:

The docs for [supporting-more-web-apis](https://rustwasm.github.io/wasm-bindgen/contributing/web-sys/supporting-more-web-apis.html) indicate that the generated rust bindings should be at target/wasm32-unknown-unknown/debug/build/ However, I only get target/debug/build (the wasm32-unknown-unknown) directory is missing. The bindings.rs file under the target that I do have is pretty sparse and doesn't appear to contain any apis.

**Comment by ZacLiveEarth** [comment]
Additionally, I have tried adding --target wasm32-unknown-unknown to the command line to cargo build, which does generate the directory under the expected path (perhaps the docs [here](https://rustwasm.github.io/wasm-bindgen/contributing/web-sys/supporting-more-web-apis.html) should be updated to add the target) but, the bindings.rs file is still sparse.

**Comment by ZacLiveEarth** [comment]
Made some progress... (is there a Discord or something where I can chat with someone in the know? I think a lot of these hangups are just learning curve and not relevant to the issue)

I found that the build does not include features unless specified. Trying to compile with all features leads to this bug - [https://github.com/rustwasm/wasm-bindgen/issues/1273](url). So, I compiled specifically with the features needed by my project.

With just these features, ANGLE_instanced_arrays does not show up in bindings.rs (though, many things do now). Unsure the mapping between a feature and the APIs, I tried searching for other examples that already have features. For example, WebGlFramebuffer. There was nothing in the source that seemed to map the feature to the list of APIs, so I concluded it must be dynamic. I tried then to add an `ANGLE_instanced_arrays = []` to the Cargo.toml file, and added the same to --features on cargo build. This did not yield any new API in bindings.rs.

Following the WebGlFramebuffer example as a guide, I guessed that perhaps adding the [Exposed] attribute would help, and added `[Exposed=(Window,Worker),
 Func="mozilla::dom::OffscreenCanvas::PrefEnabledOnWorkerThread"]` to the ANGLE_instanced_arrays interface. Again, this yielded no result.

Next, I tried outputting __WASM_BINDGEN_DUMP_FEATURES to a file, to see if it would show up there. It did not.

**Comment by alexcrichton** [comment]
We do indeed [have a discord](https://discord.gg/9e6Pvjz)! 

Looks like you've made some good progress though. In theory `__WASM_BINDGEN_DUMP_FEATURES` should work for dumping all the features, although the feature will likely not be called `ANGLE_instanced_arrays` as we rustify the name so you'll want to do a bit of a fuzzy search over the output file to see if it's in there I think

**Comment by LaylConway** [comment]
I'm interested in extensions being supported as well. A few extensions are critical for performance and quality in webgl1, with webgl2 still not being supported by Edge.

**Comment by ZacLiveEarth** [comment]
I'll probably come back to this at *some* point in the future, but it may be months from now. I needed to make progress so found another strategy for my application. If you want to take up the torch @LaylConway The conversation above lays out most of the places you might get stuck and how to get past them.

**Comment by alexcrichton** [comment]
[In a duplicate issue](https://github.com/rustwasm/wasm-bindgen/issues/1428#issuecomment-480671336) @Pauan has an excellent explanation of how to work around this temporarily
