### ISSUE TITLE
Any plans for gitter chat

### ISSUE THREAD

**Issue by madmaxio** [rustwasm/wasm-bindgen#126]
I believe the topic is interesting for a wide range of people around.

**Comment by alexcrichton** [comment]
Right now most communication happens on the `#rust-wasm` channel on the Mozilla IRC network, but I'd also be fine starting a gitter if that's too much overhead to join!

**Comment by madmaxio** [comment]
Nice!

**Comment by sendilkumarn** [comment]
slack 😉

**Comment by turboladen** [comment]
I came here wondering the same. Heading over to IRC for the first time in a while...
