### ISSUE TITLE
Cannot run wasm-bindgen's tests. "error: missing field `sessionId` at line 1 column 259"

### ISSUE THREAD

**Issue by ZacLiveEarth** [rustwasm/wasm-bindgen#1272]
Steps to reproduce:

- Clone wasm-bindgen (I used the latest commit - 9e40a6d02b8bd67fe9ed5e19e327138490ffe979)
- Follow directions at https://rustwasm.github.io/wasm-bindgen/contributing/index.html to get rust nightly
- Install browser driver, and configure with GECKODRIVER environment variable (I used Chrome 73)
- Run cargo test --target wasm32-unknown-unknown

Output:

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.19s
     Running target\wasm32-unknown-unknown\debug\deps\headless-7111f92aebb68cba.wasm
    Finished dev [unoptimized + debuginfo] target(s) in 0.33s
     Running `target\debug\wasm-bindgen-test-runner.exe C:\git\wasm-bindgen\target\wasm32-unknown-unknown\debug\deps\headless-7111f92aebb68cba.wasm`
Running headless tests in Firefox with `C:\geckodriver\chrome_72\chromedriver.exe`
driver status: exit code: 1
driver stdout:
    Starting ChromeDriver 73.0.3683.20 (8e2b610813e167eee3619ac4ce6e42e3ec622017) on port 52764
    Only local connections are allowed.
    Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.

error: missing field `sessionId` at line 1 column 259
error: process didn't exit successfully: `target\debug\wasm-bindgen-test-runner.exe C:\git\wasm-bindgen\target\wasm32-unknown-unknown\debug\deps\headless-7111f92aebb68cba.wasm` (exit code: 1)
error: test failed, to rerun pass '--test headless'

```

One suspicious line is "Running headless tests in Firefox with `C:\geckodriver\chrome_72\chromedriver.exe`", which indicates mixing Firefox and Chrome. The setup page at [https://rustwasm.github.io/wasm-bindgen/contributing/testing.html](https://rustwasm.github.io/wasm-bindgen/contributing/testing.html) indicates that I can follow to [ReadMe.md](https://github.com/rustwasm/wasm-bindgen/blob/master/crates/test/README.md) for instructions on configuring the browser, but there are no instructions about configuring a browser on that page.

**Comment by alexcrichton** [comment]
Thanks for the report! This looks like it's somewhat of a mismatch though, you're using Chrome but Firefox's geckodriver is also in use? 

Out of curiosity if you use `wasm-pack` does it solve the issue for you? (which should handle downloading all the drivers and whatnot)

**Comment by LegNeato** [comment]
I'm seeing the same thing on High Sierra:

```
Running headless tests in Safari with `safaridriver`
driver status: signal: 9                          
error: missing field `sessionId` at line 1 column 400
```

**Comment by alexcrichton** [comment]
@LegNeato just to confirm, it looks like `chromedriver.exe` above is being used to drive Firefox, but do you have something similar where `safaridriver` is driving something else perhaps? Could you provide the full logs you see?

**Comment by LegNeato** [comment]
I'm not sure...a window flashes briefly but I can't see what app it is. I've never installed chromedriver or geckodriver, though I do have Firefox Nightly installed.

There is some interesting debug output:

```
[2019-02-26T16:13:29Z DEBUG walrus::module] emitting custom section __wasm_bindgen_test_unstable
[2019-02-26T16:13:29Z DEBUG walrus::module] emission finished
[2019-02-26T16:13:29Z DEBUG tiny_http] Server listening on 127.0.0.1:54335
[2019-02-26T16:13:29Z DEBUG tiny_http] Running accept thread
Running headless tests in Safari with `safaridriver`
[2019-02-26T16:13:29Z DEBUG wasm_bindgen_test_runner::headless] POST /session {"capabilities":{},"desiredCapabilities":{}}
[2019-02-26T16:13:30Z DEBUG wasm_bindgen_test_runner::headless] got: {"status":0,"sessionId":"7E00E58A-859E-4127-9E0A-F67FBE4CB647","value":{"version":"13605.3.8","rotatable":false,"applicationCacheEnabled":true,"databaseEnabled":true,"handlesAlerts":true,"cleanSession":true,"browserName":"safari","javascriptEnabled":true,"locationContextEnabled":false,"platform":"macOS","webStorageEnabled":true,"cssSelectorsEnabled":true,"nativeEvents":true,"platformName":"macOS"}}
driver status: signal: 9                          
error: missing field `sessionId` at line 1 column 400
[2019-02-26T16:13:30Z DEBUG cargo] exit_with_error; err=CliError { error: Some(ErrorMessage { msg: "test failed, to rerun pass \'--test headless\'" }), unknown: false, exit_code: 1 }
error: test failed, to rerun pass '--test headless'
```

So the webdriver server does return json with `sessionId` but for some reason the test harness doesn't see it.

**Comment by LegNeato** [comment]
Ok, not sure if these are the same issue anymore but I found the problem and have a fix. Will put up a PR for my bug and maybe it will fix this as well if it is the same underlying issue.

**Comment by alexcrichton** [comment]
I think this was fixed in https://github.com/rustwasm/wasm-bindgen/pull/1298, so closing
