### ISSUE TITLE
Add doc comments from rust to typescript definitions

### ISSUE THREAD

**Issue by deaz** [rustwasm/wasm-bindgen#1276]
## 💡 Feature description
It would be nice to have documentation comments from rust in corresponding typescript definitions.

#### 💻 Basic example

If I have the following rust code:
```rust
#[wasm_bindgen]
/// Test comment
pub fn greet() {
    alert("Hello, test!");
}
```
I want to see `Test comment` in .d.ts file similarly to .js file:
```ts
/**
 * Test comment
 * @returns {void}
 */
export function greet(): void;
```

**Comment by alexcrichton** [comment]
I think this should be relatively simple because we already do this for JS code, we just don't do it for TypeScript yet! In that sense, although I'm not looking at the code, I suspect it's plumbing a few more things to a few more places.

**Comment by tyleranton** [comment]
I'd like to take on this issue as my first code contribution! I just need some guidance on where to go and what to look at.

**Comment by alexcrichton** [comment]
@tyleranton awesome!

You'll be most interested in `crates/cli-support`. It's not the cleanest but if you poke around there you'll find `js/mod.rs` where `typescript` is a variable that's built-up over time which is the TypeScript that we generate.

One example for exports is [around here](https://github.com/rustwasm/wasm-bindgen/blob/f3f709b1eed09221160cae219e83f52843b3ffc9/crates/cli-support/src/js/mod.rs#L2353-L2369) where the JS doc goes to the JS but not the TypeScript

**Comment by tyleranton** [comment]
I've been looking over the code trying to piece things together. I'm still not sure how everything works, but would it be enough to take the formatted comments and just push them to the `typescript` variable on `Context`?

**Comment by alexcrichton** [comment]
I think so yeah, I suspect the doc comment syntax is pretty similar across JS/TypeScript, so as long as it's all pushed in the right location it should be good to go!

If it looks wonky though we can debug further from there :)
