### ISSUE TITLE
Option to specify name of wasm module to import function

### ISSUE THREAD

**Issue by bjfish** [rustwasm/wasm-bindgen#130]
In the `js_hello_world` example, if I use:
```
#[wasm_bindgen]
extern {
    #[wasm_bindgen(js_namespace = console)]
    fn log(s: &str);
}
```
This results in the import:
```
(import "./js_hello_world" "__wbg_f_log_log_n" (func $__wbg_f_log_log_n (type 0)))
```
However, I would like to provide the `"__wbg_f_log_log_n"` function as part of an `"env"` module provided at runtime.  It would be nice if there was an option to specify which WebAssembly module to import a function from.  Can this be configured already?

I want to use this in a project I just started: https://github.com/funcdef/fdvm. I appreciate any feedback on this.

**Comment by alexcrichton** [comment]
Thanks for the report! Right now `#[wasm_bindgen]` is basically entirely geared towards ES modules and JS so going outside of those realms may not be the easiest thing to do. 

What you can do is configure the import module via:

```rust
#[wasm_bindgen(module = "env")]
extern {
     // ..
}
```

but that unfortunately also won't have the desired effect. That will still import functions like `log` from the local shim file generated (e.g. `./js_hello_world`) as a shim is required to call out to the real JS function.

Does that make sense and/or answer your question?

**Comment by alexcrichton** [comment]
I'm gonna close this for now as I think wasm-bindgen has the necessary support neede dhere, but if something isn't clear please just let me know!
