### ISSUE TITLE
web_sys::CanvasRenderingContext2d missing method 'get_image_data'

### ISSUE THREAD

**Issue by jjang4001** [rustwasm/wasm-bindgen#1301]
# Description
In the web_sys documentation, the [get-image-data](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.CanvasRenderingContext2d.html#method.get_image_data) method should be on the CanvasRenderingContext2d. However, when calling the method on an instance of the context, I get the error:
```
error[E0599]: no method named `get_image_data` found for type `web_sys::CanvasRenderingContext2d` in the current scope
```

I am on web-sys version 0.3.14, js-sys 0.3.14, and wasm-bindgen 0.2.37.

# Steps to reproduce
Run the following lines:
```
let window = web_sys::window().unwrap();
let document = window.document().unwrap();
let canvas = document
    .create_element("canvas")?
    .dyn_into::<web_sys::HtmlCanvasElement>()?;

let context = canvas
    .get_context("2d")?
    .unwrap()
    .dyn_into::<web_sys::CanvasRenderingContext2d>()?;

let _tmp_context = context.get_image_data(0, 0, 50, 50).unwrap(); // error thrown here
```
This will throw the compiler error above.

Let me know if any additional information is required.

**Comment by fitzgen** [comment]
From the `get_image_data` docs:

> This API requires the following crate features to be activated: CanvasRenderingContext2d, ImageData

Are you enabling those features? If not, then that is likely your issue.

If you are enabling those features and are still getting the error, can you share a whole crate that reproduces the error, rather than just the `src/lib.rs`? Thanks!

**Comment by jjang4001** [comment]
Oops sorry about that. Thanks!
