### ISSUE TITLE
class export is missing in generated JS if #[wasm_bindgen] is called on empty struct with no impls

### ISSUE THREAD

**Issue by rbalicki2** [rustwasm/wasm-bindgen#131]
Thanks for the amazing library!

```
#[wasm_bindgen]
pub struct MissingClass {}

#[wasm_bindgen]
pub struct Other {}

#[wasm_bindgen]
impl Other { pub fn return_a_value() -> MissingClass { MissingClass {} } }
```

if Other.return_a_value() is called from Javascript, it will result in a `MissingClass` is not defined. Adding an impl with at least one public method will fix that, though.

(Note that this isn't all that facetious of a case, as having non-wasm_bindgen'd impl's doesn't fix it :)

**Comment by alexcrichton** [comment]
Thanks for the report!
