### ISSUE TITLE
Should .slice called on TypedArray return the same type as the original?

### ISSUE THREAD

**Issue by ibaryshnikov** [rustwasm/wasm-bindgen#1317]
### Summary

In JS for example `.slice` called on Int32Array will return Int32Array.
In wasm-bindgen there is
```
pub fn slice(this: &Int32Array, begin: u32, end: u32) -> Uint8ClampedArray;
```
Should it return Int32Array instead?

**Comment by alexcrichton** [comment]
Thanks for the report! I think that this may actually just be a typo, want to send a PR to correct it?

**Comment by ibaryshnikov** [comment]
Yes, I'd like to fix it
