### ISSUE TITLE
Span doesn't implement PartialEq and Eq

### ISSUE THREAD

**Issue by c410-f3r** [rustwasm/wasm-bindgen#1320]
`Span` doesn't implement `PartialEq` and `Eq`, making the `extra-traits` feature broken.
Should `PartialEq` and `Eq` be removed or is it better to wait for an implementation?

Related: [#154](https://github.com/alexcrichton/proc-macro2/issues/154)

https://github.com/rustwasm/wasm-bindgen/blob/9f6c2a612503f99c76c3c2c0446710866f102e9f/crates/backend/src/ast.rs#L200-L210

**Comment by alexcrichton** [comment]
Oh dear this does seem bad! We probably want to remove this feature for now in that case? (removing `PartialEq` and `Eq` also seems fine to me)

**Comment by dtolnay** [comment]
I notice that ast::Function stores `name: String` and `name_span: Span` as separate fields. I would recommend storing these as one field of type proc_macro2::Ident which does have a PartialEq impl, or if the name is not guaranteed to be a legal Rust identifier/keyword then writing your own type similar to Ident to hold the name and span and provide PartialEq and any other traits you need.

**Comment by c410-f3r** [comment]
@dtolnay Thanks!
