### ISSUE TITLE
Simplify WebGL example

### ISSUE THREAD

**Issue by ibaryshnikov** [rustwasm/wasm-bindgen#1322]
### Motivation

There is a function signature
```rust
pub fn link_program<'a, T: IntoIterator<Item = &'a WebGlShader>>(
    context: &WebGlRenderingContext,
    shaders: T,
) -> Result<WebGlProgram, String> {
```
It's hard to teach, because it requires additional explanations about iterators and lifetimes.
There is also `String::from("")` and `"".into()`, which produces the question "why are they different?".

### Proposed Solution

Use distinct arguments instead of the iterator
```rust
pub fn link_program(
    context: &WebGlRenderingContext,
    vert_shader: &WebGlShader,
    frag_shader: &WebGlShader,
) -> Result<WebGlProgram, String> {
```

### Alternatives

Keep it as is

### Additional Context

I'd like to submit an update for this example if it's a good idea

**Comment by alexcrichton** [comment]
Sounds great to me! If you'd like to send a PR I'm sure we can find someone happy to review :)

**Comment by ibaryshnikov** [comment]
Should I also update it to a new behavior (like in `without-a-bundler` example)? At the moment `npm run serve` builds the page, but the code fails to run when I navigate to the browser.

**Comment by alexcrichton** [comment]
Hm these are unfortunately likely broken on master due to https://github.com/rustwasm/wasm-bindgen/issues/1318, which I hope to fix today
