### ISSUE TITLE
wasm-bindgen fails if pkg/ directory (--out-dir) does not exist

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [rustwasm/wasm-bindgen#1324]
### To reproduce:
1. Check out the recent version:
   ```
   git clone git@github.com:rustwasm/wasm-bindgen.git
   cd wasm-bindgen
   git checkout eaaf3461
   ```
2. Run without-a-bundler example:
   ```
   cd .\examples\without-a-bundler\
   cargo build --target wasm32-unknown-unknown --release
   cargo run --manifest-path ../../crates/cli/Cargo.toml --bin wasm-bindgen -- ../../target/wasm32-unknown-unknown/release/without_a_bundler.wasm --out-dir pkg --browser
   ```

These commands are from [build.sh](https://github.com/rustwasm/wasm-bindgen/blob/master/examples/without-a-bundler/build.sh), except I was running them on Windows.

### Expected

Stuff to compile, `pkg` directory with stuff to appear.

### Actual result

The last command (`cargo run ... wasm-bindgen ...`) fails with the following error:
```
error: failed to write `pkg\without_a_bundler.js`
        caused by: The system cannot find the path specified. (os error 3)
error: process didn't exit successfully: `Z:\wasm-bindgen\target\debug\wasm-bindgen.exe ../../target/wasm32-unknown-unknown/release/without_a_bundler.wasm --out-dir pkg --browser` (exit code: 1)
```

Manually creating an empty `pkg` directory fixes this.

**Comment by alexcrichton** [comment]
Thanks for the report! While somewhat intended behavior today I don't think there's any reason we can't just go ahead and create the directory if it doesn't already exist. @Vlad-Shcherbina would you be interested in sending a PR to do this? In theory it's not too hard!
