### ISSUE TITLE
Why htmlelement only has style getter but not setter?

### ISSUE THREAD

**Issue by alanpoon** [rustwasm/wasm-bindgen#1334]
### Summary

Why there is only style getter and not style setter in HtmlElement?

**Comment by limira** [comment]
In [HtmlElement.style](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.HtmlElement.html#method.style) documentation, just follow the [MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/style) link. Does the linked documentation answer your question?

**Comment by chinedufn** [comment]
Use the style getter to get the CssStyleDeclaration then use this https://docs.rs/web-sys/0.3.15/web_sys/struct.CssStyleDeclaration.html#method.set_property

**Comment by alanpoon** [comment]
thanks, I will try
