### ISSUE TITLE
wasm validation error when using webpack

### ISSUE THREAD

**Issue by alanpoon** [rustwasm/wasm-bindgen#1340]
### Summary
My qns is about web pack and wasm.
Here is my website, https://conrod.azurewebsites.net/ CompileError: "wasm validation error: at offset 47192696: expected code section" Does anybody have a clue how to solve this?

My github repo: https://github.com/alanpoon/conrod

**Comment by alexcrichton** [comment]
Thanks for the report! We've had a few issues recently related to minor bugs in webpack, so can you confirm that webpack and all its js dependencies are fully up to date?

**Comment by xtuc** [comment]
According to https://github.com/alanpoon/conrod/commit/3a7de3e41493d60b13236227eaa9f4a4fc286ab9 it's running the latest version, however this error seems like a previous version. To confirm, could you please run `npm ls | grep webpack` or similiar?

**Comment by alanpoon** [comment]
Here is the azure status badge [![Build Status](https://dev.azure.com/K1720055F/conrod/_apis/build/status/alanpoon.conrod%20(1)?branchName=master)](https://dev.azure.com/K1720055F/conrod/_build/latest?definitionId=3&branchName=master)
I have updated js dependencies. 

I suspect it has got to do with the wasm size. 4mb works on 4.29.4 and 4.29.6. 5.9 mb doesn't work on these two webpack versions.

**Comment by alexcrichton** [comment]
@alanpoon would you be up for helping out reducing this test case to an ideally minimal reproduction that we could hand the webpack folks? (and make it easier on @xtuc to investigate)

**Comment by alanpoon** [comment]
Certainly. I will put up a working and non working wasm files and the snippet of config for webpack in another repo

**Comment by alanpoon** [comment]
Here is the minimal reproduction. https://github.com/alanpoon/wer_webpack

**Comment by alexcrichton** [comment]
Thanks! @alanpoon do you want to move this over to webpack to track there as well?

**Comment by alanpoon** [comment]
added in https://github.com/webpack/webpack/issues/8928

**Comment by xtuc** [comment]
Thank you, I'll take a look at that shortly (sorry i'm moving job and country so might be slow...).
