### ISSUE TITLE
Support Importing TypeScript Definitions

### ISSUE THREAD

**Issue by davidbarsky** [rustwasm/wasm-bindgen#1341]
### Motivation

Currently, wasm-bindgen supports _exporting_ TypeScript definitions to consuming libraries and applications. It'd be handy to support _importing_ existing TypeScript definitions into Rust.

**Comment by alexcrichton** [comment]
I'm going to close this because I think it's pretty unlikely we're going to get around to doing this at this point. This would be a great feature to have and we'd be willing to consider it, but this hasn't seen activity in quite some time so I'm going to close.

**Comment by davidbarsky** [comment]
No worries. I think [WebAssembly's Interface Types](https://github.com/WebAssembly/interface-types/blob/master/proposals/interface-types/Explainer.md) solve that issue far more elegantly than a one-off Typescript to Rust conversion layer.

**Comment by ctaggart** [comment]
I've been working on a commercial application for several months now called [ts2rs](https://ts2rs.ctaggart.com/) that will support this. It is nearing initial public release. May be another month. You can follow https://medium.com/@taggartsoftware for the announcement.

I will be publishing examples sooner that that to get feedback on them. They will be under the MIT license and free to use. I'm hoping to generate examples bindings for:
- Node.js
- Electron
- VS Code

I'm open to other suggestions.

**Comment by i-schuetz** [comment]
So at the moment it's not possible to call Typescript from Rust? I also tried using a "bridge" JS file and it didn't work.

**Comment by alexcrichton** [comment]
@i-schuetz it's possible to call TypeScript from Rust (it's basically the same as calling normal JS). This issue is about auto-generate bindings (like web-sys) for TypeScript libraries since we should already know the type signatures. If you're having trouble though @i-schuetz can you open a new issue?
