### ISSUE TITLE
how to reduce the initial memory size?

### ISSUE THREAD

**Issue by laizy** [rustwasm/wasm-bindgen#1345]
### Summary

we resently tried to use wasm on a blockchain project, and find out that the initial memory allocation of the compiled wasm file is a little large (`17*64Kb`), and the data section starts from 1M . Is there some `rustc` flags to reduce the size or post-processing tool to adjust that value safely?

### Additional Details

wasm file compiled from rustc
```
(memory (;0;) 17)
(data (i32.const 1048576) "....")
```
wasm file compiled from a similiar code writen in `C` .
```
(memory (;0;) 1)
(data (i32.const 1024) "...")
```

**Comment by chinedufn** [comment]
Hey!

What does your build script look like?

If you can give a sense of what you’re running I’d be happy to let you know if there’s anything that you can do.

In the meantime should make sure that you’re using the —release flag and using wasm-opt.

https://rustwasm.github.io/docs/book/game-of-life/code-size.html

**Comment by laizy** [comment]
@chinedufn It is easy to reproduce
lib.rs
```rust
#[no_mangle]
pub fn test1(arr: [u8;2]) -> u8 {
  arr[0]
}
```
```
cargo build --release --target wasm32-unknown-unknown
wasm-opt -Os input.wasm -o opt.wasm
```
output:
```wasm
(module
  (type (;0;) (func (param i32) (result i32)))
  (func (;0;) (type 0) (param i32) (result i32)
    get_local 0)
  (memory (;0;) 16)  
  (global (;0;) i32 (i32.const 1048576))
  (global (;1;) i32 (i32.const 1048576))
  (export "memory" (memory 0))
  (export "__heap_base" (global 0))
  (export "__data_end" (global 1))
  (export "test1" (func 0))
```
seems the default minimal memory is set to 16*64kb=1M.

**Comment by chinedufn** [comment]
Ahhh gotcha so you aren’t using wasm-bindgen it seems?

In that case this issue might belong in the rust repo - but maybe someone else here will see this and know what’s going on. I don’t.

**Comment by laizy** [comment]
After some searching, discussions at https://github.com/rustwasm/team/issues/81, https://github.com/rustwasm/team/issues/247 shows the 1MB is used to store stack data. do not known how to set that value.

**Comment by alexcrichton** [comment]
The large memory size here is because we default to asking LLD to allocate a 1MB stack for all Rust binaries. If you'd like to reduce that though you can pass `-C link-arg=-zstack-size=16` to rustc, for an appropriate stack size for your application. That should allow you to shrink quite a bit!
