### ISSUE TITLE
Relative module paths regression

### ISSUE THREAD

**Issue by ZacLiveEarth** [rustwasm/wasm-bindgen#1347]
When using wasm_bindgen with a module pointing to a relative path, like so...
#[wasm_bindgen(module = "../../../../src/modules/wasm-binds.js")]

The compiler says:
error: relative module paths aren't supported yet

This worked fine in 0.2.28.

**Comment by alexcrichton** [comment]
Thanks for the report! I think this is a duplicate of https://github.com/rustwasm/wasm-bindgen/issues/1343 so I'm going to close in favor of that.
