### ISSUE TITLE
wasm-pack test does not test doc examples

### ISSUE THREAD

**Issue by najamelan** [rustwasm/wasm-bindgen#1360]
### Describe the Bug

When running wasm-pack test, it seems it doesn't run doc tests, or at least it does not report running them.

### Steps to Reproduce

1. Write a lib with some doc example
2. run wasm-pack test

### Expected Behavior

Behave similarly as normal cargo-test for other targets

### Other context

tested with versions: 
- 0.2.39 of wasm-bindgen
- 0.7 of wasm-pack
- cargo 1.35.0-nightly (0e35bd8af 2019-03-13)

**Comment by alexcrichton** [comment]
Thanks for the report! This is, however, a limitation with rustdoc and the organization of doc tests. We'd need a lot of various kinds of upstream support in rustdoc itself to get these working, so I'm going to close this for now as I think we're pretty unlikely to support this in the near future.

FWIW doc tests don't work for any cross compiled target, not just wasm.
