### ISSUE TITLE
Specialise `dyn_ref` to improve value detection

### ISSUE THREAD

**Issue by RReverser** [rustwasm/wasm-bindgen#1367]
I think `dyn_ref` should be specialised where possible to support objects from other realms (for which regular `instanceof` check would fail).

For example, it's more reliable to use `Array::is_array` instead of current `instanceof Array` for `.dyn_ref::<js_sys::Array>()`, `JsValue::is_object` for `.dyn_ref::<Object>()` and probably also existing methods for primitives for conversions to `js_sys::Number`, `js_sys::JsString` and so on.

**Comment by alexcrichton** [comment]
Can you describe what you mean by 'other realms'? Can you also elaborate on some instances that return true for `is_object` but false for `dyn_ref::<Object>`?

**Comment by fitzgen** [comment]
A realm is like a new environment with its own set of globals and all that. https://github.com/tc39/proposal-realms

Related example: if you create a new iframe and get its window's `Array`, then `[] instanceof iframeWindow.Array`  isn't true.

> Can you also elaborate on some instances that return true for `is_object` but false for `dyn_ref::<Object>`?

We must be using `typeof x === "object" && x !== null` for `is_object`.

**Comment by RReverser** [comment]
> Can you also elaborate on some instances that return true for is_object but false for dyn_ref::<Object>?

I described some of these instances in a relevant, although slightly different issue https://github.com/rustwasm/wasm-bindgen/issues/1366 - if you create a prototype-less object using `Object.create(null)`, it's not an instance of `Object` and `dyn_ref` won't detect it, but it's still a JavaScript `object` in a wider sense.

> Can you describe what you mean by 'other realms'?

In JavaScript, you can pass values between different "realms", and they each will have own prototype chain which prevents `instanceof` from working.

This is why some types provide own methods for their detection like `Array.isArray`, or why people used to do `Object.prototype.toString.call(value) === '[object Array]'` before that methods was added to the language.

Examples of such realms are `iframe`s on the browser side and `vm` module in Node.js. Arguably, passing values between them might is more of an edge case, but when you do run into it, it's nice to be covered instead of having to debug weird type errors.

**Comment by RReverser** [comment]
Btw, while looking into #1087, I realised that this above is needed not only for prototype-less `Object`s and cross-realm interaction, but also for new primitives which don't have automatic boxing.

Currently these are:

 - `Symbol`
 - `BigInt`

and for both `instanceof` check will return false when used on a corresponding primitive, because they're not objects, and so `dyn_ref` and `dyn_into` fail to recognise them too.

Example:

```rust
#[wasm_bindgen]
pub fn symbol_to_string_1(s: Symbol) -> JsString {
	s.to_string()
}

#[wasm_bindgen]
pub fn symbol_to_string_2(s: JsValue) -> JsString {
	s.dyn_into::<Symbol>().unwrap().to_string()
}

#[wasm_bindgen]
pub fn symbol_to_string_3(s: JsValue) -> JsString {
	if s.is_symbol() {
		s.unchecked_into::<Symbol>().to_string()
	} else {
		panic!("Not a symbol")
	}
}
```

Results:

```js
> require('./pkg').symbol_to_string_1(Symbol('x'))
'Symbol(x)'
> require('./pkg').symbol_to_string_2(Symbol('x'))
panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(Symbol(x))', src/libcore/result.rs:997:5
> require('./pkg').symbol_to_string_3(Symbol('x'))
'Symbol(x)'
```

@alexcrichton Do you think at least this particular instance should be considered a bug? (it certainly looks like one, as there is no way to go from `JsValue` to `Symbol` without `unchecked` right now)
