### ISSUE TITLE
Returning Self in #[wasm_bindgen] impl block aborts with error

### ISSUE THREAD

**Issue by SuperFluffy** [rustwasm/wasm-bindgen#137]
I originally reported this in https://github.com/rust-lang-nursery/rust-wasm/issues/136, where @fitzgen pointed out that this report might fit better here.

Returning `Self` instead of `Universe` in the below example gives an error, namely that the type `Self` cannot be found in this scope. Removing the `#[wasm_bindgen]` attribute above the impl block fixes compilation (I stumbled over this when going over Conway's Game of Life tutorial). This is on `wasm-bindgen 0.2.2`.

```rust
#![feature(proc_macro, wasm_custom_section, wasm_import_module)]

extern crate wasm_bindgen;

use wasm_bindgen::prelude::*;

#[repr(u8)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Cell {
    Dead = 0,
    Alive = 1,
}

#[wasm_bindgen]
pub struct Universe {
    width: u32,
    height: u32,
    cells: Vec<Cell>,
}

/// Public methods, exported to JavaScript.
#[wasm_bindgen]
impl Universe {
    // The tutorial has the signature:
    // pub fn new() -> Universe {
    pub fn new() -> Self {
        let width = 64;
        let height = 64;

        let cells = (0..width * height)
            .map(|i| {
                if i % 2 == 0 || i % 7 == 0 {
                    Cell::Alive
                } else {
                    Cell::Dead
                }
            })
            .collect();

        Universe {
            width,
            height,
            cells,
        }
    }
}
```

This gives the error:

```
error[E0411]: cannot find type `Self` in this scope
  --> src/lib.rs:70:21
   |
70 |     pub fn new() -> Self {
   |                     ^^^^ `Self` is only available in traits and impls

error: aborting due to previous error

For more information about this error, try `rustc --explain E0411`.
```

This error is very confusing, because we are obviously inside an impl block. Maybe the error should be amended to mention different behaviour for `#[wasm_bindgen]` modified blocks? Or is this a bug with the attribute?

**Comment by alexcrichton** [comment]
Ah this is definitely a bug in the attribute! I'll look to see if it can be fixed.
