### ISSUE TITLE
Implement a threadsafe version of wasm-bindgen-futures

### ISSUE THREAD

**Issue by alexcrichton** [rustwasm/wasm-bindgen#1379]
Currently the wasm-bindgen-futures crate provides a number of `unsafe` implementations to implement a runtime to execute futures within. These `unsafe` blocks, however, are predicated on the application being single threaded. The crate isn't safe in a threaded environment!

We should implement a threadsafe version of `wasm-bindgen-futures`, gated on the `target_feature = "atomics"` feature of WebAssembly!

**Comment by alexcrichton** [comment]
For those interested in getting their feet wet with the multithreading story of Rust and WebAssembly, this is definitely a meaty project to take on!

**Comment by ibaryshnikov** [comment]
So the task is to replace Cell and RefCell inside a Package struct? Would you mind if I try it?

**Comment by fitzgen** [comment]
@ibaryshnikov all yours!

I think that should do the trick, ignoring potential dead locks. I don't remember if there is `unsafe` code that needs to be updated too...

**Comment by alexcrichton** [comment]
To solve this issue the `unsafe` code from `crates/futures/src/lib.rs` basically needs to be removed, notably [these two `unsafe impl` blocks](https://github.com/rustwasm/wasm-bindgen/blob/98e554c1fa23f66f851f0e94a00d1e8894588980/crates/futures/src/lib.rs#L281-L284). Those are safe in a single-threaded scenario, but with multithreaded wasm those are legitimately unsafe.
