### ISSUE TITLE
Closure should impl Debug

### ISSUE THREAD

**Issue by Pauan** [rustwasm/wasm-bindgen#1387]
### Motivation

When implementing https://github.com/rustwasm/gloo/issues/30, I created this type:

```rust
pub struct EventListener<'a> {
    target: EventTarget,
    kind: &'a str,
    callback: Option<Closure<FnMut(Event)>>,
}
```

I would really like to just slap a `#[derive(Debug)]` and call it a day, but `Closure` doesn't impl `Debug`, so I have to do this instead:

```rust
impl<'a> std::fmt::Debug for EventListener<'a> {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.debug_struct("EventListener")
            .field("target", &self.target)
            .field("kind", &self.kind)
            .field("callback", &"Closure { ... }")
            .finish()
    }
}
```

### Proposed Solution

I propose that `Closure` should provide a `Debug` impl, which essentially just outputs `Closure { ... }` (or similar).

### Alternatives

Maybe the `Debug` impl should expose more information? For example, it could call `.toString()` on the JS function.

**Comment by fitzgen** [comment]
+1 for sure. I've done this everything-except-the-closure debug impl many times as well.

> Maybe the `Debug` impl should expose more information? For example, it could call `.toString()` on the JS function.

Don't think we should do this -- the function's source won't be anything that the user authored, just wasm-bindgen's internally defined JS source for closures.
