### ISSUE TITLE
Examples won't build

### ISSUE THREAD

**Issue by xarus01** [rustwasm/wasm-bindgen#1394]
## 🐛 Bug description
Describe your issue in detail.
Tried to build `add` example. Got this error. Seems like decode method is supposed to empty data argument but somethings not right.

#### 🤔 Expected Behavior
What should have happened?
.wasm file should have been built.

#### 👟 Steps to reproduce
Clear steps describing how to reproduce the issue, including commands and flags run. If you are seeing an error, please include the full error message and stack trace.
```
root@d81f6ae3a3a8:/wasm-bindgen/examples/add# RUST_BACKTRACE=1 wasm-pack -vvv build
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
    Finished release [optimized] target(s) in 0.16s
[INFO]: Installing wasm-bindgen...
thread 'main' panicked at 'assertion failed: data.len() == 0', crates/cli-support/src/decode.rs:8:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: wasm_bindgen_cli_support::Bindgen::_generate
   7: wasm_bindgen::main
   8: std::rt::lang_start::{{closure}}
   9: std::panicking::try::do_call
  10: __rust_maybe_catch_panic
  11: std::rt::lang_start_internal
  12: main
Error: Running the wasm-bindgen CLI
Caused by: failed to execute `wasm-bindgen`: exited with exit code: 101
```

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: 0.7.0
rustc version: nightly-2019-03-25

**Comment by alexcrichton** [comment]
Thanks for the report! I think this is a bug with wasm-bindgen's examples though, so I'm going to move it to this repository.

Unfortunately what's happening here is that https://github.com/rustwasm/wasm-bindgen/issues/1227 isn't implemented, and the `wasm-bindgen` CLI from crates.io is being used with the `wasm-bindgen` crate from git, causing a version mismatch. Version mismatches of the CLI and `wasm-bindgen` crate are a well known source of errors, and while we catch some #1227 shows that we don't catch all of them!

**Comment by xarus01** [comment]
@alexcrichton Thanks a lot! I tried to build examples outside the cloned wasm-bindgen directory and it works. Would like to give a try on #1227 but not sure where to start. Any hint?

**Comment by alexcrichton** [comment]
Sure yeah! The general idea is that [this version check](https://github.com/rustwasm/wasm-bindgen/blob/30b258515d197fcb9bc3b6e6e5ee50d82c4be2be/crates/cli-support/src/lib.rs#L605) is passing but it needs to fail when git/crates.io are involved. This *may* be as simple as using [this string as a version instead](https://github.com/rustwasm/wasm-bindgen/blob/30b258515d197fcb9bc3b6e6e5ee50d82c4be2be/crates/shared/src/lib.rs#L179-L187) which includes git commit information, although I'm not certain

**Comment by c410-f3r** [comment]
@xarus01 I am also having trouble with `examples`. Are you still working on this issue?

**Comment by montag** [comment]
To run the examples from the repo, you can build the cli in /crates/cli and then add the binary to your path.

**Comment by alexcrichton** [comment]
I'm gonna go ahead and close this in favor of https://github.com/rustwasm/wasm-bindgen/issues/1227
