### ISSUE TITLE
wait Promise response

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [rustwasm/wasm-bindgen#1411]
Based on this [example](https://rustwasm.github.io/wasm-bindgen/examples/fetch.html)
It's possible to make a request, and get data from an HTTP Query.

I have take a look on [wasm-bindgen future](https://rustwasm.github.io/wasm-bindgen/api/wasm_bindgen_futures/) to understand who it works.

But I'm not able right now to wait a response in a rust code, to continue process based on response.

The idea is to build a code like:
```rust

#[wasm_bindgen]
pub fn get_some_data() -> Branch {
  make_http_call("http://example.com/endpoint")
  .then(
     // What code should be wrote here to return a Branch ?
  )
}

#[wasm_bindgen]
pub fn make_http_call(url: &str) -> Promise {
  // make HTTP call and return Promise like the Fetch example
}
```

Thanks for any help

**Comment by alexcrichton** [comment]
Thanks for the report! Unfortunately though this isn't something that's possible today on the web. On the main thread you're not allowed to block, so once a `Promise` or a `Future` is used it needs to continue to be so all the way out to the outer JS and beyond.

**Comment by Pauan** [comment]
@MarcAntoine-Arnaud Basically, what that means is that once you start using Promises/Futures, you have to *keep* using Futures all the way, you can't "unwrap" it to get the value.

However, it is possible to use [`spawn_local`](https://rustwasm.github.io/wasm-bindgen/api/wasm_bindgen_futures/fn.spawn_local.html) to run a Future.

By doing that, it's now possible to access the `Branch`, like this:

```rust
use wasm_bindgen::throw_val;

pub fn get_some_data() -> impl Future<Item = Branch, Error = JsValue> {
  make_http_call("http://example.com/endpoint")
  .then(
    // ...
  )
}

fn main() {
  spawn_local(
    get_some_data()
      .map(|branch| {
        // use branch in here...
      })
      .map_err(|error| {
        throw_val(error);
      })
  );
}
```

It's important to note that you can only access the branch inside of the `.map(|branch| { ... })`

**Comment by MarcAntoine-Arnaud** [comment]
Thanks @Pauan for your update too.
It work pretty well now.

Do you know how to update an object ?
I wanna to to something like that:

```rust
use wasm_bindgen::throw_val;

#[wasm_bindgen]
#[derive(Clone, Debug, Default)]
pub struct Project {
  pub branch: Option<Branch>,
}

pub fn get_some_data() -> impl Future<Item = Branch, Error = JsValue> {
  make_http_call("http://example.com/endpoint")
  .then(
    // ...
  )
}

fn main(renderer: &mut Renderer) {
  spawn_local(
    get_some_data()
      .map(|branch| {
        renderer.branch = Some(branch);
      })
      .map_err(|error| {
        throw_val(error);
      })
  );
}

```

But I cannot do it, I have a lifetime error (which was logic).
I have take a look on Closure, but it's similar too.

Thanks again !

**Comment by MarcAntoine-Arnaud** [comment]
In fact the question can be also:
is it possible to return a Javascript object into a Promise (not a serialised object with serde) ?

**Comment by Pauan** [comment]
> But I cannot do it, I have a lifetime error (which was logic).

Because Futures are run asynchronously, they cannot contain references (like `&` or `&mut`).

So you'll need to instead take the `Renderer` by value (and also probably `move` it into the closure):

```rust
fn main(mut renderer: Renderer) {
  spawn_local(
    get_some_data()
      .map(move |branch| {
        renderer.branch = Some(branch);
      })
      .map_err(|error| {
        throw_val(error);
      })
  );
}
```

If you want to use the `Renderer` in multiple places, then you'll need to use `Rc` (and `RefCell` for mutation):

```rust
fn main(renderer: Rc<RefCell<Renderer>>) {
  spawn_local(
    get_some_data()
      .map(move |branch| {
        let mut renderer = renderer.borrow_mut();
        renderer.branch = Some(branch);
      })
      .map_err(|error| {
        throw_val(error);
      })
  );
}
```

> is it possible to return a Javascript object into a Promise (not a serialised object with serde) ?

If you use `JsValue` (or any of the `JsCast` wrapper types), then it isn't serialized.

And if you use `future_to_promise` then you can convert a `Future` which returns `JsValue` into a `Promise`.
