### ISSUE TITLE
How can I store a vector of JS object references

### ISSUE THREAD

**Issue by lirhtc** [rustwasm/wasm-bindgen#1421]
### Summary

Is there a way I can store JS references into a vector? I have tried to store a vector of JS object but I always got an error saying _explicit lifetime required_. But I don't know where can I add the lifetime decorator.

### Additional Details

I have an JS object which has a property 'mass'. I defined the object in rust as:

```
#[wasm_bindgen(module = "/class_defined.js")]
extern "C" {
    pub type Shape;
    #[wasm_bindgen(method, getter, structural)]
    pub fn get_mass(this: &Shape) -> f64;
    #[wasm_bindgen(method, setter, structural)]
    pub fn set_mass(this: &Shape, value: f64);
}
```

To store the JS object in rust, I create a struct called container in Rust:

```
pub struct Container {
    shapes: Vec<&Shape>, // complains expected lifetime parameter
}

#[wasm_bindgen]
impl Container {
    pub fn new() -> Container {
        Container {
            shapes: Vec::<&Shape>::new(),
        }
    }

    pub fn add_one(&mut self, one: &Shape) {
        self.shapes.push(one); // complains explicit lifetime required in the type of `one`. lifetime `'static` required
    }
}
````

I tried to add `'static` to the structure definition but I have no idea how to fix the complain in the `push` function.

**Comment by Pauan** [comment]
Using `Vec<Shape>` should work fine: the types created by wasm-bindgen are already references (at least internally), so you don't need the `&`.

If you want to use a `Shape` in multiple places, you can explicitly call `shape.clone()` (this is very fast, since it doesn't actually copy the object, it just increments the reference).

**Comment by lirhtc** [comment]
Thanks @Pauan for the suggestion and explanation . That does solve the problem for me.
