### ISSUE TITLE
Add `wasm_bindgen::function_table()`

### ISSUE THREAD

**Issue by koute** [rustwasm/wasm-bindgen#1427]
So I finally started implementing `wasm-bindgen` compatibility in `stdweb`, [and it works](https://github.com/koute/stdweb/tree/master/examples/wasm-bindgen-minimal)! It is however not yet entirely functional - for that I need access to the function table of the WASM's module. In [the RFC](https://github.com/rustwasm/rfcs/blob/master/text/006-local-js-dependencies.md) it was said that an extra `wasm_bindgen::function_table()` intrinsic will be added to access the function table; from what I can see that hasn't been done yet?

Any way I can help?

**Comment by alexcrichton** [comment]
Oops, sorry for the omission! I've pushed up https://github.com/rustwasm/wasm-bindgen/pull/1431 which should add this
