### ISSUE TITLE
Parallel Raytracing demo broken

### ISSUE THREAD

**Issue by ZacLiveEarth** [rustwasm/wasm-bindgen#1435]
### Describe the Bug

Visiting [this page](https://rustwasm.github.io/wasm-bindgen/exbuild/raytrace-parallel/) the button for rendering never activates, but instead shows "Loading wasm..." indefinitely.

### Steps to Reproduce

Load the page after enabling shared memory buffers

### Additional Context

In Firefox, the console reports this...

```
`WebAssembly.instantiateStreaming` failed. Assuming this is because your server does not serve wasm with `application/wasm` MIME type. Falling back to `WebAssembly.instantiate` which is slower. Original error:
 CompileError: "wasm validation error: at offset 4088: unknown section before code section" raytrace_parallel.js:610:17
TypeError: "Body has already been consumed."
    result https://rustwasm.github.io/wasm-bindgen/exbuild/raytrace-parallel/raytrace_parallel.js:612
```

**Comment by alexcrichton** [comment]
Note that the demo currently requires Firefox Nightly and for a few features to be enabled. It does its best job to alert you to this if it's not working, but it seems to clearly not be working!

**Comment by alexcrichton** [comment]
(and FWIW in nightly the demo continues to work for me tonight, so this is likely a local configuration issue)

**Comment by ZacLiveEarth** [comment]
Ah, yes. I was on the beta channel, not the nightly channel. It turns out once you enable the shared memory buffer, the page no longer warns you to switch to nightly. This is minor, closing.
