### ISSUE TITLE
No documentation found 404

### ISSUE THREAD

**Issue by ibrahimpmahmood** [rustwasm/wasm-bindgen#1437]
### Describe the Bug

The documentation was removed or moved somewhere(If so, is undocumented 🥇)

### Steps to Reproduce

1. Go to 'https://rustwasm.github.io/docs/wasm-bindgen/'
2. See error

### Expected Behavior

Should go to the documentation and show examples.

### Actual Behavior

Gives 404 error.

### Additional Context

Was there a recent bad merge that happened?

**Comment by alexcrichton** [comment]
Thanks for the report! Should be fixed now although may take a few more minutes for caches to empty
