### ISSUE TITLE
Remove `extends = Object` from `js_sys::{Number,JsString}`?

### ISSUE THREAD

**Issue by alexcrichton** [rustwasm/wasm-bindgen#1445]
In https://github.com/rustwasm/wasm-bindgen/pull/1405 we seem to be leaning towards `JsString` both representing the native `String` class as well as the string primitive in JS. I suspect we'd want to do the same for `Number` too!

Currently, though, both these types inhereit from `Object` which means they `Deref` to `Object`. If we use native strings in `JsString` (which we actually already do) then this may not be quite right. 

Should we remove the `extends` annotation from these types so they both deref to `JsValue`?

**Comment by alexcrichton** [comment]
cc @Pauan, you've likely got thoughts on this!

**Comment by RReverser** [comment]
This is still fine, as they do inherit all the methods from `Object`.

**Comment by Pauan** [comment]
My thoughts on this are rather nuanced, so I'll need a bit of time to formulate a response, but @RReverser is correct that the `Object` methods should continue to work fine.

**Comment by alexcrichton** [comment]
Ah ok intersting! I was unware of that :)

I'm gonna go ahead and close this, but @Pauan if you feel there's action that we need to take here a new issue/PR would be good!

**Comment by Pauan** [comment]
Well, I had a detailed reply all written up, but after thinking about it, I like the current plan better: shift `Number`/`Boolean`/`String` to use primitives, but continue to have them extend from `Object`.
