### ISSUE TITLE
Typescript files: Add docs for methods

### ISSUE THREAD

**Issue by dbrgn** [rustwasm/wasm-bindgen#1468]
## 💡 Feature description

In the Typescript declaration files that are generated, the struct docstrings are included but the method docstrings aren't. It would be great if methods were documented too.

#### 💻 Basic example

Rust:

```rust
/// The context object containing the state.
#[wasm_bindgen]
pub struct ComposeArea {
    window: web_sys::Window,
    document: web_sys::Document,
    wrapper_id: String,
    selection_range: Option<Range>,
}

#[wasm_bindgen]
impl ComposeArea {
    /// Insert plain text at the current caret position.
    pub fn insert_text(&mut self, text: &str) {
        let text_node = self.document.create_text_node(text);
        self.insert_node(text_node.unchecked_ref());
    }
}

 ```

Current type declaration:

```typescript
/**
* The context object containing the state.
*/
export class ComposeArea {
  insert_text(text: string): void;
}
```

Desired type declaration:

```typescript
/**
* The context object containing the state.
*/
export class ComposeArea {
  /**
   * Insert plain text at the current caret position.
   */
  insert_text(text: string): void;
}
```

**Comment by alexcrichton** [comment]
Thanks for the report! I've transferred this issue to the `wasm-bindgen` repository since this is where the fix will go, but I believe this is definitely something we should fix!

**Comment by c410-f3r** [comment]
`wasm-bindgen` already generates docs for JS and it shouldn't be too difficult to implement it for TS. If no one is going to take on this issue, I will gladly send a PR.

**Comment by alexcrichton** [comment]
Indeed yeah, and PRs are most welcome!

**Comment by dbrgn** [comment]
Cool, thanks @c410-f3r!
