### ISSUE TITLE
Promise::all usage. How to get an array from JsValue?

### ISSUE THREAD

**Issue by lykhouzov** [rustwasm/wasm-bindgen#1480]
I am trying to load few resources on a web. example of `fetch` is working.
But...
How could I get a value of `JsValue` object?
and the main question is how could I use `Promise::all` function to load several resources
For example, I do like
```rust
let p0: Promise = fetch("/shaders/block_fragment.glsl");
let p1: Promise = fetch("/shaders/block_vertex.glsl");
let arr = Array::new();
arr.push(&JsValue::from(p0));
arr.push(&JsValue::from(p1));
Promise::all(Promise::all(&arr));
```
And then I get a problem to get value from `JsValue`, because it contains and array of 2 strings
and I cannot cast it to a rust object. It would be easier if it would be an array of 2 `JsValue` with string inside.

Could you help me to understand how it could work?
Thank you.

**Comment by alexcrichton** [comment]
Thanks for the report! You should be able to use the `JsCast` trait to convert between various types. For example when `Promise::all` resolves you can use `promise_to_future` to manage a Rust future that generates a `JsValue`, and then use `.dyn_ref()` to convert that to an `&js_sys::Array` for example. Does that help?

**Comment by lykhouzov** [comment]
Thank you @alexcrichton 
it looks like it works.
My First attempt was 
```rust
fn example1() {
    let p0: Promise = fetch("/shaders/block_fragment.glsl");
    let p1: Promise = fetch("/shaders/block_vertex.glsl");
    let arr = Array::new();
    arr.push(&JsValue::from(p0));
    arr.push(&JsValue::from(p1));
    let res = JsFuture::from(Promise::all(&arr)).and_then(|x| {
        let arr: Array = x.dyn_into().unwrap();
        let mut res: [String; 2] = [String::new(),String::new()];
        let mut i = 0;
        for v in &arr.values() {
            let source: String = v.unwrap().as_string().unwrap();
            res[i] = source;
            i += 1;
        }
        log!("My result {:?}", res);
        future::ok(res)
    }).and_then(|a|{
        future::ok(JsValue::from("OK"))
    });
    future_to_promise(res);
}
```
But then I've checked fetch example one more time and got following:
```rust
fn example1() {
    use serde_json::{Result, Value};
    let p0: Promise = fetch("/shaders/block_fragment.glsl");
    let p1: Promise = fetch("/shaders/block_vertex.glsl");
    let arr = Array::new();
    arr.push(&JsValue::from(p0));
    arr.push(&JsValue::from(p1));
    let res = JsFuture::from(Promise::all(&arr)).and_then(|x| {
        let a: Value = x.into_serde().unwrap();
        // a as expected [String, String]
        future::ok(a)
    }).and_then(|a|{
        future::ok(JsValue::from("OK"))
    });
    future_to_promise(res);
}
```
Thank you for the help

**Comment by alexcrichton** [comment]
Great! In that case I'll close this
