### ISSUE TITLE
Error: WebGL warning: texImage2D: Invalid internalformat: 0x1903

### ISSUE THREAD

**Issue by alanpoon** [rustwasm/wasm-bindgen#1481]
### Summary
Encounter 
Error: WebGL warning: texImage2D: Invalid internalformat: 0x1903

### Additional Details
Used R8 as format because of rendering text. Also used web_sys::WebGl2RenderingContext. 
According to https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/texImage2D,
R8 should be supported in webgl2.
Running on firefox quantum 66.0.3

**Comment by ZacLiveEarth** [comment]
I don't think this is the appropriate place for general webgl/rendering questions. You may find a better response on StackOverflow.

**Comment by alexcrichton** [comment]
It's true yeah that this isn't the best place for WebGL questions, but if you have a wasm-related spin on the question we can try to help out!
