### ISSUE TITLE
Cargo workspaces breaks (seems to break?) wasm-bindgen

### ISSUE THREAD

**Issue by rbalicki2** [rustwasm/wasm-bindgen#150]
I had an existing project that used wasm-bindgen, which worked. Then, I moved the folder into a sub-folder `frontend`, and create a top-level Cargo.toml as follows:

```
[workspace]

members = [
    "frontend",
]
```

Now, running `cargo +nightly build --target wasm32-unknown-unknown` creates a target folder in the top-level folder. When that happens,  (from the sub-folder) `wasm-bindgen ../target/wasm32-unknown-unknown/debug/wasm_website_frontend.wasm --out-dir ./dist` fails with

```
thread 'main' panicked at 'failed to decode what looked like wasm-bindgen data: missing field `arguments` at line 1 column 263', /Users/robertbalicki/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-cli-support-0.2.2/src/lib.rs:201:21
```

The only way I can get this to work is to remove the top-level `Cargo.toml` (which is fine for my use case.)

Just FYI.

**Comment by alexcrichton** [comment]
Ah sorry this looks like it's probably a version mismatch between the CLI and the crate, want to update one of the two and try again?

**Comment by rbalicki2** [comment]
I'm not sure, because when I updated rust nightly and wasm bindgen everything broke ;) oh well! Got a 

```
 = note: Undefined symbols for architecture x86_64:
            "___wbindgen_throw", referenced from:
                wasm_bindgen::throw::h287c6c8d8e976c6e in libwasm_bindgen-de37e34c3952750b.rlib(wasm_bindgen-de37e34c3952750b.wasm_bindgen7.rcgu.o)
            "___wbindgen_describe", referenced from:
                wasm_bindgen::describe::inform::heb5ec36ac4978926 in libwasm_bindgen-de37e34c3952750b.rlib(wasm_bindgen-de37e34c3952750b.wasm_bindgen12.rcgu.o)
               (maybe you meant: ___wbindgen_describe_looper_start_loop, ___wbindgen_describe_looper_on_event )
            "___wbg_f_initialize_initialize_n", referenced from:
                wasm_website_frontend::js::initialize::h7a8436a54e590c6e in wasm_website_frontend.4ugtj5014xuimboh.rcgu.o
            "___wbg_f_log_js_log_n", referenced from:
                wasm_website_frontend::js::js_log::h62c50da5d56d1062 in wasm_website_frontend.4ugtj5014xuimboh.rcgu.o
            "___wbg_f_render_render_n", referenced from:
                wasm_website_frontend::js::render::h9f2832f0768ff9eb in wasm_website_frontend.4ugtj5014xuimboh.rcgu.o
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by csharad** [comment]
>  it's probably a version mismatch between the CLI and the crate

Check if `wasm-bindgen` CLI and dependency of your project are on the same version.

**Comment by rbalicki2** [comment]
heh, they weren't the same, but it didn't fix the above issue. Ok, I'll continue to investigate and try downgrading nightly. When that works I'll see whether making the versions the same will fix the original issue.
