### ISSUE TITLE
WebGl2RenderingContext can not be stored globally

### ISSUE THREAD

**Issue by sketchpunk** [rustwasm/wasm-bindgen#1505]
### Describe the Bug
Trying to save WebGl2RenderingContext globally using things like lazy_static and the likes. Tells me that it does not implement std::marker::Send. Either direction I want to build my engine, I need to store the context for later access. So this hampers things.

### Steps to Reproduce
```
43 | / lazy_static! {
46 | |     static ref TMP : Mutex< Vec<WebGl2RenderingContext> > = Mutex::new( Vec::new() );
47 | | }
   | |_^ `*mut u8` cannot be sent between threads safely
   |
   = help: within `web_sys::WebGl2RenderingContext`, the trait `std::marker::Send` is not implemented for `*mut u8`
   = note: required because it appears within the type `std::marker::PhantomData<*mut u8>`
   = note: required because it appears within the type `wasm_bindgen::JsValue`
   = note: required because it appears within the type `js_sys::Object`
   = note: required because it appears within the type `web_sys::WebGl2RenderingContext`
If applicable, add a link to a test case (as a zip file or link to a repository we can clone).
```

**Comment by Pauan** [comment]
This is because JS values cannot be sent between threads (this is a limitation in the Wasm/JS engines, so there's nothing we can do about it).

Multi-threading isn't quite fleshed out yet, but in the meantime you can use [`thread_local`](https://doc.rust-lang.org/nightly/std/macro.thread_local.html) instead of `lazy_static` (this will create one `WebGl2RenderingContext` per thread, but in practice there's only one thread):

```rust
thread_local! {
    static TMP: Mutex<Vec<WebGl2RenderingContext>> = Mutex::new(Vec::new());
}

TMP.with(|tmp| {
    // ...
})
```

**Comment by sketchpunk** [comment]
thanks. Even though thread_local! kinda works but its not easy to use the way I would like. Having to use a closure to run each webgl command seems a bit much. There has to be some easy way to store a value globally then some easy method to get back a reference be it r or rw. I've looked into other things like Rc, RWLock, Arc, RefCell. Can't seem to get any solution to work.

Guess this issue isn't a bug, more my lack of knowledge to get this working in rust.

**Comment by Pauan** [comment]
It is possible to use `lazy_static` if you create a wrapper type and then impl `Send` and `Sync` on it:

```rust
struct WebGlContext {
    contexts: RefCell<Vec<WebGl2RenderingContext>>,
}

unsafe impl Send for WebGlContext {}
unsafe impl Sync for WebGlContext {}

lazy_static! {
    static ref TMP: WebGlContext = WebGlContext {
        contexts: RefCell::new(Vec::new()),
    };
}
```

This is only safe because wasm is currently single-threaded. It won't be safe when wasm becomes multi-threaded.
