### ISSUE TITLE
Get Struct back in rust

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [rustwasm/wasm-bindgen#1509]
I need to process multiple Promises in parallel, in the result I obtain an Array of Object, which was perfect until here (`Array { obj: Object { obj: JsValue([Object({"ptr":1116768}), Object({"ptr":1116920})]) } } `).

I can iterate and get Object. But I cannot get back the struct returned (generated from `JsValue::from(my_struct_instance)`).
I found nothing to "revert" the `JsValue::from` and get back the rust instance: `JsValue::into`don't work, `as_ref()` etc. don't return the rust instance.

Do you have any idea who to do that ?

Thanks,
Marc-Antoine

**Comment by fitzgen** [comment]
You're probably looking for the `JsCast` trait, which enables both checked and unchecked conversions between different kinds of JS objects and values: https://docs.rs/wasm-bindgen/0.2.43/wasm_bindgen/trait.JsCast.html

**Comment by alexcrichton** [comment]
Oh actually I think that this currently cannot be done from within wasm itself. Once you've wrapped a Rust struct in a `JsValue`, the only way currently to unwrap it is to call a by-value-`self` method on the JS object itself, which will do the unwrapping. That being said I suspect that we can probably quite improve the situation here!

@fitzgen on in this case I don't think that `JsCast` works because `JsCast` is only intended for wrappers around `JsValue`, so Rust structs don't implement `JsCast`

**Comment by fitzgen** [comment]
Ah, yeah I read too quickly.

**Comment by MarcAntoine-Arnaud** [comment]
Thanks for your feedbacks @alexcrichton & @fitzgen.
In fact I'm trying to init my structure with many HTTP requests (so 1 per future to do them in async mode).
After that I wanna to "wait" the end of all requests to return the "complete" status of the initialisation.
So for that I have converted Future in Promise, and use the `Promise.all` to merge Futures, then convert the resulting promise in a future to get result (it's a `Vec<Message>`) but I get it into a JsValue.
I think yes it's possible to convert back using an unsafe copy but I don't found any information on it.

So for this use case I see 2 potential solutions:
- merge requests without passing by a Promise, but how to wait ending of all Future ?
- convert back the raw pointer into a structure, but I have no idea how to wrote it ...

**Comment by Pauan** [comment]
@MarcAntoine-Arnaud If you want to run multiple Futures in parallel (and wait for them to complete), you can use the [`join_all`](https://docs.rs/futures/0.1.26/futures/future/fn.join_all.html) function, or the various [`join`](https://docs.rs/futures/0.1.26/futures/future/trait.Future.html#method.join) methods.

Or you can also use [`FuturesUnordered`](https://docs.rs/futures/0.1.26/futures/stream/futures_unordered/struct.FuturesUnordered.html), which lets you dynamically add new Futures to a list, and then wait for all of those Futures to finish (by using the `FuturesUnordered` as a stream).

**Comment by MarcAntoine-Arnaud** [comment]
Hoo yeah, I have tested it, and `join_all` works perfectly.
Thank you @Pauan
