### ISSUE TITLE
Get Transferable in Rust

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [rustwasm/wasm-bindgen#1516]
Hi (again),

Following my work, I start a worker and I send a message to it (to an image decoder).
After the decoding I wanna to get back on the Rust object so I plan to use the `onmessage` method.

I cannot arrive to get back the data ArrayBuffer as I need to send it with [postMessage including a transferable object](https://developer.mozilla.org/fr/docs/Web/API/Worker/postMessage).

Do you know if we can get back the ArrayBuffer in Rust ?

Thanks,
Marc-Antoine

**Comment by alexcrichton** [comment]
Thanks for the report! Until `SharedArrayBuffer` is stable the only way to transfer data between workers on the web is to do full copies which means you can't send a Rust struct from one thread to another with workers. For that you may want to use JSON and/or the serde support!

**Comment by Pauan** [comment]
@alexcrichton Actually, transferrable objects don't have anything to do with `SharedArrayBuffer`.

They're a special kind of object which can be sent between Workers without a copy.

Right now [that means `ArrayBuffer`, `MessagePort`, `ImageBitmap`, and `OffscreenCanvas`](https://developer.mozilla.org/en-US/docs/Web/API/Transferable) (but more types might become transferrable in the future).

----

@MarcAntoine-Arnaud You would use the [`post_message_with_transfer`](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.Worker.html#method.post_message_with_transfer) method, like this:

```rust
let worker = ...;
let array_buffer = ...;

worker.post_message_with_transfer(&array_buffer, &Array::of1(&array_buffer)).unwrap_throw();
```

Then to receive it back from the Worker, you would do something like this:

```rust
let cb = Closure::wrap(Box::new(|event| {
    let array_buffer: ArrayBuffer = event.data().dyn_into().unwrap_throw();
    
    // Use ArrayBuffer...
}) as Box<FnMut(MessageEvent)>);

worker.set_onmessage(Some(cb.as_ref().unchecked_ref()));
```

**Comment by MarcAntoine-Arnaud** [comment]
I have tested it and it works like that:
```javascript
// Worker in JS
postMessage(output.buffer, [output.buffer])
```

then I can get back the `ArrayBuffer` in Rust as @Pauan mentioned.

My initial wish is to send also informations about decoded frame, so I wanna to send:
```javascript
// Worker in JS
postMessage({
  'frame_index': 666,
  'width': 1920,
  'height': 1080,
  'data': output.buffer
}, [output.buffer])
```
When I receive this message in javascript it works, I can access to all informations.

For Rust I have only access to a JsValue like:
`JsValue(Object({"frame_index":666,"width":1920,"height":1088,"data":{}}))`
The data seems an empty array...
Do you know how to get back information for that ?
Or if it's not supported right now with wasm-bindgen ?

Marc-Antoine

**Comment by UsernameN0tAvailable** [comment]
@Pauan what if I want to post a JsValue object as a message and then specifiy which parts of the object are transferable ?

**Comment by Pauan** [comment]
@UsernameN0tAvailable It works exactly the same as in JS: you specify the Transferable objects in the Array.

**Comment by UsernameN0tAvailable** [comment]
@Pauan since the first argument is type JsValue, how would you go about getting a field value / reference out of it to insert into the transferable array?

**Comment by Pauan** [comment]
@UsernameN0tAvailable You would use [`Reflect::get`](https://rustwasm.github.io/docs/wasm-bindgen/reference/accessing-properties-of-untyped-js-values.html) to lookup a property in the object, it works the same as `object[key]`. There's a lot of other useful methods in `Reflect` as well.

Or, you can [create some bindings](https://rustwasm.github.io/docs/wasm-bindgen/reference/working-with-duck-typed-interfaces.html) which specify what keys the object has... and then use [`unchecked_into`](https://docs.rs/wasm-bindgen/0.2.74/wasm_bindgen/trait.JsCast.html) to convert the JsValue into your custom type:

```rust
#[wasm_bindgen]
extern "C" {
    type Foo;

    #[wasm_bindgen(structural, method, getter)]
    fn some_property(this: &Foo) -> ArrayBuffer;
}

...

let array_buffer = object.unchecked_into::<Foo>().some_property();
```

This is faster than using `Reflect::get`, since it's equivalent to doing `object.some_property`.

**Comment by UsernameN0tAvailable** [comment]
@Pauan I apologize for my line of questioning, but is it even possible to serialize "into_serde" a rust vec to a TypedArray or Reflect:set it without it being transmutated into a map?

**Comment by Pauan** [comment]
@UsernameN0tAvailable I don't understand your question, none of this has anything to do with serde, it's all just a regular JsValue.

If you want to convert a `Vec` into a JS `Array`, just use `collect`:

```rust
vec![...].into_iter().collect::<Array>()
```

You might need to convert the values into `JsValue`:

```rust
vec![...].into_iter().map(JsValue::from).collect::<Array>()
```

If you want to convert it into a TypedArray, you can use the [`From` impl](https://docs.rs/js-sys/0.3.51/js_sys/struct.Uint8Array.html#impl-From%3C%26%27a%20%5Bu8%5D%3E):

```rust
Uint8Array::from(&foo)
```

**Comment by UsernameN0tAvailable** [comment]
@Pauan when accessing MessageEvent.data() the TypedArray data gets mapped, so I suspect the transfer is not working.
![image](https://user-images.githubusercontent.com/22366676/125195916-1eff9d80-e258-11eb-93cf-7f2013acf0e0.png)

**Comment by Pauan** [comment]
@UsernameN0tAvailable Note that *`ArrayBuffer`* is transferrable, but TypedArrays (like `Uint8Array`) are *not* transferrable, so if you have a TypedArray then you must use the [`buffer` method](https://docs.rs/js-sys/0.3.51/js_sys/struct.Uint8Array.html#method.buffer) in order to get an `ArrayBuffer`.
