### ISSUE TITLE
Typescript definitions don't include declaration for default function import.

### ISSUE THREAD

**Issue by chanks** [rustwasm/wasm-bindgen#1517]
### Describe the Bug

wasm-pack build for a simple app generates a ts file that looks like:

```ts
/* tslint:disable */
/**
* @returns {void} 
*/
export function init_panic_hook(): void;

/**
* If `module_or_path` is {RequestInfo}, makes a request and
* for everything else, calls `WebAssembly.instantiate` directly.
*
* @param {RequestInfo | BufferSource | WebAssembly.Module} module_or_path
*
* @returns {Promise<any>}
*/
export function init (module_or_path: RequestInfo | BufferSource | WebAssembly.Module): Promise<any>;
```

Unfortunately, the init function isn't labeled as the module's default export, so trying to use it that way from a .ts file:

```ts
import init, { init_panic_hook } from './my_mod';

init_panic_hook(); // TS compiler is happy with this.
init("/path"); // TS compiler hates this!
```

...will fail with a semi-cryptic `TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof import(...)' has no compatible call signatures`.

The workaround I've found for this (thanks to the Typescript gitter channel) is to append `export default init;` to the end of the generated type file. I'm not a typescript expert, though, so I'm not sure if this is the ideal solution, or if it's preferable to document that the init function should be imported in some other way? I spent a while banging my head against the wall about it though :)

Thank you!

**Comment by darthtrevino** [comment]
Related to https://github.com/rustwasm/wasm-pack/issues/644
