### ISSUE TITLE
Implement FromWasmAbi for Result<i32|u32, JsValue>

### ISSUE THREAD

**Issue by ibaryshnikov** [rustwasm/wasm-bindgen#1528]
It looks like there's no `FromWasmAbi` implementation for `Result<u32, JsValue>` and `Result<i32, JsValue>`
The feature is required by #1379, since there are return types like `Result<i32, JsValue>` in `Atomics`
https://github.com/rustwasm/wasm-bindgen/blob/master/crates/js-sys/src/lib.rs#L528

**Comment by alexcrichton** [comment]
It's intended that `Result` can be returned from functions but for `FromWasmAbi` that typically means it's an argument I think? Are you trying to take a `Result` as an argument? Or is there a different situation where the requirement for `Result: FromWasmAbi` is coming up?

**Comment by ibaryshnikov** [comment]
Here is an example
```rust
pub mod Atomics {
    use super::*;

    #[wasm_bindgen]
    extern "C" {
        #[wasm_bindgen(js_namespace = Atomics, catch)]
        pub fn add(typed_array: &JsValue, index: u32, value: i32) -> Result<JsValue, JsValue>;
```
When I run `wasm-pack test --headless --safari` in `crates/futures` folder, it fails with an error
```
error[E0277]: the trait bound `std::result::Result<wasm_bindgen::JsValue, wasm_bindgen::JsValue>: wasm_bindgen::convert::traits::FromWasmAbi` is not satisfied
   --> crates/js-sys/src/lib.rs:522:5
    |
522 |     #[wasm_bindgen]
    |     ^^^^^^^^^^^^^^^ the trait `wasm_bindgen::convert::traits::FromWasmAbi` is not implemented for `std::result::Result<wasm_bindgen::JsValue, wasm_bindgen::JsValue>`
```
The error points here https://github.com/rustwasm/wasm-bindgen/blob/master/crates/js-sys/src/lib.rs#L519
Originally the return type was `Result<i32, JsValue>`, but changing `i32` to `JsValue` didn't help. I wonder, what could cause the error

**Comment by alexcrichton** [comment]
Sorry I think I still may not be quite following, could you perhaps gist a standalone example that exhibits the error?

**Comment by ibaryshnikov** [comment]
Found it! I was confused by error message.

```rust
use wasm_bindgen::prelude::*;

pub mod Namespace {
    use super::*;

    #[wasm_bindgen]
    extern "C" {
        #[wasm_bindgen(js_namespace = Namespace)]
        pub fn example() -> Result<JsValue, JsValue>;
    }
}
```
If we try to run `wasm-pack build`, the error will be
```
error[E0277]: the trait bound `std::result::Result<wasm_bindgen::JsValue, wasm_bindgen::JsValue>: wasm_bindgen::convert::traits::FromWasmAbi` is not satisfied
 --> src/lib.rs:6:5
  |
6 |     #[wasm_bindgen]
  |     ^^^^^^^^^^^^^^^ the trait `wasm_bindgen::convert::traits::FromWasmAbi` is not implemented for `std::result::Result<wasm_bindgen::JsValue, wasm_bindgen::JsValue>
```
The mistake in code is missing `catch` here:
```rust
#[wasm_bindgen(js_namespace = Namespace)]
```
and the following code compiles:
```rust
#[wasm_bindgen(js_namespace = Namespace, catch)]
```

**Comment by alexcrichton** [comment]
Hm I'm unfortunately still having difficulty reproducing this and I don't know why, @ibaryshnikov can you perhaps send a PR adding a test to `crates/macro/ui-tests/*.rs` which produces the desired error?

**Comment by ibaryshnikov** [comment]
@alexcrichton I tried to add the code to `crates/macro/ui-tests/` but it doesn't trigger an error
I created a repo with minimal example, you can checkout it and run `wasm-pack build` to see the error
https://github.com/ibaryshnikov/fromwasmabi
