### ISSUE TITLE
Wasm-pack build error: Could not compile 'net2'

### ISSUE THREAD

**Issue by vegapit** [rustwasm/wasm-bindgen#1529]
Hi all,

I am having problems using **wasm-pack** for compiling a struct method coming from an external library. The **net2** crate seems to create the build error and it originates from a linker issue with **openssl-sys**

error: failed to run custom build command for `openssl-sys v0.9.46`
process didn't exit successfully: `D:\dev\alphanexus-web\target\release\build\openssl-sys-5a1c936190752de2\build-script-main` (exit code: 101)
--- stdout
cargo:rustc-cfg=const_fn
cargo:rerun-if-env-changed=WASM32_UNKNOWN_UNKNOWN_OPENSSL_LIB_DIR
WASM32_UNKNOWN_UNKNOWN_OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=WASM32_UNKNOWN_UNKNOWN_OPENSSL_INCLUDE_DIR
WASM32_UNKNOWN_UNKNOWN_OPENSSL_INCLUDE_DIR unset
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
OPENSSL_INCLUDE_DIR unset
cargo:rerun-if-env-changed=WASM32_UNKNOWN_UNKNOWN_OPENSSL_DIR
WASM32_UNKNOWN_UNKNOWN_OPENSSL_DIR unset
cargo:rerun-if-env-changed=OPENSSL_DIR
OPENSSL_DIR unset
run pkg_config fail: "Cross compilation detected. Use PKG_CONFIG_ALLOW_CROSS=1 to override"
note: vcpkg did not find openssl as libcrypto and libssl: the vcpkg-rs Vcpkg build helper can only find libraries built for the MSVC ABI.
note: vcpkg did not find openssl as ssleay32 and libeay32: the vcpkg-rs Vcpkg build helper can only find libraries built for the MSVC ABI.

--- stderr
thread 'main' panicked at '

Could not find directory of OpenSSL installation, and this `-sys` crate cannot
proceed without this knowledge. If OpenSSL is installed and this crate had
trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
compilation process.

Make sure you also have the development packages of openssl installed.
For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

If you're in a situation where you think the directory *should* be found
automatically, please open a bug at https://github.com/sfackler/rust-openssl
and include information about your system as well as this message.

$HOST = x86_64-pc-windows-msvc
$TARGET = wasm32-unknown-unknown
openssl-sys = 0.9.46

What would be the fix in Windows or OSX?

**Comment by alexcrichton** [comment]
Thanks for the report! This is actually an error reported by the openssl-sys build script and that's because the `openssl` crate doesn't have support for WebAssembly yet (I'm not sure that OpenSSL itself even does...).

**Comment by vegapit** [comment]
> Thanks for the report! This is actually an error reported by the openssl-sys build script and that's because the `openssl` crate doesn't have support for WebAssembly yet (I'm not sure that OpenSSL itself even does...).

Thank you for the quick response! Is there a way to know which libraries are supported (or not) before importing them into the crate?

**Comment by alexcrichton** [comment]
Currently no we unfortunately don't have a list because the list is always changing! It's recommended to try it out and see what happens mostly.

**Comment by vegapit** [comment]
> Currently no we unfortunately don't have a list because the list is always changing! It's recommended to try it out and see what happens mostly.

Understood and thank you again for the fast response !! 👍

**Comment by Morgandri1** [comment]
So q4 2024... any progress on this? any reason why OpenSSL still doesnt build with wasm-bindgen?

**Comment by daxpedda** [comment]
This isn't an issue with `wasm-bindgen`, but with the `openssl` crate which doesn't support the `wasm32-unknown-unknown` target. Or more likely an OpenSSL issue.

Its best if you ask there.
