### ISSUE TITLE
Add '.wasm' to import * as wasm from './<rust-lib-name>_bg.wasm

### ISSUE THREAD

**Issue by limira** [rustwasm/wasm-bindgen#154]
I tried wasm-bindgen with [Parcel](https://parceljs.org/).

My though is in file `<rust-lib-name>.js` should uses: `import * as wasm from './<rust-lib-name>_bg.wasm';`

Parcel is happy with the extension `.wasm` and compile the project. But the browser complains:

    Error: Cannot find module '8'
    TypeError: second argument must be an object

I am not sure these errors are with wasm-bindgen for with parcel!

**Comment by alexcrichton** [comment]
Thanks for the report! Last I checked with Parcel there's good support for importing functionality from a wasm module but it's [left unimplemented](https://github.com/parcel-bundler/parcel/issues/647) if a wasm module imports functionality from the environment. I think until that's fixed Parcel will be incompatible with wasm-bindgen :(

**Comment by alexcrichton** [comment]
I'm gonna close this for now due to my previous comment, but please let me know if the closing is in error!
