### ISSUE TITLE
Docs: requesting OffscreenCanvas example

### ISSUE THREAD

**Issue by andykais** [rustwasm/wasm-bindgen#1551]
### Summary
Hi all, browser support for the offscreen canvas is limited, but Id love to see an example that takes advantage of web workers and the offscreen canvas to show off some real parallel rendering.

### Additional Details
my basic psuedo-code for an example looks like so:
```js
// main.js
const offscreen = document.querySelector('canvas').transferControlToOffscreen();
const worker = new Worker('worker.js');
worker.postMessage({ canvas: offscreen }, [offscreen]);
```
```js
// worker.js
import { draw_with_offscreen_canvas } from 'lib.rs'
worker.addEventListener('message', e => {
  const { canvas } = e.data
  draw_with_offscreen_canvas(canvas)
})
```
```rust
extern crate wasm_bindgen;
extern crate web_sys;
use web_sys::{WebGlRenderingContext, OffscreenCanvas};


[#wasm_bindgen]
pub fn draw_with_offscreen_canvas(canvas: OffscreenCanvas) {
      let context = canvas
        .get_context("webgl")
        .unwrap()
        .unwrap()
        .dyn_into::<WebGlRenderingContext>()
        .unwrap();
  // draw something
}
```
I am running into `RuntimeError: unreachable executed` so I am guessing I am not transferring the offscreen-canvas in rust properly. I am new to rust, but web-sys has a `OffscreenCanvas`, so I believe this should be possible!

**Comment by fitzgen** [comment]
The `unreachable` is probably a panic (perhaps in those unwraps). Try using [`console_error_panic_hook`](https://github.com/rustwasm/console_error_panic_hook) to get the error message.

**Comment by andykais** [comment]
Thanks, that makes sense. I have since refactored the code to use the main thread which was fine for what I was doing. Going through main -> worker -> web assembly felt a little convoluted for drawing a few pixels to the screen. Thats 3 steps of data serialization Id like to avoid. I think this issue can be closed as it was an issue with how I was debugging my code, and not how to use the library

**Comment by arthmis** [comment]
Hey I know this is old and don't know what you tried but a minimal example I found so far to transfer an offscreen canvas looked like this

```rust
// js_sys::Array
let mut array: Array = Array::new();
// had a canvas and transfered it to be an offscreen canvas, you can probably start 
// with an offscreen if you have that already
let canvas_worker = canvas.transfer_control_to_offscreen().unwrap();
// used an array because the javascript examples use an array
array.push(&canvas_worker);
worker.post_message_with_transfer(&canvas_worker, &array).unwrap();
```

then in the worker, I also used webassembly and looked like this
```rust
let scope = DedicatedWorkerGlobalScope::from(JsValue::from(js_sys::global()));

scope
    .post_message(&JsValue::from_str("worker is initialized"))
    .unwrap();

let onmessage = Closure::wrap(Box::new(move |msg: MessageEvent| {
    let canvas = msg.data().dyn_into::<OffscreenCanvas>().unwrap();
}) as Box<dyn Fn(MessageEvent)>);
scope.set_onmessage(Some(onmessage.as_ref().unchecked_ref()));
onmessage.forget();
```
I got some of this from an example that uses Trunk to compile rust code to wasm
