### ISSUE TITLE
Is MouseEvent's button() broken?

### ISSUE THREAD

**Issue by nrayamajhee** [rustwasm/wasm-bindgen#1552]
I have been trying to handle right click on a canvas but right click doesn't seem to be triggered for some reason! The code below works for left click only.
```rust

let cl = Closure::wrap(Box::new(move |e: Event|{
  let btn = e.dyn_into::<MouseEvent>().unwrap().button();
  log!("{}", btn);
  if btn == 0 {
     log!("Left Click");
  } else if btn == 2 {
    log!("Right Click");
  }
}) as Box<dyn FnMut(_)>);
element.add_event_listener_with_callback(
    "click",
    cl.as_ref().unchecked_ref(),
)
.unwrap();
cl.forget();
```

Similarly I can't disable context menu using rust
```rust
let cl = Closure::wrap(Box::new(move |e: Event|{
    e.prevent_default();

}) as Box<dyn FnMut(_)>);
element.add_event_listener_with_callback(
    "contextmenu",
    cl.as_ref().unchecked_ref(),
)
.unwrap();
cl.forget();
```
I am resorting to embedding javascript in the html attribute

```rust
canvas.set_attribute("oncontextmenu", "event.preventDefault();").unwrap();
```

**Comment by Pauan** [comment]
This isn't a bug with wasm-bindgen, it's just how browsers work (the same thing happens in JavaScript):

```js
// Doesn't fire for right click
addEventListener("click", function (e) {
    console.log(e.button);
});
```

The only way to detect right click is with the `mousedown`, `mouseup`, or `contextmenu` events.

As for `prevent_default`, have you tried setting the `contextmenu` event on the `window`?

```rust
window().unwrap().add_event_listener_with_callback(
    "contextmenu",
    cl.as_ref().unchecked_ref(),
)
.unwrap();
```

If that doesn't work, then it's definitely a bug in wasm-bindgen.

**Comment by nrayamajhee** [comment]
Sorry I meant `mousedown`. My code has `mousedown`.

I was using a function to add event listener easily without having to type : `Closure::wrap(Box::new(move`  everytime I add a event listener. My function was internally bound to "click" event when I meant to pass in the event type as a parameter.

Such a stupid mistake! Thanks for your clarification though!

```rust
pub fn add_event<H>(el: &HtmlElement, event_type: &str, event_listener: H)
where H: 'static + FnMut(Event) {
    let cl = Closure::wrap(Box::new(event_listener) as Box<dyn FnMut(_)>);
    el.add_event_listener_with_callback("click", cl.as_ref().unchecked_ref())
        .unwrap();
    cl.forget();
}
```

and I was calling it with "mousedown" which obviously wouldn't work: `add_event(&canvas, "mousedown", move |_|{...});`

**Comment by Pauan** [comment]
Glad you got it fixed. You should also take a look at [gloo](https://github.com/rustwasm/gloo), which has an `EventListener` helper type:

```rust
EventListener::new(&canvas, "mousedown", move |_| { ... })
```

It also handles things like deregistering the event listener when it's no longer needed.

It isn't released yet, but it will be released soon.
