### ISSUE TITLE
Upgrade wasm-bindgen-test to std::future

### ISSUE THREAD

**Issue by najamelan** [rustwasm/wasm-bindgen#1558]
### Motivation

Work has been done to start enabling async/await, but the `wasm-bindgen-test` macro still requires users to return a futures 0.1 future from their test functions. I think it's time we allowed returning a std future.

### Proposed Solution

Potentially behind the same `futures_0_3` feature as with wasm-bindgen-futures. The relevant code [seems to be here](https://github.com/rustwasm/wasm-bindgen/blob/master/crates/test/src/rt/mod.rs#L369).

### Alternatives

Wait until it stabelizes completely

**Comment by fitzgen** [comment]
I think we want to wait until it stabilizes completely. We've historically put a lot of effort into getting our toolchain on stable rustc, and I wouldn't want to regress that without extremely strong motivations.

**Comment by alexcrichton** [comment]
Oh oops sorry I meant to reply to this! I think that we'll want to hold off on changing `#[wasm_bindgen_test(async)]` until futures are stable, but like with opt-in support for libstd's `Future` trait I think we could take a strategy like `#[wasm_bindgen_test(async_std)]` or something like that which means "use `std::future::Future`" and couple that with a feature of the `wasm-bindgen-test` crate and we should be able to implement this today without too much impact.

**Comment by Pauan** [comment]
`Future` will be available on Stable on July 4th, so I'm not a fan of short-term solutions.

**Comment by ctaggart** [comment]
To clarify, the work to move to std::Future https://github.com/rustwasm/wasm-bindgen/issues/1695 to enable the new async/await syntax, correct? What would [this example](https://github.com/rustwasm/wasm-bindgen/issues/1126#issuecomment-449765756
) that @Pauan gave, look like with the new async/await syntax and not the `await!` macro:

``` rust
fn on_click() {
    state.merge(Action::LoadData);
    spawn_local(indexeddb::open("my_db", 1)
        .then(|db| db.start_transaction())
        .then(|(db, trans)| db.object_store("people"))
        .then(|store| store.get(0))
        .then(|record| {
            state.merge(Action::LoadSucceeded {
                name: record.name,
                age: record.age
            });
        }));
}
```

``` rust
fn on_click() {
    state.merge(Action::LoadData);
    spawn_local(async {
        let db = await!(indexeddb::open("my_db", 1))?;
        let trans = await!(db.start_transaction())?;
        let store = await!(db.object_store("people"))?;
        let record = await!(store.get(0))?;
        state.merge(Action::LoadSucceeded {
            name: record.name,
            age: record.age
        });
    });
}
```
