### ISSUE TITLE
Compilation error details disappear in some cases

### ISSUE THREAD

**Issue by ibaryshnikov** [rustwasm/wasm-bindgen#1562]
### Describe the Bug

Error details are missing with a specific combination of macro and method invocation

### Steps to Reproduce

```rust
use js_sys::Error;
use wasm_bindgen::prelude::*;
use web_sys::WebGlRenderingContext;

#[wasm_bindgen]
pub struct Scene {
    ctx: WebGlRenderingContext,
}

#[wasm_bindgen]
impl Scene {
    #[wasm_bindgen]
    pub fn draw(&self) -> Result<(), JsValue> {
        // The problem appears when there are `include_str!` macro and
        // `.ok_or_else...` part

        // commenting `frag_src` statement alone will return part of the error information
        let frag_src = include_str!("frag.glsl");

        // commenting `positions_buffer` statement alone will return all the required information
        let positions_buffer = self.ctx
            .create_buffer()
            .ok_or_else(|| Error::new("failed to create buffer"))?;

        let n = 1u32;
        test_types(n);

        Ok(())
    }
}

fn test_types(_a: i32) {}
```

Here is a repo with the complete example
https://github.com/ibaryshnikov/missing-error-details

### Expected Behavior

The error should be
```
error[E0308]: mismatched types
  --> src/lib.rs:26:20
   |
26 |         test_types(n);
   |                    ^ expected i32, found u32

error: aborting due to previous error
```
### Actual Behavior

Error details are missing
```
error[E0308]: mismatched types

error: aborting due to previous error
```

**Comment by fitzgen** [comment]
Probably failing to associate some token bits with the proper span. This is definitely more of @alexcrichton's domain than mine :grimacing:

**Comment by alexcrichton** [comment]
I was debugging this a bit but unfortunately I don't think this is an issue that wasm-bindgen can fix. Compiling with `RUSTC_LOG=syntax` you'll see:

```
 INFO 2019-06-03T18:58:10Z: syntax::parse::token: cached tokens found, but they're not "probably equal", going with stringified version
```

which means this boils down to https://github.com/rust-lang/rust/issues/43081. 

I still need to dig more into what exactly is happening here, but the fix is likely in rustc and not here.

**Comment by alexcrichton** [comment]
Ok I've dug more into this and it looks like the syntax changing is the `||` in the closure, it's oscillating between `| |` and `||` in the compiler and the various round-trips that we have, which means we can't actually do anything about this here. I'm going to close in favor of the Rust issue.
