### ISSUE TITLE
RtcPeerConnection::set_local_description generated documentation for required features is wrong

### ISSUE THREAD

**Issue by kyren** [rustwasm/wasm-bindgen#1569]
### Describe the Bug

[RtcPeerConnection::set_local_description](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.RtcPeerConnection.html#method.set_local_description) docs say that the features required to use it are RtcPeerConnection and RtcSessionDescriptionInit, but it will not work without also enabling "RtcSdpType".

Also, the "RtcSessionDescriptionInit" type is not generated at all without enabling "RtcSdpType".  I don't know why this is, but it might have something to do with RtcSessionDescriptionInit::new taking an RtcSdpType?

I had to do a lot of trial and error to figure out which missing feature was required (copying the entire set of Rtc* features and bisecting.

### Steps to Reproduce

1) Create a new project that uses web-sys 0.3.22 and imports web_sys::RtcSessionDescriptionInit.
2) enable web-sys feature RtcSessionDescriptionInit
3) get a compilation error because RtcSessionDescriptionInit it not found in web_sys

### Expected Behavior

I would expect RtcSessionDescriptionInit to only require the feature which is the name of its type, and I would also expect the docs for RtcPeerConnection::set_local_description to mention all required features.

### Actual Behavior

They do not, and you have to bisect the entire list of available features to find which one is missing, or know what might have gone wrong.  Is there a better way to discover what features are actually required for a type / method other than the generated documentation in case it goes wrong?

**Comment by kyren** [comment]
Now that I know a bit more about the API, this issue makes a bit more sense.  You can't create an `RtcIceCandidateInit` without an `RtcSdpType` to begin with (but you could get one from javascript I suppose).  `RtcPeerConnection:: set_local_description` is also supposed to accept an `RtcIceCandidate`as well I think, but that's a separate issue.

In any case, this is not a big deal now that I know about it and it has an easy workaround that you'd *probably* do anyway, but it's still sort of a usability issue.

**Comment by fitzgen** [comment]
Thanks for filing a bug!

> [RtcPeerConnection::set_local_description](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.RtcPeerConnection.html#method.set_local_description) docs say that the features required to use it are RtcPeerConnection and RtcSessionDescriptionInit, but it will not work without also enabling "RtcSdpType".

We should definitely fix this docs bug. It sounds like our webidl frontend is missing features that are required because of constructors.
