### ISSUE TITLE
web-sys shouldn't use env_logger

### ISSUE THREAD

**Issue by Pauan** [rustwasm/wasm-bindgen#1580]
### Motivation

When using `web-sys`, it pulls in the `env_logger` dependency, which in turn pulls in all of these dependencies:

```
aho-corasick
atty
humantime
quick-error
regex
regex-syntax
termcolor
termion
thread_local
ucd-util
utf8-ranges
winapi
winapi-util
wincolor
```

This means that even a simple "hello world" app takes a *lot* longer to compile.

As far as I can tell, `env_logger` isn't actually needed, it's solely for debugging. So I propose that it be hidden behind a Cargo `--feature`, so that way it doesn't affect people who don't need the logging.

**Comment by alexcrichton** [comment]
An excellent idea!
