### ISSUE TITLE
How to build with a fixed version of wasm-bindgen (to avoid issue

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [rustwasm/wasm-bindgen#1587]
### Summary
I ran into a wasm-bindgen build issue that seems to be this:
https://github.com/rustwasm/wasm_game_of_life/issues/22

whose root cause is: https://github.com/rustwasm/wasm-bindgen/issues/1246

I tried using 0.2.45 which is the latest release at time of writing, but it still seems to have the issue. 

I have tried fixing my version of was-bindgen to a version known to not have this version as described in a comment on the issue. 
`wasm-bindgen = "=0.2.34"`

When  I do so, the build issue is fixed as expected but I get the error about different versions of "this binary" and wasm-bindgen:

```error: failed to extract wasm-bindgen custom sections
    caused by: 

it looks like the Rust project used to create this wasm file was linked against
a different version of wasm-bindgen than this binary:

  rust wasm file: 0.2.34
     this binary: 0.2.45

Currently the bindgen format is unstable enough that these two version must
exactly match, so it's required that these two version are kept in sync by
either updating the wasm-bindgen dependency or this binary. You should be able
to update the wasm-bindgen dependency with:

    cargo update -p wasm-bindgen

or you can update the binary with

    cargo install -f wasm-bindgen-cli

if this warning fails to go away though and you're not sure what to do feel free
to open an issue at https://github.com/rustwasm/wasm-bindgen/issues!

make: *** [build] Error 1```

I am not sure how to fix that to force a specific version of "the binary".

I uninstalled `wasm-bindgen-cli` and tried to install the specific 0.2.34 version of wasm-bindgen-cli with:
`cargo install -v 0.2.34 wasm-bindgen-cli`

It starts with the line:
`error: could not find `0.2.34` in registry `https://github.com/rust-lang/crates.io-index``
(despite there being an entry in crates.io for it).

and so it continues to install 0.2.45, and then I get the same error when building.

BTW: I saw https://github.com/webpack/webpack/pull/8786 was merged Feb 25th, so I also tried updating webpack.

What would be a correct configuration (Cargo.toml and anything else needed) to have a working build?

Any clues on what is a working setup would be appreciated.

**Comment by chinedufn** [comment]
Using `wasm-pack build` should have you good to go here as it will download the correct binary.

Alternatively - `cargo install wasm-bindgen@0.2.34 --force` should also have you covered, but I'd highly recommend using `wasm-pack build` instead to avoid issues like this!

Cheers!

**Comment by alexcrichton** [comment]
Indeed @chinedufn hit the nail on the head, using `wasm-pack` and then ensuring the right version is in `Cargo.lock` should do the trick!

**Comment by andrewdavidmackenzie** [comment]
OK. So, this replaces `wasm-bindgen-cli` ?

I need to figure out how to convert the project I had working with
```
build:
	@cargo build --target wasm32-unknown-unknown
	@wasm-bindgen target/wasm32-unknown-unknown/debug/web.wasm --out-dir run

run: build
	cd run && npm install
	cd run && npm run serve```

to use wasm-pack then....

**Comment by andrewdavidmackenzie** [comment]
OK. I'm following the tutorial here: https://rustwasm.github.io/docs/wasm-pack/tutorials/hybrid-applications-with-webpack/using-your-library.html

and have bootstrapped an empty project and will copy my (little) code in there and use wasm-pack from now on.

This is a fast moving area and so now I'm more up-to-date.
(after a bit of yak shaving...)

Thanks for the great help as usual.

**Comment by alanpoon** [comment]
There is something wrong with wasm-bindgen crates.io. All the previous versions of wasm-bindgen in the crates.io shows that they were updated one month ago. Even if i set the older version in the Cargo.toml, it will always download the latest version from crates.io

**Comment by Pauan** [comment]
@alanpoon I do not see that problem:

https://crates.io/crates/wasm-bindgen/versions
https://crates.io/crates/wasm-bindgen-cli/versions

Are you using a fixed version like `"=0.2.26"`? The `=` is very important, otherwise it won't work.

**Comment by alanpoon** [comment]
I am using wasm-bindgen = "0.2.47", but cargo.lock shows:
 [[package]]
name = "wasm-bindgen"
version = "0.2.48"

**Comment by alanpoon** [comment]
ok I see "=0.2.47" is working

**Comment by Pauan** [comment]
@alanpoon Cargo uses semver by default, so when you use `"0.2.47"` that means "greater than or equal to `0.2.47` and less than `0.3.00`". So it will pick the highest version which is less than `0.3.00`.

That's why you need the `=` so it tells Cargo to pick that *exact* version.
