### ISSUE TITLE
`init()` not working correctly

### ISSUE THREAD

**Issue by lazypassion** [rustwasm/wasm-bindgen#1597]
### Describe the Bug

Using `await init()` without passing the explicit wasm file name generated by wasm-pack/wasm-bindgen leads to this error:
Firefox: 
```
TypeError: first argument must be a WebAssembly.Module, ArrayBuffer or typed array object
```
Chrome: 
```
Uncaught (in promise) TypeError: WebAssembly.instantiate(): Argument 0 must be a buffer source or a WebAssembly.Module object
    at init (wasm_test.js:183)
    at run (main.html:26)
    at main.html:35
   init                       @  wasm_test.js:183
   run                        @  main.html:26
   (anonymous)                @  main.html:35
   async function (async)     
   run                        @  main.html:26
   (anonymous)                @  main.html:35
```

### Steps to Reproduce

1. Clone the repository https://github.com/lazypassion/wasm-init/tree/master
2. From within the repo do `wasm-pack build --target web`
3. Serve the folder using some http server (i'm using [http](https://github.com/thecoshman/http))
and click on main.html
4. See error on console

### Expected Behavior

I expected the wasm module to load and the output `1 + 2 = 3` on the console

### Actual Behavior

Throws the error above.

**Comment by alexcrichton** [comment]
I think that this was using a feature which hadn't been published yet, mind updating and trying again to see if it works?

**Comment by lazypassion** [comment]
Yes, it works after updating.

**Comment by alexcrichton** [comment]
Ok great, thanks for checking!
