### ISSUE TITLE
[BUG] failed to generate bindings for import

### ISSUE THREAD

**Issue by Pauan** [rustwasm/wasm-bindgen#1603]
### Steps to Reproduce

1. The code is [here](https://github.com/Pauan/js-framework-benchmark/tree/master/frameworks/keyed/wasm-bindgen)

2. Run `npm install`

3. Run `npm run build-prod-force`

I get this error:

```
error: failed to generate bindings for import `Closure(Closure { shim_idx: 20, dtor_idx: 21, function: Function { arguments: [Anyref], shim_idx: 20, ret: Unit }, mutable: true })`
    caused by: no function table found in module
Error: Running the wasm-bindgen CLI
```

This is using the latest wasm-bindgen (0.2.46) and latest wasm-pack (0.8.1)

**Comment by alexcrichton** [comment]
Oh wow that's a chain of events I wouldn't have expected, should be fixed in https://github.com/rustwasm/wasm-bindgen/pull/1606!
