### ISSUE TITLE
Function::new_with_args(&str, &str), I want to create a function in rust

### ISSUE THREAD

**Issue by greenpdx** [rustwasm/wasm-bindgen#1609]
### Summary
I am using web_sys::XmlHttpRequest and setting onloadend(to a function). I want to write a "Function" in rust and pass it in to _set_onloadend().
```
    let net = web_sys::XmlHttpRequest::new().unwrap();
    net.open_with_async("GET", "/", true);
    let f = Function::new_with_args("a",
    "{
        console.log('TST');
        console.log( a.target);
        console.log( a.target.response);
    }");
    net.set_onloadend(Some(&f));
    net.send();
```

A clear and concise summary of your question.
I want to have a rust function executed on loadend(), not a string/JS code.
How to create a "Function()" in rust to pass to set_onloadend().
  
### Additional Details

Provide any additional details here.

**Comment by Pauan** [comment]
See the [documentation for `Closure`](https://docs.rs/wasm-bindgen/0.2.47/wasm_bindgen/closure/struct.Closure.html).

As an example:

```rust
let net = web_sys::XmlHttpRequest::new().unwrap();

let cb = Closure::once_into_js(move |event: web_sys::ProgressEvent| {
    // Rust code here...
});

net.set_onloadend(Some(cb.unchecked_ref()));
net.open_with_async("GET", "/", true);
net.send();
```

**Comment by alexcrichton** [comment]
I think @Pauan's got this covered (thanks!) so I'm gonna close.

**Comment by greenpdx** [comment]
It sort of working
First, I needed to change
net.set_onloadend(Some(cb.as_ref().unchecked_ref()));
to get it compile.

I am now able to print out the ProgressEvent
info!("{:?}", event);

The next issue is how to dereference ProgressEvent "event"  to get to target and sub fields
 let evt = event.deref();
Now I have a &web_sys::Event,   But when I try evt.target() I get an error  
"no method named `target` found for type `&web_sys::Event` in the current scope"
But in the docs I see target(), I assume I am not dereferencing "event" correctly.

In the end need to get the  event.target.response
How do I get  the response from the request?

**Comment by Pauan** [comment]
Because the `target` method returns an `EventTarget`, you need to enable the `EventTarget` feature for web-sys:

```toml
[dependencies.web-sys]
version = "0.3.22"
features = [
    "EventTarget",
]
```
