### ISSUE TITLE
node-sys - Add bindings for Nodejs built-in modules

### ISSUE THREAD

**Issue by ssallay** [rustwasm/wasm-bindgen#1610]
### Motivation

`wasm-bindgen` already provides code generation for a `nodejs` target, but there are no bindings to the built-in Node.js globals and modules. With bindings to the built-in Node.js features, it will be easier to create richer WebAssembly modules with a wider set of functionality without needing to handwrite Node.js glue code.

### Proposed Solution

Add bindings for the globals that aren't related to module (`module`, `require`, `__dirname`, `__filename`, etc. seem redundant to implement)

Use the `module` attribute to add bindings for each of the built-in modules

**Comment by alexcrichton** [comment]
Thanks for the report! This is definitely something that's been on our radar. So far there have been a few small attempts to get this off the ground but unfortunately it's quite a large task!

At this time though we have come to the conclusion  that auto generation isn't likely to be feasible and we probably aren't going to be pursuing it ourselves at this time. If others like you are interested to tackle this though that would be great!

I think though it would be best for this to be developed in a separate repository of the rustwasm organization so I'm going to close this issue. If you or others are interested in getting started on this though please let me know and I can help get the repo set up!
