### ISSUE TITLE
Consistent way to test crates on CI (without hardcoding a wasm-bindgen version in CI configs)

### ISSUE THREAD

**Issue by najamelan** [rustwasm/wasm-bindgen#1611]
### Motivation

I'm trying to add CI testing to my crate following the explanation here:
https://rustwasm.github.io/wasm-bindgen/wasm-bindgen-test/continuous-integration.html

As you can see there is a lot of hardcoded version numbers for wasm-bindgen, nvm, geckodriver, chromedriver. This means that whenever wasm-bindgen is updated we would have to manually modify configuration files like `.travis.yml`. 

This also means that the book itself is outdated all the time.

### Proposed Solution

I'm wondering if we can make a simpler way to set this up which would just use the latest version of everything. I'm suspecting that `wasm-bindgen` can be installed with `cargo install`.

In either case, the book needs an update (wasm-bindgen-0.2.21), and maybe it's a good moment to consider streamlining this workflow?

**Comment by najamelan** [comment]
Ok, I see, the downside of `cargo install wasm-pack` is that a lot of ressources are wasted to compile it every time.

**Comment by alexcrichton** [comment]
Thanks for the report! Indeed `wasm-pack` is the way to fix this, and there are [prebuilt installers](https://rustwasm.github.io/wasm-pack/installer/) to avoid the compilation time of `cargo install wasm-pack`

**Comment by najamelan** [comment]
@alexcrichton would you like me to test it and propose a PR for this file: https://github.com/rustwasm/wasm-bindgen/blob/master/guide/src/wasm-bindgen-test/continuous-integration.md ?

**Comment by alexcrichton** [comment]
@najamelan oh oops didn't realize that was still there, yeah a PR for that would be great!
