### ISSUE TITLE
web-sys bindings for OffscreenCanvasRenderingContext2D

### ISSUE THREAD

**Issue by spencercw** [rustwasm/wasm-bindgen#1614]
### Motivation

web-sys has bindings for `OffscreenCanvas`, but is lacking bindings for `OffscreenCanvasRenderingContext2D` which makes it tricky to use with the 2D context.

As far as I know, Chrome is the only browser that currently supports the 2D context with `OffscreenCanvas`. [MDN](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas/getContext) says that this should return a `CanvasRenderingContext2D`, but this is at odds with the [WHATWG spec](https://html.spec.whatwg.org/multipage/canvas.html#the-offscreencanvas-interface) which says it should return an `OffscreenCanvasRenderingContext2D`. Chrome returns the latter.

### Proposed Solution

Add bindings for `OffscreenCanvasRenderingContext2D`.

### Alternatives

It is possible to work around this using reflection, but it is cumbersome.

**Comment by alexcrichton** [comment]
Currently our policy (IIRC) is to add stage 3 web apis to the webidl we generate. If this proposal is stage 3 or further then we probably just need to find a WebIDL file to include!

**Comment by MessiahAndrw** [comment]
Here's the WebIDL for OffscreenCanvasRenderingContext2D:
https://html.spec.whatwg.org/multipage/canvas.html#offscreencanvasrenderingcontext2d

**Comment by tvblomberg** [comment]
@spencercw would you be able to post your workaround for this?

**Comment by spencercw** [comment]
@tvblomberg We ended up not using wasm-bindgen because we needed to bring in some C libraries, which requires Emscripten, which wasm-bindgen is not compatible with. Currently we render into wasm memory and pass a pointer back to JavaScript, which then renders the image to a canvas.

**Comment by madsmtm** [comment]
I think this is fixed by https://github.com/rustwasm/wasm-bindgen/pull/3319
