### ISSUE TITLE
performance issue on for / loop

### ISSUE THREAD

**Issue by Yuyz0112** [rustwasm/wasm-bindgen#162]
#### issue report

When I use `wasm-bindgen` to build my first WebAssembly project, I faced a performance issue when use `for` to iterate a large number.

After debug, I can reproduce this issue with the following minimum code:
```rust
// lib.rs
#[wasm_bindgen]
pub fn test_loop() {
    for i in 0..1000000 {}
}
```

```js
// index.js
mod.then(m => {
  console.time('loop');
  m();
  console.timeEnd('loop');
});
```

This empty loop cost about 80ms ~ 100ms on my Macbook, and if I iterate over a larger number, the browser may crush.

I also record the call tree during the loop function:
![image](https://user-images.githubusercontent.com/13651389/39256997-f5f5a072-48e2-11e8-8513-dd85ca86118a.png)

**Another fact was if I changed `for` into `loop`, the time cost was lower but still has problem when the number is big.**

#### other information

wasm-bindgen version: 0.2

**Comment by Yuyz0112** [comment]
I'm not sure whether this is the current limitation of `wasm-bindgen`. And if yes, is there any method to optimize this?

**Comment by alexcrichton** [comment]
Thanks for the report! It looks like you're not compiling with optimizations enabled though. If you compile Rust code with `--release` do the performance numbers look better?

**Comment by Yuyz0112** [comment]
Wow, it works perfectly!
It's impressive to see the performance is as good as the result of benchmark test, looks like it was nearly no cost on interoperate between the two languages.

Thanks a lot @alexcrichton !
