### ISSUE TITLE
Build generating a broken .wasm file

### ISSUE THREAD

**Issue by gabrielcarneiro97** [rustwasm/wasm-bindgen#163]
I'm implementing a Conway's Game of Life in Rust to compile it to wasm, the rust module is already finished, but I'm having some troubles to transpile it to wasm. When I use the `cargo build` command, everything goes fine, like below:

```
PS C:\Users\Gabriel\Projetos\Conways-Game-of-Life\rust-module> cargo build --target wasm32-unknown-unknown
   Compiling unicode-xid v0.1.0
   Compiling wasm-bindgen-shared v0.2.5
   Compiling itoa v0.4.1
   Compiling dtoa v0.4.2
   Compiling serde v1.0.42
   Compiling rand v0.4.2
   Compiling bit-vec v0.5.0
   Compiling proc-macro2 v0.3.6
   Compiling quote v0.5.2
   Compiling syn v0.13.1
   Compiling serde_json v1.0.16
   Compiling serde_derive_internals v0.23.1
   Compiling serde_derive v1.0.42
   Compiling wasm-bindgen-backend v0.2.5
   Compiling wasm-bindgen-macro v0.2.5
   Compiling wasm-bindgen v0.2.5
   Compiling conways_game_of_life v0.1.0 (file:///C:/Users/Gabriel/Projetos/Conways-Game-of-Life/rust-module)
    Finished dev [unoptimized + debuginfo] target(s) in 40.4 secs
```

But when I try to see the wasm file with an extention that I have in my VSCode, it gaves me this error:

![image](https://user-images.githubusercontent.com/17196612/39264960-7b95758c-489c-11e8-894a-2030b77ca89f.png)

And after when I run de command `wasm-bindgen target/wasm32-unknown-unknown/debug/conways_game_of_life.wasm --out-dir .` the output .wasm file continues with this error and the .js is just empty, like the code below:

```
/* tslint:disable */
import * as wasm from './conways_game_of_life_bg'; // imports from wasm file
```

I'll not post my code here, because is an extense file, but you can find everything [in this repo](https://github.com/gabrielcarneiro97/Conways-Game-of-Life/tree/master/rust-module). Everything looks fine for me, am I forgetting something? Or is it a wasm-bindgen problem?

**Comment by gabrielcarneiro97** [comment]
@alexcrichton I was wondering how to gist a binary file, so I commited it to my git repo, the file is [here](https://github.com/gabrielcarneiro97/Conways-Game-of-Life/blob/master/rust-module/conways_game_of_life.wasm).

**Comment by alexcrichton** [comment]
Hm I'm not entirely sure what's going on here :(

This may be a bug in VSCode as the wasm file otherwise looks normal to me?

**Comment by gabrielcarneiro97** [comment]
My big doubt is why the .js file is empty, because it's a problem with my code, I'm forgetting something or it's a problem in wasm-bindgen, the VSCode just pointed something weired, but it's not important at all if it's a problem with the VS extension...

About the .wasm file, I'm not good as you with this wasm stuff 😅 , if you say that the file looks normal, I can't disagree...

**Comment by alexcrichton** [comment]
Hm so one thing to check locally perhaps would be that you've got the right CLI version and library version. Have you tried updating the `wasm-bindgen` Rust dependency as well as updating the CLI via `cargo install wasm-bindgen-cli -f`?

**Comment by gabrielcarneiro97** [comment]
So, I tried to build it on another machine, and at my Mac it worked, the problem on VSCode stills, but the .js file now looks promising, but not everything is heaven, when I tried to webpack it, just like the hello-world example, I got this error, what makes me think that maybe de .wasm file is really broken.

Error:
```
ERROR in ./conways_game_of_life.wasm
Module not found: Error: Can't resolve '__wbindgen_placeholder__' in '/Users/gabrielcastro/Projetos/wasm-test'
 @ ./conways_game_of_life.wasm
 @ ./conways_game_of_life_bg.wasm
 @ ./conways_game_of_life.js
 @ ./index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./index.js

ERROR in chunk 0
[id].index.js
Cannot read property 'id' of null
ℹ ｢wdm｣: Failed to compile.
```
index.js:
```
const js = import("./conways_game_of_life.js")

js.then(js => {
  console.log(js)
})
```
conways_game_of_life.js ([gist](https://gist.github.com/gabrielcarneiro97/a447e0e902e6550f4e14581a82b48a55))

**Comment by alexcrichton** [comment]
Hm it looks like something may be getting mixed up? The `__wbindgen_placeholder__` being referenced means that the raw output of rustc is being processed, but that's intended to be run through `wasm-bindgen` first (which removes all references to `__wbindgen_placeholder__`.

Perhaps the `--out-dir` of wasm-bindgen and `CARGO_TARGET_DIR` are getting mixed up?

**Comment by gabrielcarneiro97** [comment]
@alexcrichton hey buddy thanks for the help, looks like my Win is with some problems, maybe the wasm-bindgen-cli version, I'll check it tomorrow. About the webpack error it was what you sad, the directories was getting mixed up, so i fixed it and now my Conway's WASM is working (I'm so happy and excited with it). Thank you again, your work is amazing!

**Comment by alexcrichton** [comment]
Ok great glad to hear it's working better! If there's any more issues though feel free to reopen!
