### ISSUE TITLE
js_sys::global uses eval, and is not compatible with strict CSP

### ISSUE THREAD

**Issue by mitchchn** [rustwasm/wasm-bindgen#1641]
`js_sys::global` uses the `Function` constructor to get a handle to the global object:
https://docs.rs/js-sys/0.3.24/src/js_sys/lib.rs.html#4420.

This is a type of `eval` and is disallowed by strict content security policies that exclude `script-src 'self' 'unsafe-eval'`, even if they would otherwise permit WASM:

<img width="1033" alt="Screen Shot 2019-07-02 at 11 08 27 AM" src="https://user-images.githubusercontent.com/7342119/60734436-f385a200-9f1d-11e9-8046-c5d6e9ab44b0.png">

This behaviour causes unpredictable runtime exceptions, since several important APIs in the `web_sys` and `js_sys` ecosystem go through the global object.

## Alternatives to the Function constructor

* `globalThis` is the (very!) modern answer to get a handle to the global object in all JS environments. [MDN recommends globalThis](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) as the replacement for the `Function` constructor approach. Its browser requirements are demanding, however.
* The same article recommends a series of runtime check for the existence of well-known global objects, which is the approach used by [es6-shim](https://github.com/paulmillr/es6-shim).

**Comment by Pauan** [comment]
If we had full support for `inline_js` on all targets (or at least Node), this would be a great use of `inline_js`.

**Comment by terwer** [comment]
Well done, for some csp scenes, thi is very usefull.🌹
