### ISSUE TITLE
How is it possible to post JSON using RequestInit?

### ISSUE THREAD

**Issue by spencerkohan** [rustwasm/wasm-bindgen#1648]
I'm attempting to implement a POST request like so:

        let mut opts = RequestInit::new();
        opts.method("POST");
        opts.mode(RequestMode::Cors);

        let body = // some struct with the Serialize trait
        let json = JsValue::from_serde(&body).unwrap();
        console_log!("Posting JSON: {:?}", json);

        opts.body(
            Some(&json)
        );

When I perform this request, the server receives the body string "[object Object]" rather than the serialized JSON representation of the value.  What is the intended way to send an object as JSON?

**Comment by alexcrichton** [comment]
`JsValue::from_serde` creates a JS object (think a `{ ... }` literal) but it sounds like you want a JSON string itself here. For that you can use `serde_json` the Rust crate to turn a Rust type into a JSON string, and then you'll convert the Rust-based `String` into a `JsValue` to pass along. That should do the trick but feel free to post here if it still doesn't work!

**Comment by shijunti19** [comment]
@alexcrichton 
```js
JS:
obj
    .post({
      a: 'a',
      b: 1,
    })
RUST:
 pub fn post(&self,  body: JsValue) -> Promise {
       ..
  opts.body(Some(&body));
    }
```
Could JsValue be directly transformed into the JSON string JsValue?

It seems that the usage rate of this function is very high
