### ISSUE TITLE
unsafe impl causing error in project

### ISSUE THREAD

**Issue by jasonwilliams** [rustwasm/wasm-bindgen#1651]
### Describe the Bug

`unsafe impl` trait causes the error:
`implementation of an `unsafe` trait`

### Steps to Reproduce

1. Go to https://github.com/jasonwilliams/boa/pull/70
2. See the Travis CI output, plus the code change
3. Build and run branch
4. see error

If applicable, add a link to a test case (as a zip file or link to a repository we can clone).

### Expected Behavior

Project should build

### Actual Behavior

Errors in build with `implementation of an `unsafe` trait`

https://github.com/jasonwilliams/boa/pull/70

**Comment by fitzgen** [comment]
I don't think this is related to wasm-bindgen; if it actually is, then I think we need a smaller, more reduced test case to properly diagnose what is going on.

[This log](https://travis-ci.com/jasonwilliams/boa/jobs/214417648#L680-L708) seems to be when compiling the `boa` crate, not from `wasm-bindgen`.

**Comment by fitzgen** [comment]
Going to close this issue, but if you determine that there actually is a bug here and can provide more information / a small test case, please reopen it!
