### ISSUE TITLE
wasm-bindgen-macro-support-0.2.47 fails to compile on travis

### ISSUE THREAD

**Issue by najamelan** [rustwasm/wasm-bindgen#1656]
### Describe the Bug
```
error[E0433]: failed to resolve: unresolved import
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-macro-support-0.2.47/src/parser.rs:277:9
    |
277 |         attrgen!(parsers);
    |         ^^^^^^^^^^^^^^^^^^
    |         |
    |         unresolved import
    |         help: a similar path exists: `syn::token`
    |         in this macro invocation
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

### Steps to Reproduce
See: https://travis-ci.org/najamelan/async_runtime/builds/557296479

I can't reproduce this at home. The only difference I can see is that I'm on rustc 1.38.0-nightly (6e310f2ab 2019-07-07) where travis is on: rustc 1.38.0-nightly (cd2cd4c96 2019-07-10). My network isn't good enough here to update rust nightly.

### Expected Behavior

compile wasm-bindgen-macro-support successfully.

**Comment by najamelan** [comment]
I can now confirm I can reproduce this on nightly 2019-07-11, so somewhere between 2019-07-07 and 2019-07-11 something changed that breaks wasm-bindgen-macro-support.

**Comment by alexcrichton** [comment]
Thanks for the report! This is a bug with the recent nightly and should be fixed in https://github.com/rust-lang/rust/pull/62574
