### ISSUE TITLE
Add a no-javascript target

### ISSUE THREAD

**Issue by iirelu** [rustwasm/wasm-bindgen#1663]
There are a few potential uses for wasm that aren't related to the web at all, but could still benefit from the features of wasm-bindgen, such as universal binaries, WASI, and as an IR to replace scripting languages. This project is almost perfect for those tasks, but there's currently no option to prevent it from generating all .js and .ts files in its output directory. In practice this is only a mild annoyance, but it would be nice if non-js workflows were supported too.

### Proposed Solution

Add a "no-js" target to the existing roster of web, bundler, nodejs, no-modules.

### Alternatives

People could just use `cargo --target wasm32-unknown-unknown`, but this entirely loses the useful size optimisations that wasm-bindgen performs. rustc outputs 70kb of wasm for simple code, while wasm-bindgen turns that same 70kb into 150 bytes.

Another alternative is an entirely separate generic wasm optimising tool, but I can't think of one that would work as well as wasm-bindgen.

**Comment by iirelu** [comment]
Note: This might not be as needed as I thought, I've found that [`wabt`](https://github.com/WebAssembly/wabt)'s `wasm-strip` is the exact optimisation tool that I needed. Turns out rustc just likes loading wasm output with a ton of debug info, even in release mode.

**Comment by Pauan** [comment]
> such as universal binaries, WASI, and as an IR to replace scripting languages

Could you clarify what you mean by that?

* I don't know how wasm-bindgen is related to "universal binaries".

* Rust has native `wasm32-wasi` support, you don't need wasm-bindgen for that.

* What IR are you referring to?

>  but there's currently no option to prevent it from generating all .js and .ts files in its output directory.

Well, that's because wasm-bindgen currently requires JS in order to work.

> Another alternative is an entirely separate generic wasm optimising tool, but I can't think of one that would work as well as wasm-bindgen.

As you found, there are already a lot of generic wasm optimization tools.
