### ISSUE TITLE
"Cheap TypedArray view parameter" optimization is invalid across wasm memory growth

### ISSUE THREAD

**Issue by mstange** [rustwasm/wasm-bindgen#1668]
### Describe the Bug

When an imported JS function accepts a `&[u8]` parameter and triggers wasm memory growth during its execution, the `Uint8Array` which is passed to it becomes unusable because it gets detached from its ArrayBuffer. That's because wasm-bindgen translates such parameters into TypedArray wrappers around the raw wasm memory buffer. This is nice and fast when it works, but it doesn't survive wasm memory growth.

### Steps to Reproduce

```rust
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen]
    pub fn js_take_by_shared_reference(arr: &[u8]);
}

#[wasm_bindgen]
pub fn greet(name: &str) {
    js_take_by_shared_reference(&vec![1, 2, 3]);
}

#[wasm_bindgen]
pub fn trigger_memory_growth(&self) {
    std::mem::forget(vec![1u32; 100000]);
}
```

JavaScript:
```javascript
const { trigger_memory_growth, greet } = wasm_bindgen;

function js_take_by_shared_reference(arr) {
  console.log(arr.join(", "));
  trigger_memory_growth();
  console.log(arr.join(", "));
}

async function main() {
  await wasm_bindgen(
    await WebAssembly.compileStreaming(fetch('./bindgen_experiments_bg.wasm')));
  greet();
}
main();
```

### Expected Behavior

In this example, I expect the string "1, 2, 3" to be printed to the console twice.

### Actual Behavior

The string "1, 2, 3" only prints once. Then the following error is printed:
`TypeError: attempting to access detached ArrayBuffer`

<img width="681" alt="Screen Shot 2019-07-15 at 3 09 22 PM" src="https://user-images.githubusercontent.com/961291/61241963-94404280-a712-11e9-9d42-dce6f7f39304.png">

**Comment by alexcrichton** [comment]
Thanks for the report! This is an intentional feature of wasm-bindgen, however. The intention is that if you're using short-lived views this is a critical optimization and we must do it, but if your application needs a longer-lived view of memory then you can use `.subarray()` to copy it onto the JS heap. This may not be clearly called out in the documentation, though, and it would be good to do so!

**Comment by mstange** [comment]
Weird! But ok. I agree, this should be documented.
(`slice()` is the one that copies; `subarray()` only gives you a different view.)
