### ISSUE TITLE
impl PartialEq for web-sys

### ISSUE THREAD

**Issue by dakom** [rustwasm/wasm-bindgen#1672]
### Motivation

PartialEq is implemented for things in js_sys: https://github.com/rustwasm/wasm-bindgen/pull/1444

However, we still can't check for equality between `web_sys::Element`'s for example.

### Proposed Solution

Not sure if this is automatic via a single `derive` or in a macro or what, sorry! But on Discord @Pauan indicated that it's somehow doable.

### Additional Context

For a use case - we currently can't check if `Document.pointerLockElement` is equal to the element that initiated getting pointer lock. Workarounds are possible (like setting an id and comparing that), but it's not idiomatic and it would be much nicer to have direct equality checks.

**Comment by alexcrichton** [comment]
Thanks for the report! I agree this is probably something we should enable by default, and would agree in doing so!

FWIW this might be pretty easy, perhaps as easy as simply changing [this line](https://github.com/rustwasm/wasm-bindgen/blob/1807de74a72b9b5d0a5ede3023ef5aefe9db0031/crates/webidl/src/lib.rs#L544)!
