### ISSUE TITLE
Arguments not being checked for undefined before calculating length

### ISSUE THREAD

**Issue by johnsonw** [rustwasm/wasm-bindgen#1678]
### Describe the Bug
Consider the following snippet:
```
#[wasm_bindgen]
impl MyCallback {
    pub fn set_data(&self, data: JsValue) {
        let x:Result<Option<MyData>> = data.into_serde();
        log!("After serializing");
    }
}
```

I receive the the following error:
```
TypeError: Cannot read property 'length' of undefined
    at passStringToWasm (https://localhost:8443/wasm-components/package.js:144:24)
    at imports.wbg.__wbindgen_json_serialize (https://localhost:8443/wasm-components/package.js:509:22)
    ...
```

The error appears to be happening in the package.js:
```
if (typeof cachedTextEncoder.encodeInto === 'function') {
    passStringToWasm = function(arg) {


        let size = arg.length;
        let ptr = wasm.__wbindgen_malloc(size);
        let offset = 0;
        ...
```

in this case, `arg` is undefined.

### Steps to Reproduce
Invoke the function without any arguments.

### Expected Behavior
In the case above, we should check that `arg != null` before attempting to access a property on it. 

### Actual Behavior
Attempts to access length on undefined.

**Comment by alexcrichton** [comment]
Thanks for the report! This is sort of equivalent to a type error just happening at runtime, but if you generate bindings with `--debug` it should provide a better error message. Does that work for you?

**Comment by alexcrichton** [comment]
I'm going to close this because the error message should be improved with `--debug`, but please let us know if that doesn't work!
