### ISSUE TITLE
Add ability to pass additional options for chrome/gecko drivers

### ISSUE THREAD

**Issue by Kirguir** [rustwasm/wasm-bindgen#1681]
### Motivation

At the moment there is no possibility to pass command line flags (or "switches") for a chrome driver. This is needed to access the media device in tests. For example, such as '--use-fake-device-for-media-stream', '--use-fake-ui-for-media-stream'.

### Proposed Solution

Pass additional options through the environment variable 'GECKODRIVER_OPTIONS', as well as for the server part ('GECKODRIVER_ARGS').

**Comment by alexcrichton** [comment]
This should in theory be supported via `CHROMEDRIVER_ARGS` (like geckodriver), does that work for you?

**Comment by Kirguir** [comment]
`CHROMEDRIVER_ARGS` its arguments for spawn binary. `switches` => `Capabilities`, they [hardcoded](https://github.com/rustwasm/wasm-bindgen/blob/68a1519eaa23d1c761020d1014b1c1ccc52d3672/crates/cli/src/bin/wasm-bindgen-test-runner/headless.rs#L320) at moment. if add flags here, it works.

**Comment by alexcrichton** [comment]
Ah ok, makes sense! Sounds like a good feature to me to add and a PR should do the trick!
