### ISSUE TITLE
Support USB API

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [rustwasm/wasm-bindgen#1694]
Is it possible to support Web USB API ?
Examples of required features can be found here: https://developers.google.com/web/updates/2016/03/access-usb-devices-on-the-web

Only chrome as implemented that API, but it can be great to expose it.

**Comment by alexcrichton** [comment]
Thanks for the report! We currently support stage 3 and above proposals and we support them by copying in the official WebIDL file into our webidl folder, do you know what stage this proposal is at and where it's WebIDL can be found?

**Comment by MarcAntoine-Arnaud** [comment]
Thanks for the reply.
And I learn something, I know nothing about IDL, but right now more ;-)

I have found https://wicg.github.io/webusb/#idl-index (very recent update...)

**Comment by MarcAntoine-Arnaud** [comment]
Do you think it can be safe to add that one:
https://github.com/tidoust/reffy-reports/blob/master/whatwg/idl/webusb.idl ?

**Comment by alexcrichton** [comment]
I'm going to close this in favor of https://github.com/rustwasm/wasm-bindgen/issues/1950 which is a general strategy of how to support unstable WebIDL files.
