### ISSUE TITLE
How can JsValue implement From<&'a String>?

### ISSUE THREAD

**Issue by UnHumbleBen** [rustwasm/wasm-bindgen#1705]
### Summary

I am confuse about whether calling `from` implemented for `From<&'a String>` ultimately moves the `String` or not. Does it create a clone?

### Additional Details

I was looking at the todomvc example and notice 2 peculiar lines of code
```
            let s = item.title.clone();
            child.push(&JsValue::from(&s));
```
`item.title` is a `String` and `child` is a `js_sys::Array`.

This code attempts to clone the String before it is passed into `from`, but this is unnecessary since `from` just borrows the string slice. So I tried to simplify the code as follows
```
            let s = &item.title;
            child.push(&JsValue::from(s));
```
I took out the clone and there are no compile errors!

 I am confused about how this could work because surely a clone needs to take place somewhere for `child` to `push` a new `JsValue`. Perhaps the trait `From<&'a String>` is implemented in a way such that `clone` is called for you? In which case, the code example's call to `clone` is unnecessary. Is there something I am not seeing here? Perhaps it will lead to a runtime error?

**Comment by Pauan** [comment]
When you send a Rust `String` (or `&str`) to JS, it will convert it into a JS string. This requires it to make a copy of the string. So you are right that the `.clone()` is unnecessary.

**Comment by UnHumbleBen** [comment]
@Pauan Can you pinpoint the exact code where the copy happens?

**Comment by alexcrichton** [comment]
The copy into JS happens in generated code, roughly [looking like this](https://github.com/rustwasm/wasm-bindgen/blob/cbab8a191dd9c22fe826ac0409f856f0876de8a0/crates/cli-support/src/js/mod.rs#L1110-L1112).
