### ISSUE TITLE
Why doesn't `js_sys::Array::push` move the argument?

### ISSUE THREAD

**Issue by UnHumbleBen** [rustwasm/wasm-bindgen#1706]
### Summary

I understand that `vec::Vec::push` moves the argument. How come `js_sys::Array::push` only needs to borrow the `JsValue`?

### Additional Information

Function signature of `js_sys::Array::push`
```
pub fn push(&self, value: &JsValue) -> u32
```

Function signature of `vec::Vec::push`
```
pub fn push(&mut self, value: T)
```

**Comment by Pauan** [comment]
You can think of `JsValue` as being similar to `Rc` or `Arc`: it's valid to have many owned copies at the same time, and calling `clone()` on a `JsValue` is very fast. This is because in JavaScript all values are garbage collected.

So because you're pushing a JavaScript value into the Array, you don't need to worry about ownership, because JavaScript's garbage collector will handle ownership, so a `&` is good enough.

**Comment by UnHumbleBen** [comment]
@Pauan I am not too familiar with JavaScript's memory model. Does treating `JsValue` as a pointer apply to the actual language of JavaScript itself? For instance, if I have a JavaScript Array of some class call Foo, does that Array contains pointers to Foo, and not the actual memory of Foo itself?

**Comment by alexcrichton** [comment]
This is sort of our best attempt to map JS semantics onto Rust, but there's going to be a natural mismatch. There are not types in JS or addresses of items, in JS you've just got values and can reference them multiple times from multiple variables. There's approximations to what happens in Rust but there's nothing exactly the same.

The signatures here are our approximation of what `push` does on an array in JS. An `Array` can hold a bunch of values but they don't have addresses, it just holds values. They also don't have types, it's just normal JS values in the array.

The ergonomics of `wasm-bindgen` and Rust are what drives this signature where the way we model JS values in Rust (`JsValue`) doesn't require ownership on the Rust side to call a JS API, and it can be more efficient for our model in some circumstances. Remember though that everything we do in Rust is an approximation of JS and is geared towards making it easy to interoperate with JS.
