### ISSUE TITLE
Orphan rule: implementing From for String

### ISSUE THREAD

**Issue by UnHumbleBen** [rustwasm/wasm-bindgen#1708]
### Summary

```
impl<'a> From<&'a JsString> for String
```

How can the `js_sys` implement the `From` trait for `String` if both of these traits are defined in an external crate? Doesn't this violate the orphan rule?

**Comment by alexcrichton** [comment]
Thanks for the report! In this case `JsString` is a local type, so wasm-bindgen the crate can implement it.
