### ISSUE TITLE
Update wasm-bindgen-futures to futures-preview-0.3.0-alpha.18

### ISSUE THREAD

**Issue by ibaryshnikov** [rustwasm/wasm-bindgen#1719]
There was some [changes](https://github.com/rust-lang-nursery/futures-rs/blob/master/CHANGELOG.md#030-alpha18---2019-9-9) in futures-preview, in particular

> Changed ArcWake::into_waker to a free function waker

**Comment by alexcrichton** [comment]
Done in https://github.com/rustwasm/wasm-bindgen/pull/1716!

**Comment by ibaryshnikov** [comment]
Cool, didn't notice it

**Comment by najamelan** [comment]
@alexcrichton Do you think it would be possible to roll out a release to crates? This breaks unit tests and compilation for anything that pulls in alpha.18...

**Comment by alexcrichton** [comment]
Sure thing, I've started that at https://github.com/rustwasm/wasm-bindgen/pull/1722
