### ISSUE TITLE
How best to document wasm-bindgen?

### ISSUE THREAD

**Issue by alexcrichton** [rustwasm/wasm-bindgen#172]
There's a surprinsingly large amount of moving parts in wasm-bindgen! I've tried to update `DESIGN.md` and `README.md` as I got along but I'm continually running across pieces of functionality that don't fit great into the documentation today. For example I'm not sure where to document the new crate feature added in https://github.com/rustwasm/wasm-bindgen/pull/171.

I'm curious to hear others' thoughts if you've got any on this! I'm not sure if a book-like format would be best or if there's better ways to document things. I definitely want to ensure that questions have answers in docs ideally!

**Comment by sendilkumarn** [comment]
Can we add them in the wiki page ?

**Comment by alexcrichton** [comment]
Seems plausible! I've had not-so-great experiences with wiki pages in the past though as they're so far divorced from the code they're not always updated. I'd ideally prefer an in-tree solution so changes can be reviewed too, but that may also be a bit of a big ask!

**Comment by sendilkumarn** [comment]
Yeah, I extensively used wiki (with Gitlab) for majority of products. It is completely isolated and special attention is needed for dragging it along. But it is really very useful from documentation perspective

**Comment by konstin** [comment]
I'd prefer just having header with a short explanation and an example per feature in the readme. Once there is too much documentation for a single readme, the readme and the design.md should be combined into a mdbook. This might then eventually be joined with the current rust-wasm book.

**Comment by alexcrichton** [comment]
@konstin heh that is also certainly the direction most Rust projects seem to be going in! I'd certainly be a fan of having a book which grows over time. I'm not exactly sure how it'd be organized but I'd imagine we could figure something out on the fly

**Comment by adityac8** [comment]
@alexcrichton Are we talking to have something similar to [this book](https://github.com/rust-lang-nursery/rust-wasm)? If that is the case, then that sounds great.

**Comment by alexcrichton** [comment]
@adityac8 indeed! I think a good start would basically be to reorganize the existing documentation into a book format and we could probably go from there

**Comment by alexcrichton** [comment]
We've now got a guide as of https://github.com/rustwasm/wasm-bindgen/pull/276, which should solve this!
