### ISSUE TITLE
Reading files in WASM

### ISSUE THREAD

**Issue by ccartas** [rustwasm/wasm-bindgen#1727]
I am trying to build an electron application that uses WASM. I have a Rust library that can process files and I cannot make it work. I've read the `wasm_bindgen` documentation related to `std::fs` and I've used sample from the documentation:
#[wasm_bindgen]
pub fn schedule_some_work_for_next_tick(path: String) -> js_sys::Promise {
    let future = NextTick::new()
        // Do some work...
        .and_then(move |_| {
            let data:  Vec<u8> = fs::read(path.as_str()).expect("Unable to read file");
            Ok(data.len() as f64)
        })
        // And then convert the `Item` and `Error` into `JsValue`.
        .map(|result| {
            JsValue::from(result)
        })
        .map_err(|error| {
            let js_error = js_sys::Error::new(&format!("uh oh! {:?}", error));
            JsValue::from(js_error)
        });
    future_to_promise(future)
}

And when i try to run the code i get the following error:
`
Uncaught (in promise) RuntimeError: unreachable
    at __rust_start_panic (wasm-function[1560]:1)
    at rust_panic (wasm-function[1403]:31)
    at std::panicking::rust_panic_with_hook::h272251e545151171 (wasm-function[255]:304)
    at std::panicking::continue_panic_fmt::h36704b4bf13862b1 (wasm-function[670]:116)
    at rust_begin_unwind (wasm-function[1545]:3)
    at core::panicking::panic_fmt::h674ac69fd62081ee (wasm-function[1127]:70)
    at core::result::unwrap_failed::h16740d336e2fc0a4 (wasm-function[597]:127)
    at core::result::Result<T,E>::expect::h5b0167259ebeaa51 (wasm-function[193]:267)
    at wasm_rust::schedule_some_work_for_next_tick::{{closure}}::h8d8afcb77b2c5e80 (wasm-function[287]:125)
    at <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll::{{closure}}::{{closure}}::hed909d35d6b9a53d (wasm-function[402]:114)
`

The wasm module was built using `cargo +nightly build --target wasm32-unknown-unknown` and `wasm-bindgen target/wasm32-unknown-unknown/debug/wasm_rust.wasm --out-dir wasm/ --web --no-typescript`

Anyone have any ideas if accessing files can be done via WASM or how to get the example working?

**Comment by Pauan** [comment]
Currently you cannot use any of the Rust filesystem APIs (like `std::fs`), instead you have to use browser APIs like [`fetch`](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.Window.html#method.fetch_with_str), or you can import the Electron `fs` APIs and use those instead:

```rust
#[wasm_bindgen]
extern "C" {
    type Buffer;
}

#[wasm_bindgen(module = "fs")]
extern "C" {
    #[wasm_bindgen(js_name = readFileSync, catch)]
    fn read_file(path: &str) -> Result<Buffer, JsValue>;
}
```

Or you can import a local JS file and then do whatever you want inside of there:

```rust
#[wasm_bindgen(module = "/foo.js")]
extern "C" {
    #[wasm_bindgen(catch)]
    fn read_file(path: &str) -> Result<String, JsValue>;
}
```

```js
const fs = require("fs");

export function read_file(path) {
    return fs.readFileSync(path, { encoding: "utf8" });
}
```

**Comment by alexcrichton** [comment]
I think @Pauan has this covered, so I'm going to close this

**Comment by mb720** [comment]
Here's a minimalist example application for reading files with Wasm: https://gitlab.com/bullbytes/read_file_with_wasm

It's a combination of these two very helpful example projects:

  * https://github.com/sgasse/wasm_worker_interaction
  * https://github.com/Badel2/wasm-bindgen-file-reader-test

**Comment by tomasdev** [comment]
Emscripten provides FS which basically mounts an in-memory (browser) filesystem. Could we have that? https://emscripten.org/docs/api_reference/Filesystem-API.html#memfs

**Comment by daxpedda** [comment]
`std::fs` can not be addressed in `wasm-bindgen`, that's a Rust Std issue. But for many reasons it is currently not possible to access Web APIs in Std, so this is unlikely to get fixed without a separate dedicated Rust target or a new Wasm proposal.
