### ISSUE TITLE
 Could not compile proc-macro2

### ISSUE THREAD

**Issue by SerhiiBilyk** [rustwasm/wasm-bindgen#174]
After **cargo +nightly build --target wasm32-unknown-unknown**, I havenext errors:

  --> /home/serhii/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.3.7/src/unstable.rs:63:45
   |
63 |                 let mut group = proc_macro::Group::new(delim, tt.stream.inner.0);
   |                                             ^^^^^ Could not find `Group` in `proc_macro`

   --> /home/serhii/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.3.7/src/unstable.rs:301:27
    |
301 |               Literal::_new(proc_macro::Literal::$name(n))
    |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `proc_macro::Literal`

You've got a few errors: E0433, E0599
If you want more information on an error, try using "rustc --explain E0433"
error: Could not compile `proc-macro2`.

I don't know, what I'm doing wrong. Please help. Thank you

**Comment by SerhiiBilyk** [comment]
Linux,
My Cargo.toml:
[package]
name = "js-hello-world"
version = "0.1.0"
authors = ["Serhii Bilyk <sergiybiluk@gmail.com>"]

[dependencies]
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib"]

**Comment by alexcrichton** [comment]
Thanks for the report! Can you try updating your Rust compiler to the latest nightly and see if it works for you?

**Comment by SerhiiBilyk** [comment]
Thank you for your respond, but problem is already resolved. I've just did 'rustup update' :)))

**Comment by SerhiiBilyk** [comment]
Tip: if any body will see this error in Chrome browser->**"WebAssembly.Instance is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.instantiate."**, please try FireFox

**Comment by alexcrichton** [comment]
Indeed! There's some more information about that here -- https://github.com/rustwasm/wasm-bindgen/tree/master/examples/hello_world#caveat-for-chrome-users
