### ISSUE TITLE
[Call for help] Failed to pack generated code by wasm-pack using webpack

### ISSUE THREAD

**Issue by leonwanghui** [rustwasm/wasm-bindgen#1751]
### Describe the Bug

Please see https://github.com/rustwasm/wasm-pack/issues/710 for detailed information, thanks!

### Steps to Reproduce

If applicable, add a link to a test case (as a zip file or link to a repository we can clone).

### Actual Behavior

A clear and concise description of what actually happened.

**Comment by alexcrichton** [comment]
Thanks for opening an issue here, but in an effort to keep this contained I'm going to close this in favor of the wasm-pack issue.
