### ISSUE TITLE
less verbose way to have wasm and non-wasm tests?

### ISSUE THREAD

**Issue by mikemoraned** [rustwasm/wasm-bindgen#1768]
### Summary

In https://github.com/image-rs/imageproc/pull/386 I am extending https://github.com/image-rs/imageproc to have wasm tests by re-using the existing tests. The way I am doing this is based on this post, https://www.reddit.com/r/rust/comments/a80rst/pure_wasm_crate_testing/ec8q9r3/ i.e.

```rust
#[cfg_attr(not(target_arch = "wasm32"), test)]
#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test)]
fn test_connected_components_eight_white_background() {
...
}
```

However, this is verbose compared to `#[test]`. Given the above post was 8 months ago, is there now a better way to do this?

If not, is there any WIP I could help with to make it more succinct?

**Comment by alexcrichton** [comment]
Currently there's not a less verbose way of doing this, but I agree that there should be! I'm not entirely sure what this would look like though

**Comment by dcormier** [comment]
Maybe it would be nice if something like `#[wasm_bindgen_test(also_non_wasm)]` worked.

**Comment by daxpedda** [comment]
Addressed by https://github.com/rustwasm/wasm-bindgen/pull/4150.

In the next breaking change we should probably do the reverse: by default apply `test` and add an option to opt-out.
