### ISSUE TITLE
Example doesn't mention running a HTTP Server

### ISSUE THREAD

**Issue by matthewrobertbell** [rustwasm/wasm-bindgen#1769]
https://github.com/rustwasm/wasm-bindgen/tree/master/examples/without-a-bundler

This works fine when running build.sh. Literally following the instructions (build then open index.html) doesn't work, because of CORS. Adding a mention to run "python3 -m http.server" should make this more friendly.

Thanks for your work!

**Comment by fitzgen** [comment]
Good idea! Care to make a pull request?

**Comment by daxpedda** [comment]
Resolved by #3819.
