### ISSUE TITLE
raytrace-parallel ERROR when i use firefox-nightly and opened shared memory

### ISSUE THREAD

**Issue by Anehta** [rustwasm/wasm-bindgen#1773]
i fixed some error after last issuse
but
i get an error when i use firefox-nightly
![图片](https://user-images.githubusercontent.com/6553443/65258626-c4062f00-db35-11e9-86ac-589370a992ae.png)
![图片](https://user-images.githubusercontent.com/6553443/65258627-c4062f00-db35-11e9-9bc3-0ac5d621ec7e.png)

so...how to fix

**Comment by Anehta** [comment]
i get this error when I personally compiled it in win10
![图片](https://user-images.githubusercontent.com/6553443/65259885-02045280-db38-11e9-85f4-c9b09a87de05.png)

env:
firefox-nightly 71.0a1

toolchain:
nightly-x86-64-windows-gnu

build-script:
```export RUSTFLAGS='-C target-feature=+atomics,+bulk-memory'
rustup run nightly-x86_64-pc-windows-gnu xargo build --target wasm32-unknown-unknown --release

# Note the usage of `--no-modules` here which is used to create an output which
# is usable from Web Workers. We notably can't use `--target bundler` since
# Webpack doesn't have support for atomics yet.
rustup run nightly-x86_64-pc-windows-gnu cargo run --manifest-path ../../crates/cli/Cargo.toml --bin wasm-bindgen -- ../../target/wasm32-unknown-unknown/release/raytrace_parallel.wasm --out-dir . --no-modules
```

**Comment by Anehta** [comment]
These problem took my 30h....

**Comment by Anehta** [comment]
50h....

**Comment by Rocky12321** [comment]
Hmm, I am having a smiliar kind of issue also fyi linux doesn't change the problem either.

**Comment by alexcrichton** [comment]
@Anehta sorry but if you're going to place a timer on the amount of time to get support for this that's unfortunately not really going to help but only antagonize maintainers. We're all busy and this is an open source project which means there's no guarantee about when you can get help for an issue. 

The report here is unfortunately relatively cryptic and difficult to decipher. To compile the parallel-raytrace example you'll need a recent Rust nightly and you'll want to use or follow the `build.sh` script that it has. This is all nightly and unstable so not every combination of everything will produce great errors if things don't align, so there's likely some issue along the way which needs to be understood and updated.

**Comment by ibaryshnikov** [comment]
> The report here is unfortunately relatively cryptic and difficult to decipher

It's possible to reproduce `RuntimeError: "indirect call to null"` by opening compiled example.
I use MacOS, firefox nightly 71.0a1 (2019-09-25) (64-bit)

**Comment by alexcrichton** [comment]
Looks like this accidentally regressed in 2fbb8359e0ada6c94af467f6b1b1837fecaced62  (cc @fitzgen), digging in now
