### ISSUE TITLE
How do you use a Rust struct with a `String` field?

### ISSUE THREAD

**Issue by garrettmaring** [rustwasm/wasm-bindgen#1775]
### Summary

How do you use a Rust struct with a `String` field using wasm-bindgen?

The `String` type seems to be supported for function parameters and return values. https://rustwasm.github.io/docs/wasm-bindgen/reference/types/string.html

### Additional Details

```rust
#[wasm_bindgen]
pub struct Data {
    id: String,
}
```

**Comment by alexcrichton** [comment]
Thanks for the report! For this you'll want to use [getters and setters](https://rustwasm.github.io/docs/wasm-bindgen/reference/attributes/on-rust-exports/getter-and-setter.html), and that shoul dod the trick!

**Comment by garrettmaring** [comment]
That worked! Thank you.

**Comment by andimarek** [comment]
Hi @garrettmaring can you share some details how exactly you solved it with getters and setters? thanks

**Comment by garrettmaring** [comment]
Sure!

```rust
// doesn't work...
#[wasm_bindgen]
struct Data {
    pub id: String,
}
```

You'll get the error **error[E0277]: the trait bound std::string::String: std::marker::Copy is not satisfied**.

Since, the `String` type in Rust [isn't implicitly copyable](https://stackoverflow.com/a/38305901/3599414). I had to read up on the [difference between `Copy` and `Clone`](https://doc.rust-lang.org/std/marker/trait.Copy.html) to understand that I couldn't just implement `Copy` but rather needed to use `.clone()` to explicitly copy it.

Thankfully, _wasm-bindgen_ gives us a simple way to do it. 

```rust
#[wasm_bindgen]
struct Data {
    id: String, // ensure that the field is private
}

#[wasm_bindgen]
impl Data {
    #[wasm_bindgen(getter)]
    pub fn id(&self) -> String {
        self.id.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_id(&mut self, id: String) {
        self.id = id;
    }
}
```

There are some interesting things that you can do with getters and setters that are documented [here](https://rustwasm.github.io/docs/wasm-bindgen/reference/attributes/on-rust-exports/getter-and-setter.html).

**Comment by garrettmaring** [comment]
@alexcrichton would it be feasible for _wasm-bindgen_ to generate this code if a `struct` implements `Clone`?

**Comment by alexcrichton** [comment]
It's plausible, yeah! It's something though we've avoided doing historically because a `Clone` implementation can often be accidentally quite expensive, so we tend to prefer to request that users do so manually to ensure they know the cost they're opt-ing into

**Comment by alexcrichton** [comment]
Now that being said, it'd be a neat feature to do something like `#[wasm_bindgen(getter_setter_with_clone)]` or something like that so the boilerplate could be drastically reduced

**Comment by terwer** [comment]
Thanks @garrettmaring , it works.
