### ISSUE TITLE
`#[wasm_bindgen(skip)]` for impls functions

### ISSUE THREAD

**Issue by alexlapa** [rustwasm/wasm-bindgen#1790]
### Motivation

Add way to skip pub functions in #[wasm_bindgen] impls when generating JS glue. 

### Proposed Solution

```rust
#[wasm_bindgen]
impl Foo {
    #[wasm_bindgen(skip)]
    pub fn bar(&self) -> i32 {
        7
    }
}
```
### Alternatives

Skip `pub (crate/self/anything)` functions.

**Comment by Pauan** [comment]
You can accomplish this by simply not using `#[wasm_bindgen]`:

```rust
impl Foo {
    pub fn bar(&self) -> i32 {
        7
    }
}

#[wasm_bindgen]
impl Foo {
    // functions that you want to send to JS
}
```

This works because you can have many `impl` blocks for a single type.

**Comment by alexlapa** [comment]
@Pauan ,

Thanks! Closing then.
