### ISSUE TITLE
raytrace-parallel demo broken on chrome 77

### ISSUE THREAD

**Issue by rbtcollins** [rustwasm/wasm-bindgen#1800]
### Describe the Bug
Sometimes a picture paints a thousands words.
![image](https://user-images.githubusercontent.com/499678/65946199-1b8b8f80-e492-11e9-834f-2d7b3a1cefbb.png)

### Steps to Reproduce

1. Use Chrome
2. Visit https://rustwasm.github.io/wasm-bindgen/exbuild/raytrace-parallel/

If applicable, add a link to a test case (as a zip file or link to a repository we can clone).

### Expected Behavior
A working raytracer

### Actual Behavior

A clear and concise description of what actually happened.

**Comment by ibaryshnikov** [comment]
It's not supposed to work in version 77. But it started to work recently in canary, for example 79.0.3928.3

**Comment by alexcrichton** [comment]
Thanks for the report! As pointed out by @ibaryshnikov Chrome stable doesn't have enough support for the demo but Chrome Canary does!

**Comment by rbtcollins** [comment]
Thanks! Is there any easy way to tell where the supported levels are all at?

**Comment by rbtcollins** [comment]
Also, it is broken, differently for me in canary 79.0.3929.0 (Official Build) canary (64-bit)
![image](https://user-images.githubusercontent.com/499678/65993597-0b090280-e4ee-11e9-98a5-7863671f3daf.png)

**Comment by rbtcollins** [comment]
Filed as https://bugs.chromium.org/p/chromium/issues/detail?id=1010272 after we narrowed this down to 16+ cores only having the issue
