### ISSUE TITLE
wasm-bindgen-test-runner hardcoded 20s timeout for headless mode.

### ISSUE THREAD

**Issue by artemii235** [rustwasm/wasm-bindgen#1801]
### Describe the Bug

Wasm-bindgen-test-runner has hardcoded [20 seconds timeout for headless mode](https://github.com/rustwasm/wasm-bindgen/blob/master/crates/cli/src/bin/wasm-bindgen-test-runner/headless.rs#L148). It actually seems too low and also produces cryptic error when timeout is triggered.

### Steps to Reproduce

1. Install wasm-pack and firefox.
1. Clone https://github.com/artemii235/w-bindgen-test-run-timeout
1. Run `wasm-pack test --firefox --headless`.
1. See error
```
console.log div contained:
    Start my long integration test

driver status: signal: 9                          
driver stdout:
    1569938701576       mozrunner::runner       INFO    Running command: "/usr/bin/firefox" "-marionette" "-headless" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.99lHCwkKLbad"
    1569938701972       addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
    1569938701972       addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: telemetry
    1569938701973       addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
    1569938701973       addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
    1569938703306       Marionette      INFO    Listening on port 36397
    1569938723711       Marionette      INFO    Stopped listening on port 36397

driver stderr:
    *** You are running in headless mode.

error: some tests failed                          
error: test failed, to rerun pass '--lib'
Error: Running Wasm tests with wasm-bindgen-test failed
Caused by: failed to execute `cargo test`: exited with exit code: 1
```
### Expected Behavior

The test should output `My long integration test finished successfully` or at least that it's timed out with more detailed description.

### Actual Behavior

Test times out with error that doesn't tell what actually went wrong. At the beginning I considered `driver status: signal: 9` as webdriver or headless firefox script run time limitation, but it turned out the reason is in test runner terminating the webdriver process.

### Additional Context

It would be very nice to have the option to set the timeout explicitly by env or command line argument. Integration tests might run for quite long time (e.g. in my case tests might have to wait for transaction confirmations in cryptocurrencies blockchains) so I need to increase a timeout accordingly to e.g. 10 minutes. 20 seconds might be not even enough for big pure unit tests suite.

**Comment by alexcrichton** [comment]
Thanks for the report and seems reasonable to me to change! I was mostly thinking of compute-heavy tests when writing that but this should at bare minimum be configurable!
