### ISSUE TITLE
Provide kinder error in JS when hitting unimplemented!() in Rust

### ISSUE THREAD

**Issue by garrettmaring** [rustwasm/wasm-bindgen#1810]
### Motivation

Currently, I see this error when hitting an `unimplemented!()` call on the Rust side of things.

```
wasm-bindgen: imported JS function that was not marked as 
`catch` threw an error: unreachable
```

### Proposed Solution

I have no proposed solution.

I think I read somewhere that panic behavior is tricky. There are also unkind errors when running tests with failed assertions. Possibly related.

### Alternatives

I'm just doing this for now. `print_error` is a macro that uses web-sys' `console::error`.

```
macro_rules! log_unimplemented {
    () => ({
        print_error!("not yet implemented");
        panic!("not yet implemented");
    })
}
```

**Comment by Pauan** [comment]
Have you tried using [`console_error_panic_hook`](https://crates.io/crates/console_error_panic_hook)?

**Comment by alexcrichton** [comment]
I'm going to close this because this should be covered by @Pauan's suggestion.
