### ISSUE TITLE
Outdated Worklet IDL

### ISSUE THREAD

**Issue by msiglreith** [rustwasm/wasm-bindgen#1813]
The Worklet IDL has been changed [2 years ago](https://github.com/w3c/css-houdini-drafts/commit/b63a14e5855620570c276ce77eaa9d7d18488c6a) , but the IDL in the web-sys repository still uses the old version:

Current API:
```
interface Worklet {
  [NewObject, Throws, NeedsCallerType]
  Promise<void> import(USVString moduleURL);
};
```

New API:
```
[Exposed=Worklet]
interface WorkletGlobalScope {
};

[Exposed=Window]
interface Worklet {
    [NewObject] Promise<void> addModule(USVString moduleURL, optional WorkletOptions options);
};

dictionary WorkletOptions {
    RequestCredentials credentials = "same-origin";
};
```

**Comment by alexcrichton** [comment]
Thanks for the report! We copied over the WebIDL from Gecko at some point in the past, would you be up for copying over the new WebIDL for these APIs?
