### ISSUE TITLE
Support for interop between multiple crates

### ISSUE THREAD

**Issue by That3Percent** [rustwasm/wasm-bindgen#1815]
I'm looking at the generated .js code for a project using wasm-bindgen, and it has a single heap array used by each exported function in the module.

If I were to break the single crate into multiple using a single workspace, would there be issues trying to pass references around that were instantiated by different crates?

**Comment by Pauan** [comment]
Workspaces does *not* mean that all the crates are compiled together. Workspaces just means that the `Cargo.lock` is shared, not the crates themself.

Each crate in the workspace has to be compiled separately, so each crate will get a separate heap.

If you want to have one crate access another crate (and thus share the same heap), you have to add them as dependencies, like usual:

```toml
[dependencies]
my-crate = { path = "path/to/my/crate" }
```

**Comment by That3Percent** [comment]
Let me be explicit about the scenario for a moment, talk about how I think I need to go about fixing the problem, and then float a change to wasm-bindgen that could make this easier.

**The Problem**
I have 1 monolith crate, and would like to split it into 3. Let's call them A, B, and C. Both B and C are both dependent on A. All three contain #[wasm_bindgen] exports.

If I build any subset of crates A, B, and C to get it's exports, I loose the ability to interop between either A->B or A->C or both, depending on what combination is built.

**The Solution?**
I think the information you've laid out requires that a new crate D be created, which depends on A, B, and C. It's sole purpose would be to re-export the contents of those other crates. This would work, right?

**Something Easier?**
If the heap code generated in the glue file was just a module imported by the glue file, then it would be possible to share that module/heap across all the glue files, enabling interop. (Eg: JavaScript code calls a function in A, and passes the result to B). This would remove the need for crate D.

I'm not sure if this causes other problems, like redundant wasm code in the final bundle.

**Comment by Pauan** [comment]
@That3Percent I'm sorry, I'm not understanding your use case.

I understand wanting to split your code into separate crates, but why are you building B and C separately?

Normally it would be the other way around, you would have crates B and C (which are separate), and then A would depend on B and C.

Crates in Rust have to form a directed acyclic graph, so there always has to be 1 root crate, so the only reason to build B and C separately is if B and C are actually completely separate applications.

**Comment by That3Percent** [comment]
@Pauan I would be building B and C separately because then they could be imported as separate modules from JavaScript, for organizational purposes.

I see now that the workflow of introducing crate D to re-export B and C is not that bad in practice at the current scale for our code base. Combined with the js_namespace attribute, one can get something like separate modules as well. Closing since this state of affairs is acceptable to me.
