### ISSUE TITLE
License question: Are the .idl files really covered by Apache 2.0/MPL?

### ISSUE THREAD

**Issue by psychon** [rustwasm/wasm-bindgen#1822]
Random example from an `.idl` file:
https://github.com/rustwasm/wasm-bindgen/blob/46cbd19e60b8c08e4c1ad94a38df51c0796a20ff/crates/web-sys/webidls/enabled/Animation.webidl#L2-L10

Following the source link, I cannot find any mention of Apache nor MPL. Instead, the only license statement seems to be:

> Copyright © 2019 W3C® (MIT, ERCIM, Keio, Beihang). W3C liability, trademark and permissive document license rules apply.

(You seem to half-quote this sentence in the `.idl` file, but "document use rules" vs "permissive document license rules" is clearly a different.)

`permissive document license` is a link to here: https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document

This is clearly not the MPL nor the apache license.

Could you please clarify the situation for me and update your license statement(s) accordingly? Thanks.

Edit: You seem to violate this parts of the permissive document license:

> that you include the following on ALL copies of the work or portions thereof, including modifications:
>
> * The full text of this NOTICE in a location viewable to users of the redistributed or derivative work.
> * Any pre-existing intellectual property disclaimers, notices, or terms and conditions. If none exist, the W3C Software and Document Short Notice should be included.
> * Notice of any changes or modifications, through a copyright statement on the new code or document such as "This software or document includes material copied from or derived from [title and URI of the W3C document]. Copyright © [YEAR] W3C® (MIT, ERCIM, Keio, Beihang)."

(The last bullet part seems to be half okay? I am a bit confused about "Notice of any changes or modifications through a copyright statement".)

**Comment by alexcrichton** [comment]
Sorry for the late response, but the license listed is for the Rust code, the webidl files I believe have their own license.
