### ISSUE TITLE
Browser Compatibility Safari: InvalidCharacterError Without a Bundler

### ISSUE THREAD

**Issue by SimonAdameit** [rustwasm/wasm-bindgen#1832]
Given the examples in the repository:
- dom
- without-a-bundler
- without-a-bundler-no-modules

The examples run fine in Firefox and Chrome, however only the _dom_ example runs in Safari [Version 13.0.2 (15608.2.30.1.1)], while the other two result in this javascript error:

```
Unhandled Promise Rejection: InvalidCharacterError: The string contains invalid characters.
```

**Comment by Pauan** [comment]
Seems like a duplicate of #1825 (which should be fixed in the next release).

**Comment by SimonAdameit** [comment]
@Pauan Thanks for the hint 👍  I'll close this as duplicate of: https://github.com/rustwasm/wasm-bindgen/issues/1825.
