### ISSUE TITLE
How do I read? transport? png file from js to rust(wasm)

### ISSUE THREAD

**Issue by poccariswet** [rustwasm/wasm-bindgen#1836]
### Summary

I don't know how to read png file at rust(wasm).
I want to know it because I will make apng maker on wasm web application.

**Comment by ibaryshnikov** [comment]
An image may be represented as an ArrayBuffer in JS. For example, we can create a `png` from a canvas context using [toBlob()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob) method with 'image/png' type. Blob has a method [arrayBuffer()](https://developer.mozilla.org/en-US/docs/Web/API/Blob/arrayBuffer). Finally, we can have
```javascript
let data = new Uint8Array(arrayBufferFromBlob);
wasm.processImage(data);
```
where in Rust it will look like
```rust
#[wasm_bindgen(js_name = processImage)]
pub fn process_image(data: Vec<u8>) {
   let result = image::load_from_memory_with_format(&data, image::ImageFormat::PNG);
   ...
}
```
Docs link for [load_from_memory_with_format](https://docs.rs/image/0.22.3/image/fn.load_from_memory_with_format.html)

**Comment by poccariswet** [comment]
@ibaryshnikov 
 Thank you for this solution.
Can I also use this to return image buf from rust to js?

**Comment by alexcrichton** [comment]
I think that @ibaryshnikov has this covered, and yes @poccariswet you can also return a `Vec<u8>` or a `Uint8Array`
