### ISSUE TITLE
The "Chat" link in README.md has expired

### ISSUE THREAD

**Issue by Limeth** [rustwasm/wasm-bindgen#1838]
The "Chat" link in README.md has expired. When creating invite links for discord channels, there is an option to "edit invite link" and change the maximum number of uses and expiration time. I generated a link pointing to #wg-wasm, which shouldn't expire:
https://discord.gg/xMZ7CCY

I can either make a PR, or someone can update the readme with their own link.

**Comment by alexcrichton** [comment]
Oh dear sorry about this! If you'd like to send a PR that'd be great!

**Comment by Triuman** [comment]
The Discord invite link is broken again.
