### ISSUE TITLE
Index out of bounds when allocating arrays in rust

### ISSUE THREAD

**Issue by tocttou** [rustwasm/wasm-bindgen#1848]
Hello, I am new to rust and wasm.

I am not sure if this has something to do with `wasm-bindgen`, but I am not able to allocate large arrays at runtime (even after `memory.grow` call).

Here is my JS:

```js
import init, { getMemory, PCLDecoder } from "./pkg/index.js";

async function run() {
  await init(undefined, {
    global: {},
    env: {
      memory: new WebAssembly.Memory({ initial: 10000 })
    }
  });
  const memory = getMemory();
  console.log(memory.buffer);
  memory.grow(1);
  // memory does grow
  const test = new PCLDecoder(); // RuntimeError: index out of bounds
}

run();
```

Here is my `lib.rs`:

```rust
extern crate console_error_panic_hook;

use scroll::Pread;
use wasm_bindgen::prelude::*;

// usize here represents 32bits for the pointer space, since wasm target is 32bit
const MEMORY_WIDTH: usize = 240_000 * 3;

#[wasm_bindgen]
pub struct PCLDecoder {
    copy_memory_buffer: [u8; MEMORY_WIDTH],
    position_memory_buffer: [f32; MEMORY_WIDTH / 8],
    color_memory_buffer: [f32; MEMORY_WIDTH / 8],
}

#[wasm_bindgen]
impl PCLDecoder {
    #[wasm_bindgen(constructor)]
    pub fn new() -> PCLDecoder {
        console_error_panic_hook::set_once();
        PCLDecoder {
            copy_memory_buffer: [0; MEMORY_WIDTH],
            position_memory_buffer: [0.0; MEMORY_WIDTH / 8],
            color_memory_buffer: [0.0; MEMORY_WIDTH / 8],
        }
    }
}
```

What I am trying to do with this is:

1. allocate memory directly in rust
2. write to `memory.buffer` in JS
3. process the data in rust
4. read the `memory.buffer` in JS again for the processed values

The error I get when calling the constructor is `RuntimeError: index out of bounds`, but that doesn't look right.

Interestingly, if I set the `MEMORY_WIDTH` to `240_000 * 2`, it seems to work fine.

Any help is appreciated!

**Comment by alexcrichton** [comment]
Thanks for the report! Would you be able to gist a complete example to reproduce? I'm not sure where the `getMemory` function comes from, for example.

**Comment by tocttou** [comment]
Hi, here is a working demo of this issue: https://webassembly.studio/?f=e85ddngsnkv (you can click on Build and Run).

In chrome it crashes the tab without any errors. In firefox it gives `[error]: RuntimeError: index out of bounds`. If the error was because of `wasm.memory`, I'd suppose it should give errors regarding that.

**Comment by tocttou** [comment]
Looks like that was the issue ^

Would you suggest some other way to allocate this data in the heap instead? I am new to wasm, thanks!

**Comment by Pauan** [comment]
@tocttou I'm curious why you're trying to allocate a 1.4 gigabyte struct.

**Comment by alexcrichton** [comment]
Yes I believe this is related to the stack size where you get a 1MB stack by default but the struct being allocated there is 240_000 * 5 bytes which is 1.2MB, which causes the stack to underflow. 

@Pauan where'd you get the 1.4 GB number from? (or maybe I'm looking at a different version of the gist?)

In any case though I don't think this is a bug in wasm-bindgen but rather an issue with your crate configuration, and I'd recommend using `RUSTFLAGS` to tweak the link arguments as necessary to allocate yourself more stack.

**Comment by Pauan** [comment]
@alexcrichton I'm referring to their original post, not the gist.

The `PCLDecoder` struct has a `u8` array with `720000` elements in it, an `f32` array with `90000` elements in it, and another `f32` array with `90000` elements in it.

Therefore that's `129600720000` bytes of stack-allocated data in the struct. That seems... *really* extreme. I can't even imagine the performance of moving it by-value. I don't even know of any systems that would support that amount of stack data by default.

The obvious solution is to just use `Vec` instead of arrays, so that way it will be heap-allocated.

**Comment by tocttou** [comment]
@Pauan it is for a [project](https://github.com/rapyuta-robotics/zethus) that I am working on that has to deserialize large pointcloud data which gets refreshed at a fixed rate. I'll have to do some benchmarks using Vec instead of arrays.

**Comment by Pauan** [comment]
@tocttou `Vec` is implemented internally with an array, so the performance is similar (other than the fact it's heap allocated).

If you use `vec![0; MEMORY_WIDTH]` it will allocate an array of the specified size. So as long as you don't increase the size of the `Vec`, then it only needs to do one allocation, so it shouldn't really be slower than an array.

In some cases `Vec` can even be faster (if you're moving around the struct by-value, for example). And if you mutate it then there shouldn't be any real speed difference. 

As for writing into it, I *really* don't recommend mucking around with the wasm memory directly, you would need to deal with all sorts of annoying stuff like pointer and size alignment.

Instead, just use [`Uint8Array::view`](https://rustwasm.github.io/wasm-bindgen/api/js_sys/struct.Uint8Array.html#method.view) and [`Float32Array::view`](https://rustwasm.github.io/wasm-bindgen/api/js_sys/struct.Float32Array.html#method.view) and send them to JS. Then JS can write into the `Uint8Array` and `Float32Array` directly, and it should mutate the `Vec` in Rust.

**Comment by tocttou** [comment]
:o The views method looks amazing.

 Thanks!
