### ISSUE TITLE
Upgrade package and not working?

### ISSUE THREAD

**Issue by pictca** [rustwasm/wasm-bindgen#1849]
### Summary
My current work used `wasm-bindgen v.0.2.29` on chrome-extension which works fine. 
When I tried to upgrade wasm-bindgen in current-version `(v.0.2.53)`.I can't compile `webpack ^4.29.5 ` with my old script and have  2 case of errors when calling `#[wasm_bindgen(start)`.
I attach some errors and some config scripts.
How I can fix this? 
### Additional Details
1. my extension has one file which starts the whole process.
2. `webpack v.4.28.5` also work with `wasm-bindgen v.0.2.29`
#### old script  which work on v.0.2.29
```bash
package=buzz/
lib=buzz
cd $package
wasm-pack build 
wasm2es6js pkg/${lib}_bg.wasm --base64 -o pkg/${lib}_bg.js 
mv -f pkg/${lib}_bg.wasm pkg/${lib}_bg.b.wasm
cd ..
npm run build
````

#### new script (1) - not error and do nothing with `#[wasm_bindgen(start)]`
```bash
package=buzz/
lib=buzz
cd $package
wasm-pack build 
wasm2js pkg/${lib}_bg.wasm -o pkg/${lib}_bg.js
sed -i 's/buzz_bg.wasm/buzz_bg.js/' pkg/buzz.js
cd ..
npm run build
````

#### new script (2) - error when calling function `#[wasm_bindgen`]
```bash
package=buzz/
lib=buzz
cd $package
wasm-pack build 
wasm2es6js pkg/${lib}_bg.wasm --base64 -o pkg/${lib}_bg.js
cd ..
npm run build
````
![Screenshot from 2019-11-02 20-39-10](https://user-images.githubusercontent.com/50473532/68071822-f9e33800-fdb0-11e9-8921-eb812b49532b.jpg)

**Comment by Pauan** [comment]
Could you share your code? We can't really figure out the problem just based on those error messages.

Also, I'm curious, why are you running `wasm2es6js`?

**Comment by pictca** [comment]
my rust code just simple like console.log("in wasm"); in `#[wasm_bindgen(start)]` function
I used `browserify` to merge some useful javascript packages bridge to wasm 
but  gen code from `wasm2js`   not support
```js
 import * as import_b from './buzz.js';  // not support
```
`wasm2es6js` which convert code to 
```js 
module.exports = loadWebAssembly;  // support 
...
``` 
 
`webpack.config.js`
```js
const path = require('path');
const webpack = require('webpack');
const UglifyJsPlugin = require('uglifyjs-webpack-plugin');
const nodeExternals = require('webpack-node-externals');
const WasmPackPlugin = require("@wasm-tool/wasm-pack-plugin");

module.exports = {
    //externals: [nodeExternals()],
    target: 'web',
    entry:{
        buzz: './buzz/pkg/buzz_bg.js',
    },
    output: {
        filename: 'buzz.ext.js',
        path: path.resolve(__dirname, 'dist'),
        libraryTarget: 'umd'
    },
    module: {
        rules: [
            {
                test: /\.m?js$/,
                exclude: /(node_modules|bower_components)/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        presets: ['@babel/preset-env']
                    }
                }
            }
        ]
    },
    optimization: {
        minimizer: [
            new UglifyJsPlugin({
                test: /\.js(\?.*)?$/i,
            }),
        ],
    },
    mode: 'development'
    //mode: 'production'
};
```

**Comment by pictca** [comment]
I think error from  `buzz_bg.js` in end of file which occurs error
> _buzz_bg__WEBPACK_IMPORTED_MODULE_0__.__wbindgen_start is not a function 

but when i debug by `console.log(wasm);`  It shows module
![error](https://user-images.githubusercontent.com/26379684/68085091-7c323180-fe6f-11e9-8a70-8f3dd74b0fc2.png)

 when I call `console.log(wasm.run);` `console.log(wasm.__wbindgen_start);` or `console.log(wasm["run"])`  they're show `undefinded`.

**Comment by pictca** [comment]
I fixed it. add this on `build.sh`. I think problem  from es6 module which can't call outsider. :grimacing:

```bash
sed -i 's/buzz_bg.wasm/buzz_bg/' pkg/buzz.js
sed -i -e 's/wasm.__wbindgen_start();//g' pkg/buzz.js
sed -i '22i __wbindgen_start();' pkg/buzz_bg.js
```
