### ISSUE TITLE
js-sys Error::set_name() doesn't work.

### ISSUE THREAD

**Issue by zer0x64** [rustwasm/wasm-bindgen#1860]
### Describe the Bug

The `set_name()` method of the javascript `Error` error type in js-sys doesn't work.

### Steps to Reproduce
1. Compile this method:
```
#[wasm_bindgen]
pub fn test() -> Result<(), JsValue> {
    let mut js_error = js_sys::Error::new("test1");
    js_error.set_name("test2");
    Err(js_error.into())
}
```
2. Call the function from Javascript.

### Expected Behavior

The error should show in the console as `test2: test1`.

### Actual Behavior

The error shows up in the console as `Error: test1`.
![image](https://user-images.githubusercontent.com/17575242/68873569-d469fe80-06cd-11ea-9494-327b82d4ddd2.png)

**Comment by Pauan** [comment]
This doesn't seem to be an issue with wasm-bindgen, it also happens with raw JS:

```js
let js_error = new Error("test1");
js_error.name = "test2";
throw js_error;
```

**Comment by zer0x64** [comment]
Might be browser-dependant, but my tests are on Firefox and works as expected using your exact script:
![image](https://user-images.githubusercontent.com/17575242/68899793-6d197200-0700-11ea-9b44-069a87407c16.png)

**Comment by Pauan** [comment]
@zer0x64 This is very strange, in Chrome it sometimes shows `test2` and sometimes `Error`. If you re-test your original wasm-bindgen code multiple times in different browsers, do you get different results?

**Comment by zer0x64** [comment]
The results I get here:
Using raw JS, I get "test2" using both browser.
Using WASM, I consistently get "test2" on Chrome and "Error" on Firefox.

**Comment by zer0x64** [comment]
Even weirder: If I try/catch the exception in javascript and print the `e.name`, It prints out the right name I've set, but if it is not caught, it prints `Error`.

**Comment by alexcrichton** [comment]
I'm going to close this because this looks like browser/JS weirdness, and seems unrelated to wasm-bindgen and/or the generated bindings.
