### ISSUE TITLE
Version mismatch error when invoking exposed function via wasmtime 

### ISSUE THREAD

**Issue by mboogerd** [rustwasm/wasm-bindgen#1862]
### Describe the Bug

I created a minimal wasm-bindgen library example as per the guide [here](https://bytecodealliance.github.io/wasmtime/wasm-rust.html#webassembly-interface-types). I can build the WASM library, but when trying to invoke an exposed function I encounter a version mismatch error.

### Steps to Reproduce

1. Setup the project as per the guide:

**Cargo.toml**
```toml
[dependencies]
wasm-bindgen = "0.2.54"

[lib]
crate-type = ["cdylib"]
```

**src/lib.rs**
```rust
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub fn greet(name: &str) -> String {
    format!("Hello, {}!", name)
}
```

2. Install wasm-bindgen-cli (0.2.54) and cargo-wasi (v0.1.17).
3. Build the project: `cargo wasi build --release`
4. Invoke the exposed function: `wasmtime --invoke greet ./target/wasm32-wasi/release/wasi_lib.wasm "123"`

### Expected Behavior

I expected the `wasmtime` invocation to return `"Hello, 123!"`.

### Actual Behavior

Instead it returned the following
```
error: failed to process main module `./target/wasm32-wasi/release/wasi_lib.wasm`
    caused by: version mismatch in the bindings section: wasm file has `0.6.0` and this library supports `0.5.0`
```

### Additional Context

When I leave out all wasm-bindgen stuff and instead expose native/#[no_mangle] functions (i.e. the previous example from the same guide), the build and invocation of exposed functions work as expected. This suggests that the culprit is `wasm-bindgen`. The minimal size of the failing example makes me think this is probably my machine instead, although I have no clue how to continue debugging this. Can you confirm whether this is a bug / help me understanding the issue if it isn't?

Other setup details if relevant:
- rustup 1.20.2
- cargo 1.39.0
- rustc 1.39.0

**Comment by alexcrichton** [comment]
Thanks for the report! I think this is not a wasm-bindgen mismatch but actually a wasm interface types custom version mismatch. Can you confirm that wasmtime itself is up-to-date?

**Comment by mboogerd** [comment]
/me facepalms

Should have remembered that wasmtime was a separate installation. wasmtime was at version 0.2.0. Things work as expected after updating. Thanks a bunch @alexcrichton!
