### ISSUE TITLE
Exporting struct causes TypeError: WebAssembly.instantiate() when module imported

### ISSUE THREAD

**Issue by AlexEales** [rustwasm/wasm-bindgen#1877]
### Describe the Bug

It appears whenever I try to import from a WASm bundle which contains an exported `struct` a `TypeError: WebAssembly.instantiate()` is thrown. I simplified down the struct I was trying to export to just be:

```rust
#[wasm_bindgen]
pub struct SimpleStruct {
    value: i32,
}

#[wasm_bindgen]
impl {
    pub fn new(value: i32) -> SimpleStruct {
        SimpleStruct { value }
    } 
}
```

And I'm still getting the error? Could this be something to do with the WASM module not being generated correctly? It seemed pretty normal when I checked and compared it to the expected output of exporting a struct on this [page](https://rustwasm.github.io/docs/wasm-bindgen/contributing/design/exporting-rust-struct.html). 

I'm using Parcel bundler to create a simple website using WASM, I'm aware of the lack of compatibility between the two out of the box so I am simply recompiling my Rust package when I need to and then pointing the TS files at the generates JS file in the `pkg` directory.

### Steps to Reproduce

1. Copy above code + some arbitrary function exported to WASM
2. Compile with `wasm-pack build`.
3. Import arbitrary function inJS.
4. Serve local JS and observe error.

If applicable, add a link to a test case (as a zip file or link to a repository we can clone).

### Expected Behavior

Importing from the bundle should not error if it contains a struct being exported.

### Actual Behavior

`TypeError: WebAssembly.instantiate()` is thrown regardless of structs' contents.

### Additional Context

Full error message: `Uncaught (in promise) TypeError: WebAssembly.instantiate(): Imports argument must be present and must be an object`

**Comment by AlexEales** [comment]
My `Cargo.toml`:

```toml
[package]
name = "simple"
version = "0.1.0"
authors = ["Alex Eales"]
edition = "2018"

[dependencies]
rand = "0.7"

[dependencies.wasm-bindgen]
version = "0.2.55"

[lib]
crate-type = ["cdylib"]

```

**Comment by Pauan** [comment]
I'm not 100% sure, but this sounds like a bug with Parcel (which doesn't have great wasm support at the moment).

Do you still get the error if you use Webpack instead?

**Comment by AlexEales** [comment]
Thanks for the quick response @Pauan I do not get the error with webpack, I had a feeling it would be a Parcel issue. Do you have any idea what might be causing this so I could relay this to the Parcel team and try and get a fix for this going? :)

**Comment by AlexEales** [comment]
Have found a Parcel plugin which seems to solve the issue, will leave the link here incase anyone else goes down this rabbit hole!

https://github.com/rustwasm/rust-parcel-template

**Comment by Pauan** [comment]
@AlexEales Yup, that's covered here:

https://github.com/parcel-bundler/parcel/issues/647

https://github.com/parcel-bundler/parcel/issues/1325

https://github.com/parcel-bundler/parcel/issues/3485
