### ISSUE TITLE
Using #[wasm_bindgen] on an enumeration in an external crate

### ISSUE THREAD

**Issue by nshcat** [rustwasm/wasm-bindgen#1879]
### Summary
Is it possible to use (or emulate the use of) `#[wasm_bindgen]` on an enumeration that is defined in some external crate?

### Additional Details
Currently, the enumeration is defined in the crate that contains the JS compatibility layer, but I want to refactor my system into two crates, one for the web, and one with completely platform-agnostic code. The enumeration in question belongs to this second crate, so I would need to import it from the actual web crate. How can I apply `#[wasm_bindgen]` to it in this situation? I don't want to use `#[wasm_bindgen]` in my platform-agnostic library crate.

Thanks!

**Comment by alexcrichton** [comment]
Thanks for the report! This is not currently possible, and you'll need to copy in the definition from the external crate or work with integers perhaps and have a custom mapping.
