### ISSUE TITLE
Multithreaded memory allocation

### ISSUE THREAD

**Issue by ConradBrean** [rustwasm/wasm-bindgen#1884]
Am i correct in that memory allocation in raytrace demo (and more generally in multithreaded wasm) compiled with wasm-bindgen is currently broken?

[dlmalloc-rs wasm implementation assumes that it is run single-threaded](https://github.com/alexcrichton/dlmalloc-rs/blob/430815940214d18f575243a1c9c8ba7b1ea794cd/src/wasm.rs#L32), and it's the default memory allocator in wasm at this point. 

Am i missing something? @alexcrichton 

Considering [Lack of atomic.wait on the main thread](https://github.com/WebAssembly/threads/issues/106) it looks like the only way for me to use threads with wasm-bindgen is to manually implement allocator that uses mutexes for global lock, and spinlocks if in main thread?

**Comment by ConradBrean** [comment]
After looking at sys implementation for wasm i found that allocator is actually always [spinlocked](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/wasm/alloc.rs#L59), and should be safe to use. Was a bit misled by the comments inside dlmalloc-rs and [Multithreading Rust and Wasm](https://rustwasm.github.io/2018/10/24/multithreading-rust-and-wasm.html) blogpost from year earlier. Closing.

**Comment by alexcrichton** [comment]
Yes looks like you answered your own question! Multi-threaded memory allocation works with a spinlock today. It's pretty bad. There's a nice long comment in the source though explaining why we chose the bad route for now.
