### ISSUE TITLE
@alexcrichton Yes, exactly.

### ISSUE THREAD

**Issue by justin3687** [rustwasm/wasm-bindgen#1888]
@alexcrichton Yes, exactly.

And the intrinsic would be implemented like this on the JS side (it *has* to be on the JS side, sadly):

```js
function isValidUtf16String(str) {
    var i = 0;
    var len = str.length;

    while (i < len) {
        var char = str.charCodeAt(i);

        ++i;

        // Might be surrogate pair...
        if (char >= 0xD800) {
            // First half of surrogate pair
            if (char <= 0xDBFF) {
                // End of string
                if (i === len) {
                    return false;

                } else {
                    var next = str.charCodeAt(i);

                    // No second half
                    if (next < 0xDC00 || next > 0xDFFF) {
                        return false;
                    }
                }

            // Second half of surrogate pair
            } else if (char <= 0xDFFF) {
                return false;
            }
        }
    }

    return true;
}
```

(I loosely translated it from [the `DOMString` spec](https://heycam.github.io/webidl/#idl-DOMString) by using some tips from [the `TextEncoder` polyfill](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder#Polyfill).)

It looks big, but it minifies quite well, and it should be extremely fast.

_Originally posted by @Pauan in https://github.com/rustwasm/wasm-bindgen/issues/1348#issuecomment-477357145_

**Comment by alexcrichton** [comment]
er sorry I may be missing some context here, @justin3687 can you elaborate on why you opened a separate issue for this?

**Comment by mihaimaruseac** [comment]
This is a spammer account
