### ISSUE TITLE
Problems with RLS integration

### ISSUE THREAD

**Issue by noxabellus** [rustwasm/wasm-bindgen#1890]
When using js-sys in VS Code RLS crashes upon attempting code completion and for web-sys it does not provide type impl information

### Steps to Reproduce

1. Add js-sys/web-sys dependency to bindgen project
2. Go to main file in VS Code
3. Type something like js_sys::JSON:: (or web_sys::Window::) and wait for autocomplete suggestions
4. RLS crashes and/or does not display any information

### Expected Behavior

RLS provides lists of functions within type impls

### Actual Behavior

RLS crashes or does not display information, depending on sub crate

**Comment by alexcrichton** [comment]
Thanks for the report! I'm not sure that this is an issue with this crate though, it sounds like an RLS issue?

**Comment by noxabellus** [comment]
I haven't experienced a crash with RLS before using this crate so I wouldn't say that

**Comment by Pauan** [comment]
@noxabellus If RLS can't handle valid Rust code (and thus is crashing), then that is a bug with RLS.
