### ISSUE TITLE
How to reach a non-CORS HTTP server from WASM?

### ISSUE THREAD

**Issue by andywswan** [rustwasm/wasm-bindgen#1897]
It isn't quite a Rust or even WASM question, but still: is there a Rusty Wasm-bindgeny way to fetch a page from an HTTP server that does not send CORS headers? (Without using external stuff like cors proxy)

I know WASM is completely sandboxed, just thought there is no harm in asking.

**Comment by Pauan** [comment]
Are you trying to load something from your own server, or somebody else's server? What file type are you trying to load?

**Comment by andywswan** [comment]
Just somebody else's API, the response is JSON

**Comment by Pauan** [comment]
Well, in that case they need to enable CORS, otherwise it's impossible to load it. This isn't a limitation with Wasm, it's a limitation with the browser itself, so it won't work with JS either.

**Comment by Pauan** [comment]
(Assuming they *do* enable CORS, you can then use the usual web APIs like [`fetch`](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.Window.html#method.fetch_with_str) from within Wasm, since Wasm has access to *all* of the JS and web APIs, so everything JS can do, Wasm can do as well)

**Comment by alexcrichton** [comment]
Thanks for the report here! As mentioned by @Pauan though this sounds like a web limitation rather than a problem with `wasm-bindgen`, so I'm going to close.
