### ISSUE TITLE
Module not found: Error: Can't resolve '__wbindgen_anyref_xform__'

### ISSUE THREAD

**Issue by chadhietala** [rustwasm/wasm-bindgen#1902]
### Describe the Bug

It seems that the bidgen is referencing a module called `__wbindgen_anyref_xform__` but it does not exist.

### Steps to Reproduce

1. `cd examples/hello_world`
2. `cargo build`
3. `yarn && yarn build`

### Expected Behavior

It should create a successful build.

### Actual Behavior

When building you will get an error like the following:

```
Hash: acb9fb43eda843de7980
Version: webpack 4.41.2
Time: 2470ms
Built at: 12/07/2019 1:23:28 PM
                           Asset       Size  Chunks                         Chunk Names
                      0.index.js    622 KiB       0  [emitted]
                      1.index.js   4.98 KiB       1  [emitted]
ca3b45d28b163df26586.module.wasm   77.1 KiB       1  [emitted] [immutable]
                      index.html  181 bytes          [emitted]
                        index.js   11.2 KiB    main  [emitted]              main
Entrypoint main = index.js
[./index.js] 266 bytes {main} [built]
[./pkg/index.js] 2.54 KiB {1} [built]
[./pkg/index_bg.wasm] 77 KiB {1} [built]
    + 3 hidden modules

ERROR in ./pkg/index_bg.wasm
Module not found: Error: Can't resolve '__wbindgen_anyref_xform__' in '/Users/chietala/Code/wasm-bindgen/examples/hello_world/pkg'
 @ ./pkg/index_bg.wasm
 @ ./pkg/index.js
 @ ./index.js
```

### Additional Context

Below is my active toolchain and targets

```
❯ rustup show
Default host: x86_64-apple-darwin
rustup home:  /Users/chietala/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin
nightly-x86_64-apple-darwin (default)

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-apple-darwin

active toolchain
----------------

nightly-x86_64-apple-darwin (default)
rustc 1.41.0-nightly (ae1b871cc 2019-12-06)
```

**Comment by IsaacLeeWebDev** [comment]
Having the same issue, slightly different steps to reproduce:
1. cd examples/hello_world
(optional 1b: `cargo build`)
2. `npm i`
3. `npm run serve`

Toolchain/targets:
```
isaaclee$ rustup show
Default host: x86_64-apple-darwin

installed toolchains
--------------------

stable-x86_64-apple-darwin
beta-x86_64-apple-darwin
nightly-x86_64-apple-darwin (default)

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-apple-darwin

active toolchain
----------------

nightly-x86_64-apple-darwin (default)
rustc 1.37.0-nightly (d132f544f 2019-06-07)

```

**Comment by alexcrichton** [comment]
Thanks for the report! Unfortunately this is an instance of https://github.com/rustwasm/wasm-bindgen/issues/1227 where you're using a git version of the crate but a crates.io version of the CLI. I'm gonna close this in favor of that issue, but for a quick-fix for now you can copy the examples out of this repository, and they should build just fine!

**Comment by sauravvsonu** [comment]
ERROR in ./index.js
Module not found: Error: Can't resolve 'rust_js_game' in 'C:\Users\SOURAV\rust-js-game\www'
 @ ./index.js 1:0-37 3:0-10
 @ ./bootstrap.js
i ｢wdm｣: Failed to compile.



having same issue
