### ISSUE TITLE
Module not found: Error: Can't resolve 'env'

### ISSUE THREAD

**Issue by wangyiran125** [rustwasm/wasm-bindgen#1907]
### Summary

A clear and concise summary of your question.

Module not found: Error: Can't resolve 'env' in 'D:\project\rust\wasm-pack-template\pkg'

### Additional Details
Provide any additional details here.
when i add it to lib.rs

```
#[wasm_bindgen]
pub fn parseTest() -> String{
    let resp = ureq::get("www.google.com")
         .call();
    let text = resp.into_string().unwrap();
    text
}
```
cargo.toml add
`ureq = { version = "0.11.2", features = ["json"] }
`

**Comment by alexcrichton** [comment]
Thanks for the report! This typically means that there's an unresolved import, for example something like:

```rust
extern {
    fn foo();
}
```

where the default import module is `env`. The `ureq` crate likely doesn't target WebAssembly yet and would need to be updated to support it!

**Comment by i-schuetz** [comment]
Ran across this today and it was indeed because I was using a dependency that doesn't support WASM. Is it easy to improve this error message?

**Comment by sf-cg** [comment]
I too am using ureq and got this error, I couldn't understand it at all - is there anything that can be done for future people beyond hopefully googling the right thing to spot this issue thread?

**Comment by ShayRubach** [comment]
Joining @sf-cg. I have this issue as well, but I have no clue from which crate. I have a working Rust lib that I compiled into wasm and I want to call its API from some JS code. Without a more informative error, I have no idea which one of the dozen crates I have there causes the issue..

**Comment by kalzoo** [comment]
Started a discussion on this issue [here](https://github.com/rustwasm/wasm-bindgen/discussions/3500)

**Comment by kalzoo** [comment]
Solved, thanks to @Liamolucko ! See discussion linked above ☝️
