### ISSUE TITLE
js_namespace = "chrome.tabs" error expected an identifier

### ISSUE THREAD

**Issue by ctaggart** [rustwasm/wasm-bindgen#1911]
I'm trying to map functions from the `chrome.tabs` JavaScript namespace, but when I do:

``` rust
#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(js_namespace = "chrome.tabs")]
    pub fn query(query_info: &JsValue, callback: &dyn Fn(JsValue));
}
```

I get the error:
```
error: expected an identifier
  --> src/chrome_tabs.rs:23:35
   |
23 |     #[wasm_bindgen(js_namespace = "chrome.tabs")]
   |                                   ^^^^^^^^^^^^^
```

May be related code:
https://github.com/rustwasm/wasm-bindgen/blob/df34cf843eca7478e3879562670e52c889e32fdf/crates/backend/src/ast.rs#L72

**Comment by Pauan** [comment]
Yeah, this is covered by https://github.com/rustwasm/wasm-bindgen/issues/951

As a workaround, you can do this:

```rust
#[wasm_bindgen]
extern "C" {
    pub type Tabs;

    #[wasm_bindgen(method)]
    pub fn query(this: &Tabs, query_info: &JsValue, callback: &dyn Fn(JsValue));
}

#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(js_namespace = chrome)]
    pub fn tabs() -> Tabs;
}
```

Now you can use `tabs().query(...)`

**Comment by ctaggart** [comment]
That gave `Uncaught TypeError: chrome.tabs is not a function`

but with static like #951 worked:
``` rust
#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(js_namespace = chrome)]
    static tabs: Tabs;
}
```
Thanks again!

**Comment by Pauan** [comment]
Oops, I forgot to add `getter`, though `static` works as well.
