### ISSUE TITLE
Can't successfully build and serve examples/dom

### ISSUE THREAD

**Issue by vjancik** [rustwasm/wasm-bindgen#1912]
### Describe the Bug
I tried to build the `dom` example from this repository.
I checked out the repository, ran `npm install` and `npm run serve`.
The `.wasm` file built successfully, then when being (apparently) loaded by `webpack-dev-server`, I get multiple errors that are the same
```
ERROR in ./pkg/index_bg.wasm
Module not found: Error: Can't resolve '__wbindgen_anyref_xform__' in '/home/vix/Code/Repositories/wasm-bindgen/examples/dom/pkg'
 @ ./pkg/index_bg.wasm
 @ ./pkg/index.js
 @ ./index.js
```

### Additional Context

I'm on rust `stable` tool-chain.
I also tried bumping down the `wasm-bindgen` version from `0.2.55` to `0.2.54` as it seems `anyref` is mentioned in the release notes. Didn't help.
Updating `web-sys` from `0.3.4` to `0.3.32` or bumping `wasm-pack-plugin` from `1.0.1` to `1.1.0` doesn't seem to make a difference.

**Comment by vjancik** [comment]
After I copied out the example out of the `wasm-bindgen` project tree and rebuilt it, it built and `serve`d successfully.
I can only assume the error is caused by some parent recursive search of `cargo` when building that links against some wrong dependency from the parent workspace?

That's a blind guess though.

**Comment by vjancik** [comment]
Additionally, `npm build` whether with `mode: 'development'` or `mode: 'production'` bundles `500kB` large `lodash` into the `pkg` to be loaded as a `0.index.js` out of the box (not among dependencies).
And the line `<script type="text/javascript" src="index.js"></script>` is emitted 6 times into the built `pkg/index.html`...

**Comment by alexcrichton** [comment]
Thanks for the report! For more information on how to fix this see [this comment](https://github.com/rustwasm/wasm-bindgen/issues/1902#issuecomment-563355006)

**Comment by vjancik** [comment]
Thank you! The `lodash` `500k` dependency was resolved by removing `text-encoding`.
