### ISSUE TITLE
Can wasm-bindgen use as a target spesific dependency?

### ISSUE THREAD

**Issue by huangjj27** [rustwasm/wasm-bindgen#1919]
### Summary
I have some functionality that differs on different target, and I expect that `wasm-bindgen` should be `wasm32-unknown-unknown` target specific dependency, but if I add `#[cfg(target="wasm32-unknown-unknown")]`, all functionality don't work. Can` wasm-bindgen` be used as a target spesific dependency?

### Additional Details
Codes here:
```
// wasm.rs
#![cfg(target="wasm32-unknown-unknown")]

#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(js_namespace=console)]
    fn debug(text: &str);
}
```
```
// main.rs
mod wasm;

#[cfg(target="wasm32-unknown-unknown")]
use wasm_bindgen::prelude::*;
#[cfg(target="wasm32-unknown-unknown")]
use wasm::*;

fn main() {
    #[cfg(not(target="wasm32-unknown-unknown"))]
    println!("Non-wasm target");

    #[cfg(target="wasm32-unknown-unknown")]
    wasm::debug("wasm32-target");
}

#[cfg(target="wasm32-unknown-unknown")]
#[wasm_bindgen(start)] 
pub fn start() {
    main();
}
```
```
# Cargo.toml
[package]
name = "my_wasm_bindgen_log"
version = "0.1.0"
authors = ["huangjj27 <349373001@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "*"
# wasm-bindgen = "*"

[target.wasm32-unknown-unknown.dependencies]
wasm-bindgen = "*"
```

the code are compiled:
```
cargo build --target=wasm32-unknown-unknown
wasm-bindgen ./target/wasm32-unknown-unknown/debug/my_wasm_bindgen_log.wasm --out-dir=wasm --web
```

then, in `./wasm` directory, add this `index.html`, and open it on a browser:
```
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8"/>
    <title>Tour - Iced</title>
  </head>
  <body>
    <script type="module">
      import init from "./my_wasm_bindgen_log.js";

      init();
    </script>
  </body>
</html>
```

then you get _nothing in console(F12)_. But after removing all `#[cfg(target="wasm32-unknown-unknown")]` and uncommenting the universal denpendency, the code works again.

**Comment by alexcrichton** [comment]
Thanks for the report! `#[cfg(target)]` isn't a thing, though, and you probably want to use `#[cfg(target_arch = "wasm32")]`

**Comment by huangjj27** [comment]
> `#[cfg(target)]` isn't a thing,

then here raise another question: if `#[cfg(target)]` isn't a thing, why cargo doesn't complain about it? It's the passed compilation that makes my believe the code should work.

**Comment by alexcrichton** [comment]
The compiler doesn't warn about unknown `#[cfg]` directives because the purpose of the `#[cfg]` directive is to silently go away if it's unknown.

**Comment by huangjj27** [comment]
So, According to [reference](https://doc.rust-lang.org/reference/conditional-compilation.html), I should combine target_arch and targer_vendor.
