### ISSUE TITLE
globalThis.globalThis undefined

### ISSUE THREAD

**Issue by greenpdx** [rustwasm/wasm-bindgen#1932]
### Summary
Created a Vue project with wasm-pack. I copied the dependencies into Cargo.toml and package.json.
A clear and concise summary of your question.

 var ret = globalThis.globalThis; is undefined in ES-lint

I have tried adding sj_sys::global.  I even put a  global section in to package.json. 
I think this is a lint problem. because it run fine in the browser.

Is there a work around or fix for this undefined?
 var ret = globalThis.globalThis;

### Additional Details

Provide any additional details here.
[INFO]: :-) Done in 2.64s
[INFO]: :-) Your wasm pkg is ready to publish at ./pkg.
✅  Your crate has been correctly compiled

98% after emitting CopyPlugin

 ERROR  Failed to compile with 1 errors                               1:55:20 PM

 error  in ./pkg/index.js

Module Error (from ./node_modules/eslint-loader/index.js):
error: 'globalThis' is not defined (no-undef) at pkg/index.js:291:23:
  289 |     try {
  290 |         try {
> 291 |             var ret = globalThis.globalThis;
      |                       ^
  292 |             return addHeapObject(ret);
  293 |         } catch (e) {
  294 |             handleError(e)

1 error found.

 @ ./src/main.js 16:14-39
 @ multi (webpack)-dev-server/client?https://10.0.42.179:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by alexcrichton** [comment]
Thanks for the report! I believe though that since this is just a lint error you'll want to disable linting the generated file here. The error is caught in the JS code itself.
