### ISSUE TITLE
Passing an instance of a struct as an argument to an imported javascript function results in the wrong type

### ISSUE THREAD

**Issue by gnodarse** [rustwasm/wasm-bindgen#1937]
Passing an instance of a struct from Rust code into an imported javascript function results in javascript interpreting the wrong type. This is in contrast to returning an instance of a struct, where the type is interpreted correctly.

### In Rust:

```
extern { 
	fn handleInstruction(instruction: Instruction);
}

#[wasm_bindgen]
pub struct Instruction {
	pub x: u32,
	pub y: u32
}

#[wasm_bindgen]
pub fn pass_instruction() {
	let tmp = Instruction {
		x: 0,
		y: 0
	};
	
	unsafe { handleInstruction( tmp );}
}

#[wasm_bindgen]
pub fn return_instruction() -> Instruction {
	Instruction {
		x: 0,
		y: 0
	}
}
```

### In JavaScript:
```
import * as wasm from 'some_file';

export function handleInstruction(instruction) { 
	console.log(typeof instruction);
	console.log(typeof wasm.return_instruction());
}

wasm.pass_instruction();
```

### Expected Behavior

`console.log(typeof instruction);` and `console.log(typeof wasm.return_instruction());` should print the same type.

### Actual Behavior

`console.log(typeof instruction);` prints "number"
`console.log(typeof wasm.return_instruction());` prints "object"

**Comment by alexcrichton** [comment]
Thanks for the report! The bug here though is you need to use `#[wasm_bindgen]` on the imported function as well.
