### ISSUE TITLE
Provide js_namespace argument on static declarations

### ISSUE THREAD

**Issue by csharad** [rustwasm/wasm-bindgen#194]
When accessing static attributes of a js api, we are only allowed to use it the following way.
```
type window;
static window: window;
type Document;

#[wasm_bindgen(method, getter, structural)]
fn document(this: &window) -> Document;
```
But to create a cleaner api allowing something like `window::document` would require `js_namespace` argument be allowed on static declarations.

```
type window;
type Document;

#[wasm_bindgen(js_namespace = window)]
static document: Document;
```

**Comment by alexcrichton** [comment]
Hm so it looks like `js_namespace` works today? Are you thinking that the generated code should generate a module called `window` though?

**Comment by csharad** [comment]
@alexcrichton No, putting `js_namespace` on static does not work.

For the second question, yeah, I would love if a module was created.
Why? Its comes down to the choice of syntax. `window.document()` vs `window::document`.

**Comment by alexcrichton** [comment]
Hm can you gist a full example of what isn't working for you? The simple examples I tried locally all seemed to work :(

**Comment by csharad** [comment]
I am using version 0.2.8.
```
#[wasm_bindgen]
extern {
    pub type window;
    pub type Document;

    #[wasm_bindgen(js_namespace = window)]
    static document: Document;
}
```

Compiler error: 
```
error: expected one of `const`, `crate`, `default`, `extern`, `fn`, `pub`, `type`, or `unsafe`, found `static`
 --> src/lib.rs:8:1
  |
8 | #[wasm_bindgen]
  | ^^^^^^^^^^^^^^^ expected one of 8 possible tokens here

error: expected one of `const`, `crate`, `default`, `extern`, `fn`, `pub`, `type`, `unsafe`, or `}`, found `;`
 --> src/lib.rs:8:1
  |
8 | #[wasm_bindgen]
  | ^^^^^^^^^^^^^^^ expected one of 9 possible tokens here

```

**Comment by alexcrichton** [comment]
Aha, there we go!
