### ISSUE TITLE
Exports bloat

### ISSUE THREAD

**Issue by FreeMasen** [rustwasm/wasm-bindgen#195]
I just bumped my version of `wasm-bindgen` and `wasm-bindgen-cli` from `0.2.5` to `0.2.8` and re-compiled a library. The result included an additional 125 lines of jsthat do not get used by any of the originally exported functions.

Here is a gist with the original rust source and the two output files.

https://gist.github.com/FreeMasen/64ba95c37381ef746d049beee4d5f40f

Starting on line 113 of the new bindings through the end of the file can be removed entirely from the file, though keys with matching names need to exist in the `importObj`.  Would it be possible to revert the list of exports to only require `__wbindgen_*` functions that are used?

**Comment by alexcrichton** [comment]
To confirm, are you compiling with LTO?

**Comment by FreeMasen** [comment]
I have compiled in both debug and release mode and get the same result. I have not explicitly enabled any other flags. Now that you bring that up though, I might be having a nightly version issue.

**Comment by alexcrichton** [comment]
Ah ok, can you try turning on LTO? It's expected that these are left in when not compiling with LTO due to upstream bugs.

**Comment by FreeMasen** [comment]
That fixed it, thanks!
