### ISSUE TITLE
[feature request] run `rustfmt` on web-sys source when generating documentation

### ISSUE THREAD

**Issue by derekdreery** [rustwasm/wasm-bindgen#1953]
This would mean that the user can click through and see what is going on in the source.

**Comment by alexcrichton** [comment]
This is actually [already done](https://github.com/rustwasm/wasm-bindgen/blob/62fee13a46b54896310db0395a634aefe3694845/crates/web-sys/build.rs#L92-L98), so if it's not happening then `rustfmt` likely isn't configured on the local system.

**Comment by derekdreery** [comment]
oops thanks

**Comment by derekdreery** [comment]
I was thinking specifically in [the online docs](https://rustwasm.github.io/wasm-bindgen/api/src/web_sys/home/vsts/work/1/s/target/debug/build/web-sys-7bc9948bf771e74b/out/bindings.rs.html#5)

**Comment by alexcrichton** [comment]
I think this is perhaps an issue for docs.rs in that case which may not have rustfmt installed by default?

**Comment by derekdreery** [comment]
The docs are on rustwasm.github.io. I'll look into how to run rustfmt when generating them.

**Comment by derekdreery** [comment]
It looks like the doc builder specifically disables rustfmt (https://github.com/rustwasm/wasm-bindgen/blob/master/azure-pipelines.yml#L326).

**Comment by alexcrichton** [comment]
Oh sorry I should have clicked through to the link... in any case thanks for investigating!
