### ISSUE TITLE
web_sys Element method clone_node_with_deep can return Element

### ISSUE THREAD

**Issue by botika** [rustwasm/wasm-bindgen#1955]
I need to clone `Element`s in deep to be able to change attributes.

The current methods, `clone_node` and `clone_node_with_deep` does not follow the same behavior as its alternative in javascript that returns an `Element`. 

The only way I've found to cast `Node` to `Element` it's, when it have parent, `parent_elem` and `childrens` or `first_element_child`. 

My questions:

- `Element::clone_node_with_deep` can return an `Element`?
- Some way to cast `Node` to `Element`? will implement TryFrom? 

Thanks

**Comment by Pauan** [comment]
You can use [`JsCast`](https://docs.rs/wasm-bindgen/0.2.58/wasm_bindgen/trait.JsCast.html) to do type conversions:

```rust
node.clone_node_with_deep(true).unwrap().dyn_into::<Element>().unwrap()
```

Or if you know for sure that it's an `Element`, you can do an unchecked cast, which has zero runtime cost, because it doesn't do any type checking:

```rust
node.clone_node_with_deep(true).unwrap().unchecked_into::<Element>()
```
