### ISSUE TITLE
Transpilation of imported non-Browser JS

### ISSUE THREAD

**Issue by Tarnadas** [rustwasm/wasm-bindgen#1974]
### Motivation

I stumbled across an issue when trying to import a function from JS to WASM. I used the [proposed solution in the book](https://rustwasm.github.io/docs/wasm-bindgen/examples/import-js.html). However this uses ES import/export syntax which cannot be used in Node.

Since I passed `--target nodejs` to `wasm-bindgen`, I though this would be handled as well, since the JS glue code also has commonjs syntax. I am aware that transpilation is not the same as code generation, so I assume this is rather a feature request.

### Proposed Solution

The [swc](https://github.com/swc-project/swc) project offers a Rust solution. There are more mature solutions like Babel but swc is catching up. It also has a [Rust API](https://github.com/swc-project/swc/blob/master/examples/usage.rs). However I cannot seem to find it on crates.io. I found an [issue](https://github.com/swc-project/swc/issues/431), which led to the Rust API, but no way other than using a git dependency to use it.

In a Node project, swc would automatically scan for a `.swcrc` file to parse options. This technique could also be used with the Rust API when used with wasm-bindgen.

Swc is also capable to minify JS code. Eventually this could be used for generated JS glue code in the future.

Since this feature would pull in a new dependency, I assume it would be best to be behind a feature flag?

### Alternatives

I think any no-Rust solution wouldn't make any sense. Otherwise Babel is also a great option.

**Comment by alexcrichton** [comment]
Thanks for the report! I think we're probably not going to take a dependency on swc for now, sort of like how we don't want to take a dependency on webpack. I'd recommend the "bundler" target for compiling to different sorts of JS, which should allow projects like webpack/swc to take over all the JS compilation steps.
