### ISSUE TITLE
the trait `wasm_bindgen::convert::FromWasmAbi` is not implemented for `char`

### ISSUE THREAD

**Issue by kimtuck** [rustwasm/wasm-bindgen#198]
```
#[derive(Debug)]
#[wasm_bindgen]
pub struct Counter {
    key: char,
    count: i32
}
#[wasm_bindgen]
impl Counter {
    pub fn new(key: char, count: i32) -> Counter {
        Counter { key: key, count: count }
    }
}
```

Yields the message the trait `wasm_bindgen::convert::FromWasmAbi` is not implemented for `char`

**Comment by alexcrichton** [comment]
Ah yes excellent point! I'm not sure though, what would the best translation for a `char` be in JS? A single-character string?

**Comment by FreeMasen** [comment]
Could it be translated as a u16 and then converted on the JS side via `String.fromCharCode`?

**Comment by FreeMasen** [comment]
Or even the `u32` paired with `String.fromCodePoint`

**Comment by alexcrichton** [comment]
@FreeMasen er well the Rust side of things definitely can use `char`, so it's just what type this maps to in JS. JS doesn't really have a `char` so the closes thing seems to be a string with only one code point I guess?

**Comment by FreeMasen** [comment]
Sorry, i think I misunderstood. 

On the JS side think it would be a `string`. I was alluding to how the `impl FromWasmAbi for char` might work. 

My thought was that `into_abi` could either be convert the `char` to a `string` and use the existing helper functions (`passStringToWasm`, `getStringFromWasm`) or cast the `char` to a `u32` and then implement a new helper function that uses the `fromCodePoint` static method and `codePointAt(0)` on the `String` type.

I still may be misunderstanding, sorry if that doesn't clear anything up.

**Comment by Pauan** [comment]
@alexcrichton Just to be clear, a single code point might correspond to two JS characters:

```js
"\u{1F4A9}".length  // returns 2
```

This is because strings in JS are UTF-16 encoded, and JS does not attempt to hide that fact.

**Comment by alexcrichton** [comment]
Ok I think it seems reasonable to expect that `char` should work and realistically the only equivalent in JS is a `string`. This won't protect against passing strings of more than one code point, but I don't think there's much we can do about that!

Seems good to me to implement this, and a PR would be most welcome!

**Comment by alexcrichton** [comment]
Implemented in https://github.com/rustwasm/wasm-bindgen/pull/206
