### ISSUE TITLE
What is the state of debugging?

### ISSUE THREAD

**Issue by solomatov** [rustwasm/wasm-bindgen#1981]
### Summary
Chrome added support for DWARF based debugging information: https://twitter.com/ChromeDevTools/status/1192803818024710145 Unfortunately, they also mentioned that wasm-bindgen doesn't support updating debug info after transformation.

So my question is:
- How hard is it to add support for updating debug information?
- Do you have it on your roadmap, and if so, when do you plan to implement it?

**Comment by alexcrichton** [comment]
I commented [here as well](https://github.com/rustwasm/wasm-bindgen/issues/1289#issuecomment-579116545), but the gist of it is that DWARF isn't supported yet because we need to implement a DWARF transform inside of the `walrus` library (cc'ing @yurydelendik here as well)

**Comment by yurydelendik** [comment]
> How hard is it to add support for updating debug information?

Not trivial but possible, I started the https://github.com/yurydelendik/wtmaps-utils project to help with that.

> Do you have it on your roadmap, and if so, when do you plan to implement it?

There are no specific schedule/date set for this feature.

**Comment by solomatov** [comment]
@alexcrichton @yurydelendik Thank you for the information!

**Comment by ortem** [comment]
@alexcrichton @yurydelendik Any progress on this? AFAIU DWARF support is implemented in Binaryen https://github.com/WebAssembly/binaryen/issues/2400

**Comment by mmgeorge** [comment]
Also curious to know what the status of this is -- seems like this basically depends on https://github.com/rustwasm/walrus/issues/67?

**Comment by alexcrichton** [comment]
Unfortunately there is no status update on this, it's still not implemented. This would still largely all happen in the `walrus` crate, but I don't think work has been done to continue on updating DWARF

**Comment by mitsuhiko** [comment]
I think this issue should be reopened until resolved. I just wanted to file an issue for it. [We](https://sentry.io) are now about to start supporting DWARF for crash reporting and since so many projects that asked for WASM support are also using wasm-bindgen I would expect more people will ask for DWARF support.

**Comment by alexcrichton** [comment]
This issue is more of a question than a tracker, but @mitsuhiko would you be up to open a new issue dedicated to "support dwarf in wasm-bindgen"?

**Comment by mitsuhiko** [comment]
I opened a new issue for it in #2389.
