### ISSUE TITLE
web_sys::window() in Web Worker not returning None but throwing an error

### ISSUE THREAD

**Issue by j-devel** [rustwasm/wasm-bindgen#1982]
### Describe the Bug

Calling [`web_sys::window()`](https://rustwasm.github.io/wasm-bindgen/api/web_sys/fn.window.html) in a Web Worker throws an unexpected runtime error.

In this case, according to its signature (`pub fn window() -> Option<Window>`), I expect it to return `None` instead.

References:
- [without-a-bundler-no-modules-worker](https://github.com/j-devel/wasm-bindgen/tree/issue-window/examples/without-a-bundler-no-modules-worker) (a custom example)
- [index.html](https://github.com/j-devel/wasm-bindgen/blob/issue-window/examples/without-a-bundler-no-modules-worker/index.html) and [lib.rs](https://github.com/j-devel/wasm-bindgen/blob/issue-window/examples/without-a-bundler-no-modules-worker/src/lib.rs) (relevant code)

### Steps to Reproduce

1. Build the custom example:
```
$ git clone -b issue-window https://github.com/j-devel/wasm-bindgen
$ cd wasm-bindgen/examples/without-a-bundler-no-modules-worker/
$ wasm-pack build --target no-modules
$ python -m SimpleHTTPServer
Serving HTTP on 0.0.0.0 port 8000 ...
```
2. Open *http://localhost:8000/* in browser and see the Developer Console
3. See error
![wasm-bindgen-issue-window](https://user-images.githubusercontent.com/38098238/73239430-a70df680-41ce-11ea-9c72-70ee62637098.png)

### Expected Behavior

`web_sys::window()` returns `None`. No runtime errors reported in the Developer Console .

### Actual Behavior

Get an Uncaught ReferenceError as in the above screenshot.

### Additional Context

n/a

**Comment by Pauan** [comment]
This is a duplicate of https://github.com/rustwasm/wasm-bindgen/issues/1046

We've temporarily fixed this in [gloo](https://github.com/rustwasm/gloo/blob/f9b1727481125f1f2e3d052137f92d1e6de9af93/crates/timers/src/callback.rs#L19-L38), but we should think about a better more long-term solution for this.

**Comment by j-devel** [comment]
Woops, I just learnd this is actually a well-known issue; and thanks for the pointers to the existing pragmatic approaches that are basically relying on `unchecked_into()`.

Skimming through the previous discussions in the links, I do share the same view that a more fundamental fix would be for us to do something about `instanceof`.

The root problem has turned out to be not only about `web_sys::window()`. I am working on some `global`-agnostic code where I just want to perform some simple checks like
```
js_sys::global().has_type::<web_sys::Window>()
js_sys::global().is_instance_of::<web_sys::Window>()
js_sys::global().has_type::<web_sys::WorkerGlobalScope>()
js_sys::global().is_instance_of::<web_sys::WorkerGlobalScope>()
```
and they all are failing with similar errors thrown when in a 'wrong' context. With the sought-after fundamental fix in mind, I'd like to open a separate issue when I come up with something worth sharing.

And for now, I'm closing this particular issue on resolving `global` to `Window`.
