### ISSUE TITLE
#[wasm_bindgen] on a struct with a String?

### ISSUE THREAD

**Issue by locka99** [rustwasm/wasm-bindgen#1985]
### Summary

If I have a struct containing a String, or an Option to a String, is there any way I can expose it to Javascript? 

### Additional Details

This simple sample with `#[wasm_bindgen]` generates an error.

```
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub struct Test {
   pub value: Option<String>
}
```

Compiler error.

```
  |
3 | #[wasm_bindgen]
  | ---------------
  | |
  | required by this bound in `__wbg_get_test_value::assert_copy`
4 | pub struct Test {
5 |    pub value: Option<String>
  |               ^^^^^^^^^^^^^^ the trait `std::marker::Copy` is not implemented for `std::string::String`
  |
  = note: required because of the requirements on the impl of `std::marker::Copy` for `std::option::Option<std::string::String>`
```

**Comment by alexcrichton** [comment]
Thanks for the report! Public fields are automatically infered to generate accessors in JS but they're required to be `Copy`. [You can use `#[wasm_bindgen(skip)]`](https://rustwasm.github.io/wasm-bindgen/reference/attributes/on-rust-exports/skip.html) to avoid exporting this field or you can make [getters and setters](https://rustwasm.github.io/wasm-bindgen/reference/attributes/on-rust-exports/getter-and-setter.html) to expose the field in JS.

**Comment by Niedzwiedzw** [comment]
@alexcrichton  what if it's a field of a larger struct? will that work? I'm trying to pass a config in form of a pretty complex json object (nested key-value jsons with strings as values). What'd the approach be?

**Comment by alexcrichton** [comment]
Hm I'm not sure this issue is really affected by the size of the struct? I'm not entirely sure what your question is, sorry. Could you open a new issue with some more clarified information?

**Comment by trevyn** [comment]
xref: https://github.com/rustwasm/wasm-bindgen/issues/1775
