### ISSUE TITLE
Support optional fields in struct reflect in typescript

### ISSUE THREAD

**Issue by clearloop** [rustwasm/wasm-bindgen#1988]
### Motivation

Support optional fields in struct reflect in typescript, for example:

```rust
#[wasn_bindgen]
pub struct Ping {
    pong: Option<bool>,
}
```

in `.d.ts`

```ts
export class Ping {
    pong?: bool;
}
```

### Proposed Solution

Struct generation in `wasm_bindgen` separate fields into `getters` and `setters`, and the `ret_ty` for `getter` or `args` for `setter` which decide the final field type out are embedded in `JsBuilder`, we can't checkout if some fields' types are optional, but...optional fields generate some special docs like `@returns{{{}}}` and `@params{{{}}}` we can trace.

**If it is appropriate to render fields' types with checking if its doc contains `.. | undefined` ?**

For example, we can change this line

https://github.com/rustwasm/wasm-bindgen/blob/f507a2a5ff2fa84d3197909a4b6f095e90ee4b98/crates/cli-support/src/js/mod.rs#L3070

```rust
if docs.contains("undefined") {
    *ty = "?".to_string() + ret_ty
} else {
    *ty = ret_ty.to_string()
}
```

and this line 

https://github.com/rustwasm/wasm-bindgen/blob/f507a2a5ff2fa84d3197909a4b6f095e90ee4b98/crates/cli-support/src/js/mod.rs#L703

```rust
if &ty[0..1] == "?" {
    ts_dst.push_str("?: ");
    ts_dst.push_str(&ty[1..]);
} else {
    ts_dst.push_str(": ");
    ts_dst.push_str(&ty);
}
```

### Alternatives

I think the solution above is quite a mess, but I can't figure out a better one.

**Comment by Pauan** [comment]
I like the idea of generating optional fields... however, I would suggest that whatever tool you are using *should* work with `| undefined`, because from JS's perspective there isn't much difference, and many TypeScript programs will use `| undefined`.

**Comment by clearloop** [comment]
The `| undefined` checking just applies to `setter` and `getter` in `.d.ts`,  if this solution can make a pr, I'd like to do it, or any other way can add optional fields definition to Typescript...really need this.

btw, @Pauan, would you mind to have a look at #1986, I just wrote a pr about `#[wasm_bindgen(plain_object)]` yesterday.

**Comment by alexcrichton** [comment]
Seems like a reasonable feature to me to support as well! A PR would be most welcome to implement this
