### ISSUE TITLE
wasm-bindgen-test error on Windows

### ISSUE THREAD

**Issue by yoshuawuyts** [rustwasm/wasm-bindgen#1989]
### Describe the Bug

wasm-bindgen-test seems to have trouble executing on windows, causing the following error:

```txt
    Finished test [unoptimized + debuginfo] target(s) in 4.22s
     Running target\wasm32-unknown-unknown\debug\deps\coast-4a3465acb4c77647.wasm
error: could not execute process `C:\Users\yoshu\Code\coast\target\wasm32-unknown-unknown\debug\deps\coast-4a3465acb4c77647.wasm` (never executed)

Caused by:
  %1 is not a valid Win32 application. (os error 193)
PS C:\Users\yoshu\Code\coast> 
```

### Steps to Reproduce

With the following code:
```rust
#![cfg(target_arch = "wasm32")]

wasm_bindgen_test::wasm_bindgen_test_configure!(run_in_browser);

use futures_channel::oneshot;
use wasm_bindgen::prelude::*;
use wasm_bindgen_futures::{future_to_promise, spawn_local, JsFuture};
use wasm_bindgen_test::*;

#[wasm_bindgen_test]
async fn promise_resolve_is_ok_future() {
    let p = js_sys::Promise::resolve(&JsValue::from(42));
    let x = JsFuture::from(p).await.unwrap();
    assert_eq!(x, 42);
}
```
on Windows PowerShell do:
```txt
cargo test --target wasm32-unknown-unknown
```

### Additional Context

I'm unsure where the error originates. The error was triggered by following the instructions on a regular Windows 10 install.

**Comment by alexcrichton** [comment]
Thanks for the report! This is expected though in that `wasm-bindgen-test` needs manual configuration to get hooked into the right place. Notably you'll need to configure `CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUNNER=wasm-bindgen-test`. That typically happens with `wasm-pack test` by default, but if you're running manually you'll need to make sure `wasm-bindgen-test` is hooked in somehow.
