### ISSUE TITLE
Support skip attribute for enum

### ISSUE THREAD

**Issue by clearloop** [rustwasm/wasm-bindgen#1991]
### Motivation

Convert Rust `enum` to javascript completly.

### Proposed Solution

Check `skip` attribute while macro paring `enum`

```rust
#[wasm_bindgen]
pub enum Colors {
    #[wasm_bindgen(skip)]
    Rgba(i16, i16, i16, f64),
    Red
}

#[wasm_bindgen]
impl Colors {
    #[wasm_bindgen(js_name = "Rgba")]
    pub fn rgba(r: i16, g: i16, b: i16, a: f64) -> Colors {
        Colors::Rgba(r, g, b, a)
    }
}
```

**Comment by alexcrichton** [comment]
Thanks for the report! I'm not sure I completely understand, though. How would we represent the `Rgba` variant in JS?

**Comment by clearloop** [comment]
oops,  `completely` in my words actually **focus on the usage of the exported pkg**, for example, the ideal way to use enums with inner value is like this:

```typescript
import { Colors } from "../pkg";

//  a red color 
const red: Colors = Colors.Red;

// a RGBA color
const rgba: Colors = Colors.Rgba(255, 255, 255, 255);
```

It seems like we exported the whole enum without `skip`, this is what my `completely` means...

**Comment by alexcrichton** [comment]
Hm ok, it seems perhaps plausible but I'm still not sure how the values would be read in JS. In general I think this proposal would need to be fleshed out more before it gets a PR, perhaps even trying to write up some documentation for the feature beforehand?

**Comment by clearloop** [comment]
Close this issue now, I'll reopen this when I fix my other two `issues` / `pr` or figure out some really reasonable explanation.
