### ISSUE TITLE
how to transfer a buffer from node to rust vec<u8>

### ISSUE THREAD

**Issue by madiazp** [rustwasm/wasm-bindgen#1993]
Hello everyone,
I am trying to open a file in node using fs.readfile() and then I pass the buffer result to rust, the problem I'm having is that i am trying to deserialize the value to vec <u8> and it fails with an error:  `invalid type map expected a sequence`. i am doing it like this because is not possible to open files in wasm.
idk if there is a better way to do this, if there is please let me know.

here is an snipett of what i am doing.
*lib.rst*
```
#[wasm_bindgen]
pub fn computation(p: JsValue){
  let out: Vec<u8> = p.into_serde().unwrap();
 }
```
thanks in advance.

**Comment by Pauan** [comment]
@madiazp I recommend doing something like this:

```rust
use js_sys::{ArrayBuffer, Uint8Array};

#[wasm_bindgen]
extern "C" {
    type Buffer;

    #[wasm_bindgen(method, getter)]
    fn buffer(this: &Buffer) -> ArrayBuffer;
}

#[wasm_bindgen]
pub fn computation(buffer: &Buffer) {
    let out: Vec<u8> = Uint8Array::new(&buffer.buffer()).to_vec();

    // ...
}
```

This will be very fast, because it only has to copy the buffer once.

**Comment by madiazp** [comment]
thanks a lot, will try it!

**Comment by domoritz** [comment]
I tried the approach in https://github.com/rustwasm/wasm-bindgen/issues/1993#issuecomment-583614609 and it was actually slower for me (at least in node) compared to a function that expects an `&[u8]` or `Vec<u8>`. Has wasm-bindgen implemented optimizations for these cases in the meantime?
