### ISSUE TITLE
LinkError: import object field '__wbindgen_closure_wrapper214' is not a Function

### ISSUE THREAD

**Issue by s3bk** [rustwasm/wasm-bindgen#1999]
### Describe the Bug
The following message appeared in my logs:
`LinkError: import object field '__wbindgen_closure_wrapper214' is not a Function`

What I suspect caused it (as it didn't appear before adding this):
```rust
    #[cfg(target_arch = "wasm32")]
    fn init(&mut self, emit: impl Fn(Self::Event) + 'static) {
        use js_sys::{Uint8Array, Function};
        use wasm_bindgen::{JsCast};

        #[wasm_bindgen]
        extern {
            fn set_ws_callback(cb: &Function);
        }
        self.document.set_site_id(SiteId(2));
        let closure = Closure::wrap(Box::new(move |data: Uint8Array| {
            match bincode::deserialize(&data.to_vec()) {
                Ok(val) => emit(val),
                Err(_) => {}
            }
        }) as Box<Fn(Uint8Array)>);
        set_ws_callback(closure.as_ref().unchecked_ref());
        closure.forget();
    }
```

### Steps to Reproduce

No idea. It disappeared after changing the argument type of the closure to `i32` and back.
A cargo clean did not fix it.

Compiled with `wasm-pack build -t no-modules --release` (0.8.1).
Wasm-bindgen 0.2.58

**Comment by alexcrichton** [comment]
Thanks for the report! Could you be sure though that all the code necessary to reproduce this is in a standalone example? Otherwise this is going to be difficult to reproduce!

**Comment by s3bk** [comment]
No I can't. I can't even reproduce in the original code.

**Comment by s3bk** [comment]
I did notice something recently tho… it might be that the browser used a cached JS file instead of the one that actually was correct.

**Comment by alexcrichton** [comment]
Ah ok, in that case I'm going to close this, but feel free to reopen/resubmit if this crops up again!

**Comment by jocutajar** [comment]
Ahoj, I can confirm, this is a cache issue. However, there is a strange behavior of the compiler that produces different-incompatible `.js` files:

![Image](https://github.com/user-attachments/assets/fab66b6e-110c-45f0-8d14-1003b5d78e3e)

<s>Is there some ready to use cache busting mechanism to avoid this issue where on rebuild a cache renders the `.js` file incompatible with the `.wasm`?</s>

This is no longer an issue after upgrading npm and node:
```
$ node --version
v22.17.0
$ npm --version
10.9.2
```
