### ISSUE TITLE
expected lifetime parameter compile error on annotation

### ISSUE THREAD

**Issue by mbalex99** [rustwasm/wasm-bindgen#200]
I'm very sorry as I'm learning rust but this struct will not compile:

```rust
extern crate wasm_bindgen;
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub struct Store<'a> {
    pub name: &'a str,
}
```

```
error[E0106]: missing lifetime specifier
 --> src/store.rs:6:1
  |
6 | #[wasm_bindgen]
  | ^^^^^^^^^^^^^^^ expected lifetime parameter

error[E0261]: use of undeclared lifetime name `'a`
 --> src/store.rs:6:1
  |
6 | #[wasm_bindgen]
  | ^^^^^^^^^^^^^^^ undeclared lifetime
```

And it only seems to happen when I add the #[wasm_bindgen]. How do I specify a lifetime parameter to the annotation?

**Comment by alexcrichton** [comment]
Oh dear, now that's a bad error!

Unfortunately lifetime parameters aren't supported right now, so this should actually be an error but there should certainly be a better error message
