### ISSUE TITLE
`WebSocket.send_with_u8_array` should accept an immutable byte slice

### ISSUE THREAD

**Issue by chinedufn** [rustwasm/wasm-bindgen#2014]
Currently requires `&mut [u8]`

https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.WebSocket.html#method.send_with_u8_array

**Comment by alexcrichton** [comment]
Sounds good to fix! I think we'll just need to [update our whitelist](https://github.com/rustwasm/wasm-bindgen/blob/fb51d9036f41f6a909854f194bf9132940e37f13/crates/webidl/src/lib.rs#L207-L249)

**Comment by chinedufn** [comment]
Thanks!
