### ISSUE TITLE
Skip unnecessary dependencies when building a single binary of cli

### ISSUE THREAD

**Issue by ibaryshnikov** [rustwasm/wasm-bindgen#2020]
There are three binaries in `crates/cli`: `wasm-bindgen`, `wasm-bindgen-test-runner`, `wasm2es6js`
In case of building only one binary, the dependencies for others are also compiled.
For example, building only `wasm-bindgen` compiles dependencies for `wasm-bindgen-test-runner`. Is there a way to skip unnecessary dependencies to reduce build times?
```bash
cd crates/cli
cargo install -f --path . --bin wasm-bindgen
```
With `rouille` in `Cargo.toml` it compiles 184 dependencies and takes 1m 52s.
If we comment the line with `rouille` in `Cargo.toml`, the same command compiles 120 dependencies and takes 1m 35s.

**Comment by alexcrichton** [comment]
Unfortunately I don't think there's really anything we can do about this. Cargo doesn't have binary-specific dependencies so it can't know that `rouille` is only a dependency of `wasm-bindgen-test-runner`. We could try to split this apart though and enable something like:

```
cargo build --bin wasm-bindgen --no-default-features
```

to not enable building `wasm-bindgen-test-runner`, but that seems like it may be a bit overkill? What's the use case you have in mind for reducing build times here?

**Comment by ibaryshnikov** [comment]
Isn't this feature in the cargo's roadmap?
I'm setting up a ci. And cargo install is a popular way to install crates, though using prebuilt binaries might be a better idea.

**Comment by alexcrichton** [comment]
This is unlikely to be a feature of Cargo in the near future. I'd recommend using prebuilt binaries or wasm-pack to download the prebuilt binaries for now.
