### ISSUE TITLE
Build failures in Nightly due to Proc macro API 1.2

### ISSUE THREAD

**Issue by tirkarthi** [rustwasm/wasm-bindgen#203]
Project fails with Nightly compiler due to the recent proc macro API changes made that renames some of the components. It seems the release of proc macros 2 library with the changes already released which will fix the issue. I searched for issues here and couldn't find anything related to this. Hence I am opening this as a reminder. Feel free to close this if it's tracked elsewhere or irrelevant due to semver in cargo.toml using the latest version. 

Upstream rustc issue reference : https://github.com/rust-lang/rust/pull/50473#issue-186182501
Upstream proc macros 2 PR (merged) : https://github.com/alexcrichton/proc-macro2/pull/90
0.4.3 release : https://github.com/alexcrichton/proc-macro2/tree/0.4.3

Thanks

**Comment by alexcrichton** [comment]
Fixed in https://github.com/rustwasm/wasm-bindgen/commit/e76f5537e0b9182c273d08c8630e7112efb0fa06!
