### ISSUE TITLE
Web target now requires async support

### ISSUE THREAD

**Issue by nickbabcock** [rustwasm/wasm-bindgen#2034]
I have a project (can link if desired) which executes:

```
wasm-pack build --target web 
```

and the resulting js is interpreted by parcel. https://github.com/rustwasm/wasm-bindgen/pull/1996 introduced async/await into the generated js. My project doesn't use async/await so this was the first instance of said feature. By default, parcel is unable to cope with async without additional configuration. The result is the js error "Error: regeneratorRuntime is not defined" at runtime.

I'm fine with this change in behavior (introducing async) if is it's intended, but just wanted to voice something I stumbled upon. Perhaps a note in the changelog highlighting this change is called for?

**Comment by alexcrichton** [comment]
Thanks for the report! The glue generated by wasm-bindgen is intended to be run in relatively modern environments, though, and I think that every browser which supports wasm should support async.

For bundlers it's recommended to use `--target bundler`, but unfortunately I'm not sure that parcel has enough wasm support implemented to support `--target bundler` just yet.
