### ISSUE TITLE
Is there going to be an extension API binding?

### ISSUE THREAD

**Issue by nrayamajhee** [rustwasm/wasm-bindgen#2035]
I was wondering if there are any plans/discussions about implementing the Web Extensions API bindings. I couldn't find any extension API namespaces <https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API> in web_sys. So are there any plans to implement those?

I have been able to run the **Using the older --target no-modules** example on the browser extension popup window. So it does seem possible to run rust wasm in Web Extensions.

![screenshot](https://user-images.githubusercontent.com/4941091/76048296-f8767780-5f2a-11ea-8742-1363c55574b3.png)

**Comment by alexcrichton** [comment]
Thanks for the report! I don't think we have a plan as-is right now, but if no-modules works would that suffice for your use case? We're not going to remove no-modules at any point in the near future, so if that works it should do the trick!

**Comment by nrayamajhee** [comment]
Yes the no-modules works great. I am not working on anything specific right now so I don't have any use case tbh. I was just exploring what can be done via `web-sys`. Seems like all the extension API calls such as `tabs.insertCSS` will have to be done from the JS side. But on the brighter side, it is indeed possible to offloaded performance critical task to rust if one needs that for a browser extension 😃.

**Comment by Pauan** [comment]
I've created multiple Web Extensions entirely in Rust. After trying various different setups, I think using the `@wasm-tool/rollup-plugin-rust` plugin is the best way to go for Web Extensions (and probably in general, to be honest). [Here is an example](https://github.com/Pauan/SaltyBetBot/blob/master/rollup.config.js).

As for Web Extension bindings, we don't have any, but you can make your own. I've created some [here](https://github.com/Pauan/tab-organizer/tree/rust/web-extension), but they're not ready to be published yet.

**Comment by alexcrichton** [comment]
Ok sounds like I don't think we're going to add support specifically for extensions in the sense that it largely already works today. In that case I'm going to close.

**Comment by extraymond** [comment]
@Pauan  Woah! That binding looks awesome. Thanks for sharing it.

**Comment by fosskers** [comment]
_Wanders in from the future._

Just here to add some signal: I've accomplished some interesting things for a client in the past few days. Namely using https://github.com/w3reality/wasm-mt/ in a Seed app, and running the compiled WASM in a Web Extension. Next I was hoping that `web_sys` already had bindings to the Web Extension API, since I need it for the client work, but failing that, it'll be a good opportunity to learn about the JS FFI.
