### ISSUE TITLE
error on generated files by wasmpack

### ISSUE THREAD

**Issue by madiazp** [rustwasm/wasm-bindgen#2039]
## 🐛 Bug description
after building a rust library the compilation process is successful, but when i use the generated files on nodejs it throws the next error

```
ReferenceError: Window is not defined
      at module.exports.__wbg_instanceof_Window_04bba8b54ef81db0 (/home/italo/Documentos/zk/package/zk_lib.js:143:42)
      at wasm-function[977]:8
      at wasm-function[723]:19
      at wasm-function[21]:1946
      at wasm-function[124]:896
      at wasm-function[108]:1195
      at wasm-function[141]:1343
      at Object.module.exports.generate_proof (/home/italo/Documentos/zk/package/zk_lib.js:108:20)
      at Object.<anonymous> (/home/italo/Documentos/zk/api_app_zk/dist/services/utils/zokrates.js:41:24)
      at Generator.next (<anonymous>)
```
the command used to build the library is
`wasm-pack build --target nodejs --release`

the code in the library doesnt use any js methods, its only rust.
seems to me like Window instance doesnt exist in nodejs as the DOM is used on web.

this is the code generated that has the error
```
module.exports.__wbg_instanceof_Window_04bba8b54ef81db0 = function (arg0) {
    var ret = getObject(arg0) instanceof Window;
    return ret;
};
```
#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: 0.9.1
rustc version: 1.42.0-nightly

**Comment by alexcrichton** [comment]
Thanks for the report! The instanceof checks do not check for defineded-ness and that'll need to be checked elsewhere in the code. You'll want to find what is checking for an instance of `Window` and it'll need to be updated to work in nodejs as well.
