### ISSUE TITLE
Float32Array.set_index should take &mut self instead of just &self

### ISSUE THREAD

**Issue by stephanemagnenat** [rustwasm/wasm-bindgen#2042]
### Describe the Bug

According to the documentation, `Float32Array.set_index()` sets a value in the array, so I do not understand why it does not take an exclusive reference to self.

### Steps to Reproduce

Look at the function signature or at the [documentation here](https://rustwasm.github.io/wasm-bindgen/api/js_sys/struct.Float32Array.html#method.set).

### Expected Behavior

I would expect the function to take an exclusive reference to self (&mut self).

### Actual Behavior

The function take a shared reference to self (&self).

### Additional Context

I guess this applies to all typed arrays.

If there is a good reason for allowing a shared reference, it would be good to document it in the API doc.

**Comment by chinedufn** [comment]
Explained in https://github.com/rustwasm/wasm-bindgen/issues/1061

**Comment by Pauan** [comment]
@stephanemagnenat Unlike Rust, JS values always allow for multiple writers, so they behave like an `Rc<RefCell<T>>`.

Just like how `Rc<RefCell<T>>` allows you to mutate `T` with a `&` reference, the same is true with JS.

**Comment by stephanemagnenat** [comment]
Thank you very much for the explanation! I think that it would be good to make that appear clearly in the doc (otherwise people might ask the question again). I do not know if the documentation system supports having a note mark at each function that would logically be `&mut` from a rust perspective but is not from a JS one would be helpful. If not, as there is already a note about unsafe functions, maybe a similar note could appear about mutability.
