### ISSUE TITLE
Can't create local name binding for web_sys::FormData

### ISSUE THREAD

**Issue by maxv-rust** [rustwasm/wasm-bindgen#2046]
Can't create local name binding for web_sys::FormData.

The code

```
use web_sys::FromData;
	
fn foo(_data: FormData) {
}

```

fails with unexpected compilation error

```
  --> use_form_data/src/lib.rs:10:6
   |
10 |     use web_sys::FromData;
   |         ^^^^^^^^^--------
   |         |        |
   |         |        help: a similar name exists in the module: `FormData`
   |         no `FromData` in the root

error: aborting due to previous error
```

Workaround is to use web_sys::FormData directly in function signature. 
Ex:
```
fn foo(_data: web_sys::FormData) {
}
```

I'm not sure if it web_sys or rust bug.

**Comment by Pauan** [comment]
This isn't a bug, you just misspelled `FormData` (which is what the `help:` in the error message says).
