### ISSUE TITLE
without_a_bundler_no_modules: wasm_bindgen is not defined

### ISSUE THREAD

**Issue by worikgh** [rustwasm/wasm-bindgen#2047]
### Describe the Bug

When running `without_a_bundler_no_modules` example get error `wasm_bindgen is not defined` at line 19 of `index.html`: `const { add } = wasm_bindgen;`
I build with `wasm-pack build --target no-modules`

**Comment by Pauan** [comment]
I can't reproduce this. I copied the `without-a-bundler-no-modules` folder, ran `wasm-pack build --target no-modules`, and then loaded `index.html` in a browser and everything worked fine.

What's your version of wasm-pack and Rust?

**Comment by worikgh** [comment]
It was my mistake.  I closed this minutes after I opened it as I realised.

I have not found how to delete an issue I have opened.

Sorry about that, I have `without-a-bundler-no-modules` working well.

Not `without-a-bundler` (`--taget web`) but that is another story, and now I do not care.
