### ISSUE TITLE
js-sys v0.3.36 - error[E0603]: struct `Memory` is private

### ISSUE THREAD

**Issue by davnav** [rustwasm/wasm-bindgen#2048]
### Summary

I am getting below error when I try to compile my wasm program with **wasm-pack build**
Not  sure where is the issue !

```
 Compiling js-sys v0.3.36
error[E0603]: struct `Memory` is private
    --> /home/naveen/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.36/src/lib.rs:4920:60
     |
4920 |                 let mem = buf.unchecked_ref::<WebAssembly::Memory>();
     |                                                            ^^^^^^ this struct is private
     |
note: the struct `Memory` is defined here
    --> /home/naveen/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.36/src/lib.rs:3554:5
```

A clear and concise summary of your question.

### Additional Details

Provide any additional details here.

I am using below version:

wasm-pack 0.8.1
cargo 1.43.0-nightly (e57bd0299 2020-02-21)
rustc 1.43.0-nightly (436494b8f 2020-02-22)

**Comment by alexcrichton** [comment]
THanks for the report! This broke awhile back in nightlies but has since been fixed. If you update your nightly you should be good to go!

**Comment by davnav** [comment]
Thank you. That worked.
