### ISSUE TITLE
Copied doc comments are escaped in .d.ts

### ISSUE THREAD

**Issue by 0xd4d** [rustwasm/wasm-bindgen#2053]
Useless backslashes are added to the copied doc comments, see below.

wasm-bindgen = "0.2.59"

build: `wasm-pack build`

```rust
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub struct MyStruct;

#[wasm_bindgen]
impl MyStruct {
    /// This "is" \ some text: it's
    /// ```
    /// let a = b"\x12\x34";
    /// ```
    pub fn meth(&self) {}
}
```

Note all the extra backslashes below:

```ts
/* tslint:disable */
/* eslint-disable */
export class MyStruct {
  free(): void;
/**
* This \"is\" \\ some text: it\'s
* ```
* let a = b\"\\x12\\x34\";
* ```
*/
  meth(): void;
}
```

**Comment by alexcrichton** [comment]
Thanks for the report! I'm not too entirely sure where this is coming from myself. It seems like this has to do with some attribute escaping somewhere, and I think we'd just need to track down what's escaped where and see if we can get an unescaped version. Not really a great answer, but this is definitely a bug worth fixing!
