### ISSUE TITLE
It's not possible to js_name rename an enum

### ISSUE THREAD

**Issue by 0xd4d** [rustwasm/wasm-bindgen#2054]
It's not possible to `js_name` rename an enum.

wasm-bindgen = "0.2.59"

build: `wasm-pack build`

```rust
use wasm_bindgen::prelude::*;

#[wasm_bindgen(js_name = "MyStruct")]
pub struct MyStructJS;

#[wasm_bindgen(js_name = "MyEnum")]
pub enum MyEnumJS {
	Zero,
	One,
	Two,
}
```

Note that `MyEnumJS` wasn't renamed to `MyEnum` below

```ts
/* tslint:disable */
/* eslint-disable */
/**
*/
export enum MyEnumJS {
  Zero,
  One,
  Two,
}
export class MyStruct {
  free(): void;
}
```

**Comment by alexcrichton** [comment]
Thanks for the report! Currently not all attributes are supported in all places, but that's just a bug and it should be easy enough to plumb this through to get things working!
