### ISSUE TITLE
Unable to install wasm-bindgen-cli

### ISSUE THREAD

**Issue by Arthur-Kamau** [rustwasm/wasm-bindgen#2061]
### Describe the Bug

Trying  to install wasm-bindgen-cli throght:
` cargo +nightly install wasm-bindgen-cli`
also tried 
`cargo  install wasm-bindgen-cli`
 
rust version
`rustc 1.44.0-nightly (f509b26a7 2020-03-18)`

ubuntu version
19.10

Error stack trace
![Screenshot from 2020-03-27 20-56-58](https://user-images.githubusercontent.com/30284230/77786885-b050fd80-706f-11ea-9213-56e420fc8cdc.png)

could have raised an issue in docopt but i wanted to install wasm-bindgen-cli which has dependancy of  docopt.

how do i resolve this error.
Thanks.

**Comment by alexcrichton** [comment]
Thanks for the report! This is actually a bug in the Rust compiler, not wasm-bindgen. It looks like you're using nightly, though, so updating nightly should fix the issue.
