### ISSUE TITLE
TextMetrics or alternatives

### ISSUE THREAD

**Issue by hwchen** [rustwasm/wasm-bindgen#2069]
### Summary

Hello, I'm trying to implement some text-layout/line-breaking using web-sys and `TextMetrics` https://docs.rs/web-sys/0.3.37/i686-unknown-linux-gnu/web_sys/struct.TextMetrics.html.

For my implementation, I'm using height and baseline, but those are not available in the `TextMetrics` api. (looks like they're not supported consistently across browsers).

I'm not too familiar with web apis, so if there's other alternatives, please let me know.

**Comment by alexcrichton** [comment]
Thanks for the report! Unfortunately though at this time we don't have a ton of time to help out with web-related questions like this, so I'd recommend looking for JS examples and mirroring those into Rust

**Comment by hwchen** [comment]
Thanks for clarifying, I may not have been clear enough in the opening comment.

Yes, I'm hoping to have updated `TextMetrics` with more than just the `width` property available.

**Comment by ecton** [comment]
In case someone stumbles across this as I did, here's how I solved it:

```rust
#[derive(Serialize, Deserialize, Debug)]
struct ExtendedTextMetrics {
    actual_bounding_box_ascent: f64,
    actual_bounding_box_descent: f64,
    actual_bounding_box_left: f64,
    actual_bounding_box_right: f64,
    width: f64,
}

#[wasm_bindgen(inline_js = r#"export function measure_text(canvas, text) { 
        const metrics = canvas.measureText(text); 
        return { 
            actual_bounding_box_ascent: metrics.actualBoundingBoxAscent,
            actual_bounding_box_descent: metrics.actualBoundingBoxDescent,
            actual_bounding_box_left: metrics.actualBoundingBoxLeft,
            actual_bounding_box_right: metrics.actualBoundingBoxRight,
            width: metrics.width
        };
    }"#)]
extern "C" {
    fn measure_text(canvas: &CanvasRenderingContext2d, text: &str) -> Object;
}

...

let text_metrics = measure_text(&context, &text);
let text_metrics: ExtendedTextMetrics = text_metrics.into_serde().unwrap();
```

I'm not sure if there's a cleaner way to do this or to do it without the use of the Javascript code. The only way I could avoid the resulting type from being interpreted as the built-in TextMetrics type was to recreate the object on the Javascript side. Frustratingly, calling `web_sys::console::info_1` with a TextMetrics object properly logs out all of the values contained in the object, but no matter how I tried to access it through the JsValue interfaces, I couldn't get access to the values that weren't defined in web_sys::TextMetrics.

Hope this helps someone, although I would recommend much better error handling than the code I wrote above. From what I can tell the four properties I'm trying to access are available on most [major browsers](https://developer.mozilla.org/en-US/docs/Web/API/TextMetrics/actualBoundingBoxAscent), so I would definitely love to see them be added to the built-in TextMetrics type.

**Comment by Pauan** [comment]
@ecton This is the idiomatic way to accomplish that:

```rust
#[wasm_bindgen]
extern "C" {
    type ExtendedTextMetrics;

    #[wasm_bindgen(method, getter, js_name = actualBoundingBoxAscent)]
    fn actual_bounding_box_ascent(this: &ExtendedTextMetrics) -> f64;

    #[wasm_bindgen(method, getter, js_name = actualBoundingBoxDescent)]
    fn actual_bounding_box_descent(this: &ExtendedTextMetrics) -> f64;

    #[wasm_bindgen(method, getter, js_name = actualBoundingBoxLeft)]
    fn actual_bounding_box_left(this: &ExtendedTextMetrics) -> f64;

    #[wasm_bindgen(method, getter, js_name = actualBoundingBoxRight)]
    fn actual_bounding_box_right(this: &ExtendedTextMetrics) -> f64;

    #[wasm_bindgen(method, getter)]
    fn width(this: &ExtendedTextMetrics) -> f64;
}

...

let text_metrics = context.measure_text(&text).unwrap();
let text_metrics: ExtendedTextMetrics = text_metrics.unchecked_into();
```

This will be quite a lot faster than using `into_serde`.
