### ISSUE TITLE
Webpack loader

### ISSUE THREAD

**Issue by xtuc** [rustwasm/wasm-bindgen#207]
With the new wasm pipeline in Webpack (> 4.8.0), loader can now directly emit a wasm binary. 

I have a very simple demo here: https://github.com/xtuc/c-webpack-demo.

The idea would be to allow:

```js
  module: {
    rules: [
      {
        test: /\.c$/,
        loader: "wasm-bindgen/loader",
        type: "webassembly/experimental"
      }
    ]
  },
```

and the user would just:

```js
import("./lib.rs").then(...)
```

**Comment by alexcrichton** [comment]
Nice! I'd love to have a webpack loader for wasm-bindgen!

Do you think it'd be best to live in a separate repo with a link here? Or live here? (I'm up for whatever)

**Comment by xtuc** [comment]
> Do you think it'd be best to live in a separate repo with a link here? Or live here? (I'm up for whatever)

from my point of view it doesn't really matter.

**Comment by jsheard** [comment]
FWIW [rust-native-wasm-loader](https://github.com/dflemstr/rust-native-wasm-loader) already supports wasm-bindgen and webpack4s wasm pipeline.

I haven't used it much (mostly using no-modules mode for my stuff) but it seems to work fine.

**Comment by alexcrichton** [comment]
Ok cool! In that case I wonder if adding it in here may be the best option for the most visibility? I don't personally know much about webpack loaders but @xtuc if you're willing to help review changes I'm more than willing to help field bugs :)

**Comment by xtuc** [comment]
@alexcrichton yes sure, just ping me when needed

**Comment by alexcrichton** [comment]
@xtuc did you want to make an initial PR importing files into the repo?

**Comment by alexcrichton** [comment]
I'm gonna close this in favor of https://github.com/rustwasm/rust-webpack-template, as new issues should likely go there!
