### ISSUE TITLE
Error when using js_name with both getter and setter

### ISSUE THREAD

**Issue by 0xd4d** [rustwasm/wasm-bindgen#2072]
### Describe the Bug

It's not possible to rename both getter & setter with js_name=xxx

### Steps to Reproduce

build: `wasm-pack build`

```rust
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub struct MyStruct;

#[wasm_bindgen]
impl MyStruct {
	#[wasm_bindgen(getter)]
	#[wasm_bindgen(js_name = "myProp")]
    pub fn my_prop(&self) -> u32 {
        0
    }

    #[wasm_bindgen(setter)]
	#[wasm_bindgen(js_name = "myProp")]
    pub fn set_my_prop(&mut self, _value: u32) {}
}
```

### Expected Behavior

I expect the property to be named `myProp`

### Actual Behavior

I get this compile error:

```
error: symbol `mystruct_myProp` is already defined
 --> src\lib.rs:6:1
  |
6 | #[wasm_bindgen]
  | ^^^^^^^^^^^^^^^

error: aborting due to previous error
```

Changing the setter's name to `set_myProp` creates two properties:

```rust
    #[wasm_bindgen(setter)]
	#[wasm_bindgen(js_name = "set_myProp")]
    pub fn set_my_prop(&mut self, _value: u32) {}
```

A workaround is to rename the rust methods to `myProp` and `set_myProp` respectively.

**Comment by Pauan** [comment]
You have to use the same attribute, like this:

```rust
#[wasm_bindgen]
impl MyStruct {
    #[wasm_bindgen(getter, js_name = "myProp")]
    pub fn my_prop(&self) -> u32 {
        0
    }

    #[wasm_bindgen(setter, js_name = "myProp")]
    pub fn set_my_prop(&mut self, _value: u32) {}
}
```

**Comment by 0xd4d** [comment]
Did you try that code? I'm getting the exact same error message.

**Comment by Pauan** [comment]
@0xd4d Hmm, odd, it did work when I tested it. It seems to work if you have a getter or setter, but not both. So that's definitely a bug with wasm-bindgen.

**Comment by 0xd4d** [comment]
Seems to have been fixed by https://github.com/rustwasm/wasm-bindgen/pull/2074
