### ISSUE TITLE
How to retrieve an HTMLElement from an Event

### ISSUE THREAD

**Issue by guigeek38** [rustwasm/wasm-bindgen#2077]
### Summary
When I register a callback on an event, for exemple `onsubmit` in a form, I get an `Event` type when the event is trigger.

From the `Event`, I can get the `EventTarget` with `target()` function, but I can not do anything with this type, to retrieve the `HTMLElement` which is behind, in my case an `HTMLFormElement`.

### Additional Details
I use `Yew` (with `web_sys`) in order to build client web app, and I would like to make a form in my web page. I register form `onsubmit` event but I cannot get the content of this form with the `Event`.

Web API documentation: https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement

For exemple, _stdweb_ project gives a `TryFrom `implementation to retieve `HtmlElement`:
https://docs.rs/stdweb/0.4.20/stdweb/web/struct.EventTarget.html#implementations

I surely did not understand how to do it, but I can not find other ways to achieve this.
Thank you for your help!

**Comment by Pauan** [comment]
You can use the [`JsCast`](https://rustwasm.github.io/wasm-bindgen/api/wasm_bindgen/trait.JsCast.html) trait to cast from one JS type to another, like this:

```rust
let element = event.target()
    .unwrap_throw()
    .dyn_into::<HtmlFormElement>()
    .unwrap_throw();
```

Don't forget to put `use wasm_bindgen::JsCast;` at the top of your file.

**Comment by chinedufn** [comment]
Hey!

You'll want to use `e

```rust
let target = event
                .target()
                .unwrap()
                .dyn_into::<web_sys::Element>()
                .unwrap();
```

**Comment by guigeek38** [comment]
Thanks a lot for your help!
