### ISSUE TITLE
Optionally generate a rust binding file

### ISSUE THREAD

**Issue by autodidaddict** [rustwasm/wasm-bindgen#209]
Today, when you run the `wasm-bindgen` CLI, you will get a JS file that matches the name of your enriched `.wasm` file. When it's done, the extra metadata has been cleared from the wasm file and used to inform the codegen that happens in the JS wrapper. So for a `greet.wasm` you'd get a `greet.js` which then lets you invoke a function called `greet` from JS, and the wasm module is able to invoke an extern called `alert` that is bound to the JavaScript `alert`.

I would love to see the possibility for a similar wrapper for Rust. Currently, we can host wasm modules in Rust using the [wasmi](https://crates.io/crates/wasmi) crate. Unfortunately, we start in the same bare position that we would be in w/out wasm-bindgen - being forced to invoke numeric-only methods with numeric-only return values.

If you take a look at the trait implementations for `Externals` and `ModuleImportResolver` in the [Tic Tac Toe](https://github.com/paritytech/wasmi/blob/master/examples/tictactoe.rs) wasmi sample, you can start to see a pattern there where codegen might be able to automatically produce these for you, and create a Rust-idiomatic wrapper for both directions.

Generated wrappers for Rust->wasm would basically wrap wasmi's `instance.invoke_export` while other wrappers would implement the `Externals` trait with enough wrappers to allow Rust types to be the one the Rust-host developer sees.

I would love to help contribute to this but I'm not familiar enough with the internals of wasm-bindgen to be confident that I would do this right. Maybe there might be someone who would want to pair on a feature like this?

**Comment by autodidaddict** [comment]
After figuring out what some of the code in the CLI is doing, it looks like it's already using the `wasmi` crate in order to execute the descriptor functions within the enhanced wasm ... so, in theory, it should be somewhat straightforward to build out this kind of wrapper? Again, I'd love to do this with some assistance from those familiar with this codebase

**Comment by alexcrichton** [comment]
An interesting idea! This was also discussed previously I believe at https://github.com/rustwasm/wasm-bindgen/issues/187 although the main conclusion there was that currently this project is primarily focused on wasm<->JS interop, so wasm<->Rust interop is unlikely at this time to be prioritized

**Comment by autodidaddict** [comment]
Totally understand it not being a high priority for others. I'm doing a bit of work and writing in the area of non-web hosts and I noticed that there's a gap where a Rust host doesn't know how to deal with strings and structs and such from a wasm file produced with a wasm_bindgen macro. I guess I can do it manually for now. Is there a doc that would help me figure out how to manually interact with a wasm module that had been prepped via wasm_bindgen, e.g. a function that takes and returns a string?

**Comment by alexcrichton** [comment]
Nah unfortunately the exact particulars of the ABI aren't well documented today, but you can browse the generated JS or the `InfoWasm` and `FromWasm*` impls in `src/convert.rs` for more information

**Comment by alexcrichton** [comment]
I'm gonna close this for now because wasm-bindgen is focused on JS, but it'd be neat to see how this plays out for other languages in the future!
