### ISSUE TITLE
Element::class_name and Element::set_class_name do not work for a SvgElement

### ISSUE THREAD

**Issue by liquidblock** [rustwasm/wasm-bindgen#2091]
### Describe the Bug
When calling `web_sys::Element::set_class_name` or `web_sys::Element::class_name` on an `web_sys::SvgsvgElement` or `web_sys::SvgElement` a `TypeError` is thrown.

### Steps to Reproduce

1. Create an SVG Element
    E.g. with javascript
    ```js
    document.createElementNS("http://www.w3.org/2000/svg", "svg")
    ```
    or with rust code
    ```rust
    web_sys::window().unwrap().document().unwrap().create_element_ns(Some("http://www.w3.org/2000/svg"), "svg").unwrap()
    ```
2. Now call `web_sys::Element::set_class_name` or `web_sys::Element::class_name` on the `Element`

3. A `TypeError` will be thrown and the rust code stops executing (not due to a panic).

I added testcases to web-sys on [my wasm-bindgen fork on my websys-class-name-test branch](https://github.com/liquidblock/wasm-bindgen/tree/websys-class-name-test), which are currently failing.

I created a simple test application [here](https://github.com/liquidblock/websys-class-name-test/blob/master/src/lib.rs).

### Expected Behavior

I expect a rust panic instead of the `TypeError` to be thrown.
Alternatively i would like a `Result<String, _>` for `Element::class_name` and a `Result<(), _>` for `Element::set_class_name`. And to add `class_name` and `set_class_name` functions in `web_sys::HtmlElement` with the same signature of the currently available functions, which do not fail.

### Actual Behavior

My [testcases](https://github.com/liquidblock/wasm-bindgen/tree/websys-class-name-test) results in these:
```
---- wasm::svg_element::element_set_class_name output ----
    error output:
        wasm-bindgen: imported JS function that was not marked as `catch` threw an error: setting getter-only property "className"
[...]
```
and
```
---- wasm::svg_element::element_get_class_name output ----
    error output:
        wasm-bindgen: imported JS function that was not marked as `catch` threw an error: expected a string argument
[...]
```

The simple application crashes:
`Test Begin` is shown in the console log, but not `Test End`:
![image](https://user-images.githubusercontent.com/7364785/79671874-f19b7f80-81cd-11ea-96dc-fdc626ff6650.png)

### Additional Context

Versions used:
* wasm-bindgen = "0.2.60"
* Windows 10
* geckodriver 0.26.0 (e9783a644016 2019-10-10 13:38 +0000)
* Firefox 75.0 (64-bit)
* Chrome Version 81.0.4044.113 (Official Build) (64-bit)

The `SVNElement` interface of the DOM is derived from the `Element` interface and overrides the `className` property which is read only and returns a different type, see https://developer.mozilla.org/en-US/docs/Web/API/SVGElement.

Note that there is a `class_name` method for `SvgElement`, which has a different signature than of `Element`:
`pub fn class_name(&self) -> SvgAnimatedString` versus `pub fn class_name(&self) -> String`.

I stumbled across this bug when submitting a PR to yewstack/yew https://github.com/yewstack/yew/pull/1085.

**Comment by Pauan** [comment]
This is not a bug in wasm-bindgen, this also gives the same error:

```js
(function () {
    "use strict";

    var x = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    document.body.appendChild(x);
    x.className = "hi";
})();
```

[`SVGSVGElement`](https://developer.mozilla.org/en-US/docs/Web/API/SVGSVGElement) inherits from [`SVGElement`](https://developer.mozilla.org/en-US/docs/Web/API/SVGElement), and `SVGElement` *overrides* the `className` property, which changes its type to `SVGAnimatedString` and also makes it readonly.

Because properties/methods from subclasses have priority over parent classes, that means that `SVGElement.className` has priority over `Element.className`.

There is only one way to use `Element.className` with SVG:

```js
Object.getOwnPropertyDescriptor(Element.prototype, "className").set.call(x, "hi");
```

But I really don't recommend that. So your only real option is to use `classList` instead.
