### ISSUE TITLE
Does we need to use promise.then() to load wasm module as stated in the "Hello World" example

### ISSUE THREAD

**Issue by eisenhaus335** [rustwasm/wasm-bindgen#2096]
### Summary
Hello, i just newly start learn webassembly with rust and take a look example on this example
https://rustwasm.github.io/docs/wasm-bindgen/examples/hello-world.html#indexjs

Does wasm-bindgen need to promise.then() first to load the wasm? but there is example using ECMAScript with code like this in introduction

```
import { greet } from "./hello_world";

greet("World!");
```

```
// Note that a dynamic `import` statement here is required due to
// webpack/webpack#6615, but in theory `import { greet } from './pkg';`
// will work here one day as well!
```
this paragraph make me confused how to do this so might need more explanation. are this `import {greet} from './pkg';` already work for now or what

**Comment by bennetthardwick** [comment]
Using a [dynamic import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#Dynamic_Imports) is required because Webpack doesn't currently support the synchronous version. 

This was tracked by webpack/webpack#6615 and has been fixed in the next major version of Webpack - which will probably be released soon.

**Comment by alexcrichton** [comment]
Oh great! This is probably just code that needs to be updated!

**Comment by eisenhaus335** [comment]
i just start a new project just to showcase my project directory
[https://github.com/eisenhaus335/simple_showcase/(url)
i never test the wasm package so cant say for sure but please take alook at this [https://github.com/eisenhaus335/simple_showcase/tree/master/src/pkg](url)

the index.d.ts expose only inside wasm function. they not expose the promise first. its hard for me to explain but yeah is'nt that the index.d.ts need to give declaration for promise first and later give our important wasm func

**Comment by eisenhaus335** [comment]
after notice the difference between `import {} from './pkg'` and `const wasm = import('./pkg')` i think i know how to use wasm-bindgen. thanks for the support :D gotta close this issue

**Comment by eisenhaus335** [comment]
after noticing again. i has never test the `import {} from './pkg' syntax`. does wasm-bindgen support this? or its just me that unable to understand the basics. i think they are different but its just i has never read the document thus explain why i am keep asking this
