### ISSUE TITLE
How to get navigator.clipboard?

### ISSUE THREAD

**Issue by vojta7** [rustwasm/wasm-bindgen#2097]
### Summary

I would like to access [Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard), but I don't see it mentioned anywhere in the documentation and the following code fails.

```rust
window().navigator().clipboard()
```

with this error

```
no method named `clipboard` found for struct `web_sys::features::gen_Navigator::Navigator` in the current scope
```

### Additional Details

I tried to enable experimentall features, but it had no effect.

**Comment by Pauan** [comment]
@vojta7 `Clipboard` is an unstable API. We only add unstable APIs on an ad-hoc basis, so we would gladly accept a pull request adding it in.
