### ISSUE TITLE
ES5 example

### ISSUE THREAD

**Issue by rookboom** [rustwasm/wasm-bindgen#211]
The latest version of wasm-bindgen can export to ES5 with the no-modules flag. How do you load the wasm file at runtime in this case? The example in the documentation uses ES6' import, which is dynamic and returns a Promise. How does this work for ES5 since static import (require) does not work?

**Comment by alexcrichton** [comment]
There's some [brief documentation](https://github.com/rustwasm/wasm-bindgen#cli-reference) in the readme but I definitely agree that an example of this would be great to show off!

**Comment by qrilka** [comment]
@alexcrichton was that documentation moved somewhere? It would be great to have stable links

**Comment by qrilka** [comment]
Thanks @daxpedda that seems to be the page about the source issue. Actually I misread it initially, I was trying to find a way to use ES5 module with wasm-bindgen and https://rustwasm.github.io/docs/wasm-bindgen/examples/import-js.html seems to deal with ES6.
