### ISSUE TITLE
New version of wasm-bindgen breaks with parcel-plugin-wasm.rs

### ISSUE THREAD

**Issue by dancespiele** [rustwasm/wasm-bindgen#2120]
### Describe the Bug
with the version 0.2.61 and 0.2.62 I cannot compile wasm-bindgen with parcel and parcel-plugin-wasm.rs generate a wrong wasm-loader.js

### Steps to Reproduce

1. Install yew-parcel-template: `npm init yew-parcel yew-test`
2. Go to the project directory: `cd yew-test`
3. Remove Cargo.lock: `rm crate/Cargo.lock`
4. Start the project: `npm start`
5. the error throw in terminal:
```javascript
  1 | var wasm;const __exports = {};
> 2 | export * from "./yew_parcel_bg.js";
    |              ^
  3 | 
  4 |       function init(wasm_path) {
  5 |           const fetchPromise = fetch(wasm_path);

```
6. Open the file wasm-loader.js: `nano node_modules/parcel-plugin-wasm.rs/wasm-loader.js`
7. The script is generate wrongly:

```javascript
var wasm;const __exports = {};
export * from "./yew_parcel_bg.js";

      function init(wasm_path) {
          const fetchPromise = fetch(wasm_path);
          let resultPromise;
          if (typeof WebAssembly.instantiateStreaming === 'function') {
              resultPromise = WebAssembly.instantiateStreaming(fetchPromise, { './yew_parcel.js': __exports });
          } else {
              resultPromise = fetchPromise
              .then(response => response.arrayBuffer())
              .then(buffer => WebAssembly.instantiate(buffer, { './yew_parcel.js': __exports }));
          }
          return resultPromise.then(({instance}) => {
              wasm = init.wasm = instance.exports;
              __exports.wasm = wasm;
              return;
          });
      };
      function init_node(wasm_path) {
          const fs = require('fs');
          return new Promise(function(resolve, reject) {
              fs.readFile(__dirname + wasm_path, function(err, data) {
                  if (err) {
                      reject(err);
                  } else {
                      resolve(data.buffer);
                  }
              });
          })
          .then(data => WebAssembly.instantiate(data, { './yew_parcel': __exports }))
          .then(({instance}) => {
              wasm = init.wasm = instance.exports;
              __exports.wasm = wasm;
              return;
          });
      }
      const wasm_bindgen = Object.assign(false ? init_node : init, __exports);
      module.exports = function loadWASMBundle(bundle) {
            return wasm_bindgen(bundle).then(() => __exports)
      }
```
previous to the version 0.2.61 the parcel plugin worked fine

### Expected Behavior

wasm_bindgen should work with parcel as it was doing before of the version 0.2.61 ("no necessarily with the plugin parcel-plugin-wasmbindgen but with parcel")

### Actual Behavior
No possible run parcel with wasm-bindgen in version 0.2.61 and 0.2.62

### Additional Context
Source of parcel-plugin-wasm.rs: https://github.com/catsigma/parcel-plugin-wasm.rs

**Comment by alexcrichton** [comment]
@Pauan would you be able to help take a look at this?

**Comment by Pauan** [comment]
This is a bug with parcel-plugin-wasm. They are doing [custom parsing of the JS code](https://github.com/catsigma/parcel-plugin-wasm.rs/blob/c3f73fe4f8aac4adda75cd9de4fcbe68c9172350/WASMbindgenAsset.js#L149) (which isn't a very good idea), and so they need to update their code to take into account the `export`.

In addition, they need to load the `foo_bg.js` file, not the `foo.js` file.

They seem to be doing a lot of complicated stuff. They could make their plugin *far* simpler if they used `--target web` instead.

**Comment by Pauan** [comment]
I filed a bug report: https://github.com/catsigma/parcel-plugin-wasm.rs/issues/30

**Comment by Pauan** [comment]
In the meantime, you can remove the Parcel plugin and [just use `--target web`](https://rustwasm.github.io/docs/wasm-bindgen/examples/without-a-bundler.html):

```js
import init, * as exports from "./path/to/foo.js";

async function main() {
    await init("./path/to/foo_bg.wasm");

    // Use exports
}

main().catch(console.error);
```

You might need to use a [Parcel plugin](https://github.com/elwin013/parcel-plugin-static-files-copy) to copy the `.wasm` file into your build directory.
