### ISSUE TITLE
Structs whose name begins with "Test" cause run-time failures in wasm-bindgen-test tests

### ISSUE THREAD

**Issue by prestwich** [rustwasm/wasm-bindgen#2121]
### Describe the Bug

When using `wasm-bindgen-test` via `wasm-pack test`, if any struct have a name beginning with `Test` or `test` and have  the `#[wasm-bindgen]` macro the tests will fail to run. 

### Steps to Reproduce

1. `wasm-bindgen = "0.2.62"`
1. `wasm-bindgen-test = "0.3.12"`
1. Add the following to a fresth `lib.rs` and run `wasm-pack test --node`.

```rust
#[wasm_bindgen]
pub struct Test;

#[cfg(test)]
pub mod test {
    use wasm_bindgen_test::*;

    #[wasm_bindgen_test]
    fn pass() {
        assert_eq!(1, 1);
    }
}
```

### Actual Behavior

These struct names work:
- `ConnectionTest`
- `SocketTest`
- `ATest`
- `Attestation`

These names fail:
- `Test`
- `TestConnection`
- `Testnet`
- `Testify`
- `test`
- `testify`

Removing the `#[wasm-bindgen]` macro causes everything to succeed. Packages can be built succesfully, imported into Node, and used normally. Only tests break

Failures produce the following error message (stack information has been trimmed):

```
$ wasm-pack test --node

panicked at 'exception thrown while creating a test: Error: recursive use of an object detected which would lead to unsafe aliasing in rust
```

**Comment by alexcrichton** [comment]
Oh dear what a bizarre bug! Should be fixed in https://github.com/rustwasm/wasm-bindgen/pull/2123 though, thanks for the report!
