### ISSUE TITLE
How should imports in js modules be handled?

### ISSUE THREAD

**Issue by allsey87** [rustwasm/wasm-bindgen#2132]
I am working on creating Rust bindings for the [three.js](https://threejs.org/) graphics library. I have checked out the js library as a submodule as part my repository [threejs-sys](https://github.com/allsey87/threejs-sys/). Now, in this js library there are several js modules that reference each other. For this example, one of the lowest level classes called [`Object3D`](https://github.com/mrdoob/three.js/blob/r116/src/core/Object3D.js) depends on several other classes via import statements (mostly math classes like vectors, quaternions etc). I would have thought that since these import statements exist, these modules would have been included in `pkg/snippets/CRATE-xyz/` alongside `Object3D.js` when I build with `wasm-pack`.

However, when I build my [testbench](https://github.com/allsey87/threejs-sys-testbench/blob/modules/src/lib.rs), I find that only `Object3D.js` gets pulled into the build and everything that it imports is left behind leaving dangling references to the other modules.

Is this a bug or am I doing something wrong here?

**Comment by alexcrichton** [comment]
Currently transitive imports in included snippets to other snippets is not supported. The intention is that you'd list code as depending on the npm module directly, and then an ambient bundler/runtime would get the npm dependency working.
