### ISSUE TITLE
I don't know how can import external js libraries since I cannot use parcel-plugin-wasm.rs 

### ISSUE THREAD

**Issue by dancespiele** [rustwasm/wasm-bindgen#2134]
### Summary

How can I import third part js libraries with wasm-pack. The previous version with parcel-plugin-wasm.rs there wasn't any issue in that, you can see here https://github.com/spielrs/yew_prism/blob/master/crate/yew_prism/src/prism_sys.rs , and now that I cannot use it anymore I don't know how can import third part js libraries to be used in wasm-bindgen, I try several things but always I get TypeError: Error resolving module specifier: prismjs

**Comment by alexcrichton** [comment]
What you've written down is how to import external libraries, so this is likely a concern of your bundler or bundler configuration. Additionally you may need to be sure the dependency is listed in `package.json`.

**Comment by dancespiele** [comment]
Yes I was figure out about this and I found some alternative. Thanks anyway
