### ISSUE TITLE
wasm-bindgen dynamic linking

### ISSUE THREAD

**Issue by notdanilo** [rustwasm/wasm-bindgen#2137]
### Summary

Does wasm-bindgen support dynamic linking? Where can I find the guidelines to do it?

### Additional Details

I am planning to create plugins for my project. I tried to find some examples of usages of wasm-bindgen with dynamic linking, but I couldn't find anything.

I know wasm-bindgen creates an object registry on JavaScript side so we can retrieve JsValue, but each .wasm file has its own .js glue.

With some quick research, I realized WebAssembly does support dynamic linking, but keeping this glue mechanism in mind, it made me wonder what would be the implications of passing objects between two different modules.

**Comment by alexcrichton** [comment]
Currently wasm-bindgen doesn't have support for this but that's largely becuase rustc itself doesn't have a great amount of support for dynamic linking and wasm. I think that upstream toolchain work needs to happen independent of wasm-bindgen, so I'm going to close this.

**Comment by Pauan** [comment]
@notdanilo It's quite rare for a Wasm module to dynamically link with another Wasm module. What's your use case?

**Comment by notdanilo** [comment]
@Pauan our use case is:

We want to create visualisations as plugins (so the end-user can create custom ones), but we also want to make our rendering functions available for the plugin developers.

**Comment by alun** [comment]
I believe dynamic loading of dynamic modules is quite common on FE so to make sure a user only loads whatever they actually going to use.

Would be really nice to be able to build Rust/WASM UIs in this way.
