### ISSUE TITLE
support include!("library.rs") in extern

### ISSUE THREAD

**Issue by ctaggart** [rustwasm/wasm-bindgen#2138]
### Motivation

I'm generating bindings for a library, but they are not perfect and I need to add some manual definitions. I do not want to edit the generated file.

### Proposed Solution

``` rust
#[wasm_bindgen(module = "mylibrary")]
extern "C" {
    include!("mylibrary_generated.rs");
}
```

### Alternatives

Allow the module to be split up in more than one `extern`. This doesn't work today:

```
#[wasm_bindgen(module = "mylibrary")]
extern "C" {
}

#[wasm_bindgen(module = "mylibrary")]
extern "C" {
}
```

Another alternative is for me to add the `include!` type functionality to my generator, but I prefer the above solutions.

**Comment by alexcrichton** [comment]
Implementing this would unfortunately be somewhat nontrivial, it's basically interpreting a rustc-builtin macro. Can you say more, though, as to why the second form doens't work?

**Comment by ctaggart** [comment]
Upon further review, the alternative is working just fine. I thought it was causing an error, but I just tried a simpler example and no error.
