### ISSUE TITLE
implement OptionIntoWasmAbi for JsValue

### ISSUE THREAD

**Issue by ctaggart** [rustwasm/wasm-bindgen#2139]
### Motivation

On several occasions, I've want to map a parameter as `Option<&JsValue>` or a return type as `Option<JsValue>`, just to indicate explicitly that it is optional. I realize JsValue supports null & undefined. 

### Proposed Solution

Implement the trait.

### Alternatives

I think of `JsValue` as the TypeScript `any` type. TypeScript also has the [non-primitive object type](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#general-types) that does not support null or undefined, but everything else. May be it would be better to add that so it makes more sense to have a `Options<JsSome>` or something like that.

**Comment by alexcrichton** [comment]
The reason we haven't implemented this is that there's no way to distinguish between `Some(null)` and `None` in JS, so there's no way to losslessly represent the value in JS. We've currently been requiring that Rust opts-in to `.unwrap_or(...)` or something like that.

**Comment by ctaggart** [comment]
Okay, I may revisit this again in the future with more concrete examples, after I ship the generator.
