### ISSUE TITLE
Can't use question mark operator instead of unwrap on JSValues

### ISSUE THREAD

**Issue by typon** [rustwasm/wasm-bindgen#2143]
To avoid using un-wrap i'm using `?` operator on JSValue types. I can't seem to get it to work.
I get the following error:

```
error[E0277]: `?` couldn't convert the error to `wasm_bindgen::JsValue`
  --> src/lib.rs:27:31
   |
27 |     canvas.set_height(window()?.inner_height().unwrap().as_f64().unwrap() as u32);
   |                               ^ the trait `std::convert::From<std::option::NoneError>` is not implemented for `wasm_bindgen::JsValue`
```

Is this expected behaviour?

**Comment by ctaggart** [comment]
See #1742

**Comment by Pauan** [comment]
@typon Yes this is expected, because `window()` returns an `Option`, not a `Result`. You can't mix `Option` and `Result` when using `?`, you have to use one or the other.
