### ISSUE TITLE
OOB WASM memory read after refactoring Rust library dependency

### ISSUE THREAD

**Issue by str4d** [rustwasm/wasm-bindgen#2152]
### Describe the Bug

After refactoring a library, my WASM webapp is crashing with an out-of-bounds WASM memory read in an enum that was not part of the refactor.

### Environment

- wasm-bindgen 6ba8c6c2ecf4b6969d1118fc263038188db556a2 (pinned in the branch below)
- Windows 10, WSL 2 running Ubuntu 18.04
- rustc 1.43.1
- wasm-pack 0.9.1
- Firefox 76.0.1

### Steps to Reproduce

1. Check out https://github.com/str4d/wage/tree/wasm-memory-oob-bug
2. Build and run the webapp:
    ```
    wasm-pack build --dev
    cd www
    npm install
    npm run serve
    ```
3. Download [test.age.txt](https://github.com/rustwasm/wasm-bindgen/files/4674505/test.age.txt) and rename it to `test.age`.
4. Open http://localhost:8080/
5. Drag-and-drop or click-and-select `test.age`.
6. Type in the passphrase `foobar`.
7. Click "Decrypt".

### Expected Behavior

After several seconds (having compiled with `--dev`, it could take up to 30 seconds), the "Decrypt" button changes to a "Download" button.

### Actual Behavior

`RuntimeError: index out of bounds` is printed in the console.

### Additional Context

No backtrace is printed for this failure, but enabling "Pause on exceptions" in the Firefox debugger identified the following WASM as the source of the crash:
```
    get_local $var2
    i32.store offset=24
    get_local $var2
--> i32.load8_u
```
At this point, `$var2` is a value much larger than the size of the WASM linear memory.

The WASM is part of a closure, and I believe it is part of [this `if let Enum::Case(s) = r` line](https://github.com/str4d/rage/blob/110994d6d1e8539e18a23da85647ec746a59bbe0/age/src/protocol/decryptor.rs#L179) for the following reasons:
- The OOB crash occurs if I place a `panic!("{:?}", r)` inside the closure right before the line in question.
- If I instead place a `panic!("Panic here")` inside the closure right before the line in question, I get a regular panic with the expected backtrace.
- The OOB crash occurs if I place `panic`s at the start of both sides of the conditional (neither explicit panic is triggered).

This suggests that the crash is related to destructuring the enum, which is defined [here](https://github.com/str4d/rage/blob/110994d6d1e8539e18a23da85647ec746a59bbe0/age/src/format.rs#L26-L34). The [largest enum case is 68 bytes](https://github.com/str4d/rage/blob/110994d6d1e8539e18a23da85647ec746a59bbe0/age/src/format/ssh_ed25519.rs#L28-L32), and the [case being destructured is 49 bytes](https://github.com/str4d/rage/blob/110994d6d1e8539e18a23da85647ec746a59bbe0/age/src/format/scrypt.rs#L58-L63).

The crash started occuring after I refactored my `age` crate. If you check out the second-to-last commit of the `wasm-memory-oob-bug` branch (which pins the revision of `age` I was using before the refactor), the crash does not occur (and the expected behaviour is seen). The [diff between the two `age` revisions](https://github.com/str4d/rage/compare/103ea61c43b09060fe000bc6bbfb1dabcb249849...110994d6d1e8539e18a23da85647ec746a59bbe0) shows no changes related to the enum (note that GitHub's UI shows the diff between their common parent and the refactored commit; use `git diff` to see the exact differences).

**Comment by alexcrichton** [comment]
Thanks for the report! This is pretty unlikely to be the fault of wasm-bindgen. Have you tried running wasm-bindgen in debug mode with extra asserts in place? Additionally are you sure that the rust application doesn't itself contain any unsafe code which may cause this?

**Comment by str4d** [comment]
> This is pretty unlikely to be the fault of wasm-bindgen.

I suspected as much, but I was asked in the `wg-wasm` Discord channel to open the issue here. I'm happy to move it elsewhere if there's a more likely candidate.

> Have you tried running wasm-bindgen in debug mode with extra asserts in place?

How can I enable more `wasm-bindgen` assertions beyond using `wasm-pack build --dev`?

> Additionally are you sure that the rust application doesn't itself contain any unsafe code which may cause this?

There's no unsafe code in the library that I refactored. There is unsafe code in various (standard) dependencies, but nothing that I could think is involved in this part of the parsing code.

**Comment by alexcrichton** [comment]
It's pretty difficult to make progress on this given how much code is involved. If possible it would be great to reduce this to the bare minimum of code needed. That will also help out rule out bugs in libraries vs bugs in wasm-bindgen.

If you're using `--dev` I think you should have all the assertions necessary, although I could be wrong on that...

**Comment by str4d** [comment]
I'll spend some time later this week deleting code to try and create a reduced example.

**Comment by str4d** [comment]
I've pushed a commit to https://github.com/str4d/wage/tree/wasm-memory-oob-bug that pins the webapp to the current top commit of https://github.com/str4d/rage/tree/wasm-memory-oob-bug-test-case, in which I've deleted all code that either isn't part of the bug or was used after the point at which the bug occurs. In particular, almost all the code that was refactored has been deleted, and the OOB bug is still reproducible.

Next I'll try refactoring the code on the critical path, to see if I can create an even more minimal example.

**Comment by str4d** [comment]
In the process of making an even more minimal example, I discovered the (in hindsight rather obvious) cause of the OOB read. The top commit of the `wasm-memory-oob-bug` branch pins the age revision with the fix.

The problem was that the `Decryptor` type under the hood was storing a struct with two fields:
```rust
{
    inner: R,
    header: Header,
}
```

The type `R` is instantiated as `wage::shim::StreamReader<'a>` in this webapp, which is a wrapper around `wasm_streams::readable::IntoStream<'a>` that implements `AsyncRead`. The fixed revision of age swaps the order of `inner` and `header` inside `Decryptor`, which is sufficient to allow `header` to be read correctly.

This then led me out of the rabbit hole to the actual cause of the error: after the refactor, the type of my `Decryptor` changed from `Decryptor<BufReader<R>>` to `Decryptor<R>`, but I was losing that type information when passing over to JavaScript, and was incorrectly casting to the original inside the webapp. Fixing that cast (by removing the `BufReader`) fixes the problem!

I have a separate question about how we could handle this use-case better (where we have a JavaScript ReadableStream, have obtained a Reader for it, and want to store that Reader in a Rust object that we pass back to JavaScript, given that `wasm-bindgen` does not support passing objects with exposed lifetimes from Rust to JavaScript), but this particular issue is resolved :smile:
