### ISSUE TITLE
Typescript enum definitions are not used in function signatures

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [rustwasm/wasm-bindgen#2154]
### To reproduce

1. Run `wasm-bindgen --target web` on the wasm generated from the following library:
    ```rust
    use wasm_bindgen::prelude::*;

    #[wasm_bindgen]
    pub enum Hand {
        Left = 0,
        Righ = 1,
    }

    #[wasm_bindgen]
    pub fn f(h: Hand) -> Hand { h }
    ```
2. Inspect generated .d.ts

### Expected result

```typescript
export enum Hand {
  Left,
  Righ,
}

export function f(h: Hand): Hand;
```

### Actual result

```typescript
export enum Hand {
  Left,
  Righ,
}

export function f(h: number): number;
```

### Version info

wasm-bindgen 0.2.62

**Comment by alexcrichton** [comment]
I unfortunately don't have the time to implement a new feature like this, but a PR would be much appreciated!

**Comment by ChristianIvicevic** [comment]
> I unfortunately don't have the time to implement a new feature like this, but a PR would be much appreciated!

The requested feature is really nice to have but the PR opened 3.5 years ago is stale. What are the chances that you pick up the work on this feature? Sadly I can't personally contribute myself.

**Comment by daxpedda** [comment]
I'm not aware of any current maintainer wanting to implement this.
But I'm happy to review a potential PR.

**Comment by ChristianIvicevic** [comment]
@daxpedda I just opened a PR that is ready to be reviewed :)
