### ISSUE TITLE
Method not found `observe_with_options` in `web_sys::features::gen_MutationObserver::MutationObserver`

### ISSUE THREAD

**Issue by atifsaddique211f** [rustwasm/wasm-bindgen#2166]
### Describe the Bug

Method not found `observe_with_options` in `MutationObserver`
According to docs, it should be available.
https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.MutationObserver.html?search=#method.observe_with_options

### Steps to Reproduce

Create a Mutation observer and try to call `observe_with_options` on it.

<img width="1593" alt="Screenshot 2020-05-28 at 16 51 37" src="https://user-images.githubusercontent.com/8865972/83157103-81a0e300-a103-11ea-89d1-b2d4b4288937.png">

**Comment by Pauan** [comment]
As the docs say, you need to enable the following features: `MutationObserver`, `MutationObserverInit`, and `Node`.

**Comment by atifsaddique211f** [comment]
```
    let cb = Closure::wrap(Box::new(|mutations: Object| {
        web_sys::console::log_2(&"mutation data".into(), &mutations);
    }) as Box<FnMut(_)>);
    // let observer = MutationObserver::new(cb.as_ref().unchecked_ref());
    let observer: MutationObserver = MutationObserver::new(
        cb.as_ref().unchecked_ref()
    ).ok().unwrap().into();

    // Starts the monitoring
    let node: Node = document.document_element().unwrap().parent_node().unwrap();
    let options: MutationObserverInit = MutationObserverInit::new().child_list(true).subtree(true);
    observer.observe_with_options(
        &node,
        &options
    );
```

I am passing all those options
