### ISSUE TITLE
Incorrect package.json generated

### ISSUE THREAD

**Issue by rllola** [rustwasm/wasm-bindgen#2170]
### Describe the Bug

I believe the package.json generated is missing a file in `files` when the target is `browser`.

### Expected Behavior

I expect to have a `filecoin_signer_wasm_bg.js`
```
 "files": [
    "filecoin_signer_wasm_bg.wasm",
    "filecoin_signer_wasm.js",
    "filecoin_signer_wasm_bg.js"
  ],
```

### Actual Behavior

What I actually have 
```
  "files": [
    "filecoin_signer_wasm_bg.wasm",
    "filecoin_signer_wasm.js"
  ],
```

### Additional Context

Then when publising to npm I am missing this file.

**Comment by alexcrichton** [comment]
Thanks for the report! I don't think this is in the `package.json` generated by `wasm-bindgen`, but instead I believe this is an issue with `wasm-pack`. Mind filing an issue over there for this?

**Comment by rllola** [comment]
My bad. It was indeed meant for `wasm-pack`. Here the new issue in the correct repo https://github.com/rustwasm/wasm-pack/issues/854
