### ISSUE TITLE
raytrace-parallel example does not compile (passive-segments)

### ISSUE THREAD

**Issue by beltegeuse** [rustwasm/wasm-bindgen#2175]
### Describe the Bug

The example raytrace-parallel does not compile.

### Steps to Reproduce

1. `git clone https://github.com/rustwasm/wasm-bindgen.git`
2. `cd wasm-bindgen/examples/raytrace-parallel`
3. `sh build.sh`
4. Got the error `note: rust-lld: error: unknown argument: --passive-segments`

### Expected Behavior

The code should compile. I played with this example last Sunday, and the code was compiling and running correctly.

### Actual Behavior

The code currently does not compile with rust nightly (May 31th).

### Additional Context

Note that, removing `RUSTFLAGS='-C target-feature=+atomics,+bulk-memory'` fix the compilation problem. However, this provokes a runtime error (due to missing feature), which, I think, is expected.

**Comment by alexcrichton** [comment]
Thanks for the report! Looks like LLD changed when upgrading to LLVM 10. Some work needs to happen to update to the new output of LLD, and that'll take some time for me to implement unfortunately.
