### ISSUE TITLE
without-a-bundler-no-modules example does not build

### ISSUE THREAD

**Issue by j-devel** [rustwasm/wasm-bindgen#2179]
### Describe the Bug

The `without-a-bundler-no-modules` example does not build.

### Steps to Reproduce

1. `git clone https://github.com/rustwasm/wasm-bindgen`
2. `cd wasm-bindgen/examples/without-a-bundler-no-modules/`
3. `wasm-pack build --target no-modules`
4. See the error below.

### Expected Behavior

Build finishes without errors.

### Actual Behavior

Build fails leaving an error (using rustc 1.45.0-nightly (a74d1862d 2020-05-14)):

```
thread 'main' panicked at 'internal error: entered unreachable code', crates/cli-support/src/decode.rs:157:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: Running the wasm-bindgen CLI
Caused by: failed to execute `wasm-bindgen`: exited with exit code: 101
```

### Additional Context

It seems like a regression after merging https://github.com/rustwasm/wasm-bindgen/pull/2105
The same build works before the merge.

**Comment by wattux** [comment]
hey there. We ran into the same thing yesterday [here](https://github.com/rustwasm/wasm-bindgen/issues/2177). Turns out you have to copy the example's folder (in your case `without-a-bundler-no-modules`) somewhere out of the wasm-bindgen repo

**Comment by alexcrichton** [comment]
Indeed yes I believe this is the same issue, closing in favor of that.

**Comment by j-devel** [comment]
Confirmed! Thanks for pointing it out @wattux
