### ISSUE TITLE
Error in Safari when loading without-a-bundler-no-modules example

### ISSUE THREAD

**Issue by j-devel** [rustwasm/wasm-bindgen#2182]
### Describe the Bug

We see an error in Safari when loading the `without-a-bundler-no-modules` example.

### Steps to Reproduce

1. `git clone https://github.com/rustwasm/wasm-bindgen`
2. `cp -r wasm-bindgen/examples/without-a-bundler-no-modules .`
3. `cd without-a-bundler-no-modules`
4. `wasm-pack build --target no-modules`
5. Statically serve the `without-a-bundler-no-modules` directory and visit *index.html* using Safari.

### Actual Behavior

The example doesn't load leaving an error in the developer console:

```
ReferenceError: Can't find variable: wasm_bindgen
```

![Screen Shot 2020-06-03 at 17 27 29](https://user-images.githubusercontent.com/38098238/83626580-d4751180-a5bf-11ea-8b9e-91b1334070eb.png)

### Analysis

By loading generated *pkg/without_a_bundler_no_modules.js*:
```js
let wasm_bindgen;
...
```
`wasm_bindgen` is expected to be globally exported, which works fine in Chrome/Firefox, but not in Safari. In case of Safari, the scoping behavior seems different; the `let` variable becomes scoped in the `<script>` block (a relevant case [here](https://stackoverflow.com/questions/57147321/const-let-with-another-script-type-module-block-is-undefined)).

As a workaround, should we update *crates/cli-support/src/js/mod.rs* so that it generates JS like the following instead?
```js
var wasm_bindgen;
...
```

**Comment by alexcrichton** [comment]
Thanks for the report! This is a copy-paste typo where `type=module` isn't supposed to be there.
