### ISSUE TITLE
Mismatch in shared state of memory, declared = 0, imported = 1

### ISSUE THREAD

**Issue by ccartas** [rustwasm/wasm-bindgen#2190]
I'm trying to instantiate a wasm module across multiple web workers using SharedArrayBuffer.
I've managed to find the way to pass the Webassembly.Memory object to the init function but now I get this error and I'm stuck.
```
Uncaught (in promise) LinkError: WebAssembly.instantiate(): mismatch in shared state of memory, declared = 0, imported = 1
```

Any help is much appreciated!

**Comment by ccartas** [comment]
I guess i've fixed it by setting correct link args. Now I'm encountering another problem.
```
[target.wasm32-unknown-unknown]
rustflags = [
    "-C", "target-feature=+atomics,+bulk-memory",
    "-C", "link-args=--no-entry --shared-memory --import-memory --max-memory=2130706432",
]
```
Getting this error:
```
wasm-bindgen target/wasm32-unknown-unknown/release/wmap.wasm --out-dir ./dist --no-modules --no-typescript
error: wasm-bindgen is currently incompatible with modules that already have a start function
```

**Comment by Ngalstyan4** [comment]
I had the same error and I think it was because `wasm-bindgen-cli` and `wasm-bindgen` used by the project had different versions. `wasm-pack` can help to avoid that since it checks the version of `wasm-bindgen` and downloads `wasm-pack-cli` that has exactly same version.

**Comment by alexcrichton** [comment]
I think this was fixed very recently in https://github.com/rustwasm/wasm-bindgen/pull/2183, can y'all try that and see if it fixes things?

**Comment by Ngalstyan4** [comment]
I get the error when using version 0.2.63 in crates.io but manage to compile the same program successfully when using the git HEAD so it probably is fixed.

**Comment by ccartas** [comment]
Thanks a lot @alexcrichton and @Ngalstyan4 .
I've managed to make it work by using the git HEAD, so I can confirm that this is fixed.
