### ISSUE TITLE
wasm-bindgen panic with wasm-bindgen-futures on master

### ISSUE THREAD

**Issue by Perseus101** [rustwasm/wasm-bindgen#2192]
### Describe the Bug

When running `wasm-pack` using the latest master with wasm-bindgen and wasm-bindgen-futures, `wasm-pack` reports the following error: 
```
thread 'main' panicked at 'internal error: entered unreachable code', crates/cli-support/src/decode.rs:157:1
```

### Steps to Reproduce

1. `wasm-pack new <name>`
2. Change dependencies to use the latest master for wasm-bindgen and add wasm-bingen-futures
3. `wasm-pack build`

Repo link: https://github.com/Perseus101/wasm-pack-bug

### Expected Behavior

`wasm-pack` should build the repository successfully.

### Actual Behavior

`wasm-pack` produces the error shown above.

### Additional Context

The error only appears after adding wasm-bindgen-futures to the repository. I'm not sure what the underlying cause is, but there is no error with only wasm-bindgen.

**Comment by Perseus101** [comment]
I ran a git bisect locally, it indicates that this was introduced in commit  87663c6d2a442d98b3d8ea6242f20c5c21fc0174

**Comment by Perseus101** [comment]
I've added branches to the linked repository with the last passing and first failing commit of wasm-bindgen:

https://github.com/Perseus101/wasm-pack-bug/tree/first-failing-commit
https://github.com/Perseus101/wasm-pack-bug/tree/last-working-commit

**Comment by alexcrichton** [comment]
Thanks for the report! This is an instance of https://github.com/rustwasm/wasm-bindgen/issues/1227, however. A git version of wasm-bindgen can't be used with wasm-pack.
