### ISSUE TITLE
[asynchronous-tests.md] Typo in code snippet causing compilation error

### ISSUE THREAD

**Issue by spudmashmedia** [rustwasm/wasm-bindgen#2199]
### Describe the Bug

Compilation error with code snippet, extra trailing colon.

### Steps to Reproduce
See https://rustwasm.github.io/docs/wasm-bindgen/wasm-bindgen-test/asynchronous-tests.html, ln 22

### Expected Behavior
Currently:

```
    // Convert that promise into a future and make the test wait on it.
    let x = JsFuture::from(promise).await.unwrap();:
```

Should be:

```
    // Convert that promise into a future and make the test wait on it.
    let x = JsFuture::from(promise).await.unwrap();
```

### PR
https://github.com/rustwasm/wasm-bindgen/pull/2198

**Comment by alexcrichton** [comment]
Addressed in https://github.com/rustwasm/wasm-bindgen/pull/2198
