### ISSUE TITLE
ImageCapture API is not consistent with MDN

### ISSUE THREAD

**Issue by lwansbrough** [rustwasm/wasm-bindgen#2202]
### Describe the Bug

https://github.com/rustwasm/wasm-bindgen/blob/master/crates/web-sys/webidls/enabled/ImageCapture.webidl

The WebIDL file for the ImageCapture API description provided by MDN (here: https://developer.mozilla.org/en-US/docs/Web/API/ImageCapture/takePhoto) is outdated/incorrect.

Specifically: `takePhoto` is a `Promise<Blob>`. The Rust wasm bindings provide the following method signature: `pub fn take_photo(&self) -> Result<(), JsValue>` as well as a number of non-standard (old/deprecated?) events.

### Expected Behavior

take_photo() returns a Promise which resolves a blob.

### Actual Behavior

ImageCapture API is unusable as there is no way to retrieve the Blob.

**Comment by JAicewizard** [comment]
Shouldnt this one be closed now?

**Comment by alexcrichton** [comment]
Indeed!
