### ISSUE TITLE
[Question] Run example of fetch failed.

### ISSUE THREAD

**Issue by liangyuanpeng** [rustwasm/wasm-bindgen#2205]
### Summary

Run example of fetch failed.

```
[root@normal11 fetch]# npm run serve

> @ serve /root/wasm-bindgen/examples/fetch
> webpack-dev-server

ð§  Checking for wasm-pack...

✅  wasm-pack is installed.

ℹ️  Compiling your crate in development mode...

✖ ｢wdm｣: TypeError: Cannot read property 'stat' of undefined
    at WasmPackPlugin._compile (/root/wasm-bindgen/examples/fetch/node_modules/@wasm-tool/wasm-pack-plugin/plugin.js:120:24)
    at _checkWasmPack.then (/root/wasm-bindgen/examples/fetch/node_modules/@wasm-tool/wasm-pack-plugin/plugin.js:66:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
    at Function.Module.runMain (module.js:692:11)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /root/wasm-bindgen/examples/fetch
```

### Additional Details

Provide any additional details here.

**Comment by alexcrichton** [comment]
Thanks for the report, but this looks like it's a problem with wasm-pack/webpack/etc, not wasm-bindgen. If this ends up being a bug in wasm-bindgen, though, please feel free to open here!

**Comment by lucamoller** [comment]
I was running into this exact same issue. In my case the problem was that I was using an old version of node (installed through apt-get), which apparently didn't support the fs.promises API yet.

It got fixed when I upgraded to the latest version:
https://askubuntu.com/questions/426750/how-can-i-update-my-nodejs-to-the-latest-version
