### ISSUE TITLE
Support defining getters in Rust

### ISSUE THREAD

**Issue by alexcrichton** [rustwasm/wasm-bindgen#222]
Currently when you export a struct in Rust to JS it only exports public methods, but we should enable the ability to define getters and setters for properties too, for example:

```rust
#[wasm_bindgen]
struct Foo { /* ... */ }

#[wasm_bindgen]
impl Foo {
    pub fn new() -> Foo { ... }

    #[wasm_bindgen(getter)]
    pub fn field1(&self) -> u32 { ... }
    #[wasm_bindgen(setter)]
    pub fn set_field1(&mut self, f: u32) { ... }

    #[wasm_bindgen(getter = anotherName)]
    pub fn another_name(&self) { ... }
    #[wasm_bindgen(setter = anotherName)]
    pub fn set_another_name(&mut self, param: u32) { ... }
}
```

**Comment by dtysky** [comment]
Any updating?

**Comment by alexcrichton** [comment]
None yet, but would still be great to implement!

**Comment by c410-f3r** [comment]
I will work on it. Any tips for this issue, @alexcrichton ?

**Comment by alexcrichton** [comment]
Sure! I think a rough set of steps for implementing this would be:

1. Update the [shared definition](https://github.com/rustwasm/wasm-bindgen/blob/b670ea44d029b455e71245b94fb532b90df17fd8/crates/shared/src/lib.rs#L89-L97) of `Export` between the macro and the CLI. We probably want to delete the `is_constructor` field and instead include `kind: MethodKind<'a>`. 
2. Next we'll need to update the macro codegen to produce this. An `Export` is [produced here](https://github.com/rustwasm/wasm-bindgen/blob/b670ea44d029b455e71245b94fb532b90df17fd8/crates/backend/src/encode.rs#L174-L190). 
3. That'll require updating `ast::Export` [defined here](https://github.com/rustwasm/wasm-bindgen/blob/b670ea44d029b455e71245b94fb532b90df17fd8/crates/backend/src/ast.rs#L32-L55). How that's represented internally I'm not sure, but adding some more booleans is fine.
4. Instances of `ast::Export` are [parsed and constructed here](https://github.com/rustwasm/wasm-bindgen/blob/b670ea44d029b455e71245b94fb532b90df17fd8/crates/macro-support/src/parser.rs#L907-L956) which is where you'd add the attribute parsing code. You'd modify [this macro](https://github.com/rustwasm/wasm-bindgen/blob/b670ea44d029b455e71245b94fb532b90df17fd8/crates/macro-support/src/parser.rs#L27-L55) to parse the new attributes.
5. After all that's working you'd need to update the CLI. You'll naturally get compile errors for generating information since the structure of `shared::Export` changed. I think for this you'd basically follow the rabbit hole of compiler errors and once they're all ironed out in theory it's a working implementation

If you've got any questions though let me know!

**Comment by c410-f3r** [comment]
@alexcrichton Oh, this is plenty. Thanks!
