### ISSUE TITLE
Wasm Threads + Memory Growth

### ISSUE THREAD

**Issue by DzmitryFil** [rustwasm/wasm-bindgen#2222]
Currently there is no memory allocator for wasm that can use preallocated memory, so memory should grow. However, memory growth invalidates any pointers from js shim to wasm memory.
https://github.com/WebAssembly/design/issues/1271
emscripten workaround https://github.com/emscripten-core/emscripten/pull/8365
How can wasm-bindgen be safely used with atomics at this point, when even basic stuff like getStringFromWasm can break at any moment?

**Comment by alexcrichton** [comment]
Thanks for the report! With a shared memory, however, you're guaranteed that the base pointer will never change (for exactly this reason). This is why shared memories have required maximum size basically.

You're guaranteed, with shared memory, what once you get the `.buffer` from the `WebAssembly.Memory` it'll always be valid.

**Comment by DzmitryFil** [comment]
Oh, my bad, i misunderstood the problem. Thanks for clarification!
