### ISSUE TITLE
raytrace-parallel demo panics in chrome-based browsers

### ISSUE THREAD

**Issue by DzmitryFil** [rustwasm/wasm-bindgen#2223]
When low concurrency number is chosen (like 2 or 3) demo works most of the time, but then the higher the number the more likely it is to crash. It never works with 10+ workers for me. Demo panics with 'RuntimeError: memory access out of bounds 'and bunch of other errors, it should be no problem to reproduce the issue.

**Comment by alexcrichton** [comment]
What version of Chrome are you using? As of about a month or so ago I heard you needed to use the latest canary (at that time) since there were internal bugs in Chrome. I'm not sure about the progress of those.

**Comment by DzmitryFil** [comment]
Bug is reproducible in Chrome 83.0.4103.116. I just tried to run the demo in Canary Chrome version 86.0.4194.1, and it works perfectly! Thanks for the suggestion, it seems like it really is internal Chrome bug.

**Comment by DzmitryFil** [comment]
@alexcrichton sorry to bother you again, but maybe you could speculate about the reason for such behaviour? I can't seem to find related issues in chromium bug-tracker.

**Comment by DzmitryFil** [comment]
the Chromium issue if anyone else is going to stumble upon this
https://bugs.chromium.org/p/chromium/issues/detail?id=1067621&q=component%3ABlink>JavaScript>WebAssembly%20atomics&can=1
https://chromium.googlesource.com/v8/v8.git/+/401190baf0a0e53de2eaa48edd21a877aa710dd9
