### ISSUE TITLE
How to use shared memory between wasm and js?

### ISSUE THREAD

**Issue by mantou132** [rustwasm/wasm-bindgen#2225]
### Summary

How to use shared memory between wasm and js?

### Additional Details

For example, I get the image data from the camera on the js side, and then process the picture in wasm, but at present, I need to copy the memory, i can use [SharedArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer) in wasm and js?

**Comment by richwandell** [comment]
@mantou132 did you find a good solution?

**Comment by chinedufn** [comment]
`SharedArrayBuffer` is available in js_sys https://docs.rs/js-sys/0.3.42/js_sys/struct.SharedArrayBuffer.html

You can also have a look at the multi-threading threading example since that's somewhat related, depending on what you are trying to do https://rustwasm.github.io/docs/wasm-bindgen/examples/raytrace.html

**Comment by dc740** [comment]
The only working example I could find is this crate implementation
https://github.com/wasm-rs/shared-channel

Everything else I could find mentions SharedArrayBuffer and never really uses it.

**Comment by richwandell** [comment]
I was able to get this working and made a demo project. You can dig through the code here. https://github.com/richwandell/rust_wasm_webcam

**Comment by Ciantic** [comment]
I found out you can share whole memory between workers, e.g.

index.js
```javascript
import init from "./ratas_wasm.js";
const stuff = await init();
// this is the WebAssembly.Memory, which defaults to shared
const mem = stuff.__wbindgen_export_0; 
// This 

// Create some workers:
const w1 = new Worker("./worker.js", {
    type: "module",
});
const w2 = new Worker("./worker.js", {
    type: "module",
});

// Post the shared memory to workers:
w1.postMessage({ task: "init", mem: mem });
w2.postMessage({ task: "init", mem: mem });
```

worker.js
```javascript
import init from "./ratas_wasm.js";

onmessage = async function (m) {
    if (m.data.task === "init") {
        await init(undefined, m.data.mem);
    }
    
};
```

This way you can even share a HashMap (within once_cell::Lazy) between workers just easily :)

**Comment by qdwang** [comment]
@Ciantic This method won't work now. There is a `memory` object under `wasm`(stuff in your code), it's unshared. And there is no `__wbindgen_export_0 ` now. 

Don't know what to do to set a shared webassembly memory.

**Comment by pferreir** [comment]
I tried a similar approach and indeed you don't seem to be able to send the memory object to the worker because it cannot be cloned?

**Comment by Liamolucko** [comment]
You need to pass `-Ctarget-feature=+atomics` to rustc to enable shared memory, plus some other flags. See https://github.com/rustwasm/wasm-bindgen/blob/main/examples/raytrace-parallel/build.sh for more details.
