### ISSUE TITLE
Imports for wasm-in-wasm

### ISSUE THREAD

**Issue by Perseus101** [rustwasm/wasm-bindgen#2226]
### Summary

The current [wasm-in-wasm example](https://rustwasm.github.io/wasm-bindgen/examples/wasm-in-wasm.html
) creates and instantiates a WebAssembly module using this call: `WebAssembly::instantiate_buffer(WASM, &Object::new())`. From the [docs](https://rustwasm.github.io/wasm-bindgen/api/js_sys/WebAssembly/fn.instantiate_buffer.html), the second argument is the imports object for the WebAssembly module. The example just uses and empty object, and it isn't immediately clear how to create actual imports for the WebAssembly module.

### Additional Details

I've taken a stab at implementing this here, but I'm running into a bug I can't track down. I'm not sure if my approach is wrong, or if there is just something I'm misunderstanding:
https://github.com/Perseus101/wasm-bindgen/tree/wasm-imports-example/examples/wasm-in-wasm-imports

**Comment by alexcrichton** [comment]
Unfortunately when you provide a JS function as an input to the import object whenever it's invoked the `this` parameter is always `null`. You'd need to use `.bind` somehow if you'd like to set the `this` parameter for later usage.

There's probably not a super ergonomic way to do this in Rust right now, you'll likely need some gnarly-ish JS glue.

**Comment by Perseus101** [comment]
Thanks, that was the insight I was missing! It wasn't too hard to get it working with some judicious use of `Reflect`. The link above should be a working example now.

On another note, do you think it is worth merging this example upstream? I know this would have been useful to me, but it is a pretty niche example. Let me know, I'll open a PR if you think it's worth it.

**Comment by alexcrichton** [comment]
Nice! Seems reasonable to me to add :)
