### ISSUE TITLE
use of undeclared type or module `js_sys`

### ISSUE THREAD

**Issue by helabenkhalfallah** [rustwasm/wasm-bindgen#2228]
### Describe the Bug

I get 'use of undeclared type or module `js_sys`' when I try to use crate.

![image](https://user-images.githubusercontent.com/1331451/86842522-9c248f80-c0a5-11ea-9ce6-71c6124ee1cf.png)

I have used : 
https://github.com/rustwasm/rust-webpack-template
to generate my project.

It's a frontend React JS app in where I want to do some expensive tasks with rust and wasm.
I need js-sys to be able to use array (sort, map, collect, ..)

### Steps to Reproduce
This is a reproductible repository : 
https://github.com/helabenkhalfallah/rust-react-wasm-js

(npm start will build rust and node).

### Expected Behavior

Use js_sys without issue.

### Actual Behavior

I get 'use of undeclared type or module `js_sys`' when I try to use crate.

![image](https://user-images.githubusercontent.com/1331451/86843074-59af8280-c0a6-11ea-950b-fa9910861141.png)

Thank you for your help.

**Comment by alexcrichton** [comment]
Thanks for the report! You'll need to add `js-sys` to your `Cargo.toml`, however, since that's how Rust dependencies are pulled in.

**Comment by helabenkhalfallah** [comment]
It's imported 
https://github.com/helabenkhalfallah/rust-react-wasm-js/blob/master/Cargo.toml#L50

**Comment by alexcrichton** [comment]
That's under `[dev-dependencies]`, it'll need to be under `[dependencies]` for the main build.
