### ISSUE TITLE
Examples without nodejs

### ISSUE THREAD

**Issue by nhrones** [rustwasm/wasm-bindgen#2230]
### Motivation

All examples seem to require Webpack.   It would be much more efficient if we had an optional no-node example to try.

### Proposed Solution

Examples that don't require Webpack/node_modules

**Comment by alexcrichton** [comment]
Thanks for the report! We have an example of this at https://github.com/rustwasm/wasm-bindgen/tree/master/examples/without-a-bundler

**Comment by nhrones** [comment]
My apologies.  I  read the documents and this does satisfy my needs.  Thanks for quick responce, and for all your hard work.

**Comment by nhrones** [comment]
Even with the one example in the documentation, I was unable to use that information to get any other example to run without a bundler.  It is not very apparent as to how to run any other example without node/npm.

**Comment by alexcrichton** [comment]
Can you explain what you did that didn't work for the other examples? The without-a-bundler example should be basically analagous of how to run all the others.

**Comment by nhrones** [comment]
I got frustrated and gave up.  I'm working on Windows.  The last npm
command would produce an empty screen in Chrome. I kept getting errors in
the Chrome-dev-tools that indicated something not found?  I tried to run
the examples using the node webpack setup, and could not get any of them to
work.  Seemed to be the same dev-tools not found error. When I find time,
I'll try again and report back the exact errors that I get.  I'm not a fan
of node or webpack.  I do a lot of work with Rust and Deno now, and I'll
never look back.

**Comment by nhrones** [comment]
Alex, thanks for your time.  I'm getting too old for this.  I couldn't find
my way back to where I was getting stuck.  It was a canvas example?  I
started at ...
https://rustwasm.github.io/  and waded through
https://rustwasm.github.io/docs.html then on to
https://rustwasm.github.io/docs/book/.  I never found the canvas example.
I'm not even sure that I understand the relationship of all the wasm-****
and wasn-***-cli any more.  In my 50 years in the industry, I've paid the
bills writing assembly, C, C++, Java, C# . and Javascript. I love Rust and
Typescript and I'm getting pretty proficient with Rust. I'm a big fan of
Deno, But, this technology is just too immature and convoluted for me.I'll
wait a while for things to jell. Perhaps someone will write a good book
that explores the underlying technology without all the hand-holding
gigabytes of automation to get at 'hello-world'.
Thanks again.

**Comment by nhrones** [comment]
From https://rustwasm.github.io/docs/wasm-bindgen/examples/2d-canvas.html

Attempt to run `withouut a bundler`

`lib.rs`
```
use std::f64;
use wasm_bindgen::prelude::*;
use wasm_bindgen::JsCast;

#[wasm_bindgen(start)]
pub fn start() {
    let document = web_sys::window().unwrap().document().unwrap();
    let canvas = document.get_element_by_id("canvas").unwrap();
    let canvas: web_sys::HtmlCanvasElement = canvas
        .dyn_into::<web_sys::HtmlCanvasElement>()
        .map_err(|_| ())
        .unwrap();

    let context = canvas
        .get_context("2d")
        .unwrap()
        .unwrap()
        .dyn_into::<web_sys::CanvasRenderingContext2d>()
        .unwrap();

    context.begin_path();

    // Draw the outer circle.
    context
        .arc(75.0, 75.0, 50.0, 0.0, f64::consts::PI * 2.0)
        .unwrap();

    // Draw the mouth.
    context.move_to(110.0, 75.0);
    context.arc(75.0, 75.0, 35.0, 0.0, f64::consts::PI).unwrap();

    // Draw the left eye.
    context.move_to(65.0, 65.0);
    context
        .arc(60.0, 65.0, 5.0, 0.0, f64::consts::PI * 2.0)
        .unwrap();

    // Draw the right eye.
    context.move_to(95.0, 65.0);
    context
        .arc(90.0, 65.0, 5.0, 0.0, f64::consts::PI * 2.0)
        .unwrap();

    context.stroke();
}
```
`built with ...`
```
wasm-pack build --target web
```
`attempted to run in index.html`
```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>My Canvas Project</title>
</head>
<body>
    <script type="module">
        import init from './pkg/canvas.js';
        async function run() {
            await init();
        }
        run();
    </script>
</body>
</html>
```
`No display ... error found in canvas-dev-console ...`
```
canvas_bg.wasm:1 Uncaught (in promise) RuntimeError: unreachable
    at http://127.0.0.1:8000/pkg/canvas_bg.wasm:wasm-function[47]:0x4e3a
    at http://127.0.0.1:8000/pkg/canvas_bg.wasm:wasm-function[67]:0x559a
    at http://127.0.0.1:8000/pkg/canvas_bg.wasm:wasm-function[71]:0x565e
    at http://127.0.0.1:8000/pkg/canvas_bg.wasm:wasm-function[65]:0x550f
    at start (
http://127.0.0.1:8000/pkg/canvas_bg.wasm:wasm-function[28]:0x31e1)
    at init (http://127.0.0.1:8000/pkg/canvas.js:326:10)
    at async run (http://127.0.0.1:8000/:11:13)
```

**Comment by alexcrichton** [comment]
To help debug that I'd recommend using [`console_error_panic_hook`](https://crates.io/crates/console_error_panic_hook) as a dependency
