### ISSUE TITLE
The rust webassembly memory always growing?

### ISSUE THREAD

**Issue by NateLing** [rustwasm/wasm-bindgen#2241]
I don’t know how the Webassembly organization defines the memory allocation. However, from the results of my tests, the memory is always growing.

Even  I use `drop` or vec `set_len(0)`, the situation remains unchanged.

I cannot predict the memory usage of my application, in the worst case, it may swallow up the entire pc's memory?

Alternatively, I can also draw a separate area to make read and write shared buffer memory.
It is not safe under Web Worker mode, although I have not tested whether there will be problems under single thread.

What is the rust wasm community thinking about this?

**Comment by alexcrichton** [comment]
Do you think there's a bug in the memory allocator right now? Do you have an example program which you think shows buggy behavior?

**Comment by NateLing** [comment]
@alexcrichton this is not a bug, i just want to know a better way to free some memory from Webassembly linermomery, if there is a way!

**Comment by alexcrichton** [comment]
Ah ok, no worries! In that case the answer is that while applications can use a memory allocator to free and reuse memory (like how Rust uses dlmalloc by default) there is no ability to shrink a linear memory. I'm not currently aware of any wasm proposal to enable doing so as well.
