### ISSUE TITLE
Are web_sys methods auto generated?

### ISSUE THREAD

**Issue by Fallenstedt** [rustwasm/wasm-bindgen#2245]
### Summary

I'm working with mouse events for my project, and I came across a very interesting method name for `MouseEvents`. The method is called 

[`init_mouse_event_with_can_bubble_arg_and_cancelable_arg_and_view_arg_and_detail_arg_and_screen_x_arg_and_screen_y_arg_and_client_x_arg_and_client_y_arg_and_ctrl_key_arg_and_alt_key_arg_and_shift_key_arg_and_meta_key_arg_and_button_arg_and_related_target_arg`](https://docs.rs/web-sys/0.3.12/web_sys/struct.MouseEvent.html#method.init_mouse_event_with_can_bubble_arg_and_cancelable_arg_and_view_arg_and_detail_arg_and_screen_x_arg_and_screen_y_arg_and_client_x_arg_and_client_y_arg_and_ctrl_key_arg_and_alt_key_arg_and_shift_key_arg_and_meta_key_arg_and_button_arg_and_related_target_arg)

This seems a bit long. Do we generate method names? Is there a way to override them? It just seems really off to have method name this long.

**Comment by db48x** [comment]
Yes, see #2012 where it was changed from rebuilding these files on potentially every build to just building them once and checking in the result.

**Comment by Fallenstedt** [comment]
Good to know. Thank you!
