### ISSUE TITLE
web-sys: ReadableStream is Empty

### ISSUE THREAD

**Issue by anlumo** [rustwasm/wasm-bindgen#2252]
### Motivation

The [ReadableStream API](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream) is [not exposed](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.ReadableStream.html) via web-sys. The struct itself does exist, but it does not implement any functions.

This API is used in the Fetch API for reading responses as a stream, rather than loading them completely before operating on them.

### Proposed Solution

Expose the API for the ReadableStream feature.

**Comment by alexcrichton** [comment]
I think this probably  just needs an update to the WebIDL, and PRs are welcome to do that!

**Comment by DesmondWillowbrook** [comment]
I'd be willing to do it, if someone could point me in the right direction!
The ReadableStream feature should provide Read by the very least, right?

**Comment by DesmondWillowbrook** [comment]
Having a bit of trouble getting it to compile. Hope someone can help.

**Comment by anlumo** [comment]
Yes, you're right.
