### ISSUE TITLE
How to disable chunk?

### ISSUE THREAD

**Issue by mensta** [rustwasm/wasm-bindgen#2264]
Hello. I have some questions about chunk.

When I build project, I get 2 or 3 js files like index.js & 1.index.js in dist.
I wanna disable chunk (like output js file will be only index.js)

Can you tell me how to do?
I also wanna disable wasm file's hash.

If anyone know about it, please tell me.
Thank you.

**Comment by chinedufn** [comment]
wasm-bindgen doesn't do any chunking or hashing of the final build, so I'm assuming you're using webpack?

If so I'd recommend:

- If you don't need to use webpack, I'd personally recommend just using wasm-bindgen's `--target web` and not using a JavaScript bundler at all.

- If you do need webpack, check out their [documentation on chunks](https://webpack.js.org/plugins/limit-chunk-count-plugin/#maxchunks)

**Comment by alexcrichton** [comment]
Indeed I don't have anything to add over what @chinedufn already mentioned, so I'm gonna close this.
