### ISSUE TITLE
Transimitting Rust/JS data objects without serializing

### ISSUE THREAD

**Issue by WenheLI** [rustwasm/wasm-bindgen#2268]
### Summary

If my understanding is correct, the only way to put a Rust(wasm) Data Object into JS runtime (or the reverse way) is to use `serde`. But his method introduces a huge penalty as serializing & deserializing are time-consuming.

I am wondering if we can somethiong like `SharedArrayBuffer` to achieve more efficient data transmitting?

Thanks!

**Comment by alexcrichton** [comment]
Thanks for the report! You get to choose how data is transferred, and serde is not required. For example taking a `JsValue` in an API means that you're not copying the JS value. Similarly if you return a Rust structure then it's opaquely represented in JS and isn't copied.
