### ISSUE TITLE
EventListener constructor

### ISSUE THREAD

**Issue by madmaxio** [rustwasm/wasm-bindgen#2270]
How do you guys create EventListener's now? 

There is no constructor like this

` let on_click = EventListener::new(&submit_box, "click", move |_event| {`

**Comment by alexcrichton** [comment]
You can follow the [web-sys docs online](https://docs.rs/web-sys/0.3.44/web_sys/struct.EventListener.html) for what Rust APIs are avaialble, and otherwise we're just binding what the WebIDL files say so if an API is missing we can be sure to add it!

**Comment by madmaxio** [comment]
Well I just found examples code doesn't match some web-sys functions syntax.
