### ISSUE TITLE
`web_sys::window` throws a `ReferenceError` in Web Workers, while it's likely meant to return `None`

### ISSUE THREAD

**Issue by SnejUgal** [rustwasm/wasm-bindgen#2272]
### Describe the Bug

When `web_sys::window` is called inside a Web Worker, it throws a `ReferenceError: Window is not defined`, and so never returns. However, this function returns an `Option`, suggesting that it should return `None` when running in environments where `window` is not available.

### Steps to Reproduce

1. Create a new project with `wasm-pack new`
2. Add these dependencies to `Cargo.toml`:

   ```toml
   [dependencies]
   wasm-bindgen = "0.2"
   web-sys = { version = "0.3", features = ["Window"] }
   ```

3. Compile this function:

   ```rust
   use wasm_prelude::*;

   #[wasm_bindgen]
   pub fn test_window() -> bool {
     web_sys::window().is_some()
   }
   ```
4. Call this function inside a Web Worker

(Note: I actually tested this in context of my a bit odd, but open-source project. If needed, I will give instructions how to reproduce this bug there, as it makes the last step much easier)

### Expected Behavior

`test_window` returns `false` when run inside a Web Worker.

### Actual Behavior

`ReferenceError: Window is not defined` is printed to the console, and the function never returns.

### Additional Context

The error comes from `dyn_into::<Window>`. It calls this JS shim:

```js
export const __wbg_instanceof_Window_e8f84259147dce74 = function(arg0) {
    var ret = getObject(arg0) instanceof Window;
    return ret;
};
```

If the global object is not named `window`, then there's likely no `Window` class too. My suggestion is either that the `instanceof` check should be done in a `try/catch` block, or that `web_sys::window` should check if `Window` actually exists before downcasting.

**Comment by dhandy2013** [comment]
Additional information: ``web_sys::window()`` properly returns ``None`` in a worker thread on FireFox. It only crashes for me when running on the Chrome browser. So there is a browser compatibility issue here - the ``Window`` global is defined in JavaScript on Firefox when running a Web Worker, but on Chrome/Chromium it apparently is undefined.

**Comment by SnejUgal** [comment]
@dhandy2013 I've just tested in Firefox 84.0.2 and still get an exception. maybe that's something on your side?

**Comment by dhandy2013** [comment]
I also am testing on Firefox 84.0.2.

I apologize. I thought I had seen ``web_sys::window()`` return ``None`` inside Firefox but Crash on Chrome. But when I tried to create a minimal example of that just now, I could not. I am getting the same results as you (crashes on Firefox also.)

Here is a small example that reproduces this issue:
https://github.com/dhandy2013/web-sys-issue-2272

**Comment by pwoolcoc** [comment]
Any updates on this? I'm having trouble even starting a WebWorker on Firefox because of this generated code:

```
async function init(input) {
    // ...snip
    imports.wbg.__wbg_instanceof_Window_9c4fd26090e1d029 = function(arg0) {
        var ret = getObject(arg0) instanceof Window;
        return ret;
    };
```

**Comment by SnejUgal** [comment]
@pwoolcoc even if this bug were fixed, you'd very likely get a panic anyway unless the possibility of `None` is gracefully handled. Do you call `window` yourself or does one of your dependencies call `window`? When I faced this bug, it turned out to be an incorrect assumption in `reqwest`, which I then fixed in https://github.com/seanmonstar/reqwest/pull/990.

**Comment by voxelstack** [comment]
Any updates on this? I am using `web_sys` on a Next.js project. The `#[wasm_bindgen(start)]` function will run during pre-render and throw this error since I cannot check whether or not it's running on a browser.
If not a fix, it would be nice to know of any workarounds for checking if `Window` is defined.
