### ISSUE TITLE
Enum: Enable annotating discriminant of only some variants

### ISSUE THREAD

**Issue by Urhengulas** [rustwasm/wasm-bindgen#2273]
### Motivation
In the codebase I am working on are a couple of C-style enums, which have some variants annotated with discriminants and others not. _(see for example [`enum ColorPrimaries`](
https://github.com/xiph/rav1e/blob/6a4e7eb3445896023a7fd65df5feaefcfd53de10/src/api/color.rs#L41-L73))_

I'd like to export these enums to js, to be able to use them as input parameters for some functions.

But, currently following code doesn't work, because one`must either annotate discriminant of all variants or none`.

```rust
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
#[derive(Debug)]
pub enum Boat {
    Red,
    Blue,
    Green = 42,
    Yellow,
}

#[wasm_bindgen]
pub fn run_it(b: Boat) -> String {
    format!("{:?}", b)
}
```

### Proposed Solution
I'd like `wasm-bindgen` to generate following js-glue-code:
```ts
export const Boat = Object.freeze({
    Red: 0,     "0":  "Red",
    Blue: 1,    "1":  "Blue",
    Green: 42,  "42": "Green",
    Yellow: 43, "43": "Yellow",
});
```
... and following type annotations:
```ts
export enum Boat {
  Red,
  Green,
  Blue,
  Yellow,
}
```

### Alternatives

I could also create a copy of the needed enums, remove all discriminants and then match the copied and actual enum in the function. But this sounds not like a clean and maintainable solution...

### Additional Context

I am happy to implement these changes, but would need a bit of mentoring :smile: 

<details>
<summary>Edit</summary>

Initially I proposed to generate following js-Object:
```js
export const Boat = Object.freeze({
    Red: 0,     "0":  "Red",
    Blue: 1,    "1":  "Blue",
    Green: 42,  "42": "Green",
    Yellow: 2,  "2":  "Yellow",
});
```

But playing around with rust I saw that following code:
```rust
pub enum Boat {
    Red,
    Blue,
    Green = 42,
    Yellow,
}

fn main() {
    let a = Boat::Red as u32;
    let b = Boat::Blue as u32;
    let c = Boat::Green as u32;
    let d = Boat::Yellow as u32;

    for i in [a, b, c, d].iter() {
        eprintln!("{:?}", i);
    }
}
```
... actually outputs:
```
0
1
42
43
```
So I guess it is better to stick with that also for the js code.

</details>

**Comment by Urhengulas** [comment]
Digging a bit into the code, if found that the error message comes from: https://github.com/rustwasm/wasm-bindgen/blob/87663c6d2a442d98b3d8ea6242f20c5c21fc0174/crates/macro-support/src/parser.rs#L1155-L1163

The important bit is "We don't really want to get in the business of emulating how rustc assigns values to enums." (written by @alexcrichton).

Wouldn't it be possible to read the values `rustc` assigns to the enum variants (by casting them to `u32`)?

**Comment by alexcrichton** [comment]
Currently, no, there's no way to read what rustc assigns a variant.

**Comment by Urhengulas** [comment]
> Currently, no, there's no way to read what rustc assigns a variant.

@alexcrichton That's a pity :/ Can you think of any other way to make this possible?

**Comment by alexcrichton** [comment]
Unfortunately, no, I cannot at this time.

**Comment by RunDevelopment** [comment]
> Currently, no, there's no way to read what rustc assigns a variant.

[Implicit discriminants](https://doc.rust-lang.org/reference/items/enumerations.html#implicit-discriminants) are assigned by Rust using a very simple algorithm. We don't need rustc to know which value is assigned, because we know the algorithm it uses.

To copy a code example from the docs:

```rs
enum Foo {
    Bar,            // 0
    Baz = 123,      // 123
    Quux,           // 124
}

let baz_discriminant = Foo::Baz as u32;
assert_eq!(baz_discriminant, 123);
```
