### ISSUE TITLE
Online raytrace-parallel example cannot run on Firefox 79.0

### ISSUE THREAD

**Issue by jonasmalacofilho** [rustwasm/wasm-bindgen#2277]
### Describe the Bug

The online raytrace-parallel example is not able to run on current Firefox (79.0).

### Steps to Reproduce

1. Go to the [online raytrace-parallel example](https://rustwasm.github.io/wasm-bindgen/exbuild/raytrace-parallel/) using Firefox 79.0.
2. See error.

### Expected Behavior

The demo to run.

### Actual Behavior

Trying to run the demo with a current Firefox (79.0) fails with:

> this browser does not have SharedArrayBuffer support enabled
> This demo requires a current version of Firefox (e.g., 79.0)

I checked and `dom.postMessage.sharedArrayBuffer.withCOOP_COEP` is enabled.

That said, `dom.postMessage.sharedArrayBuffer.bypassCOOP_COEP.insecure.enabled` isn't, but it's locked.  I can probably figure out how to enable it, but I'm guessing this isn't expected to be necessary.

### Additional Context

It seems that a couple of response headers may be missing for `SharedArrayBuffer` to be enabled.[1][2]

[1] https://hacks.mozilla.org/2020/07/firefox-79
[2] https://hacks.mozilla.org/2020/07/safely-reviving-shared-memory/

**Comment by alexcrichton** [comment]
Thanks for the report! This is due to the necessary headers not being passed on GitHub Pages unfortunately. I've [updated the branch documentation](https://rustwasm.github.io/wasm-bindgen/examples/raytrace.html) to have a [different link served from netlify](https://wasm-bindgen.netlify.app/exbuild/raytrace-parallel/) which works awhile back.

**Comment by ciweiandmao** [comment]
May I ask how to forcibly enable dom.postMessage. sharedArrayBuffer. ypassCOOP_COEP. insecure. enabled?
In my Firefox browser, it is locked and cannot be changed
