### ISSUE TITLE
Can not use web-assembly rust impl because of 'Cannot access '__wbindgen_throw' before initialization' error

### ISSUE THREAD

**Issue by kaczor6418** [rustwasm/wasm-bindgen#2280]
I am trying to add some web-assembly to my project. On the beginning I created a simple method to check is my webpack works well and can I use my `.wasm` modules. So I created sth like this:

```rust
#[wasm_bindgen]
pub fn return_char() -> char {
    return 'a';
}
```
And then I used this inside constructor of my class (just to check is everything works fine):
```typescript
constructor() {
    super(template);
    this.setUpElements();
    console.log(return_char());
}
```
This worked as expected I saw `'a'` in my web-app console:
[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/Qnd4Y.png

Then when I saw that everything works fine I created structure with implementation:
```rust
#[wasm_bindgen]
pub struct LexicalAnalyzer {
    expression: char
}

#[wasm_bindgen]
impl LexicalAnalyzer {
    pub fn new() -> LexicalAnalyzer {
        let expression: char = 'a';
        LexicalAnalyzer {
            expression
        }
    }

    pub fn expression(&self) -> char {
        self.expression
    }

    pub fn change_expression(&mut self) {
        self.expression = 'b';
    }
}
```
And then again I call these methods in my TypeScript class constructor and I should see `'a'` and `'b'` in my console

```typescript
constructor() {
    super(template);
    this.setUpElements();
    const lexicalAnalyzer: LexicalAnalyzer = LexicalAnalyzer.new();
    console.log(lexicalAnalyzer.expression());
    lexicalAnalyzer.change_expression();
    console.log(lexicalAnalyzer.expression());
}
```

But this didn't happen and I saw only this error: 

> calculator_engine_bg.js:5 Uncaught (in promise) ReferenceError: Cannot access '__wbindgen_throw' before initialization at Module.__wbindgen_throw (calculator_engine_bg.js:5)

To build my rust code I used `wasm-pack` and build my code with `wasm-pac build` comand

I do not know why I am getting this error and how can I fix this. I also really do not know what I am doing wrong :/

**Comment by jxmorris12** [comment]
I have this issue as well!

**Comment by kaczor6418** [comment]
@jxmorris12 I solve this problem. If you are interested in solution i recommend you to check my answer on stack: 
 - [Can not use web-assembly rust impl because of 'Cannot access '__wbindgen_throw' before initialization' error](https://stackoverflow.com/questions/63494610/can-not-use-web-assembly-rust-impl-because-of-cannot-access-wbindgen-throw).

And if you want to see an example I also created a repository with working code example:
 - [kaczor6418/webpack-web-assembly-rust-impl-bug](https://github.com/kaczor6418/webpack-web-assembly-rust-impl-bug)
On branch **`sync-web-assebmly-and-bootstrap-file`**.
