### ISSUE TITLE
wasm-game-of-life tutorial fals to execute npm run start

### ISSUE THREAD

**Issue by chasahodge** [rustwasm/wasm-bindgen#2282]
I have been trying to complete several wasm-rust-webassembly tutorials and they all fail on the execution of the npm run start. Most of them give me the following error:

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! create-wasm-app@0.1.0 start: `webpack-dev-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the create-wasm-app@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/charleshodge/.npm/_logs/2020-08-13T14_17_40_248Z-debug.log
```
The first time they fail I go back an redo the tutorial and end up with the same result. The error result shown above is from the wasm-game-of-life tutorial. I'm running on a MB Air (2019 - Catalina). What am I missing? Help! I've successfully completed other projects in Rust, React, Vue, and many other languages, but this has me stumped in the fact that I can't get any wasm rust tutorial to work.

**Comment by alexcrichton** [comment]
Thanks for the report but I think this is an issue for the game-of-life repo rather than wasm-bindgen.

**Comment by chitalian** [comment]
I am getting the exact same issue, any solutions to this?

**Comment by chasahodge** [comment]
chittalian, I had to rebuild my Mac. I had so much clutter from learning so many languages over the last couple of years I thought I would just start clean with Rust. After rebuilding I was able to compile all of the tutorials I couldn't before the rebuild.
