### ISSUE TITLE
Raytrace example won't compile (wasm32::atomic_notify)

### ISSUE THREAD

**Issue by nemwiz** [rustwasm/wasm-bindgen#2285]
I'm trying to run the raytrace example and I'm hitting a compile error.

```
Compiling wasm-bindgen-futures v0.4.17
error[E0425]: cannot find function atomic_notify in module core::arch::wasm32
  --> C:\Users\neni\.cargo\registry\src\github.com-1ecc6299db9ec823\wasm-bindgen-futures-0.4.17\src\task\multithread.rs:39:33
   |
39 |             core::arch::wasm32::atomic_notify(
   |                                 ^^^^^^^^^^^^^ not found in core::arch::wasm32

error: aborting due to previous error

For more information about this error, try rustc --explain E0425.
error: could not compile wasm-bindgen-futures
```

Steps to reproduce:

-  Checkout the raytrace example (https://github.com/rustwasm/wasm-bindgen/tree/master/examples/raytrace-parallel)
-  Run `./build.sh`

I'm using the Rust nighlty (nightly-x86_64-pc-windows-msvc unchanged - rustc 1.47.0-nightly (81dc88f88 2020-08-13)) and I have `rust-src` component added. Am I missing some steps maybe? Any help is appreciated.

Thanks,
Nemanja

**Comment by alexcrichton** [comment]
Thanks for this! This is because the intrinsic has been renamed to `memory_atomic_notify` in nightly. I'll work on getting this fixed next I'm back at a computer.
