### ISSUE TITLE
Support `#[should_panic]` in tests

### ISSUE THREAD

**Issue by d-e-s-o** [rustwasm/wasm-bindgen#2286]
I think it would be great to have support for the `#[should_panic]` attribute on tests. That is, the following works as expected when compiling natively:

```rust
#[test]
#[should_panic]
fn foo() {
  panic!("foo")
}
```

But if I am doing the same in WASM:
```rust
#[wasm_bindgen_test::wasm_bindgen_test]
#[should_panic]
fn foo() {
  panic!("foo")
}
```
I see `warning: unused attribute` and a panic:
```
panicked at 'foo', src/XXX:YYY:ZZ

Stack:

Error
    at target/wasm32-unknown-unknown/wbg-tmp/wasm-bindgen-test.js:751:15
   ...
```

**Comment by d-e-s-o** [comment]
Oh, well, do we have no unwinding support in WASM at all?
```rust
#[test]
fn foo() {
  use std::panic::catch_unwind;

  let _ = catch_unwind(|| {
    panic!("test");
  });
}
```
Even that panics.

**Comment by alexcrichton** [comment]
Unfortunately this is not possible to easily support today because wasm does not have catchable exceptions, this will work once that proposal stabilizes, though!

**Comment by Tamschi** [comment]
I just tripped across this but had noticed earlier that the test runner now trampolines through JS to run the individual tests, which if I'm not mistaken gives it an interface to observe and handle the error.

Is it feasible to implement this feature on that basis now or is there another blocker?
