### ISSUE TITLE
What the suffix meaning (bg) with _bg.js and _bg.d.ts when we built into pkg folder?

### ISSUE THREAD

**Issue by SomboChea** [rustwasm/wasm-bindgen#2290]
### Summary

I so wonder about the built files in pkg folder. Because the files end with _bg.js and _bg.d.ts has defined different methods with parameter(s) when we return the method as String. But I don't know, why it's happened like that.
### Additional Details

`Note* I'm replaced the JavaScript to TypeScript! (not pkg files) and only file that have suffix _bg.d.ts that wrong export functions.
`
#### The function that have return String value
```rust
#[wasm_bindgen]
pub fn sample() -> String {
    "hello".into()
}
```
#### The function export in TypeScript
```typescript
export function sample(a: number): void;
```

As that, I cannot return the value into output in JavaScript. I think, it can be cause by rust wasm or mis-configuration or something else.

Thank you!

**Comment by alexcrichton** [comment]
"bg" stands for "bindgen" here, and they're intended to be internal files generated by wasm-bindgen for your project.
