### ISSUE TITLE
Calling `set_inner_html` does not work for some "old" DOM Element structs

### ISSUE THREAD

**Issue by fotoegamedev** [rustwasm/wasm-bindgen#2293]
### Describe the Bug

In my project, I build the whole DOM tree from WASM. Since my user interface is dynamic, I store `Element` structs in my Rust code to easily reference the DOM elements later on, without having to deal with giving unique ids to every DOM element.

For example, I create some `span`s, and when the user clicks a button, the test in the `span`s is updated. Curiously, this only works for some of the `span`s, others just don't update. This behavior is deterministic and occurs in both Chromium and Firefox.

### Steps to Reproduce

[This](https://github.com/rustwasm/wasm-bindgen/files/5108446/sim-master.tar.gz) is the project in which the bug occurs.
Follow the commands to set it up (standard wasm-bindgen with node-js installation).

After opening the website in the browser (localhost:8080), open the javascript console in your browsers development tools.
Then click `New Game`, then `Start Game` and then click `End Day` a few times.

In the log you will notice some messages each time you click. One message starts with `New name label`. This one is important. Note that the name label in your browser window does not get updated as written in the log.

See `src/webui/game_view/person_detail.rs` and check out the `PersonDetailView::update` function. Here this log message is generated. Notice that the line `self.name_label.set_inner_html(&name_label);` should update the name label to the value printed in the log message, but it doesn't. See lines 21ff to convince yourself that I create and store the element correctly.

### Expected Behavior

For an example where the exact same code works, see `src/webui/game_view/date_label.rs`. Here, the same update behavior is programmed for the `label` member of the struct, and as you can see when clicking the `End Day` button, the date is updated correctly.

**Comment by alexcrichton** [comment]
Sorry I don't have much time to dive into code right now, so I'm not sure there will be much external help in resolving this right now.

**Comment by fotoegamedev** [comment]
Hi,

thank you very much for your answer. I found the bug now, apparently it was in my software after all. Excuse the inconvenience.
