### ISSUE TITLE
Allow binding functions taking `T: Into<f64>`

### ISSUE THREAD

**Issue by milliams** [rustwasm/wasm-bindgen#2303]
### Motivation

I am writing a library which will be used as both a Rust crate and a a WASM module. In order to allow my Rust functions to take a range of integers and floats I define a function which takes a type `T: Into<f64>`. If I try to bind this with `wasm-bindgen`:
```rust
#[wasm_bindgen]
pub fn my_fn<T: Into<f64>>(value: T) {
    let a: f64 = value.into();
    println!("{}", a);
}
```
I get an error:
```
error: can't #[wasm_bindgen] functions with lifetime or type parameters
  --> src/foo.rs:26:13
   |
26 | pub fn my_fn<T: Into<f64>>(value: T) {
   |             ^^^^^^^^^^^^^^
```

### Proposed Solution

I understand that solving the general case of type parameter arguments is difficult (or impossible) but in the case of `T: Into<f64>` it should always be safe to take a `number` from ES. It's my understanding that WASM (as opposed to ES) also only has `i32 | i64 | f32 | f64` which are all safe to go to Rust's `f64`.

Would is be possible to special-case `T: Into<f64>` to allow for these functions to be exposed.

Perhaps a similar thing could be done with `T: Into<String>` but I understand the situation there is more complex.

**Comment by alexcrichton** [comment]
Thanks for the report! I'm going to close this though as something that's pretty unlikely we'll support. I'd recommend making a wrapper function which takes an `f64` type and then calls `my_fn` internally.
