### ISSUE TITLE
Is it possible to configure the maximum number of pages for the wasm shared memory?

### ISSUE THREAD

**Issue by d3lm** [rustwasm/wasm-bindgen#2306]
My question is the above. When you compile your Rust crate to wasm and enable and use shared memory then it will set the `maximum` number of pages to a default of `16384` which in total is about 1 GB of memory. Is this configurable in some way? If not, it would be cool if this was possible so that the user could specify how much memory they need.

**Comment by alexcrichton** [comment]
Currently it's configurable via [this env var](https://github.com/rustwasm/wasm-bindgen/blob/a04e189712a6e55056b871967f1408c8b9344f5f/crates/cli-support/src/lib.rs#L503-L505) (`WASM_BINDGEN_THREADS_MAX_MEMORY`)

**Comment by d3lm** [comment]
Thanks a lot!
