### ISSUE TITLE
How to use simd with wasm-bindgen?

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rustwasm/wasm-bindgen#2309]
### Summary

How to use simd in wasm-bindgen? could you give me a example , thanks a lot.

### Additional Details

Provide any additional details here.

**Comment by alexcrichton** [comment]
Using simd with wasm-bindgen should be basically the same as without wasm-bindgen, and you can find more information about using it [here](https://doc.rust-lang.org/nightly/core/arch/wasm32/).
