### ISSUE TITLE
--no-modules should use instantiateStreaming instead of instantiate

### ISSUE THREAD

**Issue by varkor** [rustwasm/wasm-bindgen#231]
Or it should be available as an option, as the preferred method to fetching and instantiating wasm modules.

**Comment by xtuc** [comment]
Note that instantiateStreaming is not available on Node.

I can recommend you to look at the output of Webpack: https://github.com/webpack/webpack/blob/586f9a21768e8bbc6bead6e564a6c7981a42f2d8/examples/wasm-simple/README.md (open the details).
