### ISSUE TITLE
Link to webaudio example is 404

### ISSUE THREAD

**Issue by guest271314** [rustwasm/wasm-bindgen#2314]
### Describe the Bug

Link to webaudio example is 404

### Steps to Reproduce

1. Go to https://github.com/rustwasm/wasm-bindgen/tree/master/examples/webaudio 
2. Click on 'View compiled example online'

If applicable, add a link to a test case (as a zip file or link to a repository we can clone).

https://rustwasm.github.io/wasm-bindgen/exbuild/web-audio/

### Expected Behavior

Link to example to not be 404

### Actual Behavior

Link to example is 404

**Comment by Xuanwo** [comment]
It's a typo and I made a PR to fix it.
