### ISSUE TITLE
Fails to generate valid wasm in non-dev mode: unexpected true: Exported global cannot be mutable, on

### ISSUE THREAD

**Issue by sdroege** [rustwasm/wasm-bindgen#2319]
Building my code via `wasm-pack` in non-dev mode errors out during the call to `wasm-opt`

### Steps to Reproduce

1. Go to https://github.com/sdroege/ebur128/tree/wasm and check out the `wasm` branch
2. Run `wasm-pack build --target web -- --features wasm`
3. See error below

This is with `wasm-pack` 0.9.1, Rust 1.46.0. Not sure if this is the right repo, or if it should rather be reported against `rustc`, `llvm` or `wasm-pack`.

```
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
   Compiling ebur128 v0.1.5 (/home/slomo/Projects/rust/ebur128)
    Finished release [optimized] target(s) in 1.41s
[INFO]: Installing wasm-bindgen...
[INFO]: Optimizing wasm binaries with `wasm-opt`...
[wasm-validator error in module] unexpected true: Exported global cannot be mutable, on 
global$0

[lots of wasm here]

Fatal: error in validating input
Error: failed to execute `wasm-opt`: exited with exit code: 1
  full command: "/home/slomo/.cache/.wasm-pack/wasm-opt-4d7a65327e9363b7/wasm-opt" "/home/slomo/Projects/rust/ebur128/pkg/ebur128_bg.wasm" "-o" "/home/slomo/Projects/rust/ebur128/pkg/ebur128_bg.wasm-opt.wasm" "-O"
To disable `wasm-opt`, add `wasm-opt = false` to your package metadata in your `Cargo.toml`.
```

**Comment by alexcrichton** [comment]
Thanks for the report! The issue here is with wasm-pack's invocation of wasm-opt, however, so I'm going to close this (this would be good to report there though!)

**Comment by sdroege** [comment]
Thanks for pointing in the right direction and sorry for the noise here :)

**Comment by sdroege** [comment]
That's https://github.com/rustwasm/wasm-pack/issues/886 FWIW
