### ISSUE TITLE
Target no-module can't build ImageData

### ISSUE THREAD

**Issue by botika** [rustwasm/wasm-bindgen#2320]
Compile with:
```bash
RUSTFLAGS='-C target-feature=+atomics,+bulk-memory' \
  cargo build -p client --target wasm32-unknown-unknown --release -Z build-std=std,panic_abort

wasm-bindgen target/wasm32-unknown-unknown/release/client.wasm \
  --out-dir . \
  --target no-modules
```

I can't build [`ImageData`](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.ImageData.html) with this compile options because `ImageData constructor: Argument 1 can't be a SharedArrayBuffer`.

What would be the correct way to do this compiling with target no-modules?

Thanks

**Comment by alexcrichton** [comment]
I don't think this has anything to do with `no-modules`, it looks like `ImageData` can't be built with threaded modules as the backing store according to the error message. Slices handed out to imported functions are backed by wasm's memory, which is shared if wasm is threaded. You'll probably want to create your own array buffer specifically which copies the data into a local `ArrayBuffer`.
