### ISSUE TITLE
Running tests in headless mode for Firefox is failing with 500 code response but ok in web browser

### ISSUE THREAD

**Issue by austincarrig** [rustwasm/wasm-bindgen#2321]
### Describe the Bug

Running ```wasm-pack test --headless --firefox``` should show passed tests, but it fails.

Duplicate of issue #2261 

### Steps to Reproduce

1.  -> ```git clone https://github.com/rustwasm/wasm_game_of_life.git```
2.  -> ```cd wasm_game_of_life```
3.  -> ```wasm-pack test --firefox --headless```

If applicable, add a link to a test case (as a zip file or link to a repository we can clone).

### Expected Behavior

Should pass tests.

### Actual Behavior

Tests fail when they should pass

**Comment by alexlapa** [comment]
There are a lot of things that could go wrong. Could you please run tests with logging on?
```
RUST_LOG=DEBUG wasm-pack test --firefox --headless
```

And specify geckodriver and Firefox versions: `firefox -V`, `geckodriver -V`.

**Comment by austincarrig** [comment]
I pushed the log up to my project: [log file](https://raw.githubusercontent.com/austincarrig/ClausiusWebApp/8fc20b99b1894a9434ace53f019b1d1fa06e6381/verbose_logging_ff_wasmpack_headless.log). It's a lot, about 30,000 lines of output.

I don't have Firefox or Geckodriver installed, but this was working a few weeks ago no problem without them installed...

It's also failing in Travis CI, and I don't specify geckodriver/firefox versions for that. Example [here](https://travis-ci.com/github/austincarrig/ClausiusWebApp/builds/192558740). If you can't see that let me know, it should be public but I'm relatively new to working with Travis CI.

**Comment by alexlapa** [comment]
You have `wasm-bindgen` version locked at `0.2.63` on `#automation-testing` branch, and this issue is supposed to be fixed in `0.2.68`. Try running `cargo update` and rerun CI.

**Comment by austincarrig** [comment]
This is such a simple thing, I can't believe I missed it... thank you @alexlapa.
