### ISSUE TITLE
Atomics stabilisation

### ISSUE THREAD

**Issue by chemicstry** [rustwasm/wasm-bindgen#2325]
I'm not sure if this is the correct repository to ask, but was wondering about the wasm32 atomics stabilisation. Multithreading in wasm was introduced almost 2 years ago with [this blogpost](https://rustwasm.github.io/2018/10/24/multithreading-rust-and-wasm.html), however, compiling the example still requires not only nightly rust, but also rebuilding std lib.

So I was wondering what is the current progress on wasm threads and when will we be able to use them in stable rust?

**Comment by alexcrichton** [comment]
AFAIK no progress has been made on shipping this in the standard library. The best idea we've had (which is the same as two years ago) is to have a second target (naming TBD) which is wasm-with-atomics. Other than `-Zbuild-std`, though, everything should be ready to go.

**Comment by chemicstry** [comment]
Thanks for the explanation! Is there anything I could help with to make this move forward?

**Comment by alexcrichton** [comment]
Unfortunately I don't know of a great way to move it forward. The next step is probably for a concrete proposal to be made, so the best help would be to come up with a proposal yourself, but that's no light undertaking.

**Comment by alexcrichton** [comment]
I've opened https://github.com/rust-lang/rust/issues/77839 to continue discussion on this on the Rust side of things.
