### ISSUE TITLE
wasm-pack 0.9.1: (error) the trait bound `[i8; 3]: wasm_bindgen::convert::FromWasmAbi` is not satisfied

### ISSUE THREAD

**Issue by smrangel** [rustwasm/wasm-bindgen#2330]
:space_invader: **THIS IS MY CODE:**

```
use wasm_bindgen::prelude::*;
#[wasm_bindgen]

pub fn SUMAR (mut array:[i8;3]) {
    array[0]=-4;
    array[1]=15;
    array[2]=13;
 let num: i32 = array[0] as i32 + array[1] as i32 + array[2] as i32;
 println!("{}", num);
}
fn main(){}
```

:construction: **when compiling with wasm-pack build :  **
![Captura de pantalla de 2020-10-15 15-41-49](https://user-images.githubusercontent.com/68140014/96187074-ff725900-0f01-11eb-8005-3ce90b7b29b7.png)

:earth_americas: **environment :**
   cargo-generate 0.5.1
   wasm-pack 0.9.1
   rustc 1.47.0 (18bf6b4f0 2020-10-07)

**Comment by alexcrichton** [comment]
Thanks for the report! Not all types are supported by wasm-bindgen and fixed-width arrays are one of them. You'll want to take `&[u8]` (or three `u8` values) and then do validation in Rust.
