### ISSUE TITLE
js_name does not seem to effect struct values

### ISSUE THREAD

**Issue by hacker112** [rustwasm/wasm-bindgen#2331]
### Describe the Bug

`js_name` does not affect public values in structs like it affects methods.

### Steps to Reproduce

Create a struct
```rust
#[wasm_bindgen]
pub struct FooBar {
    #[wasm_bindgen(js_name = "spamEggs")]
    pub spam_eggs: u32,
}
```

### Expected Behavior

Should generate JS/TS with name `spamEggs` just like for methods.

OR throw an error that this is not possible.

### Actual Behavior

Generates JS/TS with name `spam_eggs` as if the js_name attribute would not have been set.

**Comment by alexcrichton** [comment]
Should be easy enough to implement, but agreed that this isn't working today!
