### ISSUE TITLE
Indexing/accessing properties on a js_sys::Object

### ISSUE THREAD

**Issue by lokegustafsson** [rustwasm/wasm-bindgen#2334]
I have a `let foo: js_sys::Object`. I want to access arbitrary properties by strings: in js I would do `foo["abc"]`. I feel like I am missing something very basic, but I can't for my life figure out how to do such a thing from reading the [documentation](https://rustwasm.github.io/wasm-bindgen/api/js_sys/struct.Object.html). What am I missing?

**Comment by pauldorehill** [comment]
I believe you want [js_sys::Reflect::get](https://rustwasm.github.io/wasm-bindgen/api/js_sys/Reflect/fn.get.html).

**Comment by lokegustafsson** [comment]
Ah, I do. Thank you!
