### ISSUE TITLE
Implement JsValue::into_json_string

### ISSUE THREAD

**Issue by nklhrstv** [rustwasm/wasm-bindgen#2340]
### Motivation

I want to track errors in deserialization using libraries like `serde_ignored` and `serde_path_to_error`.

### Proposed Solution

implement `JsValue::into_json_string` function that returns String.

### Alternatives

Implement `JsValue::into_serde_deserializer` that returns `serde_json::Deserializer::from_str(&s)` instead of `serde_json::from_str(&s)`. 

### Additional Context

none

**Comment by alexcrichton** [comment]
Seems reasonable to me to add!

**Comment by alexcrichton** [comment]
I think the performance of those two should be roughly comparable, but I'd recommend testing just to make sure.

**Comment by onatm** [comment]
Would something like below implementation work @alexcrichton?

```rust
    #[cfg(feature = "serde-serialize")]
    pub fn into_serde_deserializer<T>(&self) -> serde_json::Deserializer<serde_json::de::StrRead> {
        unsafe {
            let ret = __wbindgen_json_serialize(self.idx);
            let s = String::from_abi(ret);
            serde_json::Deserializer::from_str(&s)
        }
    }
```

if you think it's a good approach then I am happy to create a PR. This change needs to enable `raw_values` feature in `serde_json`.

**Comment by alexcrichton** [comment]
That could work, but I think I'm missing something? How's that different from [`into_serde`](https://docs.rs/wasm-bindgen/0.2.68/wasm_bindgen/struct.JsValue.html#method.into_serde)

**Comment by onatm** [comment]
Forgive me I don't have great understanding around `serde` and `wasm-bindgen`. I thought this issue would an easy one to tackle and I just jumped in :)

What I could see from the tests of `into_serde` that it returns a `Result<T>` where `T` is a type that is deserialized from JavaScript. And what `into_serde_deserializer` would do is it just returns a deserializer.

**Comment by nklhrstv** [comment]
I think that could work.
@alexcrichton with that API then I could do this:
```Rust
struct X { a: u32 }
...
let mut deserializer = js_value.into_serde_deserializer();
let result = serde_path_to_error::deserialize(&mut deserializer);
```
The error message will be more descriptive. It will point to the field, that causes the deserialization to fail.

**Comment by alexcrichton** [comment]
Hm that's true, yeah, although I think it would be best perhaps to not support that natively but rather provide bindings to `JSON.stringify` in `js-sys` maybe?

**Comment by nklhrstv** [comment]
How is that gonna help me use `serde_path_to_error`?

**Comment by alexcrichton** [comment]
Well the idea is that once you have a JSON string you can do whatever you'd like to deserialize it, basically what the proposed method is doing, except in your crate you're working on.

**Comment by nklhrstv** [comment]
I will just use the as_string API.
