### ISSUE TITLE
Expose and fix all ImageCapture APIs

### ISSUE THREAD

**Issue by dodomorandi** [rustwasm/wasm-bindgen#2347]
### Describe the Bug

Not all ImageCapture API are exposed, maybe it is just because of Gecko not currently supporting some of them. The webidl contains some (maybe obsolete?) API that are different from the [current working draft](https://www.w3.org/TR/image-capture/).

### Steps to Reproduce

Open [ImageCapture.webidl](https://github.com/rustwasm/wasm-bindgen/blob/f8354b3a88de013845a304ea77d8b9b9286a0d7b/crates/web-sys/webidls/enabled/ImageCapture.webidl) to notice some attributes and methods are commented out. Compare them with the official specification to notice some differences.

### Expected Behavior

These features should be fixed and exposed in order to make them usable in `web-sys`, even if the implementation in Gecko is lacking.

### Actual Behavior

The fact that some features are commented out make them unavailable in `web-sys`, which a bit painful because using _extension traits_ is not doable when `wasm_bindgen` is involved -- if there is some workaround for this other than using a newtype, let me know. Obviously, having them available but not correctly implemented is bad as well.

**Comment by alexcrichton** [comment]
This may have been done in the very early days of web-sys as well when many types weren't supported, but should be fine to update the WebIDL or uncomment it now!
