### ISSUE TITLE
Better support for u64 through JSValue::as_u64() and u64::into() -> JsValue

### ISSUE THREAD

**Issue by lucacasonato** [rustwasm/wasm-bindgen#2350]
### Motivation

`BigInt` is now supported in stable releases of all modern browsers. Currently interfacing with `BigInt` generically in wasm-bindgen with JSValue is quite painful. `JSValue` is not aware of `BigInt` (and thus u64) at all.

### Proposed Solution

- Add a `impl From<u64> for JSValue`, that can be used to cast u64 to `BigInt`.
- Add `JSValue::as_u64(&self) -> Option<u64>` to cast `BigInt` to u64.

### Alternatives

This solution aligns closely to current implementation of primitives handling in `JSValue`. I am not aware of alternative implementation ideas, or if this can be built on top of wasm-bindgen.

**Comment by 00ff0000red** [comment]
Signed `i64` variants would be great too!

**Comment by trevyn** [comment]
Also should be closable now that https://github.com/rustwasm/wasm-bindgen/pull/2629 is merged.

**Comment by RReverser** [comment]
I don't see anything similar to `JsValue::as_u64` (a way to get u64/i64 from BigInt) in the linked PR, only the opposite conversions.

Am I missing some API? If not, perhaps worth reopening this issue.

**Comment by RReverser** [comment]
Ping, can we reopen this?
