### ISSUE TITLE
How can I resolve multiple requests in rust

### ISSUE THREAD

**Issue by shijunti19** [rustwasm/wasm-bindgen#2354]
### Summary

I want to solve the problem of concurrent requests. I can't modify it in the callback. If mut self is used, the front-end JS must be new every time, resulting in invalid.

I don't want to control this state in JS because every request has to be processed

What do I want to solve

### Additional Details
```
#[wasm_bindgen]
pub struct HttpRequest {
    loading: bool,
}
#[wasm_bindgen]
impl HttpRequest {
    #[wasm_bindgen(constructor)]
    pub fn new() -> HttpRequest {
        HttpRequest {
            loading: false,
        }
    }
    pub fn request(&mut self, url: String, method: String, body: JsValue) -> Promise {
        //防止2次请求
        if self.loading {
            return future_to_promise(async move {
                Err(JsValue::from(String::from("Requests are too frequent. Please wait")))
            });
        }
        self.loading = true;
        ...
        future_to_promise(async move {
            let resp_value = JsFuture::from(window.fetch_with_request(&request)).await?;
            let resp: Response = resp_value.dyn_into().unwrap();
            self.loading = false;//It can't be modified here
            Ok(JsValue::from(resp.json()?))
        })
    }
}
```
var http= HttpRequest.new()
function get(){
  http.request("http://www.***.com");
}
Quick click

The server has not returned and received the same request. I hope that the second request can be processed after the first request is finished

How to solve the loading in code

**Comment by alexcrichton** [comment]
Ah yes thanks for the expanded information! This is an unfortunate limitation of spawning tasks in JS where it requires `'static` futures. To do this you'll probably need to do `self: Rc<Self>` and use a `Cell` or `RefCell` internally. That way you can capture over a copy of the `Rc` and modify it.

**Comment by shijunti19** [comment]
@alexcrichton It's too difficult. I've tried all kinds of methods, but I'm not familiar with it. I can't write it. No one has ever written anything like that

**Comment by shijunti19** [comment]
@alexcrichton Hope to point out some examples in this respect, when referring to self, call its own methods and modify its own properties

**Comment by alexcrichton** [comment]
What you'll probably want is something like this: 

```rust
#[wasm_bindgen]
#[derive(Default)]
pub struct HttpRequest {
    internals: Rc<HttpRequestInternals>,
}

#[derive(Default)]
struct HttpRequestInternals {
    loading: Cell<bool>,
}

#[wasm_bindgen]
impl HttpRequest {
    #[wasm_bindgen(constructor)]
    pub fn new() -> HttpRequest {
        HttpRequest::default()
    }

    pub fn request(&self, url: String, method: String, body: JsValue) -> Promise {
        //防止2次请求
        if self.internals.loading.get() {
            return future_to_promise(async move {
                Err(JsValue::from(String::from("Requests are too frequent. Please wait")))
            });
        }
        self.internals.loading.set(true);
        ...
        let internals = self.internals.clone();
        future_to_promise(async move {
            let resp_value = JsFuture::from(window.fetch_with_request(&request)).await?;
            let resp: Response = resp_value.dyn_into().unwrap();
            internals.loading.set(false);
            Ok(JsValue::from(resp.json()?))
        })
    }
}
```

**Comment by shijunti19** [comment]
@alexcrichton Thank you. I hope  can write this kind of function into the example completely. It's very important

There's a question: can wasm break through the browser's limitations and implement multi thread simultaneous upload？

**Comment by alexcrichton** [comment]
At this time wasm only has the capabilities of JS itself. If JS can do it then wasm can do it (and vice versa). There's no wasm-specific browser functionality at this time.
