### ISSUE TITLE
Missing Window gamepad connect and disconnect event handler functions

### ISSUE THREAD

**Issue by arcriley** [rustwasm/wasm-bindgen#2356]
Using the gamepad API is made difficult because Window struct is currently lacking the following:
 ongamepadconnected
 set_ongamepadconnected
 ongamepaddisconnected
 set_ongamepaddisconnected

https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API/Using_the_Gamepad_API

**Comment by alexcrichton** [comment]
Thanks for the report! This may just be a missing WebIDL file, which should be fine to add at any time!

**Comment by arcriley** [comment]
I implemented this by hand, and then tested with JavaScript, and discovered
that while it is documented it is not yet implemented in either Chrome or
Firefox.

**Comment by alexcrichton** [comment]
Ah ok then I'm gonna go ahead and close this because I don't think there's much we can do about that unfortunately.
