### ISSUE TITLE
hello-wasm build fails

### ISSUE THREAD

**Issue by mjsML** [rustwasm/wasm-bindgen#2357]
### Describe the Bug

Trying the tutorial steps at https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm 

on 
ubuntu 20.04 
gcc version 10.2.0 (Ubuntu 10.2.0-5ubuntu1~20.04) 
GNU Make 4.2.1 Built for x86_64-pc-linux-gnu
node version 15.2.0
npm version 7.0.8

### Steps to Reproduce
same as the tutorial until step "Building the package", then the build fails as below:

```bash
~/hello-wasm$` wasm-pack build 
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
   Compiling proc-macro2 v1.0.24
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.48
   Compiling wasm-bindgen-shared v0.2.68
   Compiling log v0.4.11
   Compiling cfg-if v0.1.10
   Compiling bumpalo v3.4.0
   Compiling lazy_static v1.4.0
   Compiling wasm-bindgen v0.2.68
   Compiling quote v1.0.7
   Compiling wasm-bindgen-backend v0.2.68
   Compiling wasm-bindgen-macro-support v0.2.68
   Compiling wasm-bindgen-macro v0.2.68
   Compiling hello-wasm v0.1.0 (/home/username/hello-wasm)
error[E0433]: failed to resolve: maybe a missing crate `wasm_bindgen`?
 --> src/lib.rs:1:5
  |
1 | use wasm_bindgen::prelude::*;
  |     ^^^^^^^^^^^^ maybe a missing crate `wasm_bindgen`?

error: cannot find attribute `wasm_bindgen` in this scope
 --> src/lib.rs:8:3
  |
8 | #[wasm_bindgen]
  |   ^^^^^^^^^^^^

error: cannot find attribute `wasm_bindgen` in this scope
 --> src/lib.rs:3:3
  |
3 | #[wasm_bindgen]
  |   ^^^^^^^^^^^^

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0433`.
error: could not compile `hello-wasm`.

To learn more, run the command again with --verbose.
Error: Compiling your crate to WebAssembly failed
Caused by: failed to execute `cargo build`: exited with exit code: 101
  full command: "cargo" "build" "--lib" "--release" "--target" "wasm32-unknown-unknown"
```

### Expected Behavior
For the build to succeeded given the cargo is installed.

### Actual Behavior
Failure to find the cargo, although cargo bin is in $PATH

### Additional Context
I'm far from a rust or webassembly expert (hence the helloworld example :nerd_face:  ) 

### Update
The example at rustwasm https://rustwasm.github.io/docs/book/game-of-life/hello-world.html seems to work just fine, but it uses 0.2.63 in the toml, I'm suspecting this is related to #2279 , but even the workarounds mentioned does not make it work for 0.2.66+.

**Comment by jonboj** [comment]
On Ubuntu 20.10
In a clean dir following https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm
Compiles and builds succesfully without any tweaks.
Maybe the repo examples e.g. https://github.com/rustwasm/wasm-bindgen/tree/master/examples/hello_world
could be a more traceable source.

For initial firstline forum, SO is maybe more suited for this type of troubles https://stackoverflow.com/questions/tagged/wasm-bindgen

**Comment by mjsML** [comment]
Hi @jonboj,

Thank you for the links.

I would have used SO if this was a usage issue (i.e. I don't follow how the tutorial does a certain step or so).

In this instance I followed the tutorial to the letter, did my own troubleshooting on top with no success to confirm it is in fact a legitimate issue.

The issue is feedback to the maintainers that on x,y,z config the build fails, there are usually deeper causes to such issues.

Even with an identical setup, sometimes there is a gotcha that was not included in the tutorial (and that in its own is useful feedback to update the tutorial :relaxed: ).

**Comment by Morreski** [comment]
Hi @mjsML,

Do you have these lines in your Cargo.toml ?

```
[dependencies]

wasm-bindgen = "0.2"
```
If not try to add them then run the build.

Cheers,

**Comment by mjsML** [comment]
Hi @Morreski ,

I did follow the tutorial and added dependencies like you mentioned, I even tried to change the version from 0.2 to 0.2.65 as per #2279 or even 0.2.63, even enabling the mutable global feature via the release and debug flag was not successful e.g.:

```config
[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Os", "--enable-mutable-globals"]
```  
the interesting thing is when I use the the hello-world example from the rustwasm mentioned above it works just fine.
I even tried to change the config even further to closely match the helloworld example from rustwasm with no luck.

**Comment by xubicheng** [comment]
I succeeded. Please see a page by clicking the link below. [https://rustwasm.github.io/book/game-of-life/hello-world.html](url)

`
#![allow(unused_variables)]
fn main() {
extern crate cfg_if;
extern crate wasm_bindgen;

mod utils;

use cfg_if::cfg_if;
use wasm_bindgen::prelude::*;

cfg_if! {
    // When the `wee_alloc` feature is enabled, use `wee_alloc` as the global
    // allocator.
    if #[cfg(feature = "wee_alloc")] {
        extern crate wee_alloc;
        #[global_allocator]
        static ALLOC: wee_alloc::WeeAlloc = wee_alloc::WeeAlloc::INIT;
    }
}

#[wasm_bindgen]
extern {
    fn alert(s: &str);
}

#[wasm_bindgen]
pub fn greet() {
    alert("Hello, wasm-game-of-life!");
}

}`

As a result - 

`extern crate wasm_bindgen;

use wasm_bindgen::prelude::*;

#[wasm_bindgen]
extern {
    pub fn alert(s: &str);
}

#[wasm_bindgen]
pub fn greet(name: &str) {
    alert(&format!("Hello, {}!", name));
}
`
then try the command **wasm-pack build**

It will just install the tool **wasm_bindgen**, and succeed.

**Comment by alexcrichton** [comment]
I'm glad you got it working! It looks like it may have been a mistake in the code perhaps, but sounds like you got it resolved!

**Comment by mjsML** [comment]
Hi @alexandrestein 

I did not in fact ... until now... I was able to trace where is the problem stemming from, the example at https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm seems either outdated or there is a weird behavior going on my specific setup.

Bottom line is it seems wasm-pack build (and or rustc underneath) defaults to the 2015 edition for some reason unknown to me, if you explicitly define the edition attribute in the the build proceeds fine   

```toml
# This is the example verbatim and it breaks in the config that I have mentioned above.
[package]
name = "hello-wasm"
version = "0.1.0"
authors = ["Your Name <you@example.com>"]
description = "A sample project with wasm-pack"
license = "MIT/Apache-2.0"
repository = "https://github.com/yourgithubusername/hello-wasm"
```

```toml
# This works
[package]
name = "hello-wasm"
version = "0.1.0"
authors = ["Your Name <you@example.com>"]
description = "A sample project with wasm-pack"
license = "MIT/Apache-2.0"
repository = "https://github.com/yourgithubusername/hello-wasm"

# Adding the edition explicitly to force rustc to build with rust2018
edition = "2018"
```
As a beginner I'm not sure why would I have the 2015 edition of rust installed on my machine in the first place (I'm running ubuntu 20.04 so unless the rustup script installs it under the hood, this is a very odd behavior for me).

I'm not sure also if this behavior is by design or it's a weird glitch, however I would ask you kindly if you are able to update/ able to reach out to the right person that would be able to update the documentation, specially this is a hello world example that I believe is a good entry point to beginners into the ecosystem.

Given that the generated code from the other tools automatically includes the edition attribute to force the toolchain to switch to rust2018, so it will be confusing to people like myself  :relaxed: 

Many thanks,
M

**Comment by alexcrichton** [comment]
Ah ok, thanks for the info! How did you generate `Cargo.toml` in the first place? Was it with a template generator? Or just `cargo new`?

**Comment by mjsML** [comment]
For the first one I used cargo new as per the old MDN article , but we paste our own `Cargo.toml` anyway which is missing the edition attribute (now that is updated now because I updated the MDN article), the other tutorials use :
```bash 
generate --git https://github.com/rustwasm/wasm-pack-template
```

**Comment by alexcrichton** [comment]
Ok great, just wanted to make sure the source was fixed as well!
