### ISSUE TITLE
Provides a way to generate "bindings only" in javascript

### ISSUE THREAD

**Issue by Morreski** [rustwasm/wasm-bindgen#2358]
### Motivation
Hi ! Thanks for the awesome work with this lib. I am currently on a project where none of the available targets are working (I am building an app on top of [neutralinojs](https://github.com/neutralinojs/neutralinojs)). The target I need seems to be `web` but it does not work out of the box because:

* it uses experimental syntax `importMeta` (`import.meta.url.replace(/\.js$/, '_bg.wasm');`) which I cannot enable
* it uses async/await syntax (I solved it with a polyfill but I'd rather get rid of it)

Then I realised I do not really need the `init` & `load` methods since I can bootstrap the WebAssembly instance myself. What I really need is just the rust bindings.

### Proposed Solution

A **target** that would generate a minimalist file containing only the binding functions (i.e: the same thing as the `web` target minus the `init` and `load` methods) AND a factory function that would take a WebAssembly instance as parameter and return an object with the generated binding functions.

Maybe something like `wasm-bindgen --target bindings-only`

### Additional Context
This is what I imagine (I actually tried this method and it works for me):

```javascript
export default function bootstrap(instance) {
    const wasm = instance.exports

    let cachegetUint8Memory0 = null;
    function getUint8Memory0() { /*...*/ }
    function passStringToWasm0(arg, malloc, realloc) {/*...*/}
    /**
    * @param {string} path
    * @returns {string}
    */
    function my_rust_function(path) {/*...*/}
    
    return {my_rust_function, my_other_rust_function, yet_another_one}
}
```

Usage:
```javascript
WebAssembly.instantiate(myBinary, {})
    .then(({instance}) => {
        const rust = bootstrap(instance)
        rust.my_rust_function("wololo")
    })
```

What do you guys think of this ?

Cheers,

**Comment by alexcrichton** [comment]
This is perhaps possible, but would the web target as-is work for you? I think it's already possible to pass in a module and in general wasm-bindgen needs to have control over instantiation to hook everything up, the naming scheme for imports and such is only known to wasm-bindgen itself.

Otherwise we already have what feels like a lot of targets for the output of JS, so it'd be best I think if your use case could get shoehorned into an existing one, but if it can't then it's always possible to add a new target.

**Comment by Morreski** [comment]
The web target is "overall ok" but as I mentioned in my initial post I have to remove/tweak the loading code in order to make it work because of compatibility issues with features such as "importMeta".

> Otherwise we already have what feels like a lot of targets for the output of JS, so it'd be best I think if your use case could get shoehorned into an existing one

I see what you mean. I guess we can keep this in the `web` target and maybe split the generated `js` file to separate the instantiation logic and the "bindings interface". That would allow people that need a custom instantiation logic to implement their own.

So instead of having everything in the `my_project.js` file we'd have the instantiation logic in `my_project.js` file (for backward compatibility purposes) and the bindings in another file such as `my_project_bindings.js`.
This would avoid to create a new target and bring more modularity to the `web` target users.

Would this be a good enough solution for you ?

**Comment by alexcrichton** [comment]
Perhaps? Sorry I don't know enough about your use case and JS environment to really offer thoughts on how this can best fit into wasm-bindgen or whether this would work for all our other use cases as well. Perhaps it's good to prototype something and see how it goes?

**Comment by Morreski** [comment]
Alright I'll work on a proposal so we can talk on concrete code ;) The main idea will be to separate the instantiation-related stuff from the actual binding code. So I think it'll work with all curently supported use cases since the changes is mainly about providing more modularity.

I'll keep you updated as soon as I have something satisfying.

**Comment by quaos** [comment]
@Morreski Thanks, this should also help with running wasm-bindgen compiled WASM in Deno!

**Comment by Morreski** [comment]
@quaos I don't know deno at all. Is there something I should take in consideration in my implementation ? I did not intend to modify the `deno` target initially. But if you think that I should I'll be glad to have some pointers about what to do :)

**Comment by Morreski** [comment]
Hi all,

After a lots of time fiddling and trying to figure out how to adapt the "web" target (while still being backward compatible) I was not able to find a good solution. I found a workaround to my use case (turns out my app was building with IE8 support enabled and that was the problem).
Nevertheless I still think it'd be better if binding declaration and Webassembly instantiation were separated but it's more a Nice to have than a requirement so I won't work on it for the moment. Let's close the issue and maybe reopen it someday if deemed useful.

Regards,
