### ISSUE TITLE
Type error in Atomics.waitAsync in Chrome v87+

### ISSUE THREAD

**Issue by KiKoS0** [rustwasm/wasm-bindgen#2361]
### Describe the Bug

I have a multithreaded wasm app that uses [futures-channel-preview](https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.19/futures_channel/) for asynchronous communication that suddenly stopped working with Chrome version 87+. I googled a bit to find out that chrome released the [Atomics.waitAsync](https://www.chromestatus.com/feature/6243382101803008) feature and that even the [example](https://github.com/rustwasm/wasm-bindgen/tree/master/examples/raytrace-parallel) i used as a reference triggers exactly the same bug.

![bug stack trace](https://user-images.githubusercontent.com/22998716/99704130-3d7e1200-2a98-11eb-84af-ecbdc87f6323.png)

The problem turned out to be in this function:

https://github.com/rustwasm/wasm-bindgen/blob/316c5a70fdc4a052fb65ef82bf02d52107b5671b/crates/futures/src/task/multithread.rs#L158-L170
Since ```Atomics.waitAsync``` is now defined in Chrome, it is getting used instead of the fallback method, however the function waitAsync is expecting either a Int32Array or a BigInt64Array  backed by a SharedArrayBuffer. Also it's not returning a promise anymore but an Object with 2 properties ```async``` and ```value```. The value property can either be a string or a promise. ([Source](https://v8.dev/features/atomics))

I fixed the bug for my app in this [fork](https://github.com/KiKoS0/wasm-bindgen/tree/fix-waitAsync) but i'm not really sure if the code is compliant for a PR, not sure if that breaks anything else and also if the other output cases should be handled aswell. I'd be happy to change it accordingly with your input though.

### Steps to Reproduce

Just clone and run this [example](https://github.com/rustwasm/wasm-bindgen/tree/master/examples/raytrace-parallel) in Chrome 87+ or use the [already compiled online](https://rustwasm.github.io/wasm-bindgen/exbuild/raytrace-parallel/) one

### Expected Behavior

A promise should be returned from ```wait_async()``` to be resolved successfully later with a call to ```Atomics.notify```.

### Actual Behavior

This error is thrown: 
`TypeError: #<SharedArrayBuffer> is not an int32 or BigInt64 typed array.`

### Additional Context

```
rustc 1.49.0-nightly
futures-channel-preview = "0.3.0-alpha.18"
wasm-bindgen = "0.2.68"
```

**Comment by alexcrichton** [comment]
Thanks for the report! Looks like the spec has changed since it was first written (as is to be expected) and I hadn't had a chance to see this and get around to changing the expected API!
