### ISSUE TITLE
wasm-bindgen doesn't work on latest nightly

### ISSUE THREAD

**Issue by d3lm** [rustwasm/wasm-bindgen#2363]
### Describe the Bug

For my current project I am compiling my Rust crate to wasm32 and it was working up until I try to update to the latest nightly version. I am using `parking_lot` for their `Mutex` and `RwLock` but with the latest nightly of Rust and the latest wasm-bindgen I am getting a strange error:

`i32_atomic_wait in module wasm32 in parking_lot_core-0.7.2/src/thread_parker/wasm_atomic.rs:47:38`.

When I lock the toolchain to `nightly-2020-05-15` it works just fine.

Is there something I am missing or doesn't this work with the latest nightly yet?

**Comment by alexcrichton** [comment]
AFAIK the latest nightly should work ok, I recently compiled the parallel raytrace application just fine. Do you have some source code to peek at, or perhaps want to gist the full build log?

**Comment by d3lm** [comment]
Yep I ll get your a full build log and also create a minimal demo.

**Comment by d3lm** [comment]
So for some reason I am now getting this if I bump `wasm-bindgen-futures` from `0.4.13` to `0.4.19`:

```
error[E0425]: cannot find function `memory_atomic_notify` in module `core::arch::wasm32`
  --> /Users/delm/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-futures-0.4.19/src/task/multithread.rs:39:33
   |
39 |             core::arch::wasm32::memory_atomic_notify(
   |                                 ^^^^^^^^^^^^^^^^^^^^ not found in `core::arch::wasm32`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
error: could not compile `wasm-bindgen-futures`.
```

I saw that you're using the same version for the raytracing exmaple. Any idea why it would not work for me?

Here's my dependencies:

```
[dependencies]
js-sys = "0.3.46"
wasm-bindgen = { version = "0.2.69", features = ["serde-serialize"] }
once_cell = "1.5.2"
serde = { version = "1.0.117", features = ["derive", "rc"] }
serde-wasm-bindgen = "0.1.3"
serde_json = "1.0.60"
serde_repr = "0.1.6"
cfg-if = "1.0.0"
futures = "0.3.5"
wasm-bindgen-futures = "0.4.19"
parking_lot = { version = "0.10.2", features = ["nightly", "serde"] }
console_error_panic_hook = { version = "0.1.6", optional = true }
```

And my cargo config

```
[build]
rustflags=["-C", "target-feature=+atomics,+bulk-memory"]
```

And last but not least, I am running `wasm-pack`:

```
wasm-pack build --out-dir dist --release --target web -- -Z build-std=std,panic_abort
```

**Comment by alexcrichton** [comment]
Hm what rustc version are you're using? I think you'll want to be sure you're using the latest nightly

**Comment by d3lm** [comment]
For what it's worth, I am getting the same on the raytracing

![image](https://user-images.githubusercontent.com/12571019/101094556-e3fc0400-35bc-11eb-9242-997ed1e75178.png)

**Comment by d3lm** [comment]
Oh dang, you're right. I was not on the latest rustc nightly.

**Comment by d3lm** [comment]
Yep, that works. Now I have another issue but that's not wasm-bindgen related.
