### ISSUE TITLE
`ImageData.html::new_with_u8_clamped_array` should accept immutable `u8_clamped_array`

### ISSUE THREAD

**Issue by JAicewizard** [rustwasm/wasm-bindgen#2364]
### Motivation

This requites piet-web to clone the entire image even when it is already in the right format, this is costly because images are big.

### Proposed Solution

`ImageData.html::new_with_u8_clamped_array` should accept an imitable `u8_clamped_array` because I suspect it is not needed (I'm sure you know that better then I do). 

This was originally mentioned in in #1005 by @raphlinus but that has since been closed.

**Comment by alexcrichton** [comment]
Nah this is a known issue we have with WebIDL generation. We currently have a whitelist of methods that don't need mutable borrows and only need shared verisons, and should be fine to add this method to the whitelist!

**Comment by JAicewizard** [comment]
I looked around in the repo a bit and at the immutable list in `constants.rs`, and it took me a while to figure it out.
The problem is that this is a constructor, and cunstructors warn't supported yes by the implementation. It wasnt hard to add support for constructors after figuring out the issue.
I will probably open up a PR later today to add support for constructors + the ImageData fix, this should probably have been split but its not a big patch.

**Comment by JAicewizard** [comment]
I wanted to be extra sure that the clampedArray doesn't have to be mutable, and just playing around in JS would indicate it does need to be mutable: https://jsfiddle.net/ars6bz89/27/
