### ISSUE TITLE
Example to call Rust and back?

### ISSUE THREAD

**Issue by i-schuetz** [rustwasm/wasm-bindgen#2368]
I thought that combining the "call JS from Rust" and "Call Rust from JS" examples leads to the expected results, but so far I haven't able to do this. All the examples I've found so far (e.g. the [game of life tutorial](https://rustwasm.github.io/book/game-of-life/hello-world.html) and [import_js](https://github.com/rustwasm/wasm-bindgen/tree/master/examples/import_js)) don't implement a "full circle". In game of life the JS function is `alert`, so it's not user-declared, and in import_js the Rust code is called via the `#[wasm_bindgen(start)]` macro (not by the user in JS).

Here are my changes to the game of life example:

index.js:
```
import * as wasm from "testing-wasm";

export const jsfunc = () => {
  console.log("jsfunc called");
};

// Call Rust from JS. This function will call `jsfunc`, declared above.
wasm.rustfunc();
```

lib.rs:

```rust
mod utils;

use wasm_bindgen::prelude::*;

// When the `wee_alloc` feature is enabled, use `wee_alloc` as the global
// allocator.
#[cfg(feature = "wee_alloc")]
#[global_allocator]
static ALLOC: wee_alloc::WeeAlloc = wee_alloc::WeeAlloc::INIT;

#[wasm_bindgen(module = "/www/index.js")]
extern "C" {
    fn jsfunc();
}

#[wasm_bindgen]
pub fn rustfunc() {
    // call JS
    jsfunc();
}
```

`wasm-pack build` runs fine. But running the web project (`npm run start`) can't resolve the import anymore:
```
ERROR in ../pkg/snippets/testing-wasm-8ea926e8de57779d/www/index.js
Module not found: Error: Can't resolve 'testing-wasm' in '/Users/ischuetz/dev/ct-an/testing-wasm/pkg/snippets/testing-wasm-8ea926e8de57779d/www'
 @ ../pkg/snippets/testing-wasm-8ea926e8de57779d/www/index.js 1:0-37 7:0-13
 @ ../pkg/testing_wasm_bg.wasm
 @ ../pkg/testing_wasm.js
 @ ./index.js
 @ ./bootstrap.js
```

Note that it works perfectly before introducing the circular dependency.

**Comment by alexcrichton** [comment]
AFAIK circular dependencies are pretty hard to get right and you'll typically want more of a DAG of imports, but I don't think circular dependencies are impossible. In your error message that looks like a bundler configuration error, though? It doesn't look like it's related to circular dependencies? (but if it is I unfortunately wouldn't know how to solve it)

**Comment by i-schuetz** [comment]
@alexcrichton thanks for the quick reply!

I uploaded a repo with the problem. It seems related with the circular dependency, as it doesn't happen if I move the JS function to a different file. Not very experienced with JS modules. May be missing something.

Here is the part with the error: https://github.com/i-schuetz/wasm-error/blob/main/src/lib.rs#L21-L30

[index.js](https://github.com/i-schuetz/wasm-error/blob/main/www/index.js)
[foo.js](https://github.com/i-schuetz/wasm-error/blob/main/www/foo.js)

**Comment by alexcrichton** [comment]
Hm ok I tried poking around a bit but I think I'm out of my depth in webpack-land. I unfortunately don't know a whole lot about webpack and its configuration so I'm not sure how to fix this or tackle it.
