### ISSUE TITLE
MediaSource callbacks

### ISSUE THREAD

**Issue by SionoiS** [rustwasm/wasm-bindgen#2369]
### Describe the Bug
When MediaSource [set_onsourceopen](https://docs.rs/web-sys/0.3.45/web_sys/struct.MediaSource.html#method.onsourceopen) is called [ready_state()](https://docs.rs/web-sys/0.3.45/web_sys/struct.MediaSource.html#method.ready_state) returns __Nonexhaustive instead of Open
### Steps to Reproduce
1. Register callback
```
let callback = Closure::wrap(Box::new(on_source_open) as Box<dyn Fn(&MediaSource)>);

media_source.set_onsourceopen(Some(callback.into_js_value().unchecked_ref()));
```
2. Log ready state in callback
```
fn on_source_open(media_source: &MediaSource) {
    #[cfg(debug_assertions)]
    ConsoleService::info(&format!("Ready State => {:?}", media_source.ready_state()));
}
```
### Expected Behavior
When onsourceopen callback is called ready_state() should already be Open.
### Actual Behavior
When onsourceopen callback is called ready_state() returns  __Nonexhaustive.
### Additional Context
Using Brave browser Version 1.17.73 Chromium: 87.0.4280.67 (Official Build) (64-bit)
Also, hooking a button to log ready_state() returns Open. It seams that the timing is borked.

**Comment by alexcrichton** [comment]
Is this perhaps a bug in our WebIDL? Perhaps browsers have changed and/or updated in the meantime and we need to add some new variants?

**Comment by SionoiS** [comment]
Did some research and [W3C](https://www.w3.org/TR/media-source/#mediasource) specify only 3 variants. The [source](https://docs.rs/web-sys/0.3.45/src/web_sys/features/gen_MediaSourceReadyState.rs.html#3) also specify the same. Also looked up rust [nonexhaustive](https://doc.rust-lang.org/reference/attributes/type_system.html) and it is used to force lib users to account for future addition to Enums.

Conclusion, I really don't know where that __Nonexhaustive is coming from...

**Comment by alexcrichton** [comment]
This is [injected by the wasm-bindgen attribute](https://github.com/rustwasm/wasm-bindgen/blob/83cc988cbfa9ced7be419a3429cbd99c74b1fec1/crates/backend/src/codegen.rs#L833) to handle unknown variants. If possible you may want to try to add logging there or otherwise recreate this in JS if you can to see what the string is.

**Comment by SionoiS** [comment]
Well I was wrong! There is no bug. For posterity, be careful what you drop. Rust automatically drop things when they go out of scope. If you drop mediaSource or sourceBuffer it will obviously throw errors.
