### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by grovesNL** [rustwasm/wasm-bindgen#2371]
### Summary

Could we create a new release sometime soon-ish? We're hitting the same problem as mentioned in #1374 and it would be nice if we could update to a new release to avoid this.

### Additional Details

We're trying to use an unpublished version of web-sys/wasm-bindgen from git that contains updated WebGPU bindings, but another (transitive) dependency depends on published releases. This is a problem because two versions of `wasm-bindgen-shared` can't be used currently:
> the package `wasm-bindgen-shared` links to the native library `wasm_bindgen`, but it conflicts with a previous package which links to `wasm_bindgen` as well

(this fails intentionally in this case due to https://github.com/rustwasm/wasm-bindgen/blob/master/crates/shared/Cargo.toml#L15-L18)

We've thought about a couple options to workaround it in the meantime, but neither work well for us:
- Use `patch` to patch all transitive dependencies to use the git version instead. This works alright, but decreases usability because all root crates need to do it too (cc gfx-rs/wgpu-rs#637, gfx-rs/wgpu-rs#644).
- Change all dependencies to use the git version temporarily. This is problematic because we can't easily maintain forks of the full dependency chain.

**Comment by alexcrichton** [comment]
Certainly! I'll go through active PRs/issues and publish later today.

**Comment by grovesNL** [comment]
Thanks again!
