### ISSUE TITLE
Overload resolution failed

### ISSUE THREAD

**Issue by SionoiS** [rustwasm/wasm-bindgen#2374]
### Describe the Bug
[SourceBuffer](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.SourceBuffer.html) [.append_buffer_with_array_buffer()](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.SourceBuffer.html#method.append_buffer_with_array_buffer) & [.append_buffer_with_array_buffer_view()](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.SourceBuffer.html#method.append_buffer_with_array_buffer_view) methods trigger error.
### Steps to Reproduce
1. Create SourceBuffer
```
let media_source = MediaSource::new().unwrap();

let source_buffer = media_source.add_source_buffer(MIME_TYPE).unwrap();
```
2. Append Buffer
```
let array_buffer = <some valid a/v data>

source_buffer.append_buffer_with_array_buffer(&array_buffer).unwrap();
```
3. TypeError: Failed to execute 'appendBuffer' on 'SourceBuffer': Overload resolution failed.
### Additional Context
Same video and the same logic works well in JS.

Found [overload resolution algorithm](https://www.w3.org/TR/WebIDL-1/#es-overloads) but I'm not familiar enough to know exactly what's going on.

**Comment by alexcrichton** [comment]
Hm this does sound bizarre! Would you be able to share your JS snippet that works as well as a Rust snippet that doesn't?

**Comment by alexcrichton** [comment]
Er and by snippet, a full example that I could reproduce with locally would be great!

**Comment by SionoiS** [comment]
Best I can for now...

https://github.com/SionoiS/live-like/blob/vod/web-app/libs.js -> loadVideo function does work
https://github.com/SionoiS/live-like/blob/vod/web-app/src/agents/vod_manager.rs -> Overload resolution failed

Thanks!

**Comment by SionoiS** [comment]
See #2369 I was wrong there's no bug.
