### ISSUE TITLE
Calling `await` on a `JsFuture` results in unexplained dropped promise/future when callback takes too long

### ISSUE THREAD

**Issue by scbrickley** [rustwasm/wasm-bindgen#2379]
### Summary

Is there a way to make a `JsFuture` more resilient to requests that take a long(-ish) time to complete?

### Additional Details
Related issue + further details can be found here: https://github.com/influxdata/flux-lsp/issues/190#issuecomment-733964500

I've got this block of code:

```rust
       spawn_local(async move {
            let future = cln.call_buckets();
            match future {
                Ok(future) => {
                    if let Ok(returned) = future.await { // <---Panic/abort happens here
                        if let Ok(v) = returned.into_serde() {
                            cloned.resolve(v);
                        } else {
                            cloned.resolve(vec![]);
                        }
                    } else {
                        cloned.resolve(vec![]);
                    }
                }
                Err(_) => cloned.resolve(vec![]),
            }
        });
```

`cln.call_buckets()` returns a `Result<JsFuture, String>`. It requests some data from an api and returns it as a vector of strings. When that request is made over a network (or if it's made locally with an artificially throttled internet connection), execution stops on the indicated line, with no panics, aborts, or errors evident in the surrounding code. The associated callback returns fine on the javascript/typescript side of things, and there are no panics or errors reported on the rust side of things, but the result is never returned to this `if let` statement, and the process exits without ever making it past the indicated line. The only clue is an `Uncaught (in promise) Error: undefined` logged in the dev tools console.

To be clear, the `await` call does not return an error. If it did, we would expect the `else` block to to run, and for execution to continue as normal. Instead, the `await`ed callback just never returns.

It seems that if the request takes too long (and by "too long" I mean ~150-180ms), the `future` assumes that it will never be resolved, is dropped, and halts and/or exits execution as a result, as described [here](https://github.com/rustwasm/wasm-bindgen/blob/69546a26c19a5bb75bfb9c5a6a02cf495fc3499d/crates/futures/src/lib.rs#L204-L206). The only issue is, there are no panics or aborts in any of the calling code. The panic seems to be contained within the `wasm_bindgen_futures` crate itself.

Happy to provide further context/explanation if needed.

**Comment by alexcrichton** [comment]
Thanks for the report! There shouldn't be any sort of internal timer on futures so I think the amount of time taken is a red herring here perhaps? 

You mention panics, though? Panics don't really work in Rust on wasm because destructors won't execute which means often-critical cleanup is skipped. Do you think something is panicking though? If so, do you know what's panicking?

**Comment by scbrickley** [comment]
Sorry, I may be using the term 'panic' more loosely than I should be. I guess I should say that execution stops on that `await` call, with no obvious reason why, but only when there's some delay on the associated http request we're `await`ing. I don't know if this is because the code is waiting for a response that never comes, or if the process just exits entirely. The only clues I have found are the `Uncaught (in promise) Error: undefined` error logged in dev tools, and [this comment](https://github.com/rustwasm/wasm-bindgen/blob/a1259031775ad10c3f84f143825ea95d9f5d26d0/crates/futures/src/lib.rs#L204) in `crates/futures/lib.rs`:

```
/// If the `future` provided panics then the returned `Promise` **will not
/// resolve**. Instead it will be a leaked promise. This is an unfortunate
/// limitation of wasm currently that's hoped to be fixed one day!
```

...which sounds suspiciously like what's happening with this bug I'm tracking down: a promise that never returns, only I can't find any panics in our Rust code, nor exceptions thrown in our javascript/typescript code. Everything seems to be behaving normally, except for this one `await` call. So, I'm mostly guessing here, but it seems like the only place left to check is the wasm tooling.

**Comment by alexcrichton** [comment]
Aha yeah an uncaught error in a Rust promise is likely a panic, and that's probably the cause of your issues. Are you able to see  a backtrace associated with the uncaught error? Does it have any wasm frames in it?

**Comment by scbrickley** [comment]
The only thing I have is this error from the dev tools console, which was not super helpful to me:

![wasm-bug](https://user-images.githubusercontent.com/18431450/100766386-974ed800-33c6-11eb-80e3-01348d03594e.png)

**Comment by alexcrichton** [comment]
Oh dear that is indeed not very helpful. Is it possible to avoid webpack temporarily and/or disable the minification and mangling of symbols?

**Comment by scbrickley** [comment]
> Aha yeah an uncaught error in a Rust promise is likely a panic, and that's probably the cause of your issues.

That may be the case, but the promise returns the desired data just fine, even when reproducing the bug. It just never makes it back to the `await` statement, so if there's an uncaught error somewhere, I can't find it.

**Comment by scbrickley** [comment]
> Oh dear that is indeed not very helpful. Is it possible to avoid webpack temporarily and/or disable the minification and mangling of symbols?

Is there an annotation or something I can add to `Cargo.toml` to do that? I'm new to all of this, so I'm not sure what `minification` and `symbol mangling` are.

**Comment by alexcrichton** [comment]
Oh so on the `await` statement the Rust code is waiting on a JS promise, but it sounds like something in there is going awry and causing issues with that JS promise (that's the one which isn't caught perhaps?).

As for webpack, wasm-pack doesn't require webpack AFAIK but if it's entrenched then it's entrenched! It looks like webpack is making function names shorter (e.g. `Ns` in your image) and I suspect that a development (not a release) bundle would probably not do that? I'm not really sure about that. 

In any case if you're able to minimize this to something that I can reproduce locally I can try to help dig in as well.

**Comment by scbrickley** [comment]
Took a look at our tooling and I was using a release build, switched to a development build and still got the unhelpful error output.

I'll try making a minimally reproducible example, but it might take a while, and I can't guarantee it'll be accurate, since I inherited this codebase and am still unfamiliar with some of the setup.

Alternatively, I can give you instructions for setting up the same dev environment, which would be quicker, but would involve a bit of setup on your part.

Which would you prefer?
