### ISSUE TITLE
[wasm-bindgen-typescript] build testing infraestructure

### ISSUE THREAD

**Issue by spastorino** [rustwasm/wasm-bindgen#238]
wasm-bindgen-typescript just landed https://github.com/rustwasm/wasm-bindgen/pull/228.

It needs tests, a lot of test cases actually :). In this issue we can build a testing infraestructure maybe in a similar way that it's done in webidl crate. Check it out here https://github.com/rustwasm/wasm-bindgen/tree/master/crates/webidl/tests

Feel free to ping me on twitter, IRC, email (spastorino everywhere) and I can provide more help to tackle this.

**Comment by kwonoj** [comment]
MS just recently released testing infrastructure for sanity of type : https://github.com/Microsoft/dtslint maybe we could use utilize in some manner?
