### ISSUE TITLE
web-sys 0.3.46 - docs.rs fails to generate documentation

### ISSUE THREAD

**Issue by najamelan** [rustwasm/wasm-bindgen#2380]
The build log: https://docs.rs/crate/web-sys/0.3.46/builds/321002

It looks like rustdoc got killed, so it's maybe using to much resources.

**Comment by alexcrichton** [comment]
Thanks for the report! I opened up an issue at https://github.com/rust-lang/docs.rs/issues/1197 and hopefully something can get changed to fix this.

**Comment by alexcrichton** [comment]
Ok this has been fixed now!

**Comment by najamelan** [comment]
Thanks for the quick intervention.
