### ISSUE TITLE
Can't catch async Wasm traps in JS

### ISSUE THREAD

**Issue by alecmocatta** [rustwasm/wasm-bindgen#2392]
I'm trying to catch Wasm traps in Javascript with `window.addEventListener('error', (event) => { ... })`. This works for some traps, but not for those in [`spawn_local`](https://docs.rs/wasm-bindgen-futures/0.4/wasm_bindgen_futures/fn.spawn_local.html)ed tasks. For those, `window.addEventListener('unhandledrejection', (event) => { ... })` works in Firefox and Safari, but not Chrome or Edge. I guess it's related to https://github.com/getsentry/sentry-javascript/issues/2518, though in my case the Wasm is on the same origin. I'm using the JS generated by wasm-bindgen to load the Wasm.

Unless there's something I'm overlooking this may well be a bug in Chrome/Edge, but a solution/workaround for wasm-bindgen might be to try `queueMicrotask` [here](https://github.com/rustwasm/wasm-bindgen/blob/d6d222c9006d4c834042a1ac8cf2e3ebe5861232/crates/futures/src/queue.rs#L55-L60) and fall back to `Promise.then`? Or catch the promise rejection and [rethrow it using `setTimeout`](https://stackoverflow.com/a/30741722/750875) (ugly!)?

**Comment by alexcrichton** [comment]
Is there a conventional thing that JS typically does here? If we use `queueMicrotask` we'd have to hook that on normal wakeups too for it to work, right? Otherwise it'll only work for immediately-ready things.

**Comment by alecmocatta** [comment]
Traps inside a `queueMicrotask`-queued closure trigger `error` fine. Traps inside a `Promise.then`-queued closure trigger `unhandledrejection` rather than `error`, but seemingly due to a bug on Chrome and Edge neither are triggered from Wasm making the errors uncatchable on the JS side.

My current workaround is to wrap futures passed to `spawn_local` so that polling is wrapped by a JS `try { ... } catch (e) { ... }` block that explicitly invokes my JS error handler. Rethrowing the error using `setTimeout` would also work here.

A conventional JS solution to trigger `error` rather than `unhandledrejection`, for example in [`queueMicrotask` pollyfills](https://github.com/feross/queue-microtask/blob/master/index.js), seems to be using `setTimeout` to rethrow the error outside the Promise chain so it triggers an `error` event rather than `unhandledrejection`. This has the side effect of also solving my issue and making traps catchable from JS.

So either switching to `queueMicrotask`, or using `setTimeout` to rethrow the `error`, both solve this issue.

**Comment by alexcrichton** [comment]
Ok makes sense to me! I don't have a ton of time to implement this myself but would be happy to review a PR!

**Comment by alecmocatta** [comment]
Are we okay with just using `queueMicrotask` (see its [caniuse table](https://caniuse.com/mdn-api_windoworworkerglobalscope_queuemicrotask)) or is the wider support of `Promise.then` needed?

**Comment by alexcrichton** [comment]
I don't really have a good sense. Currently wasm-bindgen doesn't have a policy about browser version numbers to support, we have just been hoping there's a clear-and-obvious reasonable thing to do. There may not be one of those here though unfortunately.

**Comment by pjtatlow** [comment]
@alecmocatta Can you give me a little more detail about your workaround? Is it something that requires a `wasm-bindgen` change? Or no? I would love to be able to get something working soon!

**Comment by alecmocatta** [comment]
@pjtatlow If you have access to the `Promise` you can call `.catch(|e| ...)` to handle the exception. This issue is specifically about the `Promise` that's created internally in `wasm-bindgen-futures` to facilitate [`spawn_local`](https://docs.rs/wasm-bindgen-futures/0.4/wasm_bindgen_futures/fn.spawn_local.html). As it's internal, you need to fork `wasm-bindgen-futures` to add `.catch(|e| ...)`, I think after this: https://github.com/rustwasm/wasm-bindgen/blob/7465a4f84f8047f4acc8e7a2f6ea6977ebea4e58/crates/futures/src/queue.rs#L59

Instead of forking, my workaround is to wrap the future passed to `spawn_local` with the following future:

```rust
#[pin_project]
pub struct TryFuture<F: ?Sized> {
    #[pin]
    f: F,
}
impl<F: ?Sized> Future for TryFuture<F>
where
    F: Future,
{
    type Output = Result<F::Output, ()>;

    fn poll(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
        match try__(|| self.project().f.poll(cx)) {
            Ok(Poll::Ready(t)) => Poll::Ready(Ok(t)),
            Ok(Poll::Pending) => Poll::Pending,
            Err(e) => Poll::Ready(Err(e)),
        }
    }
}

fn try__<O>(f: impl FnOnce() -> O) -> Result<O, ()> {
    let mut f = Some(f);
    let mut o = None;
    try_(&mut || o = Some(f.take().unwrap()()));
    o.ok_or(())
}

#[wasm_bindgen]
extern "C" {
    fn try_(a: &mut dyn FnMut());
}
```
```javascript
function try_(a) {
    try {
        a()
    } catch (e) {
        // handle error here
    }
}
```

Bear in mind this workaround is specifically to handle an exception in a `Promise` where you can't simply add `.catch(|e| ...)` to it.

**Comment by pjtatlow** [comment]
Would this work for an `async fn` too? Or should I create an `async` block to pass into the `TryFuture`?

**Comment by alecmocatta** [comment]
`#[wasm_bindgen(start)] async pub fn main() { ... }` implicitly wraps the `main` function contents with `spawn_local`. You can do similar explicitly, while also wrapping with `TryFuture`:

```rust
use wasm_bindgen_futures::spawn_local;
use futures::FutureExt;

#[wasm_bindgen(start)]
pub fn main() {
    let f = main_async();
    spawn_local(TryFuture { f }.map(drop));
}

async fn main_async() {
    ...
}
```

**Comment by pjtatlow** [comment]
@alecmocatta you have saved me hours of aggravation.  Thank you!
