### ISSUE TITLE
Literal from macro expansion is not accepted in typescript_custom_section since rust 1.47.0

### ISSUE THREAD

**Issue by Frizi** [rustwasm/wasm-bindgen#2393]
### Describe the Bug

Since the update to rust 1.47.0, typescript_custom_section doesn't work with literal captures expanded by macro. 
In previous versions of rust, everything worked as expected.

The reported error is
```
Expected a string literal to be used with #[wasm_bindgen(typescript_custom_section)]
```

### Reproduction

```rust
macro_rules! generate_ts {
    ($lit:literal) => {
        #[wasm_bindgen(typescript_custom_section)]
        const _: &str = $lit;
    };
}

generate_ts!("TEST");
```

The snippet above represent the code that used to work, but doesn't anymore. I've printed the actual AST that `syn::ItemConst::macro_parse` received, and got this:

```rust
Group(
  	ExprGroup {
		attrs: [],
		group_token: Group,
		expr: Lit(
			ExprLit {
				attrs: [],
				lit: Str(LitStr { token: "TEST" })
			}
		)
	}
)
```

Which means, now rust expands the `literal` (and possibly other) captures as an expression group with one item, and this should probably be handled in various places in the parser.

### Current workaround

I managed to fix it in my specific case by using `tt` capture instead of `literal`, but this is obviously more general than i would like.

**Comment by alexcrichton** [comment]
Hm can you confirm what version of Rust you're using? 1.17 is quite old, and I'd recommend using something more in the 1.40 range

**Comment by Frizi** [comment]
@alexcrichton oh sorry, that was totally a typo on my side, the version is 1.48.0, I have confirmed it not working since 1.47.0, and working on 1.46.0.

**Comment by alexcrichton** [comment]
Aha makes sense! I'll try to investigate this this week.
