### ISSUE TITLE
sync-channels panicking

### ISSUE THREAD

**Issue by ineiti** [rustwasm/wasm-bindgen#2406]
### Describe the Bug

I'm trying to use `std::sync::mpsc` to synchronize between the js-world and the wasm-world. Unfortunately I always get the following panicks:

```
sync_channel_bg.js:215 panicked at 'condvar wait not supported', library/std/src/sys/wasm/../unsupported/condvar.rs:21:9
[...]
sync_channel_bg.js:215 panicked at 'cannot recursively acquire mutex', library/std/src/sys/wasm/../unsupported/mutex.rs:22:9
[...]
```

### Steps to Reproduce

I created an example code at https://github.com/ineiti/sync-channel that shows the error. It is mostly the following code:

```rust
#[wasm_bindgen]
pub fn greet() -> Result<(), JsValue> {
    utils::set_panic_hook();
    
    let (s1, r1) = mpsc::sync_channel::<&str>(1);

    let settimeout_callback = Closure::wrap(Box::new(move || {
        log_1(&JsValue::from_str("settimeout_callback"));
        match s1.send("done") {
            Ok(_) => log_1(&JsValue::from_str("OK")),
            Err(e) => log_2(&JsValue::from_str("Error: "),
            &JsValue::from_str(e.to_string().as_str())),
        }
        log_1(&JsValue::from_str("settimeout_callback done"));
    }) as Box<dyn Fn()>);
    window().unwrap().set_timeout_with_callback_and_timeout_and_arguments_0(
        settimeout_callback.as_ref().unchecked_ref(), 1000)?;
    settimeout_callback.forget();
    match r1.recv(){
        Ok(s) => log_2(&JsValue::from_str("Got: "), &JsValue::from_str(s)),
        Err(e) => log_2(&JsValue::from_str("Error: "), &JsValue::from_str(e.to_string().as_str())),
    };

    Ok(())
}
```

I'm quite new to rust/wasm, so I probably copy/pasted the wrong examples together. But I tried different versions of this, and it always failed with the sync-channel failures.

### Expected Behavior

The code should wait on the `r1.recv()` until the `setTimeout` sends the data through.

### Actual Behavior

```
sync_channel_bg.js:215 panicked at 'condvar wait not supported', library/std/src/sys/wasm/../unsupported/condvar.rs:21:9
[...]
sync_channel_bg.js:215 panicked at 'cannot recursively acquire mutex', library/std/src/sys/wasm/../unsupported/mutex.rs:22:9
[...]
```

**Comment by chinedufn** [comment]
Hey

What you're seeing is expected. `Condvar.wait()` is not supported in Rust's stdlib https://github.com/rust-lang/rust/blob/master/library/std/src/sys/unsupported/condvar.rs#L23

I think that that is blocked by https://github.com/rust-lang/rust/issues/77839

In the meantime you can consider using threads https://github.com/rustwasm/wasm-bindgen/tree/master/examples/raytrace-parallel , if they work for your use case.

Cheers

**Comment by ineiti** [comment]
I was afraid it would be expected, but still wanted to make sure there was not a simple trick to overcome it...

Thanks for the link to threads - there are some many warnings in that example that I don't want to go into this minefield.

Is there another channel library that could work? `futures` throws the same error.

**Comment by chinedufn** [comment]
Unfortunately none of my Rust work in the browser uses JS so I don't have any thoughts based on experience.

If all you're trying to do is do nothing until JS gives you a value you could try:

1. Run your Rust in a rAF loop
2. Have your Rust code poll a JS function for whatever you need
3. If you get what you need use it, otherwise try again next frame.

---

Another alternative is https://rustwasm.github.io/docs/wasm-bindgen/reference/js-promises-and-rust-futures.html

Really depends on what you're trying to do.

---

Note that I haven't used either of the above approaches so YMMV

**Comment by ineiti** [comment]
Thanks a lot for the pointers. I ended up polling the channel using `Receiver<>.try_iter().next()` and then call out to a `setTimeout` so JS has the time to actually fill in my channel. I hope I find a nicer method...

Shall I close this issue, or leave it open in the hope that this gets fixed sometimes?

**Comment by chinedufn** [comment]
Nice!

This is less of a wasm-bindgen issue and more of an synchronization primitives in the wasm world at large are still a work in progress - so I'd say you can close this issue.

Good luck with your work
