### ISSUE TITLE
Make test runner use Deno instead of Node

### ISSUE THREAD

**Issue by olanod** [rustwasm/wasm-bindgen#2418]
When testing WASM code is often desirable to run it in a lighter weight environment instead of a full browser, `wasm-bindgen-test-runner` does this running the tests in Node.js but if one uses Web APIs there's not much that can be done but run in a browser with wasm-pack(not maintained?). Deno is more aligned with the APIs that are found in a browser environment which makes it a better runtime in my opinion, or perhaps more interestingly embedding the [`deno-runtime`](https://crates.io/crates/deno_runtime) in the test runner so the binary is self-contained. The Node version could also be kept around as alternative to the Deno one.

**Comment by alexcrichton** [comment]
Thanks for the report! I don't think it makes sense to switch the defaults per se, but adding support to have it as an option seems reasonable!

**Comment by daxpedda** [comment]
I personally prefer Deno over Node.js as well. However, I'm in favor of removing the default entirely and force users to choose.

In any case, changing the default would require a breaking change anyway, so instead I would remove the default in the next breaking change.
