### ISSUE TITLE
Add a reference for which types can cross the wasm ABI boundary

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-bindgen#242]
In a new `reference.md` document, we should have a table documenting all the types that `wasm-bindgen` can send/receive across the wasm ABI boundary, like this:

| Type | `T` parameter | `&T` parameter | `&mut T` parameter | `T` return value |
|:---:|:---:|:---:|:---:|:---:|
| `u32` | Yes | Yes | Yes | Yes |
| `str` | No | Yes | Yes | No |

```markdown
| Type | `T` parameter | `&T` parameter | `&mut T` parameter | `T` return value |
|:---:|:---:|:---:|:---:|:---:|
| `u32` | Yes | Yes | Yes | Yes |
| `str` | No | Yes | Yes | No |
```

Etc.

For folks who want to help fill this table in, to figure out what is supported in what positions:

* `FromWasmAbi` corresponds to `T` parameter
* `RefFromWasmAbi` corresponds to `&T` parameter
* `RefMutFromWasmAbi` corresponds to `&mut T` parameter
* `IntoWasmAbi` corresponds to `T` return values (reference return values are not supported yet)

See `src/convert.rs` for details.

This is a great way to dive into the wasm-bindgen codebase! We also don't have to do everything at once, and can fill this table out in multiple PRs -- it is ok if a PR does not completely document everything (as long as the things it does document aren't wrong).

**Comment by jannikkeye** [comment]
I have a question about this macro usage:

```
vectors! {
    u8 i8 u16 i16 u32 i32 u64 i64 f32 f64
}
```

Does the macro implement the traits for each type in there or for vectors of type T ie. u8, i8 etc.?

**Comment by alexcrichton** [comment]
@jannikkeye ah so with the `vectors!` macro each type in there [expands to implementations of](https://github.com/rustwasm/wasm-bindgen/blob/9339a55f3eb4d294a0d001d509238bfa4a0ece8f/src/convert.rs#L221-L294):

* `IntoWasmAbi for Box<[T]>` - you can pass `Box<[T]>` and `Vec<T>` to JS
* `FromWasmAbi for Box<[T]>` - you can take `Box<[T]>` and `Vec<T>` as an argument from JS
* `IntoWasmAbi for &[T]` - you can pass `&[T]` to JS
* `IntoWasmAbi for &mut [T]` - you can pass `&mut [T]` to JS
* `RefFromWasmAbi for [T]` - you can take `&[T]` as an argument from JS
* `RefMutFromWasmAbi for [T]` - you can take `&mut [T]` as an argument from JS

For `str` the bare type isn't workable from you can take and pass `&str` to JS, but I believe you're right in that `&mut str` is a mistake, that's not supported just yet.

**Comment by jannikkeye** [comment]
@alexcrichton thank you for the clarification. I will start working on this later today, as I think it will be helpful to everyone starting out with warm-bindgen.

**Comment by alexcrichton** [comment]
Done with https://github.com/rustwasm/wasm-bindgen/pull/383, yay!
