### ISSUE TITLE
Problem calling JS functions from Rust with WasmerJS/WASI in the browser

### ISSUE THREAD

**Issue by happybeing** [rustwasm/wasm-bindgen#2422]
### Summary

I'm trying to build a browser WASI app using WasmerJS and Rust. I can call parameterless Rust functions from JS and vice versa, but as soon as the Rust imports a JS function which has parameters I have a problem. This is with a WasmerJS/WASI app and the Rust compiled to target `wasm32-wasi`.

I'm not using `wasm-pack` or `cdylib` because I'm coming from a WasmerJS/WASI direction, and am not sure how to do this for target `wasm32-wasi`.

### Additional Details
The working example is on branch `main` and the error on `wasm-bindgen-jsparams` of https://github.com/happybeing/svelte-wasi-with-rust

I have a test Svelte app which uses WasmerJS/WASI in the browser, and a Rust subsystem which can share the wasmFS filesystem with the App JavaScript. I've added bindings and can call Rust/WASI functions from the App JS and vice versa, so long as I leave the Rust `main(){}` empty.

When I add parameters to my test JavaScript function and try to call this from Rust I get an error on `WebAssembly.instantiate()` in the browser console:

```
App.svelte:73 Uncaught (in promise) TypeError: WebAssembly.instantiate(): Import #2 module="./wasi-example_bg.js" error: module is not an object or function
    at startWasiTask
```
This following import only appears when the Rust is importing a JS function which has parameters, and seems to be the cause of the error:
```
(import "./wasi-example_bg.js" "__wbg_jstestn_2988839aa0c9917f" (func $wasi_example::js_test_n::__wbg_jstestn_2988839aa0c9917f::h573713d50e0d1da7 (type $t2)))
```

JavaScript being called from Rust (test.js):
```javascript
export function js_test() {
    console.log("hello from js_test()")
}

export function js_test_n(n) {
    console.log("hello from js_test_n(): ", n)
}
```
The Rust in main.rs:
```rust
#[wasm_bindgen(module = "test")]
extern "C" {
    fn js_test();
    fn js_test_n(n: u32);
 }

#[wasm_bindgen]
pub fn rust_js_test() {
    println!("Rust calling js_test()...\n");
    js_test();

    println!("Rust calling js_test_n(123)...\n");
    js_test_n(123);
}
```
This generates wasm-example_bg.js:
```javascript
import { js_test_n } from 'test';
import * as wasm from './wasi-example_bg.wasm';

function logError(f) {
    return function () {
        try {
            return f.apply(this, arguments);

        } catch (e) {
            let error = (function () {
                try {
                    return e instanceof Error ? `${e.message}\n\nStack:\n${e.stack}` : e.toString();
                } catch(_) {
                    return "<failed to stringify thrown value>";
                }
            }());
            console.error("wasm-bindgen: imported JS function that was not marked as `catch` threw an error:", error);
            throw e;
        }
    };
}

export const __wbg_jstestn_2988839aa0c9917f = logError(function(arg0) {
    js_test_n(arg0 >>> 0);
});
```

**Comment by corwin-of-amber** [comment]
Wow, it is thrilling to see how this project is coming along.

This is a total shot in the dark here because I don't understand what wasm-bindgen is doing; but it seems like you are expected to import the generated `wasi-example_bg.js` somehow. Right now your JS side (in `App.svelte`) just imports `test`, in both branches.

Then you probably need to pass *that* module to WASI as imports, smt along the lines of:
```js
imports = {'./wasi-example_bg.js': await import('./wasi-example_bg.js')}
```

**Comment by alexcrichton** [comment]
Yes it looks likee this is missing an import? I'm not sure how things are set up in the environment that you're using but I don't think that this is an issue with wasm-bindgen itself, so I'm going to close. Unfortunately I can't offer too much help of using wasm-bindgen in nonstandard environments because there's so many variables in play.

**Comment by happybeing** [comment]
@alexcrichton thanks for reviewing this and I agree it doesn't belong here so have resumed it on this wasmerJS [issue](https://github.com/wasmerio/wasmer-js/issues/250#issuecomment-763004958). If you can have a look at that comment I'd appreciate any pointers on how wasm-pack + wasm-bindgen handles this. I'm thinking that if I can see how it happens there I might be able to figure out how to get it to work with wasmerJS/WASI, but I don't yet understand much about how either system, or wasi itself works under the hood and I'm not sure where to look.
