### ISSUE TITLE
WebIDL integration tests

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-bindgen#243]
Right now, WebIDL tests are just asserting that the output of compiling some webidl exactly matches what we expect.

We should have integration tests and infrastructure where to write a test you supply:

* a WebIDL source string
* a JS polyfill for the things described in that WebIDL
* a `src/lib.rs` that exports a `#[wasm_bindgen] pub fn run()` function that *uses* the things described in that WebIDL (via `mod bindings;`)

Then, the testing infrastructure will:

* use `wasm_bindgen_webidl` in a `build.rs` to emit `wasm-bindgen` imports into a file in the build's `out` directory
* add a `src/bindings.rs` module that does `include!(...)` of the file created in `build.rs`
* add a `test.ts` that calls the user-defined `run` function

It shouldn't be too hard to extend the existing `project()`-based test infrastructure used in `tests/all/*` (and defined in `tests/all/main.rs`) to do this stuff.

**Comment by ohanar** [comment]
Implemented in #264. It should support auto-generating `test.ts` files that will call `#[wasm_bindgen] pub fn test()`, however given that constructors aren't implemented at the moment, the basic example doesn't currently use it (although this example does demonstrate that you can still use a custom `test.ts` for webidl if needed for a test).

**Comment by ohanar** [comment]
Fixed in #264.
