### ISSUE TITLE
Current state of WASM threads

### ISSUE THREAD

**Issue by d3lm** [rustwasm/wasm-bindgen#2433]
I wanted to ask what the current status is of WebAssembly threads with Rust. I know there is [this](https://rustwasm.github.io/2018/10/24/multithreading-rust-and-wasm.html) article, which shows how to use threads with wasm-bindgen, however, it's not using the std threads API. I know threads have shipped in Chrome and Firefox and the C++ `pthread_create` does work. How about Rust? Are there any plans to support `std::thread` so that we can do something like this in Rust?

```rs
thread::spawn(|| {
  // ...
});
```

**Comment by alexcrichton** [comment]
I wrote up a bit awhile back at https://github.com/rust-lang/rust/issues/77839, and unfortunately I don't think much has changed in the meantime.
