### ISSUE TITLE
Why does `web_sys::AudioBuffer::copy_to_channel*` need a mutable buffer argument?

### ISSUE THREAD

**Issue by kerskuchen** [rustwasm/wasm-bindgen#2434]
### Summary

I hope this is the correct place to ask this. Currently I am slightly confused as to why the APIs

`web_sys::AudioBuffer::copy_to_channel` 
https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.AudioBuffer.html#method.copy_to_channel

and 

`web_sys::AudioBuffer::copy_to_channel_with_start_in_channel` 
https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.AudioBuffer.html#method.copy_to_channel_with_start_in_channel

need their first argument (the source buffer to be copied from) to be mutable.

### Additional Details

https://developer.mozilla.org/en-US/docs/Web/API/AudioBuffer/copyToChannel

**Comment by alexcrichton** [comment]
There's a [whitelist of functions](https://github.com/rustwasm/wasm-bindgen/blob/906fa91cb834e59f75b0bfa72e4b49e55f51c9de/crates/webidl/src/constants.rs#L44-L92) which are known to not need mutable slices, and it looks like this isn't on that list.

**Comment by kerskuchen** [comment]
Ah thanks for the clarification. I will try make a PR then to fix this.
