### ISSUE TITLE
Uncaught DOMException on Firefox when working with vecs in a sub-scope 

### ISSUE THREAD

**Issue by TKGgunter** [rustwasm/wasm-bindgen#2439]
### Description of Bug

When running a function from wasm lib where one has created a std::Vec, the process of pushing an element into this vec from a sub scope causes Firefox to occasionally crash with 
"""Uncaught DOMException: An attempt was made to use an object that is not, or is no longer, usable """.

### Steps to Reproduce

1. Construct a function that creates a vec. This cannot be the start function.
2. In a sub-scope, like a for loop, push an element into the vec.
3. When in js function call this function
4. Js function must include a requestAnimationframe function. 

Following is a code example that replicates the problem.

lib.rs:
```
use wasm_bindgen::prelude::*;
use wasm_bindgen::JsCast;
 
 
const WIDTH : usize = 600;
const HEIGHT : usize = 600;
 
#[no_mangle]
static mut BUFFER: [u32; WIDTH * HEIGHT] = [0; WIDTH * HEIGHT];
 
 
#[wasm_bindgen]
pub fn testing()->usize{
//NOTE this is the function of interest.
//It does not matter if we set the capacity of the fector
    let mut v : Vec<f32>= Vec::with_capacity(10);
    v.push(0f32);
    v.push(0f32);
    v.push(0f32);
    let mut _v = 0;
//NOTE
//Error occurs if we are in a for loop or in a normal subscope.
    //{
    for _ in 0..20{
        _v += v[2] as i32;
        v.push(0f32);
    }
    return v.len();
}
 
 
#[wasm_bindgen(start)]
pub fn start() -> Result<(), JsValue> {unsafe{
 
    let window = web_sys::window().unwrap();
    let document = web_sys::window().unwrap().document().unwrap();
    let canvas = document
        .get_element_by_id("canvas").unwrap()
        .dyn_into::<web_sys::HtmlCanvasElement>()?;
    let body = document.body().expect("document should have a body");
    body.append_child(&canvas)?;
 
    //testing(); //NOTE this is the function of interest
                 //if uncommented the example works
 
 
    Ok(())
}}
```
 
index.html:
```
<html>
  <head>
    <meta content="text/html;charset=utf-8" http-equiv="Content-Type"/>
  </head>
  <body>
    <!-- Note the usage of `type=module` here as this is an ES6 module -->
    <script type="module">
 
      import init, { testing } from './pkg/paint.js';
      async function run() {
 
        let wasm = await init('./pkg/paint_bg.wasm');
        const width = 600;
        const height = 600;
 
        const canvas = document.getElementById("canvas");
 
        canvas.width = width;
        canvas.height = height;
 
        const buffer_address = wasm.BUFFER.value;
        const image = new ImageData(
            new Uint8ClampedArray(
                wasm.memory.buffer,
                buffer_address,
                4 * width * height,
            ),
            width,
        );
        testing();
        const ctx = canvas.getContext("2d");
        const render_loop = () => {
 
          ctx.putImageData(image, 0, 0);
          requestAnimationFrame(render_loop);
        };
        render_loop();
 
 
      }
      run();
    </script>
    <canvas id="canvas"></canvas>
  </body>
</html>
```

### Expected Behavior

I expected behavior to be consistent with Chrome, where there were no issues.

### Actual Behavior

Crash with the following error:
"""Uncaught DOMException: An attempt was made to use an object that is not, or is no longer, usable """.

### Additional Context

Issue specifics:
 
Bug does not occur when testing in Chrome or using #[test]. 
Bug does not occur when operations occur within a #[wasm_bindgen(start)] function.
Bug does occur when wrapped in function wrapped in a #[wasm_bindgen] called from js.
Bug does occur when wrapped in a function and called by a function being called from js.
Bug does not occur wrapped in a function, but called from #[wasm_bindgen(start)] function.
Bug does not occur if wrapped in a function and called by both #[wasm_bindgen(start)] function and other functions being called from js.
Bug occurs if a requestAnimationFrame loop has been created and called. Loop does not have to call offending code, it can be called else where from js. If there is no loop the error does not occur. 

tools:
    + Firefox   version 84.0.2 (64-bit) Linux
    + Chrome    version 87.0.4280.88 (64-bit) Linux
    + rustc     version 1.47.0 (18bf6b4f0 2020-10-07)
    + wasm-pack version 0.9.1
    + pythin3   simple server

dependancies:
    + js-sys "0.3.46"
    + wasm-bindgen  "0.2.69"
    + web-sys "0.3.4"
 
compile command:
    wasm-pack build --release --target web
OR
    wasm-pack build --target web

**Comment by alexcrichton** [comment]
Thanks for the report! Is it possible to minimize this at all? It seems unlikely that wasm-bindgen is the source of the bug here, it may just be how the browser behaves?

**Comment by TKGgunter** [comment]
Hey, yeah the bug is so weird I wasn't sure who to report it to. The rust discord didn't seem to know much, so I posted it here. As for minimizing would you like to me to link the code example in a github project. I can do this or is there something else you have in mind.

**Comment by alexcrichton** [comment]
I unfortunately don't have a ton of time to minimize this myself. It's probably good to get a reference in case someone else has time to come along and minimize it, though.

**Comment by jonboj** [comment]
Just try to grab in the structure from the posted info. The `js-render_loop` seems to interfere with the memory used by the vector manipulations. 

As suggested maybe try to minimize/cleanup the project. Many frameworks in play and especially the `DOM` is hard to overview, anyhow 2 minor things could maybe contribute to cleanup.

- Looks like the element `<canvas id="canvas"></canvas>` in the rust `start` function is added to the `body` element with `body.append_child(&canvas)?;` But this element from the `index.html` already is attached to the `body` element, so this add could look superfluous and maybe cause problems to the `DOM`.

- The rust `start` function is marked `unsafe`. For a cleanup maybe possible to narrow down, so the vector manipulation in the `testing` function is extracted out of the `unsafe` section.

**Comment by TKGgunter** [comment]
Hello, sorry for the delay. This past month has been pretty hectic for me.

I've simplified the example, and it does seem like jonboj's suggestion is correct.  The js-render_loop seems to interfering with the memory used by the vector. Below is the simplified example. You can also find a copy in this git repo [here](https://github.com/TKGgunter/wasm_example_error).
Since my last post I've updated firefox and I get a new error, `Uncaught (in promise) DOMException: CanvasRenderingContext2D.putImageData: Invalid width or height`, again this seems to cooperate jonboj's suggestion. If all optional inputs are given to putImageData the error does not occur.

lib.rs
```
use wasm_bindgen::prelude::*;
use wasm_bindgen::JsCast;
const WIDTH : usize = 600;
const HEIGHT : usize = 600;

#[no_mangle]
static mut BUFFER: [u32; WIDTH * HEIGHT] = [0; WIDTH * HEIGHT];

#[wasm_bindgen]
pub fn testing(){
//NOTE this is the function of interest.
//It does not matter if we set the capacity of the fector
    let mut v : Vec<f32>= Vec::with_capacity(10);
    v.push(0f32);
    v.push(0f32);
    v.push(0f32); //NOTE: This push creates the error. If this is commented it out there would be no error.
}


#[wasm_bindgen(start)]
pub fn start() -> Result<(), JsValue>{

    //testing(); //NOTE this is the function of interest
                 //if uncommented the example works

    Ok(())
}
```
index.html
```<html>
    <head>
      <meta content="text/html;charset=utf-8" http-equiv="Content-Type"/>
    </head>
    <body>
       <!-- Note the usage of `type=module` here as this is an ES6 module -->
       <script type="module">

            import init, { testing } from './pkg/paint.js';
            async function run() {

              let wasm = await init('./pkg/paint_bg.wasm');
              const width = 600;
              const height = 600;

              const canvas = document.getElementById("canvas");

              canvas.width = width;
              canvas.height = height;

              const buffer_address = wasm.BUFFER.value;
              const image = new ImageData(
                  new Uint8ClampedArray(
                      wasm.memory.buffer,
                      buffer_address,
                      4 * width * height,
                  ),
                  width,
              );

              testing();
              const ctx = canvas.getContext("2d");
              const render_loop = () => {
                ctx.putImageData(image, 0, 0);
                requestAnimationFrame(render_loop);
              };
              render_loop();

            }
            run();

      </script>
    <canvas id="canvas"></canvas>
    </body>
</html>
```

**Comment by jonboj** [comment]
From the github project reproduced the behavior above in Firefox 85, Ubuntu 20.10 - `Uncaught (in promise) DOMException: CanvasRenderingContext2D.putImageData: Invalid width or height`.

To minimize the problem further, removed the render loop
https://github.com/TKGgunter/wasm_example_error/blob/main/index.html#L32-L37

Added
```
  function sleep(ms) {
       return new Promise(resolve => setTimeout(resolve, ms));
   }
 import init, { testing } from './pkg/paint.js';
...

console.log("Before testing");
console.dir(image);
await sleep(500);
testing();
console.log("After testing");
console.dir(image);
```
The console log shows that when `testing` is called `Uint8ClampedArray` looses its data. This is constructed as
```
  new Uint8ClampedArray(
      wasm.memory.buffer,
      buffer_address,
      4 * width * height,
  )
```
`Uint8ClampedArray` is constructed by reference to `wasm.memory.buffer` https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Memory/buffer
From the documentation I interpret this as the total raw wasm memory buffer.

Not sure, but interpret this behavior as the `v.push(0f32);` on Rust side affects the raw wasm memory buffer and since the data array on javascript side is by reference the javascript array somehow get corrupted.
At first sight maybe not related to `wasm-bindgen` more likely to the javascript interaction with wasm memory.

**Comment by CrimsonCodes0** [comment]
Pushing to the Rust Vec<_> occasionally causes reallocations, which directly lead to pointer invalidation and memory corruption.

Upon mutating the vector's length, you could update the JS reference to use the updated pointer (if it changed), or reconstruct the JS TypedArray with every call.

Overall, this is a reference lifetime problem.

**Comment by CrimsonCodes0** [comment]
@jonboj In your test, after the loop, was the JS TypedArray's length zero? Can you check?

If it is, them the Wasm heap was grown via Wasm memory.grow instruction, or something of the sort. When they are executed all JS TypedArray's have their buffers detached, so the ImageData received data indicating that it's u8 array should be of a certain size, yet the buffer was too small.

**Comment by jonboj** [comment]
Great! Checked, yes JS TypedArray has length zero. Below is attached screendump from Firefox dev-console .

![imagedata_before_after](https://user-images.githubusercontent.com/7474093/111811911-d3f00200-88d7-11eb-8c42-3e36c91089db.png)

**Comment by TKGgunter** [comment]
Thanks for your help everyone.  I'd like to confirm what happened before I close the ticket. 

`wasm.memory.buffer` contains a reference to some memory associated with the wasm module. When pushing to the Rust Vec<..> the memory buffer may be reallocated, such that the original reference is stale. This effect seems to happen on a subset of browsers. To get consistent behavior, "image" must be updated with the correct `wasm.memory.buffer` reference after wasm(Rust) functions that allocate are called.  

If my interpretation is incorrect please let me know. Also does anyone have a guess as to why this doesn't happen on all browsers?

**Comment by CrimsonCodes0** [comment]
Wait, you didn't get errors on Chromium? What happened on Chromium?

___

I'll check Chromium's behavior myself in a few hours, but I presume that there might be a browser bug at work here.

**Comment by TKGgunter** [comment]
When I run on Chrome, I get no error. 
Chrome:
Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by CrimsonCodes0** [comment]
@TKGgunter Yup, can confirm, I get the same effect, I'll open a crbug report, since they just allowed OOB access to non-existant buffer data in my quick JS example.

You could close the issue if you like, since the *potential* spec or Chromium bug isn't directly related to wasm-bindgen.

**Comment by TKGgunter** [comment]
Thanks a bunch!

**Comment by Hapyr** [comment]
Hey, I have a similar issue and realized that this bug still exists. Are there any updates on this?

**Comment by daxpedda** [comment]
From a quick glance it seems to me that this was not a bug after all, but a misuse of the API causes memory corruption.

It would probably be best if you just post your issue in Discussions if you want help.

(sorry for the late response!)
