### ISSUE TITLE
Ignore anything that has `ChromeOnly` extended attribute

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-bindgen#244]
Context: `ChromeOnly` is for things that are only exposed to priveleged code in Firefox (where we have been getting our WebIDL sources from). These items aren't exposed to the Web, so we don't want to generate bindings to them.

I'm imagining a `is_chrome_only` function that takes extended attributes and returns `bool`. Then we would check the extended attributes on interfaces, attributes, dictionaries, and operations with this function. If it returns true, and is ChromeOnly, then we would skip the item and not emit imports to it.

**Comment by teovoinea** [comment]
I’d like to pick this issue up! 😊

**Comment by fitzgen** [comment]
Awesome! Let me know if you have any questions. The WebIDL frontend lives in `crates/webidl`, and you can run its tests via `cargo test` within that directory, see `crates/webidl/tests/*`.

**Comment by teovoinea** [comment]
Just to clarify, when you said "takes extended attributes", did you mean one function for each of [these](https://docs.rs/webidl/0.6.0/webidl/ast/index.html) `*ExtendedAttribute` structs?

**Comment by fitzgen** [comment]
Yeah, for example: https://github.com/rustwasm/wasm-bindgen/blob/master/crates/webidl/tests/fixtures/Event.webidl#L45

**Comment by ohanar** [comment]
Fixed by #303.
