### ISSUE TITLE
expression has type externref but expected i32 

### ISSUE THREAD

**Issue by domoritz** [rustwasm/wasm-bindgen#2446]
### Describe the Bug

When I compile my project with `--reference-types`, I get `expression has type externref but expected i32` in Firefox (nightly 87.0a1 (2021-02-04) as well as beta) and Chrome (with flags to enable reference types). 

### Steps to Reproduce

1. Clone https://github.com/domoritz/arrow-wasm/tree/bc8cc58b0cdedf4754a190de62b6d5a088ac40b5
2. Install wasm bindgen cli
3. Run `yarn build`
4. Start python web server
5. Go to http://localhost:8000/examples/index_web.html (ideally in FF so you don't need extra flags to enable reference types)
6. See error

### Expected Behavior

Without `--reference-types` the library works so I would expect it to work with the flag as well. 

### Actual Behavior

Error `expression has type externref but expected i32`.

<img width="874" alt="Screen Shot 2021-02-04 at 21 44 52" src="https://user-images.githubusercontent.com/589034/106953046-c810fd80-66e6-11eb-8572-ab57a553e3c1.png">

**Comment by alexcrichton** [comment]
Would you be able to upload the wasm file? Additionally could you clarify which wasm-bindgen-cli version you're using?

**Comment by domoritz** [comment]
Thanks for looking into my issue. `wasm-bindgen v0.2.70`. I uploaded the lockfile and wasm files to https://github.com/domoritz/arrow-wasm/tree/dom/reference-types (wasm file is at https://github.com/domoritz/arrow-wasm/blob/dom/reference-types/pkg/arrow_wasm_bg.wasm).

**Comment by alexcrichton** [comment]
Was this file perhaps run through `wasm-opt`? If you disable that does it work for you?

**Comment by domoritz** [comment]
I don't think so. This is my build script. 

<img width="735" alt="Screen Shot 2021-02-08 at 18 04 16" src="https://user-images.githubusercontent.com/589034/107254919-9fda1500-69ec-11eb-86ca-2f22eb9eb0bd.png">

**Comment by alexcrichton** [comment]
Ok thanks for clarifying! I dug in a bit and this should be fixed in https://github.com/rustwasm/wasm-bindgen/pull/2450. Thanks again for the report!

**Comment by domoritz** [comment]
Awesome. I'm glad I could help. Thank you for the fix (and all your work on the Rust wasm ecosystem)!
