### ISSUE TITLE
get_channel_data does not return a mutable reference to the memory

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [rustwasm/wasm-bindgen#2455]
### Describe the Bug

Related to the bug in CPAL [here](https://github.com/RustAudio/cpal/issues/543), I have discover that usage of `get_channel_data` is fully supported today, not like `copy_to_channel`.

But today the definition of [get_channel_data](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.AudioBuffer.html#method.get_channel_data) returns a copy of the buffer into a `Vec<u8>`.
So it's impossible to copy the data into the buffer memory.

### Expected Behavior

Be able to return a reference to the memory of the `Buffer`.
The expected signature of the method seems to be something like:
```rust
pub fn get_channel_data(this: &AudioBuffer, channel: u32) -> Result<&mut Vec<f32>, JsValue>;
```

**Comment by alexcrichton** [comment]
The only way to fix this at this time would be to change the return value to `Float32Array` or similar I think. I suspect that to implement that we would need to have a special case for this API since it would differ from how all other APIs are bound.

**Comment by MarcAntoine-Arnaud** [comment]
Made sense. But do you know any API that returns a non-mutable array in Javascript ?
For me everything in Javascript is returned without a hard copy, so it's direct access to the memory in read/write mode...

Just by curiosity, do you know if `idl` format can help to define the mutable status of the returned value ?

**Comment by alexcrichton** [comment]
AFAIK WebIDL doesn't have a way to convey the mutability semantics and/or semantics about where the buffer is pointing. We could perhaps annotate the WebIDL ourselves, however, by inventing attributes for wasm-bindgen

**Comment by MarcAntoine-Arnaud** [comment]
I close it as the release of Safari 14.1 (Released 2021-04-26) fix it.
