### ISSUE TITLE
need example of sharing memory between JS and Rust

### ISSUE THREAD

**Issue by mvolkmann** [rustwasm/wasm-bindgen#2456]
I want to create a `Float64Array` in JS code and make it available to a Rust function through shared memory without passing/copying it. I've spent quite a bit of time looking for an example of doing this and haven't found one. Does wasm-bindgen support this? If so, can you point me to an example?

**Comment by chinedufn** [comment]
Hey there.

I think that this should do the trick -> https://rustwasm.github.io/wasm-bindgen/reference/types/pointers.html

**Comment by chinedufn** [comment]
Sorry let me clarify.

One approach off the top of my head would be to:

-  Allocate a `Vec<f32>` on the Rust side with whatever capacity that you need and return a pointer to it `*mut f64`.

- Create a `Float64Array` using the wasm memory buffer. The second and third argument for a new typed array allow you to specify the start and end index within the underlying buffer.

**Comment by mvolkmann** [comment]
@chinedufn Thanks so much! I think I'm close to having this working. After populating the shared memory on the JS side I pass the pointer and the number of elements to the Rust side. In the Rust code I can iterate over the numbers, but I don't know how to get them. I assume I have to do something like this with an `unsafe` block.

```rust
#[wasm_bindgen]
pub fn sum(ptr: *mut f64, count: usize) -> f64 {
    let mut sum = 0.0;
    unsafe {
        for i in 0..count {
            let number = ptr[i * 8] as f64; // THIS LINE IS WRONG!
            sum += number; 
        }
    }
    sum
}
```

**Comment by mvolkmann** [comment]
I have it working now, but the Rust version still is much slower than the JS version.
See https://github.com/mvolkmann/wasm-bind-demo/blob/11d4cf749c102078e0b8687b6527ac7f77bee8f5/index.js#L45
and https://github.com/mvolkmann/wasm-bind-demo/blob/11d4cf749c102078e0b8687b6527ac7f77bee8f5/src/lib.rs#L17.

**Comment by chinedufn** [comment]
Potential reasons:

- You're allocating memory in your Rust microbenchmark, but not in JS https://github.com/rustwasm/wasm-bindgen/blob/master/crates/js-sys/src/lib.rs#L4990-L4995

- There is overhead with going from JS -> Wasm -> JS

- Your JS engine might be doing a good job of optimizing your sum function

- You are not compiling your Rust code in release mode

You might be running into any number of those.

Glad it all works. If you're in good shape feel free to close this issue.

Good luck.

**Comment by chinedufn** [comment]
Also you'll want to store that `Vec<f64>` somewhere. You're dropping it and thus freeing the memory that backs it.

Something like:

```rust
#[wasm(bindgen)]
struct MyApp {
    my_data: Vec<f32>
}

#[wasm_bindgen]
impl MyApp {
    #[wasm_bindgen(constructor)]
    fn new (capacity: usize) -> Self {
        MyApp { my_data: Vec::with_capacity(capacity) }
    }
}
```

Then when you are summing you don't need to allocate a new vector.

Although, as alluded to above, summing might not be the most informative/realistic/useful benchmark. I'm just sharing some tips under the assumption that you're mainly just experimenting.

**Comment by mvolkmann** [comment]
Interesting. If I use this approach of preallocating the vector by creating an instance of `MyApp` where does that instance get created ... that is where should I place the call to `MyApp::new()`?

**Comment by chinedufn** [comment]
Take a look here https://rustwasm.github.io/docs/wasm-bindgen/reference/attributes/on-rust-exports/constructor.html

**Comment by chinedufn** [comment]
If you haven't already, have a look at the game of life tutorial https://rustwasm.github.io/book/introduction.html .

**Comment by domoritz** [comment]
Also see https://github.com/rustwasm/wasm-bindgen/issues/1643 and https://github.com/rustwasm/wasm-bindgen/issues/1993#issuecomment-583614609.

**Comment by domoritz** [comment]
Here is what I did. I allocate a vector is WASM and then pass it as a view (via view_mut_raw) to JS. I can then write a function that expects an `WasmUint8Array` and reads its buffer (e.g. `data.0`).

```rust
#[wasm_bindgen]
pub struct WasmUint8Array(Vec<u8>);

#[wasm_bindgen]
impl WasmUint8Array {
    #[wasm_bindgen(constructor)]
    pub fn new(size: usize) -> Self {
        let buffer = vec![0; size];
        Self { 0: buffer }
    }

    #[wasm_bindgen(getter, js_name = buffer)]
    pub fn buffer(&mut self) -> js_sys::Uint8Array {
        unsafe { js_sys::Uint8Array::view_mut_raw(self.0.as_mut_ptr(), self.0.len()) }
    }
}
```

**Comment by alexcrichton** [comment]
I think everything here looks like it's been answered and handled (thanks @chinedufn!), so I'm going to close.
