### ISSUE TITLE
Implicit cast to number on bool return type (update documentation?)

### ISSUE THREAD

**Issue by Tythos** [rustwasm/wasm-bindgen#2459]
### Describe the Bug

Documentation (https://rustwasm.github.io/docs/wasm-bindgen/reference/types/bool.html) indicates Rust "bool" type should be natively cast to "boolean" when returned to JavaScript via wasm bindgen decorators. However, replication of demo on linked doc page results in inconsistent typeof() results ("number"). This may be related to build configuration ("no module"?).

### Steps to Reproduce

1. Go to 'https://rustwasm.github.io/docs/wasm-bindgen/reference/types/bool.html'
2. Use Rust code snippet to build a WASM module
3. Resolve "return_bool()" export and invoke
4. Check type of result

You can clone a snapshot of these results from [a test repository I have created](https://github.com/Tythos/wasm-bindgen-casting). Running the "run-standalone.bat" script will build the WASM module from "hello-wasm-standalone/src/lib.rs", copy it to the static files under "site-local-require/", and host them with a local server, at which point you can browse to "localhost:8000".

### Expected Behavior

I would expect typeof() to verify that wasm bindgen had cast to a boolean value, as stated in documentation.

### Actual Behavior

The value returned from the export has typeof number.

### Additional Context

This isn't really a deal-breaker. But if it does reflect desired behavior (and isn't a "no-modules" side effect or some other result of the build / test case configuration), maybe documentation should be updated.

**Comment by alexcrichton** [comment]
Thanks for the report! Are you sure this isn't a bug in the other JS you've got in your project? I double-checked the output and for the `return_bool` function called from your `index.js` as-defined by wasm-bindgen clearly returns `return ret !== 0;`, so I think it's returning a `boolean`.

**Comment by yume-chan** [comment]
You are consuming the produced `.wasm` file directly.

However, WebAssembly has no `Boolean` type. It only has [number types](https://webassembly.github.io/spec/core/syntax/types.html).

`--target no-modules` means it doesn't load the `.wasm` via ES Module standard, but let you manually do it. You should still use the produced `.js` wrapper (see the [official demo](https://rustwasm.github.io/docs/wasm-bindgen/examples/without-a-bundler.html#using-the-older---target-no-modules))

Maybe there should be more code example on https://rustwasm.github.io/docs/wasm-bindgen/reference/deployment.html

**Comment by Tythos** [comment]
@yume-chan , you're absolutely right, the casting takes place in the JS wrappers. Good catch. Should have remembered this from my WASM spec.
