### ISSUE TITLE
Support WebIDL interface mixins

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-bindgen#246]
https://heycam.github.io/webidl/#idl-interface-mixins
https://heycam.github.io/webidl/#using-mixins-and-partials

Example:

```webidl
interface Entry {
  readonly attribute unsigned short entryType;
  // ...
};

interface mixin Observable {
  void addEventListener(DOMString type,
                        EventListener listener,
                        boolean useCapture);
  // ...
};

Entry includes Observable;
```

Given that example, I think we would want to

* extend the `Entry`'s bindings with all the things inside the mixin
* turn the `Observable` mixin into a trait with the appropriate methods
* and turn `Interface includes Mixin` into a trait implementation that proxies `<Entry as Observable>::addEventListener` to `Entry::addEventListener`

This way you don't *have* to always import the `Observable` trait to get an `addEventListener` method, but you can still abstract over anything that is `Observable`.

This will require some plumbing through the AST and its `ToTokens` implementations.

**Comment by ohanar** [comment]
FYI, I'm working on this.
