### ISSUE TITLE
can't call JS function from Rust

### ISSUE THREAD

**Issue by mvolkmann** [rustwasm/wasm-bindgen#2462]
### Describe the Bug

This simple repo demonstrates the issue: https://github.com/mvolkmann/wasm-bindgen-demo

`index.js` exports the functions `square` and `cube`.
`src/lib.rs` attempts to gain access to those using `#[wasm_bindgen(module = "/index.js")]`.
It uses those functions in the `sum_of_square_and_cube` function that it defines.
`index.js` tries to call that Rust function which is given the JS name `sumOfSquareAndCube`.
Entering `wasm-pack build --dev --target web` builds the WASM code without any errors.
But browsing `index.html` gives the following error:

```text
GET http://localhost:4507/pkg/snippets/wasm-bindgen-demo-4cd947d3ae947681/pkg/wasm_bindgen_demo.js net::ERR_ABORTED 404 (Not Found)
```

Note how `pkg` is in the URL twice. That seems wrong and I don't see what I did in the code cause that.

### Steps to Reproduce

Explained above.

### Expected Behavior

No errors in DevTools console, only expected output.

### Actual Behavior

Error described above.

### Additional Context

If the `square`, `cube`, and `sum_of_square_and_cube`, and `sumOfSquareAndCube` references are all removed from the JS and Rust code, this demo runs fine.

**Comment by alexcrichton** [comment]
By using `module = ...` I believe you're triggering logic for bundling the JS assuming it's a small handwritten snippet. It looks like you may need `raw_module` instead?

**Comment by mvolkmann** [comment]
Thanks so much! I had not encountered `raw_module`. That fixed it.
