### ISSUE TITLE
How to serialize integer to/from string in wasm-bindgen?

### ISSUE THREAD

**Issue by spartucus** [rustwasm/wasm-bindgen#2466]
### Summary

How to serialize integer to/from string in wasm-bindgen?

### Additional Details

Sorry I know little of JS and WASM.

I used to use wasm-bindgen to generate WASM for JS, but there're errors when JS use big-int or integer overflow or precision lost. I wonder if I could convert integer part of struct into string when send to JS, and convert string to integer when received from JS.

For example:
```
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct Data {
    pub x: Option<u64>,
    pub y: i64,
    pub z: bool,
} 

#[wasm_bindgen]
pub struct Record {
    pub(crate) data: Data,
}
```

Is there a way to serialize Record's number parts to string? So JS could use string instead of integer to interact with WASM, and the use case should be:

```
// JS example
d = {
    x: '123456789', // string, not number
    y: '-19919',  // string, not number
    z: false
}

record = {d: data}

// Send record to WASM(Rust) side
// Or Get returned record from WASM side
```
Does wasm-bindgen have some attribute that can take care this situation?

The question was also aksed on [users.rust-lang.org](https://users.rust-lang.org/t/how-to-serialize-integer-to-string-in-wasm-bindgen/56075).

**Comment by chinedufn** [comment]
Hey there.

Serde has native support for what you are trying to do.

Have a look at [serialize_with](https://serde.rs/field-attrs.html#serialize_with)

Something along the lines of:

```rust
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct Data {
    pub x: Option<u64>,
    #[serde(serialize_with = "i64_to_string")]
    pub y: i64,
    pub z: bool,
} 

fn i64_to_string<S>(x: &i64, s: S) -> Result<S::Ok, S::Error>
where
    S: Serializer,
{
    s.serialize_str(s.to_string().as_str())
}
```

**Comment by spartucus** [comment]
Thanks for reply. 
I want Rust struct serialize as usual when they in internal Rust code, only need 'i64_to_string' when deal with wasm(out side). 
Is it ok to do so?

**Comment by chinedufn** [comment]
Without knowing the specifics of your use case I can't suggest the right path forwards.

But some options that you have

- Make a second struct that serializes to strings and just convert to that before sending it over to wasm

- Serialize to a `serde_json::Value` yourself on the Rust side. Convert the numbers to strings. Then serialize that `serde_json::Value` to a JSON string and send that over to the JS side

- Look into wasm-bindgen's [BigInt](https://github.com/rustwasm/wasm-bindgen/blob/237fff06986a757802b5e398cb8b1f5ed7ca55b2/tests/all/u64.rs) support and see if it fits your use case

**Comment by spartucus** [comment]
Thanks for your help. The `serialize_with` way suits best for me.
