### ISSUE TITLE
Loading wasm module after release still slow ?

### ISSUE THREAD

**Issue by miqbalrr** [rustwasm/wasm-bindgen#2473]
### Summary
I created comparison between manual javascript haversine function, and wasm based.
the result if i compared including the module initialization, wasm based getting much slower than javascript itself.

### Additional Details
```javascript
console.time("manual")
const haversinee = require("../func/haversine")
const src = {
    lat: -7.0,
    lng: 7.0
}

const dst = {
    lat: -8.0,
    lng: 8.0
}
console.log("manual js : "+ haversinee(src, dst, false))
console.timeEnd("manual")

console.time("wasm")
const {Point, haversine} = require("haversinecalc") // this is the problem

const src_p = new Point(-7.0,7.0)
const dst_p = new Point(-8.0,8.0)

console.log("using wasm : "+ haversine(src_p, dst_p))
console.timeEnd("wasm")
```
## Result with module initialization included

```bash
manual js : 156581.10278754708
manual: 12.337ms
using wasm : 156581.10278754708
wasm: 18.109ms
```
## Result without module initialization

```bash
manual js : 156581.10278754708
manual: 7.709ms
using wasm : 156581.10278754708
wasm: 0.287ms
```

**Comment by chinedufn** [comment]
Hey there.

You can take a look at your `haversinecalc` npm package and see what is happening when you require it.

After that, if you see anything that has anything to do with wasm-bindgen feel free to open a more specific issue.

**Comment by miqbalrr** [comment]
So there are no ways to make it faster?
btw is the node JS app cached the module on startup? so the is no problem in runtime. Sorry i'm new in javascript.

**Comment by alexcrichton** [comment]
Using WebAssembly will always have the cost of module compilation and having to deal with that startup time. V8 should be pretty good about getting off the ground quickly, and the web has various tools in browsers to cache modules and make things faster (e.g. async/streaming compilation). I don't think node has a cache of wasm modules at this time.

I don't think this is anything that wasm-bindgen itself can improve, however, so I'm going to close this.
