### ISSUE TITLE
Set custom parameter on web_sys::Event

### ISSUE THREAD

**Issue by Drews4life** [rustwasm/wasm-bindgen#2475]
I want to create an event, set custom parameter on it and dispatch it. On javascript side of things it is pretty easy to do

```
const event = document.createEvent("Event");

event.initEvent("CustomMessageEvent");

event.data = "custom data";

document.dispatchEvent(event);
```

However, things are getting tricky when it comes down to Rust

```
let document = web_sys::window()
    .unwrap()
    .document()
    .unwrap();
    
let evt = document.create_event("Event").unwrap();

evt.init_event("CustomMessageEvent");

// Gives compile error
evt.data = "data".to_owned();

document.dispatch_event(&evt);
```
I searched the docs and didn't find any setters that would allow me to anyhow pass custom parameters to created event. I would like to understand is there a possibility to do this. I am still a beginner in Rust, so any help is appreciated.

**Comment by jonboj** [comment]
Here is for `get` https://stackoverflow.com/questions/63604399/how-to-access-web-syscustomevent-detail-data-from-rust
Tried similar with https://rustwasm.github.io/wasm-bindgen/api/js_sys/Reflect/fn.set.html
```
let jv : &JsValue = &event.detail();
js_sys::Reflect::set(jv, &JsValue::from_str("index"), &JsValue::from_str("valueStr"));
```
Compiles, but don't have full project setup for runtime test.

**Comment by alexcrichton** [comment]
Indeed for setting/getting arbitrary properties on JS values it's recommended to use `Reflect`, which should do the trick.
