### ISSUE TITLE
Support WebIDL getters and setters

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-bindgen#248]
https://heycam.github.io/webidl/#idl-special-operations

```webidl
interface Dictionary {
  readonly attribute unsigned long propertyCount;

  getter double (DOMString propertyName);
  setter void (DOMString propertyName, double propertyValue);
};
```

These are the moral equivalent of `Index` and `IndexMut` traits in Rust, except that those must return references and we can't support that (especially with fallible getters and setters). Maybe just translate these into `get` and `set` functions?

**Comment by afdw** [comment]
From the link in the issue body:
> Not all language bindings support all of the five kinds of special object behavior. When special operations are declared using operations with no identifier, then in language bindings that do not support the particular kind of special operations there simply will not be such functionality.

In some cases there are replacement operations:
```webidl
interface SVGStringList {
  [Throws]
  DOMString getItem(unsigned long index);
  getter DOMString(unsigned long index);
  [Throws]
  DOMString replaceItem(DOMString newItem, unsigned long index);
  setter void (unsigned long index, DOMString newItem);
  ...
};
```
But in some cases there are no:
```webidl
interface HTMLOptionsCollection : HTMLCollection {
  [CEReactions, SetterThrows]
  attribute unsigned long length;
  [CEReactions, Throws]
  setter void (unsigned long index, HTMLOptionElement? option);
  [CEReactions, Throws]
  void add((HTMLOptionElement or HTMLOptGroupElement) element, optional (HTMLElement or long)? before = null);
  [CEReactions, Throws]
  void remove(long index);
  [Throws]
  attribute long selectedIndex;
};
```
```webidl
[OverrideBuiltins]
interface DOMStringMap {
  getter DOMString (DOMString name);
  [CEReactions, Throws]
  setter void (DOMString name, DOMString value);
  [CEReactions]
  deleter void (DOMString name);
};
```

So probably they should be always generated, despite the specification says otherwise?

**Comment by alexcrichton** [comment]
@afdw hm I'm not sure I understand, but the spec may also be confusing me. The spec mentions five operations but only lists four in the table above, and additionally I don't think a replacement operation is one of the one it lists? (unless it's the elusive fifth)

How would we generate bindings though for missing operations?

**Comment by afdw** [comment]
> The spec mentions five operations but only lists four in the table above

Yes, it also confuses me.

From my understanding, the spec says that for special operations with empty name no bindings should be generated if the target language does not support that kind of operation.

It means that these futures will be missing to the user of the bindings. And I think that the spec assumes that there are replacement operations, that such operations are only syntactic sugar, not essential functionality.

I have provided an example when it is the case. As you can see, `getItem` replaces the unnamed getter and `replaceItem` replaces the unnamed setter.

But, I have also shown 2 real examples when it is not the case, when there is no replacement regular operations for languages that do not support that kind of operations. So, if I have understood the spec correctly, it means that there will be no way to use this functionality in such languages at all.

So I think that we can ignore the spec here and always generate regular functions named `get`/`set`/`delete` in Rust.

**Comment by alexcrichton** [comment]
Aha that makes sense! FWIW in [the spec](https://heycam.github.io/webidl/#idl-special-operations) the "Example 15" makes me think that it's actually not possible for getters/setters to be named, but rather a named getter/setter is actually sugar for an unnamed getter/setter plus the actual function itself. In that sense I think we'll always have to deal with the getters/setters not having names!

I agree though that the best way to implement this for now is probably bare method names like `get`, `set`, and `delete`. We can double check that it doesn't conflict with an existing method, and otherwise I definitely agree it's best to provide the functionailty *somehow* rather than leaving it out because Rust doesn't have native getters/setters :)
