### ISSUE TITLE
Uncaught (in promise) TypeError: .__wbindgen_add_to_stack_pointer is not a function

### ISSUE THREAD

**Issue by aaronleopold** [rustwasm/wasm-bindgen#2481]
### Summary

Hello, I wasn't sure if my issue was a bug or a misusage (i.e. question) so I just chose question!

I am in the process of building a very barebones lexer/parser for a custom file type in rust, and I want to load it into my react/electron app. It seems like I can *almost* load it, but I'm throwing a weird type error when attempting to call the function.

### Additional Details

I'll paste my logs below:

`printing of the loaded module (console.log(wasm))`

```
Module {__esModule: true, Symbol(Symbol.toStringTag): "Module"}
parse_ias: (...)
Symbol(Symbol.toStringTag): "Module"
__esModule: true
get parse_ias: ƒ ()
__proto__: Object
```

`printing of the type of loaded module function (console.log(typeof wasm.parse_ias))`

```
typeof wasm.parse_ias: function
```

`error from console after calling function`

```
Uncaught (in promise) TypeError:
_ias_parser_bg_wasm__WEBPACK_IMPORTED_MODULE_0__.__wbindgen_add_to_stack_pointer is not a function
    at Module.parse_ias (ias_parser_bg.js?010e:99)
    at eval (NewSessionModal.tsx?aa6d:47)
    at step (NewSessionModal.tsx:52)
    at Object.eval (NewSessionModal.tsx:33)
    at eval (NewSessionModal.tsx:27)
    at new Promise (<anonymous>)
    at __awaiter (NewSessionModal.tsx:23)
    at test (NewSessionModal.tsx?aa6d:43)
    at HTMLUnknownElement.callCallback (/Users/aaronleopold/Documents/museum/imageant_alternative/node_modules/react-dom/cjs/react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (/Users/aaronleopold/Documents/museum/imageant_alternative/node_modules/react-dom/cjs/react-dom.development.js:237)
```

`ias_parser_bg.js --> auto gen file`

```js
/**
* @param {string} ias_file
* @returns {string}
*/
export function parse_ias(ias_file) {
    try {
        const retptr = wasm.__wbindgen_add_to_stack_pointer(-16);
        var ptr0 = passStringToWasm0(ias_file, wasm.__wbindgen_malloc, wasm.__wbindgen_realloc);
        var len0 = WASM_VECTOR_LEN;
        wasm.parse_ias(retptr, ptr0, len0);
        var r0 = getInt32Memory0()[retptr / 4 + 0];
        var r1 = getInt32Memory0()[retptr / 4 + 1];
        return getStringFromWasm0(r0, r1);
    } finally {
        wasm.__wbindgen_add_to_stack_pointer(16); -----> ERROR HERE
        wasm.__wbindgen_free(r0, r1);
    }
}

```

`lib.rs`

```rust
mod util;
use wasm_bindgen::prelude::*;

pub mod parser;
pub mod lexer;
pub mod token;
pub mod task;

use parser::Parser;
use serde_json::{Result, json};

// When the `wee_alloc` feature is enabled, use `wee_alloc` as the global
// allocator.
#[cfg(feature = "wee_alloc")]
#[global_allocator]
static ALLOC: wee_alloc::WeeAlloc = wee_alloc::WeeAlloc::INIT;

#[wasm_bindgen]
pub fn parse_ias(ias_file: &str) -> String {
  let mut parser = Parser::new(ias_file.to_string());
  let ias = parser.parse_source();

  let j_obj = serde_json::to_string(&ias);

    if j_obj.is_err() {
        panic!("TODO: handle me");
    }

    j_obj.unwrap()
}
```

### Wrap up

Sorry wall of text! I wasn't sure how thorough to be. I can post a link to the repo if needed, as well

**Comment by alexcrichton** [comment]
Unfortunately I'm not entirely sure what might be causing this. It may be something in the packaging pipeline like webpack causing issues, but it could also be something like a mismatch in wasm-bindgen crate/cli version, or just a bug in wasm-bindgen itself. 

If you could reduce this to only using wasm-bindgen I could try to help and investigate.

**Comment by aaronleopold** [comment]
Of course, thanks for responding! I isolated my rust lib into the [add example](https://github.com/rustwasm/wasm-bindgen/tree/master/examples/add) and got a different error (however the example add left as is worked) so I imagine I am just using wasm wrong? 

Could it be because I have split up my library across multiple files? i.e. defining my Token struct in token.rs, my Parser in parser.rs? I figured adding the bindgen directive to the function in lib.rs would have been sufficient enough? This is the error putting my lib in the add example:

```
RuntimeError: unreachable
    at http://localhost:8080/62b1d741b9dc0de3024b.module.wasm:wasm-function[393]:0x7a4b7
    at http://localhost:8080/62b1d741b9dc0de3024b.module.wasm:wasm-function[571]:0x7f720
    at http://localhost:8080/62b1d741b9dc0de3024b.module.wasm:wasm-function[604]:0x7fda6
    at http://localhost:8080/62b1d741b9dc0de3024b.module.wasm:wasm-function[459]:0x7ced8
    at http://localhost:8080/62b1d741b9dc0de3024b.module.wasm:wasm-function[291]:0x73b13
    at f (http://localhost:8080/62b1d741b9dc0de3024b.module.wasm:wasm-function[194]:0x6a359)
    at Module.w (http://localhost:8080/2.index.js:1:1168)
    at http://localhost:8080/index.js:1:155550
```

Its not a finished lib yet but I went ahead and uploaded this to a separate repo if that helps at all: https://github.com/aaronleopold/ias_parser

**Comment by aaronleopold** [comment]
Okay, so I added [`console_error_panic_hook`](https://crates.io/crates/console_error_panic_hook) after searching a little more through other issues on here, and see that rust panicked:

```
2.index.js:1 panicked at 'Something went wrong reading the .ias file: Custom { kind: Other, error: "operation not supported on wasm yet" }'
```

corresponding to this line:

```rust
let file_contents = fs::read_to_string(ias_file)
    .expect("Something went wrong reading the .ias file");
```

So I guess this relates to https://github.com/rustwasm/wasm-bindgen/issues/1727

**Comment by aaronleopold** [comment]
So it was definitely a webpack issue, specifically I think [electron-webpack](https://webpack.electron.build/). I switched away from electron-webpack and moved to a typical webpack config and it seems to loading okay now. I'll go ahead and close this issue
