### ISSUE TITLE
Recursive use of an object detected which would lead to unsafe aliasing in rust

### ISSUE THREAD

**Issue by joao-conde** [rustwasm/wasm-bindgen#2486]
### Summary

Came across an issue with Rust compiled to WASM + browser JS interaction.

### Additional Details

Hi, I am seeking further info about my issue but couldn't find any gitter.io or similar so I opened this issue. Please close it if inappropriate but redirect me somewhere.

I wrote a chip8 emulator in Rust and wanted to expose a WASM API to render it in the browser. I want to keep the rust crate as agnostic as possible of the browser runtime. Hence, around my `Chip8` struct which is the following:

```rust
pub struct Chip8 {}

impl Chip8 {
    pub fn new() -> Chip8 {   .... }

    pub fn load_rom(&mut self, rom: &[u8]) {   ...  }

    pub fn clock(&mut self) {  ...  }

    pub fn vram(&self) -> Vec<u8> {   ...  }
}
```

I wrote a safe wrapper to avoid JavaScript concurrent access with a mutex:

```rust
#[wasm_bindgen]
pub struct Chip8 {
    chip8: Mutex<chip8::Chip8>,
}

#[wasm_bindgen]
impl Chip8 {
    #[wasm_bindgen(constructor)]
    pub fn new() -> Chip8 {
        Chip8 {
            chip8: Mutex::new(chip8::Chip8::new()),
        }
    }

    pub fn load_rom(&mut self, rom: &[u8]) {
        self.chip8.lock().unwrap().load_rom(rom);
    }

    pub fn clock(&mut self) {
        self.chip8.lock().unwrap().clock();
    }

    pub fn vram(&self) -> Vec<u8> {
        self.chip8.lock().unwrap().vram()
    }
}
```

My javascript code is as follows:

```js
(async () => {
    await wasm();
    const rom = await getROM("Pong.ch8");
    const chip8 = new Chip8();
    chip8.load_rom(rom);
    window.setInterval(() => chip8.clock(), 10);
    window.setInterval(() => render(chip8.vram()), 100);
})();
```

It runs for a couple of seconds until it logs errors to the console, as such:

```
Uncaught Error: recursive use of an object detected which would lead to unsafe aliasing in rust
```

I've did some research online and read a similar issue but from the explanation it's essentially borrow checker runtime violations. But if I am using a mutex, how can I be violating this principle?

**Comment by alexcrichton** [comment]
Thanks for the report! FWIW you shouldn't need the `Mutex` here.

Are you sure that's the only error message on the console? If Rust panicked then that would be the second error message to come out, but the first panic has the real source of the error.

**Comment by joao-conde** [comment]
Appears to be, the console is so flooded I can't see it from the top though.

**Comment by alexcrichton** [comment]
Ah ok the first issue there looks like a Rust panic (which you probably need to set up `console_error_panic_hook` to get the output of. That is the root cause of the error here.

**Comment by joao-conde** [comment]
Really great tip. Was able to find the issue:  https://github.com/rustwasm/wasm-bindgen/issues/1961
Empty [u8] meant the program had an out of bounds indexing. Thanks for the help @alexcrichton
