### ISSUE TITLE
Support WebIDL inheritence

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-bindgen#249]
https://heycam.github.io/webidl/#dfn-inherit

Example:

```webidl
interface A {
  void f();
  void g();
};

interface B : A {
  void f();
  void g(DOMString x);
};
```

Blockers:

* [ ] Need to figure out how to represent inheritance in general: https://github.com/rustwasm/wasm-bindgen/issues/152

**Comment by alexcrichton** [comment]
Done in https://github.com/rustwasm/wasm-bindgen/pull/640!
