### ISSUE TITLE
How to access methods on a custom field added to JS global object

### ISSUE THREAD

**Issue by luckysori** [rustwasm/wasm-bindgen#2493]
### Summary

If I set a property on a global object like this

```rust
#[wasm_bindgen]
#[derive(Serialize)]
pub struct Foo {}

#[wasm_bindgen]
impl Foo {
    #[wasm_bindgen(constructor)]
    pub fn new() -> Self {
        Self {}
    }

    #[wasm_bindgen]
    pub fn bar(&self) -> u8 {
        1
    }
}

#[wasm_bindgen(start)]
pub fn main() {
    let global = global();
    let foo = Foo::new();

    js_sys::Reflect::set(
        &global,
        &JsValue::from("foo"),
        &JsValue::from_serde(&foo).unwrap(),
    )
    .unwrap();
}
```

the global object has a property `foo` on it, but I cannot call the method defined on it i.e. `window.foo.bar()`. I assume that using `JsValue::from_serde(&foo)` is incorrect because it is based on the serialisation of the struct which knows nothing about the method `bar`. How should I got about doing this instead?

**Comment by alexcrichton** [comment]
Using `from_serde` serializes the value (think of converting an object to JSON). You'll want to stick the `foo` value itself (e.g. via `JsValue::from(foo)` into the map instead.

**Comment by luckysori** [comment]
So obvious in hindsight. Thank you!
