### ISSUE TITLE
Fill the vector using javascript

### ISSUE THREAD

**Issue by tadjik1** [rustwasm/wasm-bindgen#2494]
Hello,
I'm reading wonderful [Rust 🦀 and WebAssembly](https://rustwasm.github.io/docs/book/introduction.html) book, trying to play around with some examples from this book.
What I'm trying to do is to initialize the `Image` struct and populate its' data from the JS side.

```rust
mod utils;

use wasm_bindgen::prelude::*;

// When the `wee_alloc` feature is enabled, use `wee_alloc` as the global
// allocator.
#[cfg(feature = "wee_alloc")]
#[global_allocator]
static ALLOC: wee_alloc::WeeAlloc = wee_alloc::WeeAlloc::INIT;

#[wasm_bindgen]
pub struct Image {
    data: Vec<u8>,
}

#[wasm_bindgen]
impl Image {
    pub fn new() -> Image {
        Image { data: vec![] }
    }

    pub fn get_pointer(&self) -> *const u8 {
        self.data.as_ptr()
    }

    pub fn get_length(&self) -> usize {
        self.data.len()
    }

    pub fn get_first_element(&self) -> u8 {
        match self.data.get(0) {
            Some(v) => *v,
            None => 0,
        }
    }
}
```

```javascript
import { memory } from "wasm-example/wasm_example_bg";
import { Image } from "wasm-example";

const image = Image.new();

const buf = new Uint8ClampedArray(memory.buffer, image.get_pointer(), 10);

for (let i = 0; i < 10; i++) {
  buf[i] = 255;
}

console.log(image.get_length());
console.log(image.get_first_element(), buf[0]);

```

However, even though I see the correct value "255" storing in `buf` I'm not able to read it from the wasm side. Instead I get `0` as a length and as a first element inside `self.data`.

What am I doing wrong and how to fill the vector in my struct?

**Comment by tadjik1** [comment]
Found solution - vector needs to be initialized with the length
```rust
    pub fn new(length: usize) -> Image {
        Image { data: vec![0; length] }
    }
```

in that case, it works as expected.

Feel free to close this issue, I would be also very pleased for some suggestions there, mostly whether it's the right way to solve this task.

**Comment by jbuckmccready** [comment]
Another solution is to create a method in Rust to set values in the `Vec<u8>` directly.

Note this doesn't clamp like the `Uint8ClampedArray`, you still need to initialize the length of `data`, and I did not compile/test this code...
```Rust
#[wasm_bindgen]
impl Image {
    pub fn set(&mut self, i: usize, value: u8) {
        self.data[i] = value;
    }
}
```

```javascript
import { Image } from "wasm-example";

const image = Image.new(10);

for (let i = 0; i < 10; i++) {
  image.set(i, 255);
}
```

**Comment by CrimsonCodes0** [comment]
For this very particular case, you'd probably be best off with initializing it it's values:
```rust
 pub fn new(length: usize) -> Image {
        Image { data: vec![0xFF; length] }
    }
```

But it seems like enough solutions have been raised already, maybe this should be closed now?

**Comment by CrimsonCodes0** [comment]
Oh, and btw, you should look into other attributes that would allow the Rust getters to map to JS getters, Rust constructors to JS constructors, etc, e.g., `.get_pointer()` => `.pointer`, or `Image.new()` => `new Image()`

**Comment by tadjik1** [comment]
thanks a lot for your answers, @CrimsonCodes0 !
