### ISSUE TITLE
Target no-modules failed to find its .wasm file automatically

### ISSUE THREAD

**Issue by yume-chan** [rustwasm/wasm-bindgen#2502]
### Describe the Bug

When building with `--target no-modules`, the output js file should be able to find its `.wasm` file.

### Steps to Reproduce

1. Clone the `without-a-bundler-no-modules` example and build
2. Modify `index.html` as:
    ```diff
    - await wasm_bindgen('./pkg/without_a_bundler_no_modules_bg.wasm');
    + await wasm_bindgen();
    ```
3. Open it in a browser (I'm using Microsoft Edge 89.0.774.54)

### Expected Behavior

It loads the `.wasm` file and runs.

### Actual Behavior

```text
Uncaught (in promise) CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 68 74 6d @+0
```

### Additional Context

I treat it as a bug because the generated code did try to detect the correct url for its `.wasm` file, but it failed.

Related code:

```js
    async function init(input) {
        if (typeof input === 'undefined') {
            let src;
            if (typeof document === 'undefined') {
                src = location.href;
            } else {
                src = document.currentScript.src;
            }
            input = src.replace(/\.js$/, '_bg.wasm');
        }
//...
```

The problem is that, `document.currentScript` refers to the current processing script, so as most of time `init` was been called from another script (and in this case, a script tag without `src`), this code fails.

The correct method is caching `document.currentScript.src` when it's initializing, for example:

```diff
+     const cachedSrc = document.currentScript.src;
      async function init(input) {
          if (typeof input === 'undefined') {
              let src;
              if (typeof document === 'undefined') {
                  src = location.href;
              } else {
-                 src = document.currentScript.src;
+                 src = cachedSrc;
            }
            input = src.replace(/\.js$/, '_bg.wasm');
        }
```

I verified it works after the modification:

![image](https://user-images.githubusercontent.com/1330321/111612544-895b8080-8818-11eb-85da-29c558deb001.png)

**Comment by CrimsonCodes0** [comment]
We can't literally cache it like you had shown, because the code needs to check for the existence of the document object.

What we can do instead is cache the entire expression.

If document doesn't exist, and is created later, then I doubt that we'd want that document object, and the location won't change without reloading the scripts, so the entire thing can be a constant.

```js
const cached_source = ("document" in globalThis
    ? document.currentScript.src
    : location.href
).replace(/\.js$/, '_bg.wasm');

async function init(input = cached_source) {
    ...
}
```

**Comment by CrimsonCodes0** [comment]
I would like to create a small PR updating both, ESM and non-ESM to cache the default sources so they will have equal performance at runtime, but I'd like to know, in what cases is it expected that the client would have a location, but not a document?
