### ISSUE TITLE
support wasm32-unknown-emscripten because of performance and friendly use with C

### ISSUE THREAD

**Issue by moyy** [rustwasm/wasm-bindgen#2505]
### Motivation

1. After our test, the same rust code, wasm32-unknown unknown is about 30% slower than wasm32-unknown-emscripten;

2. Better compatibility with C/C++

**Comment by alexcrichton** [comment]
Thanks for the report, but this is unfortunately pretty unlikely to happen. AFAIK emscripten wants its own JS shims and all that, and having two systems of managing shims won't mix well.
