### ISSUE TITLE
Error messages in wasm functions propagated to javascript

### ISSUE THREAD

**Issue by andy734658** [rustwasm/wasm-bindgen#2507]
### Motivation

I'm not sure if this should be a bug report or a feature request, but it would be nice if there were better support for propagating errors from web assembly to javascript.  For example I have the code

#[wasm_bindgen]
pub struct foo{
  ...
  pub fn bar(size : i64)->Result<String, JsValue>{
    if size > 10 {
      return Err(JsValue::from("Size was too large"));
   }else{
      ..
      return Ok("Success".to_string());
  }

If some javascript does the following

try (foo.bar(30)){
  ..
}catch(e){
  alert(e.name);
  alert(e.message);
}

the alert will always show e.name as "RuntimeError" and e.message as "memory access out of bounds."  It would be helpful if it could show the supplied value "Size was too large."

### Proposed Solution

Propagate the error message.

### Alternatives

I've tried returning a Result<String, js_sys::Error> but that is also not supported.

**Comment by CrimsonCodes0** [comment]
> the alert will always show e.name as "RuntimeError" and e.message as "memory access out of bounds." It would be helpful if it could show the supplied value "Size was too large."

Neither, wasm-bindgen, nor Rustc create errors like that. Did you isolate your code to just the code example in question?

**Comment by DesmondWillowbrook** [comment]
There is good support for propagating error messages! It's the `console_error_panic_hook` crate which comes shipped in the [Hello World example of `wasm_bindgen`](https://rustwasm.github.io/wasm-bindgen/examples/hello-world.html).

Add this in your `Cargo.toml`: `console_error_panic_hook = "0.1.6"`
And this to your code:
```rust
pub fn set_panic_hook() {
    // Call the `set_panic_hook` function at least once during initialization, and then
    // we will get better error messages if our code ever panics.
    //
    // For more details see
    // https://github.com/rustwasm/console_error_panic_hook#readme
    #[cfg(feature = "console_error_panic_hook")]
    console_error_panic_hook::set_once();
}
```

**Comment by andy734658** [comment]
console_error_panic_hook is a great tool and I use it all the time for debugging!  Unfortunately for production I don't want to call panic! and halt the program, as there is persistent information the user has already entered and is stored in the program, and this would necessitate reentering all that; rather, I just want to bubble up to the user that they entered invalid input and give them another chance.

There is an obvious workaround to this, that I give the wasm module a struct that stores an error flag, sets the flag if there's an error, and the javascript checks the flag after calling the function:

...
pub fn bar(&self, size : i64)->Result<String, JsValue>{
if size > 10 {
 ..error condition...
 self.set_error_flag("size was > 10");
 return Ok("".to_string());
}else{
..valid input, do some stuff...
return Ok("Success".to_string());
}

now javascript does the following

foo.bar(30);
if foo.get_error_flag == "size was > 10" {
.. error handling here..
}

This works fine, just kinda kludgy.

Regarding the first comment, all I've got are Javascript and the web assembly module, being run in a Chrome browser.  My guess is that the exact error messages aren't coming from the web assembly modules but are rather defaults that Chrome spits out when e.name or e.message are null, or something of that nature.

**Comment by CrimsonCodes0** [comment]
Your Rust throws a JavaScript string:
```rust
Err(JsValue::from("Size was too large"));
```
not an exception.

Yet, a totally different exception is being thrown:
```
WebAssembly::RuntimeError {
    message: "memory access out of bounds"
}
```

You likely have to run through your code, and make sure that you don't have any undefined behavior, maybe just narrow the code down to what you've shown without any extra code in-between the return statements (as a start)?

```rust
pub fn bar(&self, size: i64) -> Result<String, JsValue> {
    if size > 10 {
        Ok("".to_string());
    } else {
        Ok("Success".to_string());
    }
}
```

The RuntimeError that you are encountering is equivalent to a segmentation fault, and is likewise caused by accessing memory outside of your program's process.

**Comment by andy734658** [comment]
Well, that's why this is a bit of a head scratcher.  I can be pretty confident there's not any undefined behavior in my code because when I kludge it to set an error flag and provide the same set of inputs, everything works fine--the desired message is propagated to the user.  No memory issues, no panics, nothing.  Furthermore everything that I've written is safe rust so accessing memory outside of my program's process would be surprising behavior to me.

There are a lot of other processor intensive tasks that take place before the size check, and in other places the if statement involves calling a high-overhead validation function rather than a simple comparison.  If I take out all of my own logic and just always return Err(JsValue::from("size was too large")) as in the code below, the javascript alerts will read "undefined", "undefined", and  "size was too large."  Which is the expected behavior.  However any time I call a validation function (which is both memory and processor intensive) the alerts are "runtime error", "memory access out of bounds", and "".  There are several different validation functions which seem to be associated with this, all of which take a very large vec and return a bool, and they all work fine if instead of returning an Err(JsValue::from("")) I just return OK("") and set the error flag in a separate place.

```#[wasm_bindgen]
pub struct foo{
  isalive: bool,
}
#[wasm_bindgen]
impl foo {
 pub fn new()->foo{
    foo{isalive : true} 
 }
 pub fn bar(&self)->Result<String, JsValue>{
   Err(JsValue::from("Size was too large")
 }
}
```
Then in javascript

```
let myfoo = wasm.foo.new();
try (myfoo.bar()){
 alert("OK!");
}catch(e){
 alert(e.name);
 alert(e.message);
 alert(e.toString());
}
```
Anyhow I've got a workaround at this point so it's not a big deal to me personally, but my main motivation for submitting was just that it seemed strange that something written in pure safe rust was throwing a memory access error.  It's also certainly possible that I've done something strange on my end to cause this that I'm not seeing.

**Comment by CrimsonCodes0** [comment]
> However any time I call a validation function (which is both memory and processor intensive) the alerts are "runtime error", "memory access out of bounds", and "". There are several different validation functions which seem to be associated with this, all of which take a very large vec and return a bool, and they all work fine if instead of returning an Err(JsValue::from("")) I just return OK("") and set the error flag in a separate place.

Odd indeed, I'd suggest trying to analyze the functions one-by-one, and turning off compiler optimization.

I can't say that the bug is definitely even involved in those functions, but look out for any "unsafe" blocks/functions, if you have any.

> try (myfoo.bar()){
>  alert("OK!");
> }

Also, note that the "(" after "try" is invalid syntax.
