### ISSUE TITLE
Recent build failures from wasm-bindgen ecosystem

### ISSUE THREAD

**Issue by code-ape** [rustwasm/wasm-bindgen#2508]
### Describe the Bug

Our CI started randomly failing today on `wasm-bindgen` projects with no dependency changes. This appears to be a failure with the wasm-bindgen macro. Since our project was a library we didn't have a pinned `Cargo.lock` I suspect this isn't the fault of wasm-bindgen but of one of its dependencies, but I wasn't sure were else to report it.

**UPDATE: We just found that forcing rollback of `syn` from `1.0.66` to `1.0.65` appears to fix this issue.** `cargo update -p syn --precise 1.0.65`. Leaving this open for wasm-bindgen to do with as they see fit.

### Steps to Reproduce

Attempt to run `cargo check` on [`urbdyn/petgraph-wasm`, commit `c4e3db9`](https://github.com/urbdyn/petgraph-wasm/tree/c4e3db97c4c07a3c9b98224b2dcfcb03b7ac71be) with `syn` version `1.0.66`.

### Expected Behavior

`cargo check` exits fine.

### Actual Behavior

Recieve hundreds of errors relating to `#[wasm_bindgen(...)]` and `WebAssembly` when attempting to build dependency `js-sys-0.3.49` in `cargo check` process.

### Additional Context

Last successful build was ~5 hours prior to time of filing this issue. No changes to source code since then. Blowing away my local `Cargo.lock` duplicated the issue. Sadly I failed to back it up before hand to diff with new one.

Link to last successful build for time reference: https://github.com/urbdyn/petgraph-wasm/actions/runs/696142253

Example from GitHub Actions output, full run viewable at: https://github.com/urbdyn/petgraph-wasm/pull/12/checks?check_run_id=2215306539#step:5:68

```
# Omitting non-wasm-bindgen related libraries.
Compiling wasm-bindgen-shared v0.2.72
Compiling serde_derive v1.0.125
Compiling serde v1.0.125
Compiling serde_json v1.0.64
Compiling wasm-bindgen v0.2.72
Compiling wasm-bindgen-test-macro v0.3.22
Compiling wasm-bindgen-backend v0.2.72
Compiling wasm-bindgen-macro-support v0.2.72
Compiling wasm-bindgen-macro v0.2.72
Checking js-sys v0.3.49
Checking console_error_panic_hook v0.1.6

error: expected `,`
Error:    --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.49/src/lib.rs:639:39
    |
639 |         #[wasm_bindgen(js_namespace = Atomics, catch)]
    |                                       ^^^^^^^

error: expected `,`
Error:    --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.49/src/lib.rs:649:39
    |
649 |         #[wasm_bindgen(js_namespace = Atomics, catch)]
    |                                       ^^^^^^^

```

**Comment by afilini** [comment]
I opened this issue in the `syn` repo before noticing this thread. I believe in a way this bug is actually here in `wasm-bindgen`, but nobody had noticed it before because `syn` also had a different "bug", or at least it was behaving differently when trying to parse an `ExprArray` which was not an `ExprArray` (it was still consuming tokens from the parse buffer).

I guess the fix here would be to just avoid forking the `ParseBuffer`?

https://github.com/rustwasm/wasm-bindgen/blob/0cec40630386e22a781f0f2723a92b92231cdbd9/crates/macro-support/src/parser.rs#L302

https://github.com/dtolnay/syn/issues/1005#issuecomment-809303566
