### ISSUE TITLE
Issue in passing JS Objects with null and undefined.

### ISSUE THREAD

**Issue by singharpit94** [rustwasm/wasm-bindgen#2509]
### Issue in passing JS Objects with null and undefined.

I am trying to pass a JS object which have undefined and null present in them but not able to use the serde Serialize, Deserialize

Example Code.

```
#[derive(Serialize, Deserialize)]
pub struct ExampleData {
    pub data: HashMap<String, Vec<JsValue>>,
}

#[wasm_bindgen]
pub fn receive_example_from_js(val: &JsValue) {
    let example: ExampleData = val.into_serde().unwrap();
}
```

From JS, I am trying to pass an object of following shape

```
const jsObject = {
    a: [1,2,3,null, 4,5,undefined]
}

```

I am not able to build the rust code as it throws an error saying 
```
the trait `Deserialize<'_>` is not implemented for `wasm_bindgen::JsValue`

```

I am not sure whether I am doing something wrong or I should take JsValue from Javascript in some other way. Can someone advice here.

Thanks,
Arpit.

**Comment by alexcrichton** [comment]
You can't use serialize/deserialize for this, you'll need to implement your own hand-rolled serialization/deserialization I think.
