### ISSUE TITLE
How to deal with mutable shared references

### ISSUE THREAD

**Issue by jhnns** [rustwasm/wasm-bindgen#2521]
👋 Hi, first of all thank you for working on wasm-bindgen :)

### Summary

I'm currently writing a library that provides bindings for a Rust crate. The crate instance is wrapped in a `struct` like this:

```rust
#[wasm_bindgen]
pub struct MyLib {
    someCrate: SomeCrate,
}
```

Now I want to provide access to `convert()` that requires ownership of the `someCrate`:

```rust
#[wasm_bindgen]
impl MyLib {
    pub fn convert(&mut self) {
        self.someCrate = self.someCrate.convert(); // <-- convert() consumes someCrate and thus
                                                   //     requires ownership of it.
                                                   //     convert() returns an instance of SomeCrate.
    }
}
```

Rust won't compile this because `self` isn't owned. If I change `self` into an owned value, it will work, but `self` is dropped afterwards and any additional calls from JS will raise an error.

My current approach is to return `self` again and store the new reference on the JS side, which works but feels kind of unorthodox:

```rust
#[wasm_bindgen]
impl MyLib {
    pub fn convert(self) -> MyLib {
        self.someCrate = self.someCrate.convert();
        
        self
    }
}
```

**My question is:** Is this the currently recommended approach for this kind of problem or is there a simpler solution?

Feel free to close this issue :)

**Comment by jbuckmccready** [comment]
You're question is really just a Rust question for dealing with the Rust ownership model. You can use one of [std::mem::replace](https://doc.rust-lang.org/std/mem/fn.replace.html), [std::mem::take](https://doc.rust-lang.org/std/mem/fn.take.html), or [std::mem::swap](https://doc.rust-lang.org/std/mem/fn.swap.html) to take local ownership of `someCrate` to avoid taking an owned `self` in the method. [Here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e1d83ac14178a85a65eb4e4f17b96c14) is a playground link to demonstrate.

**Comment by alexcrichton** [comment]
I'd recommend sticking to `&mut self` and using the functions mentioned or storing an `Option` so you can `.take().unwrap()` as necessary. Hope that helps!

**Comment by jhnns** [comment]
Thanks @jbuckmccready and @alexcrichton, that helped me a lot 🙏
