### ISSUE TITLE
wasm-bindgen-test failed to deserialize module with SIMD

### ISSUE THREAD

**Issue by calebzulawski** [rustwasm/wasm-bindgen#2522]
An example from CI: https://travis-ci.com/github/rust-lang/stdsimd/jobs/497585556

```
Error: failed to deserialize wasm module

Caused by:

    0: failed to parse code section

    1: Unknown 0xfd opcode (at offset 568559)
```

This occurred after I added SIMD comparisons (`simd_eq`, etc) to tests, which looks like it's fixed in bytecodealliance/wasm-tools#222, so hopefully it's a matter of "just" updating dependencies.

**Comment by workingjubilee** [comment]
I do not mean to be a bother, but please reopen this, or if I should direct this to another repository, then please tell me where. This remains an issue, you see, even when I did pull in `wasm-bindgen` from trunk.

```backtrace
Error: failed to deserialize wasm module

Caused by:
    0: failed to parse code section
    1: Unknown 0xfd opcode (at offset 462132)
error: test failed, to rerun pass '--test f32_ops'
Error: Running Wasm tests with wasm-bindgen-test failed
Caused by: failed to execute `cargo test`: exited with exit code: 1
  full command: "cargo" "test" "--release" "--target" "wasm32-unknown-unknown"
```

This was used in the root Cargo.toml of the workspace:
```toml
[patch.crates-io]
wasm-bindgen = { git = "https://github.com/rustwasm/wasm-bindgen" }
wasm-bindgen-test = { git = "https://github.com/rustwasm/wasm-bindgen" }
```

The commands I used were
```powershell
> $Env:RUSTFLAGS="-Ctarget-feature=+simd128"
> wasm-pack test --release --firefox crates/core_simd

**Comment by workingjubilee** [comment]
Ah, I am told (more or less) that we have to wait on the update to cascade to `wasm-pack`, it seems. Though I suppose we could also restructure our tests to use another test runner.
