### ISSUE TITLE
`app_bg.wasm` changed between 0.2.70 and 0.2.73

### ISSUE THREAD

**Issue by cecton** [rustwasm/wasm-bindgen#2523]
### Describe the Bug

I'm the author of [wasm-run](https://crates.io/crates/wasm-run) but it broke recently because the JS file (app.js) can't find the WASM file (app_bg.wasm).

As you can see in my code [here](https://docs.rs/wasm-run/0.8.1/src/wasm_run/lib.rs.html#483) I was relying on the fact that the name of the files were always "app.js" and "app_bg.wasm". But between 0.70  and 0.73 you made a change somewhere so the name used is now the crate's name that is compiled: `myfrontend_bg.wasm`.

Because of that, the JS code can't load the WASM file anymore on projects using wasm-run.

### Steps to Reproduce

1. Create a new project with wasm-run: `cargo generate --git https://github.com/cecton/wasm-run-template.git -b main`
2. Run `serve`: `cargo run -- serve`
3. Go on http://127.0.0.1:3000

![image](https://user-images.githubusercontent.com/3018448/114563879-1d7e0380-9c70-11eb-95ac-5fc89a1a6e3d.png)

### Expected Behavior

The name won't change between patch versions. This is a breaking change.

### Actual Behavior

Every project using wasm-run right now that does `cargo update` will silently fail as this is a runtime error.

**Comment by cecton** [comment]
I believe I found the commit that changed this behavior: https://github.com/rustwasm/wasm-bindgen/commit/de2a5d7bda9ee60d53f779794bc3b3643d205272

Related to #2444

**Comment by alexcrichton** [comment]
I apologize for the breakage, would something like https://github.com/rustwasm/wasm-bindgen/pull/2520 fix your use case?

**Comment by CrimsonCodes0** [comment]
@alexcrichton No, the PR I created assumes that the wasm file has the same name, it just couldn't lookup the wasm file's name correctly.

Example: "foo.js" and "bar_bg.wasm" are emit, the user calls foo.js' `load()`, `load` attempts to fetch "foo_bg.wasm," since "foo" was the name of the .js file, the fetch fails :)

wasm-bindgen should emit "foo.js" alongside "foo_bg.wasm," not "foo.js" with "bar_bg.wasm."

Hopefully it helped you see the problem better, and sorry for using metasyntactic variable placeholder names, if anyone cares.

**Comment by cecton** [comment]
> I apologize for the breakage, would something like #2520 fix your use case?

I don't think it will because wasm-run is also going through the "web" output. https://github.com/wasmbl/wasmbl/blob/main/src/lib.rs#L741

@alexcrichton Can we yank the versions for now until we decide? I wouldn't mind that you increase the version to 0.3 for that change.

**Comment by alexcrichton** [comment]
Unfortunately this is old enough I don't think a yank is feasible at this time. I also do not have the time to manage an 0.3 release. @RReverser would you be able to comment on this as the author of the original patch?

**Comment by RReverser** [comment]
Hm, if the name change happened indeed in that commit, it wasn't intentional.

To be honest I don't fully understand the issue either:

> As you can see in my code here I was relying on the fact that the name of the files were always "app.js" and "app_bg.wasm". But between 0.70 and 0.73 you made a change somewhere so the name used is now the crate's name that is compiled: myfrontend_bg.wasm.

I think crate name has been used for a while now (always?), and filename was never hardcoded to `app.js` / `app_bg.wasm` in wasm-bindgen, so the original assumption seems strange...

**Comment by RReverser** [comment]
I thought maybe something in my change made custom `--out-name` getting ignored, but no, that still works just fine too. So I'm still not sure where the original assumption was coming from or what changed it.

**Comment by cecton** [comment]
The original name was derived from the URL. So if the JS file is on `https://example.org/app.js` it will load `app.wasm`. With the changes done, the name is now derived from the crate name at compile time. @RReverser

Before:

```rust
input = import.meta.url.replace(/\\.js$/, '_bg.wasm');
```

After:

```rust
                        input = new URL('{stem}_bg.wasm', import.meta.url);
...
                stem = self.config.stem()?
...
    pub fn stem(&self) -> Result<&str, Error> {
        Ok(match &self.input {
            Input::None => bail!("must have an input by now"),
            Input::Module(_, name) => name,
            Input::Path(path) => match &self.out_name {
                Some(name) => name,
                None => path.file_stem().unwrap().to_str().unwrap(),
            },
        })
    }
```

**Comment by cecton** [comment]
You know what it's okay. Apparently this doesn't seem to bother anybody else than me so I will make a fix on wasm-run.

**Comment by cecton** [comment]
Thanks for the tip! It worked like a charm :sparkles: I made a release this weekend.

**Comment by cecton** [comment]
Closing this for now as no action will be taken. I just made a patch on my side.
