### ISSUE TITLE
What's the best way to implement wasm + rollup + Svelte ?

### ISSUE THREAD

**Issue by marioaldairsr** [rustwasm/wasm-bindgen#2524]
### Summary

Hello, I am in my first steps in wasm and rust, I find it interesting to be able to use other programming languages ​​on the web through wasm, right now I am trying to be able to work with Svelte using rollup and wasm. I was reading the documentation for rust wasm and the game of life, but I am having problems.

Hopefully there is a person who can support me, I will be very grateful.

### Additional Details

Well, I will try to detail the steps that I have been doing.

1. I generated a new rust project and also a new svelte project
`cargo new rust-wasm --lib`
`npx degit sveltejs/template  rust-wasm`
2. Then I put wasm-bindgen as dependency in Cargo.toml
```
[dependencies]
wasm-bindgen = "0.2.73"
```
3. I put this code on lib.rs
```
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub struct Person {
    age: u32,
    height: u32
}

#[wasm_bindgen]
impl Person {
    pub fn new(age: u32, height: u32) -> Person {
        Person {
            age,
            height
        }
    }

    pub fn get_age(self) -> u32 {
        self.age
    }

    pub fn get_height(self) -> u32 {
        self.height
    }
}
```
4. Then I ran the command `wasm-pack build --target web` and pasted the pkg folder into my Svelte project
5. I put the pkg folder as a dependecy on my Svelte project, similar as the doc here: https://rustwasm.github.io/book/game-of-life/hello-world.html#using-our-local-wasm-game-of-life-package-in-www
```
"dependencies": {
        ...
        "person": "file:./pkg"
 }
```
6. then i ran `npm install`
7. and finally `npm run dev`
8. and i got this error
![image](https://user-images.githubusercontent.com/77013992/114577112-5d79c200-9c41-11eb-9973-da06ab296aa4.png)

If I do the same steps with [vite](https://github.com/vitejs/vite) everything seems to work fine. What am I doing wrong? I have tried using the wasm package from rollup [@rollup/plugin-wasm](https://github.com/rollup/plugins/tree/master/packages/wasm) but have not been successful. 

Finally, this is the repo so you can clone it. 
https://github.com/marioaldairsr/issue_wasm_rust

**Comment by alexcrichton** [comment]
Sorry I know very little about either rollup or svelte so I don't think I'll be of much help :(

**Comment by HanKruiger** [comment]
@marioaldairsr I’m struggling with the same thing. Did you find a solution?

I understand this is Rollup specific but it is a common bundler, so I imagine more people will run into this.

**Comment by alephpt** [comment]
use something like vite and build the rust using npm with the following sort of defineConfig

```
export default defineConfig({
    clearScreen: false,
    resolve: { alias: { '@': resolve('src') } },
    plugins: [
        rust({
            verbose: true,
            serverPath: "build/"
        }),
        routify({
            ssr: { enable: false },
        }),
        svelte({
            compilerOptions: {
                dev: !production,
                hydratable: !!process.env.ROUTIFY_SSR_ENABLE,
            },
            extensions: ['.svelte'],
            preprocess: [preprocess()],
        }),
    ],

    server: { port: 1337 },
})
```
and in your rust directory, in cargo.toml put something like the following
```
[package]
name = "sdk"
version = "0.1.0"
edition = "2021"
resolver = "2"

[lib]
name = "sdk"
path = "src/lib.rs"
crate-type = ["rlib", "cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = "0.2.89"
```
