### ISSUE TITLE
how to call rust method without bindgen

### ISSUE THREAD

**Issue by baisijian** [rustwasm/wasm-bindgen#2530]
#[no_mangle]
pub extern "C" fn test(name: &str) {
    utils::log(&format!("Hello, {}!", name));
}

wasmModule.test("World");

I got Hello !

**Comment by CrimsonCodes0** [comment]
Why wouldn't you want to use wasm-bindgen?

JavaScript objects aren't represented as pointers, like Rust references are, so you can't pass them directly between each other, they can only pass integers, floating-point numbers, and little else.

I'm confident that calling the function like you had done causes Rust UB.

**Comment by baisijian** [comment]
> Why wouldn't you want to use wasm-bindgen? Can you elaborate on your use?
> 
> JavaScript objects aren't represented as pointers, like Rust references are, so you can't pass them directly between each other, they can only pass integers, floating-point numbers, and little else.
> 
> I'm confident that calling the function like you had done causes Rust UB.
> 
> If you need to, you could write into the heap, and pass the pointer to Rust.

thanks for reply
when I use bindgen,got there error:
extern crate wasm_bindgen;
use wasm_bindgen::prelude::*;
ERROR:
Uncaught (in promise) TypeError: WebAssembly.instantiate(): Import #13 module="__wbindgen_externref_xform__" error: module is not an object or function
