### ISSUE TITLE
module="wbindgen_placeholder" error: module is not an object or function

### ISSUE THREAD

**Issue by baisijian** [rustwasm/wasm-bindgen#2531]
when I use bindgen,got there error:

JS

const loadWasm = (filepath, wasmImports) => {
    return fetch(filepath)
        .then(response => response.arrayBuffer())
        .then(bytes => WebAssembly.instantiate(bytes, {env: wasmImports}))
        .then(results => {
            return results.instance.exports;
        });
};

const init = () => {
    return loadWasm("wasm_astar", {}).then(wasmModule => {
        WASM_ASTAR.wasmModule = wasmModule;
    });
};

window.addEventListener('load', init);
RS

extern crate wasm_bindgen;
use wasm_bindgen::prelude::*;

// Import the `window.alert` function from the Web.
#[wasm_bindgen]
extern "C" {
    fn alert(s: &str);
}

#[wasm_bindgen]
pub fn test(name: &str) {
    alert(&format!("Hello, {}!", name));
}
ERROR
localhost/:1 Uncaught (in promise) TypeError: WebAssembly.instantiate(): Import #0 module="wbindgen_placeholder" error: module is not an object or function

**Comment by alexcrichton** [comment]
Thanks for the report,  but it looks like the CLI isn't being run or the right JS glue isn't being used. I'd recommend following the examples/tutorials to get a hello world working first.
