### ISSUE TITLE
Performance: Wasm should be emit instead of JS

### ISSUE THREAD

**Issue by CrimsonCodes0** [rustwasm/wasm-bindgen#2532]
### Describe the Bug

JavaScript usually has worse performance than WebAssembly, that's a given.

Yet, I'm finding, that for what I expected to emit an operation or two, whole JavaScript functions, wasm function imports, and runtime calls were being emit.

### Steps to Reproduce

1. Create a function referencing a Rust primitive method, e.g. `f64::mul_add`
2. Compile the code with Wasm-bindgen, targetting wasm32

WebAssembly Studio [link](https://webassembly.studio/?f=hw6gi0v5n5m)

### Expected Behavior

Purely WebAssembly implementations are emit for most Rust code that doesn't manipulate JS values, the DOM, etc.

### Actual Behavior

Awful code emit is across the Wasm and JS, like this:
```js
__exports.__wbindgen_fma = function(a, b, c) { return (a * b) + c; };
```

and this:
```wat
(type $t0 (func (param f64 f64 f64) (result f64)))
(import "./rustc_h_br6dlz9ozo6" "__wbindgen_fma" (func $fma (type $t0)))
(func $mul_add (export "mul_add") (type $t0) (param $p0 f64) (param $p1 f64) (param $p2 f64) (result f64)
  get_local $p0
  get_local $p1
  get_local $p2
  call $fma
)
```

Note: even a simple function like this has the aformentioned problem:
```rust
fn const remainder(x: f64, y: f64) -> f64 {
    x % y
}
```

___

Now, I have no clue if this is the fault of Wasm-bindgen, Rustc, LLVM, etc.

The fact that a Wasm-bindgen function is emit suggests that this is related to Wasm-bindgen though.

I'm finding that optimization settings have no effect on the output.

## Real bug

Most of the JavaScript implementations are probably fine (if not unexpected), but some are absolutely not replaceable, for example, Rust's `f64::powf` emits a call to a wrapped `Math.pow`, which gives entirely different results for specific values.

Run these examples in a Rust compiler and a JavaScript engine to see the differences:
Rust:
```rust
fn main() {
	let powf = f64::powf;
	let inf = f64::INFINITY;
	let nan = f64::NAN;

	println!(
		"{}\n{}\n{}\n{}\n{}",
		powf(1.0, inf),
		powf(1.0, -inf),
		powf(-1.0, inf),
		powf(-1.0, -inf),
		powf(1.0, nan)
	);
	// (1.0) across the board
}
```

JS:
```js
const println = console.log;
const powf = Math.pow;
const inf = Number.POSITIVE_INFINITY;
const nan = Number.NaN;

println(
	"%O\n%O\n%O\n%O\n%O",
	powf(1.0, inf),
	powf(1.0, -inf),
	powf(-1.0, inf),
	powf(-1.0, -inf),
	powf(1.0, nan)
);

// (nan) across the board
```

**Comment by alexcrichton** [comment]
Thanks for the report, but it looks like you're using a very old verison of the compiler perhaps? A modern Rust compiler doesn't have this same problem.
