### ISSUE TITLE
Nim-like syntax

### ISSUE THREAD

**Issue by dullbananas** [rustwasm/wasm-bindgen#2534]
Wasm_bindgen's macro syntax is somewhat complicated:

```
#[wasm_bindgen(method, js_name = doStuff)
fn do_stuff(this: Thing, options: Options)
```

In Nim, the attribute would look like:

```
{.importjs: "#.doStuff(#)".}
```

I think wasm_bindgen might benefit from this syntax which has less clutter and is more intuitive

**Comment by memoryruins** [comment]
While intuitive might be subjective here, there isn't much `wasm-bindgen` can change. It must use Rust's syntax for attributes/ attribute macros https://doc.rust-lang.org/reference/attributes.html

**Comment by dullbananas** [comment]
> While intuitive might be subjective here, there isn't much `wasm-bindgen` can change. It must use Rust's syntax for attributes/ attribute macros https://doc.rust-lang.org/reference/attributes.html

It can become more intuitive without changing attributes' syntax:

```
#[wasm_bindgen("#.doStuff(#)")]
```

**Comment by memoryruins** [comment]
Is there precedence elsewhere in rust syntax that makes that more intuitive?

**Comment by dullbananas** [comment]
If you were new to wasm_bindgen and you see only this example:

```
#[wasm_bindgen("#.items[#] = #")
fn set_item(this: &Thing, key: &Key, value: &Value);
```

Then you could easily figure out and remember how to specify constructors, getter, setter, js_name, js_namespace, etc.

**Comment by alexcrichton** [comment]
Thanks for the suggestion, but I'm not personally to change the syntax to something like this at this time.
