### ISSUE TITLE
JsValue::from_serde is very slow compare to pass string from WASM to js and then using JSON.parse to parse data

### ISSUE THREAD

**Issue by maple-leaf** [rustwasm/wasm-bindgen#2539]
### Summary

JsValue::from_serde is very slow compare to pass string from WASM to js and then using JSON.parse to parse data.

### Additional Details

I tried to use 'wasm-bindgen' to test performance of a general senario: request data from server at WASM and then pass data to JS, and find that the `JsValue::from_serde` is very slow.
And then I change to just pass response text to JS instead, and then using `JSON.parse` to parse text to json data, which compare to 'from_serde' is way better performance.

So I wanna ask if there's anything I can do to improve `from_serde` perfroamce?

The perfomrance profile (need to remove extra extension 'txt')

[Profile-from_serde_vs_json_parse.json.txt](https://github.com/rustwasm/wasm-bindgen/files/6389520/Profile-from_serde_vs_json_parse.json.txt)

The performance screenshot
![image](https://user-images.githubusercontent.com/3980995/116356153-7d0e0e80-a82d-11eb-9e8a-4c1a2dc8e281.png)

And the demo repo to reproduce this issue: https://github.com/maple-leaf/rust-wasm-playgroud

**Comment by alexcrichton** [comment]
It generally depends on where the time is being spent. If the time is being spent copying the data into wasm's linear memory, that's unfortunately pretty difficult. If the time is spent in JSON parsing itself then you could consider parsing in JS and then passing pieces to wasm so you don't copy all of the data. Unfortunately though I don't have time myself to dig into this and provide more help at this time.

**Comment by RReverser** [comment]
You might want to use [serde-wasm-bindgen](https://github.com/cloudflare/serde-wasm-bindgen) instead which avoids JSON parsing / serialization. Also see tracking issue and previous discussion in https://github.com/rustwasm/wasm-bindgen/issues/1258.
