### ISSUE TITLE
Having issues using JsValue with variable

### ISSUE THREAD

**Issue by peepopoggers** [rustwasm/wasm-bindgen#2540]
### Summary

Having issues using JsValue with variable;
Example:

```
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub fn take_js_value_by_shared_ref(xx: &JsValue) {}
```
I am using the module ssvmup to build the .rs file to a js-compatible file. 
When compiling, I get:

```
[INFO]: Installing wasm-bindgen...
error: failed to generate bindings for `take_js_value_by_value`

Caused by:
    Type of `xx` is Anyref, only Integer, String or Vector<u8> are supported now
Error: Running the wasm-bindgen CLI
Caused by: failed to execute `wasm-bindgen`: exited with exit code: 1
```

### Additional Details

Using wasm-bindgen vers 0.2.61 w/ serde-serialize feature.
rust 1.49

Using the template from [here](https://rustwasm.github.io/docs/wasm-bindgen/reference/types/jsvalue.html?highlight=jsvalue#jsvalue)

**Comment by alexcrichton** [comment]
Do you have anything in your environment configuring wasm-bindgen? Or do you have anything in your configuration of how wasm-bindgen is run passing extra flags?

**Comment by peepopoggers** [comment]
I am using `ssvmup build --enable-aot` to compile into wasm/js files.
I am not too experienced with js so what do you mean configuring? Its a plain .rs file compiling w this

**Comment by alexcrichton** [comment]
Hm ok, do you know if that is automatically setting any env vars like `WASM_INTERFACE_TYPES` or similar? That's the only thing I can imagine would cause the incompatibility here. If so that's an issue with the build tool and not wasm-bindgen itself.

**Comment by peepopoggers** [comment]
Okay, I switched modules from `ssvmup` to `wasm-pack`, and it seems to work much better now.
For anyone interested in how I implemented wasm in nodejs in my electron-js + svelte-js project:
I did `npm install wasm-pack --save-dev` to install it.

For my wasm template (inside `./src/rust_modules`) I used:
`cargo install cargo-generate` to install cargo-generate. Then I used:
`cargo generate --git https://github.com/rustwasm/wasm-pack-template` to download the template.

Then I added to package.json scripts:
`"rust-wasm": "cd ./src/rust_modules && npx wasm-pack build && rm -r ./target && rm ./pkg/.gitignore",`

For all use cases, this will be different, and I think there will be a much better way of doing this than how I implimented, but right now it works fine. 

It builds in the dir using wasm-pack as a relative module and then I remove the target (as it takes up lots of unneeded space + I remove the gitignore because otherwise github cloners will have to build the rust).

Then the `rust_modules.js` OR `rust_modules.d.ts` files in the `pkg` folder can be required as dependancies from your project.

Also here is an object handling example for wasm with rust that I made. Pls comment if there are any improvements I can make.
It recieves the JsValue object and returns the name from it.

```rust
use wasm_bindgen::prelude::*;
use serde::{Serialize, Deserialize};

// When the `wee_alloc` feature is enabled, use `wee_alloc` as the global
// allocator.
#[cfg(feature = "wee_alloc")]
#[global_allocator]
static ALLOC: wee_alloc::WeeAlloc = wee_alloc::WeeAlloc::INIT;

#[derive(Serialize, Deserialize)]
struct HelloObject {
  name: String,
  age: u32,
}

#[wasm_bindgen]
pub fn say(s: &JsValue) -> String {
  let obj: HelloObject = match s.into_serde() {
    Ok(object) => object,
    Err(_) => HelloObject { name: "invalid json".to_string(), age: 0},
  };
  return obj.name;
}
```
:)

**Comment by alexcrichton** [comment]
Glad it's working now!
