### ISSUE TITLE
Support WebIDL partial interfaces

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-bindgen#255]
https://heycam.github.io/webidl/#dfn-partial-interface

```webidl
interface SomeInterface {
  /* interface_members... */
};

partial interface SomeInterface {
  /* interface_members... */
};

```

This is essentially the same as

```webidl
mixin SomeInterfaceExtra {...}
SomeInterface includes SomeInterfaceExtra
```

Therefore I think we should block on support for mixins, and desugar this into basically the above.

Blockers:

* [ ] #246

**Comment by ohanar** [comment]
FYI, I'm working on this (I don't believe it actually depends on #246, but I'm looking at that too).

**Comment by alexcrichton** [comment]
I believe this was done in https://github.com/rustwasm/wasm-bindgen/pull/460 (yay!)
