### ISSUE TITLE
Mechanism for Async Tests

### ISSUE THREAD

**Issue by zicklag** [rustwasm/wasm-bindgen#2553]
### Motivation

I'm trying to write WASM tests for an async library. I'm attempting to port the non-wasm tests to WASM, but I run into a challenge because the tests require async code. The problem is that the only way to get a Rust async block to execute in WASM ( that I know of ) is to use `wasm_bindgen_futures::spawn_local`. Because I can't join on the spawned future, though, I have no way of making the test case wait to report on success or failure until the future has completed.

While I can panic in my spawned future, it doesn't fail the test because the test will successfully complete before the spawned future finishes. As far as I know, I have no way to actually test async code in WASM.

### Proposed Solution

I immagine that it should be possible to make async tests. These tests would be async functions that have their return values awaited on by the test runner and the test runner would make sure that it waits for and detects the failures of the async test functions.

### Alternatives

I'm not sure about any other options. 🤷‍♂️

### Additional Context

I ran into this while trying to write tests for `async-channel`: https://github.com/smol-rs/async-channel/pull/40.

**Comment by elichai** [comment]
Was there any progress on this? is there any temporary solution I can use for that?
I want to spawn futures in a way that is abstracted over wasm/tokio/etc but get a handle to that spawn futures so I can await on it later on

**Comment by daxpedda** [comment]
This has already been possible for a while no, you can just write:
```rust
#[wasm_bindgen_test]
async fn test() {
    console::log_1(&"Hello, World!".into());
}
```
