### ISSUE TITLE
Keep track of stability for InterfaceMethod

### ISSUE THREAD

**Issue by grenierdev** [rustwasm/wasm-bindgen#2560]
### Describe the Bug

While trying to add the File System Access API WEBIDL in unstable, I noticed that while `AttributeInterfaceData` contains a `stability` member, `OperationData` does not. This means that new methods added by this unstable WEBIDL on global interfaces, like `Window::show_directory_picker`, aren't tagged with `#[cfg(web_sys_unstable_apis)]`.

### Steps to Reproduce

1. Clone https://github.com/pxlr-app/wasm-bindgen/tree/filesystemaccess
2. Generate the bindings `cargo run --release --package wasm-bindgen-webidl -- webidls src/features`

### Expected Behavior

The unstable WEBIDL adds new methods on `Window` that aren't tagged with `#[cfg(web_sys_unstable_apis)]` since the stability of methods inherits theirs from the interface.

### Actual Behavior

Function like `Window::show_directory_picker` is exposed to non-unstable feature.

**Comment by ImUrX** [comment]
@grenierdev some other properties do know they are unstable, i think the code is in there, but it doesnt cover all cases
