### ISSUE TITLE
Error on try the example page from js-promises-and-rust-futures

### ISSUE THREAD

**Issue by eduardonunesp** [rustwasm/wasm-bindgen#2563]
Trying the example from docs on page https://rustwasm.github.io/docs/wasm-bindgen/reference/js-promises-and-rust-futures.html, but it gives error on JsFuture

```rust
use wasm_bindgen::prelude::*;
use wasm_bindgen::JsValue;

async fn get_from_js() -> Result<JsValue, JsValue> {
    let promise = js_sys::Promise::resolve(&42.into());
    let result = wasm_bindgen_futures::JsFuture::from(promise).await?;
    Ok(result)
}

// This is like the `main` function, except for JavaScript.
#[wasm_bindgen(start)]
pub fn main() -> Result<(), JsValue> {
    // This provides better error messages in debug mode.
    // It's disabled in release mode so it doesn't bloat up the file size.
    #[cfg(debug_assertions)]
    console_error_panic_hook::set_once();

    Ok(())
}
```

Error 

```bash
error[E0277]: `JsFuture` is not a future
 --> src/lib.rs:6:18
  |
6 |     let result = wasm_bindgen_futures::JsFuture::from(promise).await?;
  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `JsFuture` is not a future
  |
  = help: the trait `Future` is not implemented for `JsFuture`
  = note: required by `poll`

error: aborting due to previous error
```

**Comment by alexcrichton** [comment]
I think [this is indeed a future](https://docs.rs/wasm-bindgen-futures/0.4.24/wasm_bindgen_futures/struct.JsFuture.html), so the more likely issue is that you're not importing the `JsFuture` name from the `wasm-bindgen-futures` crate.

**Comment by eduardonunesp** [comment]
Sorry for the confusion, I was using an older version from `wasm-bindgen-futures` which probably wasn't implemented, not sure, but the version was `wasm-bindgen-futures = "0.3.22"` now with the latest version `wasm-bindgen-futures = "0.4.24"` it is working as expected, thank you.
