### ISSUE TITLE
Support WebIDL callback functions

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-bindgen#257]
https://heycam.github.io/webidl/#idl-callback-functions

Example:

```webidl
callback AsyncOperationCallback = void (DOMString status);

interface AsyncOperations {
  void performOperation(AsyncOperationCallback whenFinished);
};
```

~~Should probably translate these into `FnMove(...) -> ...` since we can't be sure about the way the interfaces might use the callbacks.~~

**Comment by Pauan** [comment]
What's an `FnMove`? Did you mean `FnMut`?

**Comment by fitzgen** [comment]
Woops, yeah just meant that we have to give up ownership of anything the function closes over and move it into the function.

**Comment by Pauan** [comment]
@fitzgen Right, stdweb handles that by requiring callbacks to be `'static`, which seems to work well.

**Comment by alexcrichton** [comment]
For anything that needs `'static` then this translates in wasm-bindgen to `&Closure<FnMut<(...)>>`, but anything that doesn't need `'static` this'll translate to a usual `&mut FnMut(...)`

**Comment by fitzgen** [comment]
For arguments to imported JS functions, I believe we want to use `Closure<FnMut(...) -> ...>`.

For returned values from imported JS functions/getters, I believe we want to use `js_sys::Function`.

**Comment by alexcrichton** [comment]
@fitzgen and I had a good talk about this today, and the conclusions were:

* We should probably bind *all* callbacks as `js_sys::Function`.
* Next, we should provide the ability, from a `Closure<T>`, to get the underlying `JsValue` (which is actually a `js_sys::Function` but will need a cast)
* Additionally we should provide the ability to get a `JsValue` corresponding to `&mut FnMut(..)` (or something equivalent)

The actual method of acquiring a `JsValue` from `Closure<T>` will require mega-hacks that's not worth going into here, but I'll look into the implementation tomorrow.

**Comment by alexcrichton** [comment]
I've added support for this in https://github.com/rustwasm/wasm-bindgen/pull/796
