### ISSUE TITLE
Iterating over Headers

### ISSUE THREAD

**Issue by fosskers** [rustwasm/wasm-bindgen#2572]
[The Fetch API][fetch] offers methods like `entries`, `keys`, and `values`, although these aren't given bindings in the `web_sys::Headers` type. Is there a technical reason for that, or is this something that could reasonably be added?

Otherwise, I've been having difficulty discovering how to get values _out_ of a `Headers` if you don't know ahead of time what the keys are (so `get` doesn't help).

Thank you for any help you can offer.

[fetch]: https://developer.mozilla.org/en-US/docs/Web/API/Headers

**Comment by CrimsonCodes0** [comment]
Now I do agree that these should be implemented (maybe there's some missing WebIDL?), but Headers objects are iterable as is via `[Symbol.iterator]`, so would [this PR](https://github.com/rustwasm/wasm-bindgen/pull/1913) suit your use?

**Comment by fosskers** [comment]
> but Headers objects are iterable as is via [Symbol.iterator]

Within raw JS, you mean?

**Comment by CrimsonCodes0** [comment]
> > but Headers objects are iterable as is via [Symbol.iterator]
> 
> Within raw JS, you mean?

Indeed, but the PR was supposed to expose the functionality of a JavaScript `[Symbol.iterator]` to Rust code through wasm-bindgen.

**Comment by fosskers** [comment]
Right, such functionality would be ideal, I haven't yet found another way to do it with the existing Rust API.

**Comment by daxpedda** [comment]
Exposed in #3962.
