### ISSUE TITLE
How can I run Deno in a browser?

### ISSUE THREAD

**Issue by nabezokodaikon** [rustwasm/wasm-bindgen#2576]
### Summary
How can I run Deno in a browser?
When I download and output Deno, it doesn't work with an error in the browser.

### Additional Details
The command executed.
```bash
$ cargo build --target wasm32-unknown-unknown --release
$ wasm-bindgen target/wasm32-unknown-unknown/release/wasm_deno.wasm --out-dir ./server/public/pkg --target deno
```
This is the error that occurred.
<img width="1194" alt="スクリーンショット 2021-06-08 19 41 37" src="https://user-images.githubusercontent.com/3197942/121171539-945f0380-c891-11eb-85a5-86048d993186.png">

**Comment by CrimsonCodes0** [comment]
Deno is a server-side JavaScript/WebAssembly runtime using V8 as it's engine. Similar to Node.js, you cannot attempt to use it's native APIs in a browser, which Deno output uses. If you want to target a web browser, target the web, not Deno!

**Comment by nabezokodaikon** [comment]
When I specified the web, another error occurred.

rust coode
```rust
//@deno-types="../pkg/wasm_deno.d.ts"
import { greet } from '../pkg/wasm_deno.js';
greet('Hello');
```

Running commands
```
$ cargo build --target wasm32-unknown-unknown --release
$ wasm-bindgen target/wasm32-unknown-unknown/release/wasm_deno.wasm --out-dir ./server/public/pkg --target web
$ deno bundle server/public/ts/greet.ts server/public/js/greet.js
```

Error
<img width="1015" alt="スクリーンショット 2021-06-09 9 16 51" src="https://user-images.githubusercontent.com/3197942/121273558-7af69f80-c903-11eb-9884-aa1b5dd2d7be.png">

**Comment by CrimsonCodes0** [comment]
@nabezokodaikon You seem to be misusing Wasm-bindgen's JavaScript glue code? Your code should be in a seperate file, and should only call into any of the Wasm functions only after loading the wasm and resolving the promise, after that point `wasm` would be assigned the correct value.

I strongly suggest reviewing the documentation on how to correctly set it up and use.

**Comment by nabezokodaikon** [comment]
I tried to follow the sample, but I get the same error.
[hello_world](https://github.com/rustwasm/wasm-bindgen/blob/master/examples/hello_world/index.js)
```
const rust = import('../pkg/wasm_deno.js');
rust
  .then(m => m.greet('World!'))
  .catch(e => console.log(e));
```

**Comment by nabezokodaikon** [comment]
Does typescript bundled with deno not work with browser?

**Comment by nabezokodaikon** [comment]
I solved it by reading the wasm file separately using fetch.
```typescript
import init, { greet } from '../pkg/wasm_deno.js';
async function run() {
  await init(await fetch('../public/pkg/wasm_deno_bg.wasm'));
  greet('hello');
}
run();
```
