### ISSUE TITLE
Support WebIDL callback interfaces

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-bindgen#258]
https://heycam.github.io/webidl/#dfn-callback-interface

These are like dictionaries (structural, not nominal; user-defined, not host defined) for sets of callback functions.

Example:

```webidl
callback interface OpenCloseListener {
  void onOpen();
  void onClose();
};
```

These should probably be translated into traits, and then operations that take or return these should take `Box<OpenCloseListener>`.

**Comment by fitzgen** [comment]
so callbacks interfaces with a single callback operation are special and can be just a function: https://heycam.github.io/webidl/#es-user-objects

> As described in §2.11 Objects implementing interfaces, callback interfaces can be implemented in script by an ECMAScript object. The following cases determine whether and how a given object is considered to be a user object implementing a callback interface:
>
 > * If the interface is a single operation callback interface (defined below) then any object is considered to implement the interface. The implementation of the operation (or set of overloaded operations) is as follows:
>
>   * If the object is callable, then the implementation of the operation (or set of overloaded operations) is the callable object itself.
>
>   * Otherwise, the object is not callable. The implementation of the operation (or set of overloaded operations) is the result of invoking the internal [[Get]] method on the object with a property name that is the identifier of the operation.

and overloads of the same callbacks all count as a "single" callback:

> A single operation callback interface is a callback interface that:
>
> * is not declared to inherit from another interface,
>
> * has no attributes, and
>
> * has one or more regular operations that all have the same identifier, and no others.

**Comment by fitzgen** [comment]
we probably want to:

* treat all callback interfaces as dictionaries of `js_sys::Function`, as we were planning to.
* also implicitly add an overload of any function that takes a single operation callback interface for plain `js_sys::Function` instead of teh dictionary style object

**Comment by fitzgen** [comment]
Relevant firefox code:

* https://searchfox.org/mozilla-central/rev/6201a9e0067cf6af118c6a99ae9314b8ceb2c4d5/dom/bindings/Codegen.py#16103-16115
* https://searchfox.org/mozilla-central/source/__GENERATED__/dom/bindings/EventListenerBinding.cpp#37-48

**Comment by alexcrichton** [comment]
That sounds like a solid strategy to me!
