### ISSUE TITLE
Module imports aren't generated

### ISSUE THREAD

**Issue by Jules-Bertholet** [rustwasm/wasm-bindgen#2593]
### Describe the Bug

Module imports (as [documented](https://rustwasm.github.io/docs/wasm-bindgen/reference/attributes/on-js-imports/module.html)) don't work; no import statement is generated

### Steps to Reproduce

1. Go to https://rustwasm.github.io/docs/wasm-bindgen/reference/attributes/on-js-imports/module.html
2. Copy the first example exactly into a new `wasm-bindgen` project
3. Export a dummy function that takes the `ThirtySixChambers` type as an argument
3. Build the project with `wasm-bindgen`, with options `--typescript --target web`
4. No import statement is generated in the resulting JS

### Expected Behavior

An import statement like `import { ThirtySixChambers } from "wu/tang/clan";` is generated, as documented

### Actual Behavior

No import statement is generated in the JS glue code

**Comment by jquesada2016** [comment]
I ran into a very similar issue today, but it was me subtly misreading the docs. This is what I originally did:

```rust
#[wasm_bindgen]
extern "C" {
    type Firestore;

    #[wasm_bindgen(js_name = getFirestore, module = "@firebase/firestore")]
    pub fn get_firestore() -> Firestore;
}
```

The above didn't work, however, the following did.

```rust
#[wasm_bindgen(module = "@firebase/firestore"))] // Main change here
extern "C" {
    type Firestore;

    #[wasm_bindgen(js_name = getFirestore] // And here
    pub fn get_firestore() -> Firestore;
}
```

Note that this generates imports for the entire extern block scoped to that specific module. If you want to import from another library or file, you have to create another extern block.

Hope this helps!

Also, there is, what I think to be a bug with importing, though I'm not going to make an issue right now, if you could do it for me, that'd be wonderful. But it goes something like this, taking the above example:

```rust
#[wasm_bindgen(module = "@firebase/firestore"))]
extern "C" {
    #[wasm_bindgen(js_name = getFirestore]
    pub fn get_firestore(); // Notice this returns nothing...
}
```

will produce imports:
```rust
import * as __wbg_star0 from '@firebase/firestore';
```

Which is not what one generally wants...however, if instead you do the following:

```rust
#[wasm_bindgen(module = "@firebase/firestore"))]
extern "C" {
    #[wasm_bindgen(js_name = getFirestore]
    pub fn get_firestore() -> JsValue; // Notice this returns ANYTHING
}
```

Then this works as expected:

```rust
import { getFirestore } from '@firebase/firestore';
```

You just need to return something.
