### ISSUE TITLE
Receive "...wasm: Syntax error: end of file unexpected" when running "cargo test"

### ISSUE THREAD

**Issue by stnbu** [rustwasm/wasm-bindgen#2594]
### Describe the Bug

When I run `cargo test --target wasm32-unknown-unknown` on [my crate](https://github.com/stnbu/sandbox/tree/8afd4bee2e92fa01237faf7038e9123d4a85dc88/wasm/foobar), I get:

```
serde v1.0.126
   Compiling ryu v1.0.5
   Compiling lazy_static v1.4.0
   Compiling serde_json v1.0.64
   Compiling itoa v0.4.7
   Compiling wasm-bindgen v0.2.74
   Compiling quote v1.0.9
   Compiling wasm-bindgen-backend v0.2.74
   Compiling wasm-bindgen-macro-support v0.2.74
   Compiling wasm-bindgen-macro v0.2.74
   Compiling foobar v0.1.0 (/mydir/foobar)
    Finished test [unoptimized + debuginfo] target(s) in 29.02s
     Running unittests (target/wasm32-unknown-unknown/debug/deps/foobar-e65e2b4cd23331b9.wasm)
/mydir/foobar/target/wasm32-unknown-unknown/debug/deps/foobar-e65e2b4cd23331b9.wasm: 1: /mydir/foobar/target/wasm32-unknown-unknown/debug/deps/foobar-e65e2b4cd23331b9.wasm: Syntax error: end of file unexpected
error: test failed, to rerun pass '--lib'
```

Note that both

* `wasm-pack build --target web`
* `cargo build --target wasm32-unknown-unknown`

_Do_ succeed.

I could totally be doing something stupid (new to Rust), but looking forward to knowing what!

### Steps to Reproduce

1. Set up pre-requisite wasm-bindgen tooling.
1. run `cargo test --target wasm32-unknown-unknown` on [this crate](https://github.com/stnbu/sandbox/tree/8afd4bee2e92fa01237faf7038e9123d4a85dc88/wasm/foobar).

### Expected Behavior

I expect (barring bugs of mine) the test to pass.

### Actual Behavior

Tooling fails to build `wasm` file, emitting the above error.

### Additional Context

`src/lib.rs`:
``` rust
use wasm_bindgen::prelude::*;
use std::collections::HashMap;
use serde::{Serialize, Deserialize};

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn it_works() {
	let json = send_example_to_js();
	assert!(!json.is_string())
    }
}

#[derive(Serialize, Deserialize)]
pub struct Example {
    pub field1: HashMap<u32, String>,
    pub field2: Vec<Vec<f32>>,
    pub field3: [f32; 4],
}

#[wasm_bindgen]
pub fn send_example_to_js() -> JsValue {
    let mut field1 = HashMap::new();
    field1.insert(0, String::from("ex"));
    let example = Example {
        field1,
        field2: vec![vec![1., 2.], vec![3., 4.]],
        field3: [1., 2., 3., 4.]
    };
    JsValue::from_serde(&example).unwrap()
}
```

`Cargo.toml`:
``` toml
[package]
name = "foobar"
version = "0.1.0"
authors = ["Mike"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = { version = "0.2.74", features = ["serde-serialize"] }
```

**Comment by alexcrichton** [comment]
Thanks for the report! The problem here is `cargo` is trying to execute a `*.wasm` as it if were a native executable. Your OS is then reporting the somewhat obscure error message. (I don't know why)

Wasm-bindgen's tests are intended to be run as `wasm-bindgen-test-runner the-wasm-file.wasm`, which you can configure with Cargo by setting the `CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUNNER` environment variable (more info about this in cargo's docs)

**Comment by stnbu** [comment]
> Thanks for the report! The problem here is `cargo` is trying to execute a `*.wasm` as it if were a native executable. Your OS is then reporting the somewhat obscure error message. (I don't know why)
> 
> Wasm-bindgen's tests are intended to be run as `wasm-bindgen-test-runner the-wasm-file.wasm`, which you can configure with Cargo by setting the `CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUNNER` environment variable (more info about this in cargo's docs)

Perfect! In retrospect that makes a lot of sense. I'll do the above.

**Comment by stnbu** [comment]
[Sure enough](https://github.com/stnbu/sandbox/commit/2618443933e02363117d80b8eca8fa90226783e8). `wasm-pack test --node` now works. Thanks again.
