### ISSUE TITLE
Support WebIDL enumerations

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-bindgen#260]
https://heycam.github.io/webidl/#idl-enums

```webidl
enum MealType { "rice", "noodles", "other" };
```

These are always string literals.

I don't think we want to translate these into Rust `enum`s because Rust is allowed to assume they are exhaustive, meaning that if the definitions are extended in the future, we would get UB in Rust.

Instead, we can translate it into something like:

```rust
mod MealType {
    const Rice: &'static str = "rice";
    // ...
}

// usage:
foo(MealType::Rice);
```

**Comment by ohanar** [comment]
I would also vote for mapping them to rust enum's, especially given that the non-exhaustive enum's rfc was accepted and has already been implemented in the nightly compiler.

**Comment by fitzgen** [comment]
SGTM!
