### ISSUE TITLE
How to run tests with custom rustflags

### ISSUE THREAD

**Issue by d3lm** [rustwasm/wasm-bindgen#2603]
I am trying to run tests with `wasm-bindgen` but for my crate I need specify rustflags to enable `atomics` and `bulk-memory` as compile the standard library via `build-std`.

I have the rustflags inside a config file `.cargo/config` and tried to invoke the tests through wasm-pack with `wasm-pack test --chrome -- -Z build-std=std,panic_abort` but it won't pick up the rustflags from the config file. It does seem to recompile std tho.

Is there a way to use rustflags for `cargo test` with wasm-bindgen and wasm-pack?

**Comment by alexcrichton** [comment]
I don't know how `wasm-pack` works here, but I would recommend using `RUSTFLAGS` for `cargo test` (and/or `.cargo/config.toml` configuration) for configuring flags as with other Rust builds. I don't think there's anything special when running with wasm-bindgen in this regard.

**Comment by d3lm** [comment]
I actually have a `.cargo/config`, but it's not picking up my `[build]` rustflags. Any tips?

**Comment by alexcrichton** [comment]
Cargo only reads one of configuration or `RUSTFLAGS`, so you may have both set? Otherwise though that's generally a Cargo issue, not a wasm-bindgen issue.
