### ISSUE TITLE
Disable debug logs?

### ISSUE THREAD

**Issue by i-schuetz** [rustwasm/wasm-bindgen#2604]
Since [0.2.71](https://github.com/rustwasm/wasm-bindgen/releases/tag/0.2.71) getting thousands of log messages on the console when using wasm-bindgen (via e.g. `trunk serve`):

> [2021-06-28T12:27:12Z DEBUG walrus::module::functions] emit function Id { idx: 15476 } Some("core::alloc::layout::Layout::new::h356d9a33118a296b")
> [2021-06-28T12:27:12Z DEBUG walrus::module::functions] emit function Id { idx: 14293 } Some("alloc::rc::RcInnerPtr::dec_weak::heb08f35dd9cbc9b2")
...

I just confirmed that it doesn't happen with 0.2.70 and still happens with 0.2.74. Do I've to configure something to disable these logs?

**Comment by alexcrichton** [comment]
I believe this crate uses `env_logger` which can have log levels customized via the `RUST_LOG` env var. You can disable logging with `walrus=info` or similar in your logging specification (or only enable logging for one crate you're interested in)

**Comment by i-schuetz** [comment]
Ah thanks for the quick response! It was enough to set `RUST_LOG` to `WARN` in my case.
