### ISSUE TITLE
Fetch API cannot load file://xxxx.wasm file

### ISSUE THREAD

**Issue by DarrenTsung** [rustwasm/wasm-bindgen#261]
I'm running into this error on Google Chrome (Version 67.0.3396.79 (Official Build) (64-bit)) when attempting to use wasm-bindgen with --no-modules:
```
Fetch API cannot load file:///example_wasm_file.wasm. URL scheme must be "http" or "https" for CORS request.
```

This is in the `init()` function of the generated js file. Is there any known workaround for this or is fetching a local file just broken in Chrome? It works fine on Firefox for me.

**Comment by jsheard** [comment]
There are some launch params that supposedly enable `file://` access in Chrome but I could never get them to work, I'm guessing they only affect `XMLHttpRequest` and not the newer `fetch` API.

I'd suggest just using something like [live-server](https://www.npmjs.com/package/live-server), which has the side benefit of automatic reloading.

**Comment by alexcrichton** [comment]
Thanks for the report! If `fetch` doesn't work, what's the best way to load resources dynamically via the `file://` url? If it's small enough we can probably just include it inline in the output

**Comment by jsheard** [comment]
Maybe inline the wasm in `--debug` mode, and `fetch()` it in release?

**Comment by alexcrichton** [comment]
I'd personally prefer to investigate something like [XMLHttpRequest](https://stackoverflow.com/questions/30008114/how-do-i-promisify-native-xhr) to see if that works with `file://` urls

**Comment by leonwanghui** [comment]
Hi all, I have came across similar issues (see https://github.com/rustwasm/wasm-pack/issues/710), so what's the status of this issue?

**Comment by Pauan** [comment]
This is because of browser security restrictions: you cannot load `file://` URLs in the browser, not even with `XMLHttpRequest`.

The solution is to use a local webserver like [`https`](https://crates.io/crates/https) (you only need to do `cargo install https` and then run `http`) and then access your project on `http://localhost:8000`

**Comment by alexcrichton** [comment]
I'm going to close this because I don't think that there's anything we can do about this, and `wasm-bindgen` will require some degree of HTTP server to serve up files. It's going to be on the tooling around wasm-bindgen to provide the server.

**Comment by mukeshsoni** [comment]
Does that mean i cannot use the wasm generated from rust using `wasm-bindgen` in a chrome extension?

**Comment by Pauan** [comment]
@mukeshsoni It's possible to use wasm-bindgen with Chrome/Firefox extensions ([I've done that](https://github.com/Pauan/SaltyBetBot)). The easiest way is to use [the Rollup plugin](https://github.com/wasm-tool/rollup-plugin-rust#chrome--firefox-extensions).

Extension files aren't loaded from the `file://` protocol, they're loaded from the `chrome-extension://` protocol, so you just need to load `chrome.runtime.getURL("/path/to/foo_bg.wasm")`

**Comment by mukeshsoni** [comment]
I ended up using `wasm-pack build --target web`, using rollup to bundle my file (since webpack couldn't understand `import.meta`, and copying the generated wasm file to my dist file. That worked.

I did try using the rollup plugin but couldn't get it to work. Might give it another try once i finish the whole thing. Thanks for the pointer @Pauan

**Comment by Pauan** [comment]
@mukeshsoni The plugin I linked is our official Rollup plugin, so it should work fine (and it's kept up to date with wasm-bindgen). Any other plugins are unofficial and third-party, so we can't guarantee their correctness.

**Comment by archonic** [comment]
I agree that this isn't a wasm-bindgen concern but I'm trying out wasm and rust for the first time using [the tutorial](https://rustwasm.github.io/docs/wasm-pack/tutorials/index.html) and I hit this. 100% of people doing the same will hit this issue. Perhaps the default template could include an intergration of live-server?
