### ISSUE TITLE
wasm_bindgen_futures poll future?

### ISSUE THREAD

**Issue by iMplode-nZ** [rustwasm/wasm-bindgen#2613]
Is there any way to check whether a future is finished and return a value if it is finished with `wasm_bindgen_futures`? I know I can do this with something like an `Rc<RefCell<Option<T>>` but I would prefer to have a simpler way to do so.

**Comment by alexcrichton** [comment]
Using futures and working with them is within the realm of the `std::future` module of the standard library, so I'd recommend checking there. Currently the crate doesn't support any functionality beyond the `Future` trait itself, and you'd use `Future::poll` to see if the value is ready yet.
