### ISSUE TITLE
Using wasm bindgen for interacting rust programs compiled to wasm from C/C++ runtimes

### ISSUE THREAD

**Issue by vdimir** [rustwasm/wasm-bindgen#2615]
### Summary

Can wasm bindgen be used from environment other than JS? 

As I understand it implements some API(/ABI?) for JS. If this structures are documented somewhere and stable, can I place this structures on stack from C++ in the same way as it bindgen does before calling Rust function?
Now it's difficult to interact with Rust programs compiled to WASM from C++ without using `unsafe` if something other than `int` or `float` should be passed between native/wasm boundary. I suppose wasm bindgen can help to solve it, is it?

**Comment by alexcrichton** [comment]
While it's technically possible to do so I would not recommend doing so. The wasm-bindgen CLI tool and crate have always been designed with JS in mind. For wasm-bindgen-like functionality outside of the web I'd recommend following the wasm interface types proposal.
