### ISSUE TITLE
Can I/how should I publish the same crate to both crates.io and npm (WASM)?

### ISSUE THREAD

**Issue by czonios** [rustwasm/wasm-bindgen#2627]
### Summary

I have a crate, already published on crates.io, that I would like to also publish to npm (after creating functions that can be called from JS and compiling to WASM).
A simple way to do this would be to create a separate project, add my crate as a dependency, and essentially re-export/create wrappers for the functions that need to be exposed.

Is there a better way to do this, so that all of my code is in one place and everything is in sync? For example, a separate `lib` and `Cargo.toml` file that all use the same source code? I read about cargo workspaces but they don't seem to be what I'm looking for. I haven't worked with WASM before, so I realize this question might be dumb. Thank you for your time!

**Comment by alexcrichton** [comment]
This question is largely up to you, there's not really a correct answer. It depends on how you expect your library to be used and how you'd like to design its usage as well.
