### ISSUE TITLE
wasm-bindgen broken : serde : proc-macro2

### ISSUE THREAD

**Issue by sambathl** [rustwasm/wasm-bindgen#263]
seems proc-macro2 dependency of serde got unstable, we can't able to do `cargo build` with wasm-bindgen as dependency

**Comment by sambathl** [comment]
log for compiling hello world example 
` Compiling proc-macro2 v0.4.6
   Compiling serde_json v1.0.20
error[E0433]: failed to resolve. Could not find `Punct` in `proc_macro``

**Comment by kaorun343** [comment]
Could you check the version of  `proc-macro2` written in `Cargo.lock` ?
I also mentioned this problem and solve by deleting and recreating the lock file.

**Comment by mehdishojaei** [comment]
It's not related to `serde`, it's all about `proc_macro`.

**Comment by david-yan** [comment]
Hello, I was just wondering if there has been a fix to the issue or if it is being addressed. Thanks!

**Comment by dtolnay** [comment]
I am going to need some help reproducing this. I tried the following:

```bash
cargo new repro
echo 'wasm-bindgen = "0.2.11"' >> repro/Cargo.toml
cargo build --manifest-path repro/Cargo.toml
```

and it compiled successfully.

**Comment by david-yan** [comment]
Which toolchain are you using? The following reproduced the error for me:
```
cargo new repro
echo 'wasm-bindgen = "0.2.11"' >> repro/Cargo.toml
echo `nightly-2018-05-10` > rust-toolchain
cargo build --manifest-path repro/Cargo.toml

**Comment by dtolnay** [comment]
The "nightly" feature of proc-macro2 does not (cannot) support old nightlies. You need to be using the newest nightly. Nightly means that you update the compiler every night.

**Comment by david-yan** [comment]
I see. That complicates things for me but thanks so much for your response!

**Comment by mehdishojaei** [comment]
Cloning the repo and checking out to 0.2.8 works!
```
git clone https://github.com/rustwasm/wasm-bindgen.git
git checkout 0.2.8
```

**Comment by AugustinLF** [comment]
@dtolnay When running the same commands as you
```
cargo new repro
echo 'wasm-bindgen = "0.2.11"' >> repro/Cargo.toml
cargo build --manifest-path repro/Cargo.toml
```
At `Compiling proc-macro2 v0.4.6`, I got several errors, the first one being
```
error[E0433]: failed to resolve. Could not find `Group` in `proc_macro`
```
I don't think I have any nightly builds, do you know any command I could run to confirm that? I also got the same errors when simply running the examples in the readme.

**Comment by fitzgen** [comment]
> Second edit: Problem solved, misread parts of the readme (shame on me), and was not running the nightly build of rustup, as required. Everything works like a charm, sorry for the troubles!

Ok, closing this issue then :)
