### ISSUE TITLE
Typed array -> Vec conversion appears to unnecessarily preinitialize Vec contents

### ISSUE THREAD

**Issue by adrian17** [rustwasm/wasm-bindgen#2639]
Referring to the code here:

https://github.com/rustwasm/wasm-bindgen/blob/b97837b0989b58595f3ef72bd5691ce420591204/crates/js-sys/src/lib.rs#L5133-L5138

Rust appears to be unable to optimize out the first line, zero-initializing the Vec. This makes the compiler generate a `memset`, which can be slower than actual action of copying the data. Here's an example profile of running `to_vec()` on an 80MB `Uint8Array` on Firefox:

![image](https://user-images.githubusercontent.com/4729533/127533178-0ed93a02-be23-4cd4-9c43-d77e15cf13ff.png)

The other available APIs also make it impossible to avoid - `copy_to` and `raw_copy_to` take a slice, and creating a slice requires elements to be already initialized (otherwise it's UB, in my understanding). And the slice is only really needed for a length check, which `to_vec` already guarantees will pass.

So an extra API taking a pointer (and refactored `to_vec()` using `unsafe`) could make this cheaper without UB... at least on paper - the pointer is never directly written into, so I'm hoping the aliasing rules correctly handle this case of pointer escaping as `usize`.

```rs
/// Requires `dst` to point to a buffer large enough to fit this array's contents.
pub unsafe fn raw_copy_to_ptr(&self, dst: *mut $ty) {
    let buf = wasm_bindgen::memory();
    let mem = buf.unchecked_ref::<WebAssembly::Memory>();
    let all_wasm_memory = $name::new(&mem.buffer());
    let offset = dst as usize / mem::size_of::<$ty>();
    all_wasm_memory.set(self, offset as u32);
}
/// Efficiently copies the contents of this JS typed array into a new Vec.
pub fn to_vec(&self) -> Vec<$ty> {
    let mut output = Vec::with_capacity(self.length() as usize);
    unsafe {
        self.raw_copy_to_ptr(output.as_mut_ptr());
        output.set_len(self.length() as usize);
    }
    output
}
```
And the memset is gone:
![image](https://user-images.githubusercontent.com/4729533/127536071-b9e9fe4e-a8d1-40cc-94e1-5994810e8fbc.png)

Anyway, if you think that's a good idea, I can make a PR with this change? Or you can take it over.

**Comment by alexcrichton** [comment]
Indeed yeah most of the vector operations are optimized for safety right now, but that's just to add an initial version we know that works. It was always assumed though that at one point in the future we'd optimize these, so if you'd like to send a PR for this I'd be happy to review!

As a side note, I'm curiuos how much compiling with `-Ctarget-feature=+bulk-memory` helps? That should compile the wasm-defined `memset` into a native `memory.set` instruction which should be much faster, albeit still slower than not actually doing the memset at all (just curious about the timings)

**Comment by adrian17** [comment]
> As a side note, I'm curiuos how much compiling with -Ctarget-feature=+bulk-memory helps?

For some reason, `__rdl_alloc_zeroed` still calls `memset()` for me. (though, my own functions indeed start using `memory.fill` as they should) I'm guessing I'd need to recompile stdlib with this flag to have zeroed-allocation use `memory.fill`.

**Comment by alexcrichton** [comment]
Ah yeah you'd have to recompile libstd, but that, for wasm, should be relatively simple with `-Zbuild-std` passed to Cargo (although still not the simplest...)

**Comment by adrian17** [comment]
I worked around it by using `Vec::with_capacity`, and only actually filling it after allocation. With this and `+bulk-memory`, yeah, the improvements are huge:
![image](https://user-images.githubusercontent.com/4729533/127625631-b2ada5ad-7e63-46f9-b2ad-6d5ef3f527c9.png)

(in general my experience with bulk-memory on FF is that for large buffers it gives orders-of-magnitude improvements; the improvement falls off at Vecs smaller than 100 bytes, and below 10 bytes it can actually become slower than wasm-native `memset`)

**Comment by alexcrichton** [comment]
Nice! In any case bulk-memory won't help in the long run since the fix is to just not zero at all, but nice to see that it's working well for your use case at least!

**Comment by alexcrichton** [comment]
er, didn't mean to close.
