### ISSUE TITLE
WebGLRenderingContext.scissor() binding is incomplete.

### ISSUE THREAD

**Issue by wdanilo** [rustwasm/wasm-bindgen#2640]
### Describe the Bug

According to [docs](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/scissor) all params are optional, while the only binding [exposed](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.WebGl2RenderingContext.html#method.scissor) is `pub fn scissor(&self, x: i32, y: i32, width: i32, height: i32)`

**Comment by wdanilo** [comment]
I'm closing it. The MDN docs are invalid. The spec doesn't define the defaults and they do not work in browsers.

**Comment by CrimsonCodes0** [comment]
@wdanilo Although there isn't a bug here, you could still try getting this fixed upstream: <github.com/mdn/content>
