### ISSUE TITLE
`#[wasm_bindgen(getter_with_clone)]`: unknown attribute

### ISSUE THREAD

**Issue by 0x009922** [rustwasm/wasm-bindgen#2641]
### Summary

I am just trying the trivial [example from documentation](https://rustwasm.github.io/wasm-bindgen/reference/attributes/on-rust-exports/getter_with_clone.html):

```rust
#[wasm_bindgen(getter_with_clone)]
pub struct Foo {
    pub bar: String,
    pub baz: String,
}
```

And I receive this error:

```
error: unknown attribute
  --> src/lib.rs:21:16
   |
21 | #[wasm_bindgen(getter_with_clone)]
   |                ^^^^^^^^^^^^^^^^^
```

Project is absolutely clear and is created by `wasm-pack new`

What am I doing wrong?

**Comment by alexcrichton** [comment]
Thanks for the report, but support landed for this yesterday so it just hasn't been released to crates.io yet.

**Comment by 0x009922** [comment]
@alexcrichton, could you tell when support for this will be released?

**Comment by alexcrichton** [comment]
Yes I can release a new version today.
