### ISSUE TITLE
WebGL Example Fails in Apple Safari

### ISSUE THREAD

**Issue by dan-fritchman** [rustwasm/wasm-bindgen#2646]
### Describe the Bug

The `webgl` example renders as a blank (white) screen on MacOS Safari. 

### Steps to Reproduce

Navigate to the "compiled example online" link from the docs:  
https://rustwasm.github.io/wasm-bindgen/exbuild/webgl/  
(From https://rustwasm.github.io/wasm-bindgen/examples/webgl.html)  

Same when running a local server on the current head-commit.

**Comment by jonboj** [comment]
Does Safari trace anything in the Developer Console?

**Comment by dan-fritchman** [comment]
Here's the error printed to its console: 

```
RuntimeError: Unreachable code should not be executed (evaluating '_index_bg_wasm__WEBPACK_IMPORTED_MODULE_0__["__wbindgen_start"]()')
<?>.wasm-function[__rust_start_panic]
<?>.wasm-function[rust_panic]
<?>.wasm-function[std::panicking::rust_panic_with_hook::h2d9079427a2d996a]
<?>.wasm-function[std::panicking::begin_panic_handler::{{closure}}::h4e49f350d9f4de36]
<?>.wasm-function[std::sys_common::backtrace::__rust_end_short_backtrace::h91e711607d91be52]
<?>.wasm-function[rust_begin_unwind]
<?>.wasm-function[core::panicking::panic_fmt::h1fea623755fffed7]
<?>.wasm-function[core::panicking::panic::h38cac710b5048ca0]
<?>.wasm-function[core::option::Option<T>::unwrap::hce43372c88ddf382]
<?>.wasm-function[webgl::start::hcdb58911c74967bd]
<?>.wasm-function[start]
wasm-stub
371
Eval Code
eval
./pkg/index.js — 1.index.js:11
__webpack_require__ — index.js:210
__webpack_require__
promiseReactionJob
```

**Comment by jonboj** [comment]
Ok. The example rely on webgl2
https://github.com/rustwasm/wasm-bindgen/blob/master/examples/webgl/src/lib.rs#L12
Can't find confirmation that Safari supports webgl2 https://caniuse.com/webgl2. Haven't acces to MacOS environment. Maybe worth a check e.g. https://webglreport.com/?v=2

**Comment by dan-fritchman** [comment]
Actually I see that WebGL 2 is an "Experimental Feature", disabled by default, in current Safari.  
After enabling it that page works as expected.  

Closing.
