### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by rahulverma** [rustwasm/wasm-bindgen#2663]
### Summary

Looking at the contributor stats it looks like development has slowed down. Should I still depend on this repository for my project?

### Additional Details

I was caught off guard by a [severe memory leak issue](https://github.com/rustwasm/wasm-bindgen/issues/1963) raised more than a year back. This issue forced me to refactor out any and all `Result type` responses from my code. I don't see it getting fixed anytime soon. Should I be worried?

**Comment by alexcrichton** [comment]
Development of this project has slowed, and I am the only maintainer. I still try to merge small features and bug fixes, and you can look at the commit history and decide whether that's active enough for you. Fundamental issues like the one you pointed out I don't have time to work.
