### ISSUE TITLE
Unmark ClipboardEvent as "experimental"

### ISSUE THREAD

**Issue by jkelleyrtp** [rustwasm/wasm-bindgen#2668]
Configuring web_sys to allow experimental technologies is a hassle for library implementors. I want to implement a wrapper around ClipboardEvent, but it's experimental in websys.

However, it's widely implemented, and has been for many many versions of safari, chrome, ff, opera, etc.

https://developer.mozilla.org/en-US/docs/Web/API/ClipboardEvent

Can we manually mark this as stable?

**Comment by jonboj** [comment]
Just to confirm this have been tried. To enable unstable features is simple https://rustwasm.github.io/docs/wasm-bindgen/web-sys/unstable-apis.html?highlight=web_sys_unstable_apis
With `config.toml` in `[build]` section just add a line with the flag `rustflags=["--cfg=web_sys_unstable_apis"]`, no further hassle so far.

**Comment by torokati44** [comment]
I think https://github.com/rustwasm/wasm-bindgen/pull/3791 fixed this.

**Comment by daxpedda** [comment]
Thank you for the notice!
