### ISSUE TITLE
generate custom js test code

### ISSUE THREAD

**Issue by reenigneEsrever92** [rustwasm/wasm-bindgen#2676]
### Summary

I would like to develop a vs code plugin using rust. Therefore I'm currently in the process of implementing a lib with bindings to corresponding vs-code API types and functions. Now, I would like to test APIs against a vs code instance. Therefore I would like to load vs-code and types in the javascript that executes before my wasm tests are run. 

So my question is: Is there a way to customize test execution javascript?

**Comment by alexcrichton** [comment]
At this time I don't think that this is supported, no.
