### ISSUE TITLE
Using web_sys_unstable_apis and publishing to crates.io

### ISSUE THREAD

**Issue by ivanceras** [rustwasm/wasm-bindgen#2684]
### Summary
I have a crate which uses the navigator clipboard, however I have a hard time figuring out how should I be able to publish it to `crates.io`.

This is the function behind the `web_sys_unstable_apis` flag.
```rust
    #[cfg(web_sys_unstable_apis)]
    fn copy_to_clipboard(&self) -> bool {
        if let Some(selected_text) = self.text_buffer.selected_text() {
            let navigator = sauron::window().navigator();
            if let Some(clipboard) = navigator.clipboard() {
                let _ = clipboard.write_text(&selected_text);
                return true;
            } else {
                log::warn!("no navigator clipboard");
            }
        }
        false
    }
```
Building the crate locally using the following command works fine.
```sh
RUSTFLAGS=--cfg=web_sys_unstable_apis wasm-pack build --target web
```
However, when I try to publish it to `crates.io`, it will complain that the `copy_to_clipboard` function could not be found, due to the fact that the RUSTFLAG is not included when publishing a crate.

### Additional Details
I tried putting this on Cargo.toml
```toml
[package]
name = "mypackage"
version = "0.1.0"

[build] 
rustflags = ["--cfg=web_sys_unstable_apis"]
```
However, the error still persist.
So my question is: How do I configrure `Cargo.toml` to have the RUSTFLAGS value, so I can publish the cate?

**Comment by jonboj** [comment]
Maybe put the `[build]` section with the flag in `config.toml` instead of `Cargo.toml` https://doc.rust-lang.org/cargo/reference/config.html

**Comment by ivanceras** [comment]
Thank you for the reply @jonboj , It made me realize that `config.toml` is on your local configuration, if that would work then so thus `RUSTFLAGS=--cfg=web_sys_unstable_apis cargo publish` would work, and so it does. I'm quite surprise to see this works.

**Comment by trevyn** [comment]
@ivanceras For reference, you can pass `--no-verify` to `cargo publish` to have it skip the local build entirely. The crates.io server still checks some small things, but I'm pretty sure it doesn't do a build.
