### ISSUE TITLE
std::thread::sleep() panics

### ISSUE THREAD

**Issue by cedricbeust-okta** [rustwasm/wasm-bindgen#2699]
### Describe the Bug

Calling `std::thread::sleep()` results in a panic on the WASM side. This is what I see:

    (func $std::sys::wasm::thread::Thread::sleep::h529dcc4c2a8655f1 (;1628;)
      i32.const 1136380
      i32.const 11
      i32.const 1136440
      call $std::panicking::begin_panic::h7aa9ee66be69fd88

### Steps to Reproduce

            let duration = Duration::from_millis(1000);
            std::thread::sleep(duration);

### Expected Behavior

The code should sleep for the given `Duration`.

### Actual Behavior

The code panics.

**Comment by cedricbeust-okta** [comment]
This code is running a separate thread in Rust, though, does this mean it's still running in the main thread in JS?

**Comment by chinedufn** [comment]
Most likely unless you've gone through some of the current stuff that's needed to set up threading in wasm.

I'm not too familiar with web workers so you can try researching whether or not you can block in them..

Maybe add a `std::thread::sleep` here to see whether or not it panics:

https://github.com/rustwasm/wasm-bindgen/blob/master/examples/raytrace-parallel/src/lib.rs#L79
