### ISSUE TITLE
Loading Multiple WASM bundles in the same Page

### ISSUE THREAD

**Issue by fosskers** [rustwasm/wasm-bindgen#2700]
### Summary

Lately I've been developing a browser extension entirely in Rust/WASM. Today for the first time I attempted to load multiple [Content Scripts](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts) into the same page. Normally this is not a problem, so long as the the following is kept in mind:

> There is only one global scope per frame, per extension. This means that variables from one content script can directly be accessed by another content script, regardless of how the content script was loaded.

When I noticed that the second script failed to load, I wondered why. Then I found my browser complaining to me that:

> Uncaught SyntaxError: Identifier 'wasm_bindgen' has already been declared

Citing:

```js
let wasm_bindgen;
```
that appears in the JS output of `wasm-pack`. Since I'm using two WASM bundles, and thus two JS shims, these symbols are thus clashing in the same namespace.

**Question:** Is there a way to obfuscate that symbol name at compile-time in order to avoid the symbol clash? Or are there deeper concerns within the `wasm-bindgen` world that require that symbol to be named exactly `wasm_bindgen`? Or perhaps am I overlooking something obvious in how I should be loading these bundles? Otherwise, it doesn't seem possible to load more than one WASM bundle per page, which doesn't sound right.

Please and thank you.

### Additional Details

Note that I am compiling with `--no-modules` for technical reasons. I am also loading the WASM manually in my own shim script like:
```js
// Fire up the WASM portion of the Seed app.
const { start } = wasm_bindgen;
wasm_bindgen(wasm_url).then(start);
```
because inlined JS (i.e. `<script>` tags) is not allowed in HTML of browser extensions. Presumably I'd have to use the obfuscated name here too.

**Comment by fosskers** [comment]
Thank you, I suspect that flag will do the trick. I will be testing that tomorrow.

**Comment by fosskers** [comment]
Debugging out loud:
```
[cargo-make] INFO - Execute Command: "wasm-pack" "build" "--target" "no-modules" "--no-modules-global" "wasm_bindgen_gmail" "--out-name" "integ-gmail" "--dev"
error: Found argument '--no-modules-global' which wasn't expected, or isn't valid in this context

USAGE:
    wasm-pack build --target <target>

For more information try --help
```

**Comment by alexcrichton** [comment]
The `--no-modules-global` flag is for `wasm-bindgen`, not `wasm-pack`, so that's the issue there I think.
