### ISSUE TITLE
How to use per-project `wasm-bindgen-cli` version?

### ISSUE THREAD

**Issue by demurgos** [rustwasm/wasm-bindgen#2702]
### Summary

I have two projects on my computer depending on WasmBindgen, but requiring different versions. How can I specify and pin the right `wasm-bindgen-cli` version on a per-project basis so it always matches the corresponding `wasm-bindgen` lib version?

### Additional Details

My first `Cargo.toml` contains:
```
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "=0.2.67"
```

My second `Cargo.toml` was freshly updated and contains:
```
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "=0.2.78"
```

On my system I have a single global `wasm-bindgen` installation:
```
$ wasm-bindgen --version
wasm-bindgen 0.2.67
```

I can't compile the recently updated project:
```
thread 'main' panicked at 'remaining data [19]', /home/demurgos/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-cli-support-0.2.67/src/descriptor.rs:109:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

So I updated my globally installed `wasm-bindgen` CLI [as documented](https://rustwasm.github.io/docs/wasm-bindgen/reference/cli.html?highlight=cargo,install#installation):
```
cargo install -f wasm-bindgen-cli
```

But now I can't build my older project:
```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/demurgos/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-cli-support-0.2.78/src/descriptor.rs:205:15
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I believe that those are some relevant Cargo issues, but I feel that there is no good solution at the moment. How do you handle this problem for your own projects?

- [Proposal: allow crates to depend on a binary crate #4316](https://github.com/rust-lang/cargo/issues/4316)
- [If you depend on a binary then commands are inconsistent #8708](https://github.com/rust-lang/cargo/issues/8708)
- [Support for bin build-dependency #8873](https://github.com/rust-lang/cargo/issues/8873)
- [Tracking Issue for RFC 3028: Allow "artifact dependencies" on bin, cdylib, and staticlib crates #9096](https://github.com/rust-lang/cargo/issues/9096)

**Comment by chloekek** [comment]
You can depend on [wasm-bindgen-cli-support](https://lib.rs/crates/wasm-bindgen-cli-support) and then write your own binary, like this:

```rust
use wasm_bindgen_cli_support::Bindgen;

fn main()
{
    Bindgen::new()
        .input_path("my-wasm-file.wasm")
        .generate("my-out-dir")
        .unwrap();
}
```
