### ISSUE TITLE
Add support for `signal` field to `AddEventListenerOptions`

### ISSUE THREAD

**Issue by themaxdavitt** [rustwasm/wasm-bindgen#2707]
### Motivation

The `options` argument to [`EventTarget.addEventListener()`](https://dom.spec.whatwg.org/#ref-for-dom-eventtarget-addeventlistener%E2%91%A2) can take an `AbortSignal` through it's `signal` key, but our [`AddEventListenerOptions`](https://docs.rs/web-sys/0.3/web_sys/struct.AddEventListenerOptions.html) type doesn't support this.

### Proposed Solution

I believe all we need to do is copy [one of the existing field manipulation functions](https://github.com/rustwasm/wasm-bindgen/blob/e4477293c15df8500330b295cb9624dccb2a063b/crates/web-sys/src/features/gen_AddEventListenerOptions.rs#L22-L38) and change it's parameter type (to [`AbortSignal`](https://docs.rs/web-sys/0.3/web_sys/struct.AbortSignal.html)) and field name (to `signal`).

### Alternatives

The alternative is to do the same sort of manual field-setting code that's already handled for us in the function I linked above. This makes using functions like [`EventTarget::add_event_listener_with_callback_and_add_event_listener_options`](https://docs.rs/web-sys/0.3/web_sys/struct.EventTarget.html#method.add_event_listener_with_callback_and_add_event_listener_options) annoying for instance.

**Comment by bicarlsen** [comment]
This seems to be [in the documentation](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.AddEventListenerOptions.html#method.set_signal) but is not available when I try to use it.

I've ensured the required features are enabled.

**Comment by daxpedda** [comment]
This was fixed in https://github.com/rustwasm/wasm-bindgen/pull/4026.

> This seems to be [in the documentation](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.AddEventListenerOptions.html#method.set_signal) but is not available when I try to use it.
> 
> I've ensured the required features are enabled.

You might need to update to the newest version, #4026 was added in v0.3.70.
Let me know if you still encounter problems.
