### ISSUE TITLE
Missing SubmitEvent

### ISSUE THREAD

**Issue by erihsu** [rustwasm/wasm-bindgen#2712]

**Comment by finnbear** [comment]
@erihsu `SubmitEvent` *is* missing. Why close the issue?

**Comment by erihsu** [comment]
hi, finnbear
I close this issue because I found the bindgen exclude all event from raw web api. But  submit event can be found in web_sys crate

**Comment by Dom-1** [comment]
@erihsu Where may `SubmitEvent` be found?

**Comment by finnbear** [comment]
> @erihsu Where may `SubmitEvent` be found?

It's a browser API https://developer.mozilla.org/en-US/docs/Web/API/SubmitEvent

**Comment by Dom-1** [comment]
@finnbear That is what I was wondering as well.
https://github.com/yewstack/yew/issues/2691
I'd be happy to submit a PR to add SubmitEvent to the web_sys crate, but I would like to know if there is a reason it wasn't included to begin with.

**Comment by finnbear** [comment]
> but I would like to know if there is a reason it wasn't included to begin with.

I personally have no clue, other than it having the same fields as normal `Event`, which seemingly reduces motivation to add it. Since the required workaround is `unsafe` cast, at least to process events in a strongly typed way, I think there is motivation to add it. Maybe ask websys people.

**Comment by Dom-1** [comment]
I'll submit a PR to generate discussion on the subject ;)

Thanks for the timely responses! I'll link the PR once I get it up.
