### ISSUE TITLE
U64 does not work in Safari

### ISSUE THREAD

**Issue by Firaenix** [rustwasm/wasm-bindgen#2716]
### Describe the Bug

Safari 14 does not support BigUint64Array as mentioned in https://github.com/rustwasm/wasm-bindgen/pull/2441#issuecomment-806737455

### Steps to Reproduce
Run any wasm code/test that exposes u64 in safari.

https://github.com/Firaenix/wasm-bindgen-BigUint64Array-repro

### Expected Behavior
Should run in Safari (iOS and macOS) as in any other environment.

### Actual Behavior

Console error that causes the code not to run.

**Comment by memoryruins** [comment]
Safari 15, released in September, [added support](https://developer.apple.com/documentation/safari-release-notes/safari-15-release-notes) for `BigInt64Array` and `BigUint64Array` on macOS and iOS. It might take a few more months before a majority of users have upgraded.

**Comment by Firaenix** [comment]
I don't think that's a satisfying solution, especially when the documentation claims that it should work on Safari.
If we are already providing what is essentially a polyfill for u64, it shouldnt just be good enough to say that we should just wait for users to upgrade.

I'm working on a PR that should hopefully solve this issue for all BigInt supporting browsers

**Comment by memoryruins** [comment]
To be clear, I wasn't offering a solution previously, only describing the current state of Safari support. An improved polyfill that handles Safari 14 would be great.

**Comment by Firaenix** [comment]
All good, I misinterpreted in that case

**Comment by Firaenix** [comment]
I have a branch on my fork which works in Safari and all other browsers that support BigInt:
https://github.com/bsvwasm/wasm-bindgen/tree/universal-ui64-patch

**Comment by Firaenix** [comment]
https://github.com/rustwasm/wasm-bindgen/pull/2727

**Comment by dovahcrow** [comment]
does #3037 fixed this issue?

**Comment by Liamolucko** [comment]
> does #3037 fixed this issue?

Yes.

**Comment by senolem** [comment]
Hello, https://github.com/rustwasm/wasm-bindgen/commit/bf109de9b2a46de0d8e7ffea198823e5a6744a1b was supposed to fix this issue, but release 0.2.83 still fails upon using BigInt64Array on Safari iOS 14.8. This has been tested through Ruffle and the issue started when they updated to 0.2.83 (https://github.com/ruffle-rs/ruffle/commit/1954f6162f6b53546f216efc0de3d029ea54cc5e). Any ideas?

**Comment by Liamolucko** [comment]
#3037 fixed the problem for passing `i64`s and `u64`s directly, but it turns out that returning `Option<i64>` or `Option<u64>` still ends up using `BigInt64Array` for other reasons.

Right now (since #2886), that `BigInt64Array` gets initialised immediately, which means that trying to run something that might use it in Safari 14 will fail instantly. I've opened #3253 to change it back to only being initialised on first use, so that things can still work in Safari 14 as long as they never *reach* the code that uses the `BigInt64Array`. I think that should be enough to get Ruffle working.

**Comment by senolem** [comment]
Thanks for your detailed answer :) Unfortunately I cannot test right now because I have no idea how to compile Ruffle from source, even less how to use a specific branch rather than the release they're using. I'll update you ASAP (so whenever the PR is commited and they update their dependencies)
