### ISSUE TITLE
Question about Apple silicon / M1 support

### ISSUE THREAD

**Issue by haywoood** [rustwasm/wasm-bindgen#2723]
### Summary

When I run `trunk serve` (I know this isn't [trunk](https://github.com/thedodd/trunk)), I'm getting this error

```
Nov 16 20:32:54.057  INFO fetching cargo artifacts
Nov 16 20:32:54.123  INFO processing WASM
Nov 16 20:32:54.129  INFO calling wasm-bindgen
Nov 16 20:32:54.129 ERROR ❌ error
error from HTML pipeline

Caused by:
    0: error from asset pipeline
    1: error spawning wasm-bindgen call
    2: Bad CPU type in executable (os error 86)
Nov 16 20:32:54.131  INFO 📡 serving static assets at -> /
Nov 16 20:32:54.131  INFO 📡 server listening at 0.0.0.0:8080
```

It fails [at this point](https://github.com/thedodd/trunk/blob/master/src/pipelines/rust_app.rs#L238) where it's calling out to `wasm-bindgen`.

I was told to compile trunk myself using the `aarch64-apple-darwin` target, which I did but it didn't help. Do I need to do the same thing with wasm-bindgen?

I didn't want to file a new bug as I'm just kind of lost and was hoping someone could steer me in a better direction. But Is this already a known problem? I searched high and low for references to `Apple silicon` and `M1` to no avail.

### Additional Details

The output of `rustup show`
```
Default host: aarch64-apple-darwin
rustup home:  /Users/haywood/.rustup

installed toolchains
--------------------

stable-aarch64-apple-darwin
nightly-aarch64-apple-darwin (default)

installed targets for active toolchain
--------------------------------------

aarch64-apple-darwin
wasm32-unknown-unknown

active toolchain
----------------

nightly-aarch64-apple-darwin (overridden by '/Users/haywood/dev/rust/fixie/examples/simple/rust-toolchain')
rustc 1.58.0-nightly (891ca5f63 2021-11-15)
```

**Comment by haywoood** [comment]
Wow, I was randomly reading the instructions for this https://github.com/parasyte/pixels/tree/0.8.0/examples/minimal-web#hello-pixels--web and saw `cargo install --locked wasm-bindgen-cli` and wondered, "Hmm, do I need that?" and oh my god it worked after I installed it!!

```
Nov 16 20:58:47.832  INFO fetching cargo artifacts
Nov 16 20:58:47.954  INFO processing WASM
Nov 16 20:58:47.971  INFO using system installed binary app="wasm-bindgen" version="0.2.78"
Nov 16 20:58:47.972  INFO calling wasm-bindgen
Nov 16 20:58:48.072  INFO copying generated wasm-bindgen artifacts
Nov 16 20:58:48.080  INFO applying new distribution
Nov 16 20:58:48.119  INFO ✅ success
```

**Comment by monomadic** [comment]
Running `cargo install --locked wasm-bindgen-cli` does not fix the issue. How is this still a thing?
