### ISSUE TITLE
`#[warn(dead_code)]` warning

### ISSUE THREAD

**Issue by matthew-dean** [rustwasm/wasm-bindgen#2726]
### Summary

When I mark a module's function with `#[wasm_bindgen]`, I get a `dead_code` warning.

### Additional Details

I have `lib.rs` and `parser.rs` (as a module). Parser has a function like:
```
#[wasm_bindgen]
pub fn parse() {

}
```
Essentially, I want to export the function `parse()` to the JS interface. But I get a `dead_code` warning with this approach. I tried re-exporting the function in `lib.rs` like:
```
mod parser;

#[wasm_bindgen]
pub use parser::parse;
```
But this resulted in the error: `#[wasm_bindgen] can only be applied to a function, struct, enum, impl, or extern block`

What's the best way to go about this? Sorry, I'm a Rust noob, so I apologize if I'm missing something fundamental, but I couldn't find any examples in the `wasm-bindgen`'s docs for this. Most Rust example code seems to assume you put all your code in one file. 🤷

**Comment by edward-shen** [comment]
Not sure if you're still running into issues with this, but have you tried `pub mod parser`? Something like this should work:
```rust
// in parser.rs
#[wasm_bindgen]
pub fn parse() { }
```
```rust
// in lib.rs
pub mod parser;
```
Or, alternatively, just exporting the function and nothing else:
```rust
// in lib.rs
pub use parser::parse;
```

**Comment by alexcrichton** [comment]
I'd have to dig in further to figure out why this is happening, but yeah for now I'd recommend using `pub mod parser` to solve this.

**Comment by matthew-dean** [comment]
Okay, thanks, I'll try it!

**Comment by webmaster128** [comment]
I can reproduce this. It happens for all functions that are `pub` but are not exported at top level (such as lib.rs). I think this is pretty normal since they end up as some FFI export instead of a regular Rust export.

I'll now go for this since I don't want to export the wasm_bindgen exports at top level. Would be cool if this was the default.

```diff
 #[wasm_bindgen]
+#[allow(dead_code)] // exported via wasm_bindgen
 pub fn verify_beacon(
     pk_hex: &str,
     round: u32,
     previous_signature_hex: &str,
     signature_hex: &str,
 ) -> Result<bool, JsValue> {
```

**Comment by webmaster128** [comment]
Thank you for the fix! Makes perfect sense.
