### ISSUE TITLE
Include corresponding values in d.ts for C-style enums

### ISSUE THREAD

**Issue by remagpie** [rustwasm/wasm-bindgen#2730]
### Motivation

`wasm_bindgen` macro supports [C-style enums](https://github.com/rustwasm/wasm-bindgen/pull/36). It supports specifying literal values for each enum variant, but it seems that those values are not included in the generated d.ts file. For example,
```rust

#[wasm_bindgen]
pub enum ErrorCode {
    FooError = 0,
    BarError = 2,
}
```
is converted to the following code:
```typescript
export enum ErrorCode {
  FooError,
  BarError,
}
```

Specifying the actual values of enum lets us use more features in typescript, so it would be nice if the corresponding literal values are included in d.ts.

### Proposed Solution

The ideal solution would give us the following typescript code:
```typescript
export enum ErrorCode {
  FooError = 0,
  BarError = 2,
}
```

**Comment by Dollab** [comment]
👍  This is really important as otherwise it can lead to subtle bugs when using the literal value of the enum.
