### ISSUE TITLE
No `JsError` in the root

### ISSUE THREAD

**Issue by solidiquis** [rustwasm/wasm-bindgen#2740]
### Describe the Bug

```
error[E0432]: unresolved import `wasm_bindgen::JsError`
 --> src/lib.rs:2:37
  |
2 | use wasm_bindgen::{JsValue, JsCast, JsError};
  |                                     ^^^^^^^ no `JsError` in the root

```

I'm on the latest version of `wasm_bindgen`... here's my Cargo.toml

```
[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.78"

[dependencies.web-sys]
version = "0.3.55"
features = [
  "console",
  "Document",
  "HtmlCanvasElement",
  "WebGlProgram",
  "WebGlRenderingContext",
  "WebGlShader",
  "Window",
  "XrSession",
  "XrWebGlLayer"
]
```

### Expected Behavior

JsError should be brought into scope.

### Actual Behavior

Keep getting `No JsError in the root` errors when running `cargo check`.

**Comment by jonboj** [comment]
Looking at [JsError](https://rustwasm.github.io/wasm-bindgen/api/wasm_bindgen/struct.JsError.html)
Maybe the full prelude should be used `use wasm_bindgen::prelude::*;`

**Comment by alexcrichton** [comment]
I believe that this is because the most recent changes haven't been published to crates.io yet, so the documentation is a bit ahead of the crates.io release.
