### ISSUE TITLE
Wasm In Wasm example does not work with custom wasm

### ISSUE THREAD

**Issue by eribol** [rustwasm/wasm-bindgen#2742]
I am tring to use wasm in wasm example for my use case but with or without bundle, console.log always says; 
`panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: import object field './home_bg.js' is not an Object`
Is there anything i am missing here?

### Summary

A clear and concise summary of your question.

### Additional Details

Provide any additional details here.

**Comment by alexcrichton** [comment]
This really depends on the wasm that you're loading, and the error message is that you didn't provide an import. The wasm-in-wasm thing is mostly a toy and I wouldn't recommend trying to copy it exactly since it doesn't easily lend itself to handling the import object.

**Comment by eribol** [comment]
I send the error. 

> panicked at 'called Result::unwrap()on anErr value: JsValue(TypeError: import object field './home_bg.js' is not an Object
It cant load the object that wasm file itself tring to load file(like .js files or without bundle "wdm"). I can search for a solution but i do not know which doc i should look.
