### ISSUE TITLE
web_sys::PointerEvent cannot be cast to web_sys::TouchEvent

### ISSUE THREAD

**Issue by jvandervorm** [rustwasm/wasm-bindgen#2743]
According to MDN it seems the proper way to use MouseEvent and TouchEvent (and pen, etc. support) at once is using the PointerEvent.

However in web_sys, there does not seem a documented way to actually do this. PointerEvent in web_sys has the same API as MouseEvent, so it works for mouse events. However touches can have a web_sys::TouchList (multiple touches) attached and the PointerEvent has no `touches()` or `target_touches()` method to return the list. 

I tried casting the event to a TouchEvent when appropriate but that failed too. 

``` 
// event is a PointerEvent here (add_event_listener("pointerdown"))
if event.pointer_type() == "touch" {
    let event = event.dyn_ref::<TouchEvent>().unwrap();
    console_log!("Nr of touches {}", event.target_touches().length());
}
```

leads to an error suggesting casting to TouchEvent is not possible. 

```
panicked at 'called `Result::unwrap()` on an `Err` value: PointerEvent { obj: MouseEvent { obj: UiEvent { obj: Event { obj: Object { obj: JsValue(PointerEvent) } } } } }'
```

Is this missing? Am I missing something?

**Comment by jonboj** [comment]
According to [TouchEvent](https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent) inherits direct from `UIEvent`. While [PointerEvent](https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent) inherits from `MouseEvent`. Looks like this also is reflected in `web-sys`. In example [TouchEvent example](https://developer.mozilla.org/en-US/docs/Web/API/Touch_events#example) specific `TouchEvent` subscriptions are setup.

**Comment by alexcrichton** [comment]
Sorry I don't know enough about web APIs myself to provide guidance on this. I believe you can do an unchecked cast though if dynamic casts don't work.

**Comment by jvandervorm** [comment]
> According to [TouchEvent](https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent) inherits direct from `UIEvent`. While [PointerEvent](https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent) inherits from `MouseEvent`. Looks like this also is reflected in `web-sys`. In example [TouchEvent example](https://developer.mozilla.org/en-US/docs/Web/API/Touch_events#example) specific `TouchEvent` subscriptions are setup.

Yes, MouseEvent and TouchEvent are implemented properly in wb_sys. But they are also ' the old api'.  In the old days everybody ' rethrowed' TouchEvent as MouseEvent to make a semi-uniform interface. Now there is also PenSupport (and much more) so that gets tedious real quick. Also the original TouchEvent had to be prevented, before rethrowing it as a MouseEvent, which leads to side-effects. So now the unifying api is the PointerEvent, which should handle all. (https://www.w3.org/TR/pointerevents3/).

So the PointerEvent should be usable as both a MouseEvent and an TouchEvent, which works fine in the dynamic javascript-world.  However in web_sys we only have the PointerEvent as MouseEvent, which makes an entire slew of methods (like `touches()` but also other advanced inputs like tilts and azimuths unavailable.

**Comment by jvandervorm** [comment]
Reading up on the issue, it seems that in case of the PointerEvent also in the javascript world you have to keep track of multi-touches yourself by caching them and the PointerEvent cannot be treated as a TouchEvent. Sorry for the wrong information. Bug may be closed.
