### ISSUE TITLE
How to enable extern function provided by users of the package?

### ISSUE THREAD

**Issue by mpizenberg** [rustwasm/wasm-bindgen#2745]
### Motivation

I have a use case where I want my extern JS function to be provided by a user of the package, not by myself.

### Proposed Solution

This means that I somehow need the generated package to have a function injected when loading the package. This is possible when compiling to `--target nodejs` and modifying the generated JS as follows:

```js
module.exports = function({providedByUser}) {
    let module = { exports: {} };
    
    // Original content generated by wasm-pack build --target nodejs
    ...
    
    return module.exports;
}
```

Corresponding to the following extern declaration in the rust file.

```rust
#[wasm-bindgen]
extern "C" {
    fn providedByUser();
}
```

And loaded by a user as follows in their JS file.

```js
function providedByUser(){...}
let wasm = require("wasm-package")({providedByUser});
...
```

### Alternatives?

I haven't found any other way with the current wasm-bindgen options to do this kind of user-provided extern functions. All that I've found possible to do implies that the person compiling the wasm package also provides the associated JS that is needed by the extern functions.

Am I missing something? Could we add some configuration to say that an extern block is provided by the package user? Maybe something like this:

```rust
#[wasm-bindgen(package-import)]
extern "C" { ... }
```

**Comment by alexcrichton** [comment]
There are various ways to import JS functionality, I'd recommend reading over the reference -- https://rustwasm.github.io/wasm-bindgen/ -- and I think it should cover your use case.
