### ISSUE TITLE
I can't compile examples

### ISSUE THREAD

**Issue by adl-izzadin** [rustwasm/wasm-bindgen#2756]
I have clone wasm-bindgen package and try compile example "DOM" but cant because have error:

/wasm-bindgen/examples/dom# RUST_BACKTRACE=1 wasm-pack build --target web
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
    Finished release [optimized] target(s) in 0.17s
[INFO]: Installing wasm-bindgen...
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', crates/cli-support/src/descriptor.rs:205:15
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: wasm_bindgen_cli_support::descriptor::Descriptor::_decode
   4: wasm_bindgen_cli_support::descriptor::Descriptor::_decode
   5: wasm_bindgen_cli_support::descriptor::Descriptor::_decode
   6: wasm_bindgen_cli_support::descriptor::Function::decode
   7: wasm_bindgen_cli_support::descriptor::Descriptor::_decode
   8: wasm_bindgen_cli_support::descriptors::execute
   9: wasm_bindgen_cli_support::Bindgen::generate_output
  10: wasm_bindgen_cli_support::Bindgen::generate
  11: wasm_bindgen::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Error: Running the wasm-bindgen CLI
Caused by: failed to execute `wasm-bindgen`: exited with exit status: 101

/wasm-bindgen/examples/dom# RUST_BACKTRACE=full wasm-pack build --target web
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
    Finished release [optimized] target(s) in 0.13s
[INFO]: Installing wasm-bindgen...
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', crates/cli-support/src/descriptor.rs:205:15
stack backtrace:
   0:           0x6ebef0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf42958820747a8ac
   1:           0x7221bc - core::fmt::write::h6f5ededa5074697e
   2:           0x6e97d5 - std::io::Write::write_fmt::hdb84dc6c28fda870
   3:           0x6ede6b - std::panicking::default_hook::{{closure}}::hb85a09d7e9a16432
   4:           0x6ed941 - std::panicking::default_hook::hdc924e74cb190bbb
   5:           0x6ee534 - std::panicking::rust_panic_with_hook::hd63b080e78590a80
   6:           0x6ee017 - std::panicking::begin_panic_handler::{{closure}}::h27bfba1f7e931f90
   7:           0x6ec38c - std::sys_common::backtrace::__rust_end_short_backtrace::h2cc025f6c95b1f82
   8:           0x6edf79 - rust_begin_unwind
   9:           0x4291a1 - core::panicking::panic_fmt::h9f5a85773697c5f5
  10:           0x429162 - core::panicking::panic_bounds_check::h70dd3fd6056304a0
  11:           0x45f9ea - wasm_bindgen_cli_support::descriptor::Descriptor::_decode::h9adc04c55179ba18
  12:           0x45f9bc - wasm_bindgen_cli_support::descriptor::Descriptor::_decode::h9adc04c55179ba18
  13:           0x45f9bc - wasm_bindgen_cli_support::descriptor::Descriptor::_decode::h9adc04c55179ba18
  14:           0x45fcce - wasm_bindgen_cli_support::descriptor::Function::decode::h81540754b760c003
  15:           0x45f58e - wasm_bindgen_cli_support::descriptor::Descriptor::_decode::h9adc04c55179ba18
  16:           0x48d079 - wasm_bindgen_cli_support::descriptors::execute::hf8840b1ee2325cbc
  17:           0x443c6d - wasm_bindgen_cli_support::Bindgen::generate_output::h9b68d0f02d04575e
  18:           0x42a72e - wasm_bindgen_cli_support::Bindgen::generate::h0bb72b73165f8801
  19:           0x42dda0 - wasm_bindgen::main::h68109d2e2053b319
  20:           0x42beb3 - std::sys_common::backtrace::__rust_begin_short_backtrace::he92ef7ccf1d60268
  21:           0x42bec9 - std::rt::lang_start::{{closure}}::h1aac00108137e691
  22:           0x6eea90 - std::rt::lang_start_internal::hfee0032b3594c35b
  23:           0x42e1a2 - main
Error: Running the wasm-bindgen CLI
Caused by: failed to execute `wasm-bindgen`: exited with exit status: 101

Rust 1.57.0
Wasm-Pack 0.10.2

**What am I doing wrong?**

**Comment by alexcrichton** [comment]
This is because the examples in this repository need to be copied externally to be built, they won't build in-tree due to weirdness of which version of wasm-bindgen-the-cli is used.
