### ISSUE TITLE
multiple `spawn_local` call in single microtask. is it intended?

### ISSUE THREAD

**Issue by namse** [rustwasm/wasm-bindgen#2761]
Since the documentation said "The `future` will always be run on the next microtask tick", I thought that multiple `spawn_local` would run on each different ticks. So I used spawn_local a lot.

But there are frame drops. When I did some profiling, the spawn_locals I called multiple times were all running in one tick, interfering with the animation frame.

Is this intentional? Do I have to use a trick to use something like setTimeout outside of spawn_local to not affect the animation frame?

**Comment by alexcrichton** [comment]
Scheduling is done on the microtask tick with `promise.then(...)` to schedule the next callback. If that interferes with animation frames then you'll want to use `setTimeout` or similar, yeah.
