### ISSUE TITLE
Is it common that wasm performance is 8 times slower than native?

### ISSUE THREAD

**Issue by wormtql** [rustwasm/wasm-bindgen#2763]
### Summary

I have a heavy computation application that is initially written in JS, since wasm is fast as I heard of, I rewrite the functionality using Rust, but as my tests, the same code needs 30s when compiled natively, while needs 240s when running in the browser as wasm. I believe even JS code is no 8 times slower than native.
I compiled Rust with `opt-level = 3` and `lto = true`.

**Comment by alexcrichton** [comment]
Sorry sometimes it's better and sometimes it isn't, your use case wasm may not be faster.
