### ISSUE TITLE
Allow `Option<&Closure<T>>` to be passed to JS

### ISSUE THREAD

**Issue by sinking-point** [rustwasm/wasm-bindgen#2767]
### Motivation

Sometimes a JS function accepts an optional callback. In such cases it would be good to be able to import the function from JS with `Option<&Closure<T>>` as the argument type, so that if `None` is passed then the JS function would receive `undefined`.

E.g.

```rust
            #[wasm_bindgen(js_namespace = ["chrome", "storage", "sync"], js_name = set)]
            fn _set(data: JsValue, callback: Option<&Closure<dyn FnMut()>>);
```

### Proposed Solution

Implement `OptionIntoWasmAbi` for `&Closure<T>`. 

### Alternatives

There aren't really any viable alternatives that I can think of, but a workaround would be to import the function twice, e.g.

```rust
            #[wasm_bindgen(js_namespace = ["chrome", "storage", "sync"], js_name = set)]
            fn _set(data: JsValue);

            #[wasm_bindgen(js_namespace = ["chrome", "storage", "sync"], js_name = set)]
            fn _set_and_then(data: JsValue, callback: &Closure<dyn FnMut()>);
```

This only works if the callback is the final argument.

**Comment by cataggar** [comment]
It looks like #2768 resolved this.
