### ISSUE TITLE
Set a custom panic_hook to log to console.error in the test suite

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-bindgen#279]
Essentially what https://github.com/rustwasm/console_error_panic_hook is doing, but I don't know whether we want to use that directly (dependencies could get funky, since it depends on wasm-bindgen) or just do the same technique.

Other thing to think about is how to make this ergonomic, so that we don't have to keep repeating boilerplate in every test.

**Comment by fitzgen** [comment]
@myfreeweb because that has non-zero code size overhead implications. Something like ~40K to include all of the `std::fmt` and `std::panicking` infrastructure last time I checked.

**Comment by fitzgen** [comment]
And we have an opt-in solution right now with the `console_error_panic_hook` crate.

**Comment by alexcrichton** [comment]
This is being done in https://github.com/rustwasm/wasm-bindgen/pull/524

**Comment by alexcrichton** [comment]
Done now with the `wasm_bindgen_test` crate!
