### ISSUE TITLE
"__wbg_random_7b8246250fd79f60" error: function import requires a callable

### ISSUE THREAD

**Issue by rmrfxyz** [rustwasm/wasm-bindgen#2809]
### Describe the Bug

Using `js_sys::Math::random` results in this run-time error. 

### Steps to Reproduce

Starting with https://github.com/rustwasm/wasm_game_of_life or other Rust code that uses `js_sys::Math::random`, do `wasm-pack build --target web` - all good here.

Link `pkg` and run the client with npm or yarn.

Check the console and there's the following error:
```
react_devtools_backend.js:4061 Error importing `app.tsx`: LinkError: WebAssembly.instantiate(): Import #3 module="./index_bg.js" function="__wbg_random_7b8246250fd79f60" error: function import requires a callable
```

### Expected Behavior

Expected access to the wasm method that uses `Math.random()` 

### Actual Behavior

Client crashes with aforementioned error message.

### Additional Context

Tried both stable and nightly toolchains. 

```
extern crate js_sys;
use js_sys::Math;

[..]

fn get_rand_cells(width: u32, height: u32) -> Vec<Cell> {
    return (0..width * height)
        .map(|_i| {
            if Math::random() < 0.5 { // <--- fails
            // if _i > 0 && (_i % 2) > 0 { // <--- OK
                Cell::Alive
            } else {
                Cell::Dead
            }
        })
        .collect();
}
```

**Comment by rmrfxyz** [comment]
pardon my newbness - might have overlooked some basic fact

I had another problem with `import {memory}` and turns out adding `.wasm` to the `xxx_bg` file fixes the import, although Code (sometimes?) highlights it as _not found_.

a.i.
`my_pkg/my_pkg_index_bg` fails
`my_pkg/my_pkg_index_bg.wasm` works

Maybe it's because I've changed the project structure and config files to make wasm-game-of-life work with React. Not sure what exactly is the issue but it doesn't seem to be a bug, after all.

**Comment by kylebarron** [comment]
In case anyone else finds this issue in the future, `error: function import requires a callable` can also be produced by a version mismatch between the JS code and the generated WASM binary, in case those are distributed separately.
