### ISSUE TITLE
typescript_custom_section doesn't accept the result of include_str macro

### ISSUE THREAD

**Issue by ChristianIvicevic** [rustwasm/wasm-bindgen#2828]
### Motivation

Instead of manually writing custom typings without syntax validation or highlighting like this
```rust
#[cfg(target_arch = "wasm32")]
#[wasm_bindgen(typescript_custom_section)]
const GAME_ACTION: &'static str = r#"
export type GameAction =
  | { type: "ToggleRotation"; value: boolean }
  | { type: "ResizeWindow"; width: number; height: number };
"#;
```

### Proposed Solution

I'd prefer to extract the custom typings into a separate TS file and embed it using the following:
```rust
#[cfg(target_arch = "wasm32")]
#[wasm_bindgen(typescript_custom_section)]
const GAME_ACTION: &'static str = include_str!("./custom-typings.ts");
```
But this is currently not supported and causes the following error message: `Expected a string literal to be used with #[wasm_bindgen(typescript_custom_section)].`

**Comment by scallaway** [comment]
I am too running into this problem, with anything that isn't supplied directly to the constant as `r#""#`. 

Would be great to see if https://github.com/rustwasm/wasm-bindgen/pull/3115 can get merged as that seems to fix this problem entirely.
