### ISSUE TITLE
Why are futures generated by wasm_bindgen not `Send`?

### ISSUE THREAD

**Issue by jplatte** [rustwasm/wasm-bindgen#2833]
### Summary

Why are futures generated with wasm-bindgen not `Send`? Is there a way to opt into `Send`ness? Currently, if one wants to use `async-trait` for wasm, one has to do this very ugly thing on trait and impl:

```rust
#[cfg_attr(target_arch = "wasm32", async_trait(?Send))]
#[cfg_attr(not(target_arch = "wasm32"), async_trait)]
```

### Additional Details

This came up before in #2409, but I didn't want to bump an old closed issue.

**Comment by jplatte** [comment]
Is there anything that you can think of that could be done about that? Does `Send` even mean much of anything for browser targets in particular (maybe yes bc. of web workers)?

**Comment by alexcrichton** [comment]
Yes because of web workers it matters, and at this time I don't know of anything that can be done.

**Comment by daxpedda** [comment]
With whats said above, I'm going to go ahead and close this.
