### ISSUE TITLE
Support OPFS with AccessHandle API

### ISSUE THREAD

**Issue by lgrano** [rustwasm/wasm-bindgen#2868]
The new Origin Private File System with the[ AccessHandle Proposal](https://github.com/WICG/file-system-access/blob/main/AccessHandle.md) is getting close to becoming a standard. Safari and Chromium browsers already support it, Firefox is prototyping it but with its developers are now involved in creating the File System standard  its a done deal.

Some work has been done on the old File System Access API this PR #2558 but Firefox will not implement the part of the API that accesses the user file system as they marked it as harmful and Safari is also only supporting the OPFS. The work done still relevant i believe although it needs to be adapted.

IDL SPEC:  [https://fs.spec.whatwg.org/#api-filesystemhandle](https://fs.spec.whatwg.org/#api-filesystemhandle)

Webkit Support Announcement: [https://webkit.org/blog/12257/the-file-system-access-api-with-origin-private-file-system/](https://webkit.org/blog/12257/the-file-system-access-api-with-origin-private-file-system/)

Emscripten is planning to support this on their new [WasmFS](https://github.com/emscripten-core/emscripten/issues/15950) aswell.

**Comment by alensiljak** [comment]
Updated link to [Access Handle](https://github.com/WICG/file-system-access/blob/main/proposals/AccessHandle.md) proposal.
The implementation:

[createSyncAccessHandle](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemFileHandle/createSyncAccessHandle) is available on [FileSystemFileHandle](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemFileHandle) and supported in all the major browsers.

**Comment by daxpedda** [comment]
I'm happy to review a PR.

**Comment by Xuanwo** [comment]
Seems we already have `FileSystemHandle` features:

https://github.com/rustwasm/wasm-bindgen/blob/a5d2539314e0392c87a4d3203e99cf4888050fc0/crates/web-sys/Cargo.toml#L387-L400

Is this issue out of sync?

**Comment by daxpedda** [comment]
Yeah, if somebody does the required research we can also move on to stabilize it.
Thank you for pointing this out!

**Comment by Liamolucko** [comment]
> Seems we already have `FileSystemHandle` features that added in #3427

I should probably mention that #3427 only added the standardised subset of the API (so, not the Chrome-only `window.show*Picker` APIs), whereas #2558 added the whole thing.

Closing this issue is still correct though, since it was only asking for the standardised subset in the first place. If people want the Chrome-only APIs to be added they can open a new issue.
