### ISSUE TITLE
wasm_bindgen attribute shouldn't accept typescript_type without using it

### ISSUE THREAD

**Issue by TedDriggs** [rustwasm/wasm-bindgen#2874]
### Describe the Bug

The `#[wasm_bindgen]` attribute accepts (some?) fields without error, but doesn't use them.

### Steps to Reproduce

```rust
#[wasm_bindgen]
pub struct MyStruct {
    hello: String,
}

#[wasm_bindgen]
impl MyStruct {
    #[wasm_bindgen(getter, typescript_type = "Thing[]")]
    pub things(&self) -> Vec<JsValue> {
        todo!()
    }
}
```

### Expected Behavior

Either the return type of the getter would be `Thing[]` _or_ the macro would have produced an error on the attempt to use `typescript_type`there.

### Actual Behavior

The `typescript_type` field will be ignored, and the getter will have a return type of `any[]`

**Comment by lukaslihotzki** [comment]
`wasm-bindgen` already supports rejecting the example case by enabling the `strict-macro` feature:
```
error: unused #[wasm_bindgen] attribute
  --> example/src/lib.rs:15:28
   |
15 |     #[wasm_bindgen(getter, typescript_type = "Thing[]")]
   |                            ^^^^^^^^^^^^^^^

error: could not compile `example` due to previous error
```
