### ISSUE TITLE
Where is EXTERNREF_HEAP_START defined?

### ISSUE THREAD

**Issue by allsey87** [rustwasm/wasm-bindgen#2885]
### Summary

[externref-xform/src/lib.rs:26](https://github.com/rustwasm/wasm-bindgen/blob/main/crates/externref-xform/src/lib.rs#L26) mentions that the constant `DEFAULT_MIN` must kept in sync with [src/lib.rs]() and `EXTERNREF_HEAP_START`, however I can not find any mention of `EXTERNREF_HEAP_START` in the repository. Where is this constant defined?

### Additional Details

I need to increase the size of the stack used by wasm-bindgen from 32 to 64. So far, I have updated the code in a fork in the following locations:
- [src/lib.rs:94](https://github.com/rustwasm/wasm-bindgen/blob/bf60a108795660fe77ee2229c4a8310c9a8e3b81/src/lib.rs#L94)
- [cli-support/src/js/mod.rs:79](https://github.com/rustwasm/wasm-bindgen/blob/bf60a108795660fe77ee2229c4a8310c9a8e3b81/crates/cli-support/src/js/mod.rs#L79)
- [externref-xform/src/lib.rs:27](https://github.com/rustwasm/wasm-bindgen/blob/bf60a108795660fe77ee2229c4a8310c9a8e3b81/crates/externref-xform/src/lib.rs#L27)

Are there any other locations that I am missing?

**Comment by alexcrichton** [comment]
I believe all those offsets are the set of locations that need to be updated and the comments here are all outdated. I think having a larger default is also reasonable, it was never intended for 32 to be a final "this was tested to be perfect number", it was just sufficient for the small tests at the time. Ideally this number would be configurable by the wasm-bindgen CLI itself as well.

**Comment by allsey87** [comment]
>  Ideally this number would be configurable by the wasm-bindgen CLI itself as well.

That would indeed be ideal. Although seeing that the `HEAP_START` constant is defined in three separate locations in the repository, I guess this is not so easy to fix? Perhaps it is related to the offsets of the `true`, `false`, `undefined`, and `null` JsValue constants?

> I think having a larger default is also reasonable, it was never intended for 32 to be a final "this was tested to be perfect number", it was just sufficient for the small tests at the time.

 In #2884, I found that I needed a stack of 128 for my application, however, it does seems for most cases that 32 is a reasonable default.
