### ISSUE TITLE
Support abort(reason) call on AbortController.

### ISSUE THREAD

**Issue by gxtaillon** [rustwasm/wasm-bindgen#2889]
### Motivation

Provide accurate error message when aborting fetch programmatically without user input.

### Proposed Solution

Support `abort(reason)` call on [AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort).

### Alternatives

None known to me.

### Additional Context

Currently only [`abort()`](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.AbortController.html#method.abort) is supported. When using `abort()` on Chrome, cancelled `fetch()` calls return `AbortError: The user aborted a request.`. This is confusing when triggered without user input, for instance by timeouting early, or preemptively on navigation.

Best,
gxt

**Comment by ptdecker** [comment]
Up vote
