### ISSUE TITLE
Access files in headless unit tests

### ISSUE THREAD

**Issue by ZhaoXiangXML** [rustwasm/wasm-bindgen#2902]
### Summary

I'm trying to port a rust project from desktop to wasm.

Some unit tests of the project would access local files via `std::fs::File::open` which does not work on wasm.

I understand it supposed to use `fetch` to download the files but how can I host them in the server of headless unit tests?

### Additional Details

I've tried to put files into `wbg-tmp` folder but they got removed  at each run

**Comment by hamza1311** [comment]
Have you tried using the `include_str!`/`include_bytes!` macro? Those are provided by the std lib and include the content of the file at provided path at compile time

**Comment by ZhaoXiangXML** [comment]
> Have you tried using the `include_str!`/`include_bytes!` macro? Those are provided by the std lib and include the content of the file at provided path at compile time

I would like to have the same function to `fetch` files when running on production server so static included contents won't work.

**Comment by ZhaoXiangXML** [comment]
For now I'm using npm package [serve](https://www.npmjs.com/package/serve) to serve the project root on another port and use [start-server-and-test](https://www.npmjs.com/package/start-server-and-test) to run the tests.
