### ISSUE TITLE
Not possible to have `Result<Box[u8], JsValue>` as a return value

### ISSUE THREAD

**Issue by NumberFour8** [rustwasm/wasm-bindgen#2919]
### Describe the Bug

The `wasm-bindgen` does not compile when `Result<Box[u8]>, JsValue>` is specified as a return type on a function that in JS returns `Uint8Array` (or throws an exception).

Having the following code in Rust:

````
#[wasm_bindgen(catch, module = "my-module")]
extern "C" {
    pub fn read_file(s: &str) -> Result<Box<[u8]>, JsValue>;
}
````

and corresponding TypeScript function in `my-module` that can `throw` :

````
export function read_file(file: string): Uint8Array {
    return new Uint8Array(fs.readFileSync(file))
}
````

### Expected Behavior

It is possible to `catch` exceptions on JS functions that return a `TypedArray` (or throw) and
have it working with `Result<Box<[T]>, JsValue>` in Rust (where `T` is the corresponding number type in Rust).

### Actual Behavior

With `wasm-bindgen` version `0.2.80` the Rust compilation of the above code gives an error:

````
 pub fn read_file(s: &str) -> Result<Box<[u8]>, JsValue>;
   |            ^^^^^^^^^ the trait `FromWasmAbi` is not implemented for `Result<Box<[u8]>, wasm_bindgen::JsValue>`
````

On the other hand, `Option<Box<[T]>>` is working and supported, so this short-coming for `Result` seems more like a bug.

**Comment by Liamolucko** [comment]
`#[wasm_bindgen(catch)]` needs to be applied to the function, not the extern block. This version of your code compiles:

```rust
#[wasm_bindgen(module = "my-module")]
extern "C" {
    #[wasm_bindgen(catch)]
    pub fn read_file(s: &str) -> Result<Box<[u8]>, JsValue>;
}
```
