### ISSUE TITLE
Convert `JsValue` to `js_sys::Object`

### ISSUE THREAD

**Issue by coderaiser** [rustwasm/wasm-bindgen#2929]
### Summary

Hi!

I want to implement something like deep equal on `Rust` to speed up comparing `AST` nodes in 🐊[Putout](https://github.com/coderaiser/putout) code transformer. 

Right now I have such code:

```rust
let value_to = js_sys::Reflect::get(current_to, &key)?;
```

`value_to` is `JsValue`, but I need to get keys of an object and using `Object::keys`:

```rust
let keys_from: Array = Object::keys(&value_to);
```

But that's not work because `Object::keys` expects to receive `js_sys::Object`.

How can I convert `JsValue` to `js_sys::Object` and vice versa?

### Additional Details

I tried to use `serde_wasm_bindgen`, but I have an error:

![image](https://user-images.githubusercontent.com/1573141/172624047-364cb040-9fde-4992-87b3-16f87bc02388.png)

`Object::try_from` doesn't works here:

![image](https://user-images.githubusercontent.com/1573141/172627901-e7658c25-b992-4628-b457-08b2b789a95f.png)

**Comment by Liamolucko** [comment]
You can do this using [`dyn_into`](https://docs.rs/wasm-bindgen/0.2.80/wasm_bindgen/trait.JsCast.html#method.dyn_into). Instead of `Object::try_from(&value_to).unwrap()`, use `value_to.dyn_into().unwrap()`. (You'll also need to import `JsCast` to use it).
