### ISSUE TITLE
IntoWasmClosure change in 0.2.81 is a breaking change

### ISSUE THREAD

**Issue by JoelCourtney** [rustwasm/wasm-bindgen#2938]
### Describe the Bug

I don't think the changes in #2891 were intended to be breaking, because of [this commit description](https://github.com/rustwasm/wasm-bindgen/pull/2891/commits/209e89e9c180dca74ff8aacd78eb0fae05016645), but they were.

I encountered this when building [seed](https://github.com/seed-rs/seed). I'll open an issue there too. But I'm just letting you know, in case you want to do anything about it. I totally understand if you don't want to address the break, because I can easily set `wasm-bindgen = "=0.2.80"` for now.

### Steps to Reproduce

1. Build a new crate with dependency `seed = "0.9.1"`. It will produce the following errors:
```
error[E0283]: type annotations needed for `Closure<T>`
   --> /Users/Joelco/.cargo/registry/src/github.com-1ecc6299db9ec823/seed-0.9.1/src/browser/service/routing.rs:87:19
    |
87  |     let closure = Closure::new(move |event: web_sys::Event| {
    |         -------   ^^^^^^^^^^^^ cannot infer type for type parameter `T`
    |         |
    |         consider giving `closure` the explicit type `Closure<T>`, where the type parameter `T` is specified
    |
    = note: cannot satisfy `_: WasmClosure`
note: required by a bound in `Closure::<T>::new`
   --> /Users/Joelco/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-0.2.81/src/closure.rs:251:17
    |
251 |     T: ?Sized + WasmClosure,
    |                 ^^^^^^^^^^^ required by this bound in `Closure::<T>::new`
help: consider specifying the type argument in the function call
    |
87  |     let closure = Closure::new::<F>(move |event: web_sys::Event| {
    |                               +++++

error[E0283]: type annotations needed for `Closure<T>`
   --> /Users/Joelco/.cargo/registry/src/github.com-1ecc6299db9ec823/seed-0.9.1/src/browser/service/routing.rs:87:19
    |
87  |     let closure = Closure::new(move |event: web_sys::Event| {
    |         -------   ^^^^^^^^^^^^ cannot infer type for type parameter `T`
    |         |
    |         consider giving `closure` the explicit type `Closure<T>`, where the type parameter `T` is specified
    |
    = note: multiple `impl`s satisfying `[closure@/Users/Joelco/.cargo/registry/src/github.com-1ecc6299db9ec823/seed-0.9.1/src/browser/service/routing.rs:87:32: 126:6]: IntoWasmClosure<_>` found in the `wasm_bindgen` crate:
            - impl<T, A, R> IntoWasmClosure<(dyn Fn(A) -> R + 'static)> for T
              where <T as FnOnce<(A,)>>::Output == R, T: 'static, T: Fn<(A,)>, A: 'static, A: FromWasmAbi, R: 'static, R: ReturnWasmAbi;
            - impl<T, A, R> IntoWasmClosure<(dyn FnMut(A) -> R + 'static)> for T
              where <T as FnOnce<(A,)>>::Output == R, T: 'static, T: FnMut<(A,)>, A: 'static, A: FromWasmAbi, R: 'static, R: ReturnWasmAbi;
note: required by a bound in `Closure::<T>::new`
   --> /Users/Joelco/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-0.2.81/src/closure.rs:271:12
    |
271 |         F: IntoWasmClosure<T> + 'static,
    |            ^^^^^^^^^^^^^^^^^^ required by this bound in `Closure::<T>::new`
help: consider specifying the type argument in the function call
    |
87  |     let closure = Closure::new::<F>(move |event: web_sys::Event| {
    |                               +++++
```
2. For comparison, add the dependency `wasm-bindgen = "=0.2.80"`, and the errors go away.

### Expected Behavior

Should be able to build seed without fixing `wasm-bindgen = "=0.2.80"`.

**Comment by JoelCourtney** [comment]
Thanks to @ndarilek for opening a ticket in seed [here](https://github.com/seed-rs/seed/issues/687)

**Comment by alexcrichton** [comment]
cc @Liamolucko I think this is related to https://github.com/rustwasm/wasm-bindgen/pull/2891 would you be up for taking a look?

**Comment by Liamolucko** [comment]
It's because of this: https://github.com/seed-rs/seed/blob/master/src/browser/util.rs#L299-L316

Looks like Seed had defined its own extension to add `Closure::new`, which was overridden by the inherent method.
They aren't compatible because Seed restricts the closure to `FnMut`, giving the result a concrete type, whereas `wasm-bindgen` also allows it to be `Fn` and the compiler can't infer which one should be used.

**Comment by alexcrichton** [comment]
Thanks for the investigation! @JoelCourtney do you know if this is something `seed` would be ok changing on its end? e.g. giving a new name to the closure trait extension method?

This sort of breakage is also relatively common with the standard library IIRC and there's not really a great way out of it unfortunately as far as I know

**Comment by JoelCourtney** [comment]
@alexcrichton Looks like they're already working on it. I'm going to close this ticket since there doesn't seem to be anything to do in `wasm-bindgen`. Thanks for your help!

**Comment by flosse** [comment]
@JoelCourtney it's fixed now and you can use the master branch of seed until a new version is released.
