### ISSUE TITLE
GitHub release missing for version 0.2.81

### ISSUE THREAD

**Issue by iTitus** [rustwasm/wasm-bindgen#2939]
8 hours ago version 0.2.81 was released, but there is no GitHub release for it.
This sadly breaks [Trunk](https://trunkrs.dev/) builds, as it tries to download the newest version from [here](https://github.com/rustwasm/wasm-bindgen/releases/download/0.2.81/wasm-bindgen-0.2.81-x86_64-unknown-linux-musl).
Was there an issue with the build?

**Comment by alexcrichton** [comment]
Sorry I forgot the tag. I just pushed that and will check back tomorrow on the build happening here -- https://github.com/rustwasm/wasm-bindgen/actions/runs/2498733817

**Comment by iTitus** [comment]
Thank you very much, it is working now!
