### ISSUE TITLE
Reference types incompatible with wasm-opt

### ISSUE THREAD

**Issue by MartinKavik** [rustwasm/wasm-bindgen#2943]
### Summary

Why a Wasm web project created by `wasm-bindgen` with the parameter `--reference-types` fails once it's optimized by [wasm-opt](https://github.com/WebAssembly/binaryen#binaryen-optimizations)?

### Additional Details

- The error says `Uncaught (in promise) RangeError: WebAssembly.Table.grow(): failed to grow table by 4`.
- More info and examples in https://github.com/WebAssembly/binaryen/issues/4711
- We don't know (yet) whether it's a `wasm-opt` bug, `wasm-bindgen` bug or an unlucky combination caused by both tools.

Thank you!

**Comment by allsey87** [comment]
I have added an MRE for this issue over here: https://github.com/WebAssembly/binaryen/issues/4711#issuecomment-1157553817

**Comment by allsey87** [comment]
@MartinKavik I think this issue can be closed now that https://github.com/WebAssembly/binaryen/pull/4736 has been merged.
