### ISSUE TITLE
Getters and setters are missing jsdoc types in 0.2.81 (not 0.2.80)

### ISSUE THREAD

**Issue by dsherret** [rustwasm/wasm-bindgen#2947]
### Describe the Bug

In the latest 0.2.81 the .js file is missing jsdoc types on getters and setters. This is because in #2909 they were set to `None`: https://github.com/rustwasm/wasm-bindgen/pull/2909/files#diff-072222e984a549efeebf98f26d0c59a69d88abe246db7e0958654fc32471313eR2531

### Steps to Reproduce

Sorry, I do not have time right now to offer a simple reproduction, but I have pointed out the cause in the code above. Also a fix can be seen here, which is a revert of the above: https://github.com/rustwasm/wasm-bindgen/commit/387e821c8074b18e251fa5991ccc531302223961 -- but it is probably not a real fix since this was done for some reason in #2909

### Expected Behavior

Getters and setters should still have jsdoc comment types when not using TypeScript.

### Actual Behavior

The types are missing in 0.2.81

cc @Hywan

**Comment by Hywan** [comment]
Hello @dsherret,
Can you confirm that https://github.com/rustwasm/wasm-bindgen/pull/2956 solves your problem? We should restore some disabled tests to ensure this behavior is totally fixed, I'll probably work on this soon.

**Comment by dsherret** [comment]
@Hywan yup, it's fixed. Thanks so much for looking into it!
