### ISSUE TITLE
Why is poll only executed one times?

### ISSUE THREAD

**Issue by Mng12345** [rustwasm/wasm-bindgen#2948]
### Describe the Bug

Hi, i have written an asynchrous code with wasm_bindgen, i used spawn_local to run a future, i found that the poll function was only executed one times, the example code likes below:
```rust
use std::{future::Future, task::Poll};

use wasm_bindgen_futures::spawn_local;

struct A {
    count: i32,
}

impl Future for A {
    type Output = i32;

    fn poll(
        self: std::pin::Pin<&mut Self>,
        _cx: &mut std::task::Context<'_>,
    ) -> std::task::Poll<Self::Output> {
        log::info!("poll one times.");
        if self.count < 10 {
            self.get_mut().count = self.count + 1;
            Poll::Pending
        } else {
            Poll::Ready(self.count)
        }
    }
}

pub fn start() {
    spawn_local(async {
        let output = A { count: 0 }.await;
        log::info!("output: {}", output);
    });
}

```
[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2c4ff01bde313dfc1167cfb26c3bed64)

![image](https://user-images.githubusercontent.com/21278900/174208461-c89d3086-0bc6-497e-8b64-ebe2b09b56a6.png)
From the browser's console, the poll function was only executed one times, and the future's status was always pending.

### dependencies
[dependencies]
yew = "0.19"
rand = "0.8.5"              # Random number generators and other randomness functionality.
bounce = "0.2.0"    # The uncomplicated state management library for Yew.
getrandom = { version = "0.2", features = ["js"] }
log = "0.4.6"
wasm-logger = "0.2.0"
lazy_static = "1.4.0"
indexed_db_futures = "0.2.3"

[dependencies.web-sys]
version = "0.3"
features = [
    "console",
    "HtmlElement",
    "MouseEvent",
    "DomRect",
    "Window",
    "DomException",
    "DomStringList",
    "IdbDatabase",
    "IdbFactory",
    "IdbOpenDbRequest",
    "IdbRequest",
    "IdbRequestReadyState",
    "IdbVersionChangeEvent",
    "IdbObjectStore",
    "IdbObjectStoreParameters",
    "IdbTransaction",
    "IdbTransactionMode",
    "IdbIndex",
    "IdbIndexParameters",
    "Performance",
    "CanvasRenderingContext2d",
    "ImageData",
    "Document",
    "HtmlCanvasElement",
    "Node"
]

[dependencies.wasm-bindgen]
version = "0.2"
features = [
    "serde-serialize"
]

[dependencies.wasm-bindgen-futures]
version = "0.4"

[dependencies.js-sys]
version = "0.3.55"

**Comment by Mng12345** [comment]
Sorry, i misunderstanded the usage of Future, i will close this issue.

**Comment by SapiensAnatis** [comment]
I also misunderstood future (and still probably don't understand it) but to try and provide a more detailed explanation: if you return Pending, you need to also schedule the next poll using the waker. Here's a tokio program that illustrates this:

```rs
use std::future::*;
use std::pin::Pin;
use std::task::*;

pub struct CounterFuture {
    counter: i32,
}

impl Future for CounterFuture {
    type Output = Result<(), &'static str>;

    fn poll(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
        self.counter += 1;
        println!("Counter: {}", self.counter);

        match self.counter {
            ..5 => {
                // If you uncomment this line, poll will only be called once...
                cx.waker().wake_by_ref();
                return Poll::Pending;
            }
            _ => Poll::Ready(Ok(())),
        }
    }
}

#[tokio::main]
async fn main() {
    let fut = CounterFuture { counter: 0 };
    match fut.await {
        Ok(()) => {
            println!("Future finished.");
        }
        Err(e) => {
            eprintln!("Future failed: {}", e);
        }
    };
}
```

From the [docs](https://doc.rust-lang.org/std/task/struct.Waker.html)

> The typical life of a Waker is that it is constructed by an executor, wrapped in a [Context](https://doc.rust-lang.org/std/task/struct.Context.html), then passed to [Future::poll()](https://doc.rust-lang.org/std/future/trait.Future.html#tymethod.poll). Then, if the future chooses to return [Poll::Pending](https://doc.rust-lang.org/std/task/enum.Poll.html#variant.Pending), it must also store the waker somehow and call [Waker::wake()](https://doc.rust-lang.org/std/task/struct.Waker.html#method.wake) when the future should be polled again.
