### ISSUE TITLE
js-sys returns `undefined` when calling a function that should return a `String`

### ISSUE THREAD

**Issue by SpaceComet** [rustwasm/wasm-bindgen#2953]
### Describe the Bug

Js-sys is not working property when using `Function.call` to call a function that should return a `String`. 
Instead is returning a `undefined` result

### Steps to Reproduce:

1. Compile a wasm lib to have the next function:

```rust
#[wasm_bindgen]
pub fn hello() -> String {
 "--------- >> Hello !!".into()
}
```

2. Create a project with the `src/lib.rs` like in the [examples1.8 ](https://rustwasm.github.io/wasm-bindgen/examples/wasm-in-wasm.html) but with some small changes to call the function `hello`

```rust
# file: src/lib.rs
use js_sys::{Function, Object, Reflect, WebAssembly};
use wasm_bindgen::prelude::*;
use wasm_bindgen::JsCast;
use wasm_bindgen_futures::{spawn_local, JsFuture};

// lifted from the `console_log` example
#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(js_namespace = console)]
    fn log(a: &str);
}

macro_rules! console_log {
    ($($t:tt)*) => (log(&format_args!($($t)*).to_string()))
}

const WASM: &[u8] = include_bytes!("add.wasm");

async fn run_async() -> Result<(), JsValue> {
    console_log!("instantiating a new wasm module directly");

    let a = JsFuture::from(WebAssembly::instantiate_buffer(WASM, &Object::new())).await?;
    let b: WebAssembly::Instance = Reflect::get(&a, &"instance".into())?.dyn_into()?;

    let c = b.exports();

    let hello = Reflect::get(c.as_ref(), &"hello".into())?
        .dyn_into::<Function>()
        .expect("add export wasn't a function");

    let hello_r = hello.call0(&JsValue::undefined())?;

    console_log!("# From call0: {:?}", hello_r);

    Ok(())
}

#[wasm_bindgen(start)]
pub fn run() {
    spawn_local(async {
        run_async().await.unwrap_throw();
    });
}
```

### Expected Behavior

This should return a `String` from the function `hello`
```rust
let hello_r = hello.call0(&JsValue::undefined())?;
console_log!("# From call0: {:?}", hello_r);
```

### Actual Behavior

It is returning `undefined`

**Comment by Liamolucko** [comment]
The issue is that you're calling the raw WebAssembly function. It's impossible for a WebAssembly function to return a string directly; instead, it has some `wasm-bindgen` internal signature, for which `wasm-bindgen` generates some JS glue to make it return a string.

To get it to return a string, you'd have to use the `wasm-bindgen` glue code as well as the raw WebAssembly.

**Comment by SpaceComet** [comment]
@Liamolucko  You are right. I finally understand. I thought it was a bug but I just didn't know that. Thank you. I think I should close this issue
