### ISSUE TITLE
`type mismatch` occurred when building codes including FFI for C

### ISSUE THREAD

**Issue by NewGyu** [rustwasm/wasm-bindgen#2958]
### Summary

I'm trying to make wasm which including FFI for C. There is an example code to try it.
https://github.com/NewGyu/rust-ffi-with-cmake-example/tree/repro/wasm-bindgen

`type mismatch` was occurred when trying to build the example with `wasm-pack build`.

```shell
$ wasm-pack build --target web ./ffi-example
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
   Compiling proc-macro2 v1.0.39
   Compiling unicode-ident v1.0.1
      :
   Compiling wasm-bindgen-macro v0.2.81
   Compiling ffi-example v0.1.0 (/workspaces/rust-ffi-with-cmake-example/ffi-example)
    Finished release [optimized] target(s) in 4.96s
[WARN]: :-) origin crate has no README
[INFO]: Installing wasm-bindgen...
error: failed getting Wasm module for '/workspaces/rust-ffi-with-cmake-example/target/wasm32-unknown-unknown/release/ffi_example.wasm'

Caused by:
    0: failed to parse input as wasm
    1: failed to parse code section
    2: type mismatch: expected i32 but nothing on stack (at offset 1212)
Error: Running the wasm-bindgen CLI
Caused by: failed to execute `wasm-bindgen`: exited with exit status: 1
  full command: "/home/vscode/.cache/.wasm-pack/wasm-bindgen-e0094da74c1e9817/wasm-bindgen" "/workspaces/rust-ffi-with-cmake-example/target/wasm32-unknown-unknown/release/ffi_example.wasm" "--out-dir" "./ffi-example/pkg" "--typescript" "--target" "web"
```

#### What I noticed 1
It seems that compilation to wasm is successful. `ffi_example.wasm` file is created in target/wasm32-unknown-unknown dir. However, wat file reversed from the wasm contains questionable data.
```
(data $d0 (i32.const 1048576) "ffi-example/src/lib.rs\00\00\00\00\10\00\16\00\00\00\07\00\00\00#\00\00\00\00\00\10\00\16\00\00\00\0f\00\00\00\0a\00\00\00called `Result::unwrap()` on an `Err` value\00\01\00\00\00\10\00\00\00\04\00\00\00\02\00\00\00\03\00\00\00\08\00\00\00\04\00\00\00\04\00\00\00library/std/src/ffi/c_str.rs\84\00\10\00\1c\00\00\00\8d\01\00\007\00\00\00called `Option::unwrap()` on a `None` valuelibrary/std/src/panicking. .......
```

#### What I noticed 2
The problem is not occurred when omitting `[wasm-bindgen]` attr. The build will succeed if the following patch is applied.
https://github.com/NewGyu/rust-ffi-with-cmake-example/commit/813cd08d313de50bf1d8a4fd2350b25c9b1d495d

#### Other
Note: My real goal is wasm including FFI for Graphviz, but it is hard for me now. So, I'm trying with the above simple example.

Sorry if my question is not appropriate for here.

**Comment by Liamolucko** [comment]
I think it's because you've named your exported functions the same thing as their C versions. Unlike most of the time in Rust, `wasm-bindgen` gives exported functions exactly the same symbol name as the name the function is defined with. In this case that's the same as the functions already defined in C, which seems to have caused the linker to silently break and make the functions call themselves instead of the C versions, and pass invalid arguments as a result.

> It seems that compilation to wasm is successful. `ffi_example.wasm` file is created in target/wasm32-unknown-unknown dir. However, wat file reversed from the wasm contains questionable data.
> 
> ```
> (data $d0 (i32.const 1048576) "ffi-example/src/lib.rs\00\00\00\00\10\00\16\00\00\00\07\00\00\00#\00\00\00\00\00\10\00\16\00\00\00\0f\00\00\00\0a\00\00\00called `Result::unwrap()` on an `Err` value\00\01\00\00\00\10\00\00\00\04\00\00\00\02\00\00\00\03\00\00\00\08\00\00\00\04\00\00\00\04\00\00\00library/std/src/ffi/c_str.rs\84\00\10\00\1c\00\00\00\8d\01\00\007\00\00\00called `Option::unwrap()` on a `None` valuelibrary/std/src/panicking. .......
> ```

That bit is normal, it basically just contains the contents of all the string literals, statics, etc. used in your code.

**Comment by NewGyu** [comment]
@Liamolucko Thank you so much!!! Your great advice helps me and solve my problem.
https://github.com/NewGyu/rust-ffi-with-cmake-example/commit/5a19ac28325692daab1773b26cf6c46a65684517

Without you, I would not have gotten here. Many thanks!!
