### ISSUE TITLE
Eagerly cached TypedArray objects cause circular dependency for bundler modes

### ISSUE THREAD

**Issue by ishitatsuyuki** [rustwasm/wasm-bindgen#2961]
### Describe the Bug

Descriptions like `cachedInt32Memory0 = new Int32Array(wasm.memory.buffer);` creates a circular dependency between the `bg` module and the instantiation wrapper created by bundlers, because the wrapper needs to import the `bg` module to pass the exports to `WebAssembly.instantiate`'s second argument (`importObject`), while this depends on `wasm.memory` which is initialized *after* the instantiation is complete.

### Steps to Reproduce

I haven't isolated the reproduction yet, because it seems to depend on the use of certain ArrayBuffer related function calls.

I'm using https://github.com/Menci/vite-plugin-wasm, but at a quick glance Webpack should be doing the implementation in basically the same manner.

### Errors

```
Uncaught ReferenceError: can't access lexical declaration 'memory' before initialization
    <anonymous> http://localhost:3000/rust/pkg/wasm_bg.js?t=1655889863398:318
```

### Proposed modification

Just make it lazy.

```diff
diff --git a/crates/cli-support/src/js/mod.rs b/crates/cli-support/src/js/mod.rs
index 8ca6a854..86dda79c 100644
--- a/crates/cli-support/src/js/mod.rs
+++ b/crates/cli-support/src/js/mod.rs
@@ -607,10 +607,9 @@ impl<'a> Context<'a> {
             for kind in views {
                 writeln!(
                     out,
-                    "cached{kind}Memory{num} = new {kind}Array(wasm.{mem}.buffer);",
+                    "cached{kind}Memory{num} = new {kind}Array();",
                     kind = kind,
                     num = num,
-                    mem = mem,
                 )
                 .unwrap()
             }
```

**Comment by gthb** [comment]
In my case (running in Node.js 16, importing the wasm-bindgen module as an ES module, having changed the wasm-pack-generated `package.json` to have `"type": "module"` and a `"main"` attribute) the problem manifested as:
```js
ReferenceError: memory is not defined
```
(just adding that comment to make this issue easier for others to find than it was for me! 😊)
