### ISSUE TITLE
Error using Node.js with ES Module to import Rust function that contains `rand::thread_rng()`

### ISSUE THREAD

**Issue by Carrick-K7** [rustwasm/wasm-bindgen#2967]
### Summary

The `wasm-bindgen` converts the Rust function that contains `rand:thread_rng()` into js glue code that contains `const ret = module`, no matter `--target bundler` or `--target nodejs`. So an error `ReferenceError: module is not defined` occurs if the target is bundler or web because `module` is NOT defined in ESM.

### Additional Details

I'm trying to use wasm-pack to convert a rust function that contains `rand::thread_rng()` into .wasm file and then import it using Node.js. There is a function created in the js glue code:
```js
module.exports.__wbg_static_accessor_NODE_MODULE_26b231378c1be7dd = function() { 
    const ret = module;
    return addHeapObject(ret);
};
```
Everything is ok if the glue code is generated in CommonJS (using `wasm-pack build --target nodejs`) because `module` is already defined. But when the glue code is generated in ES Module (using `wasm-pack build`), `ReferenceError: module is not defined` occurs. The static accessor code doesn't change a lot: 
```js
export function __wbg_static_accessor_NODE_MODULE_26b231378c1be7dd() { return logError(function () {
    const ret = module;
    return addHeapObject(ret);
}, arguments) };
```
However, `module` is not defined in the whole glue code since it's ESM. Therefore, when I tried to run `node --experimental-wasm-modules myScript.js`, the abovementioned `ReferenceError` occurred. **Is there any way to construct a `module` object that is similar to the one in CJS glue code, or replace the `module` with other terms in ESM glue code?** Thanks for any solutions or thoughts in advance :)

**ps**: I know that it looks like a `wasm-pack` problem, but the static accessor function generated by wasm-bindgen  containing `const ret = module` is the source of the problem. So I decide to create a issue here instead of in the `wasm-pack` repo. Please feel free to correct me if I'm wrong :)

**pps**: The same error can be reproduced using `WebAssembly.instantiate()` to load wasm file, so I'm quite sure that it's not a problem about `--experimental-wasm-modules`.

**Comment by Carrick-K7** [comment]
**Current environment**: `Node.js v16.6.2`, `wasm-pack v0.10.3`

**Steps to reproduce the error** (`Node.js >= v13` and `wasm-pack` needed):
- `$ git clone https://github.com/originjs/WASM-benchmark-rust-repos.git`
- `$ git checkout rsa`
- `$ wasm-pack build --debug`
- Create a new file in current directory named `index.mjs` with following code:
```js
import { RsaPrivate } from "./pkg/rsa_rust.js"

new RsaPrivate(2048);
```
- Add `"type": "module"` to `./pkg/package.json`
- Comment last two lines of `./pkg/rsa_rust_bg.js`
```js
// cachedInt32Memory0 = new Int32Array(wasm.memory.buffer);
// cachedUint8Memory0 = new Uint8Array(wasm.memory.buffer);
```
- `$ node --experimental-wasm-modules index.mjs`

Then you should be able to see the error:
```sh
ReferenceError: module is not defined
    at file:///X:/WASM-benchmark-rust-repos/pkg/rsa_rust.js:414:21
    at logError (file:///X:/WASM-benchmark-rust-repos/pkg/rsa_rust.js:143:18)
    at __wbg_static_accessor_NODE_MODULE_26b231378c1be7dd (file:///X:/WASM-benchmark-rust-repos/pkg/rsa_rust.js:413:90)
    at getrandom::imp::NODE_MODULE::init::h03001817f556f76e (<anonymous>:wasm-function[4171]:0x1d26f0)
    at getrandom::imp::NODE_MODULE::_VAL::__init::hd021fa61d0b97d91 (<anonymous>:wasm-function[4217]:0x1d2974)
    at getrandom::imp::NODE_MODULE::_VAL::__getit::{{closure}}::hab0265171a73d2de (<anonymous>:wasm-function[694]:0x15ebc4)
    at std::thread::local::lazy::LazyKeyInner<T>::initialize::hece786b60c529fdb (<anonymous>:wasm-function[1434]:0x1969b8)
    at std::thread::local::statik::Key<T>::get::hb5375a8c52ae352b (<anonymous>:wasm-function[1289]:0x18ec4b)
    at getrandom::imp::NODE_MODULE::_VAL::__getit::h887e346057193017 (<anonymous>:wasm-function[2869]:0x1c111f)
    at std::thread::local::LocalKey<T>::try_with::h34b41b738c919981 (<anonymous>:wasm-function[1448]:0x197539)
```

**Comment by Liamolucko** [comment]
It looks like this has already been reported over at rust-random/getrandom#256.
