### ISSUE TITLE
the trait `From<anyhow::Error>` is not implemented for `JsValue`

### ISSUE THREAD

**Issue by junglie85** [rustwasm/wasm-bindgen#2970]
### Summary

This code generates the following error when run with 0.2.81:

```
#[cfg_attr(target_arch = "wasm32", wasm_bindgen(start))]
pub fn run() -> anyhow::Result<()> {
```

```
error[E0277]: the trait bound `JsValue: From<anyhow::Error>` is not satisfied
  --> src\lib.rs:10:36
   |
10 | #[cfg_attr(target_arch = "wasm32", wasm_bindgen(start))]
   |                                    ^^^^^^^^^^^^^^^^^^^ the trait `From<anyhow::Error>` is not implemented for `JsValue`
```

From https://github.com/rustwasm/wasm-bindgen/issues/1742, I was expecting to be able to do this.
How can I use anyhow here?

**Comment by hamza1311** [comment]
I suggest you look at gloo. `gloo-utils::error::JsError` can be created from `JsValue` and it implements `std::error::Error` so it can be used by anyhow

**Comment by Liamolucko** [comment]
You can't use `anyhow::Result` as the return type, but you can use [`wasm_bindgen::JsError`](https://docs.rs/wasm-bindgen/latest/wasm_bindgen/struct.JsError.html), which should work almost as well. It implements `From` for anything that implements `std::error::Error` (including `anyhow::Error`), which is implicitly used by the `?` operator to be able to return any well-behaved error type.

> I suggest you look at gloo. `gloo-utils::error::JsError` can be created from `JsValue` and it implements `std::error::Error` so it can be used by anyhow

That's for converting from a JS error to a Rust error, which is the wrong way around here.

**Comment by stefnotch** [comment]
@Liamolucko I can't seem to convert an anyhow::Error to a wasm_bindgen::JsError.

e.g. I have a function that currently returns an anyhow error, and so I figured I'd try to manually convert it. That didn't work out.
```
error[E0277]: the trait bound `anyhow::Error: StdError` is not satisfied
   --> wasm\src\application.rs:182:57
    |
182 |         let mut app = CpuApplication::new().map_err(|e| JsError::from(e))?;
    |                                                         ^^^^^^^ the trait `StdError` is not implemented for `anyhow::Error`, which is required by `JsError: From<anyhow::Error>`
    |
    = help: the trait `From<E>` is implemented for `JsError`
    = note: required for `JsError` to implement `From<anyhow::Error>`

```

**Comment by Liamolucko** [comment]
> @Liamolucko I can't seem to convert an anyhow::Error to a wasm_bindgen::JsError.

Oops, I was wrong: `anyhow::Error` doesn't implement `std::error::Error`. I'm guessing that's because it there would be a conflict between its `From<Self>` and `From<E> where E: Error` impls if it did?

It does implement `Deref<Target = dyn Error>` though, so you can still convert one to a `JsError` like so (since `&dyn Error` implements `Error`):

```rs
let mut app = CpuApplication::new().map_err(|e| JsError::from(&*e))?;
```

`JsError::from` just calls `e.to_string()`, so this doesn't run into any errors about `e` not living long enough.

**Comment by daxpedda** [comment]
See [`#[wasm_bindgen(main)]`](https://rustwasm.github.io/docs/wasm-bindgen/reference/attributes/on-rust-exports/main.html) as well, which should be able to handle this.
