### ISSUE TITLE
Can't use WASM functions after upgrade to create-react-app 5

### ISSUE THREAD

**Issue by ivanschuetz** [rustwasm/wasm-bindgen#2971]
### Summary

After upgrading my project to CRA 5, there seems to be a problem in `wasm_bg.js` using the exports from `wasm_bg.wasm.d.ts`
```
Compiled with problems:
ERROR in ../wasm-build/wasm_bg.js 13:71-89
Can't import the named export 'memory'.'buffer' (imported as 'wasm') from default-exporting module (only default export is available)
[...]
```

I also tried creating a new project with create-react-app (latest version - see npm version at the bottom), moving over my files and missing dependencies, same error. 

The new project was configured similarly to here: 
https://koala42.com/using-webassembly-in-your-reactjs-app/
With the addition of adding the wasm build to the dependencies `"wasm": "file:../wasm-build"` (which they might have forgotten?)

### Additional Details

Build command:
```
wasm-pack build --out-dir ../wasm-build --debug
```
npm version: 8.13.2
wasm-bindgen version: 0.2.80
wasm-pack version:  0.10.3

**Comment by ivanschuetz** [comment]
Here are 2 minimal example repositories:

With webpack configuration dir:
https://github.com/ivanschuetz/wasm-cra5

With `react-app-rewired` (which allows to only override configurations):
https://github.com/ivanschuetz/wasm-cra5-rewired

Updated dependencies (wasm-bindgen 0.2.81)

Any ideas? 2 other people have reported the same issue (Discord).

**Comment by acheroncrypto** [comment]
This was a big pain to solve but [here](https://github.com/solana-playground/solana-playground/blob/master/client/craco.config.js) is a solution that works with CRA 5.

**Comment by ivanschuetz** [comment]
> This was a big pain to solve but [here](https://github.com/solana-playground/solana-playground/blob/master/client/craco.config.js) is a solution that works with CRA 5.

Thanks! not working for me however.

1. I tried running `npm install` on your repo and got errors:

> npm ERR! Found: react-scripts@5.0.0
> npm ERR! node_modules/react-scripts
> npm ERR!   react-scripts@"5.0.0" from the root project
> npm ERR! Could not resolve dependency:
> npm ERR! peer react-scripts@"^4.0.0" from @craco/craco@6.4.3
> npm ERR! node_modules/@craco/craco
> npm ERR!   dev @craco/craco@"^6.4.3" from the root project

In the [Craco repo](https://github.com/dilanx/craco) it's stated that CRA 5 is not supported:

    ℹ️ The latest CRACO release does not support CRA 5, but alpha builds will be regularly released over the next few days. Keep up to date with our progress https://github.com/dilanx/craco/issues/426.

2. I tried migrating the Craco configuration from your repo to my rewired repo: https://github.com/ivanschuetz/wasm-cra5-rewired/commit/e0f2552caf4feb1295745d0576f9d543816a6dfb it didn't change anything.

I'm rather not experienced with npm / webpack however so most likely missing something.

Adding that `experiments: { asyncWebAssembly: true }` is mentioned in the [webpack 5 migration guide](https://webpack.js.org/migrate/5/).

**Comment by acheroncrypto** [comment]
The repo has `yarn.lock` file and I've tried to run `npm i` and had the same error. Please try using `yarn`.

**Comment by hamza1311** [comment]
@ivanschuetz can you try [this patch](https://gist.github.com/hamza1311/35af4820d12f1d51d886b72455ae9b52) in your rewired repo? I just tested it and it should work.

**Comment by kalzoo** [comment]
@acheroncrypto brilliant, thank you for sharing! Worked for me, specifically this part was new in `config-overrides.js`:

```js
  config.experiments = {
    asyncWebAssembly: true,
  };
  config.module.rules.forEach((rule) => {
    (rule.oneOf || []).forEach((oneOf) => {
      if (oneOf.type === "asset/resource") {
        oneOf.exclude.push(wasmExtensionRegExp);
      }
    });
  });
```

Also using `react-app-rewired`.

**Comment by ivanschuetz** [comment]
@hamza1311 just noticed something, this line: https://gist.github.com/hamza1311/35af4820d12f1d51d886b72455ae9b52#file-fix-patch-L73, was it meant to be the scripts maybe? rewired is here: https://gist.github.com/hamza1311/35af4820d12f1d51d886b72455ae9b52#file-fix-patch-L93 in my example, it can be removed.

**Comment by ivanschuetz** [comment]
I'm closing this, because it was solved. The React questions are probably better addressed in a space dedicated to that.
