### ISSUE TITLE
Confusing error when trying to use a moved value

### ISSUE THREAD

**Issue by rylev** [rustwasm/wasm-bindgen#30]
When a struct is passed by value (i.e., moved) into a function that is being called by JS the generated JS code nulls out the pointer to that struct in the wrapping ES6 class. This makes total sense - the struct has been moved so the previous ref to it is now invalidated, but the error at run time is simply: `Error: null pointer passed to rust`. 

Would it make debugging easier if the class kept track of if it has been invalidated due to a move and throws a more descriptive error?

**Comment by alexcrichton** [comment]
Sure yeah! There's already a debug flag to the cli tool so when that is passed I think it'd be great to generate this info

**Comment by alexcrichton** [comment]
Ah indeed I think this is done now!
