### ISSUE TITLE
toJSON method generated by 'inspectable' not in .d.ts type declarations

### ISSUE THREAD

**Issue by shreepads** [rustwasm/wasm-bindgen#3000]
### Describe the Bug

The toJSON() method generated by adding #[wasm_bindgen(inspectable)] to a struct is not present in the generated typescript  .d.ts type declarations and therefore cannot be used in typescript

### Steps to Reproduce

1. Add #[wasm_bindgen(inspectable)] to a struct in a Rust source file
2. Run wasm-pack build packagename --target web on the package
3. A pkg sub-folder is generated with the packagename.js, packagename.d.ts files
4. The .js file contains the toJSON() on the class corresponding to the struct and it can be invoked from javascript
5. The .d.ts file doesn't contain the type declaration for the toJSON() method
6. Attempting to use the toJSON method in typescript results in a compile time error (see below)
7. There are no other problems, the rest of the code works perfectly when invoked from the React app

`ERROR in src/App.tsx:153:32
TS2339: Property 'toJSON' does not exist on type 'Struct'.
    152 |
  > 153 |   console.log(test.toJSON());
        |                                ^^^^^^
    154 |
`

### Expected Behavior

The .d.ts file contains the declaration for the toJSON() method, allowing it to be used from typescript

### Actual Behavior

The .d.ts file does not contain the declaration for the toJSON() method, preventing it from being used from typescript

### Additional Context

wasm-bindgen v0.2.81
wasm-pack v0.10.3
cargo v1.62.0
rustc v1.62.0 (Fedora 1.62.0-1.fc35)
Fedora 64bit Workstation v35
Using it in a React app, but that doesn't seem relevant to the problem at hand

**Comment by Liamolucko** [comment]
Fixed by #3001

**Comment by shreepads** [comment]
Thanks @petrstudynka , @alexcrichton ! 

Can confirm it's working as expected with wasm-bindgen = "0.2.82"
