### ISSUE TITLE
BigUint64Array/BigInt64Array should be constructed from u64 arrays, not BigInt arrays

### ISSUE THREAD

**Issue by ishitatsuyuki** [rustwasm/wasm-bindgen#3009]
In https://docs.rs/js-sys/latest/js_sys/struct.BigUint64Array.html, various methods like `pub fn copy_from(&self, src: &[BigInt])` takes a slice of `BigInt`s. But `BigInt` is an object, and this just doesn't look right. When indexed from JS code they should indeed return a BigInt object, but from the view of wasm their representation should be a u64.

**Comment by Liamolucko** [comment]
You're right, but unfortunately it's a breaking change to fix it.

**Comment by ishitatsuyuki** [comment]
Well, does the old signature even work? It sounds like it will read garbage since the type signature doesn't make much sense?
