### ISSUE TITLE
v0.2.82 breaks typescript .d.ts definitions for enums

### ISSUE THREAD

**Issue by phi-fell** [rustwasm/wasm-bindgen#3010]
### Describe the Bug

Enums with static methods (e.g. constructors) worked fine in 0.2.81, but now in 0.2.82 they are no longer exported to the built .d.ts file.

After testing the intervening changes, [this commit](https://github.com/rustwasm/wasm-bindgen/commit/4e72af28a029199bb3ea3ef783a41b7d620265b0) appears to be the cause.

### Steps to Reproduce

Minimal reproducible example:

1. create a new folder, move into it
2. create `Cargo.toml`
```
[package]
name = "example"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "=0.2.82"

[build-dependencies]
wasm-pack = "0.10.3"
```
3. create `src/lib.rs`
```
use wasm_bindgen::prelude::*;

pub enum MyEnum {
    A(usize),
}

#[wasm_bindgen]
impl MyEnum {
    pub fn new_a() -> u32{
        0
    }
}
```
4.  run `wasm-pack build --target web`
5. note that `pkg/example.d.ts` contains:
```
export class MyEnum {
  free(): void;
/**
* @returns {number}
*/
  static new_a(): number;
}
```
6. in `Cargo.toml` change `wasm-bindgen = "=0.2.81"` to `wasm-bindgen = "=0.2.82"`
7. Note that `pkh/example.d.ts` no longer contains the enum *OR* it's static function

Example repo with both versions: https://github.com/phi-fell/wasm-bindgen-issue

### Expected Behavior

enum definitions should be exported - i,e, the behavior as of v0.2.81 (or [this commit](https://github.com/rustwasm/wasm-bindgen/commit/542955514e0069bc1d56048fb73c54aa9e410cc7)) should continue to occur

### Actual Behavior

enum definitions are not exported

**Comment by mmgeorge** [comment]
Also running into this

**Comment by daxpedda** [comment]
Shouldn't the enum itself have a `#[wasm_bindgen]` macro invocation on it as well?
This might have been a bug to begin with, because `wasm-bindgen` doesn't support exporting non-C-style enums.

Let me know if this doesn't explain the issue!
