### ISSUE TITLE
Support `DomRect.top()` and similar

### ISSUE THREAD

**Issue by arctic-hen7** [rustwasm/wasm-bindgen#3025]
### Describe the Bug

The MDN documentation for [`DomRect`](https://developer.mozilla.org/en-US/docs/Web/API/DOMRect) lists `.top()`, `.right()`, `.left()`, and `.bottom()` as methods on `DomRect`, but `web-sys` only implements these on [`DomRectReadOnly`](https://docs.rs/web-sys/latest/web_sys/struct.DomRectReadOnly.html) (which is correct according to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/DOMRectReadOnly)). These methods should also be defined on [`DomRect`](https://docs.rs/web-sys/latest/web_sys/struct.DomRect.html).

### Steps to Reproduce

See disparity between documentation for [`DomRect`](https://docs.rs/web-sys/latest/web_sys/struct.DomRect.html) in `web-sys` and [`DomRect`](https://developer.mozilla.org/en-US/docs/Web/API/DOMRect) on MDN. The aforementioned methods are defined on MDN, but not in `web-sys`.

### Expected Behavior

These methods should be defined on `DomRect` as well as `DomRectReadOnly`.

### Actual Behavior

These methods are not defined.

### Additional Context

This is very minor, and can be trivially circumvented with the following code, since `DomRect` can be converted into `&DomRectReadOnly`:

```rust
// For `bounding: DomRect`
let bounding: &DomRectReadOnly = bounding.as_ref();
```

Side note: thank you once again for `web-sys`, it is *superbly* useful to not have to call out to JS for everything in Rust websites!

**Comment by arctic-hen7** [comment]
Note that I've submitted this as a bug because my understanding is that `web-sys` is meant to exactly mirror the web interfaces defined on MDN. If this is incorrect, my apologies, please reclassify this as a feature request.

**Comment by Liamolucko** [comment]
The methods should be accessible through the [`Deref<Target = DomRectReadOnly>` impl](https://docs.rs/web-sys/latest/web_sys/struct.DomRect.html#deref-methods-DomRectReadOnly) on `DomRect`. Since they're actually methods of `DomRectReadOnly`, though, they're only accessible if the `DomRectReadOnly` feature is enabled, which might be the cause of your issue.

**Comment by arctic-hen7** [comment]
Ah I see! Why are the other methods like `.height()` etc not implemented like this though?

**Comment by Liamolucko** [comment]
> Why are the other methods like `.height()` etc not implemented like this though?

They probably should be, actually, but it'd be a breaking change to change that now. It's a quirk of how `web-sys` gets auto-generated from WebIDL.

The API was generated from this WebIDL:

https://github.com/rustwasm/wasm-bindgen/blob/3da2263038d384e5d3113ea7e9b20d65fec48ee3/crates/web-sys/webidls/enabled/DOMRect.webidl#L13-L36

The properties get re-declared on `DOMRect` to make them settable, which causes the code that generates `web-sys` to generate getters and setters for them directly despite the getters already being present on `DomRectReadOnly`.

**Comment by jonboj** [comment]
Maybe MDN is a little confusing for this. My interpretation of the api, looking at that spec idl referenced in the web-sys idl [idl - DOMRect](https://drafts.fxtf.org/geometry/#DOMRect), there is a separation between parameters into two categories.
Settables [`x, y, width, height`], which has set methods in the api, while [`top, right, bottom, left`] are calculated from the others and read-only. 
`[top = y, right = x + width, bottom = y + height, left = x]` when `width` and `height` are positive. Haven't tried, but think in JS it will fail to set e.g. `DOMRect.top = 220`. So naturally to separate between settable and calculated parameters (read-only), which to me the web-sys api reflects correctly.

**Comment by arctic-hen7** [comment]
@Liamolucko understood, this is probably good to close then, as I said it's a very minor thing.
