### ISSUE TITLE
`strict-macro` checking should be enabled by default

### ISSUE THREAD

**Issue by lukaslihotzki** [rustwasm/wasm-bindgen#3038]
### Describe the Bug

Unapplicable attributes are accepted inside wasm_bindgen `impl` and `extern` blocks.

### Steps to Reproduce

```
#[wasm_bindgen]
pub struct Foo;

#[wasm_bindgen]
impl Foo {
    #[wasm_bindgen(inline_js = "hello world", raw_module = "something.js")]
    pub fn foo() {
    }
}

#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(inline_js = "hello world", raw_module = "something.js")]
    pub fn bar();
}
```

### Expected Behavior

Compile errors in `Foo::foo` and `bar` because the attributes `inline_js` and `raw_module` are not applicable for these items.

### Actual Behavior

These attributes are silently ignored.

**Comment by Liamolucko** [comment]
`wasm-bindgen` already supports checking for this when the `strict-macro` feature is enabled:

```
error: unused #[wasm_bindgen] attribute
 --> src/lib.rs:8:20
  |
8 |     #[wasm_bindgen(inline_js = "hello world", raw_module = "something.js")]
  |                    ^^^^^^^^^

error: unused #[wasm_bindgen] attribute
 --> src/lib.rs:8:47
  |
8 |     #[wasm_bindgen(inline_js = "hello world", raw_module = "something.js")]
  |                                               ^^^^^^^^^^

error: unused #[wasm_bindgen] attribute
  --> src/lib.rs:14:20
   |
14 |     #[wasm_bindgen(inline_js = "hello world", raw_module = "something.js")]
   |                    ^^^^^^^^^

error: unused #[wasm_bindgen] attribute
  --> src/lib.rs:14:47
   |
14 |     #[wasm_bindgen(inline_js = "hello world", raw_module = "something.js")]
   |                                               ^^^^^^^^^^

error: could not compile `wasm-playground` due to 4 previous errors
```

So, perhaps that should be enabled by default? It would be a breaking change to do that, but it could also be argued that any code that does that is mistaken.

To do it non-breakingly, it could be a warning by default instead.

**Comment by lukaslihotzki** [comment]
Can proc_macros warn in stable Rust?

**Comment by lukaslihotzki** [comment]
Anyway, I think the `strict-macro` feature is poor design, because [Cargo features should be additive](https://doc.rust-lang.org/cargo/reference/features.html#feature-unification), and this feature is not. Its sole purpose is to put additional restrictions on user code. This obviously breaks when some crate A uses unapplicable attributes, and crate B enables the `strict-macro` feature. Also, this feature is more useful for developers who do not have a lot of experience with wasm-bindgen, but these developers are unlikely to know this feature.

Therefore, I think strict checking should be always on, and the `strict-macro` feature should be removed (or made an no-op for compatibility). This is also allowed by the [SemVer Compatibility chapter](https://doc.rust-lang.org/cargo/reference/semver.html) of the Cargo book:
> Some changes are marked as "minor", even though they carry the potential risk of breaking a build. This is for situations where the potential is extremely low, and the potentially breaking code is unlikely to be written in idiomatic Rust, or is specifically discouraged from use.

**Comment by lukaslihotzki** [comment]
#2874 is another example of the confusion caused by the current approach.
