### ISSUE TITLE
web-sys WebFont new_with_u8_array takes mutable reference

### ISSUE THREAD

**Issue by namse** [rustwasm/wasm-bindgen#3071]
### Summary

`web-sys` `WebFont` has method `pub fn new_with_u8_array(family: &str, source: &mut [u8]) -> Result<FontFace, JsValue>;`, I'm not sure why it takes source as mutable reference.

https://github.com/rustwasm/wasm-bindgen/blob/e4477293c15df8500330b295cb9624dccb2a063b/crates/web-sys/src/features/gen_FontFace.rs#L188

It should be just reference, isn't it? Is there other reason for mutable reference?

**Comment by Liamolucko** [comment]
`web-sys` is auto-generated from the WebIDL files that specify all of the Web's APIs. The WebIDL for `FontFace`'s constructor only specifies that it takes a `Uint8Array`, which it could theoretically mutate, so `web-sys` plays it safe by using `&mut [u8]`. Of course, `FontFace` doesn't mutate the `Uint8Array`, but other APIs like `crypto.getRandomBytes` do, which would be UB if the argument was `&[u8]`.

For a workaround, you can use the unsafe `Uint8Array::view` and call `FontFace::new_with_array_buffer_view`. Or, if you want a safe version, you can use `Uint8Array::from` instead, which copies the bytes.

**Comment by namse** [comment]
I understood well. Thanks for the good explanation. Let's close the issue.

**Comment by alexcrichton** [comment]
There's also a [maintained list](https://github.com/rustwasm/wasm-bindgen/blob/5c28993bec755386a92d635162cd5a17cad653f5/crates/webidl/src/constants.rs#L41-L92) of APIs which don't mutate their arguments and are safe to use `&[T]` which this could get added to.

**Comment by alexcrichton** [comment]
Sure!
