### ISSUE TITLE
`async main()` support

### ISSUE THREAD

**Issue by daxpedda** [rustwasm/wasm-bindgen#3076]
### Motivation

I think it would be great to support something like this:
```rust
#[wasm_bindgen(start)]
async fn main() { }
```

It would add a bit of quality-of-life to prevent users from having to use weird workarounds. It would also help a bit with cross-platform codebases.

### Proposed Solution

The solution is probably the same as the ones used by [`tokio::main`](https://docs.rs/tokio/1.21.0/tokio/attr.main.html) and [`async_std::main`](https://docs.rs/async-std/1.12.0/async_std/attr.main.html), they usually remove the `async` keyword and insert their code inside the function. I believe the only current limitation of `#[wasm_bindgen(start)]` is that it doesn't remove the `async` keyword.

### Alternatives

- Stick with what we have now, which works quiet fine.
- Introduce a separate attribute? E.g.: `#[wasm_bindgen(start_async)]`.

### Additional Context

Original issue: https://github.com/rustwasm/wasm-bindgen/issues/1904
PR: https://github.com/rustwasm/wasm-bindgen/pull/1905

I'm happy to do a PR, but wanted to ask if this feature is desired first.
Also some pointers would be great, I briefly looked into it and the architecture around proc-macro handling in `wasm-bindgen` is quite big.

**Comment by hamza1311** [comment]
Is it currently not supported? It seems like #1905 added that

**Comment by hamza1311** [comment]
Oh, that makes sense. 

Checking if the function name is `main` and it returns `()` (only type that `spawn_local` supports) and removing the async keyword sounds good to me.
