### ISSUE TITLE
web_sys::MediaStreamConstraints should not derive(Clone)

### ISSUE THREAD

**Issue by jpgneves** [rustwasm/wasm-bindgen#3085]
### Describe the Bug

In some browsers (at least Firefox 104), invoking `MediaStreamConstraints::clone(&self)` results in another reference to the same underlying object. Therefore, methods which mutate an instance of `MediaStreamConstraints` will also mutate any clones, and vice-versa.

### Steps to Reproduce

```rust
use web_sys::{ConstrainDomStringParameters, MediaStreamConstraints, MediaTrackConstraints};

// 1. Create a new instance of MediaStreamConstraints
let mut a = MediaStreamConstraints::new();

// 2. Clone it
let b = a.clone();

// 3. Invoke a mutating method on either object (e.g. set a constraint).
// 3.1. Create the new constraint
let mut device_id_constraint = ConstrainDomStringParameters::new();
device_id_constraint.exact(&JsValue::from_str("test"));
let mut track_constraints = MediaTrackConstraints::new();
track_constraints.device_id(&device_id_constraint);

// 3.2. Apply the constraint to the original object
a.video(&track_constraints);

// 4. Verify that both objects were modified and contain the constraint.
log::debug!("Original: {a:?}");
log::debug!("Clone: {b:?}");

// The above results in:
// Original: MediaStreamConstraints { obj: Object { obj: JsValue(Object({"video":{"deviceId":{"exact":"test"}}})) } }
// Clone: MediaStreamConstraints { obj: Object { obj: JsValue(Object({"video":{"deviceId":{"exact":"test"}}})) } }
```

### Expected Behavior

`Clone` behaves as expected, resulting in a new copy of a `MediaStreamConstraints` object which can be mutated independently. Alternatively, `MediaStreamConstraints` should not `impl Clone`.

### Actual Behavior

`Clone` results in a copy of a reference that, when mutated, affects all copies of `MediaStreamConstraints`.

**Comment by lukaslihotzki** [comment]
This `clone` behavior is not specific to `MediaStreamConstraints`. It applies to all types representing JS types in web-sys and js-sys. (Actually, all types defined with `#[wasm_bindgen] extern`.) JS types in Rust are just handles, cloning them is like cloning a `Rc<RefCell<…>>`. Just like with `Rc<RefCell<…>>`, cloning is needed in some cases, so these types must `impl Clone`.

**Comment by jpgneves** [comment]
Yeah, absolutely correct now that I think more about it. I'll close this.
