### ISSUE TITLE
Add `is_array()` method to `JsValue`

### ISSUE THREAD

**Issue by mfreeborn** [rustwasm/wasm-bindgen#3086]
### Motivation

In my library tests, I want to assert that a `JsValue` is an `Array`.

### Proposed Solution

Add `JsValue::is_array()` method.

### Alternatives

Do nothing.

### Additional Context

Other such methods are available for ~primitive JS values e.g. `bool`, `object`, even `function`, etc

Would look like:

```rust
fn array_as_js_value() -> wasm_bindgen::JsValue {
    js_sys::Array::new().into()
}

fn test() {
    let val = array_as_js_value();
    assert!(val.is_array());
}
```

**Comment by Liamolucko** [comment]
This seems reasonable enough to add.

The current best way of doing this would be `val.is_instance_of::<js_sys::Array>()`.

**Comment by RReverser** [comment]
Hm, why is this necessary on `JsValue`? Seems like an overkill to add specialized class checks to `JsValue`, it might easily get out of hand if we start doing the same for maps/sets/everything else.

> The current best way of doing this would be `val.is_instance_of::<js_sys::Array>()`.

Actually, the correct way today is `js_sys::Array::is_array(&val)` or `val.has_type::<js_sys::Array>()` (both equivalent to `Array.isArray(val)` in JS), which seems simple enough without a dedicated `JsValue` method too?

**Comment by RReverser** [comment]
To clarify - I'm just concerned and think we should have a higher bar for adding "core" methods to JsValue, as APIs are very hard to remove once added; especially so where something is possible and easy via existing, generic, methods, instead of adding dedicated methods for separate types.

**Comment by hamza1311** [comment]
I think having API for things that are syntactically part of JS is fine. `[element]` exists so an is_array method is fine. But it has no equivalent for Map or Set, so we shouldn't add methods for those

That sounds like a good compromise to me

**Comment by Liamolucko** [comment]
> > The current best way of doing this would be `val.is_instance_of::<js_sys::Array>()`.
> 
> 
> 
> Actually, the correct way today is `js_sys::Array::is_array(&val)` or `val.has_type::<js_sys::Array>()` (both equivalent to `Array.isArray(val)` in JS)

Oops, I meant to say `has_type`; I got the two confused.

> I think having API for things that are syntactically part of JS is fine. `[element]` exists so an is_array method is fine.

That was my thinking as well.
