### ISSUE TITLE
Add the OpenSSF Scorecard GitHub Action

### ISSUE THREAD

**Issue by gabibguti** [rustwasm/wasm-bindgen#3090]
### Motivation

Hello, I'm working on behalf of Google and the [Open Source Security Foundation][ossf] to help essential open-source projects improve their supply-chain security. Given wasm-bindgen importance to integrate Rust Wasm modules and JavaScript, we want to offer our support to improve the project's security posture.

### Proposed Solution

Would you consider adopting an OpenSSF tool called [Scorecards][sc]? Scorecards runs dozens of automated security checks to help maintainers better understand their project's supply-chain security posture. It is developed by the OpenSSF, [in partnership with GitHub][sc-blog].

I see wasm-bindgen already follows security best practices, such as release signing and CI testing. Adding Scorecards could help encourage other best practices, such as pinning dependencies and using fuzzing tools. It also checks for actions that increase risk, such as not setting least privilege permissions on tokens and using dangerous code patterns on GitHub Workflows. Overall, it could be a great tool to guide security decisions and show off your current hard work on security practices.

Would you be interested in a PR which adds this Action? Optionally, it can also publish your results to the OpenSSF REST API, which allows a [badge][badge] with the project's score to be added to its README.

### Additional Context

The [Scorecard GitHub Action](https://github.com/ossf/scorecard-action) is very lightweight and runs on each change to the repository's main branch. The results of its checks are available on to the project's [security dashboard](https://github.com/rustwasm/wasm-bindgen/security), and include suggestions on how to solve any issues (see examples below). The Action does not run or interact with any workflows, but merely parses them to identify possible vulnerabilities. Over 1600 projects have added the action already.

![Code scanning dashboard with multiple alerts, including Code-Review and Token-Permissions][img-security]

![Detail of a Token-Permissions alert, indicating the specific file and remediation steps][img-detail]

[badge]: https://openssf.org/blog/2022/09/08/show-off-your-security-score-announcing-scorecards-badges/
[ossf]: https://openssf.org/
[sc]: https://github.com/ossf/scorecard
[sc-blog]: https://github.blog/2022-01-19-reducing-security-risk-oss-actions-opensff-scorecards-v4/
[sc-gha]: https://github.com/ossf/scorecard-action
[img-security]: https://user-images.githubusercontent.com/15221358/190184391-84ca1844-259a-4b3b-9c86-74adadbea7f1.png
[img-detail]: https://user-images.githubusercontent.com/15221358/190184600-ee8d3b39-077e-416a-8711-1b5fb01cf0b3.png

**Comment by gabibguti** [comment]
Hey! Frindly ping here! If you'd like to try out Scorecard security tool, let me know! Otherwise we can close this as not planned for now :)

**Comment by daxpedda** [comment]
Personally I am in favor.

@hamza1311, @Liamolucko, what do you think?
Note: I found the relevant checks here: https://github.com/ossf/scorecard?tab=readme-ov-file#scorecard-checks

**Comment by hamza1311** [comment]
I'm in favor as well. We should add as many security checks as possible to return the chance of something bad slipping through.

@gabibguti, would like to send a PR? Happy to look at one

**Comment by gabibguti** [comment]
Sure!
