### ISSUE TITLE
How to use window.navigator.getBattery in wasm-bindgen? 

### ISSUE THREAD

**Issue by linzhipeng98** [rustwasm/wasm-bindgen#3094]
```
let navigator = web_sys::window().unwrap().navigator();
navigator.get_battery() // not exist get_battery
```

**Comment by jonboj** [comment]
Smart workaround. In web-sys api it looks like [web-sys BatteryManager](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.BatteryManager.html#) is declared, but not `navigator.get_battery()`. So worth trying to downcast to web-sys version of `BatteryManager`. Hence the workaround will be few lines.

**Comment by linzhipeng98** [comment]
> Support for that API hasn't been added to `web-sys` yet.
> 
> As a workaround, you can import it manually:
> 
> ```rust
> #[wasm_bindgen]
> extern "C" {
>     #[wasm_bindgen(js_namespace = navigator, js_name = getBattery)]
>     fn get_battery() -> js_sys::Promise;
> 
>     // You'll probably also want this to downcast the `Promise`'s result to:
>     type BatteryManager;
>     #[wasm_bindgen(method, getter)]
>     fn charging(this: &BatteryManager) -> bool;
>     // other getters/setters...
> }
> ```

Thank you!

**Comment by linzhipeng98** [comment]
@Liamolucko Thank you!
