### ISSUE TITLE
Missing methods for `AudioParamMap`

### ISSUE THREAD

**Issue by skyf0l** [rustwasm/wasm-bindgen#3097]
### Summary

I would like to use the `AudioParamMap` ([gen_AudioParamMap.rs](https://github.com/rustwasm/wasm-bindgen/blob/main/crates/web-sys/src/features/gen_AudioParamMap.rs)) object but it does not seem to implement any methods, is this normal?

### Additional Details

Some methods are missing like: `get`, `has`, `keys`, `values`, `entries` and others... (See the JavaScript object just bellow.)

![image](https://user-images.githubusercontent.com/59019720/193473219-ded2928a-7319-4631-8cc2-e510cf52ed58.png)

Currently, I can still get `AudioParam`s and names by casting the `AudioParamMap` into a simple `js_sys::Object` but it looks ugly...

```rust
// node: web_sys::AudioWorkletNode

let param_map = node.parameters().unwrap();
let param_map_obj = js_sys::Object::from_entries(&param_map).unwrap();

let params = js_sys::Object::values(&param_map_obj);
let param_names = js_sys::Object::keys(&param_map_obj);
```

**Comment by Liamolucko** [comment]
I believe this is caused by #2618.
