### ISSUE TITLE
Invalid JavaScript generated when property name contains a dash

### ISSUE THREAD

**Issue by manuelVo** [rustwasm/wasm-bindgen#3113]
### Describe the Bug
When generating a getter for a JavaScript object, wasm-bindgen generates invalid JavaScript when the property name contains a dash.

### Steps to Reproduce
Generate a binding to a javascript object like this:
```rust
#[wasm_bindgen]
extern "C" {
  pub type MyType;
  
  #[wasm_bindgen(method, getter, js_name="with-dash")]
  fn with_dash(this: &MyType) -> i64;
}
```
This will cause wasm_bindgen to generate
```javascript
const ret = getObject(arg0).with-dash;
```
Which is invalid JavaScript, resulting in a runtime error when `MyType::with_dash` is invoked.

### Expected Behavior
When the js_name contains a dash, wasm_bindgen could fall back to generating `getObject(arg0)["with-dash"]` instead.

**Comment by filonik** [comment]
Is there any downside to always emitting `getObject(arg0)["${property}"]`?
