### ISSUE TITLE
How to operate BigInt64Array with Atomics

### ISSUE THREAD

**Issue by daidr** [rustwasm/wasm-bindgen#3121]
### Summary

I want to operate BigInt64Array with Atomics, but i found that the function Atomics.add only allows i32

When passing in the i32 type, it generates error like this:
![image](https://user-images.githubusercontent.com/18638914/197374511-2201e127-c66c-49e2-8415-08e96117418f.png)

### Additional Details

some codes:

Rust:
```rust
#[wasm_bindgen]
pub fn test(origin_shared_buf: js_sys::SharedArrayBuffer) {
    let typedarray = js_sys::BigInt64Array::new(&origin_shared_buf);
    js_sys::Atomics::Add(&typedarray, 0, 1000).unwrap();
}
```

Javascript:
```js
const originSharedBuf = new SharedArrayBuffer(8);

test(originSharedBuf)
```

**Comment by Liamolucko** [comment]
Right, that's an oversight. Some kind of `Atomics.add64` or `Atomics.add_bigint` will have to be added which takes `i64` instead (and the same for any similar functions in `Atomics`).
