### ISSUE TITLE
How to use ```this``` in wasm-bindgen?

### ISSUE THREAD

**Issue by linzhipeng98** [rustwasm/wasm-bindgen#3125]
In javascript，I will override prototype method like this:

```javascript
const originOpen = window.XMLHttpRequest.prototype.open
window.XMLHttpRequest.prototype.open = function (arguments) {
  this.array = []
  this.array.push(something)
  originOpen.apply(this, arguments)
}

// use XMLHttpRequest
// property array will define in the instance instead of prototype
const xhr = new XMLHttpRequest()
xhr.open(arguments)
```

I would like to do the same in wasm-bindgen:

```rust
use js_sys::{Reflect, Function};
use wasm_bindgen::{prelude::Closure, JsValue};
use web_sys::window;

let window = window().unwrap();
let request = Reflect::get(&window, &JsValue::from("XMLHttpRequest")).unwrap();
let prototype = Reflect::get(&request, &JsValue::from("prototype")).unwrap();
let origin_open = Reflect::get(&prototype, &JsValue::from("open")).unwrap();

let open = Closure::<dyn Fn()>::new(|| {
    // how to access this ?
    origin_open.unchecked_into::<Function>().apply(this, args)
});

Reflect::set(&prototype, &JsValue::from("open"), open.as_ref())

```

How to use ```this``` in wasm-bindgen?

**Comment by jonboj** [comment]
Just of curiosity. What is the background for using `Reflect` to setup call of `XMLHttpRequest.open`, instead of using one of the `open` methods in the `web-sys` api e.g. [XmlHttpRequest.open](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.XmlHttpRequest.html#method.open)?

**Comment by linzhipeng98** [comment]
@jonboj Hi, like the javascript code above, i want to add some custom properties in xhr instance when the ```open``` method called. Use ```web-sys``` api seems can‘t to do this.

**Comment by jonboj** [comment]
@linzhipeng98 Ok. The different types of JS argument combinations [MDN XMLHttpRequest.open - Syntax](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/open#syntax) are mapped to corresponding methods in `web-sys` api, e.g. `open(method, url, async, user, password)` => [XmlHttpRequest.open_with_async_and_user_and_password](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.XmlHttpRequest.html#method.open_with_async_and_user_and_password).

So maybe possible to obtain similiar with the `web-sys` api.
