### ISSUE TITLE
Why does `.then()` method insist Closure should return `()`?

### ISSUE THREAD

**Issue by cowile** [rustwasm/wasm-bindgen#3131]
### Summary

I am trying to compile the following snippet:

```
let result = window.fetch_with_request(&request)
    .then(&Closure::new(|resp| Response::from(resp).json().unwrap()))
    ...[further method chaining]
```
which leads to the following error:

```
error[E0271]: expected `[closure@src/lib.rs:45:29: 45:35]` to be a closure that returns `()`, but it returns `js_sys::Promise`
   --> src/lib.rs:45:29
    |
45  |         .then(&Closure::new(|resp| Response::from(resp).json().unwrap()));
    |                ------------ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `()`, found struct `js_sys::Promise`
    |                |
    |                required by a bound introduced by this call
    |
    = note: required for `[closure@src/lib.rs:45:29: 45:35]` to implement `IntoWasmClosure<dyn FnMut(JsValue)>`
note: required by a bound in `Closure::<T>::new`
   --> /home/cwl/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-0.2.83/src/closure.rs:271:12
    |
271 |         F: IntoWasmClosure<T> + 'static,
    |            ^^^^^^^^^^^^^^^^^^ required by this bound in `Closure::<T>::new`
```

How is `.then()` supposed to be used if the Closure is needs to return `()`?

### Additional Details

I'd like to be able to take full advantage of asynchronous JS APIs, but every example in the wasm-bindgen [guide](https://rustwasm.github.io/docs/wasm-bindgen/examples/fetch.html) simply `.await`s at every step, destroying the possible advantage of having anything be asynchronous.

Versions:
wasm-bindgen: 0.2.83 1ecc6299
rustc: rustc 1.66.0-nightly (bf15a9e52 2022-10-14)

**Comment by Liamolucko** [comment]
This is a duplicate of #3111.

> I'd like to be able to take full advantage of asynchronous JS APIs, but every example in the wasm-bindgen [guide](https://rustwasm.github.io/docs/wasm-bindgen/examples/fetch.html) simply `.await`s at every step, destroying the possible advantage of having anything be asynchronous.

What do you mean? Using `.await` is still asynchronous, it pauses the program there and allows other stuff to happen while waiting (the same as `await` in JS). If you mean that you want to let the promise run in the background while continuing synchronously, you can use `wasm_bindgen_futures::spawn_local` to do that.

The signature being wrong is still a problem, to be clear, I'm just pointing out that using `.await` should also work fine.

**Comment by cowile** [comment]
Thanks for answering. I had misunderstood how `.await` works, so I am not missing out on any performance after all.

In that case, the main problem is simply ergonomic due to the wrong signature preventing an idiomatic way of handling JS promises.
