### ISSUE TITLE
How to put new api if html spec has no idl?

### ISSUE THREAD

**Issue by namse** [rustwasm/wasm-bindgen#3140]
### Summary
I tried to put createImageBitmap in wasm-bindgen but there was no idl spec for createImageBitmap api.
https://html.spec.whatwg.org/multipage/imagebitmap-and-animations.html#dom-createimagebitmap

In this case, How can I make a PR putting createImageBitmap?

**Comment by Liamolucko** [comment]
There is, it's just not next to the definition of `createImageBitmap`: https://html.spec.whatwg.org/multipage/webappapis.html#windoworworkerglobalscope-mixin:dom-createimagebitmap

**Comment by namse** [comment]
OH.... holy... Thank you a lot!
