### ISSUE TITLE
Cached Uint32 memory remains uninitialized

### ISSUE THREAD

**Issue by Oliver-makes-code** [rustwasm/wasm-bindgen#3141]
### Describe the Bug

The generated JS file creates helpers for `cachedUint32Memory`, but never initializes it.
See denoland/wasmbuild/issues/61

### Steps to Reproduce

1. Run the generator, with a JS function that returns an array
2. Call that JS function from Rust

[Repository showcasing](https://github.com/Oliver-makes-code/WasOS)

### Expected Behavior

The function runs without throwing a TypeError

### Actual Behavior

Throws `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'byteLength')`

**Comment by 0f-0b** [comment]
`wasm-bindgen --target deno` and `wasm-bindgen --target web` do initialize all memory views as needed. `wasmbuild`, however, appears to always only assign values to `cachedInt32Memory0` and `cachedUint8Memory0`.

**Comment by Oliver-makes-code** [comment]
Wasmbuild is using the direct output afaik, though that was only from a quick skim of the code

**Comment by Oliver-makes-code** [comment]
Hm, it looks like the issue is fixed in the latest commits of [denoland/wasmbuild](https://github.com/denoland/wasmbuild), but they just haven't created a release yet

**Comment by 0f-0b** [comment]
> Wasmbuild is using the direct output afaik, though that was only from a quick skim of the code

Ah, you are right. The upgrade to wasm-bindgen in denoland/wasmbuild#52 made [the code I was looking at](https://github.com/denoland/wasmbuild/blob/764e4610704eb03a9bac4b123ecdc5b37349dfd0/lib/pre_build.ts#L307-L308) redundant.
