### ISSUE TITLE
Link in documentation intro

### ISSUE THREAD

**Issue by ivanschuetz** [rustwasm/wasm-bindgen#3143]
I was just going through the [documentation](https://rustwasm.github.io/docs/wasm-bindgen/):

> The wasm-bindgen tool is sort of half polyfill for features like the [host bindings proposal](https://github.com/WebAssembly/host-bindings) and half features for empowering high-level interactions between JS and wasm-compiled code (currently mostly from Rust).

The host-bindings proposal seems to be [inactive](https://github.com/WebAssembly/interface-types), and it links to the [component model repo](https://github.com/WebAssembly/component-model). 

Should the documentation be updated (at least to explain why the proposal is inactive)?

**Comment by ydirson** [comment]
The original https://github.com/WebAssembly/host-bindings link in the doc is indeed redirected to https://github.com/WebAssembly/interface-types, which is the inactive one. There the "explainer" sheet says work moved to https://github.com/WebAssembly/component-model.
It is really unclear what the book intends to link to.

**Comment by daxpedda** [comment]
Updating the documentation to point to the component model proposal would be nice indeed.
