### ISSUE TITLE
Add XrInputSource::hand

### ISSUE THREAD

**Issue by rodrigocam** [rustwasm/wasm-bindgen#3148]
### Motivation

`XRInputSource` has a `hand` property which is not exposed by `web-sys`

### Proposed Solution

Add `XrInputSource::hand`

### Alternatives

Perhaps there is some context I am unaware of for why it isn't/shouldn't be added.

### Additional Context

[MDN Docs for the property](https://developer.mozilla.org/en-US/docs/Web/API/XRInputSource/hand)

**Comment by jonboj** [comment]
Hi, In MDN page above at section [Browser compatibility](https://developer.mozilla.org/en-US/docs/Web/API/XRInputSource/hand#browser_compatibility), none of the browsers support the `hand` feature.
From [Chrome Status - hand](https://chromestatus.com/feature/5719474055413760) specification hasn't completed yet, likely background for why isn't exposed.

**Comment by rodrigocam** [comment]
Oh yeah, I didn't see that none of the browser already support it.
