### ISSUE TITLE
Returning `Result<Vec<u8>, JsError>` from an `async` function doesn't work

### ISSUE THREAD

**Issue by nasso** [rustwasm/wasm-bindgen#3155]
### Describe the Bug

The following compiles:

```rust
#[wasm_bindgen]
pub fn foo() -> Result<Vec<u8>, js_sys::Error> {
  unimplemented!()
}
```

While the following does not:

```rust
#[wasm_bindgen]
pub async fn foo() -> Result<Vec<u8>, js_sys::Error> {
  unimplemented!()
}
```

### Steps to Reproduce

1. Copy and paste the second snippet above
2. `cargo check`
3. See error

### Expected Behavior

Whatever works without `async` works the same with `async`.

### Actual Behavior

Sometimes, it does not 😔.

### Additional Context

Not the first instance of this issue (see #3059).

**Comment by Teebor-Choka** [comment]
This issue is unpleasant. Any chance of extending to functionality for `async` to match the sync behavior?

**Comment by daxpedda** [comment]
I didn't look into it, but I don't think this requires any design work, so PRs are welcome.

**Comment by Teebor-Choka** [comment]
I created a custom type to wrap around the Vec. Was asking about future prospects.

**Comment by daxpedda** [comment]
I'm not aware of any current maintainers interested in working on something like this.

**Comment by benma** [comment]
Fyi I ran into the same and would welcome a fix. For `String` it works both with async fn and regular fn, but not with Vec<u8>.

**Comment by Solo-steven** [comment]
Hi @daxpedda I would like to work on this bug if no one is working on it! Thanks ~

**Comment by daxpedda** [comment]
Go right ahead :smiley:!

**Comment by Solo-steven** [comment]
Hi @daxpedda this currently solution I can think about is like 
```rust
impl<T> From<Vec<T>> for JsValue {
    #[inline]
    fn from(s: Vec<T>) -> JsValue {
        JsValue::from(s.as_ptr() as usize)
    }
}
```
but this would  first convert the raw pointer into f64 , then pass it to the JS function  which adds it to heap
```
function addHeapObject(obj) {
    if (heap_next === heap.length) heap.push(heap.length + 1);
    const idx = heap_next;
    heap_next = heap[idx];

    heap[idx] = obj;
    return idx;
}
```
I do not know if the behavior is correct or not,  since it just adds the address of vec to the JS heap, but in `wasm-bindgen` guide, it seems to be ok to convert type into a number, because it just abi ? Any help would be very appreciate !

**Comment by daxpedda** [comment]
Sorry @Solo-steven, poor communication on our part here ...

**Comment by Solo-steven** [comment]
It is OK, and thanks @Liamolucko for giving me the link to related PR so that I can learn from it! thanks
