### ISSUE TITLE
performance.measureUserAgentSpecificMemory

### ISSUE THREAD

**Issue by emilk** [rustwasm/wasm-bindgen#3159]
### Motivation

[`window.performance.memory`](https://developer.mozilla.org/en-US/docs/Web/API/Performance/memory) in an API for accessing the memory use of JavaScript (and by extension, wasm).

Example JS: `window.performance.memory.usedJSHeapSize`

### Proposed Solution

Add a `Memory` feature flag to expose `window.performance.memory` with three fields:

* `js_heap_size_limit`
* `total_js_heap_size`
* `used_js_heap_size`

### Alternatives

WASM apps can install a custom `#[global_allocator]` that does its own bookkeeping of amount of RAM used.

### Additional Context

Knowing the memory used by a WASM application is useful for it to know whether or not to try free up some memory.

**Comment by Liamolucko** [comment]
`performance.memory` is a non-standard, deprecated API, at least [according to MDN](https://developer.mozilla.org/en-US/docs/Web/API/Performance/memory). [`performance.measureUserAgentSpecificMemory`](https://developer.mozilla.org/en-US/docs/Web/API/Performance/measureUserAgentSpecificMemory#specifications) seems to be the more modern version, with an actual spec (although not actually standardised yet). Would adding (unstable) support for that instead be acceptable?

**Comment by emilk** [comment]
Yes, [performance.measureUserAgentSpecificMemory](https://developer.mozilla.org/en-US/docs/Web/API/Performance/measureUserAgentSpecificMemory#specifications) sounds perfect!
