### ISSUE TITLE
web_sys::Window.document().document_element().client_width() reporting incorrect width on initial load and when changing width in dev tools firefox

### ISSUE THREAD

**Issue by kappaisagreekletter** [rustwasm/wasm-bindgen#3166]
I'm trying to port my current site to rust using yew and trunk. I need the window width because I am rendering things differently for mobile, tablet, and pc.

I am sending the width to a child that prints that width in a div while also printing the width in the component where I get the width. They were the same, so I then checked what the get_viewport_width() function returns. This is where I discovered the problem:

- on pc width is correct on load and updates correctly as I resize the window
- on firefox dev tools the width is _wrong_ on load and with all methods of changing the width **except** when dragging the window, then it is correct
- on mobile (android chrome, ddg, firefox) it shows **980** for the width (980px). My phone is around 350px, so that is very wrong

note that on firefox dev tools on pc I also get _980px_ for the client width

```rust
use gloo_console::log;
use gloo_timers::future::TimeoutFuture;
use wasm_bindgen_futures::spawn_local;
use yew::prelude::*;

mod pages;
use pages::home_page::Home;

#[function_component(App)]
pub fn app() -> html {
    let width = use_state(|| get_viewport_width());
    let w2 = width.clone();

    // set width state when the screenwidth changes to force a rerender
    use_effect_with_deps(
        move |_| {
            spawn_local(async move {
                loop {
                    TimeoutFuture::new(100).await;
                    log!(*w2);
                    if *w2 != get_viewport_width() {
                        w2.set(get_viewport_width());
                    }
                }
            });
            // cleanup
            || ()
        },
        (), // dependents
    );

    html!(
        <div class="App">
            <div style="z-index: 10000; position: fixed; top: 10px; left: 10px;">{*width}</div>
            <Home width={*width} />
        </div>
    )
}

#[derive(Clone, Properties, PartialEq)]
pub struct Width {
    width: i32,
}

// get the width of the viewport
pub fn get_viewport_width() -> i32 {
    web_sys::window()
        .expect("There should be a window")
        .document()
        .expect("There should be a document attached to the window")
        .document_element()
        .expect("There should be a document element for the document")
        .client_width()

		// I get the same problem with this implementation:
        // web_sys::window()
        //   .unwrap()
        //   .inner_width()
        //   .unwrap()
        //   .into_serde()
        //   .unwrap()

}

```

Is there a different way to get the width? How can I fix this?

**Comment by Liamolucko** [comment]
You're probably missing this line in your HTML:

```html
<meta name="viewport" content="width=device-width">
```

Without it, the page defaults to being extremely zoomed out on mobile (I don't remember exactly why), and `clientWidth` is then correctly reporting that the page is 980px wide due to being zoomed out.

Also, this issue isn't anything to do with `wasm-bindgen`, it's just how the underlying web APIs work.

**Comment by kappaisagreekletter** [comment]
Oops, it seems you are correct. I forgot to add that to my HTML.
Thanks.
