### ISSUE TITLE
Closure gets called after it's dropped

### ISSUE THREAD

**Issue by obsidianical** [rustwasm/wasm-bindgen#3178]
### Describe the Bug

A closure passed into a promise that got dropped on the rust side gets called anyway.

### Steps to Reproduce

1. Use this code as an `ondrop` handler.
```rs
    let drop_handler = { 
        move |e: DragEvent| {
            let c = Closure::new(|v| {
                debug!("handler called! v: {:#?}", v);
            });
            e.prevent_default();
            debug!("Drop ev: {:#?}", 
                e.data_transfer()
                    .unwrap()
                    .files()
                    .unwrap()
                    .item(0)
                    .unwrap()
                    .text()
                    .then(&c)
            );
        }
    };
```
2. Drop a file there

### Expected Behavior

The compiler doesn't allow this code to compile, as only a reference to `c` is passed to `.then()`, the value behind which being dropped immediately after. The closure gets called anyway.

### Actual Behavior

The code compiles, leading to the error message below.

```
Uncaught (in promise) Error: closure invoked recursively or destroyed already
```

### Additional Context

This is happening inside of a `yew` project, but I suspect this is an issue with `web-sys`.

**Comment by Liamolucko** [comment]
This is expected. It'd be impossible to enforce at compile time that JS never calls a closure after it's dropped, since there's nothing stopping JS from just holding onto it for the rest of the program. So, this is the best we can do, just throwing an error if the closure gets mistakenly called after being dropped.
