### ISSUE TITLE
How to setup a shared memory by default?

### ISSUE THREAD

**Issue by qdwang** [rustwasm/wasm-bindgen#3190]
### Summary

I'd like to send `wasm.memory` from a web worker to the main thread without any memory copy. 

But cannot find a way to do it. 

By default, the `wasm.memory` is not a shared one, because the `wasm.memory.buffer` is `ArrayBuffer`. 

Is there any way to turn `wasm.memory.buffer` to `SharedArrayBuffer` in `wasm-bindgen`?

**Comment by qdwang** [comment]
@Liamolucko 

Thanks. It works. 
But is it possible for stable rust to do this? Like just to import a javascript generated shared `WebAssembly.Memory` object to the module?

**Comment by Wulfheart** [comment]
I would be also interested in this answer.

**Comment by daxpedda** [comment]
Now that I'm more familiar with the spec: this is impossible. The threads proposal specifically forbids using `SharedArrayBuffer` without a `shared` `memory`. A `shared` `memory` is only valid when enabling the `atomics` target feature.
