### ISSUE TITLE
Support returning Rust struct from JS

### ISSUE THREAD

**Issue by Procrat** [rustwasm/wasm-bindgen#320]
Should it be possible to return (a pointer to) a Rust struct from Javascript? I noticed that trying to compile this, fails:

```rust
#![feature(proc_macro, wasm_custom_section, wasm_import_module)]

extern crate wasm_bindgen;

use wasm_bindgen::prelude::*;

#[wasm_bindgen]
extern {
    pub fn f(x: MyStruct) -> MyStruct;
}

#[wasm_bindgen]
pub struct MyStruct;
```

In general, I see three ways to cross the FFI boundary between Rust and JS:
- Serialise data structures when passing the boundary
- Construct, manipulate, and query all data structures in JS by calling JS functions from Rust/wasm
- Construct, manipulate, and query all data structures in Rust/wasm by calling Rust/wasm functions from JS

It looks like there is support for the first option (with `from_serde` and `into_serde`) and there is a lot of stuff happing for the second option (like #275). Seeing that the example above isn't possible (yet?), makes me think that the third approach isn't a good idea perhaps? Or at least suboptimal to the other approaches?

Thank you for your patience if this is a trivial question or something, and thank you for the awesome work you have put into this project!

**Comment by fitzgen** [comment]
For info about how data is passed across the boundary, see https://rustwasm.github.io/wasm-bindgen/design.html and https://github.com/rustwasm/wasm-bindgen/blob/master/src/convert.rs#L16-L76

In general, we try to avoid serialization unless explicitly requested.

Agreed that your example should work. We should fix whatever needs fixing there.

**Comment by jtmorrisbytes** [comment]
Above links are outdated

**Comment by Procrat** [comment]
@jtmorrisbytes: https://rustwasm.github.io/docs/wasm-bindgen/contributing/design/index.html
