### ISSUE TITLE
How can reqwest::ClientBuilder.resolve used with wasm-bindgen?

### ISSUE THREAD

**Issue by thesved** [rustwasm/wasm-bindgen#3202]
### Summary

reqwest::ClientBuilder has a `resolve` method https://github.com/seanmonstar/reqwest/pull/1277 that enables custom DNS resolution, that resolves the domain to an IP without making DNS queries, and it is pretty simple, it can be used like:

```rust
 let client = reqwest::ClientBuilder::new()
    .resolve("cloudflare-dns.com", "1.1.1.1:443".parse().unwrap())
    .build()?;
```

BUT when I try to use it with `wasm-bindgen`, it throws an error
```
  |         .resolve("cloudflare-dns.com", "1.1.1.1:443".parse().unwrap())
  |          ^^^^^^^ method not found in `ClientBuilder`
```

My question is:
1) is it possible to use reqwest's `resolve` method with wasm-bindgen?
2) if not, is there another way to define the IP address to which I want to make an HTTPS request for a specified hostname?

eg.
- CURL also has a `--resolve` parameter
- `node-fetch` can also have a custom DNS resolver agent
- but V8 `fetch` doesn't have any option to do this

**Comment by Liamolucko** [comment]
> 1. is it possible to use reqwest's `resolve` method with wasm-bindgen?

No, that's only supported when running natively.

> 2. if not, is there another way to define the IP address to which I want to make an HTTPS request for a specified hostname?

Not that I'm aware of. That's more of a question about the web in general, though.

**Comment by thesved** [comment]
Thank you, you have just saved me a long weekend of trying to figure this
out 😅 I really appreciate your expertise and willingness to assist. Thanks
again!
