### ISSUE TITLE
Use queueMicrotask instead of Promise.then in wasm-bindgen-futures

### ISSUE THREAD

**Issue by hamza1311** [rustwasm/wasm-bindgen#3203]
This allows us to avoid issues that may arise when using Promises to queue microtasks. This explained well in [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API/Microtask_guide#enqueueing_microtasks):

> By introducing queueMicrotask(), the quirks that arise when sneaking in using promises to create microtasks can be avoided. For instance, when using promises to create microtasks, exceptions thrown by the callback are reported as rejected promises rather than being reported as standard exceptions. Also, creating and destroying promises takes additional overhead both in terms of time and memory that a function which properly enqueues microtasks avoids.

Also see

https://github.com/rustwasm/wasm-bindgen/blob/eebb201ac2310e2ca0319fbed51a9243cc350a64/crates/futures/src/queue.rs#L51-L53

Also see: #2392

**Comment by snOm3ad** [comment]
This has been fixed by #3611
