### ISSUE TITLE
lack of StorageManager.getDirectory()

### ISSUE THREAD

**Issue by XLearner** [rustwasm/wasm-bindgen#3211]
### Describe the Bug

I wanted to use the function `navigator.storage.getDirectory()`, but I found there has not the function existing on `StorageManager` feature. 
And here is the description of StorageManager: 
https://developer.mozilla.org/en-US/docs/Web/API/StorageManager

### Steps to Reproduce

1. import feature `StorageManager` on `cargo.toml`;
2. we can get a StorageManager instance with `window().unwrap().navigator().storage`;
3. you will find there is not hint about `getDirectory`;

### Expected Behavior

I can invoke `storage.getDirectory()` successfully and will not enter `catch` callback.
![image](https://user-images.githubusercontent.com/26158725/208629498-3704d709-9cd0-4b3a-9fed-7e4d43a66fef.png)

### Actual Behavior

I set the error callback and output the error message.
![image](https://user-images.githubusercontent.com/26158725/208630120-3c6d352e-8328-4d47-9d84-61bccdc53be7.png)

**Comment by Liamolucko** [comment]
That API hasn't been added to `web-sys` yet. It should be added soon. As for why you're getting the error when calling it manually, it's because you're setting the reciever (the value you're calling the method on) to undefined when calling it. You need to replace `.call0(&JsValue::undefined())` with `.call0(&storage)`.

**Comment by XLearner** [comment]
您好，你发送的信息我已成功接收，我会尽快回复您。Lambert Yim

**Comment by XLearner** [comment]
> That API hasn't been added to `web-sys` yet. It should be added soon. As for why you're getting the error when calling it manually, it's because you're setting the reciever (the value you're calling the method on) to undefined when calling it. You need to replace `.call0(&JsValue::undefined())` with `.call0(&storage)`.

Thanks, it works. I can use this temporarily. Looking forward to your supplement.
