### ISSUE TITLE
Cannot inherit from structs created via `#[wasm_bindgen]` attribute as expected

### ISSUE THREAD

**Issue by TomzBench** [rustwasm/wasm-bindgen#3213]
### Describe the Bug
If I create a struct in rust and export the struct via `#[wasm_bindgen]` attribute, and if I then inherit this struct from javascript space, my Javascript derived class will only be recognized as the parent class. For example, if I override any methods of the parent class, only the parent class methods are called. Also, `obj instanceof DerivedClass == false` and `obj instance ParentClass == true`, where i would expect both `instanceof` conditions to be true. 

### Steps to Reproduce

1. Create a struct `A` in rust and export the struct via `#[wasm_bindgen]`

2. In javasript, create a class `B` that inherits the Rust struct `A`

3. Create an instance of your derived javascript class. `let obj = new B()`

4. test `expect(obj instanceof B).toBe(true)`

### Expected Behavior

Step 4 should pass

### Actual Behavior

Step 4 will fail (obj is not an instance of B)

### Additional Context

Why this matters is because when I override any methods of the Base class, the override methods are not being called, but instead only the base methods are being called.

**Comment by snOm3ad** [comment]
The problem lies in the implementation of the constructor of the `wasm-bindgen` Parent class specifically the `__wrap` implementation currently overrides the prototype of `this` to be equal to the parent class prototype:

```js
export class Parent {
  static __wrap(ptr) {
     ptr = ptr >>> 0;
     const obj = Object.create(TestClass.prototype);
     obj.__wbg_ptr = ptr;

     return obj;
  }
  constructor() {
     const ret = wasm.testclass_new();
     return TestClass.__wrap(ret);
  }
}
```

So if you want inheritance to work, you'll need to reset the prototype back in the child class constructor.

```js
class Child extends Parent {
  constructor() {
    super();
    Object.setPrototypeOf(this, ChildTestClass.prototype);
  }
}
```

After doing this you'll see that `obj instanceof Child` and `obj instanceof Parent` output `true` and methods correctly called.

**Comment by TomzBench** [comment]
Good to know!  maybe an idea to put this in the docs. I feel like this pattern is pretty useful if you want to massage some of the wasm binding layer with a more idiomatic javascript api, you can wrap your wasm imports like this and provide some glue

**Comment by daxpedda** [comment]
@snOm3ad by any chance: do you know why this was done like this in the first place?

**Comment by Liamolucko** [comment]
> @snOm3ad by any chance: do you know why this was done like this in the first place?

I did some digging and it looks like this actually used to work prior to #1594. `__wrap` still existed, but it was only used for functions that returned a Rust struct, not constructors. For example, this Rust:

```rs
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub struct Foo(&'static str);

#[wasm_bindgen]
impl Foo {
    #[wasm_bindgen(constructor)]
    pub fn new() -> Self {
        Self("made with constructor")
    }

    pub fn builder() -> Self {
        Self("made with builder")
    }
}
```

produced this JS:

```js
export class Foo {
    static __wrap(ptr) {
        const obj = Object.create(Foo.prototype);
        obj.ptr = ptr;

        return obj;
    }

    free() {
        const ptr = this.ptr;
        this.ptr = 0;

        wasm.__wbg_foo_free(ptr);
    }

    constructor() {
        this.ptr = wasm.foo_new();
    }

    static builder() {
        return Foo.__wrap(wasm.foo_builder());
    }
}
```

The constructors were probably just changed to use `__wrap` as well for simplicity. It shouldn't be too hard to change this back.

Another unfortunate side effect of #1594 was that it accidentally got rid of the check preventing constructors returning things other than the type they're a constructor for; this code unfortunately works:

```rs
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub struct Foo;

#[wasm_bindgen]
pub struct Bar;

#[wasm_bindgen]
impl Foo {
    #[wasm_bindgen(constructor)]
    pub fn new() -> Bar {
        Bar
    }
}
```

Putting the check back would technically be a breaking change, but the odds of it causing breakage are hopefully pretty slim.

**Comment by snOm3ad** [comment]
I can work on a PR for both these issues. Might take a while as I'm not super familiar with how generation works, so any pointers are welcome.
