### ISSUE TITLE
downloading wasm-bindgen version="0.2.83"

### ISSUE THREAD

**Issue by jonZ92** [rustwasm/wasm-bindgen#3217]
### Describe the Bug

error from HTML pipeline

Caused by:
    0: error from asset pipeline
    1: failed downloading release archive
    2: error sending HTTP request
    3: error sending request for url (https://github.com/rustwasm/wasm-bindgen/releases/download/0.2.83/wasm-bindgen-0.2.83-x86_64-unknown-linux-musl.tar.gz): error trying to connect: tcp connect error: Connection timed out (os error 110)
    4: error trying to connect: tcp connect error: Connection timed out (os error 110)
    5: tcp connect error: Connection timed out (os error 110)
    6: Connection timed out (os error 110)

**Comment by Liamolucko** [comment]
That sounds like some kind of GitHub server issue. It might have been temporary; I can't reproduce it. Is the issue still happening?

**Comment by jonZ92** [comment]
Thank you, the problem has been solved.
