### ISSUE TITLE
Example project in “examples/without-a-bundler” fails to compile (index out of bounds error)

### ISSUE THREAD

**Issue by lxg** [rustwasm/wasm-bindgen#3219]
### Describe the Bug

The example code in `examples/without-a-bundler` does not compile, even with all the necessary tools installed. Running the `build.sh` script (which effectively just runs `wasm-pack build --target web`) yields the following output:

```
+ wasm-pack build --target web
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
    Finished release [optimized] target(s) in 0.06s
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /PATH_TO_HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-cli-support-0.2.83/src/descriptor.rs:208:15
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: Running the wasm-bindgen CLI
Caused by: failed to execute `wasm-bindgen`: exited with exit status: 101
  full command: "/PATH_TO_HOME/.cargo/bin/wasm-bindgen" "/PATH_TO_HOME/repos/misc/wasm-bindgen/target/wasm32-unknown-unknown/release/without_a_bundler.wasm" "--out-dir" "/PATH_TO_HOME/repos/misc/wasm-bindgen/examples/without-a-bundler/pkg" "--typescript" "--target" "web"
```

### Steps to Reproduce

1. Check out repository
2. Run `./build.sh`

### Expected Behavior

What the README says.

### Actual Behavior

See error output above.

**Comment by Liamolucko** [comment]
This is happening because `wasm-pack` is attempting to use the published version of the `wasm-bindgen` CLI with the git version of the `wasm-bindgen` crate, which is incompatible.

To work around this, you can either:

* Check out the 0.2.83 tag of `wasm-bindgen` rather than `main`, so that the published CLI is compatible, or
* Build the git version of the `wasm-bindgen` CLI and add it to PATH, which `wasm-pack` will then use instead of trying to download the published version.

**Comment by lxg** [comment]
Thanks for getting back to me. But are you sure about this?

`wasm-bindgen -V` already gives me `0.2.83`. I did successfully build other projects with `--target web`, e.g. a slightly modified version of the Game of Life tutorial.

**Comment by lxg** [comment]
Indeed, `wasm-bindgen -V` already gives me `wasm-bindgen 0.2.83`. However, running the build.sh command again this morning, everything worked just fine. After I messed around a lot with other things yesterday evening, I might have changed something that brought things into order (again). So, I’m closing this issue as pretty much invalid. Thanks for your support, anyway!

**Comment by Karrq** [comment]
I am experiencing the same, or at least similar at least, error.

EDIT: Jump to the end for solution

I was trying to use dioxus when I encountered this, but then I tried running the steps manually to verify that wasn't the tool's fault and I encountered the issue again.

Starting with the basic demo app for the web from dioxus, I build the crate like normal, `cargo build --target wasm32-unknown-unknown` and then invoke `dioxus serve` and get an error.
I attempt to invoke wasm-bindgen manually trying my best to follow along with what the dioxus cli code is configuring bindgen via `wasm-bindgen-cli-support`:
```
wasm-bindgen --target web --debug --no-demangle --keep-debug --out-dir dist/assets/dioxus target/wasm32-unknown-unknown/debug/demo.wasm

thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /private/tmp/nix-build-wasm-bindgen-cli-0.2.83.drv-0/wasm-bindgen-cli-0.2.83-vendor.tar.gz/wasm-bindgen-cli-support/src/descriptor.rs:208:15
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: wasm_bindgen_cli_support::descriptor::Descriptor::_decode
   4: wasm_bindgen_cli_support::descriptor::Function::decode
   5: wasm_bindgen_cli_support::descriptor::Descriptor::_decode
   6: wasm_bindgen_cli_support::descriptor::Descriptor::decode
   7: wasm_bindgen_cli_support::Bindgen::generate_output
   8: wasm_bindgen_cli_support::Bindgen::generate
   9: wasm_bindgen::main
```

I built the cli from source (using nix), and the version of the crates and tools is as follows:
* dioxus-cli 3.0.0 (from source, commit hash `15ec138320901c0a0a342fa949fac77bed7c551b`)
* wasm-bindgen 0.2.83
* wasm-pack 0.10.3

As far as I can tell, the cli is also depending on `0.2.83`...

EDIT: I checked my crate's dependencies and it was using `0.2.84`, so I pinned the package version to that in my toml and that did the trick.
