### ISSUE TITLE
Can i use `include_bytes!` with wasm_bindgen?

### ISSUE THREAD

**Issue by guchengxi1994** [rustwasm/wasm-bindgen#3230]
### Summary

I want to embed a common file into wasm, like this:
```rust
#[wasm_bindgen]
pub fn load_file()->Vec<u8> {
    // return  fs::read(r"C:\Users\xiaoshuyui\Desktop\我的图片.png").unwrap()
    let bytes = include_bytes!("some.file");
    println!("{:?}",bytes.len());
    return bytes.to_vec();
}
```
but it raise exception when using `wasm-pack build --target web`

**Comment by Liamolucko** [comment]
`include_bytes!` should work fine. Can you post the specific error shown by `wasm-pack`? It could be that you typed the path wrong - it needs to be relative to the Rust file that you called `include_bytes!` from.

**Comment by guchengxi1994** [comment]
@Liamolucko thanks for help, i solved this problem
