### ISSUE TITLE
How to use "web_sys_unstable_apis" properly?

### ISSUE THREAD

**Issue by Crepper710** [rustwasm/wasm-bindgen#3261]
### How do i use the "web_sys_unstable_apis" properly?

I am currently working on a webpage using yew (not that important,  just for context)
And i planned on using the `ClipboardEvent`, it seems to be an unstable part of `web_sys`.
So i tried adding the "web_sys_unstable_apis" in every way i can think of to the project, but nothing worked.

I am sure the flag is set because i checked it using:
```rust
if cfg!(web_sys_unstable_apis) {
    "with"
} else {
    "without"
}
```

### Some additional info:

I added `web_sys` to my project via the `cargo.toml` file.

Thanks in advance

**Comment by Liamolucko** [comment]
Did you also remember to enable the `ClipboardEvent` feature of `web-sys` in `Cargo.toml`?

**Comment by Crepper710** [comment]
Oh, that was the issue. Thanks
