### ISSUE TITLE
JS/C substitution strings have odd behavior

### ISSUE THREAD

**Issue by Halmela** [rustwasm/wasm-bindgen#3265]
### Describe the Bug

%s, %d and possible other JS/C style substitution symbols substitute to empty string.
Chromium logs this fine, Firefox doesn't.

### Steps to Reproduce

1. `cargo init substitute_test`
2. Cargo.toml
```
[package]
name = "substitute_test"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-logger = "0.2.0"
log = "0.4.17"

[dependencies.web-sys]
version = "0.3"
features = [
    "console",
]

```
3. src/main.rs
```
fn main() {
    wasm_logger::init(wasm_logger::Config::default());
    log::info!("%d");
    log::info!("%s");
}
```

4. `trunk serve`
5. In browser go to `localhost:8080` and open console

Expectation would be, that the logs actually include strings "%d" and "%s" on their own rows.

### Actual Behavior
On Chromium, logs are:
```
INFO src/main.rs:3 %d
INFO src/main.rs:4 %s
```

On Firefox, logs are:
```
INFO src/main.rs:3
INFO src/main.rs:4
```

### Additional context
I encountered this when interacting with chrono and yew libraries.
At least Yew does not render the substitution strings on Chromium or Firefox, but I do not know if it because of bindgen or their stuff.

I thought this would be the most appropriate place to put this, since it does not affect only logger.

**Comment by snOm3ad** [comment]
Here's a more minimal example using only `wasm-bindgen` and `web-sys`.

```rust
use wasm_bindgen::prelude::*;
use web_sys::console;

#[wasm_bindgen]
pub fn test() {
    let css = "background: inherit; color inherit";
    let specifier = "%s";
    let s = JsValue::from(&format!("%c output: {specifier}"));
    console::log_2(&s, &JsValue::from(css));
}
```

On Firefox I see no output, and on Safari I see output "%6s" which is also odd. Looks like Chromium is the only one output the right thing?

**Comment by hamza1311** [comment]
Can you try running `console.log` with the same inputs from JS? I just tried it

**Chrome 114.0.5735.198**:
![image](https://github.com/rustwasm/wasm-bindgen/assets/47357913/4bd966ad-849c-4841-92fa-a99ca07ba1d8)

**Firefox 115.0.2**:
![image](https://github.com/rustwasm/wasm-bindgen/assets/47357913/b10bd7ad-a790-46ae-b5dc-c0603e3789cd)

**Comment by snOm3ad** [comment]
@hamza1311 the issue mentions "%d" and "%s" not "$s" (like your screenshot). So, I tried it with "%s" and I'm seeing the same results:

Firefox  115.0.2

<img width="668" alt="image" src="https://github.com/rustwasm/wasm-bindgen/assets/29729942/c5606de9-9df2-4401-97db-7b1014137f45">

Chrome 115.0.5790.102

<img width="743" alt="image" src="https://github.com/rustwasm/wasm-bindgen/assets/29729942/2d4598a3-bd81-4870-9883-20d6e1543c96">

Safari 16.5.2

<img width="682" alt="image" src="https://github.com/rustwasm/wasm-bindgen/assets/29729942/79720c9f-69c8-4672-8548-97fa44aa2d62">

I'm guessing this confirms this is just an implementation difference in the console [spec](https://console.spec.whatwg.org/) between these browsers and not a `wasm-bindgen` issue?

**Comment by hamza1311** [comment]
Yep, this isn't a wasm-bindgen issue; this is how browsers are treating the input. I'm going to go ahead and close this.
