### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by bouk** [rustwasm/wasm-bindgen#3267]
Hi, I was wondering if you could release a new version of the wasm-bindgen CLI, it's been a while since the last one. Thank you!

**Comment by daxpedda** [comment]
I am also interested in a new release.
It would be great if we could squeeze in https://github.com/rustwasm/wasm-bindgen/pull/3247 and https://github.com/rustwasm/wasm-bindgen/pull/3168 beforehand though.

**Comment by gents83** [comment]
It would be nice to have a new release also for wgpu :)

**Comment by alexcrichton** [comment]
I posted a bump at https://github.com/rustwasm/wasm-bindgen/pull/3274, sorry but I don't have the time personally to go through open PRs and help push them all across the finish line.
