### ISSUE TITLE
Best way to handle self-consuming content

### ISSUE THREAD

**Issue by acdha** [rustwasm/wasm-bindgen#329]
I've been working on replacing some JavaScript hashing code with Rust variants. This works great as a simple function and the performance numbers look pretty good compared to asmCrypto.js, not to mention the ease of adding support for additional algorithms:

```rust
#[wasm_bindgen]
pub fn sha2_256(input_bytes: &[u8]) -> String {
    use sha2::Digest;

    let mut hasher = Sha256::default();

    hasher.input(input_bytes);
    let output = hasher.result();
    return format!("{:x}", output);
}
```

Unfortunately, adding a streaming interface hits a couple of implementation issues because the `sha2` crate (and the rest of the RustCrypto hash implementations) make `Digest.result()` self-consuming:

```rust
#[wasm_bindgen]
pub struct Sha2_256Hasher {
    hasher: Sha256,
}

#[wasm_bindgen]
impl Sha2_256Hasher {
    #[wasm_bindgen(constructor)]
    pub fn new() -> Sha2_256Hasher {
        Sha2_256Hasher {
            hasher: Sha256::default(),
        }
    }

    pub fn update(&mut self, input_bytes: &[u8]) {
        self.hasher.input(input_bytes)
    }

    pub fn hex_digest(&mut self) -> String {
        let output = self.hasher.result();  # FAIL: cannot move out of borrowed content
        return format!("{:x}", output);
    }
}
```

I won't pretend to be a Rust expert but normally I'd just remove the `&` for `hex_digest` but wasm-bindgen currently returns an error “by-value `self` not yet supported”. 

Is there a better way to cleanly solve this kind of problem? I was thinking initially about passing in a JavaScript callback or generator but that doesn't appear to be supported yet and doing it by passing Rust closures looks like it'll be messy.

**Comment by alexcrichton** [comment]
Thanks for the report! Here we'll likely just want to add support for `self` as it should have a simple-enough translation to JS. In that sense I think for now you can work around this with an internal `Option` and otherwise this is a TODO for wasm-bindgen to implement!

**Comment by acdha** [comment]
Thanks for confirming that I wasn't missing something obvious. The experience has otherwise been pretty awesome, with a substantial performance win over asmCrypto.js!

**Comment by jevancc** [comment]
Hi, I also have the same issue in my project. 

My solution is to implement the self-consuming method as a non-member function. For your example it could be:
```
#[wasm_bindgen]
pub fn sha2_256Hasher_hex_digest(self_: Sha2_256Hasher) -> String {
    // replace self with self_
}
```
Then you can pass your object to this function as an argument.  Notice that the member `ptr` of the consumed object on JS side will be set to `0`. Make sure that you won't use it after passing to this function.

**Comment by acdha** [comment]
I ended up kludging this with a Cell in https://github.com/acdha/wasm-hashing/commit/6bb246dd7b1ab420aeacc8031a787b4df238002c which is ugly (I wanted to see if there was a cleaner generic way to handle that boilerplate, although trait impls appear not to be supported yet) but was enough to confirm that I'm getting competitive performance with other hash implementations. I need to review that code but my main priority now is testing it using `File` contents in a web worker since it appears to be quite a bit faster than what I've been using or even the browser-native SubtleCrypto interface, which seems surprising.

**Comment by acdha** [comment]
@alexcrichton I just picked this project up again and wanted to see if my original code would work (e.g. using `pub fn hex_digest(self) -> String`) using wasm-bindgen 0.2.15. It compiles but webpack fails with this error:

```
ERROR in ./wasm_hashing.js 430:14
Module parse failed: Identifier 'ptr' has already been declared (430:14)
You may need an appropriate loader to handle this file type.
|         wasm.sha2_256hasher_hex_digest(retptr, ptr);
|         const mem = getUint32Memory();
>         const ptr = mem[retptr / 4];
|         const len = mem[retptr / 4 + 1];
|         
 @ ./index.js 8:19-43
```

**Comment by alexcrichton** [comment]
Oh dear, sounds bad! That should be fixed in https://github.com/rustwasm/wasm-bindgen/pull/662

**Comment by acdha** [comment]
Thanks for the rapid response!
