### ISSUE TITLE
Extern type in struct not possible

### ISSUE THREAD

**Issue by abduelhamit** [rustwasm/wasm-bindgen#3291]
### Describe the Bug

Currently, it's not possible that the type of a struct field is an external JS type.
As far as I can tell, it's not a missing feature but a bug. See Additional Context for the reasons that make me believe that.

### Steps to Reproduce

Example code:
```rust
#[wasm_bindgen]
extern "C" {
    type Foo;
}

#[wasm_bindgen]
struct Bar {
    #[wasm_bindgen(getter_with_clone)]
    pub foo: Foo,
}
```

### Expected Behavior

It should work without a compiler error.

### Actual Behavior

```
error[E0308]: mismatched types
  --> src/lib.rs:18:1
   |
18 | #[wasm_bindgen]
   | ^^^^^^^^^^^^^^^
   | |
   | expected struct `Foo`, found struct `JsValue`
   | arguments to this function are incorrect
   |
note: associated function defined here
  --> /Users/abdul/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-0.2.84/src/convert/traits.rs:17:8
   |
17 |     fn into_abi(self) -> Self::Abi;
   |        ^^^^^^^^
   = note: this error originates in the attribute macro `wasm_bindgen` (in Nightly builds, run with -Z macro-backtrace for more info)
help: try wrapping the expression in `Foo`
   |
18 | Foo { obj: #[wasm_bindgen] }
   | ++++++++++                 +
```

### Additional Context

[These lines in codegen.rs](https://github.com/rustwasm/wasm-bindgen/blob/0.2.84/crates/backend/src/codegen.rs#L334-L335) generate the following code in this case:
```rust
let val = (*js).borrow().foo.clone();
<Foo as IntoWasmAbi>::into_abi(val)
```
The issue is that the code assumes that the type of the cloned value is `Foo`. But actually, it's `JsValue`. I don't know why, though.
So one way to fix this issue is to modify the generator into generating `<JsValue as IntoWasmAbi>` instead of `<Foo as IntoWasmAbi>`.

**Comment by Liamolucko** [comment]
The problem is that `Foo` needs to implement `Clone` to be used with `#[wasm_bindgen(getter_with_clone)]`. You can fix this by adding `#[derive(Clone)]` to the declaration of `Foo`:

```rust
#[wasm_bindgen]
extern "C" {
    #[derive(Clone)]
    type Foo;
}
```

The error message you got was incredibly unhelpful, though, so I've opened #3295 to improve it.
