### ISSUE TITLE
Closure::once will cause ```Error closure invoked recursively or destroyed already```？

### ISSUE THREAD

**Issue by linzhipeng98** [rustwasm/wasm-bindgen#3294]
Some codes:
```
use js_sys::Promise;
use wasm_bindgen::prelude::wasm_bindgen;
use wasm_bindgen::prelude::Closure;
use wasm_bindgen::JsValue;

#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(js_namespace = console)]
    fn log(s: &str);
}

#[wasm_bindgen]
pub fn test() {
    let handle_resolve = Closure::<dyn FnMut(JsValue)>::new(|_| {
        log("resolve");
    });

    Promise::resolve(&JsValue::UNDEFINED).then(&handle_resolve);
    handle_resolve.forget();
}
```
I found the [wasm-bindgen guide](https://rustwasm.github.io/docs/wasm-bindgen/examples/closures.html) use `.forget`, but admits that that is essentially leaking memory.

> Normally we'd store the handle to later get dropped at an appropriate time but for now we want it to be a global handler so we use the forget method to drop it without invalidating the closure. Note that this is leaking memory in Rust, so this should be done judiciously!

So i change my code to:

```
#[wasm_bindgen]
pub fn test() {
    let handle_resolve = Closure::once(|_| {
        log("resolve");
    });

    Promise::resolve(&JsValue::UNDEFINED).then(&handle_resolve);
    // handle_resolve.forget();
}
```
I use `once` method to create closure and remove `forget` call. (Because resolve callback will only be executed once).
But I get this error in chrome console:

```
Uncaught (in promise) Error: closure invoked recursively or destroyed already
    at __wbindgen_throw (wasm_bindgen_webpack_bg.js:130:11)
    at 601c8939635acefd5b21.module.wasm:0x342e
    at 601c8939635acefd5b21.module.wasm:0x2cb3
    at __wbg_adapter_8 (wasm_bindgen_webpack_bg.js:92:64)
    at real (wasm_bindgen_webpack_bg.js:68:20)
```

Is there something wrong with my code?

**Comment by Liamolucko** [comment]
The function you're looking for is `Closure::once_into_js`. It directly returns a `JsValue`, and deallocates the closure after it gets called once.

`Closure::once`, on the other hand, basically behaves the same as the standard `Closure::new`, except that it accepts an `FnOnce`. It still requires that the `Closure` be kept around as long as it's used.

**Comment by linzhipeng98** [comment]
@Liamolucko Thank you for your help!
