### ISSUE TITLE
Undefined `__wbindgen_malloc` when running WASM binary

### ISSUE THREAD

**Issue by cryptoquick** [rustwasm/wasm-bindgen#3306]
### Describe the Bug

We've recently hit a snag from compiling the same code and getting different results a few weeks apart.

2 weeks ago, we published this bundle: https://unpkg.com/browse//bitmask-core@0.5.0-rc.6/

It was built from this repo and commit: https://github.com/diba-io/bitmask-core/commit/5cf7f4d64354e4979b9d5d74c8c83871f1627e83

Using this command: `wasm-pack build --release --target bundler`

Back then, it produced a binary that runs in our Chrome extension, but now it produces something different, where running any function results in this error:

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '__wbindgen_malloc')`

I'm not sure what steps I can try to investigate this further.

Examples of more recent tries:
- https://unpkg.com/browse//bitmask-core@0.5.0/
- https://unpkg.com/browse//bitmask-core@0.5.1/

**Comment by cryptoquick** [comment]
I've tried compiling this on both rustc `1.66.1`, which I believe was the version used at the time of publishing, but I also ran into this issue on `1.67.1` released just a few days ago.

**Comment by cryptoquick** [comment]
I've zipped up one of my failing builds, if that helps...
[pkg.zip](https://github.com/rustwasm/wasm-bindgen/files/10732886/pkg.zip)

I'm going to try to create a minimal reproducible example.

**Comment by cryptoquick** [comment]
Okay, I've made a minimum reproducible example, just run a local server and view index.html in this directory.
[pkg.zip](https://github.com/rustwasm/wasm-bindgen/files/10732998/pkg.zip)

**Comment by cryptoquick** [comment]
Alright, I've created an even more trimmed down MRE:

This can be compiled with `wasm-pack build --dev target web`

[wasm-test.zip](https://github.com/rustwasm/wasm-bindgen/files/10759369/wasm-test.zip)

What's interesting is that, I suspect this issue only seems to occur on Linux, but I'm not able to test that possibility.

My system:

`Linux hephaestus 6.1.9-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Wed, 01 Feb 2023 17:07:37 +0000 x86_64 GNU/Linux`
`rustc 1.67.0 (fc594f156 2023-01-24)`
`wasm-pack 0.10.3`

**Comment by FlareFlo** [comment]
I'm getting either `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '__wbindgen_add_to_stack_pointer')` or `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'main_js')` where `main_js` is a rust fn annotated with `#[wasm_bindgen(start)]`.
Occurs both on windows and Linux.

**Comment by cryptoquick** [comment]
I'm glad I'm not the only one seeing this! It's driving me crazy 😭

**Comment by FlareFlo** [comment]
> I'm glad I'm not the only one seeing this! It's driving me crazy 😭

My development branch has been offline for 2 weeks, I thought I had just misconfigured the webserver somehow.

**Comment by cryptoquick** [comment]
@FlareFlo What's your OS, rustc version, wasm-pack version, and what browser are you testing in? I forgot to mention I was trying it in Chrome. Not sure if I'd get different results in Safari or Firefox.

**Comment by FlareFlo** [comment]
> @FlareFlo What's your OS, rustc version, wasm-pack version, and what browser are you testing in? I forgot to mention I was trying it in Chrome. Not sure if I'd get different results in Safari or Firefox.

Windows 10H and Linux 6.1.12
Firefox and chrome on windows, chromium 109 on linux
Rust stable 1.67
wasm-pack 0.10.0

**Comment by cryptoquick** [comment]
Interesting, that's a good spread, probably enough to rule out something wrong on the OS and browser side. Maybe it's something to do with the Rust version... I'm gonna try some older ones.

**Comment by cryptoquick** [comment]
Okay, I went through, and tried 1.66, 1.65, 1.64, and 1.63. No improvement. I wonder what could have possibly changed? I'm running out of things to try.

**Comment by daxpedda** [comment]
I tried out your example in https://github.com/rustwasm/wasm-bindgen/issues/3306#issuecomment-1433545999 and I noticed something strange.
I'm not familiar with `wasm-pack` at all, but your `index.html` file didn't initialize the WASM instance, you didn't call `init()`. Trying your example gave me the same error both of you got, but adding `init()` seemed to fix it.

**Comment by FlareFlo** [comment]
Im not familiar with an `init()` function, is it a builtin that needs to be called?

**Comment by daxpedda** [comment]
Yes absolutely. You can read up on it here: https://rustwasm.github.io/docs/wasm-bindgen/examples/without-a-bundler.html.

I can only assume that `wasm-pack` kinda does this for you, but in the example that was posted above a custom HTML was used that doesn't call `init()`. Again, I have no clue about `wasm-pack`, just speculating.

**Comment by FlareFlo** [comment]
it seems no `init` function is generated

**Comment by daxpedda** [comment]
I'm assuming you mean by `wasm-pack`?

**Comment by FlareFlo** [comment]
> I'm assuming you mean by `wasm-pack`? `wasm-bindgen` should definitely generate one in the shim.

it's possible I did not check the right output location, however, importing `init`fails

**Comment by cryptoquick** [comment]
If I do this:

```js
      import init, * as wasm_test from "./pkg/wasm_test.js";
      init()
      wasm_test.hello("hello");
```

I see no improvement... Also, the bundler doesn't export that, so that doesn't explain why it doesn't work when using `wasm-pack build --release --target bundler`

**Comment by erwanvivien** [comment]
I don't think there is an init function when using bundler, only when targeting web

So either you have (with `wasm-pack build --target web`):
```js
import init, { function } from './pkg/xxx.js';
// Without async/await
init().then(() => {
    function();
  });
// With async await
await init();
function();
```

Or (with `wasm-pack build --target bundler`):

```js
import { function } from './pkg/xxx.js';
function();
```

**Comment by cryptoquick** [comment]
Ah! It must be awaited. Glad we have top-level await now.

```js
      import init, * as wasm_test from "./pkg/wasm_test.js";
      await init()
      wasm_test.hello("hello");
```

This does indeed resolve the issue in my example.

So, that's good to know. The question now is, why isn't it being called in the bundler? I suppose that might be more a wasm-pack question than a wasm-bindgen question. I'll create an issue over there.

**Comment by erwanvivien** [comment]
I don't think it's an issue, bundler is meant to be used when you are serving your wasm through webpack and the like (a bundler)

If you're doing it very simple aka web, you don't need to bundle the wasm module, but you will need to init it yourself

Basically:
- target web can be used anywhere but requires manual init
- target bundler the bundler takes care of the init

**Comment by FlareFlo** [comment]
I'm using webpack so i will see if this resolves it

**Comment by erwanvivien** [comment]
I'm using vite with this config (entire)
```
import { defineConfig } from 'vite';

import wasm from 'vite-plugin-wasm';

export default defineConfig({
    plugins: [wasm()]
});
```

I believe even in webpack you'll need to touch the config, but I don't know webpack

**Comment by FlareFlo** [comment]
`export 'default' (imported as 'init') was not found in '../pkg/index.js' (possible exports: __wbg_appendChild_b8199dc1655c852d,` (with a bunch of glue and my own functions listed)

**Comment by erwanvivien** [comment]
Check the example I provided above, if you use `init`, you need to use this wasm-pack command 
`wasm-pack build --target web`

If you open the index.js file in you pkg, you should see an init function at the bottom of it (if target web)

**Comment by FlareFlo** [comment]
> Check the example I provided above, if you use `init`, you need to use this wasm-pack command `wasm-pack build --target web`
> 
> If you open the index.js file in you pkg, you should see an init function at the bottom of it (if target web)

the bundler-targeted version does not work as fails with the error that this issue opened with.
i am using [this](https://github.com/wasm-tool/wasm-pack-plugin) however

**Comment by erwanvivien** [comment]
I don't know sorry :/

**Comment by cryptoquick** [comment]
@FlareFlo What version of Webpack are you using? I'm running `webpack 5.75.0`, apparently it doesn't need such loaders anymore, instead, we've got these options turned on:

```js
    experiments: {
      asyncWebAssembly: true,
      syncWebAssembly: true,
    },
```

**Comment by FlareFlo** [comment]
> @FlareFlo What version of Webpack are you using? I'm running `webpack 5.75.0`, apparently it doesn't need such loaders anymore, instead, we've got these options turned on:
> 
> ```js
>     experiments: {
>       asyncWebAssembly: true,
>       syncWebAssembly: true,
>     },
> ```

I have these options set using `5.75.0`

**Comment by Liamolucko** [comment]
I think this is caused by #3276.

The `"sideEffects": false` that triggers the issue is inserted by `wasm-pack`, not `wasm-bindgen`, so using the `wasm-bindgen` CLI directly instead of `wasm-pack` should work as a workaround.

**Comment by FlareFlo** [comment]
something I may add to this:
- the wasm file is generated in the output file
- the file is never requested/loaded at all, it does not show up in the network tab and does not error out

**Comment by AndrewJSchoen** [comment]
I was experiencing this as well on version `0.2.84`. When I downgraded to `0.2.83`, it resumed working.

**Comment by theitaliandev** [comment]
`
experiments: {
        asyncWebAssembly: true,
        topLevelAwait: true
       }
`

`
import * as rust from "./pkg"

const wasm = await rust

wasm.greet("hello")
`

and the "Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '__wbindgen_malloc')" error goes away...

**Comment by daxpedda** [comment]
Seems like this was fixed to me.

Please re-open if this still an issue.

**Comment by jswhisperer** [comment]
with vite.config I think this might help
```
  build: {
    target: "esnext",
  },
```
