### ISSUE TITLE
type inference from js values to rust with wasm-bindgen?

### ISSUE THREAD

**Issue by redcrabs** [rustwasm/wasm-bindgen#3321]
Hi .

I searched but didn't find and exact match about it. I'm clearly looking to see if wasm-bindgen is able to give the capability to recognize the types of statements in a given js file .

My point as an example :

```
// file.js 
alert("Hello! I am an alert!");
const para = document.createElement("p");
```

to read file.js with rust to give that :

**para** is a type of "create_element" in rust .

Thanks.

**Comment by daxpedda** [comment]
`wasm-bindgen` doesn't read JS files, so I'm not sure what exactly you are looking for here.
> **para** is a type of "create_element" in rust .

"create_element" is not a type, the type returned here is an `HTMLElement` ([MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/createElement#return_value)).
