### ISSUE TITLE
How it works about raw_copy_to_ptr ?

### ISSUE THREAD

**Issue by GitNiko** [rustwasm/wasm-bindgen#3336]
### Summary

I'm confused about this code.It seems to only set memory to `all_wasm_memory` but not `dst` in my opinion. 
How it works And Why it is Efficient？
https://github.com/rustwasm/wasm-bindgen/blob/main/crates/js-sys/src/lib.rs#L5990
```rust
/// Copy the contents of this JS typed array into the destination
/// Rust pointer.
///
/// This function will efficiently copy the memory from a typed
/// array into this wasm module's own linear memory, initializing
/// the memory destination provided.
///
/// # Unsafety
///
/// This function requires `dst` to point to a buffer
/// large enough to fit this array's contents.
pub unsafe fn raw_copy_to_ptr(&self, dst: *mut $ty) {
                let buf = wasm_bindgen::memory();
                let mem = buf.unchecked_ref::<WebAssembly::Memory>();
                let all_wasm_memory = $name::new(&mem.buffer());
                let offset = dst as usize / mem::size_of::<$ty>();
                all_wasm_memory.set(self, offset as u32);
            }
```
https://github.com/rustwasm/wasm-bindgen/blob/main/crates/js-sys/src/lib.rs#L6031
```rust
pub fn to_vec(&self) -> Vec<$ty> {
                let mut output = Vec::with_capacity(self.length() as usize);
                unsafe {
                    self.raw_copy_to_ptr(output.as_mut_ptr());
                    output.set_len(self.length() as usize);
                }
                output
            }
```

**Comment by Liamolucko** [comment]
`all_wasm_memory` is a JavaScript view into all of the memory used by Rust, which includes `dst`. The `all_wasm_memory.set(...)` line doesn't set the whole wasm memory to `self`; it sets a very specific bit of `all_wasm_memory`, the bit where `dst` is stored. So, that's how it indirectly sets `dst`.

It's faster to do it this way because the `set` method of JavaScript typed arrays can be used to copy the whole thing all at once. Otherwise, the whole thing would have to be copied one number at a time, which would be slower.

**Comment by GitNiko** [comment]
Thanks for your replay.  

> it sets a very specific bit of all_wasm_memory, the bit where dst is stored. So, that's how it indirectly sets dst.

I'm still confused about `all_wasm_memory.set`. I think it set self memory to `dst` after `offset`, what' wrong with thinking that way?

<img width="954" alt="image" src="https://user-images.githubusercontent.com/5418452/222614431-baf588cd-e043-454b-bb99-e8c95e25362b.png">

**Comment by Liamolucko** [comment]
You're not far off, it's just that `offset` is an offset from the start of wasm memory, not from `dst`.

**Comment by GitNiko** [comment]
Got it! Thank you for clarifying that for me!
