### ISSUE TITLE
Wrong mutation when a rust async function takes a `&mut [u8]`

### ISSUE THREAD

**Issue by MarcoPolo** [rustwasm/wasm-bindgen#3339]
### Describe the Bug

When we export a function of type:
```rust 
#[wasm_bindgen]
pub async fn read(mut s: Stream, buf: &mut [u8]) -> Result<usize, JsError> { 
// ...
}
```

The generated shim function copies the mutated buffer when the function returns *not* when the promise completes.

The shim function does:
```js
module.exports.read = function(s, buf) {
    try {
        _assertClass(s, WrappedNoiseOutput);
        var ptr0 = s.ptr;
        s.ptr = 0;
        var ptr1 = passArray8ToWasm0(buf, wasm.__wbindgen_malloc);
        var len1 = WASM_VECTOR_LEN;
        const ret = wasm.read(ptr0, ptr1, len1);
        return takeObject(ret);
    } finally {
        buf.set(getUint8Memory0().subarray(ptr1 / 1, ptr1 / 1 + len1));
        wasm.__wbindgen_free(ptr1, len1 * 1);
    }
};
```

when it should do something like:
```js
module.exports.read = async function(s, buf) {
    try {
        _assertClass(s, WrappedNoiseOutput);
        var ptr0 = s.ptr;
        s.ptr = 0;
        var ptr1 = passArray8ToWasm0(buf, wasm.__wbindgen_malloc);
        var len1 = WASM_VECTOR_LEN;
        const ret = wasm.read(ptr0, ptr1, len1);
        return await takeObject(ret);
    } finally {
        buf.set(getUint8Memory0().subarray(ptr1 / 1, ptr1 / 1 + len1));
        wasm.__wbindgen_free(ptr1, len1 * 1);
    }
};
```

The difference is that the `buf.set(getUint8Memory0().subarray(ptr1 / 1, ptr1 / 1 + len1));` should be executed after the promise completes.

Tested on NodeJS and wasm-bindgen version 0.2.83

### Steps to Reproduce

If applicable, add a link to a test case (as a zip file or link to a repository we can clone).

### Expected Behavior

The passed in buffer should have the changes the function makes when it completes.

### Actual Behavior

The passed in buffer is unmodified.

### Workaround

I think I can wrap the array buffer in a new rust type, then unwrap it when the function completes.

**Comment by Liamolucko** [comment]
This should have been fixed by #3188, which was part of version 0.2.84. Can you try switching to 0.2.84 and see if that fixes the issue?

**Comment by MarcoPolo** [comment]
ah, sounds like it! Will try soon and report back. Thanks

**Comment by stefnotch** [comment]
@MarcoPolo Have you managed to try it out?

**Comment by MarcoPolo** [comment]
No, sorry, but I'd be pretty confident in closing this from looking at the PR
