### ISSUE TITLE
Run tests on web workers

### ISSUE THREAD

**Issue by whizsid** [rustwasm/wasm-bindgen#3340]
### Motivation

In some code segments I have to depend on Web Workers APIs which not available in browser scope. So I need an option to run all the tests on a web worker.

### Proposed Solution

Run all the tests on a web worker and sending console outputs by using `postMessage` to main thread.

### Alternatives

Run each test on a separate web worker. This may break the existing behaviours for other targets. Example:- NodeJS and browser tests have shared memory access. But when using separate workers, we can not use a shared memory.

### Additional Context

I took some steps to implement it. But I got an error from `getObject` function inside the worker.

**Comment by daxpedda** [comment]
Would you mind elaborating on what Web Worker APIs you are depending and why?

**Comment by whizsid** [comment]
@daxpedda I wrote my crate to use `Window` on browser scope and `WorkerGlobalScope` on worker scopes. So I need to ensure whether my crate is working for all the scopes.
