### ISSUE TITLE
Functions with extermely long names can cause wasm-bindgen to fail to locate the main function

### ISSUE THREAD

**Issue by bobtwinkles** [rustwasm/wasm-bindgen#3362]
### Describe the Bug

When a WASM module contains a function with an extremely long mangled name (>100_000 characters, as can be generated by rust-lang/rust#109363) `wasmparser` will choke on the `names` custom section. This means that at the `walrus`/`wasm-bindgen` layer any functions in the module after the problematically named function will not have names assigned. This is particularly deleterious if `main` is late, as it means `wasm-bindgen` won't emit the `main` glue (`__wbindgen_start` and friends).

### Steps to Reproduce

1. Use the example code from rust-lang/rust#109363, or clone https://github.com/bobtwinkles/wasm-bindgen-bug/
2. Build that code with the module name `bad` or `baad` and rustc 1.66 - 1.70 (other versions not tested). The module name `good` happens to work but it's up to the order `rustc` chooses to emit the code, I'll chalk this one up to nominative determinism.

### Expected Behavior

`wasm-bindgen` should maybe complain louder that it has failed to load all function names? I'm not really sure what can be done about this at the `wasm-bindgen` layer to be honest, I'm mostly just filing this bug here because I'm not sure what layer of the stack is really at fault here and want somewhere to anchor the discussion.

### Actual Behavior

`wasm-bindgen` silently fails to generate `main` glue.

### Additional Context

I discovered this while working on a Sycamore app, in particular the [`sycamore::builder::ElementBuilder`](https://docs.rs/sycamore/0.8.2/sycamore/builder/struct.ElementBuilder.html) type suffers from the exponential drop glue function symbol size problem mentioned in the Rust bug above.

**Comment by Liamolucko** [comment]
Huh, that's strange. The limit on function name lengths in `wasmparser` is intentional:

https://github.com/bytecodealliance/wasm-tools/blob/7108f5530dda9a07f5087ce4d013730b432438bc/crates/wasmparser/src/limits.rs#L26

But I'm not sure why it's getting silently ignored.

**Comment by bobtwinkles** [comment]
`walrus` treats failure to parse the name section as nonfatal: https://github.com/rustwasm/walrus/blob/9d6c9de432d6a97478dc76ebdf18aed51584c3af/src/module/mod.rs#L217-L231

so `wasm-bindgen` thinks all the names have been parsed successfully when they have not. Running `wasm-bindgen` with `RUSTLOG=warn` or greater will print that warning on the offending modules.
