### ISSUE TITLE
how to fix wasm-bindgen version report an error

### ISSUE THREAD

**Issue by kurisaW** [rustwasm/wasm-bindgen#3369]
## The following error occurred when I tried to use the rustwasmc build command:

```
Error: Ensure that you have "wasm-bindgen 0.2.61" as a dependency in your Cargo.toml file:
[dependencies]
wasm-bindgen = "=0.2.61"
```

**I tried to change to the specified version in the Catgo.toml file, but I still got an error when updating the dependency. The version does not seem to exist, or how can I get wasm-bindgen version 0.2.61.**

**Comment by kurisaW** [comment]
https://github.com/KurisaW-Collaborative/EC_Project/issues/1#issuecomment-1473655407

**Comment by daxpedda** [comment]
This is probably not an issue in `wasm-bindgen` but in `rustwasmc` (which I know nothing about).

But `wasm-bindgen` v0.2.61 clearly exists [on crates.io](https://crates.io/crates/wasm-bindgen/0.2.61).

**Comment by kurisaW** [comment]
> This is probably not an issue in `wasm-bindgen` but in `rustwasmc` (which I know nothing about).
> 
> But `wasm-bindgen` v0.2.61 clearly exists [on crates.io](https://crates.io/crates/wasm-bindgen/0.2.61).

I tried to use a different version of rustwasmc, but when I tried to change the Catgo.toml file, the same error occurred: wasm-bindgen=0.2.61 could not be found
