### ISSUE TITLE
Add github issue/PR templates

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-bindgen#337]
Empirically, I have found that these tend to lead to better issues being filed and PRs being sent.

Here is the rust-bindgen issue template: https://github.com/rust-lang-nursery/rust-bindgen/blob/master/.github/ISSUE_TEMPLATE.md

Here is wasm-pack's PR template: https://github.com/rustwasm/wasm-pack/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by alexcrichton** [comment]
I'm going to close this since I think we've fared alright without them :)
