### ISSUE TITLE
CanvasRenderingContext2D.roundRect()

### ISSUE THREAD

**Issue by IrwinJuice** [rustwasm/wasm-bindgen#3370]
Hi!

### Summary

Method round_rect() (https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/roundRect)
doesn't exist in web_sys::CanvasRenderingContext2D.
I had searched why, but I didn't find answer.  Could you please reply if this method will be added later. If not, what is the reason?

Thanks!

**Comment by daxpedda** [comment]
It's "new" and apparently unstable on Firefox.
You could easily make a PR adding it to [`CanvasRenderingContext2D.webidl`](https://github.com/rustwasm/wasm-bindgen/blob/2a28cfb1ff878779c2538fab356e3b446978893c/crates/web-sys/webidls/enabled/CanvasRenderingContext2D.webidl), you have to mark it as unstable though.

See [the book](https://rustwasm.github.io/docs/wasm-bindgen/contributing/web-sys/supporting-more-web-apis.html) for more info on how to do that.
