### ISSUE TITLE
Question about the next release date

### ISSUE THREAD

**Issue by umut-sahin** [rustwasm/wasm-bindgen#3371]
### Summary

Hi, is there a predefined release schedule for wasm-bindgen? Or if it's not on a regular schedule, could you give an approximate date for the next release? Thanks!

### Additional Details

I'm curious about the next release date because no release has support for `#[should_panic]` attribute in `#[wasm_bindgen_test]`. This feature is introduced in https://github.com/rustwasm/wasm-bindgen/commit/d9e113b73558bdf8cfe3fabbf9fb67eb12a25990, which got commited on the 13th of February whereas the latest release is on the 1st of February, which is almost 2 months ago and this is a very important feature for having good test coverage.

**Comment by alexcrichton** [comment]
There is no schedule and it's currently on an as-requested basis when I get the time. It'll be a bit before I have a moment to to this, however.

**Comment by umut-sahin** [comment]
No worries, thanks for the quick answer!
