### ISSUE TITLE
Calling callback based function using async or Promise

### ISSUE THREAD

**Issue by zskamljic** [rustwasm/wasm-bindgen#3381]
### Is it possible to call callback-based function using async or Promise somehow?

I have spent quite a lot of time trying to call `chrome.storage.local.get` like so:

```rust
#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(catch, js_namespace = ["chrome", "storage", "local"], js_name = set)]
    async fn storage_set(data: &JsValue) -> Result<(), JsValue>;

    #[wasm_bindgen(catch, js_namespace = ["chrome", "storage", "local"], js_name = get)]
    async fn storage_get(data: &JsValue) -> Result<JsValue, JsValue>;
}
```
and even tried using non-async functions, returning `js_sys::Promise` instead. Calls succeeded, but no values were set or returned.

Finally, I tried calling the function by passing a callback:
```rust
#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(js_namespace = ["chrome", "storage", "local"], js_name = get)]
    pub fn storage_get2(data: &JsValue, callback: &js_sys::Function);
}
```

which seems to finally work, but is much less convenient compared to calling via async or using a Promise to convert via JsFuture. I assume there is a way to toggle conversion to async somehow?

### Additional details

Note that calling the same from JS can be done in both ways, so I would expect it to be possible to use wasm_bindgen to do the same:
```js
chrome.storage.local.get('key', console.log);
chrome.storage.local.get('key').then(console.log);
```

**Comment by daxpedda** [comment]
I never tried developing an extension before, so I'm can't really debug this myself, but the approach you took looks perfectly fine to me.

Did you properly `await` the returned `Promise` and tried to convert the resulting `JsValue`? A more complete example would probably help.

**Comment by zskamljic** [comment]
I have since solved the issue, as following:

```rust
#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(catch, js_namespace = ["chrome", "storage", "local"], js_name = set)]
    async fn storage_set(data: &JsValue) -> Result<JsValue, JsValue>;

    #[wasm_bindgen(catch, js_namespace = ["chrome", "storage", "local"], js_name = get)]
    async fn storage_get(data: &JsValue) -> Result<JsValue, JsValue>;
}
```

the key difference being the replacement of () with JsValue, which seemed to resolve the issue.

**Comment by daxpedda** [comment]
Strange, because the `storage_get()` interface is the same.

In any case: :tada:.
