### ISSUE TITLE
Enable Weak References by default

### ISSUE THREAD

**Issue by luveti** [rustwasm/wasm-bindgen#3384]
### Motivation

WeakRef is now supported by all mainstream browsers: https://caniuse.com/mdn-javascript_builtins_weakref

### Proposed Solution

Remove `WASM_BINDGEN_WEAKREF` and set the [default value](https://github.com/rustwasm/wasm-bindgen/blob/main/crates/cli-support/src/lib.rs#L109) to true.

### Alternatives

Leak memory forever.. :)

### Additional Context

N/A

**Comment by daxpedda** [comment]
Apparently there are runtimes, e.g. serverless, that don't support weak references. So I'm not sure if we can enable this by default without a breaking change.

**Comment by pheki** [comment]
Could we use feature detection for WeakRef? Then we would avoid breaking old browsers and serverless while making it available to most browsers

**Comment by daxpedda** [comment]
I never looked into what `wasm-bindgen-cli` does here exactly, but that's probably the best solution here.

**Comment by luxalpa** [comment]
It seems this got fixed in 0.2.91? Can this be confirmed? 
https://github.com/rustwasm/wasm-bindgen/issues/3812
https://github.com/rustwasm/wasm-bindgen/pull/3822

**Comment by Liamolucko** [comment]
> It seems this got fixed in 0.2.91? Can this be confirmed? 
> 
> https://github.com/rustwasm/wasm-bindgen/issues/3812
> 
> https://github.com/rustwasm/wasm-bindgen/pull/3822

Yes, except that it has a pretty severe flaw right now: #3854.

#3854 is the correct place to track that though, not here, so I'll close it.
