### ISSUE TITLE
Unpredictable crashes on Webkit

### ISSUE THREAD

**Issue by mondeja** [rustwasm/wasm-bindgen#3389]
### Describe the Bug

Webkit tests are failing in my app. I've traced the bug as best I can to create a minimal reproducible example, you can see it at https://github.com/mondeja/webkit-wasm-bug

The problem is fully explained in the README of the repository, but to summarize, it seems to be a problem on how wasm-bindgen is setting the memory on Webkit browsers. The bug is not easily reproducible as seems to appear sometimes and sometimes not. If I remove more code from the reproducible example it happens rarely, so I can reduce it more. I've tried a lot of things without success, so seems to be related with the memory allocated.

### Steps to Reproduce

Are clearly defined in the ["Steps to reproduce" section](https://github.com/mondeja/webkit-wasm-bug#steps-to-reproduce) of the linked repository, check it there. You can see the problem reproduced on a Github Action workflow run [here](https://github.com/mondeja/webkit-wasm-bug/actions/runs/4708778780) for all wasm-opt levels, Rust nightly and stable toolchains and the wasm-bindgen versions 0.2.84 to 0.2.81 

### Expected Behavior

The application served at http://wasm.simpleicons.org crashes when built with `--release` mode on Webkit browsers, I expect to not crash.

### Actual Behavior

It just crashes or the WASM code is not even executed, sometimes one error sometimes another apparently unpredictabily. See the README of the linked repo for more information.

**Comment by daxpedda** [comment]
Do you think you can upload a version that doesn't use `trunk` or any other tools except `wasm-bindgen`?

**Comment by mondeja** [comment]
Sure, I'll give a try!

**Comment by mondeja** [comment]
I've created two versions, one with wasm-bindgen-cli and other with wasm-pack. Let me know if more information is needed.

| Tool | Branch | Run |
| --- | --- | --- |
| wasm-bindgen-cli | [untrunk-unwasmpack](https://github.com/mondeja/webkit-wasm-bug/tree/untrunk-unwasmpack) | [Reproduced](https://github.com/mondeja/webkit-wasm-bug/actions/runs/4715740753) |
| wasm-pack |  [untrunk](https://github.com/mondeja/webkit-wasm-bug/tree/untrunk) | [Reproduced](https://github.com/mondeja/webkit-wasm-bug/actions/runs/4715506142) |

**Comment by daxpedda** [comment]
I just tried it manually without `playwright` on Safari v16.4, as far as I can tell your check asserts that the title is "Simple Icons", which seemed to work just fine. I refreshed the page around 50 times.

Is it possible to reproduce this with `wasm-bindgen-test`? Would like to see the actual error messages in the CI.
Is compiling in release necessary to reproduce the bug?

**Comment by mondeja** [comment]
> I just tried it manually without playwright on Safari v16.4, as far as I can tell your check asserts that the title is "Simple Icons", which seemed to work just fine. I refreshed the page around 50 times.

Yes, if the build just go fine, seems that "sometimes" (not sure) you can refresh and refresh and the error does not appears. 

> Is compiling in release necessary to reproduce the bug?

Yes, without `--release` doesn't happens.

> Is it possible to reproduce this with wasm-bindgen-test?

Good question, I'm going to fork the wasm-bindgen-cli branch and create other with wasm-bindgen-test and see what happens.

**Comment by mondeja** [comment]
Sorry, I'm not able to setup wasm-bindgen-test for the app, seems that the tutorials are not covering the case where you've a workspace with two crates. Note that if I put the code in one crate I can't reproduce the error. Tried all configurations with wasm-pack and without it and no success, I always get "no tests to run" or error reading `package` from *Cargo.toml* (from which I suspect that there is no workspace support).

Following the tutorial:

> Create a $MY_CRATE/tests/wasm.rs file:

What is supposed to be `$MY_CRATE`? It must be a single crate or could be a workspace? From where should I run the tests? Why are two methods to run it mixed in the same docs?

Sorry, I can't expend more time working on this very strange problem. I can replicate it manually with Safari, so pretty sure that is happening, don't thinking it's a bug in the way Playwright distributes Safari, which would be very much stranger, but could be.

So my workaround would be to redirect Safari users to the old website that is made with plain JS and encourage users to not use Safari. If they don't provide enough support for WASM and the neccesary binding I'm not going to stuck on old techs just for closed source software, especially if the project is OSS. The situation is just very difficult for webkit, I must currently use Playwright to properly test them, a software made by their direct competence, does not seem a good solution, but the wasm-bindgen-test ecosystem is unmature.

Keeping this open in case that someone faces the same problem, but feel free to close it. Cheers.

**Comment by daxpedda** [comment]
> Sorry, I'm not able to setup wasm-bindgen-test for the app, seems that the tutorials are not covering the case where you've a workspace with two crates.

`wasm-bindgen-test` is a custom runner for `cargo test`, so it works exactly like `cargo test` in this regard.

> I always get "no tests to run" or error reading `package` from _Cargo.toml_ (from which I suspect that there is no workspace support).

Strange, if you upload the code somewhere I can take a look and see if I can figure out what's wrong.

> What is supposed to be `$MY_CRATE`?

Just the root folder of your crate. It really works exactly like `cargo test` in this regard.

> It must be a single crate or could be a workspace?

It supports workspaces like `cargo test` does.

> From where should I run the tests?

From the same path you run `cargo` from. Probably your crate root folder.

> Why are two methods to run it mixed in the same docs?

Do you mean `cargo test` and `wasm-pack`? `wasm-pack` generally takes away some of the manual work you have to do otherwise, e.g. without it you have to setup the custom runner, as explained [here](https://rustwasm.github.io/docs/wasm-bindgen/wasm-bindgen-test/usage.html#configure-cargoconfig-to-use-the-test-runner).

---

I get how frustrating it is sometimes to report bugs in OSS projects just to do most of the debugging work yourself. FYI, I'm not a maintainer here.

Good luck though! If you ever decide to look more into it I will be around :)

**Comment by mondeja** [comment]
This problem is now solved.

**Comment by daxpedda** [comment]
Great to hear!
