### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by FredrikNoren** [rustwasm/wasm-bindgen#3407]
Hi,

I'm using `--target web`, and I can load and interact with the wasm module, but my question is; how would I spawn multiple instances of it? (I.e. I want mutliple `WebAssembly.Instance`). Calling `init` multiple times doesn't seem to quite work for me:

```html
<script type="module">
    import init from "https://dims-releases.fra1.digitaloceanspaces.com/testy/pkg2/ambient_web.js";
    init().then(mod => {
        mod.init_ambient(false, false);
        mod.start();
    });
    init().then(mod => {
        mod.init_ambient(false, false);
        mod.start();
    });
</script>
```

**Comment by daxpedda** [comment]
The imported JS module contains quite a lot of state. You will have to instantiate a new one.

```html
<script type="module">
    import init from "https://dims-releases.fra1.digitaloceanspaces.com/testy/pkg2/ambient_web.js";
    init().then(mod => {
        mod.init_ambient(false, false);
        mod.start();
    });
</script>
<script type="module">
    import init from "https://dims-releases.fra1.digitaloceanspaces.com/testy/pkg2/ambient_web.js";
    init().then(mod => {
        mod.init_ambient(false, false);
        mod.start();
    });
</script>
```

**Comment by FredrikNoren** [comment]
@daxpedda Any chance this could be improved in the future? Seems a bit clunky, especially when working with a webpack etc. (If so, maybe we should turn this issue into a feature request instead?)

**Comment by daxpedda** [comment]
> @daxpedda Any chance this could be improved in the future?

I don't think it's impossible, but it's a pretty large change and not particularly easy to pull off. There would need to be sufficient motivation behind it to fuel something like that, imo.

> (If so, maybe we should turn this issue into a feature request instead?)

If you would like to lay out the problem for us, that would be great.

**Comment by FredrikNoren** [comment]
@daxpedda So we're developing a game engine called [Ambient](https://github.com/AmbientRun/Ambient), which we're implementing web support for. We would like to be able to run multiple "windows" on one web page (and control their lifetimes), but we'd each one to be completely isolated (i.e. running in an isolate of their own). Ambient basically compiles to one .wasm file, so would be great to load that once and instantiate it multiple times with different HtmlElements as targets.

**Comment by daxpedda** [comment]
So whats the problem with importing it twice? There shouldn't be any overhead either really, browsers are smart, they cache imports and network requests.

> [..], but we'd like each one to be completely isolated (i.e. running in an isolate of their own)

It might be better to instantiate the isolates through Wasm instead of JS. That way you would also have a common interface for native and Web, because I'm assuming on native you will have to provide the host environment to your Wasm isolates somehow without involving any JS imports/exports.

Keep in mind I know nothing about your specific architecture, just spitballling here.

---

I know of Ambient, pretty amazing project, congratulations for pulling off something that great!

**Comment by FredrikNoren** [comment]
> So whats the problem with importing it twice? There shouldn't be any overhead either really, browsers are smart, they cache imports and network requests.

Hm but would that work with webpack? (Or other bundlers/packagers) If I import it twice, won't it just resolve to the same module?

> 
> > [..], but we'd like each one to be completely isolated (i.e. running in an isolate of their own)
> 
> It might be better to instantiate the isolates through Wasm instead of JS. That way you would also have a common interface for native and Web, because I'm assuming on native you will have to provide the host environment to your Wasm isolates somehow without involving any JS imports/exports.

Hm how would that work exactly; are you thinking we have an additional "spawner" wasm module (ambient_spawner.wasm), which internally downloads and spawns instances of the "real" ambient.wasm?

> 
> Keep in mind I know nothing about your specific architecture, just spitballling here.
> 
> I know of Ambient, pretty amazing project, congratulations for pulling off something that great!

Thanks! :)

**Comment by daxpedda** [comment]
> Hm but would that work with webpack? (Or other bundlers/packagers) If I import it twice, won't it just resolve to the same module?

Unfortunately I know absolutely nothing about bundlers or packagers! But I can confirm that importing it twice in the browsers works as intended: you will have two separate states.

> Hm how would that work exactly; are you thinking we have an additional "spawner" wasm module (ambient_spawner.wasm), which internally downloads and spawns instances of the "real" ambient.wasm?

Yes.

The idea really is to not use `wasm-bindgen` in the isolate. At the moment, `wasm-bindgen` is really only good to interface with JS. In your case, the main application, let's call it the spawner, spawns a bunch of Wasm isolates, my assumption here is that these Wasm isolates are exactly the same as the ones you use on native, so they don't (or shouldn't) use `wasm-bindgen`, but the spawner needs to, which is fine.

So you instantiate your main application, your spawner, in JS, which then spawns the isolates (see [the guide](https://rustwasm.github.io/docs/wasm-bindgen/examples/wasm-in-wasm.html)), the spawner then interfaces with the isolate without using `wasm-bindgen`.
I'm assuming you are using `wasmtime` on native, not sure how you generate the interface there, but you need to do something similar for the Web.

**Comment by FredrikNoren** [comment]
Alright, yeah that seems like a reasonable way forward. Thank you!
