### ISSUE TITLE
Rust to rust bindings

### ISSUE THREAD

**Issue by FredrikNoren** [rustwasm/wasm-bindgen#3411]
Hi, I have two rust crates, A and B. Both are being built with wasm32-unknown-unknown. B exposes an API using wasm-bindgen. Is there any way to import that API in A, without "manually" re-writing the same bindings and go through javascript? I would still like them to be run as two different `.wasm` modules in the browser.

**Comment by daxpedda** [comment]
The point of `#[wasm_bindgen]` is to expose it to JS, if you don't need to expose it to JS, you can just use `extern "C"` and call it directly.

See the [example in the guide](https://rustwasm.github.io/docs/wasm-bindgen/examples/wasm-in-wasm.html).
