### ISSUE TITLE
How declare pub struct with pub fields with wasm_bindgen attribute

### ISSUE THREAD

**Issue by HomyeeKing** [rustwasm/wasm-bindgen#3417]
### Describe the Bug

```rs
#[wasm_bindgen]
pub struct Foo{
   pub bar: String,
}
```

got error:
> the trait bound String: std::marker::Copy is not satisfied the trait std::marker::Copy is not implemented for String

### Steps to Reproduce

If applicable, add a link to a test case (as a zip file or link to a repository we can clone).

### Expected Behavior

allow pub type String

### Actual Behavior

A clear and concise description of what actually happened.

**Comment by daxpedda** [comment]
This is a reoccurring problem (https://github.com/rustwasm/wasm-bindgen/issues/1775, https://github.com/rustwasm/wasm-bindgen/issues/1985), the main issue is the lack of documentation: https://github.com/rustwasm/wasm-bindgen/issues/2775.

To summarize, `pub` fields generate getters for JS, but fields for getters have to be `Copy`.

**Solution 1**
Don't make the field `pub` and define your own getters ([Guide](https://rustwasm.github.io/wasm-bindgen/reference/attributes/on-rust-exports/getter-and-setter.html)):
```rust
#[wasm_bindgen]
pub struct Foo{
	bar: String,
}

#[wasm_bindgen]
impl Foo {
	#[wasm_bindgen(getter)]
	pub fn bar(&self) -> String {
		self.bar.clone()
	}
}
```

**Solution 2**
Don't generate getters for a specific field:
```rust
#[wasm_bindgen]
pub struct Foo{
	#[wasm_bindgen(skip)]
	pub bar: String,
}
```

**Solution 3**
Use cloning getters:
```rust
#[wasm_bindgen(getter_with_clone)]
pub struct Foo{
	pub bar: String,
}
```

**Comment by alivarastepour** [comment]
> This is a reoccurring problem (#1775, #1985), the main issue is the lack of documentation: #2775.
> 
> To summarize, `pub` fields generate getters for JS, but fields for getters have to be `Copy`.
> 
> **Solution 1** Don't make the field `pub` and define your own getters ([Guide](https://rustwasm.github.io/wasm-bindgen/reference/attributes/on-rust-exports/getter-and-setter.html)):
> 
> ```rust
> #[wasm_bindgen]
> pub struct Foo{
> 	bar: String,
> }
> 
> #[wasm_bindgen]
> impl Foo {
> 	#[wasm_bindgen(getter)]
> 	pub fn bar(&self) -> String {
> 		self.bar.clone()
> 	}
> }
> ```
> 
> **Solution 2** Don't generate getters for a specific field:
> 
> ```rust
> #[wasm_bindgen]
> pub struct Foo{
> 	#[wasm_bindgen(skip)]
> 	pub bar: String,
> }
> ```
> 
> **Solution 3** Use cloning getters:
> 
> ```rust
> #[wasm_bindgen(getter_with_clone)]
> pub struct Foo{
> 	pub bar: String,
> }
> ```

Hi @daxpedda 
Can you please explain what your 2nd solution exactly does? adding `#[wasm_bindgen(skip)]` solved me this issue but removing the getter i wrote(`#[wasm_bindgen(getter)]`) for the same field would break my code. I don't quite understand what's happening.
