### ISSUE TITLE
Ability to run unit and integ tests separately

### ISSUE THREAD

**Issue by stan-irl** [rustwasm/wasm-bindgen#3432]
### Motivation
- It's common to want to run unit and integ tests separately because integ tests are slower and can be prone to failure
- `cargo test` currently supports this as documented here: https://github.com/rust-lang/cargo/issues/10491#issuecomment-1074078912
  - unit: `cargo test --lib --bins`
  - integ: `cargo test --test "*"`
- When i pass these flags to wasm-pack test I get a panic in wasm-bidgen-test
  - unit: `wasm-pack test -- --lib --bins` throws `panicked at 'flag --lib not supported'`
  - integ:  `wasm-pack test -- --test *` throws `panicked at 'flag --test not supported'`

### Proposed Solution

Ideally these flags would be supported the same as they are on `cargo test`
### Alternatives
- N/A

### Additional Context
- N/A

**Comment by daxpedda** [comment]
Indeed, this would require some work here:
https://github.com/rustwasm/wasm-bindgen/blob/feb75a2106c3777d58410a77611bf04a107102a6/crates/test/src/rt/mod.rs#L260-L282

Happy to accept a PR.

**Comment by snOm3ad** [comment]
Is this really an issue with `wasm-bindgen-test-runner`? I just tested this on a project without using `wasm-pack` and noticed the behaviour is correct, i.e. using `cargo test --target wasm32-unknown-unknown --lib --bins` runs the unit tests only and `cargo test --target wasm32-unknown-unknown --test "*"` runs all integration tests.

Though the argument forwarding could be done from the test runner, I think it would be better to enable this functionality from `wasm-pack` as it is the recommended way of testing `wasm` applications. For me the change should be done here:

https://github.com/rustwasm/wasm-pack/blob/081861b10e2e81a230701510172f80aaa4f92e3d/src/test/mod.rs

**Comment by daxpedda** [comment]
I agree that if `wasm-bindgen-test-runner` is working correctly, then this is a problem that should be solved with `wasm-pack` and not here.

> Is this really an issue with `wasm-bindgen-test-runner`? I just tested this on a project without using `wasm-pack` and noticed the behaviour is correct, i.e. using `cargo test --target wasm32-unknown-unknown --lib --bins` runs the unit tests only and `cargo test --target wasm32-unknown-unknown --test "*"` runs all integration tests.

That is strange, because when I answered up there I tried this locally and it didn't succeed. I will look into it later.

**Comment by daxpedda** [comment]
> Is this really an issue with `wasm-bindgen-test-runner`? I just tested this on a project without using `wasm-pack` and noticed the behaviour is correct, i.e. using `cargo test --target wasm32-unknown-unknown --lib --bins` runs the unit tests only and `cargo test --target wasm32-unknown-unknown --test "*"` runs all integration tests.

Not sure what I did the last time, but this definitely works as expected.

@stan-irl this is an issue with `wasm-pack` and not `wasm-bindgen`.

**Comment by stan-irl** [comment]
No worries. I'll follow up there. Thanks for looking
