### ISSUE TITLE
Memory leak in chrome when calling async wasm functions with devtools open

### ISSUE THREAD

**Issue by SankaD** [rustwasm/wasm-bindgen#3437]
### Describe the Bug

Not sure if this is a bug from wasm-bindgen or chrome, putting this here since it gives different behaviours depending on if it's release build or not. 

But this doesn't occur if I call a sync function repeatedly. But if I call an async function, it starts growing memory until page goes OOM. 

If it's not build in release or the function is a sync method, the memory doesn't keep increasing.

### Steps to Reproduce

1. Build some code with wasm function in release mode (I used wasm-pack --release. This doesn't happen with dev build)
2. Call an async wasm function from js code repeatedly. (I used a setInterval(xxx, 100) call ) in a web page. 
3. Load the page in chrome with devtools open
4. In chrome task manager, memory keeps increasing. But the wasm.memory.buffer size is not changing (keeps around 20MB for my code)

### Expected Behavior

To not keep increasing the memory

### Actual Behavior

Memory keeps increasing

![image](https://github.com/rustwasm/wasm-bindgen/assets/2997480/2faa5d42-e686-4f05-9b12-9f8bb534e925)

![image](https://github.com/rustwasm/wasm-bindgen/assets/2997480/4306e1dd-7b15-48f2-a4d0-feb3a057e179)

**Comment by daxpedda** [comment]
Could you provide a complete minimal example?

**Comment by robertpauson** [comment]
Is the trigger for this happening opening DevTools after loading page?

**Comment by SankaD** [comment]
> Could you provide a complete minimal example?

Will try to create a minimal example within the week

> Is the trigger for this happening opening DevTools after loading page?

When loading the page with devtools open. (only for release build)

**Comment by daxpedda** [comment]
> When loading the page with devtools open.

If it only happens if the devtools are open, that's probably not an issue on our end.
Sometimes having devtools open can leak memory because of logging and profiling.

**Comment by SankaD** [comment]
I was able to recreate the issue with files generate from webpack and WasmPackPlugin. Issue is not there if the files are generated from wasm-pack directly.

https://github.com/SankaD/wasm-chrome-test

**Comment by daxpedda** [comment]
I don't know anything about webpack, but it might be that it just changes some logging output which makes it cause the memory leak. It might also be that `wasm-pack`, which runs `wasm-opt` makes specific optimizations that prevent this issue.

In any case, if it really only happens as long as the devtools are open, it's not something we can "fix" per se.

Feel free to re-open if you discover that the memory leak is also present when the devtools are not open!
