### ISSUE TITLE
Is it possible to create a file in a directory? (limited file system access)

### ISSUE THREAD

**Issue by romanusname** [rustwasm/wasm-bindgen#3439]
### Summary

Is it possible to create a file in a directory?

### Additional Details

wasm files have limited access to the file system.
 
**I can create a file.**
`fs::write("test.txt", "context").expect("error");`
 
**But I can't create a file in the directory.**
`fs::write("myDirectory/test.txt", "context").expect("error"); `

**Also I can't create a directory.**
`fs::create_dir("newDirectory").expect("error");`

I get an error - `Unable to write file: Os { code: 76, kind: Uncategorized, message: "Capabilities insufficient" }`
 
Is it possible to create a file in a directory?
I need to create many files. I want to group them in a separate directory

**Comment by daxpedda** [comment]
`std::fs` isn't implemented for the `wasm32-unknown-unknown` target, so creating a file shouldn't work either.

You can use `web-sys` to access Web APIs that are meant to offer a file system access or an equivalent:
- https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API
- https://developer.mozilla.org/en-US/docs/Web/API/File_and_Directory_Entries_API
