### ISSUE TITLE
failed wasm compilaiton because of locals exceed maximum

### ISSUE THREAD

**Issue by funlennysub** [rustwasm/wasm-bindgen#3451]
### Describe the Bug

I have a crate that works with game's save file, i parse everything in `SaveFile` struct that holds a few fields, one of them is `forge`, this struct has a method that uses a large hashmap that contains "definitions" for specific IDs that save file can have, `SCHEMATICS` is said hashmap:

![image](https://github.com/rustwasm/wasm-bindgen/assets/26184007/eddfd877-18df-4c0c-92a1-e13371764884)

Calling a function that uses that hashmap causes `locals exceed maximum` error when trying to build a wasm file.

### Steps to Reproduce

1. Clone [this repo](https://github.com/funlennysub/drg-save-editor/tree/wasm_issue) (wasm_issue branch)
2. Uncomment [this line](https://github.com/funlennysub/drg-save-editor/blob/wasm_issue/editor_ui/src/components/file_upload.rs#L19)
3. Change [this line](https://github.com/funlennysub/drg-save-editor/blob/wasm_issue/editor_core/src/save_file/mod.rs#L67) to `forge: Forge::from_gvas(gvas)?,`
4. Run `cargo build` in main directory
5. Build `editor_ui` with `trunk build` or `wasm-bindgen`

### Expected Behavior

Wasm generating with no errors

### Actual Behavior

throws an error:
```
error: failed getting Wasm module for 'drg-save-editor\target\wasm32-unknown-unknown\debug\editor_ui.wasm'

Caused by:
    0: failed to parse input as wasm
    1: failed to parse code section
    2: locals exceed maximum (at offset 1931704)
2023-05-24T16:54:38.126342Z ERROR ❌ error
error from HTML pipeline

Caused by:
    0: error from asset pipeline
    1: wasm-bindgen call returned a bad status
```

### Additional Context

More info in original [issue](https://github.com/thedodd/trunk/issues/546) on trunk repo

**Comment by daxpedda** [comment]
This is an issue with [`wasmparser`](https://crates.io/crates/wasmparser):
https://github.com/bytecodealliance/wasm-tools/blob/wasmparser-0.78.2/crates/wasmparser/src/operators_validator.rs#L157-L159

There isn't much that can be done about this in `wasm-bindgen`, as far as I understand it the parser doesn't allow for more then 50000 local variables, which somehow you have hit:
https://github.com/bytecodealliance/wasm-tools/blob/wasmparser-0.78.2/crates/wasmparser/src/limits.rs#L29

You can see how you can figure out which function it is here: https://github.com/bytecodealliance/wasm-tools/issues/665. You then have to split it into multiple functions to avoid hitting that limit.

**Comment by funlennysub** [comment]
one much simpler solution i found is it to use `opt-level = "s"` for debug builds since apparently this problem disappears in release mode
