### ISSUE TITLE
Audio worklet demo 'run.sh' not working

### ISSUE THREAD

**Issue by maxwalley** [rustwasm/wasm-bindgen#3452]
When I run run.sh I get this error message: 'error: package(s) `wasm-bindgen-cli` not found in workspace'

I am running this on a Mac with an M1 chip and this version of Cargo: cargo 1.71.0-nightly (569b648b5 2023-05-05)

**Comment by daxpedda** [comment]
Did you install the `wasm-bindgen` binary?
Use `cargo install wasm-bindgen-cli`.
See [the Rust book](https://doc.rust-lang.org/1.69.0/book/ch14-04-installing-binaries.html).

**Comment by maxwalley** [comment]
Yeah, sorry this is my fault. I was trying to run the demo outside of the repo. Running inside the full repo fixed the issue
