### ISSUE TITLE
Web Locks API?

### ISSUE THREAD

**Issue by benwr** [rustwasm/wasm-bindgen#3456]
I'm working on a project that could benefit from using the [Web Locks API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Locks_API) via web-sys.

I _think_ this API isn't currently available - is that right? If so, is it in-scope for the project / would this be a good issue for a first-time contributor (me)?

**Comment by Solo-steven** [comment]
I would like take it as my first issue if no one is work on it ! Thanks ~
