### ISSUE TITLE
Exporting bigint slices panics

### ISSUE THREAD

**Issue by daxpedda** [rustwasm/wasm-bindgen#3461]
As of Rust v1.70, exporting a function like this:
```rust
#[wasm_bindgen]
pub fn test(_: &[u64]) {}
```
... will make it panic when called from JS:
```js
test([]);
```
```
panicked at 'misaligned pointer dereference: address must be a multiple of 0x8 but is 0x4'
```

Here is a minimal reproducible example:
https://github.com/daxpedda/wasm-bindgen-bigint-slice-issue

I confirmed the following scenarios:
- Only `u64` and `i64` integer types cause this issue.
- Rust v1.69 does not have this issue.
- The recent Rust changelog doesn't note any significant changes other then the upgrade to LLVM 16, which added default target features to Wasm:
  - Compiling with `-Ctarget-feature=-sign-ext,-mutable-globals` and `-Zbuild-std` on nightly-2023-06-03 does not fix the issue.
  - Compiling with `-Ctarget-feature=+sign-ext,+mutable-globals` on Rust v1.69 does not cause this issue.

This issue was originally discovered here: https://github.com/rustwasm/wasm-bindgen/actions/runs/5176047134/jobs/9324382988#step:7:409.

Update: apparently the bug is coming from https://github.com/rust-lang/rust/pull/98112.
It's possible to circumvent the check by just disabling `debug_assert`s.

**Comment by hamza1311** [comment]
Can you reproduce this error? It would be good to file an issue for Rust so the regression can be addressed.

**Comment by daxpedda** [comment]
It's pretty easy to reproduce, I made a whole example here: https://github.com/daxpedda/wasm-bindgen-bigint-slice-issue.

I don't think it's a Rust issue, but it definitely goes over my head. I don't know enough about the Rust/`wasm-bindgen` ABI surface to understand what's going on here let alone what needs to be done.

**Comment by Liamolucko** [comment]
It looks like this is happening because `__wbindgen_malloc`, the function that all the JS glue uses to allocate memory, always aligns everything to the alignment of a `usize` (so, 4 bytes):

https://github.com/rustwasm/wasm-bindgen/blob/5453e332dc8222a1dc3f4d8dadb0d922da528790/src/lib.rs#L1571-L1588

The best fix is probably to add an `align` argument to `__wbindgen_malloc` (and `__wbindgen_realloc` and `__wbindgen_free`) instead of hard-coding it.
