### ISSUE TITLE
Change the locals exceed maximum error to a warning

### ISSUE THREAD

**Issue by Houski** [rustwasm/wasm-bindgen#3469]
**It has come to my attention that this is a "wasm-parser" issue, which is not in the purview of wasm-bindgen, so this can be ignored, thanks. :)**

### Motivation

We are developing a project in the Rust Leptos web framework.

When we do a development build with Rust at opt level 0, there are more than 50k local bindings created, causing wasm-bindgen to throw an error that the max limit is hit.

When we do a release compile and do an opt level of 1 or above, there are less than 50k bindings - so only the dev compilations have more than 50k variables. 

We need to use opt-level 0 for fast dev build iterations. The optimized builds take much longer.

This will likely be a fairly common occurrence for anyone using a Rust web framework to make a website of any large scale.

### Proposed Solution

Change the errors to warnings where it is logical.

### Alternatives

Possibly a flag to override the max local variable setting and increase it from 50k? This is not as ideal, as the tooling we use would then have to all pass that flag in (Cargo Leptos, etc), and it would not really make much sense for them to think of setting it higher.

### Additional Context

This is the error I'm referring to, that limits our ability to even compile an opt-level 0 build for dev iterations:

```
Caused by:
    0: at `/home/alex/.cargo/git/checkouts/cargo-leptos-f550c444455a3716/34dd942/src/compile/front.rs:111:10`
    1: failed getting Wasm module for 'target/front/wasm32-unknown-unknown/debug/website.wasm'
    2: failed to parse input as wasm
    3: failed to parse code section
    4: locals exceed maximum (at offset 20291387)
```

**Comment by daxpedda** [comment]
Duplicate of #3451.
