### ISSUE TITLE
Allow bare objects to be passed to functions taking exported types

### ISSUE THREAD

**Issue by hamza1311** [rustwasm/wasm-bindgen#3493]
### Motivation

At the moment, when calling a function exported by wasm-bindgen, there's no way to convert to Rust structs without creating a class instance of the exported wasm-bindgen type.

Calling without creating a class instance is needed in cases where a class instance cannot be created, such as when interfacing with existing code is needed. 

### Proposed Solution

Given the following code
```rust
#[wasm_bindgen]
pub struct Data {
    key_id: String,
    name: String,
}

#[wasm_bindgen]
pub fn do_work(data: Data) -> String {
    format!(r#"
        key_id: {}
        name: {}
    "#, data.key_id, data.name)
}
```

The following call should be possible
```js
do_work({
  key_id: 'key_id',
  name: 'name',
})
```

See https://github.com/rustwasm/wasm-bindgen/issues/3468#issuecomment-1589958213

### Alternatives

Use imported types with duck typing. Type imports with duck typing don't always work though. In my case, this is shared code and I need everything to also be usable from rust

**Comment by jkomyno** [comment]
Alternative projects that integrate `wasm_bindgen` to support creating structs in place (i.e., what OP referred to as "duck typing") are:
- [tsify](https://github.com/madonoharu/tsify/)
- [serde_wasm_bindgen](https://github.com/cloudflare/serde-wasm-bindgen)

**Comment by Liamolucko** [comment]
There's also the older issue #2645 open about this.

**Comment by daxpedda** [comment]
Closing this in favor of #2645 then.
