### ISSUE TITLE
View Transition API

### ISSUE THREAD

**Issue by itsezc** [rustwasm/wasm-bindgen#3517]
### Motivation

Add ViewTransition API to `web-sys` crate, currently only supported in Chrome but likely in Safari and Firefox soon.

### Proposed Solution

Creating bindings for it

### Alternatives

N/A

### Additional Context

N/A

**Comment by daxpedda** [comment]
PR's are welcome!

This should be quite straightforward, see [the Guide on how to add more APIs through WebIDL](https://github.com/rustwasm/wasm-bindgen/blob/main/guide/src/contributing/web-sys/supporting-more-web-apis.md).

**Comment by daxpedda** [comment]
Fixed by #3598.
