### ISSUE TITLE
proc_macro tokenstream dependency broken

### ISSUE THREAD

**Issue by David-OConnor** [rustwasm/wasm-bindgen#353]
```
error[E0599]: no function or associated item named `empty` found for type `proc_macro::TokenStream` in the current scope. 
```

```
 |             TokenStream::Nightly(proc_macro::TokenStream::empty())
 |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `proc_macro::TokenStream`
```

**Comment by chinedufn** [comment]
Vaguely recall seeing this a while ago and if I remember correctly I just needed to update to the latest nightly.

**Comment by alexcrichton** [comment]
Indeed updating dependencies should do the trick here! If it doesn't though please let us know!

**Comment by David-OConnor** [comment]
I believe I'm running the latest nightly: rustc 1.28.0-nightly (e3bf634e0 2018-06-28).

**Comment by alexcrichton** [comment]
@David-OConnor have you tried `cargo update -p proc-macro`?
