### ISSUE TITLE
Request to release a new version of web-sys

### ISSUE THREAD

**Issue by stephanemagnenat** [rustwasm/wasm-bindgen#3530]
### Motivation

I need [`WorkerGlobalScope.performance`](https://github.com/rustwasm/wasm-bindgen/commit/4aae6b38e6bed37d3b908f6e99611549840ab395) for adding timing support in web workers in [Rust CV](https://github.com/rust-cv/cv/pull/75).

### Proposed Solution

A new minor release.

**Comment by daxpedda** [comment]
I would have liked to fix https://github.com/rustwasm/wasm-bindgen/pull/3483 first, but unfortunately we don't seem to have the time.

@stephanemagnenat if you replicate https://github.com/rustwasm/wasm-bindgen/pull/3475 it would help to get a release now instead of later.

**Comment by stephanemagnenat** [comment]
@daxpedda thanks for the fast answer. Is there a script to bump minor versions, or is it a manual process so far?

**Comment by daxpedda** [comment]
AFAIK a manual process. It should be straightforward with a couple of search-and-replace.

**Comment by gabrielDevlog** [comment]
Hi,

A release would be great. Is there any ETA for this ?

Thanks

**Comment by daxpedda** [comment]
There is none AFAIK.

You can get the process started by replicating #3475.

**Comment by gabrielDevlog** [comment]
Ok i'll try. Should i follow this process: https://rustwasm.github.io/docs/wasm-bindgen/contributing/publishing.html

**Comment by daxpedda** [comment]
If you just scroll up and look at the earlier discussion you will find all your answers.

> Ok i'll try. Should i follow this process ? https://rustwasm.github.io/docs/wasm-bindgen/contributing/publishing.html

I've done it manually so far because I didn't know about this tool, feel free to try it though.

**Comment by hamza1311** [comment]
@daxpedda do you have permissions to make a release? I was thinking of setting up a GitHub actions workflow for it, but I don't have the permissions on crates.io and a secret needs be added before publishing can be done

**Comment by daxpedda** [comment]
I do not, but the way it worked until now is to set everything up and ping Alex Crichton.
Making an action for it would be ideal though!

**Comment by gabrielDevlog** [comment]
Well I'm trying manually but its not as easy as it seems. How do you get this value "APPROVED_SCHEMA_FILE_HASH" ?

https://github.com/rustwasm/wasm-bindgen/pull/3475/files#diff-515c29e8b5cfb75260c999069bc92df2bf301e4bbeddafd858b269cfac79d9f4R11

**Comment by daxpedda** [comment]
You can run this test to see what the value is supposed to be:
https://github.com/rustwasm/wasm-bindgen/blob/bfe644fe13ee84b190345c53d419a0919a4a946f/crates/shared/src/schema_hash_approval.rs#L13-L16

**Comment by daxpedda** [comment]
The schema was already bumped in #3651.

**Comment by gabrielDevlog** [comment]
Just to let you know, I haven't had the time to take care of it yet, and I probably won't next week either.
