### ISSUE TITLE
Convert JsValue to a string without "JsValue(...)"

### ISSUE THREAD

**Issue by ten3roberts** [rustwasm/wasm-bindgen#3538]
### Motivation

The `format!("{value}")` allows a `JsValue` to be converted to a string. However, it will wrap the value in a "JsValue(str)" like a tuple struct before returning.

### Proposed Solution

Adding a method allowing you to use the underlying `as_debug_string` function without being wrapped in the newtype debug.

### Alternatives

Using `as_string` works for normal strings, but not for string-*like* objects, such as thrown errors wrapping a string

**Comment by snOm3ad** [comment]
You could implement `Display` for `JsValue`, the impl is the same as `Debug` but without the wrapping.

**Comment by hamza1311** [comment]
I don't think `JsValue` should implement `Display`, for the same reason there is no derive macro for `Display`: there is no absolute way to format the value.

[`js_sys::Object::to_string`](https://docs.rs/js-sys/latest/js_sys/struct.Object.html#method.to_string) for calling the JS version of toString on an object. You can also use `unchecked_ref` to convert a JsValue to a `js_sys::JsString ` and use that

**Comment by ten3roberts** [comment]
Perhaps stupid question, but how would I get an `js_sys::Object` or stringify any JsValue? not just `Object`

**Comment by daxpedda** [comment]
If your `JsValue` is an `Object` or `JsString` you can just use [`JsCast`](https://docs.rs/wasm-bindgen/0.2.87/wasm_bindgen/trait.JsCast.html) to do your conversions.

I'm going to close this: as hamza1311 already said, there is no absolute way to format every value, certainly not `JsValue`.

Please feel free to continue posting here if there are still any open questions.
