### ISSUE TITLE
feat: add `id` to RtcDataChannel bindings

### ISSUE THREAD

**Issue by DougAnderson444** [rustwasm/wasm-bindgen#3542]
https://github.com/rustwasm/wasm-bindgen/blob/b76af3b6d0342231289cbebb6830a76e64be48a7/crates/web-sys/src/features/gen_RtcDataChannel.rs#L21

I see `label` is here, could we also add the `id` property to `RtcDataChannel` ? 

https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel/id

**Comment by daxpedda** [comment]
Yes, this is quite straightforward to accomplish, see [the `wasm-bindgen` Book](https://github.com/rustwasm/wasm-bindgen/blob/main/guide/src/contributing/web-sys/supporting-more-web-apis.md) on how to do just that.
Let me know if you need any help.

**Comment by DougAnderson444** [comment]
Excellent direction, thanks I'll do that. 
I take it since the `id` is between `0` and `65,534` would be an `unsigned long`?

```
readonly attribute unsigned long id;
```

I didn't see the definition for the difference between `unsigned long` and `unsigned short` anywhere

**Comment by DougAnderson444** [comment]
I figured out that `unsigned short` compiles to `u16` which is the `65,534` we need
