### ISSUE TITLE
Error while importing "__wbindgen_placeholder__"."__wbindgen_string_new": unknown import. Expected Function(FunctionType { params: [I32, I32], results: [I32] })

### ISSUE THREAD

**Issue by coder-xiaotian** [rustwasm/wasm-bindgen#3559]
### Describe the Bug

I have a swc plugin ["use-client"](https://github.com/coder-xiaotian/swc-useclient), I want to print some info when run this plugin, so I used `web_sys::console::log_1` in my [code](https://github.com/coder-xiaotian/swc-useclient/blob/de9dedb9ef8e69aff5a7e6b5727a193e0d8e42d3/transform/src/lib.rs#L23), when I npm link to this repo https://github.com/coder-xiaotian/antd-useclient, then`npm run dev` to start, it has the error of below:
```
Caused by:
    0: failed to invoke `/Users/xiaotian/personal/tech/my-project/use-client/target/wasm32-wasi/release/swc_plugin_use_client.wasm` as js transform plugin at /Users/xiaotian/personal/tech/my-project/use-client/target/wasm32-wasi/release/swc_plugin_use_client.wasm
    1: Error while importing "__wbindgen_placeholder__"."__wbindgen_string_new": unknown import. Expected Function(FunctionType { params: [I32, I32], results: [I32] })
- error Error: Cannot find module '/Users/xiaotian/personal/tech/my-project/antd-useclient/.next/fallback-build-manifest.json'
```

### Additional Context
build command: cargo build-wasi --release
rustc version: rustc 1.70.0 (90c541806 2023-05-31)

**Comment by snOm3ad** [comment]
This might be related to #3233. You need to file a bug with SWC. See also https://github.com/rustwasm/wasm-bindgen/issues/3421#issuecomment-1663198679

**Comment by coder-xiaotian** [comment]
> 

Thanks for your reply. It seems like I made a mistake. I will study it again.

**Comment by coder-xiaotian** [comment]
> It doesn't look like SWC plugins use `wasm-bindgen` at all, actually, so nothing `wasm-bindgen`-related is going to work. It looks like `tracing` is what SWC expects plugins to use for logging, so you should probably use that instead.

Thanks for your reply. It seems like I made a mistake. I will study it again.

**Comment by daxpedda** [comment]
`wasm-bindgen` doesn't support WASI to begin with, so I don't think this is really supposed to work at all.

Feel free to continue discussion here if any more questions come up!
