### ISSUE TITLE
Structures containing usize seems to create BigInt dependency in generated JavaScript bindings

### ISSUE THREAD

**Issue by nwoods-cimpress** [rustwasm/wasm-bindgen#3564]
### Describe the Bug

For some reason, having a `usize` in a structure seems to result in bindings that have a dependency on `BigInt`, but using `u32` instead of the `usize` does not trigger the same dependency.  Because `usize` is the same thing as `u32` on JavaScript platforms, I would expect these to create identical results.

### Steps to Reproduce

1. Unpack `wasm-bindgen-bigint-issue.zip` ([wasm-bindgen-bigint-issue.zip](https://github.com/rustwasm/wasm-bindgen/files/12407820/wasm-bindgen-bigint-issue.zip))
2. `wasm-pack build --target nodejs`
3. Scrutinize the generated `wasm_bindgen_bigint_issue.js`
4. In `src/lib.rs`, change `pub val: usize` to `pub val: u32`
5. `wasm-pack build --target nodejs`
6. Scrutinize the generated `wasm_bindgen_bigint_issue.js`

### Expected Behavior

I would expect the `wasm_bindgen_bigint_issue.js` generated by steps 3 and 6 to be identical.

### Actual Behavior

The two files are not identical; there are two snippets present when `val` is a `usize`:

````
module.exports.__wbindgen_bigint_from_u64 = function(arg0) {
    const ret = BigInt.asUintN(64, arg0);
    return addHeapObject(ret);
};
````

````
module.exports.__wbindgen_error_new = function(arg0, arg1) {
    const ret = new Error(getStringFromWasm0(arg0, arg1));
    return addHeapObject(ret);
};
`````

**Comment by daxpedda** [comment]
> 1. Unpack `wasm-bindgen-bigint-issue.zip`

I believe you forgot to provide a link to that.
A minimal example would indeed be appreciated, preferably please just post the code here instead of upload a file.

**Comment by nwoods-cimpress** [comment]
Ugh I apologize; I had the `wasm-bindgen-bigint-issue.zip` prepped but I neglected to attack it... thanks for your patience!

**Comment by daxpedda** [comment]
Not entirely sure whats going on in that example, but it's using `serde-wasm-bindgen`, which isn't maintained by the RustWasm team. Taking a quick look at the [README](https://crates.io/crates/serde-wasm-bindgen), I can see that they specify `usize` is using `BigInt`, so I assume you will have to take it up with them.

If it turns out to be an issue on `wasm-bindgen`s side, please don't hesitate to leave a comment here again!

**Comment by nwoods-cimpress** [comment]
I'll take this to the `serde-wasm-bindgen` folks; thanks for the help!
