### ISSUE TITLE
The 'imports::versions' test fails on OSX

### ISSUE THREAD

**Issue by kzvi** [rustwasm/wasm-bindgen#357]
I don't know why but here is the output: https://gist.github.com/kzvi/bf225ec60343397938dd5fbd97479678

OS: OSX 10.13.5 
Node: `v10.5.0` 
NPM: `6.1.0` 
rustc: `rustc 1.28.0-nightly (e3bf634e0 2018-06-28)` 
cargo: `cargo 1.28.0-nightly (e2348c2db 2018-06-07)`

**Comment by alexcrichton** [comment]
It looks like there's some errors there about node dependencies, perhaps `npm install` or the equivalent is required?

**Comment by sendilkumarn** [comment]
@alexcrichton I think it is mostly because of using`require` and webpack bundling. We need to add in extra parameters and supply it through the configuration file

**Comment by sendilkumarn** [comment]
I think we should add in `webpack.config.js` and supply `target: node`.  I will first try this locally and confirm.

**Comment by alexcrichton** [comment]
@sendilkumarn hm I think that's [already done](https://github.com/rustwasm/wasm-bindgen/blob/4ceaf3e0f47442db01ac3bdb1220b5f706bf958f/tests/all/main.rs#L72)?
