### ISSUE TITLE
IndexedDb storage state remains after test run

### ISSUE THREAD

**Issue by gitmalong** [rustwasm/wasm-bindgen#3571]
I expected the IndexedDb storage to be empty on each run of my test. Even tests have executed and started again there is still data from the last tests.

```rust
wasm-pack test --chrome --headless 
```

Should it not be consistent to cargo test which uses a fresh state for each test? How can I start with an empty indexeddb?

**Comment by daxpedda** [comment]
You have to clear it manually in the test. This is similar to how when you are using regular `cargo test` you have to clean up generated files.

There might be a way to communicate this to the Webdriver, so it might be prudent to look into that.

**Comment by gitmalong** [comment]
According to my research I have found no way to do the clearing via `webconfig.json` but it seems there is an API: https://developer.mozilla.org/en-US/docs/Web/API/Storage/clear

**Comment by daxpedda** [comment]
> Is that something you think should be done by the test runner or users have to add manually to each test? Having an macro option to start with a fresh environment on each test run would be great.

As I was saying earlier, this is normal for `cargo test` as well, so I don't really see a reason for `wasm-bindgen-test` to do otherwise. A macro like this could also be implemented externally by a separate crate, so I would also not be in favor of putting this into `wasm-bindgen-test`.

**Comment by daxpedda** [comment]
I'm gonna close this for now. If `wasm-bindgen-test` requires adjustments to support this issue, feel free to comment here so we can re-open and discuss how `wasm-bindgen-test` can help in that case.
