### ISSUE TITLE
Error compiling to wasm `index out of bounds` when implementing `IntoWasmAbi`

### ISSUE THREAD

**Issue by dgkf** [rustwasm/wasm-bindgen#3574]
### Describe the Bug

Introducing implementations of `WasmDescribe`, `IntoWasmAbi` and `FromWasmAbi` cause builds to fail with error:

```
[INFO]: 🎯  Checking for the Wasm target...
[INFO]: 🌀  Compiling to Wasm...
   Compiling test-wasm-bindgen v0.1.0 (~/Projects/Programming/test-wasm-binding)
    Finished release [optimized] target(s) in 0.10s
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasm-bindgen-cli-support-0.2.87/src/descriptor.rs:218:15
```

### Steps to Reproduce

1. Create a simple rust lib crate (I used the `hello-world` example as a basis)
1. Introduce a return type that requires an implementation of `IntoWasmAbi`/`FromWasmAbi`
1. Attempt to build
1. Observe error

see this [repo with the code used to minimally produce the bug](https://github.com/dgkf/test-wasm-bindgen)

### Expected Behavior

The build succeeds

### Actual Behavior

The build fails with an `index out of bounds` error

### Additional Context

This seems to have popped up from time to time in `wasm-bindgen`'s history with,
seemingly resolved by matching dependency versions ([#3441](https://github.com/rustwasm/wasm-bindgen/issues/3441), [#2776](https://github.com/rustwasm/wasm-bindgen/issues/2776), among others).

#### Troubleshooting

* Build error only arises when `IntoWasmAbi`/`FromWasmAbi` are implemented for a new type.
* As far as I can tell, dependency versions are all the same. I've tried many 
  of the older versions that resolved previous issues to no avail (`0.2.78`, `0.2.79`, `0.2.84`).
* Attempted reinstalling `wasm-pack` with `wasm-pack --locked` to no avail

**Comment by dgkf** [comment]
I'm realizing that perhaps the intention is not to be able to define arbitrary types, but to coerce a type into one of the already provided WasmAbi options. I had sort of hoped that `wasm-bindgen` would do some magic for simple structs, but I'm not seeing evidence of it in the docs. 

I was loosely trying to follow [this example](https://rustwasm.github.io/wasm-bindgen/contributing/design/rust-type-conversions.html?highlight=IntoWasmAbi#from-rust-to-js), and I'm not sure if I misunderstood the struct here to be an example when instead it is just meant to show a special case.

**Comment by daxpedda** [comment]
> I'm realizing that perhaps the intention is not to be able to define arbitrary types, but to coerce a type into one of the already provided WasmAbi options.

Pretty much, in your minimal example you didn't add a description to `WasmDescribe`, so this can't really work. But all of this is subject to the ABI implemented by `wasm-bindgen` which you can't really expand.
