### ISSUE TITLE
web_sys: missing set_transform with matrix function

### ISSUE THREAD

**Issue by stephanemagnenat** [rustwasm/wasm-bindgen#3578]
### Motivation

The function [setTransform](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/setTransform) on Canvas 2D can accept a matrix on modern browsers. This is currently not exposed in `web_sys`. However, the sister function `getTransform` [is exposed](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.CanvasRenderingContext2d.html#method.get_transform).

### Proposed Solution

Expose a `set_transform_with_matrix` function, to match the `get_transform` ones.

**Comment by stephanemagnenat** [comment]
No, if you look [at the documentation page](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/setTransform), there is a second version that takes a single `DomMatrix` parameter, and that was introduced at the same time `getTransform` was.

So I find it illogical that `web_sys` provides `get_transform` but not that version of `set_transform`.

**Comment by daxpedda** [comment]
Thanks!
Made a fix here: #3580.

**Comment by stephanemagnenat** [comment]
Thank you for the very fast answer!

A small question, `get_transform` returns a `DomMatrix` while the new `set_transform` takes a `DomMatrix2dInit`, are these compatible? A typical use [as described here](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/setTransform#retrieving_and_passing_a_dommatrix_object) is to combined these two functions to save and restore the canvas transformation matrix.

**Comment by daxpedda** [comment]
It should work, because `DOMMatrixInit` inherits `DOMMatrix2DInit`, unfortunately our WebIDL generator doesn't support inheritance on dictionaries. I think you can use `unchecked_into()`, but I'm not entirely sure.
