### ISSUE TITLE
Raw identifiers cause error

### ISSUE THREAD

**Issue by cam-narzt** [rustwasm/wasm-bindgen#3586]
### Describe the Bug

Trying to use a struct with a raw identifier in wasm causes an error to be thrown.

### Steps to Reproduce

```rust
use wasm_bindgen::prelude::*;
#[wasm_bindgen]
pub struct Column {
  pub r#type: u8,
}
```

### Expected Behavior

I expect valid rust to compile to valid wasm.

### Actual Behavior

`rustc: custom attribute panicked`

### Additional Context

[Docs about raw identifiers](https://doc.rust-lang.org/rust-by-example/compatibility/raw_identifiers.html)

**Comment by daxpedda** [comment]
Happy to review a PR fixing this!
Should be pretty straightforward with `syn`.

**Comment by Liamolucko** [comment]
[`quote::format_ident`](https://docs.rs/quote/latest/quote/macro.format_ident.html) will probably be useful here (similar to #3541).

**Comment by Solo-steven** [comment]
Hi, I would like to take this issue, and I believe we can simply solve it by adding `format_ident` to theree and add `format_ident` to make `js_name` handle raw identifier correctly.

https://github.com/rustwasm/wasm-bindgen/blob/373b7a57be3b8632499ce2198ea832fe216ef7fd/crates/macro-support/src/parser.rs#L422
<img width="865" alt="Screenshot 2023-09-16 at 2 50 45 PM" src="https://github.com/rustwasm/wasm-bindgen/assets/67428009/3e724a22-6ebd-489f-85e2-eafb6eadeb16">

it seems that `unraw` method belongs to the `Ident` structure in `syn` crate, but the `Ident` structure we use seems from the `proc_macro` mostly, so I think if we gonna using `unraw` method, maybe we need to convert Ident from `proc_macro` to `ident` from `syn` crate/

**Comment by daxpedda** [comment]
It sounds to me like `format_ident` should do the trick then if `unraw` requires unnecessary conversions.
I'm happy to review a PR.

**Comment by Liamolucko** [comment]
> it seems that `unraw` method belongs to the `Ident` structure in `syn` crate, but the `Ident` structure we use seems from the `proc_macro` mostly, so I think if we gonna using `unraw` method, maybe we need to convert Ident from `proc_macro` to `ident` from `syn` crate/

We're using `proc_macro2::Ident`, not `proc_macro::Ident`, and `syn::Ident` is just a re-export of `proc_macro2::Ident`, so there's no conversion needed.

**Comment by Solo-steven** [comment]
Hi @Liamolucko thanks for your reply, You are right! it's my fault that confused with `proc_macro` and `proc_marco2`, `unraw` would work as `format_ident`, thanks for your catch ~
