### ISSUE TITLE
Depend on specific/minimum Node.js version for tests?

### ISSUE THREAD

**Issue by jhenninger** [rustwasm/wasm-bindgen#360]
I was wondering why some tests (namely the date.toLocale* methods) were failing for me locally and it turns out the Node.js version is the culprit. Examples:

```js
new Date(Date.UTC(2012, 11, 20, 3, 0, 0)).toLocaleString('en-GB', { timeZone: 'UTC' })

'12/20/2012, 3:00:00 AM' // Node 8.11.3 (LTS)
'20/12/2012, 03:00:00' // Node 10.5.0 (Current)
```

```js
new Date(Date.UTC(2012, 11, 20, 3, 0, 0))
  .toLocaleDateString('de-DE',  { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })

'2012 M12 20, Thu' // Node 8.11.3 (LTS)
'Donnerstag, 20. Dezember 2012' // Node 10.5.0 (Current)
```

Now I don't understand why the second example is green on Travis/Appveyor (which appear to be using Node 10+) when [the expected output of `toLocaleDateString` matches neither of the strings I got above](https://github.com/rustwasm/wasm-bindgen/blob/cf08aee341838e2faa355c8a2a53be72fcbee3a1/tests/all/js_globals/Date.rs#L161-L163).

Apart from the `toLocale*` changes there are also some differences in the assert module which is used in the tests, e.g `assert.strictEqual(NaN, NaN)` fails in Node 8.11.3 but succeeds in 10.5.0.
Node 10 also recommends using the new [strict mode](https://nodejs.org/docs/latest-v10.x/api/assert.html#assert_strict_mode) of the assert module instead.

**Comment by jonathan-s** [comment]
I'm not sure that it's due to the version of Node necessarily, rather it appears it is something that you need to require when installing / compiling node. [See here](https://nodejs.org/api/intl.html#intl_options_for_building_node_js) 

So instead of the current way installing node in Travis it should probably be `nvm install -s 10.5 --with-intl=full-icu --download=all` or perhaps one of the other options listed in the link. 

@jhenninger Would you like to check to see if that solves the issue?

**Comment by sendilkumarn** [comment]
@jhenninger yes @jonathan-s is correct. I too faced the same error and it is based on the OS. That is why it works well in CI without any issues.

**Comment by jhenninger** [comment]
Thanks for clearing that up! (I'm on Arch Linux and the 10.5.0 version was installed using pacman, all other versions using nvm).

Besides the locale issue there are other version differences that can affect the tests though. E.g. `String.prototype.trimStart` and ` trimEnd` don't exist in in Node 8.x.

**Comment by alexcrichton** [comment]
I'd personally be in favor of aggressively following the newest standard and binding as many functions as it contains, regardless of whether the actual runtime supports the method. This matches what the `libc` crate does and it puts the onus on users to do version detection of their runtime (e.g. Node, Chrome, Firefox, etc). 

Version detection tends to be really tricky and highly specialized, so we wouldn't necessarily be able to get a good implementation in wasm-bindgen itself.

**Comment by sendilkumarn** [comment]
Thanks @alexcrichton for the clarification. With that I think the ticket can be closed. 

@jhenninger feel free to re-open if you have any further comments or issues with this.
