### ISSUE TITLE
vscode cant fetch metadata (rust-analyser)

### ISSUE THREAD

**Issue by murilosoaresp** [rustwasm/wasm-bindgen#3615]
I'm trying out wasm-bindgen but vscode (rust-analyser) is stuck at "Fetching: metadata" when I add

[dependencies]
wasm-bindgen = "0.2.74"

to my toml file.
There are no other dependencies.

The issue goes away if I remove the dependency.

Is this a known issue?

**Comment by daxpedda** [comment]
I assume you resolved this somehow?

**Comment by murilosoaresp** [comment]
> I assume you resolved this somehow?

Yes, it was just normal behaviour. There is some step named like "updating indexes" that takes really long when you dont update cargo frequently.
