### ISSUE TITLE
WebTransport.reliability() returns an unexpected value

### ISSUE THREAD

**Issue by rom1v** [rustwasm/wasm-bindgen#3626]
### Describe the Bug

[`WebTransport.reliability()`](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.WebTransport.html#method.reliability) returns an unexpected value, which is not one of the [`enum WebTransportReliabilityMode`](https://rustwasm.github.io/wasm-bindgen/api/web_sys/enum.WebTransportReliabilityMode.html) variants.

### Steps to Reproduce

```rust
        let web_transport = web_sys::WebTransport::new(url)?;
        JsFuture::from(web_transport.ready()).await?;
        let reliability = web_transport.reliability();
        info!("reliability = {reliability:?}");
        match reliability {
            web_sys::WebTransportReliabilityMode::Pending => info!("Pending"),
            web_sys::WebTransportReliabilityMode::SupportsUnreliable => info!("SupportsUnreliable"),
            web_sys::WebTransportReliabilityMode::ReliableOnly => info!("ReliableOnly"),
            _ => info!("unexpected reliability"),
        }
```

produces the following logs:

```
reliability = __Nonexhaustive
unexpected reliability
```

### Expected Behavior

The value returned by `reliability()` should be one of the variants of [`enum WebTransportReliabilityMode`](https://rustwasm.github.io/wasm-bindgen/api/web_sys/enum.WebTransportReliabilityMode.html).

### Actual Behavior

It returns a value which is not one of the enum variants (its `Debug` representation is `__Nonexhaustive`).

**Comment by daxpedda** [comment]
What browser are you using? This probably just returns `undefined`, as it's not supported by all browsers.

**Comment by rom1v** [comment]
> What browser are you using? This probably just returns undefined, as it's not supported by all browsers.

I'm testing on latest Chrome (more precisely chromium):

```
$ chromium --version
Chromium 117.0.5938.62 built on Debian trixie/sid, running on Debian trixie/sid
```
