### ISSUE TITLE
Alignment parameter is not passed to __wbindgen_free in js bindings.

### ISSUE THREAD

**Issue by Polish-Civil** [rustwasm/wasm-bindgen#3638]
https://github.com/rustwasm/wasm-bindgen/blob/f117406532fb2fd813d998e2ea98ad56e4a2ae4c/crates/cli-support/src/js/binding.rs#L1059

I suppose it should pass in `4` by default.

Built with: `--target wasm32-unknown-unknown -Z build
-std=std,panic_abort`
Generated binding with `--web`

**Comment by daxpedda** [comment]
Indeed, it was missed in #3463.
