### ISSUE TITLE
How to increase the memory size of the interpreter in wasm-bindgen-wasm-interpreter?

### ISSUE THREAD

**Issue by TheVeryDarkness** [rustwasm/wasm-bindgen#3653]
### Summary

I've run out of the memory (the field `mem` in Interpreter) when generating interface with wasm-bindgen (called from wasm-pack) for my project. Maybe my project is too big?
Will it be okay to simply extend the memory size when storing to a place that is not in the vector?

### Additional Details

The program panicked at wasm-bindgen-wasm-interpreter-0.2.87/src/lib.rs:311:32:
index out of bounds: the len is 1024 but the index is 375022

Run with `wasm-pack build`.

**Comment by daxpedda** [comment]
This seems like a rather big increase to me, more then two orders of magnitude.
Do you know what exactly is causing this?

Cc #3162.

**Comment by TheVeryDarkness** [comment]
Let me have a fork, increase the capacity and test it in my program.

**Comment by gustavohenke** [comment]
I have a similar issue when linking emscripten's libc (compiled to wasm32-unknown-unknown).

Here's a minimal reproduction repo (just run `./build.sh` - sorry, only tested on macOS for now. Assumes cargo and wasm-bindgen are in PATH):
https://github.com/gustavohenke/wasm-bindgen-libc-bug

(in fact, I hit #3315 unless `__environ.c` is ignored)

```
$ cargo --version
cargo 1.70.0 (ec8a8a0ca 2023-04-25)
$ rustc --version
rustc 1.70.0 (90c541806 2023-05-31)
$ clang --version
Homebrew clang version 16.0.6
Target: arm64-apple-darwin22.6.0
Thread model: posix
InstalledDir: /opt/homebrew/opt/llvm/bin
$ wasm-bindgen --version
wasm-bindgen 0.2.87
```

**Comment by TheVeryDarkness** [comment]
> Let me have a fork, increase the capacity and test it in my program.

Actually, simply increase the capacity won't work, as some other errors will show up.

**Comment by daxpedda** [comment]
> > Let me have a fork, increase the capacity and test it in my program.
> 
> Actually, simply increase the capacity won't work, as some other errors will show up.

In light of this I will close this issue.
