### ISSUE TITLE
updating wasm-bindgen/wasm-bindgen-cli to match whats in the Cargo.toml doesnt work

### ISSUE THREAD

**Issue by whattheflukz** [rustwasm/wasm-bindgen#3689]
Using leptos, running `cargo leptos watch` results in the following
`Error: at `/Users/flukz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-leptos-0.2.0/src/compile/front.rs:46:30`

Caused by:
    0: at `/Users/flukz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-leptos-0.2.0/src/compile/front.rs:112:10`
    1:

       it looks like the Rust project used to create this wasm file was linked against
       version of wasm-bindgen that uses a different bindgen format than this binary:

         rust wasm file schema version: 0.2.88
            this binary schema version: 0.2.87

       Currently the bindgen format is unstable enough that these two schema versions
       must exactly match. You can accomplish this by either updating this binary or
       the wasm-bindgen dependency in the Rust project.

       You should be able to update the wasm-bindgen dependency with:

           cargo update -p wasm-bindgen --precise 0.2.87

       don't forget to recompile your wasm file! Alternatively, you can update the
       binary with:

           cargo install -f wasm-bindgen-cli --version 0.2.88

       if this warning fails to go away though and you're not sure what to do feel free
       to open an issue at https://github.com/rustwasm/wasm-bindgen/issues!`

runninng 
`
cargo clean
'
'
cargo install -f wasm-bindgen-cli --version 0.2.88
`
does not solve the issue, same error appears, and ``wasm-bindgen -V`` reports 0.2.88
and in cargo.toml ``wasm-bindgen = "=0.2.88"``

**Comment by miketwenty1** [comment]
@whattheflukz not sure if this will fix your issue but for me I fixed it by running this first:
`cargo install wasm-server-runner --force`

**Comment by whattheflukz** [comment]
> Hey @whattheflukz, `cargo leptos` uses `wasm-bindgen-cli-support` crate, which is specified at `0.2.87` in `Cargo.lock`. Try to reinstall it (install with `--force`) and/or open issue there.

Hey @rkuklik appreciate the help,
I just tried adding 0.2.88 and that didn't seem to work either, tried searching my Cargo.lock file in this project for anything that is 0.2.87 and i couldn't find anything.
I didn't think to check Cargo.lock for cargo-leptos, but it looks like basically everything is 0.2.87 in there. Maybe I should just use that version for now?

**Comment by whattheflukz** [comment]
> That is up to you. If you want to update, just run `cargo install --force cargo-leptos` (as it ignores `Cargo.lock` by default), otherwise just lock `wasm-bindgen` with `cargo update -p wasm-bindgen --precise 0.2.87`.

Thanks! force installing cargo-leptos worked for 0.2.88, I really appreciate the help
