### ISSUE TITLE
How to disable floating-point in wasm-bindgen?

### ISSUE THREAD

**Issue by readygo67** [rustwasm/wasm-bindgen#3722]
I try to compile a rust to wasm, and then delpoyed wasm on blockchain. 
But floats cannot be used in Wasm contracts that are running on blockchains due to the non-determinism. Even I do not use floating point in my code,  after execute 
```
cargo build --target wasm32-unknown-unknown
wasm2wat target/wasm32-unknown-unknown/debug/xx.wasm  -o xx.wat
```
I found there are several places  where f64/f32 are used 

![image](https://github.com/rustwasm/wasm-bindgen/assets/78890754/8bdaa155-8682-4a5a-873b-3a06faeba674)

which is related to wasm-bindgen.
```
rustfilt $_ZN12wasm_bindgen7convert5impls70_$LT$impl$u20$wasm_bindgen..convert..traits..WasmAbi$u20$for$u20$T$GT$4join17h7ecf4c5ba75d1be6E
..convert..traits..WasmAbijoin17h7ecf4c5ba75d1be6E
```
Anyone know how to disable floating-point in wasm-bindgen?

**Comment by daxpedda** [comment]
How would that work anyway? The only way to remove floating points is to not use them. Maybe what you are asking for is a compile error when `wasm-bindgen` detects a floating point?

In any case, this isn't supported and not planned.

**Comment by readygo67** [comment]
@daxpedda, according your info,  If I do not use floating point, or not import crate which use floating point. wasm-bindgen will not generate floating point, is my understanding right?

**Comment by daxpedda** [comment]
Indeed that should be the case for Rustc, this has little to do with `wasm-bindgen`.
I can't really say for sure because there are some things inserted by Rustc (and `wasm-bindgen`) but I don't think any of those are using floating points.
