### ISSUE TITLE
how to get the function name from $_ZN12wasm_bindgen7convert8closures11invoke3_mut17h86e638c821fad360E?

### ISSUE THREAD

**Issue by readygo67** [rustwasm/wasm-bindgen#3727]
I have tried 
```
rustfilt $_ZN12wasm_bindgen7convert8closures11invoke3_mut17h86e638c821fad360E
```
but there is no respose,  how can I get the name of this function?

**Comment by Liamolucko** [comment]
You need to get rid of the '$' from the start, it isn't a part of the symbol name. It's just what's used to indicate a name for something in `wat` files.

**Comment by readygo67** [comment]
@Liamolucko  very thanks for your clear instruction
