### ISSUE TITLE
Skip `wasm_bindgen` attributes in dependencies

### ISSUE THREAD

**Issue by SebastienGllmt** [rustwasm/wasm-bindgen#3759]
### Motivation

If you're authoring a WASM package that contains WASM dependencies, the public API of your generated WASM/JS code will not only contain all WASM bindings you created yourself, but also all of those created by the dependency. This leads to bloat since maybe you only needed a small part of the dependency, but none of the unused bindings in the dependencies get eliminated

### Proposed Solution

It would be useful if the codegen tool had an option to skip `wasm_bindgen` attributes of dependencies. That way, when consuming a WASM crate, you can just skip any dependency you don't want to appear in the public API of your project.

`wasm_bindgen` is powered by a proc macro defined [here](https://github.com/rustwasm/wasm-bindgen/blob/c0ee195d7ebbb18b8517d115c4f3bfee4b797a3d/crates/macro-support/src/lib.rs#L25). Here are some key points about proc macros:
1. Proc macros cannot learn about the file they're included in (there is a nightly feature that allows this [here](https://doc.rust-lang.org/proc_macro/struct.Span.html#method.source_file), but it only gives relative files and not the full path)
2. Proc macros can read env varaibles using either `std::env::var` (runtime binding) `env!` (compile-time binding)

Therefore, we use the `env!` macro to get the crate name (and not `std::env::var`). This is key because if you have 3 crates: `my-crate` → `utility-crate` →  `wasm_bindgen`, you want to know a struct came from `utility-crate` even when you are working on `my-crate`.

With this, we should be able to just skip the proc macro if we detect it's part of a crate we want to skip. A user's Cargo file can then choose to skip specific dependency crates or ignore all dependencies entirely.

### Alternative 1: change the descriptor parsing instead

The solution may cause issues for any project that is shipping built code instead of source code for their project because we can't go back in and rerun the proc macro. To avoid this, another option would be to keep the `wasm_bindgen`  as-is, but modify the interpretation of the code they generate.

As a reminder of how wasm-bindgen works: for every `wasm_bindgen` macro found, it creates an AST element that then gets used to generate a "Descriptor" (you can find all instances of this by searching `impl ToTokens for ast::`). These descriptors get added to the initial WASM output, then deleted later. You can find more about descriptors [here](https://github.com/rustwasm/wasm-bindgen/blob/main/guide/src/contributing/design/describe.md).

We can change the descriptors to also contain information about which crate they were generated for, and then skip any effects they may have (do nothing but remove them) when we parse them later in the interpreter [here](https://github.com/rustwasm/wasm-bindgen/blob/c0ee195d7ebbb18b8517d115c4f3bfee4b797a3d/crates/cli-support/src/descriptors.rs#L37-L38).

### Alternative 2: leave it to developers to use the right feature flags

Crates that support WASM can be encouraged to use a feature flag that disables any `#[wasm_bindgen]` they use. This allows projects that consume their crate to disable all their attributes, and then re-export any type manually as needed.

This is not ideal because it makes composition of crates difficult. Image crate A has a wasm struct `Foo`. Then, crate B has a wasm struct `Bar { foo: Foo }`. This means that if we disable wasm_bindgen for crate A, it breaks the compilation of crate B unless we also disable wasm_bindgen for B as well (but B might not have such a feature flag).

In this way, this option requires opt-in from all developers to put a feature flags which isn't ideal.

**Comment by daxpedda** [comment]
> ### Proposed Solution
>
> ...
>
> Therefore, we use the `env!` macro to get the crate name (and not `std::env::var`). This is key because if you have 3 crates: `my-crate` → `utility-crate` → `wasm_bindgen`, you want to know a struct came from `utility-crate` even when you are working on `my-crate`.
>
> With this, we should be able to just skip the proc macro if we detect it's part of a crate we want to skip. A user's Cargo file can then choose to skip specific dependency crates or ignore all dependencies entirely.

So I see how you want to determine the source crate of every `#[wasm_bindgen]` invocation, but I'm not sure I understand what you are actually proposing here.

How can a "Cargo file" choose which dependencies to skip? Do you want to encode this in the package metadata?

> ### Alternative 1: change the descriptor parsing instead

We can store the information in the descriptors and then throw it out at when running the post-processor. But we need a mechanism to decide what exactly to throw out.

> ### Alternative 2: leave it to developers to use the right feature flags

I think generally speaking there is a desire to get the output of the JS shim more under control so I don't particularly think this feature request is completely out of scope and I can sympathize with it.

However, I think the difficulty here is what kind of mechanism we want here: package metadata, flags on `wasm-bindgen-cli`, attributes on the proc-macro? Whatever we come up with here should try to be as general as possible.

Considering the scope here I would really appreciate another maintainer chiming in as well, I don't know what kind of similar issues and discussions have been done on this in the past and I might be missing something obvious here.

Thank you for exploring this!

**Comment by Liamolucko** [comment]
> Considering the scope here I would really appreciate another maintainer chiming in as well, I don't know what kind of similar issues and discussions have had in the past and I might be missing something obvious here.

I couldn't remember any off the top of my head, but I did a quick search and found #1231 and #3229. They don't add much that hasn't been said here though.

> This leads to bloat since maybe you only needed a small part of the dependency, but none of the unused bindings in the dependencies get eliminated

I'm not really sure how the proposed solution solves this part, since it only allows getting rid of all a dependency's exports. Unless you mean you only want to use a pure-Rust subset of the crate?

**Comment by daxpedda** [comment]
I'm going to close this in favor of #3759.
