### ISSUE TITLE
Make sure that any rust code in the documentation compiles

### ISSUE THREAD

**Issue by jonathan-s** [rustwasm/wasm-bindgen#376]
We have lots of documentation for wasm-bindgen in [markdown](). There are a fair amount of code snippets in rust. As wasm-bindgen changes, we want to make sure that these code snippets stay up to date. 

The best way to do that seems to be with something like the following crate https://github.com/budziq/rust-skeptic

**Comment by huangjj27** [comment]
Due to [this issue](https://github.com/alexcrichton/proc-macro2/issues/104), compiling the start example failed.

**Comment by alexcrichton** [comment]
@huangjj27 ah ok thanks! What you'll need to do to update that is:

* Run `rustup update nightly`
* Run `cargo update`
* Change `#![feature(proc_macro, wasm_custom_section, wasm_import_module)]` to `#![feature(use_extern_macros)]`

and you should be good to go!

**Comment by alexcrichton** [comment]
Ah, and also likely run `cargo install -f wasm-bindgen-cli`

**Comment by Tarnadas** [comment]
Thx @alexcrichton,
I had the exact same problem as @huangjj27 and your comment resolved my issue.

**Comment by huangjj27** [comment]
@alexcrichton I'm sorry that I forgot to give you the feedback that your advice solved my issue that day, And thank you very much!

**Comment by mk-tool** [comment]
@alexcrichton ,
When I run `cargo install -f wasm-bindgen-cli`, some errors has occurred.
I already run `rustup update nightly` and `cargo update`.How should I do resolve this errors?
```
   .....
   Compiling filetime v0.2.1
   Compiling log v0.4.5
   Compiling unicode-bidi v0.3.4
   Compiling num_cpus v1.8.0
error[E0658]: non-reference pattern used to match a reference (see issue #42640)
   --> C:\Users\XXXXX\.cargo\registry\src\github.com-1ecc6299db9ec823\parity-wasm-0.32.0\src\builder\module.rs:233:86
    |
233 |                 if let Some(existing_entry) = self.module.types.types().iter().enumerate().find(|(_idx, t)| {
    |                                                                                                  ^^^^^^^^^ help: consider using a reference: `&(_idx, t)`

error[E0658]: non-reference pattern used to match a reference (see issue #42640)
   --> C:\Users\XXXXX\.cargo\registry\src\github.com-1ecc6299db9ec823\parity-wasm-0.32.0\src\builder\module.rs:234:10
    |
234 |                     let elements::Type::Function(ref existing) = t;
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider using a reference: `&elements::Type::Function(ref existing)`

error: aborting due to 2 previous errors

error: Could not compile `parity-wasm`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `wasm-bindgen-cli v0.2.22`, intermediate artifacts can be found at `C:\Users\XXXXX\AppData\Local\Temp\cargo-install.XzPFE7jGIHmS`

Caused by:
  build failed
```

**Comment by alexcrichton** [comment]
I'm gonna close this because I think that we're doing a pretty good job on this front wrt all of the examples, and otherwise I think it's largely infeasible to do for all the other small snippets here and there. That being said PRs are of course always welcome to fix any bugs we have!
