### ISSUE TITLE
wasm-bindgen-test: #[should_panic] on one test prevents using console_error_panic_hook on another

### ISSUE THREAD

**Issue by Ekleog** [rustwasm/wasm-bindgen#3779]
Hey! First of all, as always, thank you so much for all the work y'all do on wasm for rust :heart: 

I just come to report one tiny bug I hit, with the following code:
```rust
use wasm_bindgen_test::{wasm_bindgen_test, wasm_bindgen_test_configure};

wasm_bindgen_test_configure!(run_in_browser);

#[wasm_bindgen_test]
async fn bar() {
    std::panic::set_hook(Box::new(console_error_panic_hook::hook));
}

#[wasm_bindgen_test]
#[should_panic(expected = "bar")]
async fn foo() {
    panic!("bar");
}
```

This code results in a panic:
```
panicked at library/std/src/panicking.rs:135:9:
cannot modify the panic hook from a panicking thread
```

It's pretty convenient to have a panic hook setup to debug failing wasm tests, so I'm submitting this as an issue here.

The workaround is pretty simple: just extract the `should_panic` tests to another integration test, and it's good to go.

Anyway, lots of thanks for everything that already exists!

**Comment by daxpedda** [comment]
Unfortunately this will remain broken until Rust implements the exception handling proposal.
This is in line with Cargo test as well, using `panic = "abort"` together with `should_panic` doesn't really work on native either.

**Comment by Ekleog** [comment]
Hmm I'm not sure I understand? The `wasm_bindgen_test`s don't run with `panic = "abort"`, do they? Otherwise I'd expect even just setting the panic hook to fail, but it did work fine before I added my first `should_panic` test.

And considering that tests are run sequentially, even if the implementation of `should_panic` needs a custom panic hook (which would be my guess), it still should be able to just set the panic hook when starting a new `should_panic` test, which shouldn't lead to this panic.

What am I missing?

**Comment by daxpedda** [comment]
> Hmm I'm not sure I understand? The `wasm_bindgen_test`s don't run with `panic = "abort"`, do they?

The Wasm target in general on Rust has no support for unwinding, so everything compiled to Wasm will use `panic = "abort"`.
> Otherwise I'd expect even just setting the panic hook to fail, but it did work fine before I added my first `should_panic` test.

Panic hooks are still run even with `panic = "abort"`, but after the panic hook it will run `std::process::abort()` instead of unwinding.

> And considering that tests are run sequentially, even if the implementation of `should_panic` needs a custom panic hook (which would be my guess), it still should be able to just set the panic hook when starting a new `should_panic` test, which shouldn't lead to this panic.

The problem is that Rust doesn't actually allow the application to continue to run after `std::process::abort()`, so continuing an application after a panic in Wasm is unsound. See https://github.com/rust-lang/rust/issues/117344.

But yes, a temporary fix might be to just reapply the panic hook after every `should_panic` test.

**Comment by Ekleog** [comment]
Oh, so if I understand correctly even having two `#[should_panic]` tests in a single module is currently unsupported? That's a bit sad, but good to know, thank you! :)

**Comment by daxpedda** [comment]
To be precise, `#[should_panic]` in general is not supported! Currently it works just by chance. E.g. if https://github.com/rust-lang/rust/issues/117344 gets fixed properly, it won't work at all.

**Comment by Ekleog** [comment]
Hmm maybe an idea, though it would not work well with non-headless tests.

What if we required the use of nextest to run the test suite? This would require implementing quite a bit more of the API for wasm-bindgen-test-runner, but it could allow the use of `#[should_panic]` in tests… I think? Because then it would never re-enter the module.

**Comment by daxpedda** [comment]
> What if we required the use of nextest to run the test suite? This would require implementing quite a bit more of the API for wasm-bindgen-test-runner, but it could allow the use of `#[should_panic]` in tests… I think? Because then it would never re-enter the module.

I don't think requiring `nextest` is desirable, but supporting it would be nice!
