### ISSUE TITLE
SubtleCrypto verify methods accepts mutable reference that should be immutable?

### ISSUE THREAD

**Issue by eric-seppanen** [rustwasm/wasm-bindgen#3795]
### Describe the Bug

Some of the verify methods on `SubtleCrypto` take mutable references to the `signature` bytes. It doesn't seem desirable that a method for verifying signatures would mutate the signature bytes, so I wonder if this is a mistake?

### Steps to Reproduce

1. Go to https://docs.rs/web-sys/0.3.67/web_sys/struct.SubtleCrypto.html
2. Note that some of the `verify____` methods accept `signature: &mut [u8]`

### Expected Behavior

I would expect that a signature verification would never need to mutate the signature.

### Actual Behavior

Parameter is explicitly set to be mutable; git history doesn't indicate a reason why.
https://github.com/rustwasm/wasm-bindgen/blob/55a7fb848a88c0e1200baf1bf670a051b14f5025/crates/web-sys/src/features/gen_SubtleCrypto.rs#L540

### Additional Context

The [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/verify) don't suggest that the signature might be mutated. They don't promise it won't, so I'm just going on instinct here.

**Comment by eric-seppanen** [comment]
I notice a few other uses of `&mut` in `SubtleCrypto` methods that seem suspicious, e.g. `verify_with_xxx_and_yyy_and_u8_array` methods accept `data: &mut [u8]`. This refers to the data over which a signature should be verified; mutating the data would be quite unexpected.

**Comment by daxpedda** [comment]
See [The `wasm-bindgen` Guide on "Type Translations in web-sys"](https://rustwasm.github.io/wasm-bindgen/web-sys/type-translations.html).

We can add exceptions here:
https://github.com/rustwasm/wasm-bindgen/blob/55a7fb848a88c0e1200baf1bf670a051b14f5025/crates/webidl/src/constants.rs#L43-L99

I'm happy to review a PR adding exceptions to any `SubtleCrypto` methods.

**Comment by eric-seppanen** [comment]
Thanks @daxpedda. I investigated all the `SubtleCrypto` methods and I believe they can all take shared references.

I opened PR #3797 making the change.
