### ISSUE TITLE
Allow generate unmount-able / freeable wasm module in cli config

### ISSUE THREAD

**Issue by linonetwo** [rustwasm/wasm-bindgen#3818]
### Motivation

In [On WASM, How to free / destroy / close an instance? #11619](https://github.com/bevyengine/bevy/discussions/11619) I talk about the difficulty to destroy and recreate bevy game instance.

I found this is possible, by manually comment out the 

```js
if (wasm !== undefined) return wasm;
```

in bindgen generated js file.

### Proposed Solution

Maybe we can add a cli option to not adding this line, so everything I use `initSync` or `__wbg_init` to create a game instance from wasm `Uint8Array`, I can surely create a new game instance, and old one gets GC.

### Alternatives `destroy()`

Or maybe generate a method to destroy the old instance, so I can create a new one safely.

I'm using this

```js
export function destroy() {
    wasm = undefined;
    __wbg_init.__wbindgen_wasm_module = undefined;
    cachedFloat32Memory0 = null;
    cachedFloat64Memory0 = null;
    cachedInt32Memory0 = null;
    cachedUint32Memory0 = null;
    cachedUint8Memory0 = null;
}
```

with

```ts
export function destroy(): void;
```

But have to add it manually with a script after bindgen.

And this needs to be called before next `initSync`. Can't call it immediately after JS side UI canvas component unmount, otherwise there will be error `wasm is undefined` from some `wasm.xxx` calling, maybe some teardown logic sill running inside wasm. Set a timeout 1s after component unmount is not working, still get same error. Only called before next `initSync` works.

### Alternatives `getWasmContext()`

This is what I'm using later, also use custom script to modify generated js file (See [On WASM, How to free / destroy / close an instance? #11619](https://github.com/bevyengine/bevy/discussions/11619) for my script)

I use script to create

```js
export function getWasmContext() {
    const __exports = {};
//...

return { initAsync: __wbg_init, initSync, ...__exports };

}
```

```ts
declare namespace WasmBindgen {
	/* tslint:disable */
	/* eslint-disable */
	/**
	*/
	export function startGame(): void;
	/**
	*/
	export function stopGame(): void;
	/**
	* @param {string} events_json_string
	*/
	export function setGamificationEvents(events_json_string: string): void;
	
}

//...
/**
* If `module_or_path` is {RequestInfo} or {URL}, makes a request and
* for everything else, calls `WebAssembly.instantiate` directly.
*
* @param {InitInput | Promise<InitInput>} module_or_path
*
* @returns {Promise<InitOutput>}
*/
function initAsync (module_or_path: InitInput | Promise<InitInput>): Promise<InitOutput>;

/**
 * remove previous game, to prevent `Creating EventLoop multiple times is not supported.` error.
 * @url https://github.com/bevyengine/bevy/discussions/11619
 */
export function destroy(): void;
export type WasmContext = typeof WasmBindgen & { initAsync: typeof initAsync }
export function getWasmContext(): WasmContext;
```

And this works very fine, if not using `destroy()`. While there mighe be memory leak when creating new game.

### Additional Context

When embedding a game in existing apps like https://tiddlywiki.com/, we have to handle the case that component (or card note) that owns the canvas element gets unmounted. Currently I can stop the game system, but don't know a way to destroy the wasm.

Later, when such component remounts, we need to recreate the game on the new canvas. If old game already exists, they will throw error `Creating EventLoop multiple times is not supported.`

**Comment by daxpedda** [comment]
Unfortunately this isn't really a path we should go down too, especially because there is currently no way to actually destroy a Wasm instance. E.g. setting variables to `unknown` doesn't necessary cause GC, event listeners might still be holding references to the Wasm instance, which then would cause probably some form of UB when trying to call into the newly made instance.

I'm not entirely sure about the correct JS terms here, but you just have to create a new valid context.
E.g. I believe creating a new `<script>` tag should solve the problem.

Does that address your issue?

**Comment by linonetwo** [comment]
Thank you for your response, I noticed there were mysterious calls to methods. And now seems my new workaround is creating a new context via JS closure (see generated `getWasmContext()` function, while it is not able to destroy old context). Would you accept the new workaround as a cli config?

> creating a new `<script>` tag

I'm more certain that create a new iframe tag will create a context, and it is possible to delete that iframe to totally free the memory, but `script` tag will reuse the global context, and deleting script tag won't delete any memory AFAIK.

**Comment by daxpedda** [comment]
> Thank you for your response, I noticed there were mysterious calls to methods from deleted wasm. And now seems my new workaround is creating a brand new context via JS closure, that avoids this situation (see generated `getWasmContext()` function, while it is not able to destroy old context, but new context has no error).

I'm not following.
Did you make a *new* `getWasmContext()` that addresses the problem I mentioned above? If so, where can I see that?

You mentioned "brand new context via JS closure", which is an interesting idea, but I think would be complicated to implement. If you have some code I could look at it would be appreciated.

So I would prefer to make sure we just get a clean context.

> > creating a new `<script>` tag
> 
> I'm more certain that create a new iframe tag will create a context, and it is possible to delete that iframe to totally free the memory, but `script` tag will reuse the global context, and deleting script tag won't delete any memory AFAIK.

We don't use the global context in our JS module output.
The goal is not to destroy the old Wasm instance, as that's not really possible (unless you use something like an `IFrame` as you suggested), but to make sure we create a clean JS context.

**Comment by linonetwo** [comment]
> you make a new getWasmContext() that addresses the problem I mentioned above? If so, where can I see that?

Yes! 

## I generate it based on this script `scripts/buildGame.mjs` (see I'm using `--target no-modules`)

```js
#!/usr/bin/env zx

import { appendFile, readFile, writeFile } from 'fs/promises';
import { $, cd, path } from 'zx';

const gamePath = path.resolve(__dirname, '../src/scp-foundation-site-director/game');
/**
 * Build the game
 */
cd(gamePath);
await $`cargo build --release --target wasm32-unknown-unknown`;
await $`wasm-bindgen --omit-default-module-path --reference-types --weak-refs --out-name game --out-dir wasm --target no-modules target/wasm32-unknown-unknown/release/game.wasm --debug`;

/**
 * Fix Wasm Bindgen No Destroy Method
 */
// JS snippet to append
const jsSnippet = `
function destroy() {
    wasm = undefined;
    __wbg_init.__wbindgen_wasm_module = undefined;
    cachedFloat32Memory0 = null;
    cachedFloat64Memory0 = null;
    cachedInt32Memory0 = null;
    cachedUint32Memory0 = null;
    cachedUint8Memory0 = null;
}
`;

// TS definition to append
const tsDefinition = `
/**
 * remove previous game, to prevent \`Creating EventLoop multiple times is not supported.\` error.
 * @url https://github.com/bevyengine/bevy/discussions/11619
 */
export function destroy(): void;
export type WasmContext = typeof WasmBindgen & { initAsync: typeof initAsync }
/**
 * Create a new wasm context.
 * 
 * ## If reuse previous one:
 * 
 * There will be \`already borrowed: BorrowMutError\` \`RuntimeError: unreachable executed\` error, when switch from one game to another.
 *
 * And sometimes there still be \`Uncaught TypeError: wasm is undefined\` \`Uncaught RuntimeError: unreachable\` \`Uncaught TypeError: Cannot read properties of undefined (reading 'wasm_bindgen__convert__closures__invoke0_mut__h9f5f8d8886b9ec6c')\` \`Uncaught TypeError: Cannot read properties of undefined (reading '__wbindgen_export_3')\` error, when switch from one game to another, maybe switch is too fast? Change from \`0\` to \`1000\` some times still cannot fixes this, even the game should have been stopped. And it slowdown the game init. And this error throw on global can't be catch here.
 */
export function getWasmContext(): WasmContext;
`;

// Path to the wasm bindgen generated JS file
const jsFilePath = path.resolve(gamePath, 'wasm/game.js');
const tsFilePath = path.resolve(gamePath, 'wasm/game.d.ts');

try {
  // Append JS snippet
  // await appendFile(jsFilePath, jsSnippet);
  const jsFile = await readFile(jsFilePath, 'utf8');
  await writeFile(
    jsFilePath,
    jsFile
      .replace('wasm_bindgen = Object.assign(__wbg_init, { initSync }, __exports);', 'return { initAsync: __wbg_init, initSync, ...__exports };')
      .replace('})();', '}')
      .replace(
        `let wasm_bindgen;
(function() {`,
        'export function getWasmContext() {',
      ),
  );
  console.log('JS snippet appended successfully.');

  // Append TS definition
  const tsFile = await readFile(tsFilePath, 'utf8');
  await writeFile(
    tsFilePath,
    tsFile
      .replace('declare namespace wasm_bindgen', 'declare namespace WasmBindgen')
      .replace('declare function wasm_bindgen', 'function initAsync'),
  );
  await appendFile(tsFilePath, tsDefinition);
  console.log('TS definition appended successfully.');
} catch (error) {
  console.error('Failed to append to file:', error);
}
```

(copy from https://github.com/bevyengine/bevy/discussions/11619#discussioncomment-8322223 )

## And generated content is


```js
export function getWasmContext() {
    const __exports = {};
//...

return { initAsync: __wbg_init, initSync, ...__exports };

}
```

```ts
declare namespace WasmBindgen {
	/* tslint:disable */
	/* eslint-disable */
	/**
	*/
	export function startGame(): void;
	/**
	*/
	export function stopGame(): void;
	/**
	* @param {string} events_json_string
	*/
	export function setGamificationEvents(events_json_string: string): void;
	
}

//...
/**
* If `module_or_path` is {RequestInfo} or {URL}, makes a request and
* for everything else, calls `WebAssembly.instantiate` directly.
*
* @param {InitInput | Promise<InitInput>} module_or_path
*
* @returns {Promise<InitOutput>}
*/
function initAsync (module_or_path: InitInput | Promise<InitInput>): Promise<InitOutput>;

/**
 * remove previous game, to prevent `Creating EventLoop multiple times is not supported.` error.
 * @url https://github.com/bevyengine/bevy/discussions/11619
 */
export function destroy(): void;
export type WasmContext = typeof WasmBindgen & { initAsync: typeof initAsync }
export function getWasmContext(): WasmContext;
```

(Copy from https://github.com/rustwasm/wasm-bindgen/issues/3818#issue-2109907772 )

**Comment by daxpedda** [comment]
I am very confused, you are modifying the `no-modules` output but using `export`. Why are you using the `no-modules` target to being with?

In any case, an upstreamable solution for the `no-modules` target has to keep it actually free of any JS module code.

**Comment by linonetwo** [comment]
> I am very confused

Feel free to chat, I'm on vacation, so can spend 8 hours to opensource per day.

The reason for using `no-modules` instead of `browser` is that it generate an IIFE. It already wrap everything in a function closure, so it is easier to modify it. The script I'm using is just remove the `II` part of `IIFE`, and add an `export` and a function name `getWasmContext` to it.

(although I can also use `browser` target, and use script to remove all `export` and wrap things with a function, just a bit difficult to write the script. I tried.)

**Comment by daxpedda** [comment]
> Feel free to chat, I'm on vacation, so can spend 8 hours to opensource per day.

We have a [Discord channel](https://discord.com/channels/442252698964721669/1110955325814747206) on the official [Rust server](https://discord.gg/rust-lang) you can find us at, where we can have a more real-time discussion.

To summarize so far:
- Any solution has to preserve targets constraints. Ergo we can't modify the `no-modules` target to include any JS module statements like `export`.
- Creating a new context through `<script>` can hopefully cover the use-case. If it does then I would be against implementing a feature into `wasm-bindgen` unless the use-case or inconvenience by the lack thereof can be made more clear.

**Comment by linonetwo** [comment]
> can't modify the no-modules target to include any JS module statements like export.

I want to add a new target `closure` that returns a js with `export function getWasmContext()` 

> Creating a new context through `<script>`

Can you provide more details? AFAIK, `<script>` tags share a global context, so it is not working.

Even if every new `<script>` tag has a new context, how to interact with each one?

**Comment by daxpedda** [comment]
> > Creating a new context through `<script>`
> 
> Can you provide more details? AFAIK, `<script>` tags share a global context, so it is not working.

The `web` target shouldn't store anything in the global context, so that should not be an issue.

> Even if every new `<script>` tag has a new context, how to interact with each one?

I'm unsure exactly how you are deploying your page, but in the `<script type=module>` context you are initializing your Wasm module in, you are able to interact with it directly.

Interacting with a specific Wasm instantiation from outside the `<script type=module>` context is exactly as limited as it is for any JS in a `<script type=module>`. You probably will have to store functions in the global context or use some other trickery. I'm definitely no JS expert.

In any case, considering you are using Bevy, you shouldn't really need to do that, because you are interacting with your page from inside the module.

After writing all this, I guess you are using the no-modules target to circumvent exactly this problem? It would probably help at this point to figure out exactly why the `web` target doesn't work for you.

**Comment by linonetwo** [comment]
I'm building a https://tiddlywiki.com/ plugin, so I'm expecting to initialize a new canvas for bevy wasm, then create a bevy wasm instance, let it operate on that canvas.

But when using `web` target, JS code generated by wasm-bindgen will create a `wasm` variable in its module. And I'm bundling my Typescript code with this JS code, so my Typescript code always import the same module of JS code, so always get the same `wasm` variable.

I'm writing TS as a plugin, so I'm not directly writing HTML. So if I'm going to create a `<script type=module>` tag, I will have to do something like

```js
const wasmLoaderScript = document.createElement('script');
wasmLoaderScript.type = 'module';
wasmLoaderScript.textContent = // I'm importing & bundling JS, so It is not easy to get stringified version of wasm-bindgen generated js code here
// even I make it, how to pass wasm module to it? Maybe by concat it as base64 string...
```

**Comment by linonetwo** [comment]
If I want to add a new target that is similar to `no-modules`, am I going to change https://github.com/rustwasm/wasm-bindgen/blob/main/crates/cli-support/src/js/binding.rs ? It looks very complicated.

I just want to create a version similar to `web` target, but without local variable in the JS file level, that is created only once when JS module loaded. 

Only function level variables that created everytime when I call the function.

**Comment by daxpedda** [comment]
> So if I'm going to create a `<script type=module>` tag, I will have to do something like
> 
> ```js
> const wasmLoaderScript = document.createElement('script');
> wasmLoaderScript.type = 'module';
> wasmLoaderScript.textContent = // I'm importing & bundling JS, so It is not easy to get stringified version of wasm-bindgen generated js code here
> // even I make it, how to pass wasm module to it? Maybe by concat it as base64 string...
> ```

Can't you just use [`src`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#src) and point to the file?

> This is the problem, when I use bundler like webpack/esbuild, instead of load wasm-bindgen js using script tag.

It sounds to me like you should just not bundle your TS code, which handles your page state, with the `wasm-bindgen` shim, which should be a separate state you want to be able to unload.

> So by "store things in global context", I mean bundled JS module will have a closure (local variable in that JS file), and on my TS code, I import that JS module, I will always get the same closure, seems like that JS module stores a `wasm` variable in the global context.

The problem is that `import` won't create a new JS context if it's the same path, the problem is **not** that `wasm` is stored in the global context.

You can also solve that by dynamic import with something like this: `pathToYourScript.js?version=0`. That way you will always get a new context without having to make a new `script` tag.

> I just want to create a version similar to `web` target, but without local variable in the JS file level, that is created only once when JS module loaded.

Adding a new target to `wasm-bindgen` should require some very serious justification. This problem so far sounds to me like something that should be possible with the current `web` target. I have outlined multiple solutions to do this, so we should rule them out before even discussing adding a new target.

Generally speaking I would also like to make it easy to do this with the current `web` target, because all solutions known to me so far are pretty much hacks, even if they work.

> Only function level variables that created everytime when I call the function.

Something like this, but unfortunately we can't do that every time we call the default (`init`) function, but maybe with an additional parameter or something like this.

I don't know exactly what a solution would look like here, but somebody would have to dive in and figure out how and if the `web` target can be modified without breaking changes to make it easier to support this use-case.

---

So right now the following solutions for you are still on the table, both requiring that you don't bundle your TS code with the `wasm-bindgen` JS shim code.
- Creating a new `<script>` tag.
- Using dynamic import with `?version=x` to trick JS into not sharing the context. Comes with the downside of actually making a new HTTP request.

**Comment by linonetwo** [comment]
> Can't you just use [src](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#src) and point to the file?

Sorry but no, in most TS development, we need everything to be bundled as a single JS file, and in the browser there is no real filesystem, also no network if the app is local-first. So everything is handled inside JS memory.

Maybe it is possible to not bundle files for a web app using snowpack, but Tiddlywiki need to bundle all things into its in-memory filesystem, to work offline.

> ?version=0

I tried this before, but both esbuild's bundling system and Tiddlywiki's in-memory filesystem don't handle this well, it will be an unfound module and become a HTTP request, but we don't have a server to serve files, everything is bundled and loaded to in-memory filesystem.

**Comment by linonetwo** [comment]
I do more test today, seems comment out `if (wasm !== undefined) return wasm;` will do the trick. I was going too far during debug, and come up with a solution with more boilerplates...

Maybe just add a new option here:

https://github.com/rustwasm/wasm-bindgen/blob/3e469b265464e60645f7eceb5745fa2558aea703/crates/cli-support/src/js/mod.rs#L705

**Comment by daxpedda** [comment]
> Maybe it is possible to not bundle files for a web app using snowpack, but Tiddlywiki need to bundle all things into its in-memory filesystem, to work offline.

You could try creating an object URL.
```js
const blob = new Blob([yourScript], { type: 'text/javascript' })
const objectURL = URL.createObjectURL(blob)
```
I'm unfortunately completely unfamiliar with the JS/TS ecosystem and have no clue if bundlers and tools support something like that.

> > ?version=0
> 
> I tried this before, but both esbuild's bundling system and Tiddlywiki's in-memory filesystem don't handle this well, it will be an unfound module and become a HTTP request, but we don't have a server to serve files, everything is bundled and loaded to in-memory filesystem.

Seems you are stuck with adding `script` tags.

---

This seems certainly to be a very unique combination of restrictions ... so I don't really believe this justifies its own target. Though I still think using `script` tags you should be able to fit in those restrictions.

**Comment by linonetwo** [comment]
Thanks, I'm doing experiment, and first this is GPT4 says:

> Using the Exported Function:
> To use the exported function (init in your case) from another script, you should also treat that script as a module and use the import statement. However, direct import from a blob URL like this is not straightforward because the blob URL doesn't have a predictable or meaningful origin that can be used to import from other scripts.
>
> A workaround is to export your functions or variables to the global scope (e.g., window) inside the blob script itself, and then access it from other scripts. This approach, however, negates some benefits of modules like encapsulation and explicit dependencies.
>
> Concerning Multiple Instances and JavaScript Context:
When you execute the script multiple times by creating multiple blobs and object URLs, each execution of the script runs in the same JavaScript context of the webpage. Variables declared outside of functions (like your wasm variable) will not be reinitialized between executions of the script tag created this way; wasm would retain its value if the script is executed again and would not be undefined in the second script tag, assuming the init function has been called once already.

So even I new a `script` tag, it is impossible to get the exported function, unless assign them to a global context like `window.initSync`

Anyway, I can use my hack (`no-module` target + postprocess script that modify it) for a while, until I get more fremillar with wasm-bindgen, I'm reading the contributing doc today. But for now, I will focus on writing the game for a while.

Many thanks to @daxpedda , and hope this discussion can help others.

**Comment by linonetwo** [comment]
Thank you @daxpedda , using blobUrl with `async import` works:

```ts
  private async initializeGameCanvas() {
    // wasm is bundled into tiddlywiki using `game/tiddlywiki.files` as base64
    const gameWasm = $tw.wiki.getTiddlerText('$:/plugins/linonetwo/scp-foundation-site-director/game_bg.wasm');
    // we parse and run the code on runtime, to create a new JS context each time, to prevent reuse last game's wasm.
    const wasmBindGenJSCode = $tw.wiki.getTiddlerText('$:/plugins/linonetwo/scp-foundation-site-director/game.js');

    if (gameWasm !== undefined && wasmBindGenJSCode !== undefined) {
      const wasmBuffer = loadWasmModuleFromBase64(gameWasm);
      console.time('gameLoad'); // 384 ~ 1551 ms
      try {
        const blob = new Blob([wasmBindGenJSCode], { type: 'text/javascript' });
        const objectURL = URL.createObjectURL(blob);
        this.wasmContext = await import(objectURL) as typeof IGameContext;
        /**
         * Use `initAsync` for large wasm.
         *
         * Can't use `initSync`, it cause error:
         * > RangeError: WebAssembly.Compile is disallowed on the main thread, if the buffer size is larger than 8MB. Use WebAssembly.compile, compile on a worker thread
         */
        await this.wasmContext.default(wasmBuffer);
        this.wasmContext.startGame();
// ...

  destroy(): void {
    this.wasmContext?.stopGame?.();
    this.wasmContext = undefined;
    this.gameInitialized = false;
  }
```

And this use official `web` target without modification!

**Comment by linonetwo** [comment]
Problem solved, well, why didn't I come to this at first place? Maybe I forget using `async import(blobUrl)` will create new JS context?

**Comment by daxpedda** [comment]
Glad it worked out!
