### ISSUE TITLE
Missing implementation of reset method on CanvasRenderingContext2D and OffscreenCanvasRenderingContext2d

### ISSUE THREAD

**Issue by Nul-led** [rustwasm/wasm-bindgen#3843]
### Describe the Bug

[CanvasState.reset](https://html.spec.whatwg.org/multipage/canvas.html#canvasstate) is not implemented for web_sys::CanvasRenderingContext2d and web_sys::OffscreenCanvasRenderingContext2d.

### Steps to Reproduce

None

### Expected Behavior

web_sys::CanvasRenderingContext2d::reset and web_sys::OffscreenCanvasRenderingContext2d::reset should exist as per [specification](https://html.spec.whatwg.org/multipage/canvas.html#dom-context-2d-reset).

### Actual Behavior

The method mentioned above is not implemented.

### Additional Context

None

**Comment by daxpedda** [comment]
Happy to review a PR!

See the [`wasm-bindgen` Book](https://rustwasm.github.io/wasm-bindgen/contributing/web-sys/supporting-more-web-apis.html) on how to contribute Web APIs.
