### ISSUE TITLE
remove old reference to "nightly" feature

### ISSUE THREAD

**Issue by DougAnderson444** [rustwasm/wasm-bindgen#3845]
Hi,  found this but it looks like this is outdated and can be removed?

https://github.com/rustwasm/wasm-bindgen/blob/12889ef666f9b355585602e268be2b70d7f3ec80/guide/src/reference/passing-rust-closures-to-js.md?plain=1#L66-L71

**Comment by daxpedda** [comment]
Yes, would you mind making a PR?

**Comment by DougAnderson444** [comment]
Yep, done!
