### ISSUE TITLE
Does `MutSlice` handle empty boxed slices correctly?

### ISSUE THREAD

**Issue by djkoloski** [rustwasm/wasm-bindgen#3846]
### Summary

While auditing `wasm-bindgen` for import into Fuchsia, we tried to make sure that the call to `__wbindgen_copy_to_typed_array` in `src/convert/slices.rs` was safe even when `contents` is a box of an empty slice. That would make the pointer from it dangling, which could cause some bad behavior. We were unable to track down exactly what happens with that pointer. Can anyone offer some insight into how this intrinsic gets implemented? Is it safe to pass garbage pointers as long as the length of the slice is zero?

### Additional Details

[Review in progress](https://fuchsia-review.git.corp.google.com/c/fuchsia/+/990475)

**Comment by Liamolucko** [comment]
That intrinsic is defined here:

https://github.com/rustwasm/wasm-bindgen/blob/12889ef666f9b355585602e268be2b70d7f3ec80/crates/cli-support/src/intrinsic.rs#L264-L266

And the JS for it is generated here:

https://github.com/rustwasm/wasm-bindgen/blob/12889ef666f9b355585602e268be2b70d7f3ec80/crates/cli-support/src/js/mod.rs#L3564-L3571

So yes, it should be fine. `src` is a `Uint8Array` pointing to the raw bytes of the boxed slice in Rust (automatically created from Rust's ptr + len thanks to the `#[signature = fn(slice(U8), ref_externref()) -> Unit]` annotation), and `dst` is the original typed array that was passed to Rust. So if the boxed slice's length is 0, `src` and `dst`s lengths will both be 0, and the `set` won't do anything.

**Comment by djkoloski** [comment]
Thank you! Sounds good to me. 🙂
