### ISSUE TITLE
getter macro inconsistent behavior in Release/Debug builds

### ISSUE THREAD

**Issue by dt665m** [rustwasm/wasm-bindgen#3912]
### Describe the Bug

I have a rust struct that is using `#[wasm_bindgen]` tooling with `#[wasm_bindgen(getter)]` functions.  I'm seeing inconsistent behavior when building my project in Release and Debug mode.  

In Debug Mode, accessing the getter in javascript land resolves to the returned object of the getter method.
In Release Mode, accessing the getter in javascript land resolves to a function/method.  This happens with both the `#[wasm_bindgen(getter)]` proc macro for functions and the `#[wasm_bindgen(getter_with_clone)]` proc macro for the struct.

### Steps to Reproduce
- wasm-bindgen 0.2.92
- I'm using OSX Sonoma on Apple Silicon and Chrome 123.x
- clone this [minimal repro](https://github.com/dt665m/wasmbindgen-debugging)
- install trunk `cargo install --locked trunk`
- serve with `trunk serve`
- open browser at `localhost:8080`. Observe console log of "hello world"
- serve with `trunk serve --release`
- open browser at `localhost:8080`.  Observe console log of "function...."

### Expected Behavior

Debug and Release should be the same

### Actual Behavior

Differing results in Debug and Release

**Comment by Liamolucko** [comment]
This seems to be a bug with Trunk's minifier (https://github.com/wilsonzlin/minify-js): passing `--no-minification` fixes the issue. (Minification seems to be disabled by default in debug builds.)

It seems like it simply deletes the `get` keyword; this JS:

```js
class A {
    get b() {
        return 5;
    }
}
```

gets minified into 

```js
class a{b(){return 5}}
```

This is with v0.5, the version Trunk's using; I haven't checked if it's still an issue in v0.6.

**Comment by dt665m** [comment]
Thanks for tracking this...  I'll move this issue to trunk.  Should we close here?

**Comment by daxpedda** [comment]
> Thanks for tracking this... I'll move this issue to trunk. Should we close here?

Yes, thank you!
