### ISSUE TITLE
Expose synchronous XMLHttpRequest

### ISSUE THREAD

**Issue by zdimension** [rustwasm/wasm-bindgen#3924]
### Motivation

Synchronous XMLHttpRequests are not currently exposed in web-sys. Speficially, the 3-parameter `open` function (with the third one being a boolean which, when false, makes the request synchronous) isn't exposed.

Synchronous XMLHttpRequests are deprecated for the main thread, but they are very useful in Web Workers since they allow sending requests and waiting without having to manage all the weight of an async runtime (e.g. in Rust code).

### Proposed Solution

Expose the 3-parameter `open` function.

### Alternatives

The workaround I'm using in my use case:

```rust
#[cfg(target_arch = "wasm32")]
#[wasm_bindgen(inline_js = "export function req(url) { const xhr = new XMLHttpRequest(); xhr.open('GET', url, false); xhr.responseType = 'arraybuffer'; xhr.send(); return new Uint8Array(xhr.response); }")]
extern "C" {
    fn req(url: &str) -> js_sys::Uint8Array;
}
```

**Comment by daxpedda** [comment]
PRs welcome!

**Comment by zdimension** [comment]
Huh, I have no idea how I missed this. The function is exposed, it's called `open_with_async`. I guess I assumed from the name that it was something async-related, not "the open function with the parameter named async that allows making the request synchronous".
