### ISSUE TITLE
Promise's `then` method doesn't support Closures with return values

### ISSUE THREAD

**Issue by pfernandom** [rustwasm/wasm-bindgen#3948]
### Describe the Bug

`Promise` doesn't allow return values in the closure for its `then` method.

### Steps to Reproduce

```rust
 Promise::new(&mut |resolve, reject| {
      resolve.call1(&JsValue::null(), &JsValue::from_f64(123.0));
  })
  .then(&Closure::new(&mut |val| val));
```

### Expected Behavior

The specification indicates that the value returned from `then` callbacks _"becomes the fulfillment value of the promise returned by then()"_:

_"If it is not a function, it is internally replaced with an identity function ((x) => x) which simply passes the fulfillment value forward."_

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then#onfulfilled

### Actual Behavior

This code fails compilation with:
```
mismatched types
expected `()`, found `JsValue`
```

because the argument for then is `&Closure<dyn FnMut(JsValue)>`, instead of something like `&Closure<dyn FnMut(JsValue) -> JsValue>`

### Additional Context

NA

**Comment by Liamolucko** [comment]
Yeah, this is a known issue. Closing in favour of #3111.
