### ISSUE TITLE
Still alive for issue #2168

### ISSUE THREAD

**Issue by cyk2018** [rustwasm/wasm-bindgen#3960]
### Describe the Bug

null pointer for auto free.

### Steps to Reproduce

1. following the step in [thie issue](https://github.com/rustwasm/wasm-bindgen/issues/2168)

### Expected Behavior

May be two 42 in console?
I follow one article written by this author, and I find that the result in console still throw null pointer exception.

### Additional Context

I found the "the_answer" function has been fixed like this:
```javascript
        const ptr = this.__destroy_into_raw();
        const ret = wasm.answer_the_answer(ptr);
        return ret >>> 0;
```
but the "__destroy_into_raw" function will work like this:
```javascript
        const ptr = this.__wbg_ptr;
        this.__wbg_ptr = 0;
        AnswerFinalization.unregister(this);
        return ptr;
```
and the "__wbg_ptr" will be 0 when second-call.

**Comment by cyk2018** [comment]
@alexcrichton may be you can check this problem? Thanks!

**Comment by daxpedda** [comment]
Closing in favor of #2168.
