### ISSUE TITLE
docs: add examples docs comment how to use it, instead just put MDN docs.

### ISSUE THREAD

**Issue by afifurrohman-id** [rustwasm/wasm-bindgen#3965]
### Motivation

> Every public module, trait, struct, enum, function, method, macro, and type definition should have an example that exercises the functionality.

https://rust-lang.github.io/api-guidelines/documentation.html#all-items-have-a-rustdoc-example-c-example

Instead of answer some common question over, and over again, would be good to add example in docs.
why not?, this why i fun learn rust.

### Proposed Solution

Add examples docs.

### Additional Context
Put MDN docs in docs comment require to connect internet, it would be nice if we can just see examples in docs comment like a bunch of others rust crate and quickly understand how to use it.

**Comment by xpe** [comment]
If you don't have Internet access for some reason, as one workaround one could probably download the MDN documentation offline.

I can see how including a wasm-bindgen example in the docs could be helpful; there are some areas that are non-obvious. This would be a good amount of work.

At the present, one great way to learn about how to use specific parts of wasm-bindgen is from the [examples](https://github.com/rustwasm/wasm-bindgen/tree/main/examples).

**Comment by daxpedda** [comment]
If we are talking about `js-sys` or `web-sys` then the answer is no.

We do include a link to MDN for that reason and unless MDN gains some machine readable and interpretable way to extract a reasonable example this isn't really viable.
