### ISSUE TITLE
Return Proxy object from JavaScript

### ISSUE THREAD

**Issue by JosiahParry** [rustwasm/wasm-bindgen#3980]
### Summary

I am (trying) to write bindings to a TypeScript / Node library called [WebR](https://docs.r-wasm.org/webr/latest/api/js/classes/WebR.WebR.html#evalr)

I can successfully call a few of the methods no problem. However, the [`WebR.evalR()`](https://docs.r-wasm.org/webr/latest/api/js/classes/WebR.WebR.html#evalr) method returns a Promise to a Proxy object. It appears this cannot be cast to a `JsValue` by wasm-bindgen. 

wasm-bindgen bindings: https://github.com/JosiahParry/webr-js-rs/blob/b4da698f4e505d75a635813bf516d2029cec094a/src/bindings/webr.rs#L24-L25

```rs
use wasm_bindgen::prelude::*;
#[wasm_bindgen(module = "https://webr.r-wasm.org/latest/webr.mjs")]
extern "C" {
    #[derive(Debug, Clone)]
    #[wasm_bindgen(js_name = WebR)]
    pub type WebR;

    #[wasm_bindgen(constructor)]
    pub fn new() -> WebR;

    #[wasm_bindgen(method, catch, js_name = "evalR")]
    pub async fn eval_r(this: &WebR, code: String) -> Result<JsValue, JsValue>;
}
```
This results in an error when used (see [test here](https://github.com/JosiahParry/webr-js-rs/blob/b4da698f4e505d75a635813bf516d2029cec094a/tests/wasm.rs#L37-L41))
```    
error output:
panicked at tests/wasm.rs:39:47:
called `Result::unwrap()` on an `Err` value: JsValue(TypeError: Cannot read properties of undefined (reading 'evalR')
TypeError: Cannot read properties of undefined (reading 'evalR')
```

## Additional details

This isn't a bug in the WebR library because the following code runs: 

```html
<html>
<script src="./test.js"></script>
</html>
```
```js
import('https://webr.r-wasm.org/latest/webr.mjs').then(
    async ({ WebR }) => {
        const webR = new WebR();
        await webR.init();
        const res = await webR.evalR("print('Hello, world!')");
        console.log(res);
    }
);
```

which shows it is returning a `Proxy(Object)`

How might i be able to return the Proxy(Object) from this library in a way that works with rust or at minimum doesnt panic?

**Comment by Liamolucko** [comment]
That error is coming from this line in WebR, not wasm-bindgen: https://github.com/r-wasm/webr/blob/c07d8997ddbb58f63002e8d46792be54edcd134c/src/webR/webr-main.ts#L401

I think it's because you need to call `webr.init().await` first, the same as you do in your JS example. Doing that fixes the error for me.
