### ISSUE TITLE
Type safe pointers in generated JS bindings

### ISSUE THREAD

**Issue by ColinTimBarndt** [rustwasm/wasm-bindgen#3982]
### Motivation
Javascript only has one (strictly two when counting BigInt) numeric types, which both represent data and pointers in generated bindings. This allows using regular numbers as arguments for a function accepting a pointer. Additionally, accidentally "casting" a pointer value to another type not supporting the size and alignment constraints is possible.

<details><summary>Example</summary>

Let's assume the following functions are all callable from JS (`#[wasm_bindgen]` omitted).

```rs
pub fn new_foo(x: i32) -> *mut Foo;
pub fn new_bar() -> *mut Bar;
pub fn compute(foo: *const Foo, bar: *const Bar);
```

The resulting  binding types would be this:

```ts
function new_foo(x: number): number;
function new_bar(): number;
function compute(foo: number, bar: number): void;
```

And the following code is accepted by Typescript, even though it's not correct.

```ts
let bar = new_bar();
// 1. transmuting *mut Bar to number
let foo = new_foo(bar);
// 2. transmuting *mut Bar to *const Foo
// 3. transmuting number to *const Bar
compute(bar, 10);
```

</details>

### Proposed Solution

I propose storing metadata on numbers using Typescript branding as follows:

```ts
declare const POINTER: unique symbol;
type Pointer<T> = number & {[POINTER]: {type: T}};
const NULL: Pointer<unknown> = 0 as Pointer<unknown>; // explicit cast is required
```

<details><summary>Updated Example</summary>

From the given example, the new Typescript function signatures would look like this:

```ts
function new_foo(x: number): Pointer<"Foo">;
function new_bar(): Pointer<"Bar">;
function compute(foo: Pointer<"Foo">, bar: Pointer<"Bar">): void;
```

Typescript is now giving errors in 2 out of 3 cases:

```ts
let bar = new_bar();
// 1. transmuting *mut Bar to number still possible
let foo = new_foo(bar);
compute(bar, 10); // 2 errors
```

The compiler errors are also very human-readable:

```
Argument of type 'Pointer<"Bar">' is not assignable to parameter of type 'Pointer<"Foo">'.
  Type 'Pointer<"Bar">' is not assignable to type '{ [POINTER]: { type: "Foo"; }; }'.
    The types of '[POINTER].type' are incompatible between these types.
      Type '"Bar"' is not assignable to type '"Foo"'.
```

```
Argument of type 'number' is not assignable to parameter of type 'Pointer<"Bar">'.
  Type 'number' is not assignable to type '{ [POINTER]: { type: "Bar"; }; }'.
```

Note that casting from pointer to number is still possible, though this is as safe as `ptr as usize` in Rust and won't result in undefined behavior.

</details>

In addition to just a type, it would also be possible to represent the distinction between `*const T` and `*mut T` at least to some degree:

```ts
type PointerMut<T> = number & {[POINTER]: {type: T, mut: true}};
```

With this addition, `PointerMut<T>` implicitly downcasts to `Pointer<T>`, but not the other way around. This can be useful to prevent the following scenario:

```rs
pub fn get_name() -> *const u8;
pub fn get_name_len() -> usize;
pub fn read(buf: *mut u8, len: usize);
```

```ts
function get_name(): Pointer<"u8">;
function get_name_len(): number;
function read(buf: PointerMut<"u8">, len: number): void;
```

```ts
let namePtr = get_name();
let nameLen = get_name_len();
read(namePtr, nameLen);
// namePtr could now contain non-UTF-8 characters if this was possible
```

Thanks to the typing of pointers, this results in a human-readable Typescript error:

```
Argument of type 'Pointer<"u8">' is not assignable to parameter of type 'PointerMut<"u8">'.
  Type 'Pointer<"u8">' is not assignable to type '{ [POINTER]: { type: "u8"; mut: true; }; }'.
    Types of property '[POINTER]' are incompatible.
      Property 'mut' is missing in type '{ type: "u8"; }' but required in type '{ type: "u8"; mut: true; }'.
```

### Alternatives

Another approach to this problem could be to wrap each pointer in a class. This would prevent accidentally casting from a number, and also to a number (which my proposed solution doesn't prevent). However, this can result in a lot of object instantiations and pointer arithmetic may involve more overhead while my proposed solution only exists in the type system and is erased at runtime. Also, by using a `unique symbol` for branding, pointer types are not interchangeable between different WASM libraries (which have distinct memories).

```ts
class Pointer<T> {
  #address: number;

  get address() { return this.#number }
}

class PointerMut<T> extends Pointer<T> {}
```

### Additional Context

![image](https://github.com/rustwasm/wasm-bindgen/assets/26167910/e8aa0c99-26ee-45d2-b1f7-0e1975e7d023)

**Comment by daxpedda** [comment]
My TypeScript skills are pretty subpar, so I had to do some research just to be able to parse the syntax you are proposing.

While I do believe that introducing some TS types for pointers would be very useful, I don't believe we can use simple strings to denote the type. Type names can overlap in Rust, and while you can include the module name and even the crate name, don't forget that crate names can be duplicate as well!
Ideally we could check if the type is already exported in TS, then we can just use that. Otherwise we would have to use a unique ID somehow, I wouldn't know how, because [`Any::type_id()`](https://doc.rust-lang.org/1.80.0/std/any/trait.Any.html#tymethod.type_id) isn't really available on the proc-macro level.
So this would require some research.

Alternatively we just introduce `Pointer/Mut` without further type safety, which is still better then nothing.

All that said, I don't know how `wasm-bindgen` handled breaking changes in the TS output in the past.

---

Apologies for the late response, I actually had some text already queued but forgot to send it :/

**Comment by ColinTimBarndt** [comment]
> Type names can overlap in Rust, and while you can include the module name and even the crate name, don't forget that crate names can be duplicate as well!

I used strings in my examples because they're easy to use. Users could use builtin helper types to extract the pointer type from exported functions instead of writing out the discrete type, including a unique string identifier. It's also possible to use any type here, including unique symbols like the following:

```ts
declare const MyUniqueSymbol: unique symbol; // creates a variable that doesn't exist in JS, we only use it as a unique type here
type MyUniqueType = typeof MyUniqueSymbol; // unique type
type MyPointer = Pointer<MyUniqueType>;
```

I've used this for branding numbers as pointer before, such that different versions of the WASM bindings could be used in JS without interfering. The same trick can also be used for types from Rust.

The types could be exported using either namespaces or suffixes, but I don't know what the best convention would be to avoid breaking code if a new Rust function is exported, exposing the same type that's already used in an exported function, but of a different version of the same crate.

```ts
// export using suffixes
export type {my_crate_MyUniqueType_v0_1_0, my_crate_MyUniqueType_v0_2_0};

// export using namespaces
export declare namespace my_crate_v0_1_0 {
  export type {MyUniqueType};
}
export declare namespace my_crate_v0_2_0 {
  export type {MyUniqueType};
}
```

It's also possible to not export the types directly at all, and instead just export the functions using them. They could then be extracted for example using the `ReturnType<typeof someFunction>` builtin helper type. This would avoid the naming problem, which I would recommend, because naming things correctly is hard.

**Comment by daxpedda** [comment]
> The types could be exported using either namespaces or suffixes, but I don't know what the best convention would be to avoid breaking code if a new Rust function is exported, exposing the same type that's already used in an exported function, but of a different version of the same crate.

Crates can have the same name and version number as well, e.g. a Crates.io and git dependency.

> It's also possible to not export the types directly at all, and instead just export the functions using them. They could then be extracted for example using the `ReturnType<typeof someFunction>` builtin helper type. This would avoid the naming problem, which I would recommend, because naming things correctly is hard.

I'm not sure what you mean here, would you mind expanding on that proposal?

**Comment by ColinTimBarndt** [comment]
Sure, here's an example using only `Pointer` without the proposed `PointerMut` distinction in this case for simplicity.

#### lib.rs
```rs
pub struct Foo {
  n: f64,
}

pub fn make_foo(n: f64) -> *mut Foo { Box::new(Foo {n}).into_raw() }
pub unsafe fn foo_n(foo: *const Foo) -> f64 { (&*foo).n }
```

#### bindings.ts
```ts
declare const POINTER: unique symbol;
export type Pointer<T> = number & {[POINTER]: {type: T}};
export const NULL: Pointer<unknown> = 0 as Pointer<unknown>;

interface WasmExports {
  make_foo(n: number): Pointer<Foo_1337>;
  foo_n(foo: Pointer<Foo_1337>): number;
}

let instance: WasmExports | null = null;

export async function init() {
  instance = {} as any; // stub
}

// for generated bindings, this could just be named as the identifier
// followed by the type id, as it is not exported and wouldn't break
// anything if it's not consistent across builds
declare const Foo_1337: unique symbol;
type Foo_1337 = typeof Foo_1337;

export function make_foo(n: number): Pointer<Foo_1337> {
  return instance.make_foo(n);
}

export function foo_n(foo: Pointer<Foo_1337>): number {
  return instance.foo_n(foo);
}
```

#### usage.ts
```ts
import {init, make_foo, foo_n, Pointer} from "./bindings.ts";

await init();

// infers the pointer type from the return type of make_foo
type FooPtr = ReturnType<make_foo>; // Pointer<Foo_1337>

// Technically, it's possible to get Foo_1337 as well, but this has no practical use
type Foo = FooPtr extends Pointer<infer T> ? T : never; // Foo_1337

class FooWrapper {
  inner: FooPtr;

  constructor(n: number) {
    this.inner = make_foo();
  }

  get n() { return foo_n(this.inner); }

  // destructor logic omitted
}
```

**Comment by daxpedda** [comment]
Ah, I see! I didn't know about `ReturnType`, which is why it didn't make sense to me, I thought this is a type we make and not a TS utility type.

Okay, but this still goes back to creating a unique identifier for this type. It would be easy if we want to create a unique identifier for this *function*, but the type identifier has to be the same across functions for the same type, otherwise you wouldn't be able to pass a pointer to the same type around.

Again, I'm not aware of any way this can be solved. [`Any::type_id()`](https://doc.rust-lang.org/1.80.0/std/any/trait.Any.html#tymethod.type_id) doesn't work in a proc-macro.

**Comment by ColinTimBarndt** [comment]
> [Any::type_id()](https://doc.rust-lang.org/1.80.0/std/any/trait.Any.html#tymethod.type_id) doesn't work in a proc-macro.

That's a bummer. The only way that I can think of about how the type ids could be extracted, would be by generating another exposed function returning them. In this case, I'm using core intrinsics because there's no other way to actually get the type ID at the moment, sadly. Those functions and the static can then be snipped out of the WASM module. In this case, I'm using a static because there's currently no way to return a u128 from a function in WASM and I don't want to use allocations.

```rs
pub fn make_foo(n: f64) -> *mut Foo { /* ... */ }

// provided by wbindgen maybe
pub static mut WBINDGEN_TYPE_ID: u128 = 0;

// generated
pub unsafe fn make_foo__ty0() {
    ::core::ptr::write_volatile(::core::ptr::addr_of_mut!(WBINDGEN_TYPE_ID), ::core::intrinsics::type_id::<Foo>());
}
```

I guess a stable implementation of this would a) be more complicated than I thought and b) have to wait until either TypeId gives access to the actual ID or there's a stable intrinsic for it.

**Comment by daxpedda** [comment]
I assume you are also implying to transmute the internal data from `TypeId`, which might also be a bad idea.
Suffice to say unless somebody comes up with a good idea here, I'm gonna go ahead and close this.

But thank you for the effort!
