### ISSUE TITLE
Impl Into<JsValue> for Vec<T> where T: Into<JsValue> / Return Async Vec<T> where T: Into<JsValue> / Impl VectorIntoJsValue for arbitrary data

### ISSUE THREAD

**Issue by samankittani** [rustwasm/wasm-bindgen#4006]
@Liamolucko 
If you could help me with this problem, it would be greatly appreciated. Could you help me understand why this fails to compile with `wasm-pack build --target web`. I am aware of the workarounds (newtypes, returning Vec<JsValue>, etc. ). Is there a way to implement the new Vector traits for arbitrary data? When returning `Vec<Data>`, it would return `Vec<JsValue>` automatically, without explicitly changing the function signature. 

```rust
// this doesn't work
#[wasm_bindgen]
pub async fn test_wait_vec() -> Vec<Data>  //the trait `JsObject` is not implemented for `Data`, which is required by `Vec<Data>: wasm_bindgen::describe::WasmDescribe`
{
    vec![Data::new()]
}
// This works
#[wasm_bindgen]
pub async fn test_wait() -> Data {
    Data::new()
}

#[derive(Serialize, Deserialize, Tsify)]
#[into_wasm_abi]
pub struct Data {
    pub time: SystemTime,
    pub map: HashMap<Test, InnerData>,
}

impl Into<JsValue> for Data {
    fn into(self) -> JsValue {
        serde_wasm_bindgen::to_value(&self).unwrap()
    }
}

impl VectorIntoJsValue for Data {
    fn vector_into_jsvalue(vector: Box<[Data]>) -> JsValue {
        wasm_bindgen::__rt::js_value_vector_into_jsvalue(vector)
    }
}
```
The error is in the comment. 

When I implement any combination of the following traits below...
```rust 
impl WasmDescribeVector for Data {
    fn describe_vector() {
        inform(VECTOR);
        Data::describe();
    }
}

impl VectorIntoJsValue for Data {
    fn vector_into_jsvalue(vector: Box<[Data]>) -> JsValue {
        wasm_bindgen::__rt::js_value_vector_into_jsvalue(vector)
    }
}

impl VectorIntoWasmAbi for Data {
    type Abi = WasmSlice;

    fn vector_into_abi(vector: Box<[Self]>) -> WasmSlice {
        let jsvaluevec: Box<[JsValue]> = vector
            .iter()
            .map(|x| serde_wasm_bindgen::to_value(&x).unwrap())
            .collect();
        JsValue::vector_into_abi(jsvaluevec)
    }
}

```
I get a different error:
 
error: import of `__wbindgen_array_new` doesn't have an adapter listed
Error: Running the wasm-bindgen CLI
Caused by: Running the wasm-bindgen CLI

Thank you for your time! :)

**Comment by daxpedda** [comment]
From a quick glance I believe this might be related to #3919.
Let me know if this isn't the case after all.

Related: https://github.com/rustwasm/wasm-bindgen/pull/3630#issuecomment-2208976000.
Fixed by #3919.
