### ISSUE TITLE
Document more prominently that traits like `TryFromJsValue` are for internal use only

### ISSUE THREAD

**Issue by hrxi** [rustwasm/wasm-bindgen#4023]
I was reviewing code using [`wasm_bindgen::convert::TryFromJsValue`](https://docs.rs/wasm-bindgen/0.2.92/wasm_bindgen/convert/trait.TryFromJsValue.html) and it wasn't obvious to me that this is not meant to be used unless you know what you're doing. Could this be documented more clearly? It's already documented on the [`wasm_bindgen::convert`](https://docs.rs/wasm-bindgen/0.2.92/wasm_bindgen/convert/) module, but I didn't stumble upon this in the code review.

Some options:
1) rename the `convert` module to `internal` to make it more obvious from the import path.
2) mention that it's an internal item on all the items in the `convert` module.
3) mark the module as `#[doc(hidden)]` so they're not easily found when trying to look through the documentation.

**Comment by daxpedda** [comment]
> * mention that it's an internal item on all the items in the `convert` module.

This is probably the best solution.
I'm happy to look at a PR.
