### ISSUE TITLE
Version 0.2.93 does not work with async-channel

### ISSUE THREAD

**Issue by vmgarcia** [rustwasm/wasm-bindgen#4076]
### Describe the Bug

Latest wasm-bindgen update breaks compatibility with async-channel crate

### Steps to Reproduce

1. Use `spawn_local` to spawn a task that awaits a channel in a loop.
2. Compile and load library using wasm-bindgen 0.2.93.
3. Console in browser will say `RuntimeError: unreachable`

### Expected Behavior

should be able to use the async-channel crate

### Actual Behavior

wasm module errors out with "RuntimeError: unreachable"

![image](https://github.com/user-attachments/assets/2b504493-7443-4369-98b0-c16b744eb921)

**Comment by vmgarcia** [comment]
I switched to flume and it's unaffected

**Comment by daxpedda** [comment]
I was unable to reproduce this locally.
A minimal reproducible example would really help out here.
