### ISSUE TITLE
Experimental coverage feature breaks stable browser test

### ISSUE THREAD

**Issue by cdata** [rustwasm/wasm-bindgen#4083]
### Describe the Bug

When building a trivial test against `wasm-bindgen@0.2.93` and running it using `wasm-bindgen-test`, the browser-side test harness throws an exception as it tries to call into an experimental test coverage feature (causing the test runner to time out). The same test runs to completion when built against `wasm-bindgen@0.2.92` and run the same way.

### Steps to Reproduce

Using the following trivial test suite:

```rs
use wasm_bindgen_test::wasm_bindgen_test;
use wasm_bindgen_test::wasm_bindgen_test_configure;

wasm_bindgen_test_configure!(run_in_browser);

#[wasm_bindgen_test]
fn it_runs_a_test() {
    assert!(true)
}
```

1. Depend on `wasm-bindgen` at version `0.2.93`
2. Install `wasm-bindgen-cli` at version `0.2.93` 
3. Install the appropriate `chromedriver` for the local version of Chrome
4. Run the above test with `NO_HEADLESS=true CHROMEDRIVER=`which chromedriver` cargo test --target wasm32-unknown-unknown`
5. Open `http://127.0.0.1:8000` and refer to the error in the dev tools console

### Expected Behavior

The test passes; when run headlessly, the CLI output reflects the passing state.

### Actual Behavior

The test never runs; when run headlessly, the CLI times out.

### Additional Context

This error appears in the browser console when building against `wasm-bindgen@0.2.93`:

```
Uncaught SyntaxError: The requested module './wasm-bindgen-test' does not provide an export named '__wbgtest_cov_dump
```

**Comment by schell** [comment]
I've just hit this as well.

**Comment by daxpedda** [comment]
The issue is that you also need to update your `wasm-bindgen-test` dependency to v0.3.43.

This is a bit unfortunate and I'm not entirely sure how to prevent this in the future apart from pinning all dependencies on each other ...

Let me know if this doesn't solve your problem!
