### ISSUE TITLE
Appropriate way to contribute a web API interface that is changing (Gamepad hapticActuators -> vibrationActuator)

### ISSUE THREAD

**Issue by brettchalupa** [rustwasm/wasm-bindgen#4089]
### Summary

The Gamepad specification is in draft for for how force feedback (a.k.a. rumble, a.k.a. vibration) works. The specification within web-sys for [`hapticActuators`](https://github.com/rustwasm/wasm-bindgen/blob/0cbca3174acad5111725f7e7d4f1ab7c10bebaaf/crates/web-sys/webidls/enabled/Gamepad.webidl#L93-L98) is in [Editor's Draft as of 09 August 2024](https://w3c.github.io/gamepad/) to [change to](https://w3c.github.io/gamepad/#gamepad-interface):

``` webidl
[Exposed=Window]
interface Gamepad {
  readonly attribute DOMString id;
  readonly attribute long index;
  readonly attribute boolean connected;
  readonly attribute DOMHighResTimeStamp timestamp;
  readonly attribute GamepadMappingType mapping;
  readonly attribute FrozenArray<double> axes;
  readonly attribute FrozenArray<GamepadButton> buttons;
  [SameObject] readonly attribute GamepadHapticActuator vibrationActuator;
};
```

Notice the last line:

``` webidl
[SameObject] readonly attribute GamepadHapticActuator vibrationActuator;
```

`hapticActuators` has changed to `vibrationActuator`, and then the API for what that attribute is, a `GamepadHapticActuator`, has [a new API](https://w3c.github.io/gamepad/#gamepadhapticactuator-interface):

``` webidl
[Exposed=Window]
interface GamepadHapticActuator {
  [SameObject] readonly attribute FrozenArray<GamepadHapticEffectType> effects;
  Promise<GamepadHapticsResult> playEffect(
      GamepadHapticEffectType type,
      optional GamepadEffectParameters params = {}
  );
  Promise<GamepadHapticsResult> reset();
};
```

This definition differs from what's currently enabled in [GamepadHapticActuator.webidl](https://github.com/rustwasm/wasm-bindgen/blob/0cbca3174acad5111725f7e7d4f1ab7c10bebaaf/crates/web-sys/webidls/enabled/GamepadHapticActuator.webidl)

**So my question is this:** how does one go about contributing a change to an existing specification in this scenario? Would we add the new ones side-by-side with the existing? Or something else?

### Additional Details

- the Gamepad `hapticActuators` API is only supported in Firefox ([MDN](https://developer.mozilla.org/en-US/docs/Web/API/Gamepad/hapticActuators)) and is marked as experimental; it does not work from my testing
- the Gamepad `vibrationActuator` api is supported in Chrome, Edge, Opera, and Safari ([MDN](https://developer.mozilla.org/en-US/docs/Web/API/Gamepad/vibrationActuator)) and functions from my testing
- `hapticActuators` [appears to be](https://w3c.github.io/gamepad/extensions.html#partial-gamepad-interface) part of an older specification extension
- I couldn't find the WebIDL file that specifies the whole specification for Gamepad, but I think we can piece it together from https://w3c.github.io/gamepad/

Because many browsers do support the `vibrationActuator` property and it's in the Gamepad spec draft, it seems like it's the future standard; it'd be awesome is web-sys supported it for implementing rumble for controllers in WASM; that's the core motivation for this addition/change.

I'm happy to do the work to contribute this, but I figure since it's something changing, I should open an issue to start the conversation and get guidance. Thank you!

**Comment by daxpedda** [comment]
This API should probably not have been made stable in the first place, but fortunately none of these new additions require a breaking change to the already existing API.

Generally speaking we follow the spec no matter the browser support, but non-stable specifications should never override stable ones.

In this case adding all this new API unstably shouldn't be an issue and we can go ahead and deprecate the old API.

Let me know if you have any issues accomplishing any of this.

**Comment by brettchalupa** [comment]
@daxpedda thanks for the guidance, makes sense! I'll dig into adding the new API. Is there any reference/guidance for how to deprecate the old API?

**Comment by daxpedda** [comment]
To deprecate an API you just slap the [`[RustDeprecated]`](https://github.com/rustwasm/wasm-bindgen/blob/e4f8c4540aee2f3c0798fdae51ac7dace28e102b/crates/web-sys/webidls/enabled/AudioBufferSourceNode.webidl#L27) attribute on it.
