### ISSUE TITLE
Support Tail Call Proposal

### ISSUE THREAD

**Issue by CryZe** [rustwasm/wasm-bindgen#4096]
### Motivation

The tail call proposal is now supported by every browser. `wasm-bindgen` can't currently handle the proposal.

```
error: failed getting Wasm module for 'foo.wasm'

Caused by:
    0: failed to parse input as wasm
    1: failed to parse code section
    2: tail calls support is not enabled (at offset 0x2474f)
```

### Proposed Solution

It may just be a matter of updating some dependencies / enabling the proposal.

### Alternatives

None

### Additional Context

None

**Comment by daxpedda** [comment]
Isn't Rust support missing first?

But yes, this is not a problem of `wasm-bindgen` directly, but should be taken up with Walrus.
I'm seeing you already started working on it: https://github.com/rustwasm/walrus/pull/272 :rocket:.

In that light I will close this, but please let us know of any updates in this regard!

**Comment by CryZe** [comment]
Yeah I'll finish up the walrus PR and then open the followup PR here. Rust itself supports it just fine as it just forwards the feature to LLVM.
