### ISSUE TITLE
`wasm_bindgen::JsError` doesn't implement `Debug`

### ISSUE THREAD

**Issue by ldnvnbl** [rustwasm/wasm-bindgen#4099]
### Summary

`wasm_bindgen::JsError` doesn't implement `Debug`

### Additional Details

When I write unit test, I can't direct use unwrap or expect func, so I use match handle it, It's too long and ugly.
I want ask it can implement `Debug` or can some one tell me the best practice

**Comment by daxpedda** [comment]
On a quick glance I could not tell why this was not done, so I'm happy to review a PR.

**Comment by rcrisanti** [comment]
I also ran into this error recently, so I just opened up a PR for it here: #4136
