### ISSUE TITLE
mutable  obj  show warm

### ISSUE THREAD

**Issue by thedtvn** [rustwasm/wasm-bindgen#4112]
### Describe the Bug

when obj need to mut is show err that his obj is not mut
![image](https://github.com/user-attachments/assets/f0becafc-ade9-4b08-a1e7-c64cecbd4fc1)

**Comment by daxpedda** [comment]
This isn't a bug.
Since the latest version of `web-sys`, new setter methods were introduced, which you are already using here, that don't need mutable access.

**Comment by thedtvn** [comment]
> This isn't a bug. Since the latest version of `web-sys`, new setter methods were introduced, which you are already using here, that don't need mutable access.

@daxpedda if am not set it to mut it not modify the obj :/
and it show warn on rust runtime checker

**Comment by daxpedda** [comment]
> @daxpedda if am not set it to mut it not modify the obj :/

That doesn't sound right, but seems like a Rust problem to me and not a `wasm-bindgen` one.

I'm happy to take a bit of deeper look if you can share a minimal example of the problem you are encountering.

**Comment by thedtvn** [comment]
> > @daxpedda if am not set it to mut it not modify the obj :/
> 
> That doesn't sound right, but seems like a Rust problem to me and not a `wasm-bindgen` one.
> 
> I'm happy to take a bit of deeper look if you can share a minimal example of the problem you are encountering.

@daxpedda Sorry I think I fix it by updating the version
