### ISSUE TITLE
Let `#[wasm_bindgen_test]` resolve to just `#[test]` on non-wasm targets

### ISSUE THREAD

**Issue by matheus23** [rustwasm/wasm-bindgen#4139]
### Motivation

When writing tests for libraries that target both `target_family = "wasm"` and native targets, I need to do this cfg dance:
```rs
#[cfg_attr(all(target_family = "wasm", target_os = "unknown"), wasm_bindgen_test)]
#[cfg_attr(not(all(target_family = "wasm", target_os = "unknown")), test)]
fn test_something() {
  // ...
}
```

### Proposed Solution

This should just work on native targets:
```rs
#[wasm_bindgen_test]
fn test_something() {
  // ...
}
```

It should have the exact same effect as
```rs
#[test]
fn test_something() {
  // ...
}
```

### Alternatives

What's written in `Motivation`. I'd love to reduce the amount of `cfg`ing I have to do, though.

### Additional Context

Perhaps it'd be useful to also support common alternative macros to substitute with for native code. E.g. to make async functions work more easily:
```rs
#[wasm_bindgen_test(tokio::test)] // resolves to #[tokio::test] on native targets
async fn test_something() {
  // ...
}
```

**Comment by daxpedda** [comment]
Unfortunately we can't change the default here as that would be a breaking change.
I will make a PR shortly implementing it like this:
```
#[wasm_bindgen_test(unsupported = test)]
```
