### ISSUE TITLE
wasm-bindgen-test v0.3.44 causes `function is never used` compilation warnings for tests on WASM64

### ISSUE THREAD

**Issue by newpavlov** [rustwasm/wasm-bindgen#4161]
### Describe the Bug

In the `getrandom` crate we have code like this in [`tests/mod.rs`](https://github.com/rust-random/getrandom/blob/master/tests/mod.rs):
```rust
#[cfg(getrandom_browser_test)]
use wasm_bindgen_test::wasm_bindgen_test as test;
#[cfg(getrandom_browser_test)]
wasm_bindgen_test::wasm_bindgen_test_configure!(run_in_browser);

#[test]
fn test_zero() {
    // ...
}
```

As part of our CI we test that our code and tests compile for `wasm64-unknown-unknown` target using the following command: `RUSTFLAGS='-Dwarnings --cfg getrandom_backend="wasm_js" --cfg getrandom_browser_test' cargo test --no-run -Z build-std=std,panic_abort --target=wasm64-unknown-unknown`.

With `wasm-bindgen-test` v0.3.43 it works without issues, but the recent v0.3.44 release has [broken](https://github.com/rust-random/getrandom/actions/runs/11266154188/job/31329544540) our CI. With it we now get "function `test_zero` is never used" compilation warnings (which become errors because of the `-Dwarnings` flag). This does not happen for `wasm32-unknown-unknown` target.

The likely culprit is #4151, this [line](https://github.com/rustwasm/wasm-bindgen/pull/4151/files#diff-44ada20d1266a30f2c183c41398e3a5a1c3b7e8495612390d04c058f5baa4b5fR126) in particular.

cc @daxpedda

**Comment by newpavlov** [comment]
I've created the fix PR, but I also think that WASM64 should be tested as part of this repository's CI to prevent similar breakage in future.

**Comment by mthiesmeyer** [comment]
@newpavlov that will be a reasonable way to move forward once confirmation is received that this COB was either expected or more desirable than the previous behavior.

**Comment by daxpedda** [comment]
I can't find the breaking change here. Emitting a warning is not a breaking change, right?

To clarify: `wasm-bindgen` is only compatible with the `wasm32-unknown-unknown` target. Tests marked with `#[wasm_bindgen_test]` will only be tested when running on this target. So this warning is more desirable than the previous behavior.

If the desired behavior is to test other platforms, the new `#[wasm_bindgen_test(unsupported = test)]` functionality can be used.

**Comment by mthiesmeyer** [comment]
I agree, I wouldn't classify it as a breaking change. However, it is a change of behavior, and I am curious if it was intended or not before I start to work around it.

> So this warning is more desirable than the previous behavior.

I think I am in agreement on this. I'd say some of the crates in our workspace were incorrectly configured.

**Comment by daxpedda** [comment]
> I agree, I wouldn't classify it as a breaking change. However, it is a change of behavior, and I am curious if it was intended or not before I start to work around it.

Just to clarify: the **only** behavior that changed is the emitted warning! It wasn't tested on unsupported targets before #4151 and still isn't after.

**Comment by daxpedda** [comment]
I'm gonna go ahead and close this, please let me know if there is any new information or anything `wasm-bindgen` can do to improve the situation!

**Comment by fgsch** [comment]
Apologies to comment on an old and closed issue, but just ran into this and I wonder if we could apply a fix similar to https://github.com/wasm-bindgen/wasm-bindgen/pull/3180 in this case so the code is still "available" but does not produce dead code warnings.

**Comment by daxpedda** [comment]
So the point here was that this warning is actually desired, the change was intentional. If you get this warning it means that this code isn't tested.

I understand of course that there are situations where this warning isn't helpful, but it should be helpful in the most common situation: detecting misconfigured tests.

**Comment by fgsch** [comment]
> So the point here was that this warning is actually desired, the change was intentional. If you get this warning it means that this code isn't tested.

I'm not sure I understand. Given the snippet above:

```
pub fn main() {}

#[cfg(test)]
mod tests {
    use wasm_bindgen_test::wasm_bindgen_test;

    #[wasm_bindgen_test]
    fn example() {
        assert_eq!(5, 5)
    }
}
```

Why is `warning: function example is never used` desired? 
Happy to take this to discussions.

**Comment by daxpedda** [comment]
Because you probably wanted to do this instead:
```rust
    #[wasm_bindgen_test(unsupported = test)]
    fn example() {
        assert_eq!(5, 5)
    }
```
The warning means that your tests are not run in the current target.

I think the reason why most users encounter this is because the default target is the native one and not `wasm32-unknown-unknown`. In that case you should use a `.cargo/config.toml` with `build.target = "wasm32-unknown-unknown"` for e.g. rust-analyzer to pick it up.

Maybe the warning should be improved with these suggestions.
Let me know what you think!
