### ISSUE TITLE
Support creating `Uint8ClampedArray` views into wasm's memory

### ISSUE THREAD

**Issue by alexcrichton** [rustwasm/wasm-bindgen#421]
This [first came up](https://github.com/rustwasm/wasm-bindgen/pull/419#issuecomment-403296031) with #419 but some APIs on the web specifically take `Uint8ClampedArray`, so we should support taking a view into wasm's memory with this type of array! Today there's no easy way to create a `Uint8ClampedArray` which doesn't copy data from wasm's memory into a temporary buffer.

A strawman is something like:

```rust
#[wasm_bindgen]
extern {
    #[wasm_bindgen(clamped)]
    fn foo(a: &[u8]);
}
```

where that sort of vaguely means that all `&[u8]` arguments are actually clamped arrays instead of `Uint8Array`, but it's not great as it's not too configurable!

**Comment by fitzgen** [comment]
The goal being giving JS borrows of wasm memory, rather than copies, right?

**Comment by alexcrichton** [comment]
Indeed!

**Comment by fitzgen** [comment]
From a least-surprise, zero-cost perspective, I'd think that we should never copy by default, and that copying is something that one opts into rather than out of.

Also, clamping seems unrelated to copying, unless I am misunderstanding something about typed arrays.

**Comment by afdw** [comment]
Looks like this was accidentally closed?

**Comment by alexcrichton** [comment]
Oops!

**Comment by alexcrichton** [comment]
@RReverser oh other types are supported as `&[T]`, we just didn't have a way for `&[u8]` to be interpreted as "clamped" so this was added

**Comment by RReverser** [comment]
I see, I guess I misunderstood this issue and PR and it's unrelated to what I was looking for. Sorry!
