### ISSUE TITLE
`sequence<[EnforceRange] unsigned long>` compiler error

### ISSUE THREAD

**Issue by lizelive** [rustwasm/wasm-bindgen#4217]
### Steps to Reproduce

1. checkout https://github.com/lizelive/wasm-bindgen/blob/4bf006d408f1244800156eb8b531366740af6595/crates/web-sys/webidls/unstable/WebNN.webidl
2. build ` podman run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp/crates/web-sys         mcr.microsoft.com/devcontainers/rust:1 cargo run --release --package wasm-bindgen-webidl -- webidls src/features ./Cargo.toml`

If applicable, add a link to a test case (as a zip file or link to a repository we can clone).

### Expected Behavior

should compile 

### Actual Behavior

```
Error: compiling WebIDL into wasm-bindgen bindings in file "webidls/enabled/CanvasRenderingContext2D.webidl", line 368 column 3

Caused by:
    failed to parse webidl at byte position 83817
```

### Additional Context

you can work around by doing a `typedef [EnforceRange] unsigned long Index32;`

**Comment by daxpedda** [comment]
`wasm-bindgen-webidl` is not meant for public consumption, its an internal library.
If your intention is to contribute the WebNN API to `web-sys` I'm more then happy to look at a PR though. Even if you can't get it to work, I can help troubleshoot it there!

Let me know if need any further guidance!
