### ISSUE TITLE
RangeError: failed to grow table

### ISSUE THREAD

**Issue by GeTechG** [rustwasm/wasm-bindgen#4228]
### Describe the Bug
I'm guessing the problem is similar to #2943

### Steps to Reproduce

Unfortunately I haven't found out yet what exactly causes the error.
UPD. I seem to be able to recreate the code that gives the error, the problem appears when another function is called inside the function.
```rust
fn test() -> Option<String> {
    Some("".to_string())
}

#[wasm_bindgen]
pub fn test_wasm(data: Vec<u8>) -> Option<String> {
    test()
}
```

[wasm-opt.zip](https://github.com/user-attachments/files/17531811/wasm.zip)
[wasm-debug.zip](https://github.com/user-attachments/files/17531819/wasm.zip)
target: bundler

I build via wasm-pack in release mode, if I build in debug the problem is not observed, which proves that the problem is also in optimization.

**Comment by GeTechG** [comment]
The problem is in `wasm-opt`, I tried compressing myself through the binary https://github.com/WebAssembly/binaryen/releases/tag/version_119 and no such problem is observed.

**Comment by daxpedda** [comment]
It seems this problem has been resolved, let me know if it is not.

**Comment by johanpel** [comment]
For those searching for this error, this could also cause this issue: 
https://github.com/rustwasm/wasm-pack/issues/1446

**Comment by mi-prata** [comment]
Faced the same error in my application when running release mode with optimisations. 

We narrowed it down to be a system dependent issue that was happening on my machine only and the reason was that I had binaryen installed. 

Fixed it by running:
`sudo apt remove --purge binaryen`

**Comment by SSL-ACTX** [comment]
@mi-prata thanks a lot! ❤ 
Saved me *hours*
