### ISSUE TITLE
Upgrading from 0.2.93 to 0.2.95 does not emit JS code with link_to! macro

### ISSUE THREAD

**Issue by noname0310** [rustwasm/wasm-bindgen#4247]
### Describe the Bug

I'm using wasm-bindgen-rayon which has the following statement to emit a worker.js file.
```rust
#[allow(unused_must_use)]
fn _ensure_worker_emitted() {
    // Just ensure that the worker is emitted into the output folder, but don't actually use the URL.
    wasm_bindgen::link_to!(module = "/src/workerHelpers.worker.js");
}
```
https://github.com/RReverser/wasm-bindgen-rayon/blob/main/src/lib.rs#L56-L60

The problem is that since wasm-bindgen 0.2.95 this syntax doesn't work at all.

### Steps to Reproduce

*Requires [sccache](https://github.com/mozilla/sccache), [clang](https://clang.llvm.org/), and [llvm](https://llvm.org/)*

1. Clone https://github.com/noname0310/babylon-bulletphysics/tree/d00bd56412e63448822572f729669e243f3d2170
2. Type the following commands `npm i`, `npm run wasm-build-all
4. Goto ./src/wasm/md/
5. See error

### Expected Behavior

The file structure generated by a project using wasm-bindgen-rayon should look like this

![image](https://github.com/user-attachments/assets/75ceeb6e-50c1-4bd8-960b-c7da77916cdb)

### Actual Behavior

However, since worker.js is not emitted as of 0.2.95, it is generated like this.

![image](https://github.com/user-attachments/assets/1c357fb9-4ccc-4cb5-bdf3-2723bfe590e2)

**Comment by RunDevelopment** [comment]
I think this is a duplicate of #4233.

**Comment by noname0310** [comment]
This seems to be a duplicate. closing the issue.
