### ISSUE TITLE
JS type for enum string is not generated

### ISSUE THREAD

**Issue by skanehira** [rustwasm/wasm-bindgen#4248]
### Describe the Bug

JS type for enum string is not generated.

Rust code is bellow.
```rust
use wasm_bindgen::prelude::wasm_bindgen;

#[wasm_bindgen]
pub enum MyEnum {
    One = "one",
    Two = "two",
    Three = "three",
}

#[wasm_bindgen]
pub fn get_enum() -> MyEnum {
    MyEnum::One
}
```

Generated *.d.ts code is bellow.

```ts
/* tslint:disable */
/* eslint-disable */
/**
 * @returns {any}
 */
export function get_enum(): any;
```

### Steps to Reproduce

1. git clone https://github.com/skanehira/rust-wasm-bindgen-example
2. make build

### Expected Behavior

enum string should be

```ts
enum MyEnum {
    One = "one",
    Two = "two",
    Three = "three",
}
```

### Actual Behavior

enum string always be `any`.

**Comment by RunDevelopment** [comment]
Duplicate of #2153.

Also, the next release will include #4180, so the `.d.ts` will then look like this:

```ts
/* tslint:disable */
/* eslint-disable */
type MyEnum = "one" | "two" | "three";
export function get_enum(): MyEnum;
```

**Comment by skanehira** [comment]
@RunDevelopment Oh, I got it.
Thank you :)
