### ISSUE TITLE
#[wasm_bindgen] in crate with #![deny(missing_docs)]?

### ISSUE THREAD

**Issue by limira** [rustwasm/wasm-bindgen#425]
Sorry because this is a simple question. But I am unable to find the answer myself! If my crate require docs: `#![deny(missing_docs)]`, there are errors cause by `#[wasm_bindgen]`:

```rust
//! Docs for the crate
#![deny(missing_docs)]
#![feature(proc_macro, wasm_custom_section, wasm_import_module)]
extern crate wasm_bindgen;
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
/// Docs for the struct
pub struct Struct {
    /// Docs for the field
    pub id: u32,
}
```
Error message:
```
error: missing documentation for a function
 --> src/lib.rs:7:1
  |
7 | #[wasm_bindgen]
  | ^^^^^^^^^^^^^^^
  |
```
How can I supply `doc` for them? Or just simply hide them with `#[doc(hidden)]`?

**Comment by alexcrichton** [comment]
Ah I don't believe there's anything you can do here, but it's definitely a [bug in wasm-bindgen](https://github.com/rustwasm/wasm-bindgen/pull/428)!
