### ISSUE TITLE
wasm-bingen fails to parse files with relaxed-simd instructions

### ISSUE THREAD

**Issue by dragostis** [rustwasm/wasm-bindgen#4263]
Any Rust crate with a `core::arch::wasm32::f32x4_relaxed_madd` call will break wasm-bindgen thusly (as reported by wasm-pack):

```
Caused by:
    0: failed to parse input as wasm
    1: failed to parse code section
    2: relaxed SIMD support is not enabled (at offset 0x332b)
Error: Running the wasm-bindgen CLI
Caused by: Running the wasm-bindgen CLI
Caused by: failed to execute `wasm-bindgen`: exited with exit status: 1
  full command: "/Users/dragos/.cargo/bin/wasm-bindgen" "/Users/dragos/Documents/rust/engine/target/wasm32-unknown-unknown/release/engine.wasm" "--out-dir" "/Users/dragos/Documents/rust/engine/pkg" "--typescript" "--target" "web"
```

It seems like this is caused by not having a way to enable the `relaxed-simd` feature in the parser.

**Comment by daxpedda** [comment]
I created a PR at Walrus for this: https://github.com/rustwasm/walrus/pull/281.

This should automatically start working with the next point release of Walrus, so I will go ahead and close this issue as there is nothing `wasm-bindgen` can do here.
