### ISSUE TITLE
Request: expose `walrus/parallel` flag on cli-support crate

### ISSUE THREAD

**Issue by jkelleyrtp** [rustwasm/wasm-bindgen#4314]
### Motivation

Hi there - I'm using the cli-support crate in the Dioxus CLI and I recently ran into an issue where we were having suboptimal performance since `wasm-bindgen` enables the `parallel` flag on walrus, but the cli-support crate does not.

https://github.com/rustwasm/wasm-bindgen/blob/main/crates/cli-support/Cargo.toml

I fixed this by adding walrus to my tree and turning on the flag manually, like wasm-bindgen:

https://github.com/rustwasm/wasm-bindgen/blob/main/crates/cli/Cargo.toml#L34

However, whenever wasm-bindgen updates its walrus version, Dioxus will be setting the `parallel` flag on the wrong walrus (ie 22 vs 23) until we fix it manually.

Is it possible for the cli-support crate to re-export the `walrus/parallel` flag directly under its own parallel flag?

**Comment by daxpedda** [comment]
I don't see a reason why we wouldn't just enable the crate feature in `cli-support` directly. Will go ahead and do just that.
