### ISSUE TITLE
Using `js_namespace = []` causes a crash in the CLI

### ISSUE THREAD

**Issue by RunDevelopment** [rustwasm/wasm-bindgen#4328]
### Describe the Bug

```rs
#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(js_namespace = [])]
    fn my_function();
}
```

The proc macro allows this, but the CLI crashes with:

```
    status: exit code: 101
    stderr:
        thread 'main' panicked at crates\cli-support\src\wit\mod.rs:1087:34:
        range start index 1 out of range for slice of length 0
        note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Steps to Reproduce

Compile the code and run the CLI.

### Expected Behavior

I'm not sure, whether the proc macro should just not allow this, or whether this should be interpreted as "no namespace".

### Actual Behavior

Crash.

### Additional Context

We currently internally represent the namespace of an imported item as `Option<Vec<String>>`. The CLI apparently assumes that the inner `Vec` is non-empty.

**Comment by daxpedda** [comment]
> I'm not sure, whether the proc macro should just not allow this, or whether this should be interpreted as "no namespace".

I think we should allow this but emit a warning. The easier way is definitely to disallow it.

The CLI should obviously not crash either way.
