### ISSUE TITLE
Using exported Rust structs causes detached Buffer issue

### ISSUE THREAD

**Issue by Anoromi** [rustwasm/wasm-bindgen#4352]
### Describe the Bug
When creating a function that accepts a vector of exported rust structs in rust > 1.82 on big enough sizes function returns an error.

### Steps to Reproduce

1. Use hello_world example and set wasm_bindgen to version 2.99.
2. Create a function and a struct in rust:
```rust
#[wasm_bindgen]
#[derive(Clone, Copy, Debug)]
pub struct PartialTestData {
    pub a: u32,
    pub b: f64,
    pub c: f64,
}

#[wasm_bindgen]
impl PartialTestData {
    #[wasm_bindgen(constructor)]
    pub fn new(a: u32, b: f64, c: f64) -> Self {
        return Self { a, b, c };
    }
}

#[wasm_bindgen]
pub fn test_sum(param: Vec<PartialTestData>) -> u64 {
    let mut k = 0u64;
    for v in param {
        k += u64::from(v.a)
    }
    return k;
}
```
3. Replace index.js file with call to a function:
```js
import { PartialTestData, test_sum } from "./pkg";

const size = 1_000_000;
const values = new Array(size)
  .fill(0)
  .map((_, i) => new PartialTestData(i, 0, 0));
alert(test_sum(values));
```
5. Run `npm install`, `npm run serve`
6. Open the browser
7. See error

### Expected Behavior

Alert with a result of a computation.

### Actual Behavior

An exception in console `TypeError: attempting to access detached ArrayBuffer` in Firefox or `TypeError: Cannot perform DataView.prototype.setUint32 on a detached ArrayBuffer` in Chrome

![image](https://github.com/user-attachments/assets/59415102-8e05-454e-89da-1fe7b6fd8f35)

### Additional Context

The issue doesn't happen in versions of rust below 1.82. I also didn't test options other than bundler.

**Comment by mProjectsCode** [comment]
I am facing the same issue. A rollback to `wasm-bindgen = "=0.2.92"` seems to also fix the issue.

**Comment by daxpedda** [comment]
Note: the bug is specific to the reference type transformations. So it doesn't show up in `0.2.92` because reference type transformations were not enabled by default back then.
