### ISSUE TITLE
Add IndexedDB and web-sys example to `examples/` and guide

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-bindgen#441]
General info on IndexedDB: https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API

* [ ] Add an example to `examples/` that shows off working with IndexedDB
* [ ] Add a subsection to "web-sys >> examples" in the guide that includes this example

**Comment by alexcrichton** [comment]
I"m gonna close this in favor of https://github.com/rustwasm/gloo/issues/68 because I think IndexedDB is more likely to be covered by gloo rather than wasm-bindgen examples

**Comment by indolering** [comment]
@alexandrestein rustwasm/gloo#68 has been closed and won't be implemented.

**Comment by Pauan** [comment]
@indolering We still plan to add an API for IndexedDB, though probably not that specific API.

**Comment by datdinhquoc** [comment]
Please, examples for IndexedDB in web-sys, I can't get it working.

Got the IdbDatabase, got IdbObjectStore, but failed to add a doc:
```
// The store is already in db with key id, autoIncremental
myStore.add(&JsValue::from_str("{test:1}")).unwrap();
```

Failed at '.unwrap()', although it's a Result.
