### ISSUE TITLE
Add WebAudio support to web-sys

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-bindgen#443]
This is a tracking issue for adding support for the web audio API to the `web-sys` crate.

General info on web audio: https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API

How to add support for new Web APIs to `web-sys`: https://rustwasm.github.io/wasm-bindgen/web-sys/supporting-more-web-apis.html

## Interfaces

Here is a list of interfaces we need to support:

* [ ] `AudioContext`
* [ ] `AudioContextOptions`
* [ ] `AudioNode`
* [ ] `AudioParam`
* [ ] `AudioParamMap`
* [ ] `BaseAudioContext`
* [ ] `The ended event`
* [ ] `AudioScheduledSourceNode`
* [ ] `OscillatorNode`
* [ ] `AudioBuffer`
* [ ] `AudioBufferSourceNode`
* [ ] `MediaElementAudioSourceNode`
* [ ] `MediaStreamAudioSourceNode`
* [ ] `BiquadFilterNode`
* [ ] `ConvolverNode`
* [ ] `DelayNode`
* [ ] `DynamicsCompressorNode`
* [ ] `GainNode`
* [ ] `WaveShaperNode`
* [ ] `PeriodicWave`
* [ ] `IIRFilterNode`
* [ ] `AudioDestinationNode`
* [ ] `MediaStreamAudioDestinationNode`
* [ ] `AnalyserNode`
* [ ] `ChannelSplitterNode`
* [ ] `ChannelMergerNode`
* [ ] `AudioListener`
* [ ] `PannerNode`
* [ ] `StereoPannerNode`
* [ ] `OfflineAudioContext`
* [ ] `complete (event)`
* [ ] `OfflineAudioCompletionEvent`
* [ ] `JavaScriptNode`
* [ ] `WaveTableNode`

## Example

* [ ] Add an example to `examples/` that shows off working with web audio

**Comment by eminence** [comment]
I took a look at this over the weekend.  Nearly all of these interfaces are "enabled", but many of them are incomplete due to lack of dictionary support (#241).   But once that is fixed up, I'll be happy to develop some Web Audio examples

**Comment by fitzgen** [comment]
Yeah, most of these issues domain-specific webidl issues I filed are half out of date because of the big PR that just enabled everything. As you point out, a lot of functionality is still missing for various reasons, so we can use them as tracking issues for whatever is blocking the interfaces being functional and usable. I also think the examples will be really great to get in tree, and we can even include them into the wasm-bindgen guide.

**Comment by fitzgen** [comment]
We have an example and its included in the guide. I think we can close this issue and opportunistically take more sanity tests for interfaces if/when they come.
