### ISSUE TITLE
Add SVG elements' interfaces to web-sys

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-bindgen#448]
This is a tracking issue for adding support for adding the SVG elements' interfaces to the `web-sys` crate.

General info on SVG interfaces: https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model#SVG_interfaces

How to add support for new Web APIs to `web-sys`: https://rustwasm.github.io/wasm-bindgen/web-sys/supporting-more-web-apis.html

## Interfaces

Here is a list of interfaces we need to support:

* [ ] `SVGAElement`
* [ ] `SVGAnimationElement`
* [ ] `SVGAnimateElement`
* [ ] `SVGAnimateMotionElement`
* [ ] `SVGAnimateTransformElement`
* [ ] `SVGCircleElement`
* [ ] `SVGClipPathElement`
* [ ] `SVGComponentTransferFunctionElement`
* [ ] `SVGCursorElement`
* [ ] `SVGDefsElement`
* [ ] `SVGDescElement`
* [ ] `SVGElement`
* [ ] `SVGEllipseElement`
* [ ] `SVGFEBlendElement`
* [ ] `SVGFEColorMatrixElement`
* [ ] `SVGFEComponentTransferElement`
* [ ] `SVGFECompositeElement`
* [ ] `SVGFEConvolveMatrixElement`
* [ ] `SVGFEDiffuseLightingElement`
* [ ] `SVGFEDisplacementMapElement`
* [ ] `SVGFEDistantLightElement`
* [ ] `SVGFEDropShadowElement`
* [ ] `SVGFEFloodElement`
* [ ] `SVGFEFuncAElement`
* [ ] `SVGFEFuncBElement`
* [ ] `SVGFEFuncGElement`
* [ ] `SVGFEFuncRElement`
* [ ] `SVGFEGaussianBlurElement`
* [ ] `SVGFEImageElement`
* [ ] `SVGFEMergeElement`
* [ ] `SVGFEMergeNodeElement`
* [ ] `SVGFEMorphologyElement`
* [ ] `SVGFEOffsetElement`
* [ ] `SVGFEPointLightElement`
* [ ] `SVGFESpecularLightingElement`
* [ ] `SVGFESpotLightElement`
* [ ] `SVGFETileElement`
* [ ] `SVGFETurbulenceElement`
* [ ] `SVGFilterElement`
* [ ] `SVGFilterPrimitiveStandardAttributes`
* [ ] `SVGForeignObjectElement`
* [ ] `SVGGElement`
* [ ] `SVGGeometryElement`
* [ ] `SVGGradientElement`
* [ ] `SVGGraphicsElement`
* [ ] `SVGImageElement`
* [ ] `SVGLinearGradientElement`
* [ ] `SVGLineElement`
* [ ] `SVGMaskElement`
* [ ] `SVGMetadataElement`
* [ ] `SVGMPathElement`
* [ ] `SVGPathElement`
* [ ] `SVGPatternElement`
* [ ] `SVGPolylineElement`
* [ ] `SVGPolygonElement`
* [ ] `SVGRadialGradientElement`
* [ ] `SVGRectElement`
* [ ] `SVGScriptElement`
* [ ] `SVGSetElement`
* [ ] `SVGStopElement`
* [ ] `SVGStyleElement`
* [ ] `SVGSVGElement`
* [ ] `SVGSwitchElement`
* [ ] `SVGSymbolElement`
* [ ] `SVGTextContentElement`
* [ ] `SVGTextElement`
* [ ] `SVGTextPathElement`
* [ ] `SVGTextPositioningElement`
* [ ] `SVGTitleElement`
* [ ] `SVGTSpanElement`
* [ ] `SVGUseElement`
* [ ] `SVGViewElement`

## Example

* [ ] Add an example to `examples/` that shows off working with SVG

**Comment by fitzgen** [comment]
@sepiropht we already enabled pretty much all of these interfaces, and we just need sanity testing and an example for working with SVG now. If you'd like to help out with that, it would be very appreciated!

**Comment by sepiropht** [comment]
Ok i can try that. 
@fitzgen And by 'sanity test' you mean testing only the essential ie SVGElement ?

**Comment by fitzgen** [comment]
Similar to stuff like

* https://github.com/rustwasm/wasm-bindgen/blob/master/crates/web-sys/tests/wasm/event.rs
* https://github.com/rustwasm/wasm-bindgen/blob/master/crates/web-sys/tests/wasm/table_element.rs
* https://github.com/rustwasm/wasm-bindgen/blob/master/crates/web-sys/tests/wasm/dom_point.rs

Basically, we just want to test the essential things for an interface, don't need to test all of an interface's inherited methods or whatever.

We just want to be fairly confident that things are working as expected.

**Comment by mstallmo** [comment]
@sepiropht what interfaces were you planning to work on? I was hoping to chip in on this as well but don't want to step on your toes!

**Comment by mstallmo** [comment]
Cool! I'll start on SVGAElement.
