### ISSUE TITLE
Add the fetch API to web-sys

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-bindgen#449]
This is a tracking issue for adding support for the fetch API to the `web-sys` crate.

General info on the fetch API: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API

How to add support for new Web APIs to `web-sys`: https://rustwasm.github.io/wasm-bindgen/web-sys/supporting-more-web-apis.html

## Interfaces

Here is a list of interfaces we need to support:

* [ ] `fetch()`
* [x] `Headers`
* [ ] `Request`
* [x] `Response`
* [ ] `Body`

## Example

* [ ] Add an example to `examples/` that shows off working with the fetch API

**Comment by brisad** [comment]
While `Headers` does show up in the docs, it does not have any methods. Should it still be added like that (without tests), or should I check into why `wasm_bindgen_webidl` doesn't export the methods? I see a bunch of warnings of unsupported definitions when building.
