### ISSUE TITLE
Wasm validation errors with certain floating point math

### ISSUE THREAD

**Issue by allindier** [rustwasm/wasm-bindgen#484]
I've been running into a kind of peculiar issue with floating point math when using wasm bindgen.  I've provided a simplified example below that seems to have the exact problem.  What occurs is that when I try to load the wasm into the browser (using webpack) I get a console error that says:

`CompileError: wasm validation error: at offset 169: expected 'anyfunc' element type`

After backtracking through a lot of code, I found that the issue somehow seems to be related to having both of the following floating point operations.  For whatever reason, all of the steps in `test_two` are required to cause this to happen.  At this point, I'm getting around the issue by casting the `f64` to an `i64` and then back for the modulus step, but I would prefer to avoid this.

In the example provided below, it only seems to fail when built in debug, although this problem also happens to me when building in release when I build with the rest of my code.  I haven't figured out what parts of that code contribute to this problem, so I've stuck with this toy example.

I'm not super familiar with Rust or wasm, so any help would be appreciated.

Cargo.toml

    [package]
    name = "test-package"
    version = "0.1.0"
    authors = ["Harold"]

    [lib]
    crate-type = ["cdylib"]

    [dependencies]
    wasm-bindgen = "0.2"

lib.rs

    #![feature(proc_macro, wasm_import_module, wasm_custom_section)]
    
    extern crate wasm_bindgen;
    
    use wasm_bindgen::prelude::*;
    
    #[wasm_bindgen]
    pub struct Test {}
    
    #[wasm_bindgen]
    impl Test {
        pub fn test_one() -> f64 {
            let num = 13_f64;
            let other_num = 42_f64;
            num.atan2(other_num)
        }
    
        pub fn test_two() -> f64 {
            let num = 4_f64;
            let a = num.round();
            let b = a % 2_f64;
            b / 15_f64
        }
    }

I build the wasm to load into the browser with:

    cargo build --target wasm32-unknown-unknown
    wasm-bindgen target\wasm32-unknown-unknown\debug\geodesy_wa.wasm --out-dir .\pkg --debug --browser

Rust version: 1.29.0-nightly (I believe this was also happening in 1.26; I updated while trying to troubleshoot the problem)
System: Windows 10
Browser: Firefox 60.0

**Comment by alexcrichton** [comment]
Thanks for the report! I'm unfortunately unable to reproduce with the above code though, could you perhaps gist a repo which includes your webpack config and a lock file for the npm dependencies as well as Rust dependencies?

**Comment by allindier** [comment]
https://gist.github.com/allindier/7223efe89cfe1d289fb3e9ce2864d970

Thanks for taking a look!

**Comment by alexcrichton** [comment]
Ok thanks! It looks like this was a webpack issue as I verified the raw output of wasm-bindgen is a valid wasm module, and after updating webpack (removing `package-lock.json` and re-running `npm install`) it seems to work. Can you confirm updating webpack fixes the issue?

**Comment by allindier** [comment]
Yeah, that fixed the issue on my end.  Thanks!
