### ISSUE TITLE
Zero-garbage memory transfers

### ISSUE THREAD

**Issue by jsheard** [rustwasm/wasm-bindgen#495]
In WebGL 1.0, functions for uploading data to a buffer or texture look like this:

    void bufferData(GLenum target, BufferSource? srcData, GLenum usage);

This is usable from wasm_bindgen but comes with a catch, as the JS bindings have to allocate a subarray of wasm memory to isolate the slice being passed to `srcData`, therefore every upload operation puts pressure on the JS garbage collector. WebGL 2.0 allows us to do better by using functions of this form:

    void bufferData(GLenum target, ArrayBufferView srcData, GLenum usage, GLuint srcOffset, optional GLuint length = 0);

Using this variant we could pass the entire wasm memory into `srcData` then use `srcOffset` and `length` to isolate the slice, which achieves the same result without creating any garbage. [Emscripten observed a 3-7% performance gain when switching to these zero-garbage APIs.](https://kripken.github.io/emscripten-site/docs/optimizing/Optimizing-WebGL.html#which-gl-mode-to-target)

The issue is there's currently no way to express this kind of binding in wasm_bindgen - we need some way to pass a JS function the entire wasm memory buffer rather than a sub-region of it.

**Comment by jsheard** [comment]
Binding the function that way gives us zero-**copy** transfers, but the subslice is still a full JS object that needs to be garbage collected even though it's pointing to data in an existing buffer. That's specifically why WebGL 2.0 added those new function variants, so more demanding apps can avoid thrashing the GC with 100,000s of subslice objects per second.

This is certainly a low-priority issue since it only affects performance and only in some very specific cases (mainly WebGL) but it would be nice to resolve eventually.

**Comment by alexcrichton** [comment]
Aha sorry I misunderstood! That makes perfect sense though. I think we could tweak it to just take `&JsValue`, right? That way the same JS value would be passed in each time?

**Comment by jsheard** [comment]
So, something like this?

```
#[wasm_bindgen]
extern {
    fn buffer_data(target: u32, src_data: &JsValue, usage: u32, srcOffset: u32, length: u32);
}
```

which could be used like this

```
gl.buffer_data(gl.ARRAY_BUFFER, &JsValue::memory_u8(), data.as_ptr() as u32, data.len() as u32);
```

where `JsValue::memory_u8()` is a special value that maps to the current cached `Uint8Array` wrapping the wasm memory. That sounds like it should work.

**Comment by alexcrichton** [comment]
Indeed that's what I was thinking! 

I'm not sure exactly how to expose importing your own memory, but adding a various function on `JsValue` or somewhere in `wasm_bindgen` should be more than appropriate.

**Comment by alexcrichton** [comment]
Ah right yes, true!
