### ISSUE TITLE
Add webidl `optional` support to web-sys

### ISSUE THREAD

**Issue by derekdreery** [rustwasm/wasm-bindgen#502]
Currently `optional` parameters are forced. I think they should be an `Option<T>`.

This depends on #14 to generate the correct glue code, provided the way options are represented in the end is compatible with these APIs.

Also, in the spec, `optional` parameters can have a default. This doesn't really affect the rust function, but it could be mentioned in some generated documentation, perhaps.

WebIDL snippet from the Console api (`console.*`):

```webidl
[UseCounter]
void count(optional DOMString label = "default");
```

**EDITS**
 - 2018-07-18 Added more detail.

**Comment by fitzgen** [comment]
What rust-bindgen does is pretty sucky, and I hope we can come up with something better. Even just a better mangling algorithm would be an improvement, eg

```rust
#[wasm_bindgen]
extern {
    fn count();
    #[wasm_bindgen(js_name = count)]
    fn count_label(label: &str); // concatenate each optional argument's name to the method name
}
```

**Comment by derekdreery** [comment]
I can do this for now. I'm doing the console API, and maybe having a concrete implementation to see will aid bikeshedding.
