### ISSUE TITLE
Add webidl variadic (`...`) support to web-sys

### ISSUE THREAD

**Issue by derekdreery** [rustwasm/wasm-bindgen#503]
Like `optional` this requires deciding how to represent this in rust. It could be a slice (so `...any` becomes `&[JsValue]`, etc.), or a varargs function. Since varargs isn't implemented yet ([tracking issue]), probably best to go with a slice.

Example of a variadic function in WebIDL (Console API):

```webidl
[UseCounter]
void log(any... data);
```

[tracking issue]: https://github.com/rust-lang/rust/issues/44930

**Comment by fitzgen** [comment]
Fixed in #726
