### ISSUE TITLE
Automatic documentation generation for web-sys bindings

### ISSUE THREAD

**Issue by alexcrichton** [rustwasm/wasm-bindgen#513]
It'd be awesome if we could automatically hook up something like `Element::class_name` to the [MDN docuementation for the method](https://developer.mozilla.org/en-US/docs/Web/API/Element/className)!

**Comment by TimNN** [comment]
Were you thinking about just linking to the MDN page or including part of it as rust comments?

**Comment by alexcrichton** [comment]
Oh nothing as fancy as scraping words, just mdn URLs!

**Comment by jonathanKingston** [comment]
Some improvements on what I just submitted:

- [ ] Mock arguments to setters like `input.accept = "val";` based on their type.
- [ ] Explain arguments to methods like: `document.querySelector('val')` or `document.querySelector(selectors)`
- [ ] Scrape code examples from MDN, use ESTree to translate them to Rust.
- [ ] Provide a mode that checks for 404's on links and omits them if they don't exist. (a fair few of the `HTML*Interface.getter` don't exist)
- [ ] Place Rust code examples in a file and combine them, this would provide the best code examples and also provide compile time checks for the documentation against webidl changes. (It may make sense to have some IDL overrides in a file anyway: #458)
