### ISSUE TITLE
Travis regularly times out on "npm ci"

### ISSUE THREAD

**Issue by alexcrichton** [rustwasm/wasm-bindgen#517]
I'm not really sure why but Travis will regularly time out with `npm ci` not emitting output for 10 minutes. This seems to happen sporadically but fairly regularly. Some example logs are:

* https://travis-ci.org/rustwasm/wasm-bindgen/jobs/405978557
* https://travis-ci.org/rustwasm/wasm-bindgen/jobs/405978581
* https://travis-ci.org/rustwasm/wasm-bindgen/jobs/405964606
* https://travis-ci.org/rustwasm/wasm-bindgen/jobs/405869282
* https://travis-ci.org/rustwasm/wasm-bindgen/jobs/405837840
* https://travis-ci.org/rustwasm/wasm-bindgen/jobs/405837842

Does anyone know why this is happening? Is there a way we can help debug this?

**Comment by Alexendoo** [comment]
You can use `npm ci --verbose` to see what operation it is hanging on

**Comment by alexcrichton** [comment]
Hm well this hasn't happened in awhile that I've seen, so maybe the verbose output actually helps us! In any case we should be set next time it times out to investigate further, thanks @Alexendoo!

**Comment by alexcrichton** [comment]
Looks like we hit this first on https://travis-ci.org/rustwasm/wasm-bindgen/jobs/409944853
