### ISSUE TITLE
Support `#[wasm_bindgen]` from within rust `mod`s.

### ISSUE THREAD

**Issue by derekdreery** [rustwasm/wasm-bindgen#551]
# Motivation

I'm looking at how to implement enough of the webidl to wasm compiler to use the `console` webidl definition. It uses the `namespace` construct which is not yet handled. There are two approaches one could take to creating the rust-js glue that I can think of:
 - name mangling (`namespace_function`, e.g. `console_log` in rust (or some other mangling strategy))
 - using rust modules (`namespace::function` e.g. `console::log` in rust)

Rust modules would be more ergonomic, I think, so I propose supporting them in the AST.

I don't think they can be supported in the wasm_bindgen proc_macro because you can't have attributes on modules (or at least this is what I was told by the compiler).

# Implementation
Here is a bit of a brain dump on my progress so far.
 - I think we would only need a depth of 1, since WebIDL namespaces cannot contain other namespaces.
 - Start with just supporting `Import`s in a module, since this is what is needed for the console api.
 - Could the codegen for functions be reused, does it need generalising to modules, or do we need new codegen.

Does this sound like the best approach? What are your thoughts on the implementation notes?

**Comment by fitzgen** [comment]
Agreed that we would want to translate webidl namespaces into modules.

I'm unsure what this issue is supposed to cover that #253 doesn't?

**Comment by derekdreery** [comment]
I'd forgotten that in that issue you describe converting namespaces into rust modules, so the first part of this issue is redundant.

The other part is that we can split the task into creating the AST, and the codegen. I can do the first part, but I still need to look more at the codegen side of things to understand it all.
