### ISSUE TITLE
links to self in docs aren't resolving correctly

### ISSUE THREAD

**Issue by yoshuawuyts** [rustwasm/wasm-bindgen#569]
## Problem

In https://rustwasm.github.io/wasm-bindgen/web-sys/supporting-more-web-apis.html, the link https://rustwasm.github.io/web-sys/testing.html does not resolve to anything.

Instead it's meant to link to https://rustwasm.github.io/wasm-bindgen/web-sys/testing.html, but it's missing the `/wasm-bindgen/` piece of the path.

There are more instances of this occurring on the same page, which probably means there are more instances of this happening throughout the book.

## Possible solutions
- inject a [`<base>` tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base). This can be a bit weird to work with though; I've had mixed experiences with it.
- maybe there's an `mdbook` to set the root correctly?
- manually go over all links and prefix them with `/wasm-bindgen/`.

---

hope this is helpful!

**Comment by alexcrichton** [comment]
Thanks for the report!
