### ISSUE TITLE
Copy doc comments from Rust to JS

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-bindgen#57]
Would be good for JS programmers reading the generated JS to have documentation on

* Classes
* Methods
* Functions
* Anything else that gets emitted and has a doc comment in the Rust version

**Comment by FreeMasen** [comment]
Would that require a modification to #23 to include the doc comment strings?

**Comment by alexcrichton** [comment]
Indeed! That's fine though, the format isn't specified yet :)

**Comment by FreeMasen** [comment]
After #265 we are now copying doc comments from Rust to JS for the following using the [JSDoc](http://usejsdoc.org/) format. 

- Classes
- Methods
- Public Attributes
- Functions

The only other doc comments that I can think of would be module level comments. 

One of the nice things about the JSDoc comments is that they define the tooltip content when working in VSCode. I would ideally like to see the following annotated lines added to our current translation.

- `@constructor`: When using `no-modules` this would be added to the prototype function
- `@param {type} name`: This would be added for each parameter in a function signature
- `@returns {type}`: This would be added to functions and methods that return non-unit types
  - We could also have unit returns annotated with `void`

Both `@param` and `@returns` optionally can have a description added to them, I do not believe that Rust Doc comments have this feature?
