### ISSUE TITLE
Lots of malformed WebIDL files

### ISSUE THREAD

**Issue by derekdreery** [rustwasm/wasm-bindgen#570]
A lot of the WebIDL files are malformed in the same way: they have an interface declaration like so:

```webidl
interface nameofinterface;
```

which is not valid WebIDL. The valid equivalent is

```webidl
interface nameofinterface {};
```

We could either change all the webidl files to be correct, or adapt the parser to handle the above form.

**Comment by jrakow** [comment]
The conclusion in #446 is:
> it is fine to just comment it out and leave a comment about why it is commented out.

**Comment by alexcrichton** [comment]
Indeed! We should update the documentation for web-sys to reflect this as well!
