### ISSUE TITLE
Cannot properly create setters when js_name is provided

### ISSUE THREAD

**Issue by brisad** [rustwasm/wasm-bindgen#584]
While attempting to create the binding for `regexp.lastIndex` with the following code,
```rust
/// The lastIndex is a read/write integer property of regular
/// expression instances that specifies the index at which to
/// start the next match.
///
/// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/lastIndex
#[wasm_bindgen(method, getter, structural, js_name = lastIndex)]
pub fn last_index(this: &RegExp) -> u32;
#[wasm_bindgen(method, setter, structural, js_name = lastIndex)]
pub fn set_last_index(this: &RegExp, index: u32);
```
I got the following error when compiling:
> 
> error: custom attribute panicked
>     --> crates/js-sys/src/lib.rs:2054:1
>      |
> 2054 | #[wasm_bindgen]
>      | ^^^^^^^^^^^^^^^
>      |
>      = help: message: setters must start with `set_`
> 

Since the method is called `set_last_index` this error appears to be invalid. And according to https://github.com/rustwasm/wasm-bindgen/pull/580#discussion_r205978745 `js_name = lastIndex` is correct.

**Comment by alexcrichton** [comment]
Aha! Turns out there's some sneaky syntax here, instead of `js_name` the `setter = lastIndex` syntax is supported. That being said, both should probably be supported! (or we should deprecate one of them)
