### ISSUE TITLE
Support extern bindings (imports) from within rust modules.

### ISSUE THREAD

**Issue by derekdreery** [rustwasm/wasm-bindgen#588]
To support functionality like the following:

```rust
#![feature(proc_macro_mod)]

#[wasm_bindgen]
mod console {
    #[wasm_bindgen]
    extern "C" {
        #[wasm_bindgen(js_namespace = console)]
        pub fn log(s: &str);
    }
}
```

This is an attempt to split the issues #253, #254, #450, possibly others, into 2 parts - the codegen part and the AST transform part.

It would also be useful functionality, to allow rust developers to put their bindings into something other than the global namespace.

**Comment by alexcrichton** [comment]
Note that this is supported today so long as `console` is `pub` ([which is a bug](https://github.com/rustwasm/wasm-bindgen/issues/201)). Are you thinking though that the macro itself should generate a module?

**Comment by derekdreery** [comment]
Yeah I was thinking of generating something like

```rust
mod console {
    pub fn log(s: &str) {
        __our_mangled_external_fn(s)
    }
}

extern "C" {
    #[doc(hidden)]
    pub fn __our_mangled_external_fn(s: TheABIType) {
        // ...
    }
}
```

or something else, I've not really figured out how wasm-bindgen joins the imports yet.

**Comment by derekdreery** [comment]
I've looked again, and I think this is probably a duplicate of that other issue.
