### ISSUE TITLE
Improve #[wasm_bindgen] errors with `compile_error!`

### ISSUE THREAD

**Issue by alexcrichton** [rustwasm/wasm-bindgen#601]
Right now the procedural macro simply panics if anything goes wrong, but this is pretty bad! The error messages coming out look pretty opaque at times and are often quite subpar, especially in that they're pointing to the wrong items. 

I've just realized, however, that the procedural macro can generate `compile_error!` invocations which gives us the ability to generate custom compiler errors as well as custom error spans. An example of this is:

https://gist.github.com/alexcrichton/35f9b54585b39d16a887cffd4eabdb2d

We should refactor the macro crate to use `Result` for error handling and use a structured error type which has a string and start/end spans, and that way we can generate nicely spanned error messages, yay!

**Comment by mkane0814** [comment]
Yes please! These errors have been really frustrating to work around. Does anyone know what causes them?

**Comment by alexcrichton** [comment]
I think this is effectively done now, yay!
