### ISSUE TITLE
Publish an initial release of wasm-bindgen-futures

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-bindgen#614]
As discussed in today's WG meeting, we are aiming for publishing an initial release of the `wasm-bindgen-futures` crate for the Rust 2018 Release Candidate milestone. That's 6 weeks from now: 2018-09-13.

What needs to be done before we ship an initial release of `wasm-bindgen-futures`?

* [x] Once over of public API. I think this is probably quite close to being ready to ship as-is, and can have a fairly small public API and everything else be internal implementation details.
* [x] Documentation for using Promises and Futures together in the wasm-bindgen guide
* [x] Larger example program that uses Promises and Futures together
* [x] A release of `js-sys` with the `Promise` bindings that this uses
* [x] Some sanity tests: #680

Anything else?

+cc @alexcrichton

**Comment by alexcrichton** [comment]
The [current API](https://rustwasm.github.io/wasm-bindgen/api/wasm_bindgen_futures/) is *extremely* conservative, providing basically only these things:

```rust
struct JsPromise { ... }
impl From<Promise> for JsPromise { ... }
impl Future<Item = JsValue, Error = JsValue> for JsPromise { ... }

fn future_to_promise(impl Future<Item = JsValue, Error = JsValue>) -> Promise;
```

in that sense I'd be comfortable with the public API as-is, but I think a prerequisite for publishing should be some more documentation and/or at least one usage example in a larger context. Right now the documentation for how to use is very thin, and could be bolstered quite a bit!

**Comment by Cyres** [comment]
Is this also possible in the other direction? I.e. calling a function from Rust and return the promise as future?

```rust
#[wasm_bindgen]
pub fn fetch(path: &str) -> js_sys::Promise;

...

let mut future: JsFuture = fetch("http://example.org/").into();
future.poll();

```
always results in
> panicked at 'no Task is currently running', libcore/option.rs:1000:5.

wasm-version: 0.2.15 (157ba0066)

**Comment by alexcrichton** [comment]
@Cyres ah that has to do with futures in general, not so much the support here. You can't `poll` a future outside the context of a "task", and it's true yeah that `wait` won't work on wasm because it can't block. Once you have a future you'll need to keep using futures and plumb them throughout.

**Comment by Cyres** [comment]
So long story short I cannot get the result of my fetch in Rust directly? Feels, that I need a buffer thing at JS side then, which can then be pulled from Rust.

**Comment by alexcrichton** [comment]
Sort of, yeah. The only way to execute a Rust future is to convert it to a JS promise. You don't necessarily have to interface with JS per se, but you will have to take a future and then convert it to a `Promise` at some point to execute it.

**Comment by Cyres** [comment]
Thanks for the response. Is there a reason by the way, why `feature 0.1.20` is used instead of 0.2 or feature-preview?

**Comment by fitzgen** [comment]
> why feature 0.1.20 is used instead of 0.2 or feature-preview?

Because it is the stable version of `futures` right now. Once 0.3, the next stable version, is released, then we can update to that version.

**Comment by fitzgen** [comment]
Also added some sanity tests in #680 -- I think we can publish this crate after that lands and we do a new release of js-sys to get the promise bindings!

**Comment by alexcrichton** [comment]
Sounds good to me!

**Comment by fitzgen** [comment]
This is complete! :tada: :taco: :tada:

**Comment by withoutboats** [comment]
> Because it is the stable version of futures right now. Once 0.3, the next stable version, is released, then we can update to that version.

Do you anticipate any issues arising from the change to the `futures` API? I'm thinking especially of the explicit `Context` argument, but maybe there are other problems. This integration is very valuable!

**Comment by fitzgen** [comment]
I expect that @alexcrichton is the most appropriate person to answer this question. I'm not super familiar with the incoming changes to `futures` other than that it won't always be a `Result` anymore, which I love :)

**Comment by alexcrichton** [comment]
@withoutboats an excllent point! I doubt though that the 0.3 release will cause many problems for us. The [code](https://github.com/rustwasm/wasm-bindgen/blob/master/crates/futures/src/lib.rs) is quite small and should be very easily portable to 0.3!
