### ISSUE TITLE
Support merging of wasm files via binaryen

### ISSUE THREAD

**Issue by mandeepbrar** [rustwasm/wasm-bindgen#618]
Tried merging two wasm files containing wasm-bindgen with binaryen wasm-merge. It worked, but when i run the wasm bindgen cli on the merged file, the resulting javascript is not created properly. The resulting javascript only contains functions from one file.

**Comment by alexcrichton** [comment]
Thanks for the report! I believe in theory this should work as long as things don't conflict, but this also depends on what the merge process does with custom sections. Do you have an example of the wasm-merge to poke around with?

**Comment by alexcrichton** [comment]
Also in general Rust code can't be merged with another wasm module because it's not necessarily relocatable (static data is all at fixed addresses). To that end fully supporting this may require toolchain support.

**Comment by alexcrichton** [comment]
@mandeepbrar unfortunately I think these modules just fundamentally can't be merged together. They both have static data in the same location, and `wasm-merge` doesn't know how to disambiguate that.

**Comment by alexcrichton** [comment]
I'm going to close this because I don't think it's a wasm-bindgen specific issue, but broader discussion may be good as well on internal forums!
