### ISSUE TITLE
Meet "unsupported optional argument Ref" when set attribute

### ISSUE THREAD

**Issue by Yuyz0112** [rustwasm/wasm-bindgen#619]
I'm trying to add some test for the `HtmlTableElement` in `web-sys` crate.
In the interface there is attribute called caption.
```webidl
[CEReactions, SetterThrows]
attribute HTMLTableCaptionElement? caption;
```
and if use a setter to set this attribute
```rust
let table = new_table(); // get a HtmlTableElement;
let caption = new_caption(); // get a HtmlTableCaptionElement
table.set_caption(Some(&new_caption()));
```
I meet the error
```
error: executing `wasm-bindgen` over the wasm file
        caused by: failed to generate bindings for JS import `set_caption`
        caused by: unsupported optional argument Ref(Anyref)
```

Does this means that we cannot set an optional attribute which is ok in JS?

**Comment by alexcrichton** [comment]
Oops this looks like a bug! I think it should be fixed in https://github.com/rustwasm/wasm-bindgen/pull/626
