### ISSUE TITLE
use weedle instead of webidl-rs

### ISSUE THREAD

**Issue by ohanar** [rustwasm/wasm-bindgen#620]
(See #506 for prior experimental implementation of this issue.)

There are currently a number of issues with weedle that need to be addressed upstream before we can really use it.
- Currently weedle never errors. This can be easily fixed as it is a small oversight, but the best context you could give at the moment without more thorough changes is pointing to the definition block that failed.
- Weedle parses the subset of the WebIDL grammar that is used by the WebIDL spec. The main place that these differ is for extended attributes, where the grammar is far more general that what the spec needs. mozilla-central's webidl files use this more general grammar with attribute="some string literal" all over the place. From a cursory glace through webidl-rs' source, it doesn't seem like it supports the full general grammar of extended attributes either (although some commented out code looks like there was the intention at some point), however, it seems to parse the main offender previously mentioned just fine.
- web-sys gets truncated due to a combination of the two previous bullet points.

Note that the author of weedle is not planning on working on it for the near future, and has offered to transfer ownership should we decide to pursue this issue.

**Comment by alexcrichton** [comment]
I've attempted to do this in https://github.com/rustwasm/wasm-bindgen/pull/639
