### ISSUE TITLE
web-sys: Add Chrome headless testing to CI

### ISSUE THREAD

**Issue by alexcrichton** [rustwasm/wasm-bindgen#622]
We'll want to edit the travis config to download `chromedriver` and also probably Chrome itself. We should the configure js-sys and web-sys tests to both run with `geckodriver` and `chromedriver` on CI, ensuring that tests pass in both Firefox and Chrome.

**Comment by andrewdavidmackenzie** [comment]
When trying to run chromedriver tests in travis I get this error message:

```
driver stdout:
    Starting ChromeDriver 2.46.628411 (3324f4c8be9ff2f70a05a30ebc72ffb013e1a71e) on port 59072
    Only local connections are allowed.
    Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
```

if via this work you know how to avoid that it would be very useful. Thanks.
