### ISSUE TITLE
WebIDL: Remove all typedefs in early passes

### ISSUE THREAD

**Issue by alexcrichton** [rustwasm/wasm-bindgen#623]
[According to](https://github.com/rustwasm/wasm-bindgen/issues/613#issuecomment-410136314) @ohanar, even the WebIDl spec says we shouldn't expose them!

**Comment by ohanar** [comment]
To quote the first paragraph of [the WebIDL spec](https://heycam.github.io/webidl/#idl-typedefs):
> A typedef is a definition (matching Typedef) used to declare a new name for a type. This new name is not exposed by language bindings; it is purely used as a shorthand for referencing the type in the IDL.
