### ISSUE TITLE
WebIDL: Enable bindings that have unusual enum names

### ISSUE THREAD

**Issue by alexcrichton** [rustwasm/wasm-bindgen#625]
Need to make sure this folder is empty! https://github.com/rustwasm/wasm-bindgen/tree/master/crates/web-sys/webidls/unavailable_enum_ident

**Comment by afdw** [comment]
Will just renaming to `"none"` whenever it is named `""` work?

**Comment by alexcrichton** [comment]
That sounds reasonable to me! It looks like these are enum values with the empty string, which I think naturally translates to `Foo::None` in Rust. I think though that we'll specifically want to handle the empty string case where enums are processed rather than the general location where identifiers are manufactured.
