### ISSUE TITLE
Propagate bindings to depending crate

### ISSUE THREAD

**Issue by jgregory553142** [rustwasm/wasm-bindgen#649]
Hello,

For my project I use two crates A and B. Crate B contains functions that are marked with `#[wasm_bindgen]`. Crate A is built into a wasm-library using wasm-bindgen, and it depends on crate B.

When I build crate B on its own, the JavaScript bindings are correctly generated. But when I build crate A, the annotations for the functions in crate B seem to be ignored.

What do I need to do to build crate A, but still get the JavaScript bindings for the functions in crate B for my library?

**Comment by alexcrichton** [comment]
Thanks for the report! I think this is an unfortunate limitation of how LLD works (the linker for wasm code).

Currently if you're linking to a library LLD doesn't actually load the library *unless* you use something from it. If you're exporting functionality from B there's likely nothing else pulling it in to link to it, so LLD doesn't end up pulling in the functionality.

You can see a longer explanation [here](https://github.com/rustwasm/wasm-bindgen/blob/e9f9ede1fa23a59a4514f8222344b98e0c1f386c/src/lib.rs#L742-L779) along with the workaround this crate uses. Perhaps something like that could work for you?

**Comment by jgregory553142** [comment]
Ah thank you very much for the hint. That might work for me, but for now I have decided to just include the exported functions also in the depending crate. Seemed to be the easiest and least hacky solution, and also makes the structure of my project actually nicer.
