### ISSUE TITLE
Add `extends = ...` attributes to `js-sys` types

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-bindgen#670]
We should add all the inheritance relations for global JS types to `js-sys`.

We can use this snippet of JS to log the prototype chain for something, eg `Uint8Array`:

```js
function logPrototypeChain(cls) {
  let obj = cls.prototype;
  do {
    console.log(obj.constructor.name);
    obj = obj.__proto__;
  } while (obj != null);
}

logPrototypeChain(Uint8Array);
```

Pasting that snippet in a browser's devtools console logs:

```text
Uint8Array
TypedArray
Object
```

So we would add `#[wasm_bindgen(extends = Object, extends = TypedArray)` to `Uint8Array`'s import definition and a corresponding test to the appropriate file in `crates/js-sys/tests/..` like:

```rust
use wasm_bindgen::JsCast;

#[wasm_bindgen_test]
fn test_blah_inheritance() {
    let blah = js_sys::Blah::new(); // its constructor might require different args

    // Assert JS actually agrees with our set of base classes.
    assert!(blah.is_instance_of::<Blah>());
    assert!(blah.is_instance_of::<BlahBase>());
    // etc for each base class...
    assert!(blah.is_instance_of::<js_sys::Object>());

    // Ensure that we generated the appropriate `AsRef` upcasting implementations
    // for each base class.
    let _: &BlahBase = blah.as_ref();
    // etc for each base class...
    let _: &js_sys::Object = blah.as_ref();
}
```

Here is an example PR for the `RegExp` type: https://github.com/rustwasm/wasm-bindgen/pull/671

See also `js-sys` contributing documentation: https://rustwasm.github.io/wasm-bindgen/js-sys.html

-------------------------------------------------------

Here are all the JS global import types for which we need to add this information:

* [x] `Array`
* [x] `ArrayBuffer`
* [x] `Boolean`
* [x] `DataView`
* [x] `Date`
* [x] `Error`
* [x] `EvalError`
* [x] `Float32Array`
* [x] `Float64Array`
* [x] `Function`
* [x] `Generator`
* [x] `Int16Array`
* [x] `Int32Array`
* [x] `Int8Array`
* [x] `Intl.Collator`
* [x] `Intl.DateTimeFormat`
* [x] `Intl.NumberFormat`
* [x] `Intl.PluralRules`
* [x] `JSON`
* [x] `Map`
* [x] `Math`
* [x] `Number`
* [x] `Promise`
* [x] `RangeError`
* [x] `ReferenceError`
* [x] `Reflect`
* [x] `RegExp`
* [x] `Set`
* [x] `String`
* [x] `Symbol`
* [x] `SyntaxError`
* [x] `TypeError`
* [x] `TypedArray`
* [x] `URIError`
* [x] `Uint16Array`
* [x] `Uint32Array`
* [x] `Uint8Array`
* [x] `Uint8ClampedArray`
* [x] `WeakMap`
* [x] `WeakSet`
* [x] `WebAssembly.Module`
* [x] `WebAssembly.Instance`
* [x] `WebAssembly.Table`
* [x] `WebAssembly.Memory`

**Comment by kraai** [comment]
It seems like the `extends` attribute isn't necessary for `Promise`.  The following test passes without any changes to `lib.rs`:

```rust
use wasm_bindgen_test::*;                                                       
use wasm_bindgen::JsCast;                                                       
use js_sys::*;                                                                  
                                                                                
#[wasm_bindgen_test]                                                            
fn test_promise_inheritance() {                                                 
    let promise = Promise::new(&mut |_, _| ());                                 
    assert!(promise.is_instance_of::<Promise>());                               
    assert!(promise.is_instance_of::<Object>());                                 
}                                                                               
```

Should it be marked as complete, should the test be added, or should the `extends` attribute and test be added anyway?

**Comment by fitzgen** [comment]
Good catch! The example test I provided only tests the dynamic JS behavior with `instanceof`, which doesn't exercise the code emitted by `extends = ...` at all :-p Instead we should do something like this:

```rust
#[wasm_bindgen_test]
fn test_promise_inheritance() {
    let promise = Promise::new(&mut |_, _| ());

    // Assert that JS matches our inheritance hierarchy.
    assert!(promise.is_instance_of::<Promise>());
    assert!(promise.is_instance_of::<Object>());

    // Ensure that we emitted the appropriate `AsRef` implementations for each base class.
    let _: &Object = promise.as_ref();
}
```

That bottom bit is the new bits, and that should fail to compile without the `extends = ...` attributes!
