### ISSUE TITLE
Support exporting Rust functions as variadic JS functions

### ISSUE THREAD

**Issue by derekdreery** [rustwasm/wasm-bindgen#694]
Support the following example

```rust
#[wasm_bindgen(apply_ending_slice_bikeshedded)]
pub fn add(first: u32, second: u32, rest: &[u32]) -> u32 {
    rest.iter().sum() + first + second
}
```

callable from javascript as

```js
import { add } from './wasm';

console.log(add(1, 2, 3, 4, 5)); // prints 15
```

You could implement the transformation in javascript as

```js
function add(first, second, ..rest) {
    return add_from_rust(first, second, rest);
}
```

This is ~~a prerequisite for implementing #503~~ the reverse of #503.

**Comment by alexcrichton** [comment]
Seems plausible to me! I think though that this is the opposite of #503, right? (this is about defining something in Rust whereas that's about importing something defined in JS)

**Comment by derekdreery** [comment]
Yeah I don't know why I said prerequisite :)

**Comment by joaofreires** [comment]
@alexcrichton maybe we can close this issue as #2954 has been merged.
