### ISSUE TITLE
Using JS Module inside Webpack Project

### ISSUE THREAD

**Issue by rylev** [rustwasm/wasm-bindgen#700]
This is probably a webpack issue, but I wanted to confirm here.

Using a wasm-bindgen I built a library that I want to include as a dependency in another webpack based project. I added a package.json file to the output from wasm-bindgen and set the generated js file as the main file. Finally, I set the directory where my generated files and this package.json are located as the location in my webpack project's package.json. 

Inside of my webpack project I import this library using the async `import()` since wasm file's can't be imported synchronously. However, I still get the error: 

```
WebAssembly module is included in initial chunk.
This is not allowed, because WebAssembly download and compilation must happen asynchronous.
Add an async splitpoint (i. e. import()) somewhere between your entrypoint and the WebAssembly module:
```  

I'm not sure why I'm getting this issue as I am using an async `import()`  to import my wasm-bindgen generated lib. Any ideas? Does this seem like a webpack issue to you?

**Comment by xtuc** [comment]
Yes that's a current Webpack limitation. It means that you need to `import("../wasm-bindgen-thing")` instead of using the `import x from "..."` syntax.

**Comment by rylev** [comment]
@xtuc I think I wasn't clear. I am using the `import("../wasm-bindgen-thing")` syntax and never importing the wasm-bindgen-thing using the `import x from "wasm-bindgen-thing"` syntax.

**Comment by rylev** [comment]
If I reduce my webpack project down to just `import('../../../wasm-bindgen-thing').then(module => console.log(module))` where the `wasm-bindgen-thing` is just the straight output from wasm-bindgen, I get the same error.

**Comment by rylev** [comment]
Main project - src/index.ts:
```js
import('../../dmg-01-js/pkg/dmg_01_js').then(dmg => console.log(dmg))
```
dmg_01_js: 

```js
import * as wasm from './dmg_01_js_bg';
function foo() {
    wasm.add(0,0)
}
```

webpack config:

```js
module.exports = {
    entry: "./src/index.tsx",
    output: {
        filename: "cpu.js",
      path: __dirname + "/dist",
      // Export this as a library that can be accessed from plain JS
    },

    // Enable sourcemaps for debugging webpack's output.
    devtool: "source-map",

    resolve: {
        // Add '.ts' and '.tsx' as resolvable extensions.
        extensions: [".ts", ".tsx", ".js", ".json", ".wasm"]
    },
    mode: 'development',

    module: {
        rules: [
            // All files with a '.ts' or '.tsx' extension will be handled by 'awesome-typescript-loader'.
            { test: /\.tsx?$/, loader: "awesome-typescript-loader" },

            // All output '.js' files will have any sourcemaps re-processed by 'source-map-loader'.
            { enforce: "pre", test: /\.js$/, loader: "source-map-loader" }
        ]
    },

};
```

**Comment by xtuc** [comment]
Since the index uses a dynamic import, your bundle is splited and everything can be synchronous then. The example you posted seems fine to me, I'm just wondering if TypeScript would transform the `import()` to something else? could you please try with JS?

**Comment by rylev** [comment]
@xtuc you might be right. I switched to js and it worked. I can try to find out what the typescript loader is doing

**Comment by xtuc** [comment]
Yeah that would be very helpful for us

**Comment by alexcrichton** [comment]
This issue has been stale for a bit and I think it's largely about webpack issues so I'm going to close it here on this repo, but if there's wasm-bindgen issues please let us know!

**Comment by patientplatypus** [comment]
I am also getting this error: 

```
 ERROR  Failed to compile with 1 errors                                                                                                                                                                                           3:07:46 PM

 error  in ./zenMiner/pkg/zenMiner_bg.wasm

WebAssembly module is included in initial chunk.
This is not allowed, because WebAssembly download and compilation must happen asynchronous.
Add an async splitpoint (i. e. import()) somewhere between your entrypoint and the WebAssembly module:
* multi (webpack)-dev-server/client?http://192.168.0.2:8081/sockjs-node (webpack)/hot/dev-server.js ./src/main.js --> ./src/main.js --> ./src/routes/index.js --> ./src/components/screens/Buy.vue --> ./src/components/screens/Buy.vue?vue&type=script&lang=js& --> ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/components/screens/Buy.vue?vue&type=script&lang=js& --> ./zenMiner/pkg/zenMiner.js --> ./zenMiner/pkg/zenMiner_bg.wasm
* ... --> ./zenMiner/pkg/zenMiner.js --> ./zenMiner/pkg/zenMiner_bg.wasm --> ./zenMiner/pkg/zenMiner.js --> ./zenMiner/pkg/zenMiner_bg.wasm
* ... --> ./src/main.js --> ./src/App.vue --> ./src/App.vue?vue&type=script&lang=js& --> ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js& --> ./src/components/screens/Buy.vue --> ./src/components/screens/Buy.vue?vue&type=script&lang=js& --> ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/components/screens/Buy.vue?vue&type=script&lang=js& --> ./zenMiner/pkg/zenMiner.js --> ./zenMiner/pkg/zenMiner_bg.wasm
```

If this is a 'webpack issue' that means that people can't use Rust wasm in popular webpack based libraries such as React and Vue.js. This would seem to be a big deal and rather than merit closing the issue, I think it probably should be addressed. Thank you.

**Comment by rylev** [comment]
For the record, the way I currently work around this is by having one JavaScript file that exposes a function that simply imports the wasm module. This file is built using a babel loader and is not touched by the TypeScript compiler. I then can include that JavaScript file in my TypeScript. 

As I've said before, this seems to be an issue with the TypeScript compiler - I'm not sure exactly what it's doing, but it seems to be messing up how imports work.

@patientplatypus it doesn't seem like you're using TypeScript but having the same issue. Are you using the `import(WASM_FILE).then(module => /* use module here */)` syntax?

**Comment by emk** [comment]
I've posted the pieces for a pure-TypeScript soluton [on issue #43](https://github.com/rustwasm/rust-webpack-template/issues/43#issuecomment-426597176) using `"module": "esNext"` and Webpack.

**Comment by emk** [comment]
@xtuc It might be a good idea to turn this into a fully-working example project, hook it up to CI as part of #922, and then add instructions to the README with a link to the actual working project. Otherwise, I fear that's it's too easy to leave out steps or to regress. Webpack + TypeScript + WebAssembly can be pretty fragile.

I'd be happy to take a shot at this sometime this coming weekend.

**Comment by xtuc** [comment]
Yes, that's a good point. Should we commit a tsc configuration in the template? Could you please send a PR :)

**Comment by emk** [comment]
@xtuc It would be possible to update the template to use TypeScript, but it would involve the following changes:

1. Convert [the template's `js/index.js`](https://github.com/rustwasm/rust-webpack-template/blob/master/js/index.js) to TypeScript.
2. Update [`webpack.config.js`](https://github.com/rustwasm/rust-webpack-template/blob/master/webpack.config.js) to include `ts-loader`.
3. Add a `tsconfig.json` file.
4. Make sure that TypeScript can find the `$CRATE.d.ts` file, even when using `wasm-pack` and/or VS Code, so that everything hooks up nicely.

Would we really want to do (1)? Or would it be better to have a separate template for TypeScript projects?

There's already a `rust-parcel-template` project. Maybe we might want to add a `rust-webpack-typescript-template` project? The integration between `wasm-bindgen` and TypeScript is _really_ slick once it's set up, and likely to be of interest to Rust programmers.

**Comment by sandromario** [comment]
Hi, I'm running into this problem too, but I'm a beginner and don't know where to start, sorry. Could someone help me please?

My workflow is very simple, as follows:
1. I ran through the official "book" tutorial (https://rustwasm.github.io/book/).
2. I've successfully run `wasm-pack` and `npm run build`, so a node module has been created.
3. I've written my own Rust code, and I've recompiled using wasm-pack.
4. I now want to use this in a different Webpack-based JS project.

What do I need to do? I don't want to publish to an npm registry or anything. The "npm link" method, which worked in the "book" example, gives me the error described above:

```
ERROR in ../my-rust-project/pkg/my_rust_project_bg.wasm
WebAssembly module is included in initial chunk.
This is not allowed, because WebAssembly download and compilation must happen asynchronous.
Add an async splitpoint (i. e. import()) somewhere between your entrypoint and the WebAssembly module:
* ./src/test.js --> ../my-rust-project/pkg/my_rust_project.js --> ../my-rust-project/pkg/my_rust_project_bg.wasm
* ... --> ../my-rust-project/pkg/my_rust_project.js --> ../my-rust-project/pkg/my_rust_project_bg.wasm --> ../my-rust-project/pkg/my_rust_project.js --> ../my-rust-project/pkg/my_rust_project_bg.wasm
```

**Comment by alexcrichton** [comment]
@sandromario I think you're running into https://github.com/webpack/webpack/issues/6615 where wasm instantiation is required to be asynchronous, which makes it a bit more difficult to expose and use at the bundler level, leading to this current limitation

**Comment by Kingsearch** [comment]
@rylev 
require.ensure([], function () {
       const rust = require("../pkg")
       rust
           .run()
           .then(c => {
               console.log(c)
           })
   })

**Comment by sc-laurence** [comment]
I know this is an old issue but cant seem to see what the solution is?
I have posted a issue in a different repo
https://github.com/rustwasm/create-wasm-app/issues/146 but think this might be more closely related? can I get a hand with this please.

**Comment by murtyjones** [comment]
Just wanted to share a similar solution building off of @michaeljones's excellent answer. I wanted to ensure that my wasm module would be typed, which the below solution does:

**index.ts**
```ts
import { import_wasm } from './import_wasm';

(async () => {
  const module = await import_wasm();
  module.greet();
})();
```

**import_wasm.js**
```js
export function import_wasm() {
    return import("../pkg/index.js");
}
```

**import_wasm.d.ts**
```ts
export const import_wasm: () => Promise<typeof import('../pkg/index')>;
```

**Comment by noxue** [comment]
if you are deploy to nginx , just set the mime-type,like this:
```
http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  types {
    application/wasm wasm;
    application/octet-stream clr;
    application/octet-stream pdb;
    application/font-woff woff;
    application/font-woff woff2;
  }
```

https://platform.uno/docs/articles/how-to-host-a-webassembly-app.html
