### ISSUE TITLE
WebIDL: Support the BufferSource type

### ISSUE THREAD

**Issue by alexcrichton** [rustwasm/wasm-bindgen#701]
We've currently got a number of fields/methods that aren't bound because the `BufferSource` type isn't recognized. [Defined by the spec](https://www.w3.org/TR/WebIDL-1/#h-common-buffersource) this type is basically `TypedArray or DataView or ArrayBuffer`. We unfortunately don't have a great way to bind this type tight now!

How should we support this type? Should we just take `&JsValue` and call it a day?

**Comment by fitzgen** [comment]
For inputs, we can overload these similar to other unions.

For outputs, we can probably use `JsValue` and call it a dat.

+cc @afdw

**Comment by alexcrichton** [comment]
Added in https://github.com/rustwasm/wasm-bindgen/pull/745!
