### ISSUE TITLE
Prototype WeakRef support with a SpiderMonkey shell polyfill

### ISSUE THREAD

**Issue by alexcrichton** [rustwasm/wasm-bindgen#704]
https://gist.github.com/tschneidereit/51dd7d5b51e16e21f8281b111fe638d1 is a polyfill for the upcoming `WeakRef` proposal, and we're definitely going to want to make use of it to avoid the need to manually call `free` on Rust structs exported to JS.

We should add an option to wasm-bindgen (probably an env var for now) to tailor output of wasm-bindgen for the SpiderMonkey JS shell and use these weakref bindings!

**Comment by alexcrichton** [comment]
cc @tschneidereit

**Comment by Pauan** [comment]
I might be wrong, but my understanding is that the WeakRef proposal does not guarantee that the destructors will run in a timely manner, so there could be an arbitrary amount of time before the object is garbage collected, so it would still be useful to manually call `free` to guarantee fast and deterministic cleanup.

**Comment by tschneidereit** [comment]
> I might be wrong, but my understanding is that the WeakRef proposal does not guarantee that the destructors will run in a timely manner, so there could be an arbitrary amount of time before the object is garbage collected, so it would still be useful to manually call free to guarantee fast and deterministic cleanup.

I agree that it's good to also provide a way to manually free memory. The idea isn't to use finalizers as some kind of RAII mechanism; if you know when to call `free`, then you should definitely do that.

However, there are a lot of situations where you simply cannot know when you should free a resource. E.g. if you have data associated with a DOM node whose lifetime you don't control—when do you free that data? Without finalizers, you only have the two options of either leaking memory, or somehow restructuring things such that you *do* control the node's lifetime. In particular if you want to use WebAssembly for only part of your application and keep the rest in JS, the latter often won't be possible.
