### ISSUE TITLE
#[wasm_bindgen] on `impl {}` produces duplicate function in wasm-bindgen-test

### ISSUE THREAD

**Issue by limira** [rustwasm/wasm-bindgen#714]
Hi, 
I am trying to implement some tests for my crate using `wasm-bindgen-test`. If I have `#[wasm_bindgen]` on an `impl ... {...}`, the test failed because of duplicate definition of:
```
// in file: `/wbg-tmp/wasm-bindgen-test.js`
export function __wbg_static_accessor_document_document
```
[Here is the code that cause the problem](https://gitlab.com/limira-rs/simi/blob/wasm-bindgen-test/simi/tests/wasm/counter.rs). (Note that it is on branch `wasm-bindgen-test`, not on master.) If I uncomment line 53, the problem will occur.

**Comment by csharad** [comment]
I also encountered the same problem when declaring bindings for `static document: HtmlDocument`. 
When I looked into the code of `wasm-bindgen-test`, it is also generating bindings for the same for its internal use, which is causing duplication.
