### ISSUE TITLE
Support namespace attributes in the webidl frontend

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-bindgen#746]
We don't yet support attributes within namespaces:

```webidl
namespace Whatever {
    readonly attribute bool blah;
}
```

Note that attributes within namespaces are always `readonly`.

Would need to add support here: https://github.com/rustwasm/wasm-bindgen/blob/master/crates/webidl/src/lib.rs#L926

**Comment by fitzgen** [comment]
This might be a blocker for https://github.com/rustwasm/wasm-bindgen/issues/613 -- I need to check how often this happens in practice and how important the instances are.

**Comment by fitzgen** [comment]
> This might be a blocker for #613 -- I need to check how often this happens in practice and how important the instances are.

There aren't any in our enabled webidls. Don't think this is a blocker!

**Comment by alexcrichton** [comment]
Since this doesn't show up in any of our webidl and it doesn't look like namespaces are really used much any more I'm gonna go ahead and close this
