### ISSUE TITLE
Wasm decoding failed: table index X out of bounds

### ISSUE THREAD

**Issue by KenanSulayman** [rustwasm/wasm-bindgen#753]
Hello,

I'm having an issue when trying to call a declared C extern (setInterval) with a closure and building the library in release (-C  lto) mode.

Cargo.toml:
```
[dependencies]
wasm-bindgen = "0.2.17"
wee_alloc = "0.4.2"

[lib]
crate-type = ["cdylib"]

[profile]

[profile.release]
lto = true
opt-level = "s"
panic = "abort"
```

lib.rs:
```
#![no_std]

#![feature(
    alloc_error_handler,
    alloc,
    core_intrinsics,
    custom_attribute,
    lang_items,
    panic_implementation,
)]

extern crate alloc;
extern crate wee_alloc;

#[global_allocator]
static ALLOC: wee_alloc::WeeAlloc = wee_alloc::WeeAlloc::INIT;

extern crate js_sys;
extern crate wasm_bindgen;
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen]
    pub fn setInterval(cb: &Closure<FnMut()>, millis: i32) -> i32;
}

#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(js_namespace = console)]
    fn log(s: &str);
}

#[wasm_bindgen]
pub struct Julia {
    width: i32,
    height: i32
}

#[wasm_bindgen]
impl Julia {
    #[wasm_bindgen(constructor)]
    pub fn new (width: i32, height: i32) -> Julia {
        Julia {
            width,
            height
        }
    }

    pub fn print(&self) {
        fn handler () {
            log("test");
        }

        setInterval(&Closure::new(handler), 1_000);
    }
}
```

makefile:
```
all:
	cargo build --target=wasm32-unknown-unknown --release \
	&& wasm-bindgen target/wasm32-unknown-unknown/release/lib.wasm --out-dir out/ \
	&& wasm-opt -O3 out/lib_bg.wasm -o out/main.wasm
```

The build doesn't produce a corrupted wasm binary when the handler definition and `setInterval` invocation from `print(self: &Julia)` is removed.

Any idea why this can happen?

I didn't find any information on “table index” and `wasm2wat` (all binaryen tools, actually) refused to produce a wat output: `0000241: error: invalid export table index: 99`.

**Comment by KenanSulayman** [comment]
Addendum: this happens independently of wasm-bindgen, which -- surprisingly -- does not complain about this error. I'm currently trying to somehow get a working AST of this binary.

Here is (1) the uncorrupted wasm binary without the invocation and (2) the corrupted one:

(1) [uncorrupted.wasm.zip](https://github.com/rustwasm/wasm-bindgen/files/2321614/uncorrupted.wasm.zip)
(2) [corrupted.wasm.zip](https://github.com/rustwasm/wasm-bindgen/files/2321613/corrupted.wasm.zip)

**Comment by KenanSulayman** [comment]
Addendum: I'm not exactly sure, but it seems to be related to the webpack build process (I expected the wasm file _not_ to change).

File produced through _cargo_ -> _wasm-bindgen_ -> _wasm-opt_: [ares_bg.wasm.zip](https://github.com/rustwasm/wasm-bindgen/files/2321616/ares_bg.wasm.zip)

File produced through webpack from the _wasm-opt_ artifact: [db7d1aa3f3ce8a64a0a3.wasm.zip](https://github.com/rustwasm/wasm-bindgen/files/2321617/db7d1aa3f3ce8a64a0a3.wasm.zip)

What kind of aggressive optimization is the webpack build doing? I stripped all of the stdlib, use -C lto and wasm-opt, and the webpack build still cuts off 5KB from the 8KB file? 😕

**Comment by KenanSulayman** [comment]
Here's a binary diff of what the webpack build optimization strips from the original wasm-opt artifact:

<img width="1115" alt="screenshot 2018-08-26 at 17 15 23" src="https://user-images.githubusercontent.com/280212/44629734-ac20a380-a953-11e8-93d6-658c584b4ede.png">

**Comment by KenanSulayman** [comment]
Removing the `preprocess` invocation and updating all webassembly-dependencies of webpack to ^1.7.5 did not fix this issue. I will dig deeper and report.

**Comment by KenanSulayman** [comment]
Revising my previous statement: cleaning the workspace and the re-running the build with your tree does indeed fix the issue.

**Comment by alexcrichton** [comment]
Ok great! Sounds like this was an upstream webpack issue? If that's the case I'm gonna close, but if it's still an issue here I can certainly reopen!
