### ISSUE TITLE
Is optional double supported?

### ISSUE THREAD

**Issue by ludwigpacifici** [rustwasm/wasm-bindgen#760]
While playing with the [`webaudio`](https://github.com/rustwasm/wasm-bindgen/blob/master/examples/webaudio/src/lib.rs#L98) example provided in this repository, I noticed I cannot provide an optional double to the `start` method, even though it is defined in the [webidl](https://github.com/rustwasm/wasm-bindgen/blob/master/crates/web-sys/webidls/enabled/AudioScheduledSourceNode.webidl#L16). As far as I can tell, some work was done to [support option numbers](https://github.com/rustwasm/wasm-bindgen/pull/630) but I don't manage to get the code to compile when I provide an argument:

Code where a dummy double is passed:

```rust
AsRef::<AudioScheduledSourceNode>::as_ref(&primary)
    .start(1.0) // Additional argument
    .unwrap();
```

Error:

```
error[E0061]: this function takes 0 parameters but 1 parameter was supplied
   --> examples/webaudio/src/lib.rs:104:14
    |
104 |             .start(1.0)
    |              ^^^^^ expected 0 parameters
```

I am missing something or is it not yet supported?

**Comment by alexcrichton** [comment]
They are indeed supported! Taking a look [at the generated APIs](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.AudioScheduledSourceNode.html) the methods that take the double have different names which should hopefully work here for you!
