### ISSUE TITLE
Cannot instantiate closure

### ISSUE THREAD

**Issue by Tarnadas** [rustwasm/wasm-bindgen#767]
Hi,

I just updated from wasm-bindgen 0.2.15 to 0.2.19, updated Rust nightly as well and now I get this error:

```
error[E0599]: no function or associated item named `new` found for type `wasm_bindgen::prelude::Closure<_>` in the current scope
  --> src/rust\vdom.rs:50:41
   |
50 |         let closure: Closure<FnMut()> = Closure::new();
   |                                         ^^^^^^^^^^^^ function or associated item not found in `wasm_bindgen::prelude::Closure<_>`
```

Has something changed with Closures?

**Comment by limira** [comment]
It is behind a feature now:
```toml
[dependencies]
wasm-bindgen = {version = "0.2.19", features = ["nightly"]}
```

**Comment by Tarnadas** [comment]
Oh ok, thanks that helped me. Could someone update the docs?

**Comment by fitzgen** [comment]
@Tarnadas I can mentor you, if you'd like to write up a PR!

**Comment by Tarnadas** [comment]
Sure why not. I could do that, but there's nothing other than writing, that you would have to enable the feature flag. I cannot give any description of what the feature flag includes. Could you give me a hint where to find information about it?

**Comment by fitzgen** [comment]
I think just mentioning that the `nightly` feature is required in the doc comment and in `guide/src/reference/passing-rust-closures-to-js.md` should do the trick.

**Comment by fitzgen** [comment]
doc comment -> the doc comment for the closure type, in `src/closure.rs`.
