### ISSUE TITLE
Serde serialization example from docs not working

### ISSUE THREAD

**Issue by Tarnadas** [rustwasm/wasm-bindgen#768]
Basically what the title says.

```rs
// rust
#[derive(Serialize)]
pub struct Example {
    pub field1: HashMap<u32, String>,
    pub field2: Vec<Vec<f32>>,
    pub field3: [f32; 4],
}

#[wasm_bindgen]
pub fn send_example_to_js() -> JsValue {
    let mut field1 = HashMap::new();
    field1.insert(0, String::from("ex"));
    let example = Example {
        field1,
        field2: vec![vec![1., 2.], vec![3., 4.]],
        field3: [1., 2., 3., 4.]
    };

    JsValue::from_serde(&example).unwrap()
}
```

```js
import {
  send_example_to_js
} from 'rustfile';

send_example_to_js();
```

throws this error:

```js
Uncaught (in promise) TypeError: Cannot read property 'obj' of undefined
    at getObject (lib.rs:23)
    at takeObject (lib.rs:45)
    at send_example_to_js (lib.rs:53)

// compiled src
function getObject(idx) {
    if ((idx & 1) === 1) {
        return stack[idx >> 1];
    } else {
        const val = slab[idx >> 1];
        
        return val.obj; // <----
        
    }
}

let slab_next = slab.length;

function dropRef(idx) {
    
    idx = idx >> 1;
    if (idx < 4) return;
    let obj = slab[idx];
    
    obj.cnt -= 1;
    if (obj.cnt > 0) return;
    
    // If we hit 0 then free up our space in the slab
    slab[idx] = slab_next;
    slab_next = idx;
}

function takeObject(idx) {
    const ret = getObject(idx);
    dropRef(idx);
    return ret;
}

export function send_example_to_js() {
    return takeObject(wasm.send_example_to_js());
}
```

I enabled the serialization feature via the TOML file:
```
[dependencies.wasm-bindgen]
version = "^0.2"
features = ["nightly", "serde-serialize"]
```

I'm also interested whether HashMap serialization will become a built-in of wasm-bindgen or what would be the easiest approach to pass a JavaScript Object, e.g. { [key: string]: string }, into Rust?

**Comment by fitzgen** [comment]
Looks like a bug in the slab, maybe related to enabling serde. Not good!

**Comment by Tarnadas** [comment]
@alexcrichton, I double checked and my version seems to be right.
I made a repository with a minimal reproduction example:
https://github.com/Tarnadas/wasm-bindgen-test

I use a few tools to facilitate my workflow like Webpack and a custom watch mode command, but I don't believe that this should be the problem.

**Comment by alexcrichton** [comment]
@Tarnadas hm there's quite a lot going on there with a lot of dependencies that could be introducing a bug, could you try to perhaps minimize this to see which dependency is causing the issue?

**Comment by Tarnadas** [comment]
It seems like rust-native-wasm-loader is causing this problem. Idk what exactly it is, but for now, I will just stick with the regular way to use wasm-bindgen and create a custom watch mode
