### ISSUE TITLE
web_sys: events/callbacks EventListener

### ISSUE THREAD

**Issue by aep** [rustwasm/wasm-bindgen#770]
Hi! 

I wanted to add some tests for websocket, but i'm not actually sure how.
WebSocket is generated, but the onmessage/etc eventlisteners are missing.
How do you actually set a callback then?

**Comment by fitzgen** [comment]
Thanks for filing an issue! Unfortunately, this not supported yet: https://github.com/rustwasm/wasm-bindgen/issues/257

Will close this issue in favor of that one.

**Comment by aep** [comment]
oops didnt see the other one, thanks!
