### ISSUE TITLE
Pass object with Uint8Array into Rust

### ISSUE THREAD

**Issue by ernieturner** [rustwasm/wasm-bindgen#779]
I'm trying to create a function in Rust which takes an object that looks like `{x: Uint8Array, y: Uint8Array}` but I can't seem to get it to work without throwing an exception. Here's the code on the Rust side that I have:

```
#[derive(Serialize, Deserialize)]
pub struct Key {
    x: Vec<u8>,
    y: Vec<u8>,
}

#[wasm_bindgen]
pub fn take_bytes(key: &JsValue) -> Vec<u8> {
    let key_obj: Key = key.into_serde().unwrap();
    key_obj.x.to_vec()
}
```

Obviously I'm not doing anything useful yet with the provided argument, I'm just trying to prove that I can marshal data in/out in the expected format. When I invoke the function above with just normal JS arrays

```
take_bytes({x: [1], y: [2]})
```

then I get out the expected result of a `Uint8Array[1]`. However, if I change the inputs to be `Uint8Array`

```
take_bytes({x: new Uint8Array([1]), y: new Uint8Array([2])})
``` 

Then I get a runtime panic.

```
wasm-00329b12-1813:2 Uncaught (in promise) RuntimeError: unreachable
    at __rust_start_panic (wasm-function[1813]:1)
    at rust_panic (wasm-function[1810]:30)
    at std::panicking::rust_panic_with_hook::h4cd0781f5610a7e9 (wasm-function[1805]:444)
    at std::panicking::continue_panic_fmt::h3cf345c25c890a40 (wasm-function[1803]:122)
    at rust_begin_unwind (wasm-function[1802]:3)
    at core::panicking::panic_fmt::h783ef2a31d4e6cf1 (wasm-function[1929]:70)
    at core::result::unwrap_failed::h13503bf0d64c7922 (wasm-function[185]:348)
    at _$LT$core..result..Result$LT$T$C$$u20$E$GT$$GT$::unwrap::h3d1cb4ba128b15d3 (wasm-function[184]:328)
    at wasm::api256::take_bytes::h8be68dd636fbe8cd (wasm-function[226]:92)
    at take_bytes (wasm-function[227]:153)
```

Is the above just not possible yet, or am I doing something wrong? I'll admit I'm just getting started compiling Rust to wasm so it's entirely possible that I'm missing something obvious. I've had no issues passing Uint8Arrays directly in/out using wasm-bindgen, it just seems that having them contained within an object isn't working. Maybe this is just an issue with Serde and not wasm-bindgen too. I really appreciate any help/suggestions. Thanks!

**Comment by alexcrichton** [comment]
Thanks for the report! Right now the serde-like methods use JSON serialization in the middle and it looks like a `Uint8Array` serializes as an object rather than an array, which I think is the issue here?

**Comment by ernieturner** [comment]
Thanks for the reply @alexcrichton! That would probably explain this problem. So your thought is that when you JSON.stringify typed arrays, they turn into objects and when I'm trying to pass that in to Rust the deserialization fails because I said thing should be a Vector (array) and instead it got an object?

**Comment by alexcrichton** [comment]
Indeed that appears to be the case!

This may indicate that long-term we don't want to use JSON serialization but perhaps a more chatty interface across the JS boundary, but that'd take some time to implement!

**Comment by ernieturner** [comment]
Interesting, after playing around with this a bit more, it looks like I can take Uint8Arrays in as HashMaps, which actually makes sense because the JSON stringified value for a typed array becomes something like `{0: 1, 1: 2}`.

```
#[derive(Serialize, Deserialize)]
pub struct Key {
    x: HashMap<u32, u32>,
    y: HashMap<u32, u32>,
}

#[wasm_bindgen]
pub fn take_bytes_obj(key: &JsValue) -> u32 {
    let key_obj: Key = key.into_serde().unwrap();
    *key_obj.x.get(&0).unwrap()
}
```

When I call that with `take_bytes_obj(new Uint8Array([1]))` it then successfully returns me `1` as a result like I'd expect.
