### ISSUE TITLE
Unable to use closures

### ISSUE THREAD

**Issue by cubetastic33** [rustwasm/wasm-bindgen#782]
I am trying to use addEventListener using wasm-bindgen, but it's not working. I tried this:
```
#[wasm_bindgen]
extern {
    /*...*/
    #[wasm_bindgen(method, js_name = addEventListener)]
    fn add_event_listener(this: &Element, ev_type: &str, listener: &Closure<FnMut()>);
}
/*...*/
#[wasm_bindgen]
pub fn initialize(_ {
    let a = Closure::new(foo.solve);
    document.query_selector("#solve").add_event_listener("click", &a);
}
```
But I got the following error:
```
error[E0615]: attempted to take value of method `solve` on type `foo`
  |
  = help: maybe a `()` to call it is missing?

error: aborting due to previous error

For more information about this error, try `rustc --explain E0615`.
error: Could not compile `foobar`.
```
But the example [here](https://github.com/rustwasm/wasm-bindgen/blob/master/examples/closures/src/lib.rs) uses a similar example. When I changed the `foo.solve` to `move || {foo.solve()}`, I got the following error:
```
error[E0525]: expected a closure that implements the `FnMut` trait, but this closure only implements `FnOnce`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0525`.
error: Could not compile `foobar`.
```

**Comment by limira** [comment]
In the example, `fn update_time()` is a function. In your code, `solve` is a method of `foo`! So there is some kind of... difference!
I don't know enough about `move || {foo.solve()}` to say anything about it!

**Comment by limira** [comment]
In `examples/closures`, I add this:
```rust
struct Counter {
    clicks: u32,
}
impl Counter{
    fn count(&mut self){
        self.clicks += 2;
    }
}
```
Then use it instead of `clicks`:
```rust
    //let mut clicks = 0;
    let mut counter = Counter{clicks:0};
    let b = Closure::new(move || {
        //clicks += 1;
        counter.count();
        document
            .get_element_by_id("num-clicks")
            .set_inner_html(&counter.clicks.to_string());
    });
```
It works, hope it help you!

**Comment by cubetastic33** [comment]
After reading your answers, I tried both the method example you gave _and_ a regular function defined inside that function exactly like the one in `examples/closures`. Both of them compile, but give this error in the JS console:
```
Uncaught Error: closure invoked recursively or destroyed already
    at Module.__wbindgen_throw (foo.js:172)
    at __wbindgen_throw (main.js:77)
    at wasm_bindgen::throw::hc87cb30c4d40aef9 (:8080/wasm-function[188]:86)
    at _$LT$$LP$dyn$u20$core..ops..function..FnMut$LP$$RP$$u20$$u2b$$u20$$u27$static$RP$$u20$as$u20$wasm_bindgen..closure..WasmClosure$GT$::invoke_fn::invoke::h413d11663b64255b (:8080/wasm-function[196]:80)
    at Function.cbarg3 (foo.js:124)
```

**Comment by limira** [comment]
[Did you miss this](https://github.com/rustwasm/wasm-bindgen/blob/master/examples/closures/src/lib.rs#L77-L82)?

**Comment by cubetastic33** [comment]
@limira Thanks a lot! Now it works - I did indeed miss that.

**Comment by alexcrichton** [comment]
Sounds like it's working well now, thanks @limira for the help!

**Comment by najtin** [comment]
> [Did you miss this](https://github.com/rustwasm/wasm-bindgen/blob/master/examples/closures/src/lib.rs#L72-L82)?

in case anyone is stumbling upon this in 2022: the link is no longer valid, as the master branch was restructured since. I believe the original comment pointed to this: https://github.com/rustwasm/wasm-bindgen/blob/269c49138010f7b7d9a1229748fbbf12bfdad99e/examples/closures/src/lib.rs#L72-L82
