### ISSUE TITLE
How to use querySelectorAll?

### ISSUE THREAD

**Issue by cubetastic33** [rustwasm/wasm-bindgen#783]
I'm new to both rust and wasm-bindgen, so this might be a bit simple, but I can't seem to figure it out, and I couldn't find it anywhere either. I want to get the 3rd .foo element for example, and I think I need querySelectorAll to do this like `querySelectorAll('.foo')[2]`. I got querySelector like this:
```
#[wasm_bindgen]
extern {
    type HTMLDocument;
    static document: HTMLDocument;
    #[wasm_bindgen(method, js_name = querySelector)]
    fn query_selector(this: &HTMLDocument, selector: &str) -> Element;
}
```
But when I did this:
```
#[wasm_bindgen(method, js_name = querySelectorAll)]
fn query_selector_all(this: &HTMLDocument, selector: &str) -> Vec<Element>;
```
, I got this error:
```
error[E0277]: the trait bound `std::boxed::Box<[Element]>: wasm_bindgen::convert::FromWasmAbi` is not satisfied
 --> src/lib.rs:4:1
  |
4 | #[wasm_bindgen]
  | ^^^^^^^^^^^^^^^ the trait `wasm_bindgen::convert::FromWasmAbi` is not implemented for `std::boxed::Box<[Element]>`
  |
  = help: the following implementations were found:
            <std::boxed::Box<[f32]> as wasm_bindgen::convert::FromWasmAbi>
            <std::boxed::Box<[i16]> as wasm_bindgen::convert::FromWasmAbi>
            <std::boxed::Box<[i64]> as wasm_bindgen::convert::FromWasmAbi>
            <std::boxed::Box<[i8]> as wasm_bindgen::convert::FromWasmAbi>
          and 7 others
  = note: required because of the requirements on the impl of `wasm_bindgen::convert::FromWasmAbi` for `std::vec::Vec<
Element>
```

**Comment by limira** [comment]
`querySelectorAll` return a `NodeList`, so, you must import `NodeList` and its properties/methods, then

```rust
#[wasm_bindgen(method, js_name = querySelectorAll)]
fn query_selector_all(this: &HTMLDocument, selector: &str) -> NodeList;
//                                                            ^^^^^^^^ return type
```

**Comment by cubetastic33** [comment]
@limira I couldn't find how to "import NodeList" - I check the wasm-bindgen book and also googled this, and I also tried the following code which of course didn't work:
```
extern crate web_sys;
use web_sys::prelude::*;
```

**Comment by limira** [comment]
If you want to use `web_sys` you should consult the [api docs](https://rustwasm.github.io/wasm-bindgen/api/web_sys/index.html) to see if what you need is already imported or not (afaik, web_sys is not ready to use yet)!
Otherwise, I guess that you must import everything using `wasm-bindgen`:
```rust
#[wasm_bindgen]
extern {
    type HTMLDocument;
    static document: HTMLDocument;
    #[wasm_bindgen(method, js_name = querySelector)]
    fn query_selector(this: &HTMLDocument, selector: &str) -> Element;
    #[wasm_bindgen(method, js_name = querySelectorAll)]
    fn query_selector_all(this: &HTMLDocument, selector: &str) -> NodeList;

    // Import NodeList/Node and their properties/methods
    type NodeList;
    #[wasm_bindgen(method)]
    fn item(this: &NodeList, index: u32) -> Option<Node>;

    type Node;
    ....
}
```

**Comment by cubetastic33** [comment]
@limira Okay! Thanks a lot -that worked (I just replaced `Option<Node>` with `Option<Element>`, which had some other methods defined already. But I still have some questions - using `item(index)`, I'm able to get specific elements, but how do I loop over all the results? Or, if I could get the number of results, I could use a for loop with `i in 0..number_of_results`, and do `.item(i)`. How do I do this?

**Comment by limira** [comment]
You need to import `NodeList.length`

**Comment by cubetastic33** [comment]
Okay, great - I found [this](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.NodeList.html) part of the api docs you had linked to, which seems to have my answers. Thanks a _lot_ for helping me!

**Comment by cubetastic33** [comment]
@limira Oh, no - I'm still getting errors. This is my code:
```
//NodeList methods
#[wasm_bindgen(method)]
fn item(this: &NodeList, index: u32) -> Option<Element>;
#[wasm_bindgen(method)]
fn length(this: &NodeList) -> u32;
````
And this line:
`document.query_selector_all(".className").length()`
compiles properly, but I get the following error in JS:
```Uncaught (in promise) TypeError: Illegal invocation
    at eval (foo.js:204)
    at Module../foo.js (0.main.js:11)
    at __webpack_require__ (main.js:114)
```

**Comment by limira** [comment]
I think [this will help](https://rustwasm.github.io/wasm-bindgen/reference/attributes/on-js-imports/getter-and-setter.html):
```rust
#[wasm_bindgen(method, getter)] // getter
fn length(this: &NodeList) -> u32;
```
(I am gonna offline now)

**Comment by cubetastic33** [comment]
@limira Yes! It works! :smile: Thank you so much...

**Comment by alexcrichton** [comment]
Ok great! I'm gonna close this as it looks solved
