### ISSUE TITLE
Emit fixed-arity versions of variadic functions in webidl frontend

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-bindgen#788]
After #726, we can import functions that take any number of args as `&[JsValue]`.

If you are always calling an imported variadic function with a fixed N number of arguments, it is both faster and more ergonomic to have a version of the import that is specialized to N arguments. Our webidl fronted should automatically emit fixed N imports for 0...N.

For example,

```webidl
void fluffers(any... args);
```

should generate the equivalent of

```rust
#[wasm_bindgen]
extern {
    // What we generate now.
    fn fluffers(&[JsValue]);

    // but we should also generate these.
    #[wasm_bindgen(js_name = fluffers)]
    fn flufers0();

    #[wasm_bindgen(js_name = fluffers)]
    fn flufers1(args1: &JsValue);

    #[wasm_bindgen(js_name = fluffers)]
    fn flufers2(args1: &JsValue, args2: &JsValue);

    #[wasm_bindgen(js_name = fluffers)]
    fn flufers3(args1: &JsValue, args2: &JsValue, args3: &JsValue);

    // Etc... up to N
}
```

I think N=3 or N=4 would be good.

**Comment by fitzgen** [comment]
+cc @derekdreery

**Comment by derekdreery** [comment]
Yeah that seems like a good idea! I'm not sure that &[JsValue] works in general yet, IIRC it was one of the tests I had to comment out.

**Comment by alexcrichton** [comment]
Fixed in https://github.com/rustwasm/wasm-bindgen/pull/792

**Comment by derekdreery** [comment]
Sorry I've been busy with work recently, I plan to do more when I have free time!

**Comment by alexcrichton** [comment]
Oh no worries!
