### ISSUE TITLE
Behavior of wasm_bindgen on non wasm target

### ISSUE THREAD

**Issue by mandeepbrar** [rustwasm/wasm-bindgen#801]
Was trying to look up the behavior of wasm_bindgen attribute if i am not using wasm32-unknown-unknown target. But couldnt find in the documentation. Will this be ignored or will some action be done. The intention is to write some code that is common between wasm and mobile.

**Comment by chinedufn** [comment]
Not sure about any technical implications such as.. for example.. does it affect the final binary size at all.. but you can still compile to other targets so you can have code that is common between your WASM target and another target.

You'll panic if you try to call any functions that expect a DOM to be there or anything of course. So on mobile you wouldn't be able to call functions that create DOM elements etc.

---

It sounds like you might want a cargo workspace with a `mobile` crate and `web` crate that both use your common functionality crate. If you like your common functionality crate can expose a feature(s) and your `web` and `mobile` crate can enable this feature(s) for conditional compilation.

More here https://doc.rust-lang.org/1.9.0/book/conditional-compilation.html#cfg_attr

**Comment by mandeepbrar** [comment]
Thank you. The question was more about common objects(POJO types) to be used by both. Can i used wasm-bindgen on them and expect to work with both.
