### ISSUE TITLE
web-sys: required Cargo features aren't exhaustive

### ISSUE THREAD

**Issue by Bobo1239** [rustwasm/wasm-bindgen#802]
For example `Window::fetch_with_str`'s [requirement list](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.Window.html#method.fetch_with_str) only includes the `Window` feature but to actually get access to the  function, you need at least `Window`, `Request`, and `Response`.

**Comment by alexcrichton** [comment]
Thanks for the report! This shouldn't actually require the `Request` and `Response` features though, that's a bug! It should be fixed in https://github.com/rustwasm/wasm-bindgen/pull/803
