### ISSUE TITLE
web-sys public interface

### ISSUE THREAD

**Issue by jonathanKingston** [rustwasm/wasm-bindgen#807]
I would like the ability to figure out the relationship from webidl files and investigate the properties, and interfaces an element exposes.

The use-case I am trying to solve is essentially wrapping up the interfaces and neaten the API a little. That way I can wrap that "input" creates `HTMLInputElement` and also implements `HTMLElement`

I started by parsing webidl myself however it will end up requiring a lot of reimplementation of the web-sys crate. I ended up having to manipulate `type` into `_type`, `accessKey` to `access_key` and `HTMLDivElement` to `HtmlDivElement`

I'm not sure if it makes sense to output the backend format instead, in a way I kind of need a mapping of the webidl to the web_sys.

To be useful I would need something like an interim data structure like the following:
```
HtmlInputElement {
  webidl_name: "HTMLInputElement",
  interfaces: ["HTMLElement", "Element", "EventTarget"],
  properties: [
    {
      name: "id",
      setter: {name: "set_id", arguments: [...]}
    }
  ]
}
```

Having the ast that is about to be written to file might be a simpler way to code generate and wrap around the Element interfaces.

**Comment by alexcrichton** [comment]
This seems like a good idea to me! I think we could pretty reasonably basically have a public crate that sits on top of web-sys's webidls and is run by web-sys's build script. That could have a conservative API which provides access to all of the internals of what we do, basically iterating over the program imports that we generate

**Comment by alexcrichton** [comment]
I'm going to close this since it's been quiet for some time, it's still possible to add this if necessary though!

**Comment by cortopy** [comment]
@alexandrestein I've just landed here from https://github.com/rust-lang/rls/issues/1489. It seems like this would be required to have a good RLS experience with web-sys

**Comment by Pauan** [comment]
@cortopy Although it wasn't intended to fix RLS, [this PR](https://github.com/rustwasm/wasm-bindgen/pull/2012) does indirectly fix it, because it removes the build.rs script.

**Comment by dancespiele** [comment]
@Pauan In my case I have the last version of wasm-bindgen(0.2.59) and web_sys(0.3.36) and I don't get autocomplete in vscode
