### ISSUE TITLE
Support converting js_sys typed arrays to Vec

### ISSUE THREAD

**Issue by aschampion** [rustwasm/wasm-bindgen#811]
Currently there's no way to convert `TypedArray`s to `Vec<T>`s in rust, e.g., `js_sys::Uint8Array` to `Vec<u8>`, even though one can pass (via an implicit copy) a `Uint8Array` across the wasm boundary to rust functions expecting `Vec<u8>` or `&[u8]`. See [this comment](https://github.com/rustwasm/wasm-bindgen/issues/5#issuecomment-420401682) for motivation.

**Comment by alexcrichton** [comment]
One thing I've been pondering recently is if it's possible to, in a generic fashion, convert anything that implements `IntoWasmAbi` into a `JsValue`. This would fit the bill perfectly for this issue as well as solve a number of other issues I've wanted to handle in the past. We currently do this ad-hoc in two locations:

* [You can extract a `JsValue` from a `Closure<T>`](https://github.com/rustwasm/wasm-bindgen/blob/d10ca579e43a9d072d1aa9880fa873fd59a8f0c2/src/closure.rs#L231-L235)
* [`#[wasm_bindgen]` structs can also be converted](https://github.com/rustwasm/wasm-bindgen/blob/d10ca579e43a9d072d1aa9880fa873fd59a8f0c2/crates/backend/src/codegen.rs#L173-L201)

It'd be great to somehow unify the two of these and provide this for all types (like `&[u8]` which can be converted into a `JsValue`). I'll noodle on this a bit...

**Comment by alexcrichton** [comment]
I believe I've implemented this in https://github.com/rustwasm/wasm-bindgen/pull/918

**Comment by chinedufn** [comment]
I have a fetch request and I'm turning the response into an array buffer. I then want to convert that array buffer into `[u8]` so that I can deserialize it with `bincode`.

Poked around a bit before I realized that it wasn't possible (I sadly didn't fully understand this issue when I first saw it, my own fault!)

So, in case anyone else gets tripped up, I'm sharing what I'm planning to do in the meantime:

```rust
#[wasm_bindgen]
extern "C" {
    /// Bridge the gap for things that are currently unsupported or difficult to accomplish with
    /// wasm-bindgen
    pub type WasmHelpers;

    #[wasm_bindgen(static_method_of = WasmHelpers)]
    pub fn uint8array_into_boxed_slice(uint8array: Uint8Array) -> Box<[u8]>;
}
```

```rust
let mut opts = RequestInit::new();
opts.method("GET");
opts.mode(RequestMode::Cors);

let request = Request::new_with_str_and_init("/dist/meshes.bytes", &opts).unwrap();

let window = web_sys::window().unwrap();
let request_promise = window.fetch_with_request(&request);

let future = JsFuture::from(request_promise)
    .and_then(|resp_value| {
        let resp: Response = resp_value.dyn_into().unwrap();
        resp.array_buffer()
    })
    .and_then(|array_buffer_promise: Promise| JsFuture::from(array_buffer_promise))
    .and_then(|array_buffer| future::ok(Uint8Array::new(&array_buffer)));

let mesh_bytes = WasmHelpers::uint8array_into_boxed_slice(future.wait().unwrap());
let meshes: HashMap<String, BlenderMesh> = bincode::deserialize(&mesh_bytes).unwrap();
```

```html
<script>
  // Bridge the gap for things that are currently unsupported or difficult to accomplish with
  // wasm-bindgen
  window.WasmHelpers = {
    uint8array_into_boxed_slice: array => array
  }
</script>
```

**Comment by alexcrichton** [comment]
Ok I've made another attempt to solve this in https://github.com/rustwasm/wasm-bindgen/pull/1147!

**Comment by dakom** [comment]
would it make sense to implement a `to_vec()` on top of `copy_to()`?

i.e. to allocate a new local Vec, copy_to() it, and return that?
