### ISSUE TITLE
web-sys: Unable to add body to a Request

### ISSUE THREAD

**Issue by Bobo1239** [rustwasm/wasm-bindgen#817]
I'm trying to create a `Request` with a body but I can't figure out how (or it isn't possible yet). Neither `Request` nor `RequestInit` offer a way to add a body. Ultimately I'd like to do something like [this](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#Uploading_JSON_data).

**Comment by fitzgen** [comment]
`RequestInit` has a `body` member:

```webidl
dictionary RequestInit {
  // ...
  BodyInit? body;
  // ...
};
```

and `BodyInit` is defined as

```webidl
typedef (Blob or BufferSource or FormData or URLSearchParams or USVString) BodyInit;
```

I wonder if we support that kind of union yet... time to dig into the logs.

**Comment by afdw** [comment]
No, it is not yet supported. Only non-nullable unions with only interfaces in them are supported in dictionaries.

**Comment by fitzgen** [comment]
@afdw can you point me to where we identify and skip these members right now? I think we need better logging

**Comment by afdw** [comment]
https://github.com/rustwasm/wasm-bindgen/blob/4e86ecd2c58b489c561f45d5bb1230312241a7d9/crates/webidl/src/idl_type.rs#L508-L528

**Comment by fitzgen** [comment]
Thanks!

**Comment by fitzgen** [comment]
I think it is OK to fall back to `JsValue` for nullable unions
