### ISSUE TITLE
Gracefully handle attempts to run tests configured for headless browsers in node and vice versa

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-bindgen#822]
This will be used (perhaps indirectly?) by `wasm-pack test`. I expect users will do (or have CI configured to do) something like this:

```
wasm-pack test --node
wasm-pack test --firefox
```

with a tests directory like

```
my-crate/
  |- tests/
  |    |- node.rs        # tests for node.js
  |    `- browsers.rs    # tests for browsers
```

and we should ultimately do the Right Thing and just skip tests that aren't configured for the given target, but this requires some sort of introspection/communication in the test runner and/or test `.wasm` binary itself.

Perhaps a custom section in the test binary that identifies what it is configured to target?

cc @alexcrichton @ashleygwilliams

**Comment by alexcrichton** [comment]
Currently there's effectively a custom section yeah for browsers/node, but I'm not entirely sure how we'd plumb that through into this. Do you have an idea in mind for how we'd automatically classify tests?

**Comment by fitzgen** [comment]
Talked about this at lunch today: basically just need flags for "only run browser tests" and "only run node tests"
