### ISSUE TITLE
Discuss size optimization

### ISSUE THREAD

**Issue by joshtriplett** [rustwasm/wasm-bindgen#826]
https://rustwasm.github.io/wasm-bindgen/whirlwind-tour/basic-usage.html says:

> After this you'll have a wasm file at target/wasm32-unknown-unknown/debug/js_hello_world.wasm. Don't be alarmed at the size, this is an unoptimized program!

Even compiled in release mode, however, this still seems true. Please consider explaining this in a bit more detail to show what the real sizes look like after processing.

**Comment by fitzgen** [comment]
Our documentation for size optimization is currently embedded in the Game of Life tutorial, but should be split out into its own reference page soon: https://rustwasm.github.io/book/game-of-life/code-size.html

Once it is split out into a reference page, we should link to that here.

**Comment by joshtriplett** [comment]
This isn't just about optimizing the size of the file, it's also that the initial mention needs to call attention to how the .wasm file `cargo build --release --target wasm32-unknown-unknown` generates is thousands of times larger than the file wasm-bindgen generates from it.

How about this for text?

"When using `wasm-bindgen`, the wasm file generated by Rust's WebAssembly code generation will often be much larger than the file you actually ship; it contains various metadata that `wasm-bindgen` reads and uses when generating the final wasm file. For information on shrinking that smaller file even further, see (link to the page you mentioned)."

**Comment by fitzgen** [comment]
Sounds good to me!
