### ISSUE TITLE
web-sys's API around Window seems to be wrong

### ISSUE THREAD

**Issue by upsuper** [rustwasm/wasm-bindgen#834]
Currently, web-sys provides a Window type and use static functions to access objects and functions in the current global.

This seems to be conceptually wrong. Window is an object, and there can be multiple independent Window around, so the current global is just one Window object.

I suggest it provide a top level function `window()` which returns a `Option<Window>` instead (`Option` because the code may run in worker / worklet global where `window` isn't available).

**Comment by upsuper** [comment]
And it seems to me that to reasonably implement `Window.open` as well as `HTMLIFrameElement.contentWindow`, there needs to be proper `Window` object support.

**Comment by alexcrichton** [comment]
Makes sense to me, I'll work on reverting #761
