### ISSUE TITLE
Document.readyState isn't exposed in web-sys

### ISSUE THREAD

**Issue by upsuper** [rustwasm/wasm-bindgen#839]
[Document.readyState](https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState) doesn't seem to be exposed via web-sys. It probably needs adding a new type?

**Comment by afdw** [comment]
Looks like it was commented for some reason, probably something was not supported when this file was enabled, as it was one of the first: https://github.com/rustwasm/wasm-bindgen/blob/f8354b3a88de013845a304ea77d8b9b9286a0d7b/crates/web-sys/webidls/enabled/Document.webidl#L124-L132
