### ISSUE TITLE
Allow returning Result<T, JsValue> for throwing

### ISSUE THREAD

**Issue by upsuper** [rustwasm/wasm-bindgen#841]
Many functions in web-sys return a `Result<_, JsValue>` presumably because they can throw in certain cases. But Rust code isn't really the best place to handle those, so it would be better if we can just pass (rethrow) it back to JavaScript.

I would suggest have wasm-bindgen support function returning `Result<T, JsValue>` where `T` is the current supported return types, and handle the `Err(_)` branch as throw.

This way, we can also easily redirect exceptions from web-sys functions to the caller rather than need to `unwrap()` everywhere.

**Comment by Pauan** [comment]
I'm not so sure about that. Rust is calling these functions, so Rust should deal with the possibility of failure (just like when it calls another Rust function).

Using `unwrap` is one way to deal with it, but a better way is to use `?` (which is the idiomatic Rust way of handling errors).

There are plenty of situations where the Rust side needs to know whether a failure occurred or not, therefore *always* re-throwing doesn't seem like a great solution to me.

**Comment by upsuper** [comment]
I'm not proposing always re-throwing exception, I'm proposing that Rust code *can* use `?` to re-throw when it seems to be the right thing to do. Currently it is not possible, because you cannot return `Result<_, JsValue>` from a export function.

**Comment by Pauan** [comment]
Oh, I see! Yeah, that makes sense.
