### ISSUE TITLE
web-sys types should probably impl Deref to types they're inheriting

### ISSUE THREAD

**Issue by upsuper** [rustwasm/wasm-bindgen#842]
Currently, for example if you have an `Element`, but you want to use `first_child` from `Node`, you have to either `e.into::<Node>().first_child()` or `(e.as_ref() as &Node).first_child()`. If would be great if one can just use `e.first_child()` without explicit type conversion.

Types defined in WebIDL can only have single inheritance, so I think this is doable via `Deref` chain.

**Comment by afdw** [comment]
Check https://github.com/rustwasm/rfcs/pull/3.

**Comment by upsuper** [comment]
Thanks for the pointer. It seems that the conversion there leans towards having `Deref` as well. Closing this issue for now.

**Comment by upsuper** [comment]
Maybe we can keep this open until the proposed change in rustwasm/rfcs#3 is actually implemented?

**Comment by alexcrichton** [comment]
Ah I'm gonna close this in favor of the RFC. If we decide to merge that then we can have a tracking issue here to implement that, but until that happens all discussion should be on the RFC!
