### ISSUE TITLE
Hard to pass functions to web-sys

### ISSUE THREAD

**Issue by upsuper** [rustwasm/wasm-bindgen#843]
Tehe wasm-bindgen reference has [a chapter for passing Rust closures to JS](https://rustwasm.github.io/wasm-bindgen/reference/passing-rust-closures-to-js.html), which involves using `Closure` from wasm-bindgen.

However, functions exposed from web-sys doesn't seem to be using that. For example, `Window::set_timeout_with_callback` accepts a `&Function` which doesn't seem to have any conversion method with `Closure`, and it doesn't seem to be possible to construct a `Function` from Rust code (without writing JavaScript code inline).

It would be great if it is possible to pass Rust function or closure to web-sys functions which accept callbacks.

**Comment by afdw** [comment]
Here is what you can do for now:
```rust
let closure: Closure<FnMut()> = Closure::new(|| {
    web_sys::console::log_1(&"Timeout".into());
});
web_sys::Window::set_timeout_with_callback_and_timeout_and_arguments_0(
    closure.as_ref().unchecked_ref(),
    3000,
).unwrap();
closure.forget();
```

See [Paint](https://github.com/rustwasm/wasm-bindgen/tree/e1ea897d2ff3423afd0a3d829776484337496b15/examples/paint) for more examples.
