### ISSUE TITLE
Proper way to pass Vec<js_sys::Function>  into Rust and invoke them

### ISSUE THREAD

**Issue by Tarnadas** [rustwasm/wasm-bindgen#858]
Hi,

for my use case I need to pass a Vec\<js_sys::Function\> into Rust. Since this is not possible, I use Vec\<JsValue\>, but then I lose the possibility to invoke these functions from within Rust.

Is it possible to directly invoke a JsValue as a function from within Rust?

As a workaround I currently pass an invoker function from JS to Rust which takes a function as an argument and invokes it. Example:

```js
const wasmBooted = import('./rust');

// curryable function
function rs (i: number): () => void {
  return (): void => console.log(`INSIDE RUST ${i}`);
}

(async (): Promise<void> => {
  const wasm = await wasmBooted;
  const { sendExampleToJs } = wasm;
  sendExampleToJs(
    // invoker function
    (fn: () => void): void => {
      fn();
    },
    // create function array from curryable function
    Array.from((function * (): IterableIterator<() => void> {
      for (let i = 0; i < 10; i++) {
        yield rs(i);
      }
    })())
  );
})();
```

```rust
#[wasm_bindgen(js_name=sendExampleToJs)]
pub fn send_example_to_js(invoker: js_sys::Function, functions: Vec<JsValue>) {
    let this = JsValue::NULL;
    for function in &functions {
        invoker.call1(&this, function);
    }
    // this didn't work and doesn't look right
    // let func = unsafe { &*(&functions[0] as *const JsValue as *const js_sys::Function) };
    // func.call0(&this);
}
```

**Comment by afdw** [comment]
I think it should be possible to use [JsCast::unchecked_into](https://rustwasm.github.io/wasm-bindgen/api/wasm_bindgen/trait.JsCast.html#method.unchecked_into) here for now, it should be better than unsafe.

**Comment by alexcrichton** [comment]
Indeed I believe `JsCast` should solve the problem here, but thanks for the report!
