### ISSUE TITLE
is there a spec about what parts of `std` can be used and what parts of `std` can not be used in rust wasm backend ?

### ISSUE THREAD

**Issue by xieyuheng** [rustwasm/wasm-bindgen#865]
When I used some function I like this :: https://github.com/xieyuheng/jojo/blob/3405bd579307a69c2c6bfd824415166b9787e036/jojo-web/src/lib.rs#L12
I got the following error, which does not make sense to me ::

```
[WDS] Disconnected! client:171:5
Source map error: TypeError: sockjs.js.map is not a valid URL.
Resource URL: webpack:///./node_modules/sockjs-client/dist/sockjs.js?
Source Map URL: sockjs.js.map[Learn More]
RuntimeError: unreachable executed d4e5c4e36f490b3d3ac2.module.wasm:190730:1
```

**Comment by xieyuheng** [comment]
for example, are functions from `std::path` usable in wasm backend ?

**Comment by alexcrichton** [comment]
Thanks for the report! I'd recommend using [`console_error_panic_hook`](https://crates.io/console_error_panic_hook) in situations like this as it should help pinpoint where the panic is and precisely what isn't supported.

**Comment by xieyuheng** [comment]
Thank you again Alex.
Sorry to bug you so often.

**Comment by alexcrichton** [comment]
Oh no worries! Questions are always welcome :)
