### ISSUE TITLE
Support passing non-closure functions to js without allocation?

### ISSUE THREAD

**Issue by upsuper** [rustwasm/wasm-bindgen#874]
Currently we can use `Closure::wrap` to create a `Closure` and cast it to `Function` for passing to Web API. However it isn't always necessary to have a closure, and in those cases an additional allocation may be unfortunate.

Can we / do we have some approach to pass function pointer like `fn(Event)` to Web API without using `Box`?

**Comment by alexcrichton** [comment]
Currently `Box::new(|a| the_function_pointer(a))` I think will "just work" in that it won't actually allocate any memory (as there's no captured environment). Currently though we [wrap it in another `Rc`](https://github.com/rustwasm/wasm-bindgen/blob/9a1fa5a81b75807b03bee54907297560fd3a88d6/src/closure.rs#L139) which causes memory allocation to always happen.

I think this may perhaps be best to explore first by optimizing the runtime implementation of that? We could probalby dispatch at runtime whether it's a ZST or not (behind the `Box`) and then act accordingly (avoiding the `Rc` for ZSTs)

**Comment by upsuper** [comment]
Oh, I didn't realize that ZST optimization would be applied here as well. And yeah, it sounds like it would be good to try optimizing the runtime implementation first.

After reading the code in [closure.rs](https://github.com/rustwasm/wasm-bindgen/blob/9a1fa5a81b75807b03bee54907297560fd3a88d6/src/closure.rs), I'm confused by why we need the `Rc` at all. Couldn't `Closure` just store a `UnsafeCell<Box<T>>` instead? It doesn't seem to me the counter is used at all. Maybe we just need an unmovable place to put the fat pointer?

It doesn't seem that Rust std provides a safe way to detect ZST as well. Maybe we can `transmute` it and check whether the first pointer is `0x1` but that doesn't feel good...
