### ISSUE TITLE
web-sys. webgl error 

### ISSUE THREAD

**Issue by oldtree2008** [rustwasm/wasm-bindgen#875]
I test the sample webgl. It is OK.when I add uniform parameter. 
error[E0599]: no method named `get_uniform_location` found for type `web_sys::WebGlRenderingContext` in the current scope. get_uniform_block_index etc do not work.
why?

**Comment by afdw** [comment]
Have you `WebGlProgram` and `WebGlUniformLocation` features enabled?

**Comment by alexcrichton** [comment]
Indeed I think @afdw is right here in that it sounds like the crate features may not be activated. You'll probably want to [browse the online docs](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.WebGl2RenderingContext.html#method.get_uniform_location) to ensure that all the right features are activated, and that should do the trick!

**Comment by oldtree2008** [comment]
Thanks. When WebGlProgram and WebGlUniformLocation features enabled,It is Ok
