### ISSUE TITLE
How to import JS function takes object as parameter?

### ISSUE THREAD

**Issue by lygyf123** [rustwasm/wasm-bindgen#885]
Example:
```
function area(obj) {
    console.log(obj.length * obj.width);
}
```

**Comment by fitzgen** [comment]
If you want a function that is callable with any JS object, you can do this:

```rust
extern crate js_sys;
extern crate wasm_bindgen;
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
extern {
    fn area(obj: &js_sys::Object);
}

// ...

// get an object from somewhere...
let obj: js_sys::Object = ...;

// call the JS `area` function with the object:
area(&obj);
```

If you want to type it to only work with isntances of `Shape` or soemthing like that, look into importing JS classes and how to define methods/getters/etc in the guide:

* https://rustwasm.github.io/wasm-bindgen/reference/types/imported-js-types.html
* https://rustwasm.github.io/wasm-bindgen/reference/attributes/on-js-imports/method.html
* https://rustwasm.github.io/wasm-bindgen/reference/attributes/on-js-imports/getter-and-setter.html

etc
