### ISSUE TITLE
create js-sys::Object from literals?

### ISSUE THREAD

**Issue by an4tua** [rustwasm/wasm-bindgen#889]
After import a JS function, I can't find a way to pass a object to it.
Is there a simple way like JS?
```rust
let object: js_sys::Object = {
    property1: "some string",
    property2: 100
}
```

**Comment by afdw** [comment]
You should be able to do it like this:
```rust
let object = Object::new();
Reflect::set(&object.as_ref(), &"property1".into(), &"some string".into()).unwrap();
Reflect::set(&object.as_ref(), &"property2".into(), &100.0.into()).unwrap();
```

**Comment by an4tua** [comment]
It works. Thanks

**Comment by alexcrichton** [comment]
FWIW this'd make a neat macro if someone were interested!

**Comment by fitzgen** [comment]
For posterity, here are the docs for working with untyped JS objects: https://rustwasm.github.io/wasm-bindgen/reference/accessing-properties-of-untyped-js-values.html
