### ISSUE TITLE
Pretty-ify generated JS code

### ISSUE THREAD

**Issue by alexcrichton** [rustwasm/wasm-bindgen#89]
Right now it has crazy indentation, we should make it pretty!

@ashleygwilliams says we should use `prettier`!

**Comment by corbinu** [comment]
@alexcrichton does this mean the CLI will depend on Node being installed? 

If so how would you feel if we modify the output to be TypeScript and simply run it through the TSC into JavaScript if people don't specify --typescript? 

That way we get the declaration file automatically.

**Comment by alexcrichton** [comment]
@corbinu hm perhaps! I'm not actually too sure how this would work, I'm pretty unfamiliar with `pretty` myself. I think for now we'd probably want to shell out to something rather than embedding a JS interpreter in wasm-bindgen itself, but we can also probably gracefully handle the case where it's not available and just opportunistically do it.

**Comment by ashleygwilliams** [comment]
i was thinking that we might just first implement it for when tests are run as that's really the time where a prettified output would be appreciated. post that i think there might be some fun compile stuff we might be able to do to make it work, or there's always just porting it entirely to rust ;)

**Comment by corbinu** [comment]
Ok no worries. I can put something together that shells out

**Comment by corbinu** [comment]
Ok so this is what I have so far. 

I am building a Node cli app that will use TypeScript and Prettier to do a bunch of the work. 

However I also have been testing and I created a new bindgen for Duktape. Looks like I can get the JS to run inside of Duktape as well. (looks like I can keep that app under 5mb but don't think it should be directly included as most won't need it). 

That way the cli can try these things in order:

1. See if the Node companion CLI is installed and use that
2. See if npx with an acceptable version of node is installed and if so run the node companion CLI with npx
3. See if the Duktape wrapped version is installed and use that
4. Print out that the user should either download node or install the wrapped cli with something like "cargo install wasm-bindgen-cli-js-fallback"

I should have a MVP by the start of next week.

**Comment by alexcrichton** [comment]
Awesome! Let me know if you need any help @corbinu

**Comment by corbinu** [comment]
Will do! Still experimenting but going to need a lot of feedback.

**Comment by alexcrichton** [comment]
@kwonoj it's true yeah we probably wouldn't want to ship node with `wasm-bindgen`, but that being said I think it'd be possible to opportunistically try to prettyify code and silently avoid that if it's otherwise not available.

Another option here is to simply generate prettier code! I've added a few commits to do this historically, and there's just a few places left that produce ugly code by default I believe

**Comment by kwonoj** [comment]
> simply generate prettier code

actually this seems most feasible solutions :)

**Comment by alexcrichton** [comment]
FWIW the parts of the code that need fixing I believe are mostly related to generating `class Foo { .. }` and member methods. That, and the `--no-modules` output could still use a bit of improvement

**Comment by alexcrichton** [comment]
Fixed in https://github.com/rustwasm/wasm-bindgen/pull/268 I believe, thanks @FreeMasen!
