### ISSUE TITLE
Clarity on which targets are supported

### ISSUE THREAD

**Issue by ndarilek** [rustwasm/wasm-bindgen#892]
I'm having a hard time figuring out whether or not this is intended to work with wasm32-unknown-emscripten. There seem to be lots of checks of the form:

```
        #[cfg(all(target_arch = "wasm32", not(target_os = "emscripten")))]
```

But I'm not sure if that is meant to preclude generation of code known not to work or not needed on Emscripten, or if that is meant to make this crate a no-op when compiled for wasm32-unknown-emscripten. And I can't find a clear answer in any of the docs I've checked. Apologies if it is documented somewhere and I haven't found it.

FWIW, I'm aware of Rust's preference for wasm32-unknown-unknown, and if I didn't need to link against C libraries that will never be ported to Rust, I'd prefer that too. I'm just currently jumping through lots of hoops to make this code work in wasm, and if wasm-bindgen doesn't support Emscripten at all, it'd be helpful to see that in some prominant place, instead of learning that after I've jumped through bunches of hoops only to get a .wasm file that won't work. :)

And if it *does* work under Emscripten, some general pointers on how to get a working .wasm file would also be helpful. I'm happy to try distilling those points into user-friendly docs if I have a bit of guidance. The issue I'm hitting now is that `crate-type=["cdylib"]` isn't supported under Emscripten and doesn't generate a .wasm file. So now I'm trying to create a bin crate with an empty `main` and a more JS-friendly API which I export via `#[wasm_bindgen]`, but that's going to take a bit of work, and I'd rather not do that if what I'll ultimately get is an incompatible .wasm file. :)

Thanks!

**Comment by alexcrichton** [comment]
Thanks for the report! Definitely agreed we should clarify this. The `wasm-bindgen` project doesn't work on the Emscripten target, only the `wasm32-unknown-unknown` target.

**Comment by ndarilek** [comment]
Got it, thanks for saving me the effort of finding that out on my own. :)
