### ISSUE TITLE
Is it possible to have a `set_onclick` method which takes a closure which takes a `MouseEvent`

### ISSUE THREAD

**Issue by rbalicki2** [rustwasm/wasm-bindgen#894]
It looks like [set_onclick](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.HtmlElement.html#method.set_onclick) on HTMLElement takes a [Function](https://rustwasm.github.io/wasm-bindgen/api/js_sys/struct.Function.html), and there's no way to instantiate a function with a parameter (AFAICT). Thus, I've been doing my own wasm_bindgen binding to `set_onclick` that takes [a mouseevent](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.MouseEvent.html), so that I can have a rust closure that executes when an element is clicked.

Is there a way of doing this within web-sys, instead of working around it with the custom binding?

```
#[wasm_bindgen]
extern {
  pub type HTMLElement;
  #[wasm_bindgen(method, setter)]
  pub fn set_onclick(this: &HTMLElement, cb: &Closure<FnMut(MouseEvent)>);
}
// later...
  let html_el = unsafe {
    transmute::<&Element, &HTMLElement>(el)
  };
  let on_click_cb = Closure::new(|e: MouseEvent| { ... });
  html_el.set_onclick(&on_click_cb);
  on_click_cb.forget();
```

**Comment by alexcrichton** [comment]
We've got [an example using closures](https://rustwasm.github.io/wasm-bindgen/examples/closures.html), notably with using `web-sys` as well. Although the [closure doesn't take arguments](https://github.com/rustwasm/wasm-bindgen/blob/826619870f4cb043663530c8c6a60e486aa5b2b7/examples/closures/src/lib.rs#L110) right now you could add an argument and it would work the same way!

Would that solve your use case here?

**Comment by alexcrichton** [comment]
Ok I'm gonna close this because I believe the above comment and example should work, but if you've still got trouble please let us know!

**Comment by rbalicki2** [comment]
hm. the following code doesn't compile

`Closure::wrap(Box::new(move |e| {}));`

When you say add an argument, do you mean pass an extra argument from javascript (which then I can't access in Rust)? Do you mean make a PR to add an argument?

Thanks!

**Comment by rbalicki2** [comment]
Thanks, I will give that a try!
