### ISSUE TITLE
Full MS Edge Support

### ISSUE THREAD

**Issue by ernieturner** [rustwasm/wasm-bindgen#895]
After building a project with wasm-bindgen and getting it working as expected in Chrome/Safari/FF I decided to give Edge a shot since I expected things to work there as well since it supports WebAssembly in the latest version. However, when I loaded up my code nothing seemed to happen. I don't get any errors in the console, but nothing seems to work. After debugging and paring things down a bit the issue _might_ be related to using serde, but I'm not sure that's entirely what is responsible. 

I'm seeming to have the same issue running the `fetch` from the examples directory too - https://rustwasm.github.io/wasm-bindgen/exbuild/fetch. Loading that URL seems to work fine except in Edge where, similar to what I'm seeing, nothing happens, no errors, no console output. Plenty of other projects in the examples directory seem to work fine, so there appears to be something partial that doesn't work in Edge.

I did notice that when using serde the JS shim that wasm-bindgen creates has the following:

```
const TextDecoder = typeof self === 'object' && self.TextDecoder
    ? self.TextDecoder
    : require('util').TextDecoder;
``` 

And I know that `TextDecoder` [isn't available within Edge yet](https://caniuse.com/#feat=textencoder). However I tried just jamming in a quick polyfill for that but it didn't seem to change anything. Is there any docs/known issues around supporting Edge?

**Comment by alexcrichton** [comment]
Thanks for the report! We [discussed this during today's meeting](https://paper.dropbox.com/doc/RustWebAssembly-WG--AN0Kj_TSmeR5csz9JFryWJQsAg-dcXi5F7Bqlvg10zd7dKve#:uid=466221811040185070621428&h2=2018/09/27) and concluded that at least for `TextDecoder` we probably won't do the polyfill ourselves but we'd love to have documentation about how to support it! @xtuc mentioned that there's plugins for webpack and @fitzgen mentioned that there's a "drop in polyfill" which we can link to as well.

Once we figure out what to document we'll be sure to update all our examples with that as well!

Once I get a chance I'll investigate as well on Edge to see if there's other things that aren't supported.

**Comment by ernieturner** [comment]
Thanks for the reply and update! To be clear, I don't think the TextEncoder polyfill is the big issue here, it's more that I can't seem to get Edge to work even if I do add a polyfill. Once we figure out the root cause of why Edge doesn't work, I'd be more than willing to add some documentation content explaining the requirements for Edge and the necessity of adding a polyfill.

**Comment by ernieturner** [comment]
Just to confirm so I can try it myself, by "the example" do you mean the [fetch example](rustwasm.github.io/wasm-bindgen/exbuild/fetch) I posted originally?

**Comment by alexcrichton** [comment]
Yeah I built that locally, injected a polyfill, and then it worked in Edge (and it failed to work before)

**Comment by alexcrichton** [comment]
@ernieturner can you try out https://github.com/rustwasm/wasm-bindgen/pull/910 and see if it works for you? I think the generated JS also needed a few tweaks after running Edge locally a bit too. I'm unfortunately away from Windows right now so I haven't tested the final version, so a double check would be great!

**Comment by ernieturner** [comment]
It works! I pulled down this branch and ran it in both Edge 16 and 17 and it logged the expected content to the console. Thanks so much!
