### ISSUE TITLE
Unclear semantics of new() on Document

### ISSUE THREAD

**Issue by LaylConway** [rustwasm/wasm-bindgen#899]
While working with web-sys, I wanted to get the current global `document`. Looking through the docs I just saw `Document::new()` on `Document`, with the following documentation:

![firefox_2018-09-27_16-57-46](https://user-images.githubusercontent.com/3094382/46155229-1db38080-c277-11e8-8297-2b45ff41e219.png)

This made me assume this will get the global `document` as the documentation does not say otherwise.
It took a while of tracking down the issue of a failing `query_selector` call before I noticed that the *actual* way to do this is by calling `web_sys::window()` and calling `document()` from there.

Perhaps this should be documented for clarity?

**Comment by alexcrichton** [comment]
Thanks for the report! Adding a blurb about "this constructs a new instance" to all documentation for constructors definitely sounds like a good idea, I suspect that this may be a common mistake!
