### ISSUE TITLE
Generate webpack config, package.json, index.html and index.js 

### ISSUE THREAD

**Issue by sendilkumarn** [rustwasm/wasm-bindgen#90]
It would be awesome to generate the above boiler plate files.

**Comment by alexcrichton** [comment]
Hm perhaps! I'd ideally prefer to avoid being too opinionated towards webpack or how a project should be structured, currently the layout is largely just how the exmaples work but is no means for sure the best practice!

**Comment by alexcrichton** [comment]
I'm gonna close this in favor of wasm-pack, but if that feels in error we can of course continue discussing!
