### ISSUE TITLE
Accessing window.indexedDB fails because it's not known in prototype

### ISSUE THREAD

**Issue by krampenschiesser** [rustwasm/wasm-bindgen#904]
I am trying to access the window.indexedDB via wasm-pack and wasm-bindgen.

cargo.toml contents:
```
wasm-bindgen = "0.2.23"
js-sys = "0.3.0"
web-sys = { version = "0.3.0", features = ["IdbFactory","Window","IdbOpenDbRequest"] }
```

Code:
```
    web_sys::window().unwrap().indexed_db().unwrap().unwrap().open("test").unwrap();
```

Running it I get the following error:
```
Error importing `index.js`: Error: "descriptor for id='indexedDB' not found"
```

Looking into the javascript code I see:
```
GetOwnOrInheritedPropertyDescriptor(Window.prototype, 'indexedDB')

function GetOwnOrInheritedPropertyDescriptor(obj, id) {
    while (obj) {
        let desc = Object.getOwnPropertyDescriptor(obj, id);
        if (desc) return desc;
        obj = Object.getPrototypeOf(obj);
    }
    throw new Error(`descriptor for id='${id}' not found`);
}
```

However executing ```Object.getOwnPropertyDescriptor(window.prototype, "indexedDB");``` returns undefined. 
Where as ```Object.getOwnPropertyDescriptor(window,"indexedDB")``` returns the wanted descriptor.
My javascript knowledge is at its limits here. Maybe for window we should not access the prototype?

**Comment by alexcrichton** [comment]
Thanks for the report! This should be fixed in https://github.com/rustwasm/wasm-bindgen/pull/911
