### ISSUE TITLE
Why do the functions in js-sys take string arguments as &str but return them as JsString?

### ISSUE THREAD

**Issue by Migi** [rustwasm/wasm-bindgen#912]
This may have been discussed somewhere already but I tried searching for it and didn't find anything.

In `js-sys`, the bindings of all functions that take a string as an argument take a `&str` and the bindings of all functions that return a string return a `JsString`. For example, `encodeURI` has the binding

```rust
#[wasm_bindgen(js_name = encodeURI)]
pub fn encode_uri(decoded: &str) -> JsString;
```

The issue with doing it like this is: **this makes it impossible to take a string that you receive from one function call and to pass it into a different call without quite a bit of overhead**: as far as I can tell, you have to convert the `JsString` into a Rust `String`, which does both an allocation and a UTF-8 encoding of the string, and then pass that `String` as a `&str` to Javascript, which decodes the UTF-8 string again.

In contrast, if the functions in `js-sys` would take a `&JsString` as an argument, then no such en-/decoding of UTF-8 strings is necessary. You just take the `JsString` you receive and pass it on.

Don't get me wrong, I'm not necessarily advocating that we should change `&str` to `&JsString` everywhere in `js-sys` (and `web-sys`?). That would be a major breaking change. Instead, I'd like to know why the decision was made to do it like this. I'm writing my own bindings for some JS libraries and I have to decide myself between taking strings as `&str` or `&JsString`, or returning them as `JsString` or as `String`.

I understand that taking strings as `&JsString` instead of `&str` would have the following downsides:

* It would hurt the ergonomics for the case of passing a regular Rust string. You'd have to use `into()` instead of being able to pass Rust strings directly (e.g. `encode_uri("test")` would have to be changed to `encode_uri(&"test".into())`). But if I understand correctly (from comments such as [this one](https://github.com/rustwasm/wasm-bindgen/issues/582#issuecomment-408688177)), ergonomics is not really a priority for `js-sys`.

* It would also come with a (small) performance decrease for the case of passing regular Rust strings to Javascript: The `.into()` call creates a temporary `JsString`, and the JS string is put on the slab before being passed into the function call. This `JsString` temporary and slab allocation are avoided when taking strings by `&str`. How large this performance decrease would be, I don't know. It seems like it would be very small, but we can't know without benchmarking. But if it's not small, then I'm confused as to why the methods in `js-sys` return a `JsString` instead of a `String`: it causes the same kind of avoidable `JsString` temporary and slab-allocation. Is the difference that return values can go unused, while function arguments are always used?

Is that it? Are there any other downsides that I'm not seeing? Has there been any discussion about this topic that I haven't found?

**Comment by fitzgen** [comment]
Implementers / standardization is focused on building blocks that will be necessary for it: working with references to external GC'd types from within wasm. For example, see https://blog.benj.me/2018/07/04/mozilla-2018-faster-calls-and-anyref/

Thanks!
