### ISSUE TITLE
Wasm bindgen code does not compile if i include "use std::borrow::BorrowMut;"

### ISSUE THREAD

**Issue by mandeepbrar** [rustwasm/wasm-bindgen#919]
Structs containing wasm_bindgen attribute stop compiling if BorrowMut is included 
```
use std::borrow::BorrowMut;
```

Receive the following error pointing to #[wasm_bindgen]

error[E0283]: type annotations required: cannot resolve `std::boxed::Box<wasm_bindgen::__rt::WasmRefCell<application::Mystruct>>: std::borrow::BorrowMut<_>`

Struct in the example was pretty simple 

```
#[wasm_bindgen]
struct MyStruct {
 mystr: String
}
```

**Comment by alexcrichton** [comment]
What a bizarre bug! Should be fixed in https://github.com/rustwasm/wasm-bindgen/pull/920
