### ISSUE TITLE
Test TypeScript output on CI

### ISSUE THREAD

**Issue by alexcrichton** [rustwasm/wasm-bindgen#922]
There have been a number of TypeScript-related regressions recently like https://github.com/rustwasm/wasm-bindgen/issues/917, and while we used to test TypeScript on CI we no longer do! We should figure out how to set up a dedicated builder focused on testing the TypeScript output of wasm-bindgen!

**Comment by emk** [comment]
And as mentioned in that issue, if you'd like, I can try to take a look at setting up an example TypeScript+Rust+Webpack project which can be built using `npm run something` sometime this coming weekend.

**Comment by alexcrichton** [comment]
A nice idea! I think it's good to have a test like that but for this repository we can probably just stick to the vanilla typescript compiler and a sample project 

I'd be wary of coupling to too many things outside of wasm bindgens control

**Comment by emk** [comment]
My recent experience is that if I just check run `wasm-bindgen` and `tsc`, there's still a really impressive number of ways that everything can silently produce broken output. (And it feels like I've hit most of them getting this to work.) In particular, the async module loading code requires cooperation from all 3 of `wasm-bindgen`, `tsc`'s `esnext` support, and `webpack`, and it's easy for one tool to be silently out of alignment with the other 2.

In a perfect world, _something_ would run `webpack` and make sure that everything all hooks up together. Basically, my goal here is to be able to upgrade `wasm-bindgen` and expect everything to still work. But there's an excellent argument to be made that this is an "integration" or "acceptance" test, and that as such, maybe it belongs in a new `rust-webpack-typescript-template` repository somewhere.

Still, I'd love for `wasm-bindgen` to "just work" with TypeScript. And I suspect that it may be hard to guarantee that without a good end-to-end test somewhere.

What would be the most useful way for me to approach this goal?

**Comment by alexcrichton** [comment]
Oh well I think the priority here is getting *something* tested, so I'm fine getting that done however and then we can tweak it as necessary!
