### ISSUE TITLE
Some issues with the examples

### ISSUE THREAD

**Issue by lnicola** [rustwasm/wasm-bindgen#925]
This might not be up to date, so I'll have to test it again, but I noticed some problems with the examples. I tried to take notes, but I can no longer understand what I meant :sob:.

- ~~`asm.js`: coldn't test (something about `binaryen` not working for me?)~~ `wasm2js` works, not sure if it's the same
- ~~`closures`: invalid date~~ works
- ~~`comments`: validation error after add~~ gone
- ~~`dom`, `math` etc.: they run twice (check the console); probably all of them do that~~ works
- ~~`fetch`: missing npm serve~~ works
- `guide-supported-types-examples`: `SomeJsType` missing
- `no_modules`: does nothing
- `webaudio`: ~~uses webpack-serve instead of webpack-dev-server, doesn't work~~ works with some build warnings
- `webgl`: some build warnings
- ~~`paint`: doesn't build (`Closure::new`)~~ fixed now

**Comment by alexcrichton** [comment]
Thanks for the report! I think actually almost all of these have been fixed now at this point, mind double checking to make sure though?

**Comment by lnicola** [comment]
Sure, I was planning to take a look one of these days.

**Comment by lnicola** [comment]
I updated the list with the current status.

**Comment by alexcrichton** [comment]
Thanks for the update!

Those should be fixed by https://github.com/rustwasm/wasm-bindgen/pull/927 and https://github.com/rustwasm/wasm-bindgen/pull/926, minor mistakes!

The `guide-supported-types-examples` I think is mostly for the book rather than running manually

**Comment by lnicola** [comment]
> The `guide-supported-types-examples` I think is mostly for the book rather than running manually

I thought so, but since it _can_ be run, it might be surprising for someone.

The others are fixed now, thanks.
