### ISSUE TITLE
[question] Handling DOMContentLoaded

### ISSUE THREAD

**Issue by lnicola** [rustwasm/wasm-bindgen#935]
Shouldn't [this](https://github.com/lnicola/wasm-domcontentloaded) code work?

I was able to handle other events with that pattern, but the handler in that example never gets called.

**Comment by alexcrichton** [comment]
I think this may not be how event listeners work? It looks like the wasm file is loaded long after the `DOMContentLoaded` event is fired, and it looks like attaching an event listener after an event is fired doesn't fire it

**Comment by lnicola** [comment]
Ugh, I forgot about `Document.readyState`. Sorry :confused:.
