### ISSUE TITLE
Building web-sys 3.1 fails with Windows

### ISSUE THREAD

**Issue by katis** [rustwasm/wasm-bindgen#943]
The line at:

https://github.com/rustwasm/wasm-bindgen/blob/3001d1e9739ea6cda9b56960c4aa325776804926/crates/web-sys/src/lib.rs#L30

has the wrong separator for Windows and build fails with error:

```
   Compiling web-sys v0.3.1
error: couldn't read "\\\\?\\D:\\code\\image-diff\\target\\wasm32-unknown-unknown\\release\\build\\web-sys-e7f8c3d13d9222a2\\out/bindings.rs": The filename, directory name, or volume label syntax is incorrect. (os error 123)
  --> C:\Users\jonik\.cargo\registry\src\github.com-1ecc6299db9ec823\web-sys-0.3.1\src\lib.rs:30:1
   |
30 | include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by alexcrichton** [comment]
Thanks for the report, can't say I've run into this before? Out of curiosity do you have `CARGO_TARGET_DIR` set to this UNC path?

In any case this should be fixed in https://github.com/rustwasm/wasm-bindgen/pull/944

**Comment by katis** [comment]
I haven't set `CARGO_TARGET_DIR` explicitly, just tried out wasm-pack with web-sys on my Windows machine.

**Comment by alexcrichton** [comment]
Unusual! I'm curious where the UNC path got introduced as Cargo doesn't do it by default, but regardless of where #944 should fix this.
