### ISSUE TITLE
Allow Serialize/Deserialize into a `JsValue`

### ISSUE THREAD

**Issue by alexcrichton** [rustwasm/wasm-bindgen#96]
We should have an option to convert an arbitrary object to a `JsValue` via `Serialize` an `Deserialize`. It may not be quick but it's often quite useful!

**Comment by udoprog** [comment]
I want to take a stab at this and have a couple of questions.

Would you be in favor changing `JsValue` into an enum to make it easier to match based on its type during serialization?

It's not apparent how we deal with objects and arrays right now (if at all). Would you mind providing some instructions for how that would work?

**Comment by alexcrichton** [comment]
I've posted an initial pass of this API at https://github.com/rustwasm/wasm-bindgen/pull/171
