### ISSUE TITLE
DataView endian parameters

### ISSUE THREAD

**Issue by katis** [rustwasm/wasm-bindgen#960]
DataView doesn't support the `littleEndian` [boolean parameter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/setInt32), and as such everything is written as big endian.

I could do this as a practice issue next week, but I'd like to know if there should be a new method (`set_int32_endian` or something) or just add the boolean parameter to the end for every method that needs it?

**Comment by alexcrichton** [comment]
Thanks for the report! It should definitely be ok to simply add new methods here which exposes the boolean parameters, and tacking on `_endian` to the end sounds good to me as well!

If you need any help with adding these just let us know!

**Comment by katis** [comment]
Fixed with https://github.com/rustwasm/wasm-bindgen/pull/966
