### ISSUE TITLE
How to pass an array of objects to WebAssembly and convert it to a vector of structs with wasm-bindgen?

### ISSUE THREAD

**Issue by gregorredinger** [rustwasm/wasm-bindgen#964]
It's possible to pass an array of integers like this:

    const js = import("./webassembly_rust");
    let array_nums = [1,2,3,4,5,6,7,8,9];
    
    js.then(js => {
      js.test( array_nums );
    }); 

to WebAssembly and save it in a vector like this:

    
    extern crate serde_json;
    extern crate wasm_bindgen;
    
    use wasm_bindgen::prelude::*;
    
    #[macro_use]
    extern crate serde_derive;
    
    #[wasm_bindgen]
    pub fn test(array: JsValue) {
        let elements: Vec<u32> = array.into_serde().unwrap();
    }

It's also possible to pass a single object like this:

    const js = import("./webassembly_rust");
    let jsObject = {name: "hello world", id: "99", parent_id: "11"};
    
    js.then(js => {
      js.test( jsObject );
    }); 

to WebAssembly and save it as a `Element` struct like this:

    
    extern crate serde_json;
    extern crate wasm_bindgen;
    
    use wasm_bindgen::prelude::*;
    
    #[macro_use]
    extern crate serde_derive;
    
    #[derive(Serialize, Deserialize)]
    pub struct Element {
        name: String,
        id: String,
        parent_id: String,
    }
    
    #[wasm_bindgen]
    pub fn test(js_object: &JsValue) {
        let element: Element = js_object.into_serde().unwrap();
    }

The next thing I tried is to pass an array of objects like this:

    const js = import("./webassembly_rust");
    let arrayOfObjects = [
      {name: "hello world", id: "99", parent_id: "88"},
      {name: "hello world2", id: "88", parent_id: "12"},
      {name: "hello world3", id: "77", parent_id: "88"}
    ]
    
    js.then(js => {
      js.test( arrayOfObjects );
    }); 

to WebAssembly and save it as a vector of `Element` structs like this:

    
    extern crate serde_json;
    extern crate wasm_bindgen;
    
    use wasm_bindgen::prelude::*;
    
    #[macro_use]
    extern crate serde_derive;
    
    #[derive(Serialize, Deserialize)]
    pub struct Element {
        name: String,
        id: String,
        parent_id: String,
    }
    
    #[wasm_bindgen]
    pub fn test(js_objects: &JsValue) {
        let elements: Vec<Element> = js_objects.into_serde().unwrap();
    }

This compiles, but when I run this code I get the error:

    func $__rust_start_panic (param i32) (result i32)
      unreachable
      unreachable
    end

![screenshot_promise_rejection_error][1] 

[1]: https://i.stack.imgur.com/nkw9x.png

Passing an array of objects just filled with numbers like this:

        const js = import("./webassembly_rust");
        let arrayOfNumObjects = [
            {name: 1, id: 2, parent_id: 3 },
            {name: 1, id: 2, parent_id: 3 },
            {name: 1, id: 2, parent_id: 3 }
        ]
        
        js.then(js => {
          js.test( arrayOfNumObjects );
        }); 

to webassembly is possible, when the `Element` struct contains only `u32` values.

    extern crate wasm_bindgen;
    extern crate serde_json;
    use wasm_bindgen::prelude::*;
    
    #[macro_use]
    extern crate serde_derive;
    
    #[derive(Serialize, Deserialize)]
    pub struct Element {
        name: u32,
        id: u32,
        parent_id: u32,
    }
    
    #[wasm_bindgen]
    pub fn test( js_objects: &JsValue ) {
        let elements: Vec<Element> = js_objects.into_serde().unwrap();
    }

It seems like the problem is caused by the String type in the `Element` struct.

What did I do wrong? 

I found the following articles, but I can't find a solution for my problem in them:

* [Serializing and Deserializing Arbitrary Data Into and From `JsValue` with Serde](https://rustwasm.github.io/wasm-bindgen/reference/arbitrary-data-with-serde.html)

    This explains how to convert a JavaScript object to a struct, but not how to convert an array of objects to a vector of structs.

* [js_sys crate ](https://rustwasm.github.io/wasm-bindgen/api/js_sys/struct.Array.html#method.entries)

    This crate allows to use JavaScript types like arrays or objects in Rust, but this is not what I want. I want to convert JavaScript values into their Rust counterparts. This crate only allows to use JavaScript inline in Rust, as far as I understand... and this isn't as fast as using just Rust.

**Comment by alexcrichton** [comment]
Thanks for the report! I'm also surprised that `into_serde` isn't working here. Could you try perhaps to use `console_error_panic_hook` to get the panic message from Rust? That may help debug a bit more as well. Failing that I can certainly help dig in to see what's going on!

**Comment by gregorredinger** [comment]
Hi, i have no idea why but it seems to work now. Today i tried to get the error message from rust via `console_error_panic_hook` like you suggested, but i didn't get a error.

I passed the array of objects from my js file:
```
const js = import("./webassembly_rust")

let arrayOfObjects = [
  {name: "hello world", id: "99", parent_id: "88"},
  {name: "hello world2", id: "88", parent_id: "12"},
  {name: "hello world3", id: "77", parent_id: "88"}
]

js.then(js => {
  js.test(arrayOfObjects);
}); 
```
to rust

```
extern crate wasm_bindgen;
extern crate serde_json;
use wasm_bindgen::prelude::*;
extern crate console_error_panic_hook;

#[macro_use]
extern crate serde_derive;

#[derive(Serialize, Deserialize)]
pub struct Element {
    name: String,
    id: String,
    parent_id: String,
}

#[wasm_bindgen]
pub fn test( js_objects: &JsValue )  {
    console_error_panic_hook::set_once();
    let elements: Vec<Element> = js_objects.into_serde().unwrap();
}
```
but the error is gone.

**Comment by alexcrichton** [comment]
Interesting! I wonder if the code may have changed in the meantime by accident? Or maybe an accidentaly diagnosis of a bug? In any case looks like it's good to go now, so I'm gonna close this. If it comes up again though let us know!

**Comment by FilipLitwora** [comment]
I know this is old but i copied your code and i get following error : 
```
let elements: Vec<Element> = js_objects.into_serde().unwrap();
   |                                            ^^^^^^^^^^ method not found in `&wasm_bindgen::JsValue`

```

**Comment by FilipLitwora** [comment]
So I thought I forgot to add dependencies to cargo.toml and i was right, so i added 
```
[dependencies.wasm-bindgen]
version = "^0.2"
features = ["serde-serialize"]
```

but i get an error : 

```
Caused by:
  could not parse input as TOML

Caused by:
  duplicate key: `wasm-bindgen` for key `dependencies` at line 55 column 1
```

My cargo.toml file : 


```
`
# You must change these to your own details.
[package]
name = "rust-webpack-template"
description = "My super awesome Rust, WebAssembly, and Webpack project!"
version = "0.1.0"
authors = ["You <you@example.com>"]
categories = ["wasm"]
readme = "README.md"
edition = "2018"

[lib]
crate-type = ["cdylib"]
[profile.release]
# This makes the compiled code faster and smaller, but it makes compiling slower,
# so it's only enabled in release mode.
lto = true
debug = true

[features]
# If you uncomment this line, it will enable `wee_alloc`:
#default = ["wee_alloc"]

[dependencies]
# The `wasm-bindgen` crate provides the bare minimum functionality needed
# to interact with JavaScript.
wasm-bindgen = "0.2.45"
js-sys = "0.3.33"
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0.32"

version = "0.3.22"
features = ["console"]


[dependencies.wasm-bindgen]
version = "^0.2"
#features = ["serde-serialize"]


# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so it's only enabled
# in debug mode.
[target."cfg(debug_assertions)".dependencies]
console_error_panic_hook = "0.1.5"

# These crates are used for running unit tests.
[dev-dependencies]
wasm-bindgen-test = "0.2.45"
futures = "0.1.27"
js-sys = "0.3.22"
wasm-bindgen-futures = "0.3.22"


`
```
