### ISSUE TITLE
Can't run the wasm-bindgen tests on Windows

### ISSUE THREAD

**Issue by Migi** [rustwasm/wasm-bindgen#967]
I'm on Windows (64 bit). I tried to run the current wasm-bindgen tests, and didn't really get it to work.

If I set the environment variable NO_HEADLESS to 1, then run `cargo test --target wasm32-unknown-unknown` then go to http://localhost:8000/, then I get as output:

> running 1 test
> 
> test headless::works ... ok
> 
> test result: ok. 1 passed; 0 failed; 0 ignored

And that's it. Just 1 test. Nothing in the console output either. Changing the assert in some of the tests doesn't make this 1 test fail, so I don't think it's running all the tests.

If I download either Geckodriver's 64 bit release or Chromedriver's 32 bit release, and then (after setting either the GECKODRIVER or CHROMEDRIVER environment variable) run `cargo test --target wasm32-unknown-unknown`, I do get more output, but it eventually fails with the error "BigInt64Array is not defined":

![output](https://user-images.githubusercontent.com/706561/47029643-53f46980-d16c-11e8-919e-9aad616b343f.png)

Geckodriver's 32 bit release runs into a "permission denied" error:

![output2](https://user-images.githubusercontent.com/706561/47029799-b483a680-d16c-11e8-90e3-242ad0ea084d.png)

EDIT: I should mention that I also didn't always get the same output. Sometimes even running the same `cargo test --target wasm32-unknown-unknown` command twice in a row, without changing anything, gave different output and a different error.

**Comment by alexcrichton** [comment]
Thanks for the report! I think that the first issue is with Node where we need a pretty recent version of Node to have `BigInt64Array`. For the latter are you sue that geckodriver/firefox are configured right? 

(I'm not sure how to configure it myself...)

**Comment by Migi** [comment]
That was it. I was running the long-term-support version of Node (v8.12.0). Updating to the latest version of Node (v10.12.0) fixed it so I can run headless tests now.

For the others, I may indeed have things configured wrongly. I have no idea. I read [this page](https://rustwasm.github.io/wasm-bindgen/contributing/testing.html) in the guide and [this page](https://github.com/rustwasm/wasm-bindgen/blob/master/crates/test/README.md) and [this page](https://rustwasm.github.io/wasm-bindgen/wasm-bindgen-test/index.html). That's it. I have very little experience with Node and headless browsers.

**Comment by earthengine** [comment]
Please reopen this issue (or create a new one?) since the experienced the same error message for a different reason.

The error message was

```text
could not execute process `C:\Users\User Name\.cargo\bin\wasm-bindgen-test-runner.exe ...
```
(Note the whitespace inside the user name)
If manually copy the command in the message and remove the path parts, like
```text
> wasm-bindgen-test-runner.exe ...
```
it runs successfully.
```

**Comment by Liamolucko** [comment]
> The strange thing is, although in `cargo.toml` I have
> 
> ```toml
> [build]
> target = 'wasm32-unknown-unknown'
> 
> [target.wasm32-unknwon-unknown]
> runner = 'wasm-bindgen-test-runner''
> ```
> 
> It does not work.

That's because those settings go in `.cargo/config.toml`; putting them in `Cargo.toml` does nothing.

**Comment by earthengine** [comment]
@Liamolucko I was exactly doing that; so I said it picks up the "[build]" settings, not the “[target...]" settings.

**Comment by Liamolucko** [comment]
Did you also already fix the typo in `[target.wasm32-unknwon-unknown]` (to `[target.wasm32-unknown-unknown]`)?

**Comment by earthengine** [comment]
@Liamolucko Arr goo catch. Seems like this is the issue.
