### ISSUE TITLE
Webpack builds become very slow for large wasm files

### ISSUE THREAD

**Issue by chinedufn** [rustwasm/wasm-bindgen#973]
I'm working on an application where after running a debug build through `wasm-bindgen` that `wasm` file is around 9Mb.

I was originally using webpack (mostly because it seems to be recommended by `rustwasm`) but as my `wasm` file grew build times got slower and slower (I have almost no JS code).

Eventually when my `wasm` file hit `9Mb` my webpack builds (in both watch mode as well as a fresh build) were taking 50+ seconds.

Do I know exactly why things go so slow? Nope

Do I know exactly why my debug bundle is so large? Nope but I'll look into it eventually..

---

Mainly posting this here in case someone runs into the same problem and searches this repository for some answers.

I ended up just using `--no-modules` and calling it a day for now.

---

Immediately closing this issue as I'm not sure if there is anything actionable right now and just want to save others time if they run into the same problem.

**Comment by alexcrichton** [comment]
Yes thanks for the issue @chinedufn! I'd be curious to at least diagnose where the slowness is coming from, you're probably not the last person to run into this! Do you have some example code/configuration you could share that we could help dig in to?

**Comment by xtuc** [comment]
The transformations themselves are at AST level and only some parts of the binary are actually replaced (no full reprint).

I bet the slowdown comes from the decoder, there's room for improvement, like lazy decoding or concurrency.

The clang wasm port is fairly big (30M or so) I can link it here if you want to test, just bundle it.

**Comment by chinedufn** [comment]
The codebase is private but it only has a few dependencies so if it would help I can try to just make a clean project that uses those dependencies and see if I can create a large build and reproduce the slowness.

---

So I guess if bundling the clang wasm port that @xtuc mentions doesn't lead to minute+ builds I can try and throw something together for ya @alexcrichton ?

**Comment by alexcrichton** [comment]
Oh so if Webpack is known to be slow on large modules then it may be best to move this issue to a different location, but I'd also want to be sure to rule out wasm-bindgen because it's also possible that excessive time is taken somewhere in wasm-bindgen or wasm-pack

**Comment by chinedufn** [comment]
I'm not using wasm-pack and the 50+ seconds is all webpack, 

My understanding is that the only way that wasm-bindgen could be the problem is if it was unnecessarily emitting a bunch of stuff that webpack needed to sift through..?

If that sounds like an oversimplification, it is because I don't know the exact details of what's happening under the hood.

---

So okay - maybe I'll close this and whenever I look back into figuring out why my debug wasm bundle (post wasm-bindgen-cli) is 9Mb I'll have more specific / targeted questions that will be actionable.

Let me know if you disagree with this approach!

Cheers and thanks!

**Comment by Dig-Doug** [comment]
I also ran into this issue, hopefully https://github.com/xtuc/webassemblyjs/pull/1140 fixes it.
