### ISSUE TITLE
Add example of using request animation frame

### ISSUE THREAD

**Issue by chinedufn** [rustwasm/wasm-bindgen#976]
After searching the web sys docs and wasm-bindgen issues I can't seem to find anything about request animation frame.

Months ago, before web-sys, I tried to use RAF via an extern call and ran into some closure issues (don't remember what exactly but likely just me misunderstanding things). 

Ended up giving up and just calling some JS function from my Rust code that handled my RAF loop for me.

Now that I'm circling back to this.. does the RAF API not exist in web-sys for some reason? Or does it actually exist and I just didn't find it?

**Comment by alexcrichton** [comment]
I think that [`Window::request_animation_frame`](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.Window.html#method.request_animation_frame) may be the equivalent you're looking for? Coupled with the [closures example](https://rustwasm.github.io/wasm-bindgen/examples/closures.html) it's hopefully enough to go off!

**Comment by chinedufn** [comment]
Ah... silly me was searching `requestAnimationFrame`...... Thanks!

**Comment by gregtatum** [comment]
For future readers, I haven't actually run this example code, but it should be the gist of what needs to happen to do a requestAnimationFrame loop.

```rust
extern crate wasm_bindgen;
extern crate web_sys;

use wasm_bindgen::JsCast;

#[wasm_bindgen]
pub struct ClosureHandle(Closure<FnMut()>);

#[wasm_bindgen]
pub fn run() -> ClosureHandle {
    let cb = Closure::wrap(Box::new(move || {
        web_sys::console::log_1(&"raf called".into());
    }) as Box<FnMut()>);

    let window = web_sys::window().unwrap();
    window.request_animation_frame(
        // Note this method call, which uses `as_ref()` to get a `JsValue`
        // from our `Closure` which is then converted to a `&Function`
        // using the `JsCast::unchecked_ref` function.
        cb.as_ref().unchecked_ref(),
        1_000,
    );

    // Return the ClosureHandle so the lifetime of the closure will be correct, otherwise
    // this code will panic as the closure will have been removed already.
    ClosureHandle(cb)
}
```

**Comment by gregtatum** [comment]
It escapes me how to make a `requestAnimationFrame` loop though...

**Comment by fitzgen** [comment]
We should add an example for working with `requestAnimationFrame`

**Comment by dakom** [comment]
Thanks to the work at https://github.com/clinuxrulz/sodium-rust-push-pull - here's a starter template demoing an alternative method - using Streams as a hook for sending update events:

https://github.com/dakom/hello-rust-sodium-wasm

(I imagine the stream could also be sent to via a local window.request_animation_frame, the round-tripping here isn't totally necessary)

**Comment by chinedufn** [comment]
@fitzgen any quick points on how to implement a `requestAnimationFrame` loop in the meantime?

To date I've just been handling `RAF` on the JS side but would be nice to move that to Rust.

**Comment by fitzgen** [comment]
@chinedufn 

The example that @gregtatum posted upthread looks right to me. Basically, something like this (untested):

```rust
let f = Closure::wrap(Box::new(move || {
    // do stuff...
})  as Box<FnMut()>);

let window = web_sys::window().unwrap();
window.request_animation_frame(f.as_ref().unchecked_ref());
f.forget();
```

Strawman proposal for a useful example, if you'd like to make a PR: incrementing a number in a RAF loop and rendering it into the body's `textContent`.

**Comment by chinedufn** [comment]
@fitzgen I think what @gregtatum and I mean is that running RAF once is as easy as what you're saying, but running a RAF loop appears difficult (which is why I've to date just done it on the JS side)

i.e. what's the web-sys equivalent of the following JS?:

```
function draw () {
  console.log('drawing a frame')
  window.requestAnimationFrame(draw)
}

draw()
```

Notice that this will loop forever, throttled by RAF

**Comment by mclucario** [comment]
I'm new to rust and I am currently struggling to get my variables into a raf loop. Could you guys add an explanation for that?

**Comment by g-braeunlich** [comment]
Is there also an example on how to use `requestAnimationFrame` with a timestamp argument as explained [here](https://developer.mozilla.org/en-US/docs/Web/API/Window/requestAnimationFrame#examples)?

**Comment by daxpedda** [comment]
In general you are free to define your own parameters in any passed `Closure`, the generic types are erased when converting it to a `Function`.
