### ISSUE TITLE
Instantiate Struct from object

### ISSUE THREAD

**Issue by DanielRamosAcosta** [rustwasm/wasm-bindgen#981]
I'm trying to instantiate a complex Struct in the JS side with lots of attributes. Is there an easy way instantiate it? maybe something like this?

```rust
#[wasm_bindgen]
pub struct BigUserStruct {
    username: String,
    email: String,
    // ...
}
```

And at the JS side do something like this:

```js
const user = new BigUserStruct({username: "Sam1", email: "sam@sam.com", /* ... */ })
```

**Comment by alexcrichton** [comment]
To support this you'd probably want to do something like:

```rust
#[wasm_bindgen]
impl BigUserStruct {
    #[wasm_bindgen(constructor)]
    pub fn new(obj: &js_sys::Object) -> BigUserStruct {
        // ...
    }
}
```

and then accessing the fields of `obj` can be done with [`Reflect::get`](https://docs.rs/js-sys/0.3.2/js_sys/struct.Reflect.html#method.get) perhaps?

**Comment by Pauan** [comment]
@alexcrichton Although that works, I think he was just asking for a more convenient way to create the Rust struct on the JS side.

If wasm-bindgen auto-generated a `fromObject` method, he could do this in JS:

```js
BigUserStruct.fromObject({username: "Sam1", email: "sam@sam.com", /* ... */ });
```

The `fromObject` method would take the object, access its properties in JS, and then somehow translate those values into a Rust struct:

```js
class BigUserStruct {
    static fromObject(obj) {
        let username = obj.username;
        let email = obj.email;
        return new BigUserStruct(wasm_bindgen_magic_goes_here(username, email));
    }

    ...
}
```

**Comment by DanielRamosAcosta** [comment]
Yes, exactly what @Pauan said

**Comment by alexcrichton** [comment]
Ok thakns for the clarification @DanielRamosAcosta, if this is a feature request though I'd be more inclined to do this via a Rust macro rather than a builtin "magical method". You could also use serde here I believe!

**Comment by DanielRamosAcosta** [comment]
I'm closing this, as it's 3 years old now.
