### ISSUE TITLE
Safari headless test fails due to non-200 status code in Safari 12

### ISSUE THREAD

**Issue by C-Saunders** [rustwasm/wasm-bindgen#983]
(Migrated from https://github.com/rustwasm/wasm-pack/issues/418)

Running `cargo test --target wasm32-unknown-unknown` with a fresh, unmodified clone of the repository has a failing test in Safari 12.
```
Running headless tests in Safari with `safaridriver`
driver status: signal: 9
error: non-200 response code: 500
{"value":{"error":"session not created","message":"Request body does not contain required parameter 'capabilities'.","stacktrace":""}}
```

The issue seems to be that with Safari 12, by default, supports the W3C driver protocol, rather than the Selenium JSON protocol, as described in [this Apple documentation](https://developer.apple.com/documentation/webkit/macos_webdriver_commands_for_safari_12_and_later).

I made an update that gets this working that you can see [in this commit](https://github.com/C-Saunders/wasm-bindgen/commit/60a23bf614582d4b506d1d58ca927ccb48c6b374), but am concerned about dropping support for Safari < 12.

Please let me know if you'd like me to open a pull request with the above change, investigate further regarding support for older versions, or any other feedback.

Thanks!

**Comment by henriiik** [comment]
I ran into the same problem, it is also possible work around by passing the `--lagcy` flag to safari driver.

ex.

```sh
SAFARIDRIVER_ARGS=--legacy cargo test --target wasm32-unknown-unknown
```

**Comment by alexcrichton** [comment]
Thanks for the report and links @C-Saunders! Also thanks for the tip @henriiik, this all makes sense!

I've posted a fix for this at https://github.com/rustwasm/wasm-bindgen/pull/991 to hopefully enable us to both work in legacy mode and w3c
