### ISSUE TITLE
[Question] How do I remove event listener?

### ISSUE THREAD

**Issue by bokuweb** [rustwasm/wasm-bindgen#993]
Hi:) I have a question. How do I remove event listener?
When I tried to remove event listener I met some errors.

``` Rust
pub fn run() {
    let window = web_sys::window().expect("no global `window` exists");
    let document = window.document().expect("should have a document on window");
    let body = document.body().expect("document should have a body");

    let main = &document
        .query_selector(&".main".to_owned())
        .unwrap()
        .unwrap();

    let handler = Box::new(|| {
        web_sys::console::log_1(&"click".into());
    }) as Box<Fn()>;
    let cb: Closure<Fn()> = Closure::wrap(handler);
    (main.as_ref() as &web_sys::EventTarget)
        .add_event_listener_with_callback(&"click".to_owned(), cb.as_ref().unchecked_ref())
        .unwrap();
    cb.forget();
    // bellow code is meaningless sample code
    (main.as_ref() as &web_sys::EventTarget)
        .remove_event_listener_with_callback(&"click".to_owned(), cb.as_ref().unchecked_ref()) // ---> cb is already moved by forget.
        .unwrap();
}
```

This is because `cb`'s ownership is already moved `forget`.
What should I do to remove this event listener?

Then I did some investigation to solve it, i bellow code.
This code does not call `forget`, but it works fine.
Why does not this need `forget` ??? Why is not closure dropped???

https://github.com/utkarshkukreti/draco/blob/master/src/element.rs#L522-L531

**Comment by limira** [comment]
> Why does not this need forget ??? Why is not closure dropped???

Because of the last line of the code you linked to:
https://github.com/utkarshkukreti/draco/blob/master/src/element.rs#L531

Storing it in `self.closure` prevent it from dropping unless that `self` get dropped!

**Comment by alexcrichton** [comment]
A good question here! Could this perhaps be a case where the `JsValue` from `cb.as_ref()` is stored separately from the `Closure<T>` itself? That way you can pass it to `removeEventListener` later on and deouple it from the lifetime of the closure.

Although I may be missing some background as well? Or I may be missing some context as to why `forget` is being used and such.

**Comment by bokuweb** [comment]
@limira @alexcrichton Thanks for your quick response. I'll give it a try :)

**Comment by bokuweb** [comment]
Sorry, I was mistaken. `forget` is called here.

https://github.com/utkarshkukreti/draco/blob/dc6a74195f5c2c2fd5676a4207554ad1ae9677b8/src/mailbox.rs#L35

**Comment by bokuweb** [comment]
I am glad if an example of remove_event_listener is added. Close for now. thanks :)

**Comment by bokuweb** [comment]
@alexcrichton sorry.. I can not find better solution yet.I tried to store `cb.as_ref()` as `&JsValue` to use remove listener later.However it required `static` lifetime because it is pointer. For now, I forced lifetime with `mem::transmute::<&JsValue, &'static JsValue>(cb.as_ref());` to static, because it is already leaked. It made the compilation successful, but it is so ugly..Do you have any idea to solve this.

I did some investigation. But It seems that nobody manage this properly..? 🤔 

https://github.com/rustwasm/wasm-bindgen/blob/master/examples/todomvc/src/view.rs#L120

I think If the `Callback.forget() ` return ownership, it solve this issue. But was it impossible?

Thanks.

``` Rust
pub struct Listener {
    cb: RefCell<Option<&'static JsValue>>,
}

pub fn run() {
    let mut listner = Listenr {
        cb: RefCell::new(None)
    }
    ...
    let handler = Box::new(|| {
        web_sys::console::log_1(&"click".into());
    }) as Box<Fn()>;
    let cb: Closure<Fn()> = Closure::wrap(handler);
    let mut cb_ref: &'static JsValue;
    unsafe {
      cb_ref = mem::transmute::<&JsValue, &'static JsValue>(cb.as_ref());
    }
    (main.as_ref() as &web_sys::EventTarget)
        .add_event_listener_with_callback(&"click".to_owned(), cb_ref.unchecked_ref())
        .unwrap();
    listner.cb.replace(Some(cb_ref));
    cb.forget();
    ...
}
```

**Comment by Pauan** [comment]
@bokuweb Why are you using `cb.forget()`?

The purpose of `cb.forget()` is to keep the closure alive *forever* (so it will *never* be removed).

If you simply don't call `cb.forget()` then it should work:

```rust
pub fn run() {
    let handler = Box::new(|| {
        web_sys::console::log_1(&"click".into());
    }) as Box<Fn()>;

    let cb: Closure<Fn()> = Closure::wrap(handler);

    (main.as_ref() as &web_sys::EventTarget)
        .add_event_listener_with_callback(&"click".to_owned(), cb.as_ref().unchecked_ref())
        .unwrap();

    ...

    (main.as_ref() as &web_sys::EventTarget)
        .remove_event_listener_with_callback(&"click".to_owned(), cb.as_ref().unchecked_ref())
        .unwrap();
}
```

The above code registers the listener and then immediately removes it.

You probably don't want to remove it immediately, in that case you can *return* the `Closure` (and leave it up to the caller to remove it).

However, returning the `Closure` is pretty cumbersome, so instead let's create a `Listener` struct which makes things easy:

```rust
struct Listener {
    element: web_sys::EventTarget,
    name: &'static str,
    cb: Closure<Fn()>,
}

impl Listener {
    fn new<F>(element: web_sys::EventTarget, name: &'static str, cb: F) where F: Fn() + 'static {
        let cb = Closure::wrap(Box::new(cb) as Box<Fn()>);

        element.add_event_listener_with_callback(name, cb.as_ref().unchecked_ref()).unwrap();

        Self { element, name, cb }
    }
}

impl Drop for Listener {
    fn drop(&mut self) {
        self.element.remove_event_listener_with_callback(self.name, self.cb.as_ref().unchecked_ref()).unwrap();
    }
}
```

Here I created a `Listener` struct. When you call `Listener::new` it will add the event listener, and when it is dropped it will automatically remove the event listener.

You can use it like this:

```rust
// When listener is dropped it will remove the listener
let listener = Listener::new(main, "click", || {
    web_sys::console::log_1(&"click".into());
});
```

If you don't want the listener to be removed right away, you can return it from the function:

```rust
fn run() -> Listener {
    Listener::new(main, "click", || {
        web_sys::console::log_1(&"click".into());
    })
}
```

This creates the `Listener` inside of the `run()` function, and then transfers ownership to whoever called the `run()` function:

```rust
// When the listener is dropped it will remove the listener
let listener = run();
```

You could also put the `Listener` into a struct (which moves ownership into the struct). This sort of "moving of ownership" is very common in Rust, so it's important to understand it.

It's also possible to move ownership into a closure! Here is an example which adds a listener and then 1000 milliseconds later removes it:

```rust
let listener = Listener::new(main, "click", || {
    web_sys::console::log_1(&"click".into());
});

let callback = move || {
    drop(listener);
};

let cb = Closure::wrap(Box::new(callback) as Box<Fn()>);
web_sys::window().unwrap().set_timeout_with_callback(cb.as_ref().unchecked_ref(), 1000);
cb.forget();
```

Notice the `move` keyword, that causes `listener` to be transferred into the `callback` closure. When the `callback` closure is called, it will then drop the `listener` (which then removes the event listener).

Right now wasm-bindgen has a lot of clunky syntax that makes everything more complicated than it should be. Here's the same example, but with stdweb:

```rust
let listener = main.add_event_listener(|_: ClickEvent| {
    console!(log, "click");
});

set_timeout(move || {
    listener.remove();
}, 1000);
```

There are some plans to make wasm-bindgen easier to use, but we're not there just yet.

**Comment by bokuweb** [comment]
@Pauan Cool 😄 Thanks for your quick and kind response 👍 I'll try it!! Thanks :)

**Comment by JamyGolden** [comment]
I know this is many years later but I'm having this same problem. 

> The purpose of cb.forget() is to keep the closure alive forever (so it will never be removed).

If `cb.forget()` is not run, then rust doesn't pass the closure to javascript and the event is immediately removed by the rust borrow checker - is this correct? If so, since `cb.forget()` must be run, how can I keep ownership `cb` to use for `remove_event_listener_with_callback` since running `cb.forget()` moves `cb` ?

@bokuweb how did you end up solving it?

**Comment by Pauan** [comment]
> @JamyGolden When running in fn main() using the Listener struct above

It's better to use [`gloo_events::EventListener`](https://crates.io/crates/gloo-events), which standardizes and improves the `Listener` struct.

> I get the following the the browser console

Yes, that's because JS is calling the closure *after* the closure has been dropped in Rust.

> If cb.forget() is not run, then rust doesn't pass the closure to javascript and the event is immediately removed by the rust borrow checker since rust runs until the end of fn main()- is this correct?
>
> If so then cb.forget() must be run so it doesn't get immediately cleaned up - perhaps there's some fundamental thing I'm missing.

The closure is always passed to JS. When the `Closure` is dropped, then it will clean up the closure's memory, the same as every other type in Rust. After the closure is dropped, it is an error to call that closure from JS.

In addition to that, the `Listener` struct has special `Drop` behavior which removes the event listener when the `Listener` is dropped. If you don't want that then you'll have to keep it alive in some way.

----

There are many ways to keep things alive in Rust, the simplest is [`std::mem::forget`](https://doc.rust-lang.org/std/mem/fn.forget.html) which permanently leaks memory.

Instead of permanently leaking memory, you can wrap your type in [`ManuallyDrop`](https://doc.rust-lang.org/std/mem/struct.ManuallyDrop.html) which allows you to control when the data is dropped.

----

However, instead of using `std::mem::forget` or `ManuallyDrop`... you most likely want to use [`thread_local`](https://doc.rust-lang.org/std/macro.thread_local.html):

```rust
thread_local! {
    static MY_EVENT: EventListener = EventListener::new(...);
}
```

This creates a global variable that lives forever, so it leaks memory just like `std::mem::forget`.

If you want to clean the memory up, you can wrap it in `RefCell`:

```rust
thread_local! {
    static MY_EVENT: RefCell<Option<EventListener>> = RefCell::new(None);
}
```

Now you can mutate the global variable:

```rust
// Create the event listener
MY_EVENT.with(|event| event.replace(Some(EventListener::new(...))));

// Clean up the existing event listener
MY_EVENT.with(|event| event.replace(None));
```

This is a very common pattern for mutating global variables in Rust.
