### ISSUE TITLE
Regession: 0.2.26 fail to build hello world example

### ISSUE THREAD

**Issue by la10736** [rustwasm/wasm-bindgen#994]
Follow hello world wasm example at https://rustwasm.github.io/book/game-of-life/hello-world.html fail at

```
> wasm-pack build

...
  [7/9] Copying over your README...
  [8/9] wasm-bindgen already installed...
| [9/9] Running WASM-bindgen...
wasm-bindgen failed to execute properly. stderr:

thread 'main' panicked at 'assertion failed: *i != u32::max_value()', crates/gc/src/lib.rs:805:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Change in `Cargo.toml` the `wasm-bindgen` dependency in
```
 wasm-bindgen = "=0.2.25"
```
fix the issue.

**Comment by alexcrichton** [comment]
Egad sorry about this and thanks for the quick report! This should be fixed in https://github.com/rustwasm/wasm-bindgen/pull/995 and I'll publish a new version of wasm-bindgen once it's merged.
